using System;using System.IO;using System.Reflection;using System.Runtime.CompilerServices;
class Program {
 static int n;static void Check(bool value,string label){if(!value)throw new Exception(label);Console.WriteLine("PASS "+label);n++;}
 static void Main(string[] args){string root=Path.GetFullPath(args[0]);AppDomain.CurrentDomain.AssemblyResolve+=(s,e)=>{foreach(string folder in new[]{root,Path.GetFullPath(Path.Combine(root,"../../7DaysToDie_Data/Managed")),Path.GetFullPath(Path.Combine(root,"../0_TFP_Harmony"))}){string p=Path.Combine(folder,new AssemblyName(e.Name).Name+".dll");if(File.Exists(p))return Assembly.LoadFrom(p);}return null;};
 var mod=Assembly.LoadFrom(Path.Combine(root,"RebirthUtils.dll"));var native=Assembly.LoadFrom(Path.GetFullPath(Path.Combine(root,"../../7DaysToDie_Data/Managed/Assembly-CSharp.dll")));var itemType=native.GetType("ItemValue");var statType=native.GetType("ItemValue+Stat");var passive=native.GetType("PassiveEffects");var infoType=native.GetType("DisplayInfoEntry");var formatter=mod.GetType("RebirthItemStatColors");var effect=Enum.Parse(passive,"EntityDamage");var stat=Activator.CreateInstance(statType,new object[]{effect,0,10});var item=RuntimeHelpers.GetUninitializedObject(itemType);var array=Array.CreateInstance(statType,1);array.SetValue(stat,0);itemType.GetProperty("Stats").SetValue(item,array);var info=RuntimeHelpers.GetUninitializedObject(infoType);infoType.GetField("StatType").SetValue(info,effect);var bonus=formatter.GetMethod("WithBonus");var format=formatter.GetMethod("Format");
 string marked=(string)bonus.Invoke(null,new[]{"10",item,info});Check(marked=="[sp=ui_stat]10","native boosted item receives marker without hover");Check((string)bonus.Invoke(null,new[]{marked,item,info})==marked,"marker is not duplicated");Check((string)format.Invoke(null,new[]{marked})=="[FFAF0B][t][sp=ui_game_symbol_star][/t][-]10","bonus star is yellow");var plain=RuntimeHelpers.GetUninitializedObject(itemType);Check((string)bonus.Invoke(null,new[]{"10",plain,info})=="10","next unboosted selection has no stale bonus");Check(((string)format.Invoke(null,new[]{"[sp=ui_stat]-5"})).Contains("[FF0000]-5[-]"),"negative values remain red");var inputEffects=Array.CreateInstance(passive,1);inputEffects.SetValue(effect,0);Check(((string)formatter.GetMethod("MarkDerived").Invoke(null,new object[]{"17.3 (38.9)",item,inputEffects})).StartsWith("[FFAF0B][t][sp=ui_game_symbol_star][/t][-]"),"derived melee DPS preserves the yellow boosted-stat marker");
var farming=mod.GetType("RebirthPhase8WorldOutputTrainingService").GetMethod("IsPlayerCropHarvest",BindingFlags.Static|BindingFlags.NonPublic);
foreach(var crop in new[]{"plantedCorn3Harvest","plantedPotato3Harvest","plantedCorn2","plantedCornDead"})Check(!(bool)farming.Invoke(null,new object[]{crop}),"no farming credit for "+crop);
Check((bool)farming.Invoke(null,new object[]{"plantedCorn3HarvestPlayer"}),"player-grown mature crop eligible");
var evalType=mod.GetType("RebirthCapabilityEvaluation");var evaluation=Activator.CreateInstance(evalType,new object[]{"test","recipe","meal",true,null});var merge=mod.GetType("RebirthCapabilityService").GetMethod("WithReadingRequirement",BindingFlags.Static|BindingFlags.NonPublic);
var unread=merge.Invoke(null,new object[]{evaluation,"literature.read.card",false});Check(!(bool)evalType.GetProperty("IsAllowed").GetValue(unread),"unread card denies crafting even when skill passes");var read=merge.Invoke(null,new object[]{evaluation,"literature.read.card",true});Check((bool)evalType.GetProperty("IsAllowed").GetValue(read),"read card retains satisfied skill admission");Check(((System.Collections.ICollection)evalType.GetProperty("Requirements").GetValue(read)).Count==1,"reading requirement remains displayed after reading");var marker=(Func<string,string>)Delegate.CreateDelegate(typeof(Func<string,string>),mod.GetType("RebirthLiteratureService").GetMethod("RecipeReadMarker"));
Check(marker(null)=="" && marker("")=="","empty marker behavior preserved");
Check(marker("Axes")=="literature.recipe_read.Axes" && marker("axes")=="literature.recipe_read.axes","marker case and serialized ID preserved");
string cachedMarker=marker("Axes");long allocated=GC.GetAllocatedBytesForCurrentThread();for(int i=0;i<10000;i++)if(!ReferenceEquals(cachedMarker,marker("Axes")))throw new Exception("marker not reused");
Check(GC.GetAllocatedBytesForCurrentThread()==allocated,"10000 cached marker lookups allocate zero bytes");
for(int i=0;i<5000;i++)marker("external"+i);Check(marker("Axes")==cachedMarker,"bounded cache eviction preserves result");Console.WriteLine(n+" checks passed against compiled DLL and native ItemValue");}
}