#!/usr/bin/env python3
from pathlib import Path
import sys, xml.etree.ElementTree as ET
root=Path(sys.argv[1]) if len(sys.argv)>1 else Path('.')
checks=[]
def ck(name, cond):
    cond=bool(cond); checks.append((name,cond)); print(('PASS' if cond else 'FAIL')+': '+name)
q=(root/'Scripts/Crafting/UI/PersonalCrafting/XUiC_RebirthCraftingQueue.cs').read_text(encoding='utf-8')
e=(root/'Scripts/Crafting/UI/PersonalCrafting/XUiC_RebirthCraftingQueueEntry.cs').read_text(encoding='utf-8')
t=(root/'Config/XUi_InGame/templates.xml').read_text(encoding='utf-8')
w=(root/'Config/XUi_InGame/windows.xml').read_text(encoding='utf-8')
ET.parse(root/'Config/XUi_InGame/templates.xml'); ET.parse(root/'Config/XUi_InGame/windows.xml')
ck('50 queue capacity retained', 'MaximumQueueEntries = 50' in q)
ck('queue active count written directly to live label', 'UpdateCapacityLabelDirect();' in q and 'label.Text = text;' in q)
ck('queue direct label refreshed every update', 'ApplyPresentation(false);\n        UpdateCapacityLabelDirect();' in q and 'TraceQueueState("update", false);\n        // Reassert' in q)
ck('queue trace records rendered label text', 'label=\\\"' in q)
ck('queue header label no longer has stale binding source', 'name="rebirthCraftingQueueCapacity"' in w and 'text=""' in w[w.find('name="rebirthCraftingQueueCapacity"'):w.find('name="rebirthCraftingQueueCapacity"')+220])
ck('queue cards cannot render partially outside viewport', 'top >= -0.01f && bottom <= viewportHeight + 0.01f' in q)
ck('queue native-compatible rect host retained', '<rect name="rebirthCraftingQueueRowsHost"' in w and '<panel name="rebirthCraftingQueueRowsHost"' not in w)
ck('queue custom track is standard 16px', 'ScrollbarTrackWidth = 16' in q and 'name="rebirthCraftingQueueScrollTrack"' in w and 'width="16"' in w[w.find('name="rebirthCraftingQueueScrollTrack"'):w.find('name="rebirthCraftingQueueScrollTrack"')+220])
ck('queue custom thumb is standard 12px', 'ScrollbarThumbWidth = 12' in q and 'name="rebirthCraftingQueueScrollThumb"' in w and 'width="12"' in w[w.find('name="rebirthCraftingQueueScrollThumb"'):w.find('name="rebirthCraftingQueueScrollThumb"')+220])
ck('queue reasserts standard scrollbar geometry', 'SetRect(scrollTrack, trackX, trackY, ScrollbarTrackWidth, viewportHeight)' in q and 'ScrollbarThumbWidth' in q)
ck('recipe scrollbar remains standard 16/12', 'name="rebirthCraftingRecipeScrollTrack"' in w and 'name="rebirthCraftingRecipeScrollThumb"' in w and 'width="16"' in w[w.find('name="rebirthCraftingRecipeScrollTrack"'):w.find('name="rebirthCraftingRecipeScrollTrack"')+220] and 'width="12"' in w[w.find('name="rebirthCraftingRecipeScrollThumb"'):w.find('name="rebirthCraftingRecipeScrollThumb"')+220])
ck('inventory scrollbar remains standard 16/12', 'name="rebirthCraftingInventoryScrollTrack"' in w and 'name="rebirthCraftingInventoryScrollThumb"' in w and 'width="16"' in w[w.find('name="rebirthCraftingInventoryScrollTrack"'):w.find('name="rebirthCraftingInventoryScrollTrack"')+220] and 'width="12"' in w[w.find('name="rebirthCraftingInventoryScrollThumb"'):w.find('name="rebirthCraftingInventoryScrollThumb"')+220])
ck('queue index label lowered for vertical centering', 'SetRect(GetChildById("rebirthQueueIndex"), indexX, -11, indexSize, 22);' in e and 'name="rebirthQueueIndex" pos="191,-11"' in t)
ck('native queue cancel child names retained', 'name="background"' in t and 'name="cancel"' in t and 'XUiC_RebirthCraftingQueueEntry : XUiC_RecipeStack' in e)
ck('cancel hit target is visibly red', 'new Color32(116, 28, 31, 235)' in e and 'color="116,28,31,235"' in t)
ck('cancel x is white and drawn above hit target', 'new Color32(255, 255, 255, 255)' in e and 'depth="10" name="cancel"' in t and 'color="255,255,255,255"' in t)
ck('cancel hit target remains press-enabled', 'name="background"' in t and 'on_press="true"' in t[t.find('name="background" pos="195,-34"'):t.find('name="background" pos="195,-34"')+420])
ck('native queue base update retained', 'base.Update(dt);' in e and 'base.Update(dt);' in q)
ck('queue braces balanced', q.count('{')==q.count('}'))
ck('entry braces balanced', e.count('{')==e.count('}'))
passed=sum(v for _,v in checks)
print(f'RESULT: {passed}/{len(checks)} PASS')
sys.exit(0 if passed==len(checks) else 1)
