from pathlib import Path
import sys, xml.etree.ElementTree as ET
root=Path(sys.argv[1]) if len(sys.argv)>1 else Path('.')
xml=(root/'Config/XUi_InGame/windows.xml').read_text(encoding='utf-8')
layout=(root/'Scripts/Crafting/UI/PersonalCrafting/RebirthPersonalCraftingLayoutService.cs').read_text(encoding='utf-8')
cat=(root/'Scripts/Crafting/UI/PersonalCrafting/XUiC_RebirthCraftingRecipeCatalogue.cs').read_text(encoding='utf-8')
entry=(root/'Scripts/Crafting/UI/PersonalCrafting/XUiC_RebirthCraftingRecipeEntry.cs').read_text(encoding='utf-8')
checks=[]
def ck(n,c): checks.append((n,bool(c)))
ET.parse(root/'Config/XUi_InGame/windows.xml')
ck('inventory viewport restored to foreground depth', 'name="rebirthCraftingInventoryViewport" depth="20"' in xml)
ck('inventory ItemStack uses stock sizing contract', '<item_stack name="0" controller="RebirthCraftingInventorySlot, RebirthUtils"/>' in xml and 'cell_size="64" controller="RebirthCraftingInventorySlot' not in xml)
ck('wide inventory uses thirteen proportional columns after PC101 supersession', 'name="inventory" rows="8" cols="13"' in xml)
ck('inventory stats beside title and enlarged', 'name="rebirthCraftingInventoryCapacity"' in xml and 'pos="154,-8"' in xml and 'font_size="19"' in xml and 'upper_case="true"' in xml)
ck('layout keeps inventory stats beside title', 'int capacityX = 154;' in layout and '"rebirthCraftingInventoryCapacity"), capacityX, -8' in layout)
ck('recipe catalogue has ten visible rows', 'public const int VisibleRowCount = 10;' in cat and 'PresentationRowCount = VisibleRowCount + 1' in cat)
ck('eleventh recipe buffer authored', 'name="rebirthCraftingRecipeRow10"' in xml and 'rebirthCraftingRecipeRowHit10' in xml)
ck('recipe viewport enlarged', 'name="rebirthCraftingRecipeViewport"' in xml and 'height="398"' in xml)
ck('recipe category matches name font', xml.count('name="rebirthCraftingRecipeCategory"') >= 11 and xml.count('name="rebirthCraftingRecipeCategory" depth="5" pos="48,-19" width="158" height="19" font_size="16"') >= 11)
ck('recipe categories uppercase in controller', 'categoryDisplayName ?? string.Empty).ToUpperInvariant()' in entry)
ck('recipe status font enlarged', 'statusLabel.FontSize = 14;' in entry)
ck('lock icon shifted right with gap', 'width - 41' in entry)
ck('middle category matches item name size', 'name="rebirthCraftingSelectedRecipeType"' in xml and 'font_size="22"' in xml and 'upper_case="true"' in xml)
ck('middle description enlarged', 'name="rebirthCraftingSelectedRecipeDescription"' in xml and 'font_size="18"' in xml)
ck('knowledge title enlarged to craft-time size', 'name="rebirthCraftingKnowledgeTitle"' in xml and 'font_size="20"' in xml)
ck('knowledge description enlarged', 'name="rebirthCraftingSelectedRecipeKnowledge"' in xml and 'font_size="16"' in xml)
ck('craft time title enlarged', 'name="rebirthCraftingSelectedRecipeTimeTitle"' in xml and 'font_size="20"' in xml)
ck('batch size title enlarged', 'name="rebirthCraftingBatchTitle"' in xml and 'font_size="20"' in xml)
ck('craft time value aligns to batch input left edge', 'name="rebirthCraftingSelectedRecipeTimeValue"' in xml and 'pos="571,-150"' in xml and 'justify="left"' in xml and 'name="count_input"' in xml and 'pos="20,-2"' in xml)
ck('requirement name font enlarged', xml.count('name="rebirthCraftingRequirementName"') >= 6 and xml.count('font_size="17" color="240,240,242,255"') >= 6)
ck('requirement HAVE and NEED match name font/case', xml.count('name="rebirthCraftingRequirementHaveLabel"') >= 6 and xml.count('name="rebirthCraftingRequirementHaveValue"') >= 6 and xml.count('name="rebirthCraftingRequirementNeedLabel"') >= 6 and xml.count('name="rebirthCraftingRequirementNeedValue"') >= 6)
ck('expected outcome metric titles enlarged', 'name="rebirthCraftingOutcomeStatusTitle"' in xml and 'font_size="16"' in xml and 'name="rebirthCraftingOutcomeQualityTitle"' in xml and 'name="rebirthCraftingOutcomeXpTitle"' in xml)
ck('expected outcome result title larger than values', 'name="rebirthCraftingOutcomeResultsTitle"' in xml and 'font_size="18"' in xml and 'name="rebirthCraftingOutcomeResultsValue"' in xml and 'font_size="16"' in xml)
ck('expected outcome explanation enlarged', 'name="rebirthCraftingOutcomeExplanation"' in xml and 'font_size="15"' in xml)
failed=[n for n,c in checks if not c]
for n,c in checks: print(('PASS ' if c else 'FAIL ')+n)
print(f'PC099 personal crafting readability/inventory render recovery: {len(checks)-len(failed)} PASS / {len(failed)} FAIL')
sys.exit(1 if failed else 0)
