using System;
public class RebirthNpcPersistentRecord {public uint AggregateRevision=1;public string AggregateChecksum="fixture-checksum";public RebirthNpcIdentityRecord Identity;public RebirthNpcProfileBindingRecord Profile;public RebirthNpcPresenceRecord Presence;internal RebirthNpcNativeReconstruction NativeReconstruction;public RebirthNpcControllerFragmentSet ControllerFragments;public RebirthNpcVitalStateRecord Vitals=new RebirthNpcVitalStateRecord();}
public class RebirthNpcIdentityRecord{public RebirthNpcStableId StableNpcId;}
public class RebirthNpcProfileBindingRecord{public string ProfileId;}
public class RebirthNpcPresenceRecord{public uint EmbodimentGeneration;}
public class ItemClass{public ItemAction[] Actions=new ItemAction[0];public bool Holdable;public bool CanHold()=>Holdable;public string GetItemName()=>"fixture";}
public class ItemValue{public ItemClass ItemClass=new ItemClass();public bool IsEmpty()=>false;public ItemValue Clone()=>this;}
public class ItemStack{public bool IsEmpty()=>count<=0||itemValue==null||itemValue.IsEmpty();public int count;public ItemValue itemValue;public ItemStack(ItemValue value,int count){itemValue=value;this.count=count;}}
public static class RebirthNativeItemCodec{public static ItemClass DecodedClass;public static string Encode(ItemValue v)=>"AQ==";public static bool TryDecode(string p,out ItemValue v){v=new ItemValue();if(DecodedClass!=null)v.ItemClass=DecodedClass;return true;}}
public class RebirthNpcControllerFragmentSet{public int FragmentCount;public RebirthNpcControllerFragment[] Fragments;}
public class RebirthNpcControllerFragment{public string ControllerTypeId;public int FragmentVersion;public int FragmentLength;public string FragmentChecksum;public byte[] Bytes;public bool Required;}
public class Entity{public int entityId;public bool enabled=true;public UnityEngine.Transform RootTransform=new UnityEngine.Transform();public UnityEngine.Transform transform=>RootTransform;public CharacterControllerAbstract m_characterController;}
public class World{public bool Remote;public EntityRebirthHumanoidNPC Actor;public PlayerList Players=new PlayerList();public System.Collections.Generic.Dictionary<int,Entity> Entities=new System.Collections.Generic.Dictionary<int,Entity>();public bool IsRemote()=>Remote;public Entity GetEntity(int id)=>Entities.TryGetValue(id,out var entry)?entry:Actor;}
public partial class RebirthNpcRuntimeState{public RebirthNpcStableId StableId;public string ProfileId;public uint Revision;public bool PreparedRestorationPending,HasGuardPosition,HasHumanAppearance,Dirty;public byte Presence,OwnershipKind,Order,Travel;public string OwnerId;public object GuardPosition,HumanAppearance;public RebirthNpcRuntimeState(){}public RebirthNpcRuntimeState(RebirthNpcStableId id,string profile){StableId=id;ProfileId=profile;}}
public enum StreamModeWrite{Persistency}
public class EntityCreationData{public const int FileVersion=38;}
public class ItemGrid{public ItemStack[] Items=new ItemStack[1];public int Length=>Items.Length;public ItemStack this[int i]=>Items[i];}
public class NativeState{public int FocusedSlot;public int SelectedSlot=>FocusedSlot;public int SlotCount=>ItemGrid.Length;public ItemGrid ItemGrid=new ItemGrid();public virtual void Write(PooledBinaryWriter w,StreamModeWrite m){w.Write((byte)1);}}
public class EntityStats{public object Stamina,Food,Water;public int waitTicks,netSyncWaitTicks;public float m_amountEnclosed,buffDamageRemainder;public void Write(PooledBinaryWriter w){w.Write((byte)1);}}
public class Buffs{public void Write(PooledBinaryWriter w,bool n){w.Write((byte)1);}}
public class BodyDamage{public int StunKnee,StunProne;public float StunDuration;public EnumEntityStunType CurrentStun;public EnumBodyPartHit bodyPartHit;public bool ShouldBeCrawler;public void Write(PooledBinaryWriter w){w.Write((byte)1);}}
public class EntityRebirthNPC:Entity{public RebirthNpcRuntimeState RebirthRuntimeState;}
public class EntityRebirthHumanoidNPC:EntityRebirthNPC{public EntityRebirthHumanoidNPC(){ModelTransform=PhysicsTransform=physicsRBT=RootTransform;emodel.headTransform=RootTransform;emodel.avatarController.RightHand=RootTransform;Hand.entity=this;Hand.bareHandData.holdingEntity=Hand.transientData.holdingEntity=this;}public UnityEngine.Transform ModelTransform,PhysicsTransform,physicsRBT;public EModelBase emodel=new EModelBase();public float physicsBaseHeight=1,physicsHeight=1,physicsHeightScale=1,physicsColliderLowerY;public bool IsPreparedRestorationPending=true;public bool hasAI=true,AimingGun;public Hand Hand=new Hand();public int belongsPlayerId=-1,spawnById=-1,clientEntityId,teamNumber,lastSleeperPose;public float lifetime=-1,OverrideSize=1,OverrideHeadSize=1;public EModelBase.HeadStates currentHeadState;public bool onGround,IsSleeper,IsSleeperPassive,IsSleeping,isDancing,spawnByAllowShare;public string entityName="Fixture NPC",spawnByName="";public Coordinates Home=new Coordinates();public int DeathTime,HomeRange=-1;public int GetDeathTime()=>DeathTime;public void SetDeathTime(int value){DeathTime=value;}public Coordinates getHomePosition()=>Home;public int getMaximumHomeDistance()=>HomeRange;public void setHomeArea(Vector3i pos,int range){Home.position=pos;HomeRange=range;}public World world=new World();public EntityStats Stats=new EntityStats();public Buffs Buffs=new Buffs();public BodyDamage bodyDamage=new BodyDamage();public NativeState inventory=new NativeState(),equipment=new NativeState(),bag=new NativeState();public bool Dead,Overflow;public int Health=80;public int GetMaxHealth()=>100;public bool IsDead()=>Dead;public void Write(PooledBinaryWriter w,StreamModeWrite m){if(Overflow)w.Write(new byte[1048577]);else w.Write((byte)1);}}
public class PooledBinaryWriter:System.IO.BinaryWriter{public PooledBinaryWriter():base(new System.IO.MemoryStream()){}public void SetBaseStream(System.IO.Stream s){OutStream=s;}protected override void Dispose(bool d){Flush();}}
public class WriterPool{public PooledBinaryWriter AllocSync(bool _bReset)=>new PooledBinaryWriter();}
public static class MemoryPools{public static WriterPool poolBinaryWriter=new WriterPool();}
public class GameManager{public static GameManager Instance=new GameManager();public World World;}
public static class RebirthNpcRuntimeRegistry{public static bool TryGetEntityId(RebirthNpcStableId id,out int entity){entity=7;return true;}}
public class RebirthNpcVitalStateRecord{public int CurrentHealth,MaximumHealthAtSave;public string DeathOrIncapacitationState;public uint VitalsRevision;}
public static class RebirthNpcInventoryTransactionService{internal static RebirthNpcNativeStackSet Custody;internal static uint Revision;internal static bool TryGetExistingNativeCustody(RebirthNpcStableId id,out RebirthNpcNativeStackSet custody,out uint revision){custody=Custody;revision=Revision;return custody!=null;}}
class NativeGateCallbacks{public bool hasAI=true,AimingGun;public int EntityTicks,LiveTicks;public virtual void OnUpdateEntity(){EntityTicks++;}public virtual void OnUpdateLive(){LiveTicks++;}}
public enum EnumEntityStunType{None=0,Prone=1}
public enum EnumBodyPartHit{None=0,Head=1}
public class EModelBase{public FixtureAvatar avatarController=new FixtureAvatar();public UnityEngine.Transform headTransform;public HeadStates HeadState;public float HeadStandardSize=1,HeadBigSize=3;public enum HeadStates{Normal=0,Missing=1}}
public struct Vector3i{public int x,y,z;public Vector3i(int x,int y,int z){this.x=x;this.y=y;this.z=z;}}
public class Coordinates{public Vector3i position;}
public class EntityPlayer:Entity{public string Canonical;}
public class PlayerList{public System.Collections.Generic.List<EntityPlayer> list=new System.Collections.Generic.List<EntityPlayer>();}
public class RebirthStablePlayerIdentity{public string CanonicalId;public static bool TryResolveServerEntity(EntityPlayer player,out RebirthStablePlayerIdentity id){id=string.IsNullOrEmpty(player.Canonical)?null:new RebirthStablePlayerIdentity{CanonicalId=player.Canonical};return id!=null;}}
namespace UnityEngine {
public class GameObject{public bool activeSelf=true;public void SetActive(bool value){activeSelf=value;}}
public class Transform{public Vector3 localPosition,localScale=new Vector3(1,1,1);public Quaternion localRotation=Quaternion.identity;public Transform parent=>Parent;public System.Collections.Generic.List<Transform> Children=new System.Collections.Generic.List<Transform>();public int childCount=>Children.Count;public Transform GetChild(int i)=>Children[i];public int GetSiblingIndex()=>Parent==null?0:Parent.Children.IndexOf(this);public T[] GetComponents<T>()=>System.Linq.Enumerable.ToArray(System.Linq.Enumerable.OfType<T>(Components));public Transform Parent;public bool IsChildOf(Transform root){for(var node=Parent;node!=null;node=node.Parent)if(ReferenceEquals(node,root))return true;return false;}public GameObject gameObject=new GameObject();public System.Collections.Generic.List<object> Components=new System.Collections.Generic.List<object>();public T[] GetComponentsInChildren<T>(bool inactive){foreach(var item in Components){if(item is Collider c&&c.transform==null)c.transform=this;if(item is Rigidbody r&&r.transform==null)r.transform=this;}var result=new System.Collections.Generic.List<T>(System.Linq.Enumerable.OfType<T>(Components));foreach(var child in Children)result.AddRange(child.GetComponentsInChildren<T>(inactive));return result.ToArray();}}
public class Collider{public Transform transform;private bool current=true;public bool ThrowOnce,IgnoreEnableTrue;public bool enabled{get=>current;set{if(IgnoreEnableTrue&&value)return;current=value;if(ThrowOnce){ThrowOnce=false;throw new System.InvalidOperationException("injected collider callback failure");}}}}
public enum RigidbodyInterpolation{None,Interpolate,Extrapolate}public enum CollisionDetectionMode{Discrete,Continuous,ContinuousDynamic,ContinuousSpeculative}public enum RigidbodyConstraints{None=0,FreezePositionX=2,FreezeRotation=112}public class Rigidbody{public float mass=1,drag,angularDrag;public bool useGravity=true;public RigidbodyConstraints constraints;public RigidbodyInterpolation interpolation;public CollisionDetectionMode collisionDetectionMode;public Vector3 velocity,angularVelocity;public Transform transform;public bool isKinematic,detectCollisions=true;}
public class CharacterController:Collider{public Vector3 center;public float height=2,radius=0.5f,stepOffset=0.2f,skinWidth=0.01f,slopeLimit=45,minMoveDistance;public bool detectCollisions=true,enableOverlapRecovery=true;}
}
public abstract class CharacterControllerAbstract{public UnityEngine.Vector3 Center;public float Height=1,Radius=0.5f,Step=0.1f,Skin=0.01f;public virtual UnityEngine.Vector3 GetCenter()=>Center;public virtual float GetHeight()=>Height;public virtual float GetRadius()=>Radius;public virtual float GetStepOffset()=>Step;public virtual float GetSkinWidth()=>Skin;public virtual void SetSize(UnityEngine.Vector3 c,float h,float r){Center=c;Height=h;Radius=r;}public virtual void SetStepOffset(float s){Step=s;}public virtual void SetSkinWidth(float s){Skin=s;}public abstract void Enable(bool value);}
public class CharacterControllerUnity:CharacterControllerAbstract{public UnityEngine.CharacterController cc=new UnityEngine.CharacterController();public override void Enable(bool value){cc.enabled=value;}}
public class FixtureMotor{public UnityEngine.Transform transform;public bool enabled=true;}
public class CharacterControllerKinematic:CharacterControllerAbstract{public FixtureMotor motor=new FixtureMotor();public override void Enable(bool value){motor.enabled=value;}}
namespace UnityEngine {
public struct Vector3{public float x,y,z;public static Vector3 zero=>new Vector3();public Vector3(float x,float y,float z){this.x=x;this.y=y;this.z=z;}}
public struct Quaternion{public float x,y,z,w;public Quaternion(float x,float y,float z,float w){this.x=x;this.y=y;this.z=z;this.w=w;}public static Quaternion identity=>new Quaternion(0,0,0,1);}
public class CapsuleCollider:Collider{public Vector3 center;public float height=1,radius=0.5f;public int direction=1;}
public class BoxCollider:Collider{public Vector3 center,size=new Vector3(1,1,1);}
public class SphereCollider:Collider{public Vector3 center;public float radius=0.5f;}
}
