using System;using System.IO;using System.Xml.Linq;
static class NativePreflightFixture{
static byte[] Bytes(Action<BinaryWriter> action){using(var m=new MemoryStream()){using(var w=new BinaryWriter(m,System.Text.Encoding.UTF8,true))action(w);return m.ToArray();}}
static XElement Blob(string name,byte[] b)=>new XElement(name,new XAttribute("payload",Convert.ToBase64String(b)),new XAttribute("sha256",RebirthNpcNativeReconstruction.Digest(b)));
static byte[] Item()=>Bytes(w=>{w.Write((byte)9);w.Write((byte)0);w.Write((ushort)42);w.Write(1f);w.Write((ushort)2);w.Write((ushort)0);w.Write((byte)0);w.Write((byte)0);w.Write((byte)0);w.Write((byte)0);w.Write((byte)0);w.Write((ushort)1);w.Write(false);});
static void Grid(BinaryWriter w,int count,bool occupied){w.Write((ushort)2);w.Write(count);w.Write(1);w.Write((short)count);for(int i=0;i<count;i++){w.Write((ushort)(occupied&&i==0?2:0));if(occupied&&i==0)w.Write(Item());}w.Write(false);w.Write(false);w.Write(0ul);w.Write(false);}
internal static XElement Valid(){var id=new RebirthNpcStableId(1,1);byte[] item=Item();var n=new XElement("nativeReconstruction",new XAttribute("version",1),new XAttribute("required",1),new XAttribute("nativeVersion",38),new XAttribute("owner",id),new XAttribute("profile","specialist.medic"),new XAttribute("generation",1),new XAttribute("inventoryRevision",3),new XAttribute("assembly",new string('a',64)),new XAttribute("complete",1));
n.Add(Blob("actor",Bytes(w=>{w.Write((byte)0);w.Write(1ul);w.Write(0);w.Write(0f);})),Blob("bodyDamage",Bytes(w=>{w.Write(4);w.Write(0);w.Write(0u);})),Blob("stats",Bytes(w=>{w.Write(11);w.Write(6);w.Write(80f);w.Write(0f);w.Write(100f);w.Write(100f);w.Write(80f);})),Blob("buffs",Bytes(w=>{w.Write((byte)3);w.Write((ushort)0);w.Write((ushort)0);})),Blob("toolbelt",Bytes(w=>{w.Write((byte)1);Grid(w,1,true);w.Write((byte)0);})),Blob("equipment",Bytes(w=>{w.Write((byte)6);Grid(w,13,false);for(int i=0;i<13;i++)w.Write(0);w.Write(0);})),Blob("bag",Bytes(w=>{w.Write((byte)2);Grid(w,1,false);})),new XElement("slots",new XElement("slot",new XAttribute("area","toolbelt"),new XAttribute("index",0),new XAttribute("stack",new Guid("22222222-2222-2222-2222-222222222222").ToString("N")),new XAttribute("count",2),new XAttribute("payload",Convert.ToBase64String(item)),new XAttribute("sha256",RebirthNpcNativeReconstruction.Digest(item)))),new XElement("controllers"));return n;}
static bool Preflight(XElement n){if(!RebirthNpcNativeReconstruction.TryRead(n,out var d))throw new Exception("fixture component shape");return RebirthNpcNativeReconstructionPreflight.TryValidate(d,100000,7,b=>b==0,id=>id==42?(bool?)false:null,id=>false);}
internal static int Run(){int n=0;Action<bool,string> check=(b,label)=>{if(!b)throw new Exception(label);n++;};check(Preflight(Valid()),"current native layout preflight");
foreach(var name in new[]{"actor","bodyDamage","stats","buffs","toolbelt","equipment","bag"}){var root=Valid();byte[] old=Convert.FromBase64String((string)root.Element(name).Attribute("payload"));byte[] extra=new byte[old.Length+1];Array.Copy(old,extra,old.Length);root.Element(name).ReplaceWith(Blob(name,extra));check(!Preflight(root),"trailing native bytes "+name);}
var bad=Valid();bad.Element("buffs").ReplaceWith(Blob("buffs",Bytes(w=>{w.Write((byte)3);w.Write((ushort)129);})));check(!Preflight(bad),"excess buffs before native read");bad=Valid();bad.Element("buffs").ReplaceWith(Blob("buffs",Bytes(w=>{w.Write((byte)3);w.Write((ushort)1);w.Write(new byte[]{255,255,255,255,7});})));check(!Preflight(bad),"string size before allocation");bad=Valid();bad.Element("equipment").ReplaceWith(Blob("equipment",Bytes(w=>{w.Write((byte)6);Grid(w,13,false);for(int i=0;i<13;i++)w.Write(0);w.Write(int.MaxValue);})));check(!Preflight(bad),"cosmetics count before allocation");bad=Valid();bad.Element("toolbelt").ReplaceWith(Blob("toolbelt",Bytes(w=>{w.Write((byte)1);w.Write((ushort)2);w.Write(4097);w.Write(1);w.Write((short)4097);})));check(!Preflight(bad),"slot count before native resize");bad=Valid();bad.Element("slots").Element("slot").SetAttributeValue("count",1);check(!Preflight(bad),"slot count disagrees custody proof");return n;}}
