using System;using System.Linq;using System.Xml;using System.Xml.Linq;
static class Program{
static int checks;static void Check(bool b,string name){if(!b)throw new Exception(name);checks++;}
static string payload="AQ==",hash=RebirthNpcNativeReconstruction.Digest(new byte[]{1});
static RebirthNpcStableId owner=new RebirthNpcStableId(1,1);
static Guid stackId=Guid.Parse("22222222-2222-2222-2222-222222222222");
static XElement Valid(){return new XElement("nativeReconstruction",new XAttribute("version",1),new XAttribute("required",1),new XAttribute("nativeVersion",38),new XAttribute("owner",owner),new XAttribute("profile","specialist.medic"),new XAttribute("generation",1),new XAttribute("inventoryRevision",3),new XAttribute("assembly",new string('a',64)),new XAttribute("complete",1),new[]{"actor","bodyDamage","stats","buffs","toolbelt","equipment","bag"}.Select(n=>new XElement(n,new XAttribute("payload",payload),new XAttribute("sha256",hash))),new XElement("slots",Slot()),new XElement("controllers"));}
internal static XElement HeaderMigrationRoot()=>Valid();
static XElement Slot()=>new XElement("slot",new XAttribute("area","toolbelt"),new XAttribute("index",0),new XAttribute("stack",stackId.ToString("N")),new XAttribute("count",2),new XAttribute("payload",payload),new XAttribute("sha256",hash));
static void Main(){Check(RebirthNpcNativeReconstruction.TryRead(Valid(),out var d),"valid");var edit=d.Write();edit.SetAttributeValue("profile","other");Check(d.Profile=="specialist.medic","immutable");
foreach(var key in Valid().Attributes().Select(a=>a.Name).ToArray()){var n=Valid();n.Attribute(key).Remove();Check(!RebirthNpcNativeReconstruction.TryRead(n,out _),"missing"+key);}
foreach(var key in new[]{"version","required","nativeVersion","complete"}){var n=Valid();n.SetAttributeValue(key,"99");Check(!RebirthNpcNativeReconstruction.TryRead(n,out _),"unknown"+key);}
foreach(var name in new[]{"actor","bodyDamage","stats","buffs","toolbelt","equipment","bag","slots","controllers"}){var n=Valid();n.Add(new XElement(n.Element(name)));Check(!RebirthNpcNativeReconstruction.TryRead(n,out _),"duplicate"+name);}
foreach(var name in new[]{"actor","bodyDamage","stats","buffs","toolbelt","equipment","bag"}){var n=Valid();n.Element(name).SetAttributeValue("sha256",new string('b',64));Check(!RebirthNpcNativeReconstruction.TryRead(n,out _),"hash"+name);}
var dup=Valid();dup.Element("slots").Add(Slot());Check(!RebirthNpcNativeReconstruction.TryRead(dup,out _),"duplicate slot");dup=Valid();var second=Slot();second.SetAttributeValue("index",1);dup.Element("slots").Add(second);Check(!RebirthNpcNativeReconstruction.TryRead(dup,out _),"duplicate custody projection");
var stackNode=new XElement("nativeStack",new XAttribute("version",1),new XAttribute("id",stackId.ToString("N")),new XAttribute("owner",owner),new XAttribute("item","fixture"),new XAttribute("count",2),new XAttribute("payload",payload));Check(RebirthNpcNativeStackRecord.TryRead(stackNode,out var record),"actual stack codec");Check(RebirthNpcNativeStackSet.TryCreate(owner,3,new[]{record},out var set),"actual custody codec");Check(d.TryValidateCustody(set),"exact custody");Check(!d.TryValidateCustody(set.WithRevision(4)),"wrong revision");Check(!d.TryValidateCustody(null),"missing custody");
var xml=new XmlDocument();xml.LoadXml("<npc/>");Check(RebirthNpcNativeReconstruction.TryReadAggregate(xml.DocumentElement,out var missing)&&missing==null,"legacy missing");xml.DocumentElement.AppendChild(d.WriteAggregate(xml));Check(RebirthNpcNativeReconstruction.TryReadAggregate(xml.DocumentElement,out var saved)&&saved.Owner==d.Owner,"aggregate helper roundtrip");xml.DocumentElement.AppendChild(d.WriteAggregate(xml));Check(!RebirthNpcNativeReconstruction.TryReadAggregate(xml.DocumentElement,out _),"duplicate aggregate");
Check(d.TryValidateControllers(null,null),"empty controller set");
var withController=Valid();withController.Element("controllers").Add(new XElement("fragment",new XAttribute("type","fixture.controller"),new XAttribute("version",1),new XAttribute("required",1),new XAttribute("payload",payload),new XAttribute("sha256",hash)));Check(RebirthNpcNativeReconstruction.TryRead(withController,out var controllerState),"controller codec");
var fragmentSet=new RebirthNpcControllerFragmentSet{FragmentCount=1,Fragments=new[]{new RebirthNpcControllerFragment{ControllerTypeId="fixture.controller",FragmentVersion=1,FragmentLength=1,Bytes=new byte[]{1},FragmentChecksum=hash,Required=true}}};
Check(!controllerState.TryValidateControllers(fragmentSet,null),"required unknown handler fails");Check(controllerState.TryValidateControllers(fragmentSet,(id,v)=>id=="fixture.controller"&&v==1),"exact qualified handler");fragmentSet.Fragments[0].Bytes[0]=2;Check(!controllerState.TryValidateControllers(fragmentSet,(id,v)=>true),"changed controller bytes");
var person=new RebirthNpcPersistentRecord{Identity=new RebirthNpcIdentityRecord{StableNpcId=owner},Profile=new RebirthNpcProfileBindingRecord{ProfileId="specialist.medic"},Presence=new RebirthNpcPresenceRecord{EmbodimentGeneration=1}};
var actor=new EntityRebirthHumanoidNPC{RebirthRuntimeState=new RebirthNpcRuntimeState{StableId=owner,ProfileId="specialist.medic"}};actor.inventory.ItemGrid.Items[0]=new ItemStack(new ItemValue(),2);GameManager.Instance.World=actor.world;
Check(RebirthNpcNativeReconstructionCapture.TryCapture(actor,person,set,null,out var captured,out _),"actual capture source with native API doubles");Check(captured.TryValidateCustody(set)&&captured.Matches(person),"capture binding");actor.Overflow=true;Check(!RebirthNpcNativeReconstructionCapture.TryCapture(actor,person,set,null,out _,out _),"preallocation bound refusal");actor.Overflow=false;actor.world.Remote=true;Check(!RebirthNpcNativeReconstructionCapture.TryCapture(actor,person,set,null,out _,out _),"client capture refusal");actor.world.Remote=false;actor.Dead=true;Check(!RebirthNpcNativeReconstructionCapture.TryCapture(actor,person,set,null,out _,out _),"dead capture refusal");actor.Dead=false;Check(!RebirthNpcNativeReconstructionCapture.TryCapture(actor,person,null,null,out _,out _),"no custody grant");
actor.world.Actor=actor;GameManager.Instance.World=actor.world;RebirthNpcInventoryTransactionService.Custody=set;RebirthNpcInventoryTransactionService.Revision=3;
Check(RebirthNpcNativeReconstructionCapture.TryCaptureCheckpoint(actor.RebirthRuntimeState,person),"actual checkpoint helper");Check(person.NativeReconstruction!=null&&person.Vitals.CurrentHealth==80,"checkpoint evidence and actual health");RebirthNpcInventoryTransactionService.Custody=null;RebirthNpcInventoryTransactionService.Revision=0;Check(!RebirthNpcNativeReconstructionCapture.TryCaptureCheckpoint(actor.RebirthRuntimeState,person)&&person.NativeReconstruction==null,"changed active evidence invalidated");
var gate=new FoundationGateHarness();gate.OnUpdateEntity();gate.OnUpdateLive();Check(gate.EntityTicks==1&&gate.LiveTicks==1&&gate.hasAI,"ordinary actual callbacks");gate.Prepare(true);gate.OnUpdateEntity();gate.OnUpdateLive();Check(gate.EntityTicks==1&&gate.LiveTicks==1&&!gate.hasAI,"prepared actual callbacks suppressed");
actor.RebirthRuntimeState.PreparedRestorationPending=true;Check(actor.RebirthRuntimeState.CloneForProjection().PreparedRestorationPending,"actual clone retains transient hold");
checks+=RigidbodyStateFixture.Run();checks+=BodyPolicyIntegrationFixture.Run();checks+=BodyPolicyFixture.Run();checks+=IdleHandQualificationFixture.Run();checks+=DerivedHandRetirementFixture.Run();checks+=HandMaterializationFixture.Run();checks+=NativeHandFixture.Run();checks+=NativeGeometryFixture.Run();checks+=EventGateDoubles.EventGateFixture.Run();checks+=PhysicalHoldFixture.Run();checks+=NativeHeaderProjectionFixture.Run();checks+=NativeHeaderFixture.Run();checks+=OriginalScopeFixture.Run();checks+=NativePreflightFixture.Run();checks+=HydrationDoubles.HydrationFixture.Run();
Console.WriteLine(checks+" PASS reconstruction strict codec/custody checks; native API and aggregate owner not doubled as success.");}}
