using System;
using System.Collections.Generic;
using System.Linq;
using System.IO;
class Vec { public int x,y,z; public Vec(int a=0,int b=0,int c=0){x=a;y=b;z=c;} public static Vec operator +(Vec a,Vec b)=>new Vec(a.x+b.x,a.y+b.y,a.z+b.z);public override bool Equals(object o)=>o is Vec v&&x==v.x&&y==v.y&&z==v.z;public override int GetHashCode()=>x; }
class Definition { public Vec startPos=new Vec(),size=new Vec(10,10,10);public short spawnCountMin=1,spawnCountMax=2;public int flags;public string minScript; }
class Prefab {public bool bTraderArea;public string PrefabName="house";public List<Definition> SleeperVolumeList=new List<Definition>{new Definition()};}
class PrefabInstance {public Prefab prefab=new Prefab();public Vec boundingBoxPosition=new Vec(),boundingBoxSize=new Vec(10,10,10);public byte rotation;public List<SleeperVolume> sleeperVolumes=new List<SleeperVolume>();}
class Biome {public string m_sBiomeName="forest";}
class WorldState {public string Guid=System.Guid.NewGuid().ToString("N").ToUpperInvariant();}
class World {public WorldState worldState=new WorldState();public ulong worldTime=1;public Dictionary<int,EntityAlive> Entities=new Dictionary<int,EntityAlive>();public List<SleeperVolume> Volumes=new List<SleeperVolume>(); public bool IsRemote()=>false;public EntityAlive GetEntity(int id)=>Entities.TryGetValue(id,out var e)?e:null;public int FindSleeperVolume(Vec min,Vec max)=>Volumes.FindIndex(v=>v.BoxMin.Equals(min)&&v.BoxMax.Equals(max));public SleeperVolume GetSleeperVolume(int id)=>id>=0&&id<Volumes.Count?Volumes[id]:null;public Biome GetBiome(int x,int z)=>new Biome();}
class EntityBuffs {public Dictionary<string,float> Vars=new Dictionary<string,float>();public bool HasCustomVar(string key)=>Vars.ContainsKey(key);public float GetCustomVar(string key)=>Vars[key];public void SetCustomVar(string key,float value,bool netSync){Vars[key]=value;} }
class EntityAlive {public EntityBuffs Buffs=new EntityBuffs();public World world;public int entityId;public bool Dead;public bool IsDead()=>Dead;}
class EntityPlayer:EntityAlive {public bool IsSpectator;public bool IsAlive()=>!Dead;public Vec GetBlockPosition()=>new Vec();}
class Script {public bool Running;public bool IsRunning()=>Running;}
class Handle {public bool IsCompleted=true;public Action onComplete;}
class SleeperVolume {public PrefabInstance prefabInstance;public Vec BoxMin=new Vec(),BoxMax=new Vec(10,10,10);public short spawnCountMin=1,spawnCountMax=2;public int flags,numSpawned;public bool isSpawning,wasCleared;public Script minScript;public Dictionary<int,object> respawnMap=new Dictionary<int,object>();public HashSet<int> pendingSpawnMap=new HashSet<int>();public Queue<Handle> pendingSpawnOps=new Queue<Handle>();}
class Decorator {public PrefabInstance Prefab;public PrefabInstance GetPrefabFromWorldPos(int x,int z)=>Prefab;}
class GameStateManager {public bool IsGameStarted()=>true;}
class GameManager {public static GameManager Instance;public World World;public bool IsStartingGame;public GameStateManager gameStateManager=new GameStateManager();public bool IsEditMode()=>false;public Decorator Decorator=new Decorator();public Decorator GetDynamicPrefabDecorator()=>Decorator;}
class ConnectionManager {public bool IsServer=true;}
class SingletonMonoBehaviour<T> {public static T Instance;}
class ThreadManager {public static bool IsMainThread()=>true;}
class GameIO {public static string GetSaveGameDir()=>"unused";}
class Log {public static void Warning(string s){} }

static class Program
{
 static int checks;static void Check(bool condition,string name){if(!condition)throw new Exception("FAIL "+name);checks++;Console.WriteLine("PASS "+name);}
 static RebirthPoiPartialObservation Partial(Guid generation,long revision,IEnumerable<RebirthPoiActorObservation> actors,long epoch=0)=>new RebirthPoiPartialObservation(generation,epoch,revision,new[]{new RebirthPoiVolumeObservation(7,new string('a',64),actors)});
 static void Main()
 {
  object scope=new object();Guid world=Guid.NewGuid(),generation=Guid.NewGuid(),token=Guid.NewGuid(),death=Guid.NewGuid();var poi=new RebirthPoiIdentity("house",1,2,3,0,10,10,10,"forest");var ledger=new RebirthPoiClearanceLedger(world,scope);ledger.TryDiscover(scope,world,0,poi,out ledger);
  var actor=new RebirthPoiActorObservation(token,1,"zombieArlene",0);var original=Partial(generation,1,new[]{actor});Check(ledger.TryObservePartial(scope,world,ledger.Revision,poi,0,original,out ledger),"actual domain accepts first original observation generation");string xml=RebirthPoiClearanceCodec.Write(ledger);Check(RebirthPoiClearanceCodec.TryRead(xml,world,scope,out var restored)&&restored.Records[poi.Key].Observations.Canonical==original.Canonical,"cold codec retains exact native actor generation and manifest");Check(!RebirthPoiClearanceCodec.TryRead(xml,Guid.NewGuid(),scope,out _),"partial journal original world enforced");Check(!ledger.TryObservePartial(new object(),world,ledger.Revision,poi,0,original,out _),"partial original scope enforced");Check(ledger.TryObservePartial(scope,world,0,poi,0,original,out var same)&&ReferenceEquals(same,ledger),"original observation duplicate retains global revision");
  var died=new RebirthPoiActorObservation(token,1,"zombieArlene",0,death,42);var terminal=Partial(generation,2,new[]{died});Check(ledger.TryObservePartial(scope,world,ledger.Revision,poi,0,terminal,out ledger),"original death receipt is durable monotonic successor");Check(!ledger.TryObservePartial(scope,world,ledger.Revision,poi,0,Partial(generation,3,new[]{actor}),out _),"dead actor cannot revive in same generation");Check(!ledger.TryObservePartial(scope,world,ledger.Revision,poi,0,Partial(generation,3,new RebirthPoiActorObservation[0]),out _),"old enrolled actor cannot disappear");Check(!ledger.TryObservePartial(scope,world,ledger.Revision,poi,0,Partial(Guid.NewGuid(),3,new[]{died}),out _),"replacement generation cannot reuse same epoch");Check(!ledger.TryObservePartial(scope,world,ledger.Revision-1,poi,0,Partial(generation,3,new[]{died}),out _),"stale global predecessor refused");
  Guid reset=Guid.NewGuid();ledger.TryBeginReset(scope,world,ledger.Revision,poi,0,reset,out ledger);Check(!ledger.TryObservePartial(scope,world,ledger.Revision,poi,0,terminal,out _),"pending reset blocks observations");ledger.TryFinishReset(scope,world,ledger.Revision,poi,0,reset,RebirthPoiResetDisposition.NoMutation,out ledger);Check(ledger.Records[poi.Key].Observations.Canonical==terminal.Canonical,"proven no mutation restores original partial causality");reset=Guid.NewGuid();ledger.TryBeginReset(scope,world,ledger.Revision,poi,0,reset,out ledger);ledger.TryFinishReset(scope,world,ledger.Revision,poi,0,reset,RebirthPoiResetDisposition.Completed,out ledger);Check(ledger.Records[poi.Key].Epoch==1&&ledger.Records[poi.Key].Observations==null,"proven completed reset advances epoch and forgets old generation");
  Check(!RebirthPoiClearanceCodec.TryRead(xml.Replace("<observations ","<observations unknown=\"1\" "),world,scope,out _),"unknown observation attribute refused");Check(!RebirthPoiClearanceCodec.TryRead(xml+"<!--extra-->",world,scope,out _),"whole envelope remains strict with observation payload");
  string dir=Path.Combine(Path.GetTempPath(),"rebirth-purge-observation-"+Guid.NewGuid().ToString("N"));Directory.CreateDirectory(dir);var binding=new RebirthPoiWorldBinding(scope,world.ToString("N").ToUpperInvariant(),dir,()=>true);bool armed=false;string faultStage="afterShardWrite";int written=0;Check(RebirthPoiWorldStore.TryOpen(binding,out var store,stage=>{if(armed&&stage==faultStage&&++written==1)throw new IOException("first repack file lost response");})==RebirthPoiStoreResult.Published,"production store opens real observation save");
  for(int i=0;i<110;i++){var p=new RebirthPoiIdentity("house"+i,i,2,3,0,10,10,10,"forest");if(store.TryDiscover(store.Published,p)!=RebirthPoiStoreResult.Published)throw new Exception("setup discover "+i);}
  Check(store.Published.Count==110,"prepare110 real saved POIs");
  var target=new RebirthPoiIdentity("house0",0,2,3,0,10,10,10,"forest");var actors=Enumerable.Range(0,2070).Select(i=>new RebirthPoiActorObservation(Guid.NewGuid(),10000+i,new string('z',256),i%255)).ToArray();var large=Partial(Guid.NewGuid(),1,actors);int oldShards=store.Published.Shards.Count;armed=true;var predecessor=store.Published;Check(store.TryObservePartial(predecessor,target,0,large)==RebirthPoiStoreResult.Uncertain&&store.HasPending&&store.Published.Revision==predecessor.Revision,"repack first file interruption preserves original visible global revision");var originalFiles=Directory.GetFiles(binding.Directory,"shard-*.xml");armed=false;Check(store.TryRetryPending()==RebirthPoiStoreResult.Published,"original multi-shard candidate retry publishes");Check(store.Published.Shards.Count==oldShards+1&&store.Published.Count==110,"payload budget repacks one POI with exact map cardinality");Check(originalFiles.All(File.Exists),"uncertain repack immutable files preserved");Check(store.Published.TryGet(target,out var saved)&&saved.Observations.Canonical==large.Canonical,"actual final witness contains original partial payload");Check(RebirthPoiWorldStore.TryOpen(binding,out var cold)==RebirthPoiStoreResult.Published&&cold.Published.Count==110&&cold.Published.TryGet(target,out saved)&&saved.Observations.Volumes[7].Actors.Count==2070,"cold actual file reload verifies both repacked shards and all actors");Check(cold.TryObservePartial(cold.Published,target,0,large)==RebirthPoiStoreResult.Duplicate,"cold original partial retry idempotent");Check(cold.TryObservePartial(predecessor,target,0,large)==RebirthPoiStoreResult.Conflict,"pre-repack scope snapshot cannot publish late operation");
  var nextTarget=new RebirthPoiIdentity("house1",1,2,3,0,10,10,10,"forest");var nextLarge=Partial(Guid.NewGuid(),1,actors.Select(a=>new RebirthPoiActorObservation(Guid.NewGuid(),a.EntityId,a.ClassName,a.SpawnPoint)));armed=true;written=0;faultStage="afterManifestCandidateWritten";var before=store.Published;Check(store.TryObservePartial(before,nextTarget,0,nextLarge)==RebirthPoiStoreResult.Uncertain,"two-shard final candidate interruption remains uncertain");string retained=File.ReadAllText(Path.Combine(binding.Directory,"world.xml.candidate"));Check(RebirthPoiWorldStore.TryOpen(binding,out var restarted)==RebirthPoiStoreResult.Uncertain&&restarted.Published.Revision==before.Revision,"restart preserves original predecessor for retained two-shard candidate");Check(restarted.TryRetryPending()==RebirthPoiStoreResult.Published&&restarted.Published.Manifest==retained&&restarted.Published.Count==110,"restart exact two-shard candidate publishes unchanged envelope");Check(restarted.Published.TryGet(nextTarget,out saved)&&saved.Observations.Canonical==nextLarge.Canonical,"restart original partial causality survives full publication interruption");
  var malformed=System.Xml.Linq.XDocument.Parse(xml);var observations=malformed.Root.Element("poi").Element("observations");var firstVolume=observations.Element("volume");firstVolume.Add(new System.Xml.Linq.XElement(firstVolume.Element("actor")));Check(!RebirthPoiClearanceCodec.TryRead(malformed.ToString(),world,scope,out _),"duplicate persisted native actor token refused");bool invalid=false;try{new RebirthPoiActorObservation(Guid.NewGuid(),5,"bad"+'\ud800',0);}catch(System.Xml.XmlException){invalid=true;}Check(invalid,"invalidUTF16 actor identity refused");
  var roomA=new RebirthPoiVolumeObservation(7,new string('a',64),new[]{died});var roomB=new RebirthPoiVolumeObservation(8,new string('b',64),new[]{new RebirthPoiActorObservation(Guid.NewGuid(),2,"zombieArlene",1,Guid.NewGuid(),43)});
  var rooms=new RebirthPoiPartialObservation(generation,0,1,new[]{roomA,roomB});var resetPlan=new RebirthPoiResetPlan(Guid.NewGuid(),RebirthPoiResetCaller.NaturalRespawn,new string('c',64),new long[0],new[]{7},new int[0]);var rolled=rooms.RollOverVerifiedReset(resetPlan);
  Check(rolled.Epoch==1&&rolled.Revision==2&&rolled.Volumes[7].Actors.Count==0&&rolled.EffectiveGeneration(rolled.Volumes[7])==resetPlan.Transaction,"exact selective reset stamps affected volume original transaction");
  Check(rolled.Volumes[8].Actors.Values.Single().DeathReceipt==roomB.Actors.Values.Single().DeathReceipt&&rolled.EffectiveGeneration(rolled.Volumes[8])==generation,"positively untouched room retains original generation and death receipt");
  Check(rolled.Canonical==rooms.RollOverVerifiedReset(resetPlan).Canonical,"selective successor is deterministic under original retry");
  Check(rooms.RollOverVerifiedReset(new RebirthPoiResetPlan(Guid.NewGuid(),RebirthPoiResetCaller.NaturalRespawn,new string('c',64),new long[0],new[]{9},new int[0]))==null,"unknown reset volume cannot preserve partial evidence");
  var v2=RebirthPoiPartialObservation.Write(rolled);Check(RebirthPoiPartialObservation.Read(v2).Canonical==rolled.Canonical,"version3 explicit per-volume generations round trip");
  var v1=RebirthPoiPartialObservation.Write(rooms);v1.SetAttributeValue("version",1);foreach(var v in v1.Elements("volume"))v.Attribute("generation").Remove();var legacy=RebirthPoiPartialObservation.Read(v1);
  Check(legacy.Volumes.Values.All(v=>legacy.EffectiveGeneration(v)==generation),"backward version1 volumes resolve original journal generation");
  var replacedGeneration=new RebirthPoiPartialObservation(generation,0,2,new[]{new RebirthPoiVolumeObservation(7,new string('a',64),new[]{died},Guid.NewGuid()),roomB});Check(!replacedGeneration.IsSuccessorOf(rooms),"normal observation cannot replace volume generation without reset");
  Guid restoreReceipt=Guid.NewGuid();var replacement=actor.RestoreVerifiedNativeParticipant(11,restoreReceipt);var restoreJournal=Partial(generation,2,new[]{replacement});Check(restoreJournal.IsSuccessorOf(original),"explicit native restoration preserves logical participant with new entity ID");
  Check(replacement.Token==actor.Token&&replacement.Restorations.Single().FromEntityId==1&&replacement.Restorations.Single().ToEntityId==11,"lineage retains exact original participant and predecessor");
  Check(RebirthPoiPartialObservation.Read(RebirthPoiPartialObservation.Write(restoreJournal)).Canonical==restoreJournal.Canonical,"strict persisted restoration chain cold round trip");
  Check(!Partial(generation,2,new[]{new RebirthPoiActorObservation(token,11,"zombieArlene",0)}).IsSuccessorOf(original),"new ID without positive restoration receipt refused");
  Check(!Partial(generation,3,new[]{new RebirthPoiActorObservation(token,11,"zombieArlene",0)}).IsSuccessorOf(restoreJournal),"original restoration receipt cannot be forgotten");
  var replacementDead=new RebirthPoiActorObservation(token,11,"zombieArlene",0,Guid.NewGuid(),45,replacement.Restorations);Check(Partial(generation,3,new[]{replacementDead}).IsSuccessorOf(restoreJournal),"restored participant original lineage retained through actual death");
  bool deadRestore=false;try{replacementDead.RestoreVerifiedNativeParticipant(12,Guid.NewGuid());}catch(InvalidOperationException){deadRestore=true;}Check(deadRestore,"witnessed dead logical participant cannot be restored");
  bool cyclic=false;try{replacement.RestoreVerifiedNativeParticipant(1,Guid.NewGuid());}catch(ArgumentException){cyclic=true;}Check(cyclic,"restoration native ID cycles refused");
  bool duplicateReceipt=false;try{replacement.RestoreVerifiedNativeParticipant(12,restoreReceipt);}catch(ArgumentException){duplicateReceipt=true;}Check(duplicateReceipt,"original restoration receipt cannot alias a second native replacement");
  var repeated=actor;for(int i=0;i<32;i++)repeated=repeated.RestoreVerifiedNativeParticipant(20+i,Guid.NewGuid());var compacted=repeated.RestoreVerifiedNativeParticipant(99,Guid.NewGuid());Check(compacted.Checkpoint.Count==32&&compacted.Restorations.Count==1&&compacted.IsCausalSuccessorOf(repeated),"exact deterministic checkpoint supports restoration beyond32 without unbounded history");
  var many=compacted;for(int i=0;i<200;i++)many=many.RestoreVerifiedNativeParticipant(100+i,Guid.NewGuid());Check(many.Checkpoint.Count+many.Restorations.Count==233&&many.Restorations.Count<=32,"233restorations retain bounded current lineage and cumulative count");
  Check(RebirthPoiPartialObservation.Read(RebirthPoiPartialObservation.Write(Partial(generation,3,new[]{many}))).Canonical==Partial(generation,3,new[]{many}).Canonical,"compacted native lineage strict cold round trip");
  var forged=new RebirthPoiActorObservation(compacted.Token,compacted.EntityId,compacted.ClassName,compacted.SpawnPoint,restorations:compacted.Restorations,checkpoint:new RebirthPoiRestorationCheckpoint(32,1,51,new string('f',64)));Check(!forged.IsCausalSuccessorOf(repeated),"successor recomputes original checkpoint rather than trusting arbitrary digest");
  var historicalV2=RebirthPoiPartialObservation.Write(restoreJournal);historicalV2.SetAttributeValue("version",2);Check(RebirthPoiPartialObservation.Read(historicalV2).Canonical==restoreJournal.Canonical,"backward version2 restoration receipts read without checkpoint");
  var checkpointXml=RebirthPoiPartialObservation.Write(Partial(generation,3,new[]{many}));var checkpointActor=checkpointXml.Element("volume").Element("actor");checkpointActor.Add(new System.Xml.Linq.XElement(checkpointActor.Element("checkpoint")));bool duplicateCheckpoint=false;try{RebirthPoiPartialObservation.Read(checkpointXml);}catch(FormatException){duplicateCheckpoint=true;}Check(duplicateCheckpoint,"duplicate persisted restoration checkpoint refused");
  string playerKey=new string('b',64);var creditToken=Guid.NewGuid();var creditDeath=Guid.NewGuid();var credited=new RebirthPoiActorObservation(creditToken,990,"zombieArlene",0,creditDeath,10,contributor:playerKey);
  var creditJournal=Partial(Guid.NewGuid(),1,new[]{credited});var creditXml=RebirthPoiPartialObservation.Write(creditJournal);
  Check((string)creditXml.Attribute("version")=="6"&&RebirthPoiPartialObservation.Read(creditXml).Volumes[7].Actors[creditToken].Contributor==playerKey,"verified death contributor roundtrips explicit v6 evidence");
  Check((string)RebirthPoiPartialObservation.Write(original).Attribute("version")=="5","old unattributed observations retain prior schema");
  Check(!new RebirthPoiActorObservation(creditToken,990,"zombieArlene",0,creditDeath,10,contributor:new string('c',64)).IsCausalSuccessorOf(credited),"immutable witnessed death cannot transfer contributor");
  bool contributorRejected=false;try{new RebirthPoiActorObservation(Guid.NewGuid(),991,"zombieArlene",0,contributor:playerKey);}catch(ArgumentException){contributorRejected=true;}Check(contributorRejected,"living enrollment cannot mint kill credit");
  contributorRejected=false;try{new RebirthPoiActorObservation(Guid.NewGuid(),991,"zombieArlene",0,Guid.NewGuid(),10,terminalKind:RebirthPoiActorTerminalKind.NativeDespawn,contributor:playerKey);}catch(ArgumentException){contributorRejected=true;}Check(contributorRejected,"native despawn cannot mint player kill credit");
  contributorRejected=false;try{new RebirthPoiActorObservation(Guid.NewGuid(),991,"zombieArlene",0,Guid.NewGuid(),10,contributor:"runtime-player-123");}catch(ArgumentException){contributorRejected=true;}Check(contributorRejected,"runtime entity ID cannot be durable contributor identity");
  var duplicateContributor=new System.Xml.Linq.XElement(creditXml);var duplicatedActor=duplicateContributor.Element("volume").Element("actor");duplicatedActor.Add(new System.Xml.Linq.XElement(duplicatedActor.Element("contributor")));contributorRejected=false;try{RebirthPoiPartialObservation.Read(duplicateContributor);}catch(FormatException){contributorRejected=true;}Check(contributorRejected,"duplicate contributor custody refused");
  var v5Credit=new System.Xml.Linq.XElement(creditXml);v5Credit.SetAttributeValue("version",5);contributorRejected=false;try{RebirthPoiPartialObservation.Read(v5Credit);}catch(FormatException){contributorRejected=true;}Check(contributorRejected,"v5 evidence cannot smuggle v6 contributor extension");
  Console.WriteLine("RESULT "+checks+" PASS; actual observation/domain/codec/CAS/repacking real files; native methods doubled; no automatic gameplay proof enabled.");
 }
}



