<Project><PropertyGroup><BaseIntermediateOutputPath>$(MSBuildThisFileDirectory)obj/open-observer/</BaseIntermediateOutputPath><MSBuildProjectExtensionsPath>$(MSBuildThisFileDirectory)obj/open-observer/</MSBuildProjectExtensionsPath><IntermediateOutputPath>$(MSBuildThisFileDirectory)obj/open-observer/$(Configuration)/</IntermediateOutputPath><OutputPath>$(MSBuildThisFileDirectory)bin/open-observer/</OutputPath><OutDir>$(MSBuildThisFileDirectory)bin/open-observer/</OutDir></PropertyGroup></Project>
