using System;using System.Collections.Generic;using System.Linq;
// Explicit doubles: UI layout/events, native inventory/quest/audio/XP, and authority/repository APIs.
public struct Vector3i{} public class WorldState{public string Guid="fixture";} public class World{public WorldState worldState=new WorldState();public EntityPlayerLocal Player;public TileEntityWorkstation Station;public object GetEntity(int id)=>Player;public object GetTileEntity(Vector3i p)=>Station;public bool Remote;public bool IsRemote()=>Remote;}
public class EntityPlayerLocal{public Progression Progression=new Progression();public bool IsDead()=>false;public int entityId=1;public World world=new World();public Equipment equipment=new Equipment();}public class Equipment{public void UnlockCosmeticItem(ItemClass x){}}
public class ItemClass{public string Name="item";public string GetItemName()=>Name;}public class ItemClassQuest:ItemClass{}
public class ItemValue{public int type,Quality;public float UseTimes;public ItemClass ItemClass=>type==0?null:new ItemClass{Name="item"+type};public Dictionary<string,string> Metadata=new Dictionary<string,string>();public static ItemValue None=>new ItemValue(0);public ItemValue(int t,int min=1,int max=1){type=t;Quality=min;}public bool IsEmpty()=>type==0;public ItemValue Clone()=>new ItemValue(type,Quality,Quality){UseTimes=UseTimes,Metadata=new Dictionary<string,string>(Metadata)};}
public class ItemStack{public ItemValue itemValue;public int count;public ItemStack(ItemValue v,int c){itemValue=v;count=c;}public bool IsEmpty()=>count==0||itemValue.type==0;public ItemStack Clone()=>new ItemStack(itemValue.Clone(),count);public static ItemStack[] Clone(ItemStack[] a)=>a.Select(x=>x.Clone()).ToArray();public bool CanStackWith(ItemStack s)=>!IsEmpty()&&itemValue.type==s.itemValue.type&&itemValue.Quality==s.itemValue.Quality&&count+s.count<=10;}
public class Recipe{public int itemValueType=2,count=1,craftExpGain=5;public bool Marked=true,Cooking,IsScrap;public string craftingArea="workbench";public List<ItemStack> ingredients=new List<ItemStack>{new ItemStack(new ItemValue(1),1)};public string GetName()=>"nativeRecipe";}
public class RecipeQueueItem{public Recipe Recipe;public int StartingEntityId=1;public short Multiplier=1;}
public class CraftCompleteData{public ItemStack CraftedItemStack;public int CrafterEntityID;public string RecipeName,ItemScrapped;public int CraftExpGain,RecipeUsedCount;}
public class TileEntityWorkstation{public Vector3i ToWorldPos()=>new Vector3i();private ItemStack[] output;public RecipeQueueItem[] Queue;public int Modified;public void AddCraftComplete(int actor,ItemValue output,string recipe,string scrap,int xp,int count){Hooks.Receipt++;}public ItemStack[] Output{get=>output;set{output=ItemStack.Clone(value);Modified++;Hooks.Modified?.Invoke();}}}
public static class Hooks{public static Action Read,Write,Modified,Capture;public static int Xp,Inventory,Drop,Receipt;public static bool InventoryAccept;public static void Reset(){Read=Write=Modified=Capture=null;Xp=Inventory=Drop=Receipt=0;InventoryAccept=false;RebirthStationCompletionOriginalScope.Epoch=0;}}
public class PlayerUI{public EntityPlayerLocal entityPlayer=new EntityPlayerLocal();}public class XUi{public PlayerUI playerUI=new PlayerUI();public PlayerInventory PlayerInventory=new PlayerInventory();public DragWindow DragAndDropWindow=new DragWindow();}public class DragWindow{public ItemStack CurrentStack=new ItemStack(ItemValue.None,0);}public class PlayerInventory{public bool AddItemNoPartial(ItemStack s,bool _playCollectSound){Hooks.Inventory++;if(Hooks.InventoryAccept){s.count=0;return true;}return false;}public void DropItem(ItemStack s){Hooks.Drop++;}}
public class WindowGroup{public bool isShowing=true;public XUiController Controller;}public class View{public bool IsVisible;}
public class XUiController{public XUi xui;public WindowGroup windowGroup;public View ViewComponent=new View();public bool IsDirty;public virtual void Update(float dt){}public T GetChildByType<T>()where T:class=>(this as XUiC_WorkstationWindowGroup)?.outputWindow as T;public void SetAllChildrenDirty(){}}
public class XUiC_CraftingQueue{public XUiC_RecipeStack[] Entries;public XUiC_RecipeStack[] GetRecipesToCraft()=>Entries;}
public partial class XUiM_Workstation{public readonly TileEntityWorkstation tileEntity;public TileEntityWorkstation TileEntity=>tileEntity;public XUiM_Workstation(TileEntityWorkstation t){tileEntity=t;}}
public class XUiC_WorkstationWindowGroup:XUiController{public XUiM_Workstation WorkstationData;public XUiC_WorkstationOutputGrid outputWindow;public XUiC_CraftingQueue craftingQueue;}
public class XUiC_ItemStack{public ItemStack ItemStack;}
public partial class XUiC_ItemStackGrid:XUiController{protected XUiC_ItemStack[] itemControllers;public void SetStacks(ItemStack[] cells){itemControllers=cells.Select(x=>new XUiC_ItemStack{ItemStack=x.Clone()}).ToArray();}public virtual void UpdateBackend(ItemStack[] cells){Hooks.Write?.Invoke();}}
public class XUiC_WorkstationGrid:XUiC_ItemStackGrid{public XUiM_Workstation workstationData;public XUiM_Workstation WorkstationData=>workstationData;public virtual void SetSlots(ItemStack[] cells)=>SetStacks(cells);}
public partial class XUiC_WorkstationOutputGrid:XUiC_WorkstationGrid{}
public partial class XUiC_RecipeStack:XUiController{public Recipe recipe;public int recipeCount=1,recipeTier=1,outputQuality=1,amountToRepair,startingEntityId=1;public float craftingTimeLeft,totalCraftTimeLeft,oneItemCraftTime=1;public bool isCrafting=true,isInventoryFull,playSound;public ItemValue originalItem=ItemValue.None,outputItemValue;public XUiC_CraftingQueue Owner;public void ClearRecipe(){recipe=null;recipeCount=0;}public void updateRecipeData(){}public void giveExp(ItemValue v,ItemClass c){Hooks.Xp++;}}
public static class ItemAction{public static void HandleDegradation(ItemValue v,EntityPlayerLocal p){}}public static class Localization{public static bool Exists(string s)=>false;public static string Get(string s)=>s;}public class GameManager{public static GameManager Instance;public World World;public static void ShowTooltip(EntityPlayerLocal p,string s){}}public static class Manager{public static void PlayInsidePlayerHead(string s){}}
public class AchievementManager{public void SetAchievementStat(EnumAchievementDataStat s,int n){}}public class PlatformValue{public AchievementManager AchievementManager=new AchievementManager();}public static class PlatformManager{public static PlatformValue NativePlatform=new PlatformValue();}public enum EnumAchievementDataStat{StoneAxeCrafted,WoodFrameCrafted}
public class WorkstationData{public string CraftCompleteSound;}public static class CraftingManager{public static WorkstationData GetWorkstationData(string s)=>null;}
public class QuestEventManager{public static QuestEventManager Current=new QuestEventManager();public void RepairedItem(ItemValue v){}public void CraftedItem(ItemStack v){}public void ScrappedItem(ItemStack v){}}
public static class GameSparksCollector{public enum GSDataKey{CraftedItems}public static void IncrementCounter(GSDataKey k,string n,int c){}}
public static class RebirthStationGridQueue{public static bool IsMarked(Recipe r)=>r.Marked;}public static class RebirthCookingBatch{public static bool IsBatch(Recipe r)=>r.Cooking;}
public static class RebirthStationGridIngredients{public static bool IsSameStackSnapshot(ItemStack a,ItemStack b)=>a!=null&&b!=null&&a.count==b.count&&a.itemValue.type==b.itemValue.type&&a.itemValue.Quality==b.itemValue.Quality&&a.itemValue.UseTimes==b.itemValue.UseTimes&&a.itemValue.Metadata.OrderBy(x=>x.Key).SequenceEqual(b.itemValue.Metadata.OrderBy(x=>x.Key));}
public class RebirthStationCompletionOriginalScope{public static StringComparison PathComparison=>StringComparison.OrdinalIgnoreCase;public static int Epoch;private readonly int epoch;private readonly TileEntityWorkstation station;private RebirthStationCompletionOriginalScope(TileEntityWorkstation s){epoch=Epoch;station=s;}public bool IsCurrent()=>epoch==Epoch&&station!=null;public static bool TryCapture(TileEntityWorkstation s,RecipeQueueItem a,out RebirthStationCompletionOriginalScope scope){scope=new RebirthStationCompletionOriginalScope(s);Hooks.Capture?.Invoke();return scope.IsCurrent();}}
public static class RebirthStationCompletionReceipt{public const string Prefix="receipt.";public sealed class Identity{public int Count;}public static bool TryReadIdentity(CraftCompleteData r,out Identity id){id=new Identity{Count=r.CraftedItemStack.count};return true;}}
public static class RebirthStationCompletionCapture{
 public sealed class OutputObservation{private readonly ItemStack[] before;private readonly TileEntityWorkstation station;private readonly RecipeQueueItem active;public readonly RebirthStationCompletionOriginalScope Original;public OutputObservation(ItemStack[] b,RebirthStationCompletionOriginalScope o,TileEntityWorkstation s){before=b;Original=o;station=s;active=s.Queue.Last();}public bool Matches(TileEntityWorkstation s,CraftCompleteData r)=>ReferenceEquals(s,station)&&ReferenceEquals(s.Queue.Last(),active)&&Original.IsCurrent()&&RebirthStationOutputDelta.Matches(before,s.Output,r);}
 public static bool TryBuild(TileEntityWorkstation s,int actor,ItemValue v,string recipe,string scrap,int xp,int count,out CraftCompleteData row){row=new CraftCompleteData{CraftedItemStack=new ItemStack(v.Clone(),count),CrafterEntityID=actor,RecipeName=recipe,ItemScrapped=scrap,CraftExpGain=xp,RecipeUsedCount=1};return true;}
 public static bool TryObserveBefore(TileEntityWorkstation s,int actor,ItemValue v,string recipe,string scrap,int xp,int count,out OutputObservation o){RebirthStationCompletionOriginalScope.TryCapture(s,s.Queue.Last(),out var scope);o=new OutputObservation(ItemStack.Clone(s.Output),scope,s);return scope.IsCurrent();}
}


public static class GameIO{public static string GetSaveGameDir()=>System.IO.Path.GetTempPath();}
public class RebirthStationNativeQueueSnapshot{RecipeQueueItem row;Recipe recipe;short count;int actor;public static bool TryCapture(System.Collections.Generic.IList<RecipeQueueItem> q,out RebirthStationNativeQueueSnapshot s){s=new RebirthStationNativeQueueSnapshot{row=q[q.Count-1],recipe=q[q.Count-1].Recipe,count=q[q.Count-1].Multiplier,actor=q[q.Count-1].StartingEntityId};return true;}public bool Matches(System.Collections.Generic.IList<RecipeQueueItem> q)=>q.Count==1&&ReferenceEquals(q[0],row)&&ReferenceEquals(row.Recipe,recipe)&&row.Multiplier==count&&row.StartingEntityId==actor;}
public class Progression{public enum XPTypes{Other=0,Crafting=3}}
