using System;
class Program{
 static int n;static void Check(bool b,string s){if(!b)throw new Exception(s);n++;}
 sealed class Case{public TileEntityWorkstation T;public XUiC_RecipeStack S;public XUiC_WorkstationOutputGrid G;public XUiC_WorkstationWindowGroup Group;}
 static Case New(int count=0){Hooks.Reset();var r=new Recipe();var t=new TileEntityWorkstation{Queue=new[]{new RecipeQueueItem{Recipe=r}},Output=new[]{new ItemStack(count==0?ItemValue.None:new ItemValue(2),count)}};var ui=new XUi();var model=new XUiM_Workstation(t);var group=new XUiC_WorkstationWindowGroup{xui=ui,WorkstationData=model};var w=new WindowGroup{Controller=group};group.windowGroup=w;var grid=new XUiC_WorkstationOutputGrid{xui=ui,windowGroup=w,workstationData=model};grid.SetSlots(t.Output);group.outputWindow=grid;var q=new XUiC_CraftingQueue();group.craftingQueue=q;var s=new XUiC_RecipeStack{xui=ui,windowGroup=w,recipe=r,Owner=q};q.Entries=new[]{s};return new Case{T=t,S=s,G=grid,Group=group};}
 static RebirthStationOpenOutputObserverCandidate.Frame Run(Case c){RebirthStationOpenOutputObserverCandidate.BeginOutput(c.S,out var f);try{c.S.outputStack();RebirthStationOpenOutputObserverCandidate.FinalizeOriginal(null,f);}catch(Exception e){Check(ReferenceEquals(e,RebirthStationOpenOutputObserverCandidate.FinalizeOriginal(e,f)),"same exception");throw;}return f;}
 static void Main(){
 var c=New();var f=Run(c);Check(c.T.Output[0].count==1,"empty physical");Check(f.Confirmed!=null,"empty proof");Check(f.Confirmed.TryTake(out _),"one take");Check(!f.Confirmed.TryTake(out _),"no replay");Check(Hooks.Xp==1&&Hooks.Receipt==0,"native XP untouched");
 c=New(4);f=Run(c);Check(c.T.Output[0].count==5&&f.Confirmed!=null,"merge detached clone proof");
 c=New(10);Hooks.InventoryAccept=true;f=Run(c);Check(Hooks.Inventory==1&&c.T.Output[0].count==10&&f.Confirmed==null,"inventory fallback no buffer proof");
 c=New(10);f=Run(c);Check(c.S.isInventoryFull&&f.Confirmed==null&&Hooks.Xp==1,"full failure native early XP");
 c.T.Output=new[]{new ItemStack(ItemValue.None,0)};c.G.SetSlots(c.T.Output);RebirthStationOpenOutputObserverCandidate.BeginUpdate(c.S,out f);c.S.Update(.1f);RebirthStationOpenOutputObserverCandidate.FinalizeOriginal(null,f);Check(c.T.Output[0].count==1&&f.Confirmed!=null,"retry physical/proof");Check(c.S.recipeCount==0&&!c.S.isInventoryFull&&Hooks.Xp==1,"retry decrements without repeat XP");
 c=New();Hooks.Capture=()=>RebirthStationCompletionOriginalScope.Epoch++;f=Run(c);Check(c.T.Output[0].count==1&&f.Confirmed==null,"capture scope retires observer only");
 c=New();Hooks.Write=()=>c.Group.WorkstationData=new XUiM_Workstation(c.T);f=Run(c);Check(c.T.Output[0].count==1&&f.Confirmed==null,"model swap native preserved");
 c=New();Hooks.Modified=()=>RebirthStationCompletionOriginalScope.Epoch++;f=Run(c);Check(c.T.Output[0].count==1&&f.Confirmed==null,"post effect retirement");
 c=New();f=Run(c);c.T.Queue=new[]{new RecipeQueueItem{Recipe=c.S.recipe}};Check(!f.Confirmed.TryTake(out _),"queue replacement refuses transfer");
 c=New();c.S.recipe.Marked=false;f=Run(c);Check(f==null&&c.T.Output[0].count==1,"ordinary currently unobserved native preserved");
 c=New();c.S.recipe.Cooking=true;f=Run(c);Check(f==null&&c.T.Output[0].count==1,"cooking excluded");
 c=New();var error=new InvalidOperationException("before write");Hooks.Write=()=>throw error;try{Run(c);Check(false,"must throw");}catch(Exception e){Check(ReferenceEquals(e,error)&&c.T.Output[0].count==0,"before effect exception preserved");}
c=New();error=new InvalidOperationException("after write");Hooks.Modified=()=>throw error;try{Run(c);Check(false,"must throw");}catch(Exception e){Check(ReferenceEquals(e,error)&&c.T.Output[0].count==1,"after effect exception physical retained");}
c=New();RebirthStationOpenOutputObserverCandidate.BeginOutput(c.S,out var outer);RebirthStationOpenOutputObserverCandidate.BeginOutput(c.S,out var nested);c.S.outputStack();RebirthStationOpenOutputObserverCandidate.FinalizeOriginal(null,nested);RebirthStationOpenOutputObserverCandidate.FinalizeOriginal(null,outer);Check(outer.Abandoned&&nested.Abandoned&&outer.Confirmed==null&&c.T.Output[0].count==1,"nested observer refuses without changing native");
c=New();c.S.recipe.Marked=false;var world=c.S.xui.playerUI.entityPlayer.world;world.Player=c.S.xui.playerUI.entityPlayer;world.Station=c.T;GameManager.Instance=new GameManager{World=world};UnpaidOpenAdmissionCandidate.BeginUpdate(c.S,out var unpaid);Check(unpaid!=null&&UnpaidOpenAdmissionCandidate.BeginOutput(c.S),"ordinary original admission");c.S.outputItemValue=new ItemValue(2);UnpaidOpenAdmissionCandidate.ObserveNativeArguments(c.S,1,c.S.outputItemValue,"nativeRecipe","",5,1);Check(UnpaidOpenAdmissionCandidate.TryCapturePlayerContext(c.S,out var playerContext)&&playerContext.IsCurrent(c.S),"ordinary player context capture");Check(playerContext.MatchesOriginalDestination(c.S,new ItemStack(c.S.outputItemValue,1)),"exact original player destination");Check(!playerContext.MatchesOriginalDestination(c.S,new ItemStack(c.S.outputItemValue,2)),"destination quantity substitution refused");var slots=UnpaidOpenAdmissionCandidate.ReadSlots(c.G,c.S);slots[0]=new ItemStack(c.S.outputItemValue,1);c.G.SetSlots(slots);UnpaidOpenAdmissionCandidate.WriteOutput(c.G,slots,c.S);c.S.recipeCount--;UnpaidOpenAdmissionCandidate.ObserveQueueDecrement(c.S,1,0);c.S.ClearRecipe();UnpaidOpenAdmissionCandidate.FinalizeOriginal(null,unpaid);Check(unpaid.Completed!=null&&unpaid.Completed.TryTake(out _),"ordinary physical plus native decrement witness");Check(!unpaid.Completed.TryTake(out _),"ordinary oneuse");Check(playerContext.IsCurrent(c.S),"context after native clear");c.T.Queue[0].Multiplier=2;Check(!playerContext.IsCurrent(c.S),"context scalar queue change refused");
c=New(10);c.S.recipe.Marked=false;world=c.S.xui.playerUI.entityPlayer.world;world.Player=c.S.xui.playerUI.entityPlayer;world.Station=c.T;GameManager.Instance=new GameManager{World=world};UnpaidOpenAdmissionCandidate.BeginUpdate(c.S,out unpaid);c.S.outputStack();UnpaidOpenAdmissionCandidate.ObserveNativeArguments(c.S,1,c.S.outputItemValue,"nativeRecipe","",5,1);UnpaidOpenAdmissionCandidate.FinalizeOriginal(null,unpaid);Check(Hooks.Xp==1&&c.S.isInventoryFull,"retained failed native output");c.T.Output=new[]{new ItemStack(ItemValue.None,0)};c.G.SetSlots(c.T.Output);UnpaidOpenAdmissionCandidate.BeginUpdate(c.S,out var retry);Check(retry.Arguments&&retry.NativeXp==5&&!retry.Invalid,"retry retains original arguments");slots=UnpaidOpenAdmissionCandidate.ReadSlots(c.G,c.S);slots[0]=new ItemStack(c.S.outputItemValue,1);c.G.SetSlots(slots);UnpaidOpenAdmissionCandidate.WriteOutput(c.G,slots,c.S);c.S.recipeCount--;UnpaidOpenAdmissionCandidate.ObserveQueueDecrement(c.S,1,0);c.S.ClearRecipe();UnpaidOpenAdmissionCandidate.FinalizeOriginal(null,retry);Check(retry.Completed!=null&&retry.Completed.TryTake(out _)&&Hooks.Xp==1,"retry completion no repeated XP");
c=New();c.S.recipe.Marked=false;world=c.S.xui.playerUI.entityPlayer.world;world.Player=c.S.xui.playerUI.entityPlayer;world.Station=c.T;GameManager.Instance=new GameManager{World=world};UnpaidOpenAdmissionCandidate.BeginUpdate(c.S,out unpaid);c.S.outputItemValue=new ItemValue(2);UnpaidOpenAdmissionCandidate.ObserveOriginalGiveExp(c.S,c.S.outputItemValue,c.S.outputItemValue.ItemClass);Check(!UnpaidOpenAdmissionCandidate.TryCapturePlayerContext(c.S,out _),"two giveExp operands alone insufficient");UnpaidOpenAdmissionCandidate.ObserveOriginalRecipeName(c.S,c.S.recipe,"nativeRecipe");UnpaidOpenAdmissionCandidate.ObserveOriginalRecipeName(c.S,c.S.recipe,"nativeRecipe");UnpaidOpenAdmissionCandidate.ObserveOriginalCraftExpGain(c.S,c.S.recipe,5);Check(!unpaid.Arguments,"raw XP lacks physical quantity");UnpaidOpenAdmissionCandidate.ObserveOriginalAward(c.S,c.S.xui.playerUI.entityPlayer.Progression,2,"_xpFromCrafting",Progression.XPTypes.Crafting,true,true,-1,null,3);Check(unpaid.AwardObserved&&unpaid.NativeAwardRequested==2&&unpaid.NativeAwardReturn==3&&unpaid.NativeXp==5,"raw/request/return XP distinct");UnpaidOpenAdmissionCandidate.ObserveOriginalDestination(c.S,new ItemStack(c.S.outputItemValue,1),1);Check(unpaid.Arguments&&unpaid.NativeXp==5&&unpaid.NativeQuantity==1&&unpaid.NativeScrap==null,"original operand chain raw XP notaward and scrapunknown");Check(UnpaidOpenAdmissionCandidate.TryCapturePlayerContext(c.S,out _),"realoperand context admitted");UnpaidOpenAdmissionCandidate.FinalizeOriginal(null,unpaid);
c=New();c.S.recipe.Marked=false;world=c.S.xui.playerUI.entityPlayer.world;world.Player=c.S.xui.playerUI.entityPlayer;world.Station=c.T;GameManager.Instance=new GameManager{World=world};UnpaidOpenAdmissionCandidate.BeginUpdate(c.S,out unpaid);c.S.outputItemValue=new ItemValue(2);UnpaidOpenAdmissionCandidate.ObserveOriginalGiveExp(c.S,c.S.outputItemValue,c.S.outputItemValue.ItemClass);UnpaidOpenAdmissionCandidate.ObserveOriginalRecipeName(c.S,c.S.recipe,"first");UnpaidOpenAdmissionCandidate.ObserveOriginalRecipeName(c.S,c.S.recipe,"changed");Check(unpaid.Invalid&&!UnpaidOpenAdmissionCandidate.TryCapturePlayerContext(c.S,out _),"original getter disagreement refuses");UnpaidOpenAdmissionCandidate.FinalizeOriginal(null,unpaid);
Console.WriteLine("PASS "+n+" actual extracted native bodies with explicit authority/UI doubles");}
}







