using System;
using System.Collections.Generic;
using System.Linq;
using System.IO;
using System.Reflection;
namespace HarmonyLib{
 class HarmonyMethod{public MethodInfo method;public HarmonyMethod(MethodInfo m){method=m;}}
 class Patch{public string owner;public MethodInfo PatchMethod;}
 class Info{public List<Patch> Prefixes=new(),Postfixes=new(),Finalizers=new(),Transpilers=new();public List<string> Owners=new();}
 class Harmony{readonly string owner;public Harmony(string s){owner=s;}static readonly Dictionary<MethodBase,Info> info=new();public static Info GetPatchInfo(MethodBase m)=>info.TryGetValue(m,out var p)?p:null;public void Patch(MethodBase m,HarmonyMethod prefix,HarmonyMethod postfix,object transpiler,HarmonyMethod finalizer,object last){var p=GetPatchInfo(m)??new Info();info[m]=p;p.Owners.Add(owner);p.Prefixes.Add(new Patch{owner=owner,PatchMethod=prefix.method});p.Postfixes.Add(new Patch{owner=owner,PatchMethod=postfix.method});p.Finalizers.Add(new Patch{owner=owner,PatchMethod=finalizer.method});}}
 static class AccessTools{public static MethodInfo Method(Type t,string name,Type[] args=null)=>args==null?t.GetMethod(name,BindingFlags.NonPublic|BindingFlags.Public|BindingFlags.Static|BindingFlags.Instance):t.GetMethod(name,args);}
}
// Fixture forces installation on native doubles; production release gate remains false.
static class RebirthPurgeReleasePolicy {public static bool Enabled=>true;}
enum EnumRemoveEntityReason{Undef,Unloaded,Killed,Despawned,Captured}
class Entity{public int entityId;public World world;public bool bDead,IsDespawned,bWillRespawn,Marked;public bool IsMarkedForUnload()=>Marked||bDead;}
class Buffs{readonly Dictionary<string,float> values=new();public bool HasCustomVar(string k)=>values.ContainsKey(k);public float GetCustomVar(string k)=>values[k];public void SetCustomVar(string k,float v,bool sync)=>values[k]=v;}
class EntityAlive:Entity{public Buffs Buffs=new();public int entityClass=1;public bool Fatal;public bool IsDead()=>bDead||Fatal;public void SetDead(){bDead=true;}}
class EntityClass{public string entityClassName="zombieArlene";public static Dictionary<int,EntityClass> list=new(){{1,new EntityClass()}};}
class Entities{public Dictionary<int,Entity> dict=new();}
class WorldState{public string Guid=System.Guid.NewGuid().ToString("N").ToUpperInvariant();}
class World{public WorldState worldState=new();public Entities Entities=new();public ulong worldTime=50;public int Hydrations;public bool IsRemote()=>false;public Entity GetEntity(int id){Hydrations++;return Entities.dict.TryGetValue(id,out var e)?e:null;}public void unloadEntity(Entity e,EnumRemoveEntityReason reason){Entities.dict.Remove(e.entityId);}}
class GameManager{public static GameManager Instance;public World World;}
class ConnectionManager{public bool IsServer=true;}class SingletonMonoBehaviour<T>{public static T Instance;}
static class ThreadManager{public static bool IsMainThread()=>true;}
static class GameIO{public static string GetSaveGameDir()=>"unused";}
static class Log{public static void Warning(string value){}}
class RebirthPoiWorldLifecycle{public static RebirthPoiWorldLifecycle Instance=new();public long Generation;public RebirthPoiWorldStore Store;public bool TryGetEvidenceStore(out RebirthPoiWorldStore store){store=Store;return store!=null;}public bool TryGetStore(out RebirthPoiWorldStore store){store=Store;return store!=null;}}
// Metadata doubles for exact already-reviewed production medical observers.
static class RebirthExternalTreatmentEvidenceDeathPatch {static void Prefix(){}static void Postfix(){}}
static class RebirthSelfMedicalPracticeDeathPatch {static void Postfix(){}}
static class UnknownDeathPatch {public static void Prefix(){}}
class Program{
 static int checks;static void Check(bool good,string label){if(!good)throw new Exception("FAIL "+label);checks++;}
 static string H=>new string('a',64);
 sealed class Fixture{
  public World World=new();public EntityAlive Entity=new();public RebirthPoiWorldStore Store;public RebirthPoiIdentity Poi=new("house",0,0,0,0,10,10,10,"forest");public RebirthPoiInheritedActorOutcomes Outcomes;public bool Armed;public double Time;public Guid Token=Guid.NewGuid();
  public Fixture(bool inherit=true){GameManager.Instance=new GameManager{World=World};SingletonMonoBehaviour<ConnectionManager>.Instance=new ConnectionManager();Entity.world=World;Entity.entityId=100;World.Entities.dict.Add(100,Entity);var bytes=Token.ToByteArray();for(int i=0;i<8;i++)Entity.Buffs.SetCustomVar("_rbPoiActorGuid"+i,(bytes[i*2]|bytes[i*2+1]<<8)+1,false);var binding=new RebirthPoiWorldBinding(World,World.worldState.Guid,Path.Combine(Path.GetTempPath(),"purge-actor-"+Guid.NewGuid().ToString("N")),()=>ReferenceEquals(GameManager.Instance.World,World));RebirthPoiWorldStore.TryOpen(binding,out Store,stage=>{if(Armed&&stage=="afterManifestCandidateWritten")throw new IOException("fixture");});Store.TryDiscover(Store.Published,Poi);var generation=Guid.NewGuid();var actor=new RebirthPoiActorObservation(Token,100,"zombieArlene",1);var old=new RebirthPoiPartialObservation(generation,0,1,new[]{new RebirthPoiVolumeObservation(7,H,new[]{actor})});Store.TryObservePartial(Store.Published,Poi,0,old);if(inherit){var tx=Guid.NewGuid();var plan=new RebirthPoiResetPlan(tx,RebirthPoiResetCaller.NaturalRespawn,H,Array.Empty<long>(),new[]{7},Array.Empty<int>(),new[]{new RebirthPoiAuthoredResetExpectation(RebirthPoiAuthoredResetKind.Sleeper,0,H,7,true)});var retained=new RebirthPoiResetActorOutcome(Token,100,0,generation,H,actor.CausalDigest,RebirthPoiPriorActorDisposition.RetainedUnresolved,Guid.NewGuid());var bindings=new RebirthPoiAuthoredResetBindings(plan,new[]{new RebirthPoiAuthoredRuntimeBinding("1:0",H,7,Guid.NewGuid())},0,new[]{retained});Store.TryBeginReset(Store.Published,Poi,0,tx,plan);Store.TryFinishReset(Store.Published,Poi,0,tx,RebirthPoiResetDisposition.Completed,old.RollOverVerifiedReset(plan,bindings),bindings);}Outcomes=new RebirthPoiInheritedActorOutcomes(()=>Store,()=>Time);RebirthPoiWorldLifecycle.Instance.Store=Store;}
  public RebirthPoiActorObservation Saved(){Store.Published.TryGet(Poi,out var record);return record.Observations.Volumes[7].Actors[Token];}
 }
 static void Main(){
  var f=new Fixture();var witness=f.Outcomes.BeforeSetDead(f.Entity);Check(witness!=null&&f.World.Hydrations==0,"direct saved actor capture avoids lazy hydration");f.Entity.Fatal=true;Check(!f.Outcomes.AfterSetDead(witness,true)&&!f.Saved().Dead,"fatal recorded damage without bDead cannot prove original SetDead");f.Entity.bDead=true;Check(!f.Outcomes.AfterSetDead(witness,false)&&!f.Saved().Dead,"skipped original SetDead cannot retire obligation");Check(f.Outcomes.AfterSetDead(witness,true)&&f.Saved().Dead&&f.Saved().TerminalKind==RebirthPoiActorTerminalKind.Death,"successful original SetDead readback persists inherited death");Check(!f.Outcomes.AfterSetDead(witness,true),"same original callback cannot mint second completion");Check(RebirthPoiWorldStore.TryOpen(f.Store.Published.Binding,out var cold)==RebirthPoiStoreResult.Published&&cold.Published.TryGet(f.Poi,out var saved)&&saved.Observations.Volumes[7].Actors[f.Token].Dead,"exact final files preserve inherited native death");
  f=new Fixture();Check(f.Outcomes.BeforeUnload(f.World,f.Entity,EnumRemoveEntityReason.Unloaded)==null&&!f.Saved().Dead,"normal Unloaded preserves inherited obligation");f.Entity.Marked=true;f.Entity.IsDespawned=true;witness=f.Outcomes.BeforeUnload(f.World,f.Entity,EnumRemoveEntityReason.Despawned);Check(witness!=null,"exact original marked Despawned captures saved actor scope");Check(!f.Outcomes.AfterUnload(witness,true,EnumRemoveEntityReason.Despawned)&&!f.Saved().Dead,"despawn post-body presence cannot prove removal");f.World.Entities.dict.Remove(100);Check(!f.Outcomes.AfterUnload(witness,false,EnumRemoveEntityReason.Despawned),"skipped original unload cannot prove absence");Check(f.Outcomes.AfterUnload(witness,true,EnumRemoveEntityReason.Despawned)&&f.Saved().Dead&&f.Saved().TerminalKind==RebirthPoiActorTerminalKind.NativeDespawn,"successful original permanent despawn retires without calling it death");Check(RebirthPoiWorldStore.TryOpen(f.Store.Published.Binding,out cold)==RebirthPoiStoreResult.Published&&cold.Published.TryGet(f.Poi,out saved)&&saved.Observations.Volumes[7].Actors[f.Token].TerminalKind==RebirthPoiActorTerminalKind.NativeDespawn,"native despawn kind survives exact-file cold read");
  f=new Fixture();witness=f.Outcomes.BeforeSetDead(f.Entity);f.Entity.bDead=true;GameManager.Instance.World=new World();Check(!f.Outcomes.AfterSetDead(witness,true),"replacement world cannot publish original death");f=new Fixture();witness=f.Outcomes.BeforeSetDead(f.Entity);f.World.Entities.dict[100]=new EntityAlive{world=f.World,entityId=100,bDead=true};f.Entity.bDead=true;Check(!f.Outcomes.AfterSetDead(witness,true)&&!f.Saved().Dead,"same ID replacement actor cannot discharge original GUID obligation");
  f=new Fixture();witness=f.Outcomes.BeforeSetDead(f.Entity);f.Armed=true;f.Entity.bDead=true;Check(f.Outcomes.AfterSetDead(witness,true)&&f.Store.HasPending&&f.Outcomes.PendingCount==1&&!f.Saved().Dead,"uncertain save retains original death receipt and published predecessor");var originalReceipt=witness.Receipt;f.Armed=false;f.Time=1;f.Outcomes.Pulse();Check(f.Outcomes.PendingCount==0&&f.Saved().DeathReceipt==originalReceipt,"event-time retry publishes exact original death candidate");
  RebirthPoiInheritedActorOutcomeHooks.Install();Check(RebirthPoiInheritedActorOutcomeHooks.IsReady,"actual owned passive installer qualifies native-double ABI");var originalError=new IOException("native");var returned=typeof(RebirthPoiInheritedActorOutcomeHooks).GetMethod("Failed",BindingFlags.Static|BindingFlags.NonPublic).Invoke(null,new object[]{originalError});Check(ReferenceEquals(returned,originalError),"original native exception preserved without death/removal implication");  f=new Fixture();var hooks=typeof(RebirthPoiInheritedActorOutcomeHooks);var flags=BindingFlags.Static|BindingFlags.NonPublic;var deathArgs=new object[]{f.Entity,null};hooks.GetMethod("DeathBefore",flags).Invoke(null,deathArgs);Check(deathArgs[1]!=null,"actual passive death prefix captures original saved actor without volume membership");f.Entity.SetDead();hooks.GetMethod("DeathAfter",flags).Invoke(null,new object[]{true,deathArgs[1]});Check(f.Saved().Dead&&f.Saved().TerminalKind==RebirthPoiActorTerminalKind.Death,"actual passive original death postfix persists saved inherited terminal");
  f=new Fixture();f.Entity.IsDespawned=true;f.Entity.Marked=true;var unloadArgs=new object[]{f.World,f.Entity,EnumRemoveEntityReason.Despawned,null};hooks.GetMethod("UnloadBefore",flags).Invoke(null,unloadArgs);Check(unloadArgs[3]!=null,"actual passive unload prefix captures original GUID and generation");f.World.unloadEntity(f.Entity,EnumRemoveEntityReason.Despawned);hooks.GetMethod("UnloadAfter",flags).Invoke(null,new object[]{true,EnumRemoveEntityReason.Despawned,unloadArgs[3]});Check(f.Saved().TerminalKind==RebirthPoiActorTerminalKind.NativeDespawn,"actual passive unload postfix distinguishes successful permanent despawn");
  f=new Fixture();deathArgs=new object[]{f.Entity,null};hooks.GetMethod("DeathBefore",flags).Invoke(null,deathArgs);f.Entity.SetDead();hooks.GetMethod("DeathAfter",flags).Invoke(null,new object[]{false,deathArgs[1]});Check(!f.Saved().Dead,"actual skipped-body postfix cannot invent death proof");
  var terminal=f.Saved();var actorDeath=new RebirthPoiActorObservation(terminal.Token,terminal.EntityId,terminal.ClassName,terminal.SpawnPoint,Guid.NewGuid(),60,terminal.Restorations,terminal.Checkpoint,terminal.Inheritance,RebirthPoiActorTerminalKind.NativeDespawn);var recordPartial=new RebirthPoiPartialObservation(Guid.NewGuid(),1,1,new[]{new RebirthPoiVolumeObservation(7,H,new[]{actorDeath},terminal.Inheritance.ResetTransaction)});var encoded=RebirthPoiPartialObservation.Write(recordPartial);Check(RebirthPoiPartialObservation.Read(encoded).Volumes[7].Actors[terminal.Token].TerminalKind==RebirthPoiActorTerminalKind.NativeDespawn,"strict v5 terminal despawn payload round trip");encoded.SetAttributeValue("version",4);try{RebirthPoiPartialObservation.Read(encoded);throw new Exception("accepted forward kind in old schema");}catch(FormatException){Check(true,"legacy v4 rejects forward terminal kind");}
  f=new Fixture();var fenced=new RebirthPoiInheritedActorOutcomes(()=>f.Store,()=>f.Time,()=>RebirthPoiWorldLifecycle.Instance.Generation);witness=fenced.BeforeSetDead(f.Entity);f.Entity.SetDead();RebirthPoiWorldLifecycle.Instance.Generation++;Check(!fenced.AfterSetDead(witness,true)&&!f.Saved().Dead,"same native world late callback rejected by original lifecycle generation");
f=new Fixture();f.Store.Published.TryGet(f.Poi,out var beforeReset);var resetTx=Guid.NewGuid();var resetPlan=new RebirthPoiResetPlan(resetTx,RebirthPoiResetCaller.Quest,H,new[]{1L},new[]{7},Array.Empty<int>(),new[]{new RebirthPoiAuthoredResetExpectation(RebirthPoiAuthoredResetKind.Sleeper,0,H,7,true)});Check(f.Store.TryBeginReset(f.Store.Published,f.Poi,1,resetTx,resetPlan)==RebirthPoiStoreResult.Published,"original reset intent commits before terminal callback");witness=f.Outcomes.BeforeSetDead(f.Entity);Check(witness!=null&&witness.Obligations[0].Reset==resetTx,"pending reset actor captures exact original transaction");f.Entity.SetDead();Check(f.Outcomes.AfterSetDead(witness,true)&&f.Outcomes.PendingCount==1,"death during reset intent retains original terminal receipt");var priorActor=beforeReset.Observations.Volumes[7].Actors[f.Token];var carry=new RebirthPoiResetActorOutcome(f.Token,100,1,beforeReset.Observations.EffectiveGeneration(beforeReset.Observations.Volumes[7]),H,priorActor.CausalDigest,RebirthPoiPriorActorDisposition.RetainedUnresolved,Guid.NewGuid());var resetBindings=new RebirthPoiAuthoredResetBindings(resetPlan,new[]{new RebirthPoiAuthoredRuntimeBinding("1:0",H,7,Guid.NewGuid())},1,new[]{carry});Check(f.Store.TryFinishReset(f.Store.Published,f.Poi,1,resetTx,RebirthPoiResetDisposition.Completed,beforeReset.Observations.RollOverVerifiedReset(resetPlan,resetBindings),resetBindings)==RebirthPoiStoreResult.Published,"successor conservatively retains original obligation");f.Time=2;f.Outcomes.Pulse();Check(f.Outcomes.PendingCount==0&&f.Saved().Dead&&f.Saved().DeathReceipt==witness.Receipt,"same native terminal receipt retires exact inherited successor");Check(f.World.Hydrations==0,"reset terminal transfer never hydrates missing actors");
f=new Fixture(false);f.Store.Published.TryGet(f.Poi,out beforeReset);resetTx=Guid.NewGuid();resetPlan=new RebirthPoiResetPlan(resetTx,RebirthPoiResetCaller.Quest,H,new[]{1L},new[]{7},Array.Empty<int>(),new[]{new RebirthPoiAuthoredResetExpectation(RebirthPoiAuthoredResetKind.Sleeper,0,H,7,true)});f.Store.TryBeginReset(f.Store.Published,f.Poi,0,resetTx,resetPlan);witness=f.Outcomes.BeforeSetDead(f.Entity);Check(witness!=null,"first reset captures ordinary actor without prior inheritance");f.Entity.SetDead();Check(f.Outcomes.AfterSetDead(witness,true)&&f.Outcomes.PendingCount==1,"ordinary actor death held behind pending reset intent");priorActor=beforeReset.Observations.Volumes[7].Actors[f.Token];carry=new RebirthPoiResetActorOutcome(f.Token,100,0,beforeReset.Observations.EffectiveGeneration(beforeReset.Observations.Volumes[7]),H,priorActor.CausalDigest,RebirthPoiPriorActorDisposition.RetainedUnresolved,Guid.NewGuid());resetBindings=new RebirthPoiAuthoredResetBindings(resetPlan,new[]{new RebirthPoiAuthoredRuntimeBinding("1:0",H,7,Guid.NewGuid())},0,new[]{carry});f.Store.TryFinishReset(f.Store.Published,f.Poi,0,resetTx,RebirthPoiResetDisposition.Completed,beforeReset.Observations.RollOverVerifiedReset(resetPlan,resetBindings),resetBindings);f.Time=2;f.Outcomes.Pulse();Check(f.Outcomes.PendingCount==0&&f.Saved().Dead&&f.Saved().DeathReceipt==witness.Receipt,"ordinary actor native death survives its first inherited successor");
var deathInfo=HarmonyLib.Harmony.GetPatchInfo(typeof(EntityAlive).GetMethod("SetDead"));var medicalPrefix=new HarmonyLib.Patch{owner="medical",PatchMethod=HarmonyLib.AccessTools.Method(typeof(RebirthExternalTreatmentEvidenceDeathPatch),"Prefix")};var medicalPostfix=new HarmonyLib.Patch{owner="medical",PatchMethod=HarmonyLib.AccessTools.Method(typeof(RebirthExternalTreatmentEvidenceDeathPatch),"Postfix")};var practicePostfix=new HarmonyLib.Patch{owner="practice",PatchMethod=HarmonyLib.AccessTools.Method(typeof(RebirthSelfMedicalPracticeDeathPatch),"Postfix")};deathInfo.Prefixes.Add(medicalPrefix);deathInfo.Postfixes.Add(medicalPostfix);deathInfo.Postfixes.Add(practicePostfix);Check(RebirthPoiInheritedActorOutcomeHooks.IsReady,"exact current medical observer methods coexist with native death proof");
var observer=new HarmonyLib.Patch{owner="other-mod",PatchMethod=typeof(UnknownDeathPatch).GetMethod("Prefix")};deathInfo.Prefixes.Add(observer);Check(RebirthPoiInheritedActorOutcomeHooks.IsReady,"foreign observer presence does not disable native outcome tracking");deathInfo.Transpilers.Add(medicalPostfix);Check(RebirthPoiInheritedActorOutcomeHooks.IsReady,"transpiler presence alone does not replace actual completion checks");deathInfo.Transpilers.Remove(medicalPostfix);deathInfo.Prefixes.Remove(observer);

f=new Fixture(false);f.Store.Published.TryGet(f.Poi,out beforeReset);resetTx=Guid.NewGuid();resetPlan=new RebirthPoiResetPlan(resetTx,RebirthPoiResetCaller.Quest,H,new[]{1L},new[]{7},Array.Empty<int>(),new[]{new RebirthPoiAuthoredResetExpectation(RebirthPoiAuthoredResetKind.Sleeper,0,H,7,true)});f.Store.TryBeginReset(f.Store.Published,f.Poi,0,resetTx,resetPlan);f.Entity.IsDespawned=true;f.Entity.Marked=true;witness=f.Outcomes.BeforeUnload(f.World,f.Entity,EnumRemoveEntityReason.Despawned);Check(witness!=null,"ordinary marked actor captures original native removal during reset");f.World.unloadEntity(f.Entity,EnumRemoveEntityReason.Despawned);Check(f.Outcomes.AfterUnload(witness,true,EnumRemoveEntityReason.Despawned)&&f.Outcomes.PendingCount==1,"successful original unload retained until reset successor commits");priorActor=beforeReset.Observations.Volumes[7].Actors[f.Token];carry=new RebirthPoiResetActorOutcome(f.Token,100,0,beforeReset.Observations.EffectiveGeneration(beforeReset.Observations.Volumes[7]),H,priorActor.CausalDigest,RebirthPoiPriorActorDisposition.RetainedUnresolved,Guid.NewGuid());resetBindings=new RebirthPoiAuthoredResetBindings(resetPlan,new[]{new RebirthPoiAuthoredRuntimeBinding("1:0",H,7,Guid.NewGuid())},0,new[]{carry});f.Store.TryFinishReset(f.Store.Published,f.Poi,0,resetTx,RebirthPoiResetDisposition.Completed,beforeReset.Observations.RollOverVerifiedReset(resetPlan,resetBindings),resetBindings);f.Time=2;f.Outcomes.Pulse();Check(f.Outcomes.PendingCount==0&&f.Saved().Dead&&f.Saved().TerminalKind==RebirthPoiActorTerminalKind.NativeDespawn,"native removal retires exact retained successor without inventing death");
Console.WriteLine("PASS "+checks+" actual actor outcome/store/callback assertions; native and Harmony doubles; no live native/game proof");
 }
}
internal static class RebirthPurgeKillContributor {internal static Func<EntityAlive,string> Resolve;internal static string Capture(EntityAlive entity)=>Resolve?.Invoke(entity);}
