using System;
using System.IO;
using System.Text;
using System.Collections.Generic;
public class PooledBinaryReader : BinaryReader { public PooledBinaryReader(Stream s):base(s){} }
public class PooledBinaryWriter : BinaryWriter { public PooledBinaryWriter(Stream s):base(s){} }
public struct Vector3i { public int x,y,z; public Vector3i(int a,int b,int c){x=a;y=b;z=c;} }
public struct PropRef { public static PropRef Read(PooledBinaryReader r){throw new Exception("Prop reader forbidden");} }
public struct BlockValueRef { public bool TryGetBlockPos(out Vector3i value){value=pos;return true;} public static BlockValueRef None; public Vector3i pos; public BlockValueRef(Vector3i v){pos=v;} public BlockValueRef(PropRef v){pos=default(Vector3i);} /*BLOCKREF_READ*/ }
public class Shape {public bool terrain;public bool IsTerrain(){return terrain;}}
public class Block {public Shape shape=new Shape();public bool IsTerrainDecoration;}
public class BlockPlantGrowing:Block {}
public static class MarchingCubes {public const sbyte DensityAir=-127;}
public struct BlockValue {public Block Block {get{return new BlockPlantGrowing();}} public uint rawData; public int damage; public int type {get{return (int)(rawData&65535);}} public BlockValue(uint r,int d){rawData=r;damage=d;} /*BLOCKVALUE_READ*/ }
public struct TextureFullArray { public long[] values; public bool IsDefault {get{return values==null||values[0]==0;}} public long this[int index]{get{return values==null?0:values[index];}} /*TEXTURE_READ*/ }
public class BlockChangeInfo {
 [Flags] public enum Flags:byte {ChangeBlockValue=1,ChangeDamage=2,ChangeDensity=4,ForceDensity=8,UpdateLight=16,ChangeTexture=32}
 public BlockValueRef blockValueRef; public int changedByEntityId; public bool bChangeBlockValue,bChangeDensity,bForceDensity,bUpdateLight,bChangeDamage,bChangeTexture; public BlockValue blockValue; public sbyte density;
 public TextureFullArray textureFull = new TextureFullArray{values=new long[1]};
 /*BLOCKCHANGE_READ*/
}
public class PlatformUserIdentifierAbs { public byte[] canonical; public void ToStream(PooledBinaryWriter w){w.Write(canonical);} }
public class ClientInfo {public int entityId;public PlatformUserIdentifierAbs PlatformId,CrossplatformId;}
public class ConnectionManager {public bool IsServer=true;}
public class SingletonMonoBehaviour<T> where T:new(){public static T Instance=new T();}
public class NetPackage {public ClientInfo Sender;public virtual void read(PooledBinaryReader r){}public virtual void write(PooledBinaryWriter w){w.Write((ushort)124);}public virtual void ProcessPackage(World w,GameManager gm){}public bool ValidUserIdForSender(PlatformUserIdentifierAbs id){return object.ReferenceEquals(id,Sender.PlatformId)||object.ReferenceEquals(id,Sender.CrossplatformId);}public bool ValidEntityIdForSender(int id){return id==Sender.entityId;}}
public class NetPackageSetBlock {public static int Writes,Executions;public static bool ThrowWrite;public void ProcessPackage(World w,GameManager gm){Executions++;}public void write(PooledBinaryWriter w){Writes++;if(ThrowWrite)throw new InvalidDataException("serialize fixture");w.Write((ushort)123);persistentPlayerId.ToStream(w);w.Write((short)blockChanges.Count);foreach(var c in blockChanges){w.Write((byte)1);w.Write(c.blockValueRef.pos.x);w.Write(c.blockValueRef.pos.y);w.Write(c.blockValueRef.pos.z);w.Write(c.changedByEntityId);byte flags=(byte)((c.bChangeBlockValue?1:0)|(c.bChangeDamage?2:0)|(c.bChangeDensity?4:0)|(c.bForceDensity?8:0)|(c.bUpdateLight?16:0)|(c.bChangeTexture?32:0));w.Write(flags);if(c.bChangeBlockValue){w.Write(c.blockValue.rawData);w.Write((ushort)c.blockValue.damage);}if(c.bChangeDensity)w.Write(c.density);if(c.bChangeTexture)w.Write(c.textureFull[0]);}w.Write(localPlayerThatChanged);} public PlatformUserIdentifierAbs persistentPlayerId;public int localPlayerThatChanged;public List<BlockChangeInfo> blockChanges;public ClientInfo Sender; }
public static class NetPackageManager {public static int Factory;public static int GetPackageId(Type t){return 123;}public static T GetPackage<T>() where T:new(){Factory++;return new T();}}
public static class StreamUtils {
 public static int Readers;
 public static Vector3i ReadVector3i(PooledBinaryReader r){return new Vector3i(r.ReadInt32(),r.ReadInt32(),r.ReadInt32());}
 public static MemoryStream ToBlob(Action<PooledBinaryWriter> a){var m=new MemoryStream();var w=new PooledBinaryWriter(m);a(w);w.Flush();return m;}
 public static void FromBlob(MemoryStream m,Action<PooledBinaryReader> a){Readers++;var r=new PooledBinaryReader(m);a(r);}
}
public class TypedMetadataValue {public enum TypeTag {None,Float,Integer,String} public TypeTag tag;public object value;public TypeTag GetTypeTag(){return tag;}public object GetValue(){return value;}}
public class ItemValue {public struct Stat {public int type;public bool isBoosted;public short value;}public int type,Meta;public float UseTimes;public ushort Quality,Seed;public byte Flags,SelectedAmmoTypeIndex;public TextureFullArray TextureFullArray;public Stat[] Stats;public ItemValue[] modifications,cosmeticMods;public Dictionary<string,TypedMetadataValue> Metadata;public BlockValue ToBlockValue(){return new BlockValue((uint)type,0);}}
public class Inventory {public ItemInventoryData holdingItemData;public int SlotCount=10,SelectedSlot;public ItemStack holdingItemStack;public ItemValue holdingItemItemValue;}
public class ItemStack {public int count;}
public class EntityPlayerLocal:EntityPlayer {public int entityId=7;}
public class EntityPlayer {public Inventory inventory;}
public class World {public object GetTileEntity(Vector3i pos){return null;}public bool remote;public EntityPlayer player;public EntityPlayer GetPrimaryPlayer(){return player;}public BlockValue block;public bool IsRemote(){return remote;}public object GetEntity(int id){return player;}public BlockValue GetBlock(Vector3i pos){return block;}}
public class GameManager {public static GameManager Instance;public World World;public bool IsEditMode(){return false;}}
public class ItemInventoryData {public EntityPlayer holdingEntity;public World world;public bool IsBlock=true;public ItemValue itemValue;}
public class BlockPlacement {public class Result {public Vector3i blockPos;}}
/*ENVELOPE*/
public class PacketAdmissionDouble:ISeedPlacementReviewAdmission {public bool ThrowDispose;public int Completed,Disposed;public void CompleteObservedCommit(){Completed++;}public void Dispose(){Disposed++;if(ThrowDispose)throw new InvalidOperationException("dispose fixture");}}
public class PacketOwnerDouble:ISeedPlacementReviewOwner {public int Terminal,Admits;public bool ReplaceOwner;public PacketAdmissionDouble Admission=new PacketAdmissionDouble();public PacketOwnerDouble Replacement;public void ReleaseOrRetainNativeAndReconcile(ClientInfo s,World w,ulong e,ulong n,SeedPlacementIntentCodecReview.Intent? i,NetPackageSetBlock p,ISeedPlacementReviewAdmission a){Terminal++;}public bool TryAdmit(ClientInfo s,World w,GameManager gm,ulong e,ulong n,SeedPlacementIntentCodecReview.Intent i,NetPackageSetBlock p,out ISeedPlacementReviewAdmission a){Admits++;a=Admission;if(ReplaceOwner)NetPackageRebirthSeedPlacementReview.Owner=Replacement;return true;}}
public class ClientOwnerDouble:ISeedPlacementClientReviewOwner,ISeedPlacementRetainedCommandReview {
 public int Retired,Marks,Binds,SendReturns;public bool Sent,Prediction,AllowRetain=true,AllowBind=true;public SeedPlacementOriginalCommandReview Original;public SeedPlacementConsumedEnvelopeReview Capture;
 public bool IsAuthoredHumanSeedCommand(ItemInventoryData d,BlockPlacement.Result p,BlockValue t){return true;}
 public bool TryGetBoundSessionCommand(World w,EntityPlayerLocal p,out ulong e,out ulong n){e=1;n=2;return true;}
 public bool TryRetainOriginalCommand(World w,EntityPlayerLocal p,SeedPlacementOriginalCommandReview original,out ISeedPlacementRetainedCommandReview retained){Original=original;retained=AllowRetain?this:null;return AllowRetain;}
 public void MarkNativeInvocationStarted(){Marks++;}
 public bool TryBindConsumedEnvelope(SeedPlacementConsumedEnvelopeReview capture){Binds++;Capture=capture;return AllowBind&&object.ReferenceEquals(Original,capture.Original);}
 public void ObserveNativeSendReturn(SeedPlacementConsumedEnvelopeReview capture){if(!object.ReferenceEquals(capture,Capture))throw new Exception("capture identity");SendReturns++;}
 public void Retire(bool envelopeConsumed,bool predictionMayHaveStarted){Retired++;Sent=envelopeConsumed;Prediction=predictionMayHaveStarted;}
}
public class HostPolicyDouble:ISeedPlacementHostPolicyReview {public bool Validate(ClientInfo s,World w,GameManager gm,SeedPlacementSessionAuthority.Reservation r,SeedPlacementIntentCodecReview.Intent i,NetPackageSetBlock p){return true;}}
/*CONSUMED_CAPTURE*/
public enum AdvancedFarmingPlantOrigin {Unknown,Player,System}
public class TileEntityPlantGrowingRebirth {public AdvancedFarmingPlantOrigin PlantOrigin;public ulong PlantIncarnation,StateRevision;}
public static class SeedPlacementSessionAuthority {public class Reservation{public int Actor;}public static int Reservations;private static HashSet<string> consumed=new HashSet<string>();public static bool TryReserve(ClientInfo sender,World w,ulong e,ulong n,out Reservation result){result=null;if(!consumed.Add(e+":"+n))return false;Reservations++;result=new Reservation{Actor=sender.entityId};return true;}public static bool IsCurrent(Reservation r){return true;}public static bool IsBoundToSender(Reservation r,ClientInfo s,World w,int actor){return r.Actor==actor&&s.entityId==actor;}}
public static class AdvancedFarmingRemotePlantingAdmissionReview {public class RemoteScope:IDisposable{public bool BeforeNativeExecution(){return true;}public bool Complete(){return false;}public void Dispose(){}}public static RemoteScope Begin(SeedPlacementSessionAuthority.Reservation r,SeedPlacementOriginalCommandReview c,World w,int actor){return new RemoteScope();}}
internal class TerminalDouble:ISeedPlacementTerminalBoundaryReview {public int Count;public void ObserveTerminal(ClientInfo s,World w,ulong e,ulong n,SeedPlacementIntentCodecReview.Intent? i,NetPackageSetBlock p,SeedPlacementHostOutcomeReview o,bool may,SeedPlacementHostOwnerReview.TerminalReceipt receipt){Count++;}}
/*HOST_OWNER*/
/*ORIGINAL_COMMAND*/
/*CLIENT_SCOPE*/
/*INTENT_CODEC*/
/*DECODER*/
public static class DecoderFixture {
 static int checks;
 static void Check(bool value,string label){checks++;if(!value)throw new Exception(label);}
 static byte[] Frame(byte[] identity,byte flags=1,short count=1,byte tag=1,int actor=7,int local=7){using(var m=new MemoryStream()){var w=new BinaryWriter(m);w.Write((ushort)123);w.Write(identity);w.Write(count);w.Write(tag);w.Write(1);w.Write(2);w.Write(3);w.Write(actor);w.Write(flags);if((flags&1)!=0){w.Write((uint)42);w.Write((ushort)12);}if((flags&4)!=0)w.Write((sbyte)-12);if((flags&32)!=0)w.Write((long)987654321);w.Write(local);return m.ToArray();}}
 static void Refuse(byte[] b,ClientInfo s,string name,bool beforeRead=true){int f=NetPackageManager.Factory,r=StreamUtils.Readers;NetPackageSetBlock p;Check(!SeedPlacementNativeDecoderReview.TryDecode(b,s,out p)&&p==null,name);Check(NetPackageManager.Factory==f,name+" factory");if(beforeRead)Check(StreamUtils.Readers==r,name+" reader");}
 public static void Run(){var platform=new byte[]{1,1,3,65,66,67,2,68,69};var cross=new byte[]{1,1,1,88,1,89};var sender=new ClientInfo{entityId=7,PlatformId=new PlatformUserIdentifierAbs{canonical=platform},CrossplatformId=new PlatformUserIdentifierAbs{canonical=cross}};
 foreach(var identity in new[]{platform,cross})foreach(byte flags in new byte[]{1,17,5,13,33,53,61}){NetPackageSetBlock p;Check(SeedPlacementNativeDecoderReview.TryDecode(Frame(identity,flags),sender,out p),"valid");Check(p.blockChanges.Count==1&&p.Sender==sender&&p.blockChanges[0].blockValue.rawData==42,"payload");if((flags&32)!=0)Check(p.blockChanges[0].textureFull.values[0]==987654321,"texture");}
 var good=Frame(platform);for(int n=0;n<good.Length;n++){var shortFrame=new byte[n];Array.Copy(good,shortFrame,n);Refuse(shortFrame,sender,"trunc"+n);}
 var trailing=new byte[good.Length+1];Array.Copy(good,trailing,good.Length);Refuse(trailing,sender,"trailing");
 var badId=(byte[])good.Clone();badId[0]=124;Refuse(badId,sender,"id");
 foreach(short count in new short[]{-1,0,2,32767})Refuse(Frame(platform,1,count),sender,"count");
 foreach(byte tag in new byte[]{0,2,255})Refuse(Frame(platform,1,1,tag),sender,"reference");
 foreach(byte flags in new byte[]{0,2,3,9,65,129,255})Refuse(Frame(platform,flags),sender,"flags");
 Refuse(Frame(new byte[]{0}),sender,"identity");Refuse(good,null,"sender");
 Refuse(Frame(platform,1,1,1,8),sender,"embeddedactor");Refuse(Frame(platform,1,1,1,7,8),sender,"actor");
  var seed=new ItemValue{type=42,Meta=13,Seed=123,Quality=5,UseTimes=float.NaN,Stats=new ItemValue.Stat[]{new ItemValue.Stat{type=8,isBoosted=true,value=-12}},Metadata=new Dictionary<string,TypedMetadataValue>(StringComparer.OrdinalIgnoreCase){["Color"]=new TypedMetadataValue{tag=TypedMetadataValue.TypeTag.String,value="green"}}};
 var empty=new ItemValue{Seed=456};seed.modifications=new[]{empty};byte[] identityBytes;Check(SeedPlacementIntentCodecReview.TrySeedIdentity(seed,out identityBytes),"full seed");Check(empty.Seed==456&&seed.Seed==123,"unchanged empty seed");
 var encoded=SeedPlacementIntentCodecReview.Write(2,3,new Vector3i(1,2,3),new BlockValue(42,12),new BlockValue(9,0),seed);SeedPlacementIntentCodecReview.Intent intent;Check(SeedPlacementIntentCodecReview.TryRead(encoded,out intent),"intent");Check(intent.Slot==2&&intent.Seed.Length==identityBytes.Length,"intent fields");
 for(int n=0;n<encoded.Length;n++){var truncated=new byte[n];Array.Copy(encoded,truncated,n);Check(!SeedPlacementIntentCodecReview.TryRead(truncated,out intent),"intent trunc");}
 seed.modifications=new[]{seed};Check(!SeedPlacementIntentCodecReview.TrySeedIdentity(seed,out identityBytes)&&identityBytes==null,"cycle");seed.modifications=new ItemValue[256];Check(!SeedPlacementIntentCodecReview.TrySeedIdentity(seed,out identityBytes),"count");seed.modifications=null;
 seed.Metadata["Color"].value=new string('x',1025);Check(!SeedPlacementIntentCodecReview.TrySeedIdentity(seed,out identityBytes),"string");seed.Metadata["Color"].value="\uD800";Check(!SeedPlacementIntentCodecReview.TrySeedIdentity(seed,out identityBytes),"surrogate");seed.Metadata["Color"].value="green";
 var held=new Inventory{SelectedSlot=2,holdingItemStack=new ItemStack{count=1},holdingItemItemValue=seed};var world=new World{player=new EntityPlayer{inventory=held},block=new BlockValue(9,0)};var gm=new GameManager{World=world};NetPackageSetBlock packet;Check(SeedPlacementNativeDecoderReview.TryDecode(Frame(platform,21),sender,out packet),"snapshot packet");packet.blockChanges[0].density=MarchingCubes.DensityAir;Check(SeedPlacementIntentCodecReview.TryRead(SeedPlacementIntentCodecReview.Write(2,3,new Vector3i(1,2,3),new BlockValue(42,12),new BlockValue(9,0),seed),out intent),"snapshot intent");Check(SeedPlacementIntentCodecReview.ValidateSenderSnapshot(sender,world,gm,intent,packet),"snapshot valid");held.SelectedSlot=3;Check(!SeedPlacementIntentCodecReview.ValidateSenderSnapshot(sender,world,gm,intent,packet),"snapshot slot");held.SelectedSlot=2;seed.Seed++;Check(!SeedPlacementIntentCodecReview.ValidateSenderSnapshot(sender,world,gm,intent,packet),"snapshot fullseed");seed.Seed--;world.block=new BlockValue(10,0);Check(!SeedPlacementIntentCodecReview.ValidateSenderSnapshot(sender,world,gm,intent,packet),"stale old");
 var local=new EntityPlayerLocal{inventory=held};world.player=local;world.remote=true;world.block=new BlockValue(9,0);GameManager.Instance=gm;var data=new ItemInventoryData{world=world,holdingEntity=local,itemValue=seed};held.holdingItemData=data;var owner=new ClientOwnerDouble();SeedPlacementClientScopeReview.ClientOwner=owner;
 NetPackageRebirthSeedPlacementReview consumedEnvelope=null;using(var scope=SeedPlacementClientScopeReview.Begin(data,new BlockPlacement.Result{blockPos=new Vector3i(1,2,3)},new BlockValue(42,12))){Check(scope!=null,"client begin preprediction");NetPackageRebirthSeedPlacementReview envelope;Check(!SeedPlacementClientScopeReview.TryConsumeMatchingSend(packet,out envelope),"beforeprediction refuses");Check(scope.BeforeNativeInvocation()&&owner.Marks==1,"retained mark native once");world.block=new BlockValue(42,12);Check(SeedPlacementClientScopeReview.TryConsumeMatchingSend(packet,out envelope)&&envelope!=null,"one client send");consumedEnvelope=envelope;bool duplicate=false;try{SeedPlacementClientScopeReview.TryConsumeMatchingSend(packet,out envelope);}catch(InvalidDataException){duplicate=true;}Check(duplicate&&NetPackageSetBlock.Writes==1,"duplicate suppressed");Check(!SeedPlacementClientScopeReview.ObserveNativeSendReturned(new NetPackageRebirthSeedPlacementReview()),"wrong envelope return closed");Check(SeedPlacementClientScopeReview.ObserveNativeSendReturned(consumedEnvelope)&&owner.SendReturns==1,"exact native nominal return capture");Check(!SeedPlacementClientScopeReview.ObserveNativeSendReturned(consumedEnvelope)&&owner.SendReturns==1,"duplicate native return closed");}
 Check(owner.Retired==1&&owner.Sent,"client retirement");NetPackageRebirthSeedPlacementReview after;Check(!SeedPlacementClientScopeReview.TryConsumeMatchingSend(packet,out after),"disposed scope");Check(held.holdingItemStack.count==1,"no second debit");Check(!SeedPlacementClientScopeReview.ObserveNativeSendReturned(consumedEnvelope)&&owner.SendReturns==1,"disposed nominal return closed");
 var receiptIntent=new SeedPlacementIntentCodecReview.Intent{Slot=2,Position=new Vector3i(1,2,3),Target=new BlockValue(42,12),ExpectedOld=new BlockValue(9,0),Seed=new byte[]{4,5,6}};
 var original=SeedPlacementOriginalCommandReview.Capture(1,2,7,3,receiptIntent);receiptIntent.Seed[0]=99;Check(original.MatchesSeedIdentity(new byte[]{4,5,6}),"receipt input detached");var copy=original.CopySeedIdentity();copy[1]=88;Check(original.MatchesSeedIdentity(new byte[]{4,5,6}),"receipt output detached");Check(!original.MatchesSeedIdentity(null)&&!original.MatchesSeedIdentity(new byte[]{4,5})&&!original.MatchesSeedIdentity(new byte[]{4,5,7}),"receipt mismatch");Check(original.Actor==7&&original.OriginalCount==3&&original.Slot==2&&original.Position.x==1&&original.Epoch==1&&original.Nonce==2,"receipt primitive fields");
 for(int kind=0;kind<8;kind++){var invalid=receiptIntent;invalid.Seed=new byte[]{1};ulong e=1,n=2;int actor=7,count=1;if(kind==0)e=0;if(kind==1)n=0;if(kind==2)actor=0;if(kind==3)count=0;if(kind==4)invalid.Slot=-1;if(kind==5)invalid.Seed=null;if(kind==6)invalid.Seed=new byte[0];if(kind==7)invalid.Seed=new byte[8193];bool refused=false;try{SeedPlacementOriginalCommandReview.Capture(e,n,actor,count,invalid);}catch(InvalidDataException){refused=true;}Check(refused,"receipt invalid shape"+kind);}
 var uncertain=new SeedPlacementHostOutcomeReview(original,SeedPlacementHostDispositionReview.NativeExecutionUncertain,new BlockValue(999,3),0,0);Check(uncertain.ObservedBlock.rawData==999&&uncertain.PlantIncarnation==0,"uncertain partial target allowed no commit");
 var committed=new SeedPlacementHostOutcomeReview(original,SeedPlacementHostDispositionReview.Committed,new BlockValue(42,12),5,6);Check(committed.PlantIncarnation==5&&committed.StateRevision==6&&object.ReferenceEquals(committed.Original,original),"valid committed identity");
 for(int kind=0;kind<4;kind++){bool refused=false;try{new SeedPlacementHostOutcomeReview(original,SeedPlacementHostDispositionReview.Committed,new BlockValue(kind==2?43u:42u,kind==3?13:12),kind==0?0UL:5UL,kind==1?0UL:6UL);}catch(InvalidDataException){refused=true;}Check(refused,"committed invalid"+kind);}
 Check(SeedPlacementIntentCodecReview.MatchesChange(intent,packet.blockChanges[0]),"full native change");packet.blockChanges[0].density++;Check(!SeedPlacementIntentCodecReview.MatchesChange(intent,packet.blockChanges[0]),"density bound");packet.blockChanges[0].density--;packet.blockChanges[0].bUpdateLight=false;Check(!SeedPlacementIntentCodecReview.MatchesChange(intent,packet.blockChanges[0]),"light bound");packet.blockChanges[0].bUpdateLight=true;
 seed.TextureFullArray=new TextureFullArray{values=new long[]{777}};Check(SeedPlacementIntentCodecReview.TryRead(SeedPlacementIntentCodecReview.Write(2,3,new Vector3i(1,2,3),new BlockValue(42,12),new BlockValue(9,0),seed),out intent)&&intent.Flags==33&&intent.Texture==777&&intent.Density==0,"native texture route");var textured=new BlockChangeInfo{bChangeBlockValue=true,bChangeTexture=true,blockValue=new BlockValue(42,12),textureFull=new TextureFullArray{values=new long[]{777}}};Check(SeedPlacementIntentCodecReview.MatchesChange(intent,textured),"texture exact");textured.textureFull.values[0]=778;Check(!SeedPlacementIntentCodecReview.MatchesChange(intent,textured),"texture mismatch");
 seed.TextureFullArray=new TextureFullArray();world.remote=false;world.block=new BlockValue(9,0);var forged=intent;byte[] plainIdentity;Check(SeedPlacementIntentCodecReview.TrySeedIdentity(seed,out plainIdentity),"plain host seed");forged.Seed=plainIdentity;textured.textureFull.values[0]=777;textured.changedByEntityId=7;textured.blockValueRef=new BlockValueRef(new Vector3i(1,2,3));var forgedPacket=new NetPackageSetBlock{blockChanges=new List<BlockChangeInfo>{textured}};Check(!SeedPlacementIntentCodecReview.ValidateSenderSnapshot(sender,world,gm,forged,forgedPacket),"both intent+packet forged texture versus native seed route");
 var nativeIntent=receiptIntent;nativeIntent.Seed=new byte[]{4,5,6};nativeIntent.Flags=0x15;nativeIntent.Density=-127;nativeIntent.Texture=999;var densityReceipt=SeedPlacementOriginalCommandReview.Capture(1,2,7,3,nativeIntent);Check(densityReceipt.Flags==0x15&&densityReceipt.Density==-127&&densityReceipt.Texture==0,"receipt native density normalized texture");nativeIntent.Flags=0x21;nativeIntent.Density=123;nativeIntent.Texture=987654321;var textureReceipt=SeedPlacementOriginalCommandReview.Capture(1,2,7,3,nativeIntent);Check(textureReceipt.Flags==0x21&&textureReceipt.Density==0&&textureReceipt.Texture==987654321,"receipt native texture normalized density");nativeIntent.Flags=0x11;nativeIntent.Density=123;nativeIntent.Texture=987654321;var lightReceipt=SeedPlacementOriginalCommandReview.Capture(1,2,7,3,nativeIntent);Check(lightReceipt.Flags==0x11&&lightReceipt.Density==0&&lightReceipt.Texture==0,"receipt native light absent fields");nativeIntent.Flags=0;nativeIntent.Seed[0]=88;Check(textureReceipt.Flags==0x21&&textureReceipt.Texture==987654321&&textureReceipt.MatchesSeedIdentity(new byte[]{4,5,6}),"receipt input mutation primitives+seed");var textureCopy=textureReceipt.CopySeedIdentity();textureCopy[2]=44;Check(textureReceipt.MatchesSeedIdentity(new byte[]{4,5,6}),"receipt output copy v2");
 seed.TextureFullArray=new TextureFullArray();var countFrame=SeedPlacementIntentCodecReview.Write(2,17,new Vector3i(1,2,3),new BlockValue(42,12),new BlockValue(9,0),seed);Check(SeedPlacementIntentCodecReview.TryRead(countFrame,out intent)&&intent.OriginalCount==17,"original client count preserved");world.remote=false;world.block=new BlockValue(9,0);Check(SeedPlacementIntentCodecReview.ValidateSenderSnapshot(sender,world,gm,intent,packet)&&held.holdingItemStack.count==1,"server snapshot count differs allowed");
 foreach(int count in new[]{0,-1,1000001,int.MaxValue}){bool refused=false;try{SeedPlacementIntentCodecReview.Write(2,count,new Vector3i(1,2,3),new BlockValue(42,12),new BlockValue(9,0),seed);}catch(InvalidDataException){refused=true;}Check(refused,"original count write refusal");var badCount=(byte[])countFrame.Clone();var countBytes=BitConverter.GetBytes(count);Array.Copy(countBytes,0,badCount,5,4);Check(!SeedPlacementIntentCodecReview.TryRead(badCount,out intent),"original count read refusal");}
 var maxCount=SeedPlacementIntentCodecReview.Write(2,1000000,new Vector3i(1,2,3),new BlockValue(42,12),new BlockValue(9,0),seed);Check(SeedPlacementIntentCodecReview.TryRead(maxCount,out intent)&&intent.OriginalCount==1000000,"count proposed ceiling accepted");
 world.remote=false;world.block=new BlockValue(9,0);packet.persistentPlayerId=sender.PlatformId;packet.localPlayerThatChanged=7;var terminalOwner=new PacketOwnerDouble();terminalOwner.Admission.ThrowDispose=true;NetPackageRebirthSeedPlacementReview.Owner=terminalOwner;var hostEnvelope=new NetPackageRebirthSeedPlacementReview().Setup(packet,1,2,SeedPlacementIntentCodecReview.Write(2,3,new Vector3i(1,2,3),new BlockValue(42,12),new BlockValue(9,0),seed));hostEnvelope.Sender=sender;int executeBefore=NetPackageSetBlock.Executions;bool disposeThrown=false;try{hostEnvelope.ProcessPackage(world,gm);}catch(InvalidOperationException){disposeThrown=true;}Check(disposeThrown&&terminalOwner.Terminal==1&&terminalOwner.Admission.Disposed==1&&terminalOwner.Admission.Completed==1&&NetPackageSetBlock.Executions==executeBefore+1,"dispose throws still terminal exactlyonce nativeonce");
 var originalOwner=new PacketOwnerDouble{ReplaceOwner=true,Replacement=new PacketOwnerDouble()};NetPackageRebirthSeedPlacementReview.Owner=originalOwner;hostEnvelope.ProcessPackage(world,gm);Check(originalOwner.Terminal==1&&originalOwner.Replacement.Terminal==0&&originalOwner.Admits==1,"static owner replacement uses captured original");Check(NetPackageSetBlock.Executions==executeBefore+2,"replacement no extra executor");
 var terminal=new TerminalDouble();var actualOwner=new SeedPlacementHostOwnerReview(terminal,new HostPolicyDouble());NetPackageRebirthSeedPlacementReview.Owner=actualOwner;world.remote=false;world.block=new BlockValue(9,0);held.holdingItemItemValue=seed;var actualIntent=SeedPlacementIntentCodecReview.Write(2,3,new Vector3i(1,2,3),new BlockValue(42,12),new BlockValue(9,0),seed);var actualEnvelope=new NetPackageRebirthSeedPlacementReview().Setup(packet,55,66,actualIntent);actualEnvelope.Sender=sender;held.SelectedSlot=3;int executions=NetPackageSetBlock.Executions,reserved=SeedPlacementSessionAuthority.Reservations;actualEnvelope.ProcessPackage(world,gm);Check(SeedPlacementSessionAuthority.Reservations==reserved+1&&NetPackageSetBlock.Executions==executions&&terminal.Count==1,"actual owner bad snapshot reserves no execution terminal");held.SelectedSlot=2;actualEnvelope.ProcessPackage(world,gm);Check(SeedPlacementSessionAuthority.Reservations==reserved+1&&NetPackageSetBlock.Executions==executions&&terminal.Count==2,"corrected snapshot same nonce rejected no executor");
 Check(owner.Capture!=null&&object.ReferenceEquals(owner.Capture.Original,owner.Original)&&owner.Original.OriginalCount==1&&owner.Prediction,"same retained private original+count");var nativeCopy=owner.Capture.CopyNativeBytes();var expectedNative=StreamUtils.ToBlob(packet.write).ToArray();Check(nativeCopy.SequenceEqual(expectedNative),"captured exact native Setup bytes");nativeCopy[0]++;Check(owner.Capture.CopyNativeBytes().SequenceEqual(expectedNative),"native byte output alias detached");var commandCopy=owner.Capture.CopyIntentBytes();commandCopy[0]++;Check(owner.Capture.CopyIntentBytes()[0]==3,"intent byte output alias detached");
 world.remote=true;world.block=new BlockValue(9,0);var refusedRetain=new ClientOwnerDouble{AllowRetain=false};SeedPlacementClientScopeReview.ClientOwner=refusedRetain;using(var noScope=SeedPlacementClientScopeReview.Begin(data,new BlockPlacement.Result{blockPos=new Vector3i(1,2,3)},new BlockValue(42,12))){Check(noScope==null&&refusedRetain.Marks==0&&refusedRetain.Binds==0,"retention false no specialized scope");}
 var refusedBind=new ClientOwnerDouble{AllowBind=false};SeedPlacementClientScopeReview.ClientOwner=refusedBind;using(var noBind=SeedPlacementClientScopeReview.Begin(data,new BlockPlacement.Result{blockPos=new Vector3i(1,2,3)},new BlockValue(42,12))){Check(noBind!=null&&noBind.BeforeNativeInvocation(),"binding setup mark");world.block=new BlockValue(42,12);NetPackageRebirthSeedPlacementReview rejectedEnvelope;bool rejected=false;try{SeedPlacementClientScopeReview.TryConsumeMatchingSend(packet,out rejectedEnvelope);}catch(InvalidDataException){rejected=true;}Check(rejected&&refusedBind.Binds==1,"bind false refuses specialized send");bool retryRejected=false;try{SeedPlacementClientScopeReview.TryConsumeMatchingSend(packet,out rejectedEnvelope);}catch(InvalidDataException){retryRejected=true;}Check(retryRejected&&refusedBind.Binds==1,"failed binding never native fallback/rebind");}Check(refusedBind.Retired==1&&!refusedBind.Sent&&refusedBind.Prediction,"bind refusal preserves terminal prediction state");
 world.block=new BlockValue(9,0);var duplicateMark=new ClientOwnerDouble();SeedPlacementClientScopeReview.ClientOwner=duplicateMark;using(var doubleScope=SeedPlacementClientScopeReview.Begin(data,new BlockPlacement.Result{blockPos=new Vector3i(1,2,3)},new BlockValue(42,12))){Check(doubleScope.BeforeNativeInvocation()&&!doubleScope.BeforeNativeInvocation()&&duplicateMark.Marks==1,"duplicate invocation cannot run second native");}
 var inputNative=new byte[]{1,2,3};var inputIntent=new byte[]{3,4,5};var copiedCapture=SeedPlacementConsumedEnvelopeReview.Capture(original,inputNative,inputIntent);inputNative[0]=99;inputIntent[0]=99;Check(copiedCapture.CopyNativeBytes()[0]==1&&copiedCapture.CopyIntentBytes()[0]==3,"capture both input aliases detached");
 world.remote=true;world.block=new BlockValue(9,0);var serializeOwner=new ClientOwnerDouble();SeedPlacementClientScopeReview.ClientOwner=serializeOwner;using(var serializeScope=SeedPlacementClientScopeReview.Begin(data,new BlockPlacement.Result{blockPos=new Vector3i(1,2,3)},new BlockValue(42,12))){Check(serializeScope.BeforeNativeInvocation(),"serialization mark");world.block=new BlockValue(42,12);NetPackageSetBlock.ThrowWrite=true;NetPackageRebirthSeedPlacementReview unavailable;bool failed=false;try{SeedPlacementClientScopeReview.TryConsumeMatchingSend(packet,out unavailable);}catch(InvalidDataException){failed=true;}NetPackageSetBlock.ThrowWrite=false;bool retry=false;try{SeedPlacementClientScopeReview.TryConsumeMatchingSend(packet,out unavailable);}catch(InvalidDataException){retry=true;}Check(failed&&retry&&serializeOwner.Binds==0,"serialize failure no second fallback/bind");}Check(serializeOwner.Retired==1&&!serializeOwner.Sent&&serializeOwner.Prediction,"serialize failure terminal flags");
 Console.WriteLine("PASS"+checks+" exact decoder; native Read bodies extracted; identity canonical bytes/adapters are explicit test doubles, not platform codec proof.");
 }
}
















