using System;
using System.Collections.Generic;
using System.Linq;
using System.IO;
class Vec { public int x,y,z; public Vec(int a=0,int b=0,int c=0){x=a;y=b;z=c;} public static Vec operator +(Vec a,Vec b)=>new Vec(a.x+b.x,a.y+b.y,a.z+b.z);public override bool Equals(object o)=>o is Vec v&&x==v.x&&y==v.y&&z==v.z;public override int GetHashCode()=>x; }
class Definition { public Vec startPos=new Vec(),size=new Vec(10,10,10);public short spawnCountMin=1,spawnCountMax=2;public int flags;public string minScript; }
class Prefab {public bool bTraderArea;public string PrefabName="house";public List<Definition> SleeperVolumeList=new List<Definition>{new Definition()};}
class PrefabInstance {public Prefab prefab=new Prefab();public Vec boundingBoxPosition=new Vec(),boundingBoxSize=new Vec(10,10,10);public byte rotation;public List<SleeperVolume> sleeperVolumes=new List<SleeperVolume>();}
class Biome {public string m_sBiomeName="forest";}
class WorldState {public string Guid=System.Guid.NewGuid().ToString("N").ToUpperInvariant();}
class World {public WorldState worldState=new WorldState();public ulong worldTime=1;public Dictionary<int,EntityAlive> Entities=new Dictionary<int,EntityAlive>();public List<SleeperVolume> Volumes=new List<SleeperVolume>(); public bool IsRemote()=>false;public EntityAlive GetEntity(int id)=>Entities.TryGetValue(id,out var e)?e:null;public int FindSleeperVolume(Vec min,Vec max)=>Volumes.FindIndex(v=>v.BoxMin.Equals(min)&&v.BoxMax.Equals(max));public SleeperVolume GetSleeperVolume(int id)=>id>=0&&id<Volumes.Count?Volumes[id]:null;public Biome GetBiome(int x,int z)=>new Biome();}
class EntityBuffs {public Dictionary<string,float> Vars=new Dictionary<string,float>();public bool HasCustomVar(string key)=>Vars.ContainsKey(key);public float GetCustomVar(string key)=>Vars[key];public void SetCustomVar(string key,float value,bool netSync){Vars[key]=value;} }
class EntityAlive {public EntityBuffs Buffs=new EntityBuffs();public World world;public int entityId;public bool Dead;public bool IsDead()=>Dead;}
class EntityPlayer:EntityAlive {public bool IsSpectator;public bool IsAlive()=>!Dead;public Vec GetBlockPosition()=>new Vec();}
class Script {public bool Running;public bool IsRunning()=>Running;}
class Handle {public bool IsCompleted=true;public Action onComplete;}
class SleeperVolume {public PrefabInstance prefabInstance;public Vec BoxMin=new Vec(),BoxMax=new Vec(10,10,10);public short spawnCountMin=1,spawnCountMax=2;public int flags,numSpawned;public bool isSpawning,wasCleared;public Script minScript;public Dictionary<int,object> respawnMap=new Dictionary<int,object>();public HashSet<int> pendingSpawnMap=new HashSet<int>();public Queue<Handle> pendingSpawnOps=new Queue<Handle>();}
class Decorator {public PrefabInstance Prefab;public PrefabInstance GetPrefabFromWorldPos(int x,int z)=>Prefab;}
class GameStateManager {public bool IsGameStarted()=>true;}
class GameManager {public static GameManager Instance;public World World;public bool IsStartingGame;public GameStateManager gameStateManager=new GameStateManager();public bool IsEditMode()=>false;public Decorator Decorator=new Decorator();public Decorator GetDynamicPrefabDecorator()=>Decorator;}
class ConnectionManager {public bool IsServer=true;}
class SingletonMonoBehaviour<T> {public static T Instance;}
class ThreadManager {public static bool IsMainThread()=>true;}
class GameIO {public static string GetSaveGameDir()=>"unused";}
class Log {public static void Warning(string s){} }

static class Program
{
 static int checks;static void Check(bool b,string s){if(!b)throw new Exception("FAIL "+s);checks++;Console.WriteLine("PASS "+s);}
 class Native:System.Collections.IEnumerator,IDisposable{public int Calls,Effects,Disposed;public Action Execute;public bool Fail;public object Yielded;public object Current=>Yielded;public bool MoveNext(){Calls++;if(Calls==1){Effects++;Execute?.Invoke();if(Fail)throw new IOException("native");return true;}return false;}public void Reset()=>throw new Exception();public void Dispose(){Disposed++;}}
 static void Main()
 {
  object scope=new object();string dir=Path.Combine(Path.GetTempPath(),"rebirth-purge-resetprotocol-"+Guid.NewGuid().ToString("N"));Directory.CreateDirectory(dir);bool live=true,armed=false;string stage="afterManifestCandidateWritten";var binding=new RebirthPoiWorldBinding(scope,Guid.NewGuid().ToString("N").ToUpperInvariant(),dir,()=>live);RebirthPoiWorldStore.TryOpen(binding,out var store,s=>{if(armed&&s==stage)throw new IOException("fixture");});double time=0;int poiIndex=0;
  Func<RebirthPoiIdentity> prepare=()=>{var p=new RebirthPoiIdentity("house",poiIndex++,2,3,0,10,10,10,"forest");if(store.TryDiscover(store.Published,p)!=RebirthPoiStoreResult.Published)throw new Exception("setup");return p;};
  Func<Guid,RebirthPoiResetPlan> plan=id=>new RebirthPoiResetPlan(id,RebirthPoiResetCaller.Quest,new string('a',64),new long[]{4,5},new[]{7,8},new[]{9});
  var poi=prepare();var tx=Guid.NewGuid();var envelope=plan(tx);var native=new Native();var protocol=new RebirthPoiResetCallerProtocol(store,store.Published,poi,envelope,native,()=>time);armed=true;Check(protocol.MoveNext()&&native.Calls==0&&store.HasPending,"failed intent prevents original native iterator advancement");for(int i=0;i<500;i++)protocol.MoveNext();Check(native.Calls==0,"pending admission never recreates or advances native caller");armed=false;Check(store.TryRetryPending()==RebirthPoiStoreResult.Published,"original saved intent retries");Check(RebirthPoiWorldStore.TryOpen(binding,out var cold)==RebirthPoiStoreResult.Published&&cold.Published.TryGet(poi,out var pending)&&pending.ResetPlan.Canonical==envelope.Canonical,"original expected chunk volume trigger plan survives cold load");
  native.Execute=()=>{protocol.ChunkCopied(scope,tx,4,true);protocol.ChunkCopied(scope,tx,5,true);protocol.ChunkRegenerated(scope,tx,4,true);protocol.ChunkRegenerated(scope,tx,5,true);protocol.VolumeReset(scope,tx,7);protocol.VolumeReset(scope,tx,8);protocol.TriggerReset(scope,tx,9);protocol.TriggersRefreshed(scope,tx,envelope.Manifest);};time=1;Check(protocol.MoveNext()&&native.Calls==1&&native.Effects==1,"original iterator resumes exactly once after witnessed admission");armed=true;Check(protocol.MoveNext()&&protocol.State==RebirthPoiResetProtocolState.PendingCompletion&&store.HasPending,"lost terminal publication never reports native completion");armed=false;store.TryRetryPending();time=2;Check(!protocol.MoveNext()&&protocol.State==RebirthPoiResetProtocolState.Completed&&native.Calls==2,"exact terminal receipt completes caller after original retry");Check(store.Published.TryGet(poi,out var final)&&final.Epoch==1&&final.ResetPlan==null,"terminal publication advances original epoch and removes active plan");
  var missingPoi=prepare();var missingNative=new Native();var missing=new RebirthPoiResetCallerProtocol(store,store.Published,missingPoi,plan(Guid.NewGuid()),missingNative,()=>time);missing.MoveNext();Check(missing.MoveNext()&&missing.State==RebirthPoiResetProtocolState.Unknown,"normal native iterator end without copy proof never completes caller");Check(store.Published.TryGet(missingPoi,out pending)&&pending.State==RebirthPoiClearanceState.ResetPending,"unknown effects retain durable withheld reset intent");missing.Dispose();Check(store.Published.TryGet(missingPoi,out pending)&&pending.State==RebirthPoiClearanceState.ResetPending,"abandoned mutated iterator cannot restore no-mutation");
  var cancelledPoi=prepare();var cancelledNative=new Native();var cancelled=new RebirthPoiResetCallerProtocol(store,store.Published,cancelledPoi,plan(Guid.NewGuid()),cancelledNative,()=>time);cancelled.CancelBeforeMutation();Check(cancelled.State==RebirthPoiResetProtocolState.Refused&&cancelledNative.Calls==0,"known pre-mutation cancellation records no-mutation without native calls");bool refusal=false;try{cancelled.MoveNext();}catch(InvalidOperationException){refusal=true;}Check(refusal,"refused caller cannot emit normal child completion");
  var failedPoi=prepare();var failingNative=new Native{Fail=true};var failing=new RebirthPoiResetCallerProtocol(store,store.Published,failedPoi,plan(Guid.NewGuid()),failingNative,()=>time);Check(failing.MoveNext()&&failing.State==RebirthPoiResetProtocolState.Unknown&&failing.NativeFailure!=null,"native exception retains explicit unknown and original error");
  var stalePoi=prepare();var staleNative=new Native();var stale=new RebirthPoiResetCallerProtocol(store,store.Published,stalePoi,plan(Guid.NewGuid()),staleNative,()=>time);live=false;stale.Poll();Check(stale.State==RebirthPoiResetProtocolState.Refused&&staleNative.Calls==0,"replacement world refuses original unstarted caller");live=true;
  var foreignPoi=prepare();var foreignNative=new Native();var foreignTx=Guid.NewGuid();var foreign=new RebirthPoiResetCallerProtocol(store,store.Published,foreignPoi,plan(foreignTx),foreignNative,()=>time);foreignNative.Execute=()=>{foreign.ChunkCopied(new object(),foreignTx,4,true);foreign.ChunkCopied(scope,Guid.NewGuid(),5,true);};foreign.MoveNext();foreign.MoveNext();Check(foreign.State==RebirthPoiResetProtocolState.Unknown,"foreign scope or receipt cannot satisfy original plan");
  var cancelFaultPoi=prepare();var cancelFaultNative=new Native();var cancelFault=new RebirthPoiResetCallerProtocol(store,store.Published,cancelFaultPoi,plan(Guid.NewGuid()),cancelFaultNative,()=>time);armed=true;cancelFault.Poll();Check(store.HasPending&&cancelFaultNative.Calls==0,"uncertain admission cancellation retains original intent");cancelFault.CancelBeforeMutation();armed=false;store.TryRetryPending();time++;armed=true;cancelFault.Poll();Check(store.HasPending&&cancelFaultNative.Calls==0,"uncertain no-mutation receipt cannot advance native iterator");armed=false;store.TryRetryPending();time++;cancelFault.Poll();Check(cancelFault.State==RebirthPoiResetProtocolState.Refused&&cancelFaultNative.Calls==0,"exact no-mutation lost response reconciles explicit refusal");
  var refreshPoi=prepare();var refreshNative=new Native();var refreshTx=Guid.NewGuid();var refresh=new RebirthPoiResetCallerProtocol(store,store.Published,refreshPoi,plan(refreshTx),refreshNative,()=>time);refreshNative.Execute=()=>{foreach(long k in new long[]{4,5}){refresh.ChunkCopied(scope,refreshTx,k,true);refresh.ChunkRegenerated(scope,refreshTx,k,true);}refresh.VolumeReset(scope,refreshTx,7);refresh.VolumeReset(scope,refreshTx,8);refresh.TriggerReset(scope,refreshTx,9);};refresh.MoveNext();refresh.MoveNext();Check(refresh.State==RebirthPoiResetProtocolState.Unknown,"all copies volume resets without native trigger refresh still unknown");
  var extraPoi=prepare();var extraNative=new Native();var extraTx=Guid.NewGuid();var extra=new RebirthPoiResetCallerProtocol(store,store.Published,extraPoi,plan(extraTx),extraNative,()=>time);extraNative.Execute=()=>extra.ChunkCopied(scope,extraTx,99,true);extra.MoveNext();time++;extra.Poll();Check(extra.State==RebirthPoiResetProtocolState.Unknown,"unexpected native chunk under original receipt faults complete envelope");
  var nestedPoi=prepare();var deepest=new Native();var middle=new Native{Yielded=deepest};var root=new Native{Yielded=middle};var nestedProtocol=new RebirthPoiResetCallerProtocol(store,store.Published,nestedPoi,plan(Guid.NewGuid()),root,()=>time);nestedProtocol.MoveNext();var guardedMiddle=(System.Collections.IEnumerator)nestedProtocol.Current;guardedMiddle.MoveNext();var guardedDeepest=(System.Collections.IEnumerator)guardedMiddle.Current;live=false;Check(guardedDeepest.MoveNext()&&deepest.Calls==0&&nestedProtocol.State==RebirthPoiResetProtocolState.Unknown,"yielded nested coroutine cannot mutate replacement world without parent poll");live=true;for(int i=0;i<20;i++)guardedDeepest.MoveNext();Check(deepest.Calls==0&&root.Calls==1&&nestedProtocol.State==RebirthPoiResetProtocolState.Unknown,"nested unknown cannot resume original parent or emit vanilla completion");
  Guid journalGeneration=Guid.NewGuid(),roomDeath=Guid.NewGuid();var roomJournal=new RebirthPoiPartialObservation(journalGeneration,0,1,new[]{new RebirthPoiVolumeObservation(7,new string('a',64),new[]{new RebirthPoiActorObservation(Guid.NewGuid(),1,"zombieArlene",0)}),new RebirthPoiVolumeObservation(8,new string('b',64),new[]{new RebirthPoiActorObservation(Guid.NewGuid(),2,"zombieArlene",1,roomDeath,40)})});
  Func<Guid,RebirthPoiResetPlan> selectivePlan=id=>new RebirthPoiResetPlan(id,RebirthPoiResetCaller.NaturalRespawn,new string('c',64),new long[0],new[]{7},new int[0]);
  var selectivePoi=prepare();Check(store.TryObservePartial(store.Published,selectivePoi,0,roomJournal)==RebirthPoiStoreResult.Published,"original two-room causality durably published before native reset");var selectiveTx=Guid.NewGuid();var selectiveNative=new Native();var selective=new RebirthPoiResetCallerProtocol(store,store.Published,selectivePoi,selectivePlan(selectiveTx),selectiveNative,()=>time);
  selectiveNative.Execute=()=>{var oldActor=roomJournal.Volumes[7].Actors.Values.Single();selective.RuntimeBindingVerified(scope,selectiveTx,new RebirthPoiAuthoredRuntimeBinding("1:7",new string('a',64),7,Guid.NewGuid()));selective.PriorActorOutcomeVerified(scope,selectiveTx,new RebirthPoiResetActorOutcome(oldActor.Token,oldActor.EntityId,0,journalGeneration,new string('a',64),oldActor.CausalDigest,RebirthPoiPriorActorDisposition.NativeRemoved,Guid.NewGuid()));selective.VolumeReset(scope,selectiveTx,7);selective.UnaffectedVolumeVerified(scope,selectiveTx,8,new string('b',64),journalGeneration);};selective.MoveNext();armed=true;Check(selective.MoveNext()&&store.HasPending&&selective.State==RebirthPoiResetProtocolState.PendingCompletion,"selective successor lost terminal response never completes caller");armed=false;store.TryRetryPending();time++;Check(!selective.MoveNext()&&selective.State==RebirthPoiResetProtocolState.Completed,"original selective reset candidate completes after exact retry");
  store.Published.TryGet(selectivePoi,out var selectiveSaved);Check(selectiveSaved.Observations.Volumes[7].Actors.Count==0&&selectiveSaved.Observations.EffectiveGeneration(selectiveSaved.Observations.Volumes[7])==selectiveTx&&selectiveSaved.Observations.Volumes[8].Actors.Values.Single().DeathReceipt==roomDeath,"actual terminal store preserves only positively untouched room receipt");
  Check(RebirthPoiWorldStore.TryOpen(binding,out var selectiveCold)==RebirthPoiStoreResult.Published&&selectiveCold.Published.TryGet(selectivePoi,out var selectiveReload)&&selectiveReload.Observations.Canonical==selectiveSaved.Observations.Canonical,"cold final file retains original selective generation and untouched causality");
  var noProofPoi=prepare();store.TryObservePartial(store.Published,noProofPoi,0,roomJournal);var noProofTx=Guid.NewGuid();var noProofNative=new Native();var noProof=new RebirthPoiResetCallerProtocol(store,store.Published,noProofPoi,selectivePlan(noProofTx),noProofNative,()=>time);noProofNative.Execute=()=>noProof.VolumeReset(scope,noProofTx,7);noProof.MoveNext();noProof.MoveNext();Check(noProof.State==RebirthPoiResetProtocolState.Unknown&&store.Published.TryGet(noProofPoi,out var noProofRecord)&&noProofRecord.State==RebirthPoiClearanceState.ResetPending&&noProofRecord.Observations.Canonical==roomJournal.Canonical,"omitted unchanged-volume proof withholds rather than discarding original room evidence");
  var wrongProofPoi=prepare();store.TryObservePartial(store.Published,wrongProofPoi,0,roomJournal);var wrongProofTx=Guid.NewGuid();var wrongProofNative=new Native();var wrongProof=new RebirthPoiResetCallerProtocol(store,store.Published,wrongProofPoi,selectivePlan(wrongProofTx),wrongProofNative,()=>time);wrongProofNative.Execute=()=>{wrongProof.VolumeReset(scope,wrongProofTx,7);wrongProof.UnaffectedVolumeVerified(scope,wrongProofTx,8,new string('e',64),journalGeneration);};wrongProof.MoveNext();wrongProof.MoveNext();Check(wrongProof.State==RebirthPoiResetProtocolState.Unknown,"changed unaffected native manifest cannot retain original causality");
  var surprisePoi=prepare();store.TryObservePartial(store.Published,surprisePoi,0,roomJournal);var surpriseTx=Guid.NewGuid();var surpriseNative=new Native();var surprise=new RebirthPoiResetCallerProtocol(store,store.Published,surprisePoi,selectivePlan(surpriseTx),surpriseNative,()=>time);surpriseNative.Execute=()=>{surprise.VolumeReset(scope,surpriseTx,7);surprise.UnaffectedVolumeVerified(scope,surpriseTx,8,new string('b',64),journalGeneration);surprise.VolumeReset(scope,surpriseTx,8);};surprise.MoveNext();surprise.MoveNext();Check(surprise.State==RebirthPoiResetProtocolState.Unknown,"unexpected mutation of claimed untouched room invalidates whole original envelope");
  var batchA=prepare();var batchB=prepare();var batchTx=Guid.NewGuid();var batchEntries=new[]{new RebirthPoiResetBatchEntry(batchA,plan(batchTx)),new RebirthPoiResetBatchEntry(batchB,plan(batchTx))};var batchNative=new Native();var batch=new RebirthPoiResetBatchCallerProtocol(store,store.Published,batchEntries,batchNative,()=>time);bool allAdmitted=false;
  batchNative.Execute=()=>{allAdmitted=batchEntries.All(e=>store.Published.TryGet(e.Identity,out var r)&&r.State==RebirthPoiClearanceState.ResetPending&&r.ResetId==batchTx);foreach(var e in batchEntries){foreach(long k in e.Plan.Chunks){batch.ChunkCopied(e.Identity,scope,batchTx,k,true);batch.ChunkRegenerated(e.Identity,scope,batchTx,k,true);}foreach(int id in e.Plan.Volumes)batch.VolumeReset(e.Identity,scope,batchTx,id);foreach(int id in e.Plan.Triggers)batch.TriggerReset(e.Identity,scope,batchTx,id);batch.TriggersRefreshed(e.Identity,scope,batchTx,e.Plan.Manifest);}batch.VolumeReset(new RebirthPoiIdentity("foreign",99,2,3,0,10,10,10,"forest"),new object(),batchTx,99);};
  Check(batch.TryAdmitBeforeMutation()&&!batch.HasNativeStarted&&batchNative.Calls==0&&batchEntries.All(e=>store.Published.TryGet(e.Identity,out var r)&&r.State==RebirthPoiClearanceState.ResetPending&&r.ResetId==batchTx),"owning caller admits all durable POI intents before any native side effects");for(int n=0;n<100;n++)batch.TryAdmitBeforeMutation();Check(batchNative.Calls==0&&batch.State==RebirthPoiResetProtocolState.Ready,"repeated caller admission never advances or recreates native iterator");
  Check(batch.MoveNext()&&batch.HasNativeStarted&&allAdmitted&&batchNative.Calls==1&&batchNative.Effects==1,"whole native multi-POI iterator starts once only after every original intent is durable");Check(!batch.TryAdmitBeforeMutation()&&batchNative.Calls==1,"running original reset cannot be admitted again as a fresh owner");armed=true;Check(batch.MoveNext()&&batch.State==RebirthPoiResetProtocolState.PendingCompletion&&store.HasPending,"multi-POI caller withholds completion when one terminal save is uncertain");armed=false;store.TryRetryPending();time++;Check(!batch.MoveNext()&&batch.State==RebirthPoiResetProtocolState.Completed&&batchNative.Calls==2,"one original native iterator completes after every original POI receipt publishes");Check(batchEntries.All(e=>store.Published.TryGet(e.Identity,out var r)&&r.Epoch==1&&r.LastResetId==batchTx),"all overlapping original POI generations invalidated under one caller transaction");
  var cancelBatchA=prepare();var cancelBatchB=prepare();var cancelBatchTx=Guid.NewGuid();var cancelBatchNative=new Native();var cancelBatch=new RebirthPoiResetBatchCallerProtocol(store,store.Published,new[]{new RebirthPoiResetBatchEntry(cancelBatchA,plan(cancelBatchTx)),new RebirthPoiResetBatchEntry(cancelBatchB,plan(cancelBatchTx))},cancelBatchNative,()=>time);
  Check(cancelBatch.TryAdmitBeforeMutation(),"cancellation fixture admits complete original batch");armed=true;cancelBatch.Dispose();Check(!cancelBatch.PollCancellation()&&store.HasPending&&cancelBatchNative.Calls==0,"failed cancellation publication stays pending without native effects");armed=false;store.TryRetryPending();time++;for(int n=0;n<4&&!cancelBatch.PollCancellation();n++){store.TryRetryPending();time++;}
  Check(cancelBatch.PollCancellation()&&!cancelBatch.HasNativeStarted&&cancelBatch.State==RebirthPoiResetProtocolState.Refused&&cancelBatchNative.Calls==0&&new[]{cancelBatchA,cancelBatchB}.All(p=>store.Published.TryGet(p,out var r)&&r.State==RebirthPoiClearanceState.Discovered&&r.LastResetDisposition==RebirthPoiResetDisposition.NoMutation),"owner drains every original no-mutation receipt after lost publication");
  Check(!batch.PollCancellation()&&batch.State==RebirthPoiResetProtocolState.Completed,"cancellation polling cannot change a completed native batch");
  var refusedA=prepare();var refusedB=prepare();var refusedTx=Guid.NewGuid();var refusedNative=new Native();var refusedBatch=new RebirthPoiResetBatchCallerProtocol(store,store.Published,new[]{new RebirthPoiResetBatchEntry(refusedA,plan(refusedTx)),new RebirthPoiResetBatchEntry(refusedB,plan(refusedTx))},refusedNative,()=>time);var otherTx=Guid.NewGuid();store.TryBeginReset(store.Published,refusedB,0,otherTx);bool wholeRefusal=false;try{refusedBatch.MoveNext();}catch(InvalidOperationException){wholeRefusal=true;}Check(wholeRefusal&&refusedNative.Calls==0&&refusedBatch.State==RebirthPoiResetProtocolState.Refused,"competing overlapping POI refuses whole caller without advancing native effects");Check(store.Published.TryGet(refusedA,out var cancelledBatchRecord)&&cancelledBatchRecord.State==RebirthPoiClearanceState.Discovered&&cancelledBatchRecord.LastResetDisposition==RebirthPoiResetDisposition.NoMutation&&store.Published.TryGet(refusedB,out var otherRecord)&&otherRecord.ResetId==otherTx,"whole refusal restores only original admitted intent and preserves competing transaction");
  var batchMissingA=prepare();var batchMissingB=prepare();var batchMissingTx=Guid.NewGuid();var batchMissingNative=new Native();var batchMissing=new RebirthPoiResetBatchCallerProtocol(store,store.Published,new[]{new RebirthPoiResetBatchEntry(batchMissingA,plan(batchMissingTx)),new RebirthPoiResetBatchEntry(batchMissingB,plan(batchMissingTx))},batchMissingNative,()=>time);batchMissing.MoveNext();batchMissing.MoveNext();Check(batchMissing.State==RebirthPoiResetProtocolState.Unknown&&new[]{batchMissingA,batchMissingB}.All(p=>store.Published.TryGet(p,out var r)&&r.State==RebirthPoiClearanceState.ResetPending),"missing multi-POI effect proof cannot emit native caller completion");
  var batchNestedA=prepare();var batchNestedB=prepare();var batchNestedTx=Guid.NewGuid();var batchDeepest=new Native();var batchRoot=new Native{Yielded=batchDeepest};var batchNested=new RebirthPoiResetBatchCallerProtocol(store,store.Published,new[]{new RebirthPoiResetBatchEntry(batchNestedA,plan(batchNestedTx)),new RebirthPoiResetBatchEntry(batchNestedB,plan(batchNestedTx))},batchRoot,()=>time);batchNested.MoveNext();var batchGuarded=(System.Collections.IEnumerator)batchNested.Current;live=false;Check(batchGuarded.MoveNext()&&batchDeepest.Calls==0&&batchNested.State==RebirthPoiResetProtocolState.Unknown,"whole multi-POI nested native callback cannot advance into replacement world");live=true;
  Check(batch.TryGetCompleted(out var batchOutcome)&&batchOutcome.World==binding.WorldId&&batchOutcome.Transaction==batchTx&&batchOutcome.PoiKeys.Count==2,"actual original completed batch produces positively witnessed immutable correlation outcome");
  var witnessedRevision=batchOutcome.GlobalRevision;prepare();Check(batch.TryGetCompleted(out var retryOutcome)&&ReferenceEquals(batchOutcome,retryOutcome)&&retryOutcome.GlobalRevision==witnessedRevision,"unrelated published revision retains original completion object and revision on retry");
  Check(!batchMissing.TryGetCompleted(out _)&&!refusedBatch.TryGetCompleted(out _)&&!batchNested.TryGetCompleted(out _),"unknown refused and replaced-world batches cannot produce success receipts");
  live=false;Check(!batch.TryGetCompleted(out _),"late completed outcome cannot cross original world scope");live=true;
  var laterTx=Guid.NewGuid();store.TryBeginReset(store.Published,batchA,1,laterTx);Check(!batch.TryGetCompleted(out _),"subsequent pending reset cannot replay original rally completion");store.TryFinishReset(store.Published,batchA,1,laterTx,RebirthPoiResetDisposition.Completed);Check(!batch.TryGetCompleted(out _),"subsequent published epoch cannot replay original rally completion");
  var deferredPoi=prepare();store.TryClear(store.Published,deferredPoi,0,new RebirthPoiClearEvidence(Guid.NewGuid(),1,1,1,0,0,false,1));
  var deferredTx=Guid.NewGuid();var deferredNative=new Native();var deferred=new RebirthPoiResetCallerProtocol(store,store.Published,deferredPoi,plan(deferredTx),deferredNative,()=>time);
  deferred.Poll();Check(deferred.State==RebirthPoiResetProtocolState.Ready&&deferredNative.Calls==0,"reset admission does not wait for unrelated objective milestone writes");
  deferred.Dispose();
  Console.WriteLine("RESULT "+checks+" PASS; actual caller protocol/domain/store and real files; native IEnumerator/effect hooks doubled; protocol is not installed on native caller routes.");
 }
}




