using System;using System.Linq;using System.Collections.Generic;using System.Runtime.CompilerServices;
// TOOLS ONLY. Called only from retained original paid event seam, never registered.
internal static class NativePaidOrdinaryExitCandidate {
 internal sealed class Held {
  internal readonly RebirthStationCompletionCapture.SuccessfulOutput Original;internal readonly RecipeQueueItem Active;internal readonly int Actor,Quantity,Xp;internal readonly string Recipe,Scrap,OutputImage;internal NativePaidOrdinaryRouteLink Route;internal ExitWitness Witness;internal RebirthStationNativeQueueSnapshot QueueBefore;internal string Quarantine;internal bool Busy;
  internal Held(RebirthStationCompletionCapture.SuccessfulOutput e,RecipeQueueItem a,int actor,string image,string recipe,string scrap,int xp,int quantity){Original=e;Active=a;Actor=actor;OutputImage=image;Recipe=recipe;Scrap=scrap;Xp=xp;Quantity=quantity;}
 }
 internal sealed class ExitWitness {
  readonly Held held;readonly NativePaidOrdinaryRouteLink originalRoute;readonly RebirthStationNativeQueueSnapshot queueImage;readonly RecipeQueueItem[] queue;readonly Recipe[] recipes;readonly string[] output,receipts;
  internal ExitWitness(Held h,RecipeQueueItem[] q,string[] o,string[] r,RebirthStationNativeQueueSnapshot image){held=h;originalRoute=h.Route;queueImage=image;queue=(RecipeQueueItem[])q.Clone();recipes=q.Select(x=>x?.Recipe).ToArray();output=(string[])o.Clone();receipts=(string[])r.Clone();}
  internal bool MatchesOriginal(RebirthStationCompletionCapture.SuccessfulOutput e)=>ReferenceEquals(held.Original,e);internal bool MatchesRoute(NativePaidOrdinaryRouteLink route)=>ReferenceEquals(originalRoute,route)&&ReferenceEquals(held.Route,originalRoute);internal string QueueBeforeDigest=>held.QueueBefore.Digest();internal string QueueAfterDigest=>queueImage.Digest();
  internal bool IsCurrent(){try{return held.Quarantine==null&&ReferenceEquals(held.Route,originalRoute)&&held.Original.Original.IsCurrent()&&QueueMatches(held,queue,recipes)&&queueImage.Matches(held.Original.Original.Station.Queue)&&output.SequenceEqual(OutputImages(held.Original.Original.Station))&&OrdinaryNativeCallsiteCandidate.TrySnapshotReceiptImages(held.Original.Original.Station,out var current)&&receipts.SequenceEqual(current)&&QueueMatches(held,queue,recipes)&&queueImage.Matches(held.Original.Original.Station.Queue)&&output.SequenceEqual(OutputImages(held.Original.Original.Station))&&held.Original.Original.IsCurrent();}catch{return false;}}
 }
 static readonly ConditionalWeakTable<TileEntityWorkstation,Dictionary<string,Held>> retained=new ConditionalWeakTable<TileEntityWorkstation,Dictionary<string,Held>>();
 static string PhysicalImage(ItemValue v){var physical=v.Clone();foreach(var field in new[]{"version","job","creation","definition","tier","count","xp"})physical.Metadata.Remove(RebirthStationCompletionReceipt.Prefix+field);return RebirthNativeItemCodec.Encode(physical);}
 static string[] OutputImages(TileEntityWorkstation s){var live=s.Output;var clones=live.Select(x=>x.Clone()).ToArray();Func<ItemStack[],string[]> encode=a=>a.Select(x=>x.count.ToString(System.Globalization.CultureInfo.InvariantCulture)+":"+RebirthNativeItemCodec.Encode(x.itemValue)).ToArray();var frozen=encode(clones);if(!frozen.SequenceEqual(encode(clones))||!ReferenceEquals(live,s.Output)||!live.Zip(clones,(a,b)=>RebirthStationGridIngredients.IsSameStackSnapshot(a,b)).All(x=>x))throw new InvalidOperationException();return frozen;}
 static bool QueueMatches(Held h,RecipeQueueItem[] q,Recipe[] r){var current=h.Original.Original.Station.Queue;return current!=null&&q.Length==current.Length&&q.Zip(current,(a,b)=>ReferenceEquals(a,b)).All(x=>x)&&current.Zip(r,(a,b)=>ReferenceEquals(a?.Recipe,b)).All(x=>x)&&!current.Any(x=>ReferenceEquals(x,h.Active)||x?.Recipe!=null&&RebirthStationGridQueue.TryGetJobId(x.Recipe,out var key)&&key==h.Original.Original.Admission.JobId);}
 internal static bool AfterPaidRetained(RebirthStationCompletionCapture.SuccessfulOutput e,RecipeQueueItem active,int actor,ItemValue output,string recipe,string scrap,int xp,int quantity){Held h=null;try{if(e==null||active==null)return false;var entries=retained.GetValue(e.Original.Station,_=>new Dictionary<string,Held>(StringComparer.Ordinal));if(entries.TryGetValue(e.Original.Admission.JobId,out var previous)){if(previous.Busy){previous.Quarantine="Reentrant original exporter";return false;}return ReferenceEquals(previous.Original,e)&&previous.Quarantine==null;}if(entries.Count>=64)return false;h=new Held(e,active,actor,RebirthNativeItemCodec.Encode(output),recipe,scrap,xp,quantity);entries.Add(e.Original.Admission.JobId,h);h.Busy=true;if(!ReferenceEquals(e.Original.Station.Queue.LastOrDefault(),active)||!e.TryCopyPhysicalDelta(out _,out _,out var row)||row.CrafterEntityID!=actor||row.RecipeName!=recipe||row.ItemScrapped!=scrap||row.CraftExpGain!=xp||row.CraftedItemStack.count!=quantity||PhysicalImage(row.CraftedItemStack.itemValue)!=h.OutputImage||!NativePaidOrdinaryRouteLink.TryStageBeforeOrdinary(e,out var route)||!OrdinaryNativeCallsiteCandidate.Bind(e)||!e.Original.IsCurrent()){h.Quarantine="Original paid exporter proof failed";return false;}if(!RebirthStationNativeQueueSnapshot.TryCapture(e.Original.Station.Queue,out var queueBefore)||!queueBefore.Matches(e.Original.Station.Queue)||!e.Original.IsCurrent()){h.Quarantine="Original queue capture failed";return false;}if(h.Quarantine!=null||!e.Original.IsCurrent())return false;h.QueueBefore=queueBefore;h.Route=route;return true;}catch{if(h!=null)h.Quarantine="Original paid exporter callback failed";return false;}finally{if(h!=null)h.Busy=false;}}
 internal static bool TryGetOriginal(RebirthStationCompletionCapture.SuccessfulOutput e,out Held h){h=null;return e!=null&&retained.TryGetValue(e.Original.Station,out var map)&&map.TryGetValue(e.Original.Admission.JobId,out h)&&ReferenceEquals(h.Original,e);}
 internal static Exception OnOriginalExit(TileEntityWorkstation station,Exception original){if(station==null||!retained.TryGetValue(station,out var map))return original;foreach(var h in map.Values.ToArray()){if(original!=null||h.Busy||h.Quarantine!=null){h.Quarantine=h.Quarantine??"Original native exit failed or reentered";h.Route=h.Route?.QuarantineLifecycle();continue;}h.Busy=true;try{foreach(var addition in OrdinaryNativeCallsiteCandidate.Pending(station)){if(!addition.MatchesOriginal(h.Original))continue;var result=h.Route.TryAppendOriginal(addition,out var next);if(next!=null)h.Route=next;if(result==NativePaidOrdinaryRouteLink.Result.Refused||result==NativePaidOrdinaryRouteLink.Result.Quarantined)throw new InvalidOperationException();}var q=station.Queue;var output=OutputImages(station);if(h.Route==null||h.Route.IsQuarantined||!h.Route.CurrentTail().Select(c=>c.Count.ToString(System.Globalization.CultureInfo.InvariantCulture)+":"+c.Image).SequenceEqual(output))throw new InvalidOperationException();if(q==null||!QueueMatches(h,q,q.Select(x=>x?.Recipe).ToArray())||!OrdinaryNativeCallsiteCandidate.TrySnapshotReceiptImages(station,out var rows)||!h.Original.Original.IsCurrent())throw new InvalidOperationException();if(!RebirthStationNativeQueueSnapshot.TryCapture(q,out var image)||!image.Matches(q))throw new InvalidOperationException();if(!rows.SequenceEqual(h.Route.CurrentReceipts()))throw new InvalidOperationException();var witness=new ExitWitness(h,q,output,rows,image);if(!witness.IsCurrent())throw new InvalidOperationException();h.Witness=witness;}catch{h.Quarantine="Original queue exit or ordered evidence failed";h.Route=h.Route?.QuarantineLifecycle();}finally{h.Busy=false;}}return original;}
}