using System;using System.Linq;using System.IO;using System.Text;using System.Xml;using System.Xml.Linq;using System.Globalization;using System.Collections.Generic;
// Tools-only versioned stored source DATA. Reading cannot mint native events, claim, restore or publish.
internal static class NativePaidOrdinaryChainCodec {
 internal const int MaximumBytes=8*1024*1024;
 internal sealed class StoredData {
  readonly XElement image;internal StoredData(XElement node){image=new XElement(node);}internal XElement Write()=>new XElement(image);internal bool MatchesRetainedLiveRouteData(NativePaidOrdinaryRouteLink route){try{return route!=null&&route.OriginalIsCurrentForData()&&route.TryWriteStoredData(out var xml)&&TryRead(xml,out var original)&&XNode.DeepEquals(image,original.image)&&route.OriginalIsCurrentForData();}catch{return false;}}internal bool CanPublish=>false;internal bool HasNativeEventAuthority=>false;internal string OriginalPaidJob=>(string)image.Attribute("job");internal bool IsQuarantined=>(string)image.Attribute("state")=="quarantined";
 }
 static readonly UTF8Encoding utf8=new UTF8Encoding(false,true);
 static bool Id(string text,int max=256)=>text!=null&&text.Length>0&&text.Length<=max&&text.Trim()==text&&!text.Any(char.IsControl);
 static bool Number(string text,out int n){return int.TryParse(text,NumberStyles.AllowLeadingSign,CultureInfo.InvariantCulture,out n)&&n.ToString(CultureInfo.InvariantCulture)==text;}
 static string EncodeText(string text)=>Convert.ToBase64String(utf8.GetBytes(text));
 static bool Base64(string text,int bound,out byte[] bytes){bytes=null;try{if(text==null||text.Length<1||text.Length>bound)return false;var b=Convert.FromBase64String(text);if(Convert.ToBase64String(b)!=text)return false;bytes=b;return true;}catch{return false;}}
 static bool Shape(XElement n,string name,string[] attrs,string[] children){if(n==null||n.Name!=name||n.Attributes().Count()!=attrs.Length||attrs.Any(a=>n.Attribute(a)==null)||n.Attributes().Any(a=>a.IsNamespaceDeclaration||a.Name.Namespace!=XNamespace.None)||n.Nodes().Any(x=>!(x is XElement)&&!(x is XText t&&string.IsNullOrWhiteSpace(t.Value))))return false;return n.Elements().Count()==children.Length&&children.All(x=>n.Elements(x).Count()==1);}
 static XElement Grid(string name,NativePaidOrdinaryRouteLink.Cell[] cells)=>new XElement(name,cells.Select((c,i)=>new XElement("cell",new XAttribute("index",i),new XAttribute("count",c.Count),new XAttribute("image",c.Image))));
 static XElement Receipts(string name,string[] images)=>new XElement(name,images.Select(x=>new XElement("row",new XAttribute("image",EncodeText(x)))));
 internal static bool TryWrite(RebirthStationCompletionCapture.SuccessfulOutput paid,NativePaidOrdinaryRouteLink.Cell[] before,NativePaidOrdinaryRouteLink.Cell[] after,NativePaidOrdinaryRouteLink.Cell[] tail,string[] receipts,NativePaidOrdinaryRouteLink.Transition[] transitions,int quantity,string originalReceipt,string quarantine,bool unresolvedHeld,out string xml){xml=null;try{
  var o=paid.Original;var admission=o.Admission.Write();var block=(string)admission.Attribute("block");var node=new XElement("nativePaidOrdinaryChain",new XAttribute("version",1),new XAttribute("job",o.Admission.JobId),new XAttribute("creation",o.Admission.CreationId),new XAttribute("definition",o.Admission.DefinitionId),new XAttribute("owner",o.Identity.StorageKey),new XAttribute("world",o.WorldGuid),new XAttribute("root",o.SaveRoot),new XAttribute("block",block),new XAttribute("x",o.Position.x),new XAttribute("y",o.Position.y),new XAttribute("z",o.Position.z),new XAttribute("paidQuantity",quantity),new XAttribute("state",quarantine==null?"pending":"quarantined"),new XAttribute("reason",quarantine??""),new XAttribute("unresolvedHeld",unresolvedHeld?1:0),new XElement("admission",EncodeText(admission.ToString(SaveOptions.DisableFormatting))),Receipts("paidReceipt",new[]{originalReceipt}),Grid("paidBefore",before),Grid("paidAfter",after),Grid("tail",tail),Receipts("receiptTail",receipts),new XElement("transitions",transitions.Select((t,i)=>new XElement("transition",new XAttribute("ordinal",i+1),new XAttribute("quantity",t.Quantity),new XAttribute("recipe",t.Original.NativeRecipeName),new XAttribute("actor",t.Original.NativeCrafter),Grid("before",t.Before()),Grid("after",t.After()),Receipts("receiptBefore",t.ReceiptBefore()),Receipts("receiptAfter",t.ReceiptAfter())))));
  var text=node.ToString(SaveOptions.DisableFormatting);if(!TryRead(text,out _))return false;xml=text;return true;
 }catch{return false;}}
 static bool ReadGrid(XElement n,out string[] image,out int[] counts){image=null;counts=null;try{if(n.HasAttributes||n.Elements().Count()<1||n.Elements().Count()>255||n.Nodes().Any(x=>!(x is XElement)&&!(x is XText t&&string.IsNullOrWhiteSpace(t.Value))))return false;var cells=n.Elements().ToArray();var images=new string[cells.Length];var q=new int[cells.Length];for(int i=0;i<cells.Length;i++){var c=cells[i];if(!Shape(c,"cell",new[]{"index","count","image"},new string[0])||!Number((string)c.Attribute("index"),out var index)||index!=i||!Number((string)c.Attribute("count"),out q[i])||q[i]<0||q[i]>65535||!Base64((string)c.Attribute("image"),262144,out _))return false;images[i]=(string)c.Attribute("image");}image=images;counts=q;return true;}catch{return false;}}
 static bool ReadReceipts(XElement n,out string[] rows){rows=null;try{if(n.HasAttributes||n.Elements().Count()>255||n.Nodes().Any(x=>!(x is XElement)&&!(x is XText t&&string.IsNullOrWhiteSpace(t.Value))))return false;var texts=new List<string>();foreach(var r in n.Elements()){if(!Shape(r,"row",new[]{"image"},new string[0])||!Base64((string)r.Attribute("image"),524288,out var bytes))return false;var text=utf8.GetString(bytes);if(!SafeDocument(text,out var receipt)||!Shape(receipt,"nativeReceipt",new[]{"actor","recipe","scrap","xp","used","count","image"},new string[0])||!Number((string)receipt.Attribute("actor"),out _)||!Number((string)receipt.Attribute("xp"),out var xp)||xp<0||!Number((string)receipt.Attribute("used"),out var used)||used<0||used>65535||!Number((string)receipt.Attribute("count"),out var count)||count<0||count>65535||!Base64((string)receipt.Attribute("image"),262144,out _)||((string)receipt.Attribute("recipe")).Length>256||((string)receipt.Attribute("scrap")).Length>256)return false;texts.Add(text);}rows=texts.ToArray();return true;}catch{return false;}}
 static bool SafeDocument(string text,out XElement root){root=null;try{if(text==null||utf8.GetByteCount(text)>MaximumBytes)return false;var settings=new XmlReaderSettings{DtdProcessing=DtdProcessing.Prohibit,XmlResolver=null,MaxCharactersInDocument=MaximumBytes};using(var reader=XmlReader.Create(new StringReader(text),settings)){int nodes=0;while(reader.Read()){if(++nodes>160000||reader.Depth>12||reader.NodeType==XmlNodeType.Comment||reader.NodeType==XmlNodeType.ProcessingInstruction||reader.NodeType==XmlNodeType.CDATA||reader.NodeType==XmlNodeType.DocumentType)return false;}}root=XElement.Parse(text,LoadOptions.PreserveWhitespace);return !root.DescendantsAndSelf().Any(n=>n.Name.Namespace!=XNamespace.None||n.Attributes().Any(a=>a.IsNamespaceDeclaration||a.Name.Namespace!=XNamespace.None));}catch{return false;}}
 static bool Same(string[] a,int[] ac,string[] b,int[] bc)=>a.SequenceEqual(b)&&ac.SequenceEqual(bc);
 internal static bool TryRead(string xml,out StoredData stored){stored=null;try{if(!SafeDocument(xml,out var n)||!Shape(n,"nativePaidOrdinaryChain",new[]{"version","job","creation","definition","owner","world","root","block","x","y","z","paidQuantity","state","reason","unresolvedHeld"},new[]{"admission","paidReceipt","paidBefore","paidAfter","tail","receiptTail","transitions"})||(string)n.Attribute("version")!="1")return false;foreach(var key in new[]{"job","creation","owner","world","block"})if(!Id((string)n.Attribute(key)))return false;if(((string)n.Attribute("definition")).Length!=64||((string)n.Attribute("definition")).Any(c=>!Uri.IsHexDigit(c)))return false;if(!Id((string)n.Attribute("root"),4096)||!Number((string)n.Attribute("x"),out _)||!Number((string)n.Attribute("y"),out _)||!Number((string)n.Attribute("z"),out _)||!Number((string)n.Attribute("paidQuantity"),out var paid)||paid<1||paid>32767||!Number((string)n.Attribute("unresolvedHeld"),out var held)||held<0||held>1)return false;var state=(string)n.Attribute("state");var reason=(string)n.Attribute("reason");if(state!="pending"&&state!="quarantined"||reason.Length>256||reason.Any(char.IsControl)||state=="pending"&&(reason!=""||held!=0)||state=="quarantined"&&!Id(reason))return false;
 var admission=n.Element("admission");if(admission.HasAttributes||admission.HasElements||admission.Nodes().Any(x=>!(x is XText))||!Base64(admission.Value,524288,out var admitted)||!SafeDocument(utf8.GetString(admitted),out var admissionData)||(string)admissionData.Attribute("job")!=(string)n.Attribute("job")||admissionData.Name!="stationAdmission"||!new[]{"creation","definition","x","y","z","block"}.All(key=>(string)admissionData.Attribute(key)==(string)n.Attribute(key))||((string)admissionData.Attribute("version")!="1"&&(string)admissionData.Attribute("version")!="2"))return false;
 if(!ReadReceipts(n.Element("paidReceipt"),out var originalReceiptRows)||originalReceiptRows.Length!=1||!Number((string)XElement.Parse(originalReceiptRows[0]).Attribute("count"),out var originalPaidCount)||originalPaidCount!=paid||(string)XElement.Parse(originalReceiptRows[0]).Attribute("used")!="1")return false;
 if(!ReadGrid(n.Element("paidBefore"),out var pb,out var pbc)||!ReadGrid(n.Element("paidAfter"),out var pa,out var pac)||!ReadGrid(n.Element("tail"),out var tail,out var tailc)||!ReadReceipts(n.Element("receiptTail"),out var receiptTail))return false;long delta=0;if(pb.Length!=pa.Length)return false;for(int i=0;i<pb.Length;i++){if(pac[i]<pbc[i]||pbc[i]>0&&pb[i]!=pa[i])return false;delta+=(long)pac[i]-pbc[i];}if(delta!=paid)return false;
 var chain=n.Element("transitions");if(chain.HasAttributes||chain.Elements().Count()>64||chain.Nodes().Any(x=>!(x is XElement)&&!(x is XText t&&string.IsNullOrWhiteSpace(t.Value))))return false;var current=pa;var currentCount=pac;string[] currentReceipts=null;int ordinal=0;foreach(var t in chain.Elements()){if(!Shape(t,"transition",new[]{"ordinal","quantity","recipe","actor"},new[]{"before","after","receiptBefore","receiptAfter"})||!Number((string)t.Attribute("ordinal"),out var position)||position!=++ordinal||!Number((string)t.Attribute("quantity"),out var q)||q<1||q>65535||!Id((string)t.Attribute("recipe"))||!Number((string)t.Attribute("actor"),out _)||!ReadGrid(t.Element("before"),out var b,out var bc)||!ReadGrid(t.Element("after"),out var a,out var ac)||!ReadReceipts(t.Element("receiptBefore"),out var rb)||!ReadReceipts(t.Element("receiptAfter"),out var ra)||b.Length!=a.Length)return false;long addition=0;for(int i=0;i<b.Length;i++){if(ac[i]<bc[i]||bc[i]>0&&a[i]!=b[i])return false;addition+=(long)ac[i]-bc[i];}if(addition!=q)return false;if(state=="pending"&&(!Same(current,currentCount,b,bc)||currentReceipts!=null&&!currentReceipts.SequenceEqual(rb)))return false;current=a;currentCount=ac;currentReceipts=ra;}
 if(state=="pending"&&(!Same(current,currentCount,tail,tailc)||currentReceipts!=null&&!currentReceipts.SequenceEqual(receiptTail)))return false;stored=new StoredData(n);return true;
 }catch{return false;}}
}




