using System;using System.Linq;using System.Collections.Generic;using System.Xml.Linq;
// Tools-only linkage. Original paid JobId is retained; durable ordinary transitions/publisher authority absent.
internal sealed class NativePaidOrdinaryRouteLink {
 internal sealed class Cell {internal readonly string Image;internal readonly int Count;internal Cell(string i,int c){Image=i;Count=c;}}
 internal sealed class Transition {
  internal readonly OrdinaryNativeCallsiteCandidate.Addition Original;internal readonly int Quantity;readonly Cell[] before,after;readonly string[] receiptBefore,receiptAfter;
  internal Transition(OrdinaryNativeCallsiteCandidate.Addition e,Cell[] b,Cell[] a,string[] rb,string[] ra){Original=e;Quantity=e.Quantity;before=b;after=a;receiptBefore=rb;receiptAfter=ra;}
  internal Cell[] Before()=>(Cell[])before.Clone();internal Cell[] After()=>(Cell[])after.Clone();internal string[] ReceiptBefore()=>(string[])receiptBefore.Clone();internal string[] ReceiptAfter()=>(string[])receiptAfter.Clone();
 }
 internal enum Result {Refused,Staged,RetrievedOriginal,Quarantined}
 readonly RebirthStationCompletionCapture.SuccessfulOutput paid;readonly Cell[] before,paidAfter,tail;readonly string[] receipts;readonly string originalReceipt;readonly Transition[] transitions;readonly OrdinaryNativeCallsiteCandidate.Addition held;internal readonly string QuarantineReason;internal readonly int PaidQuantity;
 internal int HeldOriginalCount=>held==null?0:1;internal bool IsQuarantined=>QuarantineReason!=null;internal string OriginalPaidJob=>paid.Original.Admission.JobId;internal bool HasDurableOrdinaryTransitionBinding=>false;internal bool CanPublish=>false;internal bool HasSavedProjectionPairWitness=>false;
 NativePaidOrdinaryRouteLink(RebirthStationCompletionCapture.SuccessfulOutput e,Cell[] b,Cell[] a,Cell[] tail,string[] r,Transition[] t,int quantity,string originalReceipt,string reason=null,OrdinaryNativeCallsiteCandidate.Addition held=null){paid=e;before=b;paidAfter=a;this.tail=tail;receipts=r;transitions=t;PaidQuantity=quantity;this.originalReceipt=originalReceipt;QuarantineReason=reason;this.held=held;}
 internal Cell[] PaidBefore()=>(Cell[])before.Clone();internal Cell[] PaidAfter()=>(Cell[])paidAfter.Clone();internal Cell[] CurrentTail()=>(Cell[])tail.Clone();internal Transition[] Transitions()=>(Transition[])transitions.Clone();internal string OriginalPaidReceiptImage=>originalReceipt;internal bool MatchesOriginalPaidEvent(RebirthStationCompletionCapture.SuccessfulOutput e)=>ReferenceEquals(paid,e);internal string[] CurrentReceipts()=>(string[])receipts.Clone();
 static bool Same(Cell[] a,Cell[] b)=>a.Length==b.Length&&a.Zip(b,(l,r)=>l.Count==r.Count&&l.Image==r.Image).All(x=>x);
 static Cell[] Freeze(ItemStack[] a){if(a==null||a.Length<1||a.Length>255)throw new InvalidOperationException();var snapshots=a.Select(s=>s.Clone()).ToArray();var cells=snapshots.Select(s=>new Cell(RebirthNativeItemCodec.Encode(s.itemValue),s.count)).ToArray();if(cells.Any(c=>c.Count<0||c.Count>65535||c.Image.Length<1||c.Image.Length>262144)||cells.Sum(c=>(long)c.Image.Length)>8*1024*1024||!a.Zip(snapshots,(l,r)=>RebirthStationGridIngredients.IsSameStackSnapshot(l,r)).All(x=>x))throw new InvalidOperationException();var verified=snapshots.Select(x=>new Cell(RebirthNativeItemCodec.Encode(x.itemValue),x.count)).ToArray();if(!Same(cells,verified)||!a.Zip(snapshots,(l,r)=>RebirthStationGridIngredients.IsSameStackSnapshot(l,r)).All(x=>x))throw new InvalidOperationException();return cells;}
 static string ReceiptImage(CraftCompleteData r)=>new XElement("nativeReceipt",new XAttribute("actor",r.CrafterEntityID),new XAttribute("recipe",r.RecipeName??""),new XAttribute("scrap",r.ItemScrapped??""),new XAttribute("xp",r.CraftExpGain),new XAttribute("used",r.RecipeUsedCount),new XAttribute("count",r.CraftedItemStack.count),new XAttribute("image",RebirthNativeItemCodec.Encode(r.CraftedItemStack.itemValue))).ToString(SaveOptions.DisableFormatting);
 static string[] ReceiptImages(TileEntityWorkstation s){if(!OrdinaryNativeCallsiteCandidate.TrySnapshotReceiptImages(s,out var rows))throw new InvalidOperationException();return rows;}
 internal static bool TryStageBeforeOrdinary(RebirthStationCompletionCapture.SuccessfulOutput e,out NativePaidOrdinaryRouteLink route){route=null;try{if(e==null||!e.TryCopyPhysicalDelta(out var b,out var a,out var r))return false;var fb=Freeze(b);var fa=Freeze(a);var originalReceipt=ReceiptImage(r);var receipts=ReceiptImages(e.Original.Station);if(fb.Sum(c=>(long)c.Image.Length)+fa.Sum(c=>(long)c.Image.Length)+receipts.Sum(x=>(long)x.Length)+originalReceipt.Length>8*1024*1024)return false;if(!Same(fa,Freeze(e.Original.Station.Output))||!e.Original.IsCurrent()||!e.MatchesReceipt()||!receipts.SequenceEqual(ReceiptImages(e.Original.Station))||!Same(fa,Freeze(e.Original.Station.Output))||originalReceipt!=ReceiptImage(r)||!e.Original.IsCurrent())return false;route=new NativePaidOrdinaryRouteLink(e,fb,fa,fa,receipts,new Transition[0],r.CraftedItemStack.count,originalReceipt);return true;}catch{return false;}}
 NativePaidOrdinaryRouteLink Quarantine(string reason,OrdinaryNativeCallsiteCandidate.Addition e,Transition extra=null){var t=transitions;if(extra!=null)t=transitions.Concat(new[]{extra}).ToArray();return new NativePaidOrdinaryRouteLink(paid,before,paidAfter,tail,receipts,t,PaidQuantity,originalReceipt,reason,e);}
 internal Result TryAppendOriginal(OrdinaryNativeCallsiteCandidate.Addition e,out NativePaidOrdinaryRouteLink next){next=null;if(e==null||!e.MatchesOriginal(paid))return Result.Refused;if(transitions.Any(t=>t.Original.SameOriginal(e))){next=this;return Result.RetrievedOriginal;}if(IsQuarantined){next=this;return Result.Quarantined;}try{if(!e.TryConsumeEvidence(out var b,out var a,out var rb,out var ra)){next=Quarantine("Original native evidence unavailable; custody retained",e);return Result.Quarantined;}var fb=Freeze(b);var fa=Freeze(a);var transition=new Transition(e,fb,fa,(string[])rb.Clone(),(string[])ra.Clone());long cost=before.Sum(c=>(long)c.Image.Length)+paidAfter.Sum(c=>(long)c.Image.Length)+receipts.Sum(x=>(long)x.Length)+originalReceipt.Length;foreach(var t in transitions.Concat(new[]{transition}))cost+=t.Before().Sum(c=>(long)c.Image.Length)+t.After().Sum(c=>(long)c.Image.Length)+t.ReceiptBefore().Sum(x=>(long)x.Length)+t.ReceiptAfter().Sum(x=>(long)x.Length);long added=0;bool physical=fb.Length==fa.Length;for(int i=0;physical&&i<fb.Length;i++){if(fa[i].Count<fb[i].Count||fb[i].Count>0&&fa[i].Image!=fb[i].Image)physical=false;added+=(long)fa[i].Count-fb[i].Count;}
 if(transitions.Length>=64||cost>8*1024*1024||!Same(fb,tail)||!rb.SequenceEqual(receipts)||!physical||added!=e.Quantity||!paid.Original.IsCurrent()){next=Quarantine("Ordered native output/receipt chain mismatch or bound exceeded",e,transition);return Result.Quarantined;}
 next=new NativePaidOrdinaryRouteLink(paid,before,paidAfter,fa,(string[])ra.Clone(),transitions.Concat(new[]{transition}).ToArray(),PaidQuantity,originalReceipt);return Result.Staged;
 }catch{next=Quarantine("Native snapshot callback failed; original retained",e);return Result.Quarantined;}}
 internal bool OriginalIsCurrentForData()=>paid.Original.IsCurrent();
 internal bool TryWriteStoredData(out string xml)=>NativePaidOrdinaryChainCodec.TryWrite(paid,before,paidAfter,tail,receipts,transitions,PaidQuantity,originalReceipt,QuarantineReason,held!=null&&!transitions.Any(t=>t.Original.SameOriginal(held)),out xml);
 internal NativePaidOrdinaryRouteLink QuarantineLifecycle()=>Quarantine("Original lifecycle retirement unresolved; retained without publication",held);
}






