using System.Xml.Linq;
using System.Text;
using System.Reflection;
using Noemax.GZip;
class Program {
 static int count;static void A(bool b,string name){if(!b)throw new Exception(name);count++;}
 static byte[][] Spans(TileEntityWorkstation s){RebirthStationTerminalContents.Decoded=s.Output.Select(x=>x.Clone()).ToArray();RebirthNativeItemConformanceReader.Decoded=(s.CraftCompleteList??new List<CraftCompleteData>()).ToArray();return new[]{Encoding.UTF8.GetBytes(string.Join("|",s.Input.Select(x=>x.count+":"+RebirthNativeItemCodec.Encode(x.itemValue)))),Encoding.UTF8.GetBytes((string)typeof(RebirthStationNativeQueueSnapshot).GetMethod("Encode",BindingFlags.Static|BindingFlags.NonPublic).Invoke(null,new object[]{s.Queue})),new byte[]{2},new byte[]{1}};}
 static byte[] Pack(byte[] raw){using(var m=new MemoryStream()){m.Write(new byte[]{116,116,99,0,47,0,0,0});var z=new DeflateOutputStream(m,3,true);z.Write(raw,0,raw.Length);z.Restart();return m.ToArray();}}
 static byte[] Region(byte[] p){int sectors=(p.Length+16+4095)/4096;var f=new byte[(3+sectors)*4096];f[0]=55;f[1]=114;f[2]=103;f[3]=1;f[4096]=3;f[4099]=(byte)sectors;Buffer.BlockCopy(BitConverter.GetBytes(p.Length),0,f,12288,4);Buffer.BlockCopy(p,0,f,12304,p.Length);return f;}
 static RebirthStationSnapshotEvidence.Publication Publish(RebirthStationSnapshotEvidence.Request request,TileEntityWorkstation s,string path){
 var world=(World)request.World;var obj=new object();var frame=RebirthStationSnapshotEvidence.Begin(obj,world.Chunk,world,0,0,true);using(var m=new MemoryStream()){m.Write(new byte[]{116,116,99,0,47,0,0,0});var parts=Spans(s);for(int k=0;k<4;k++){long start=k<2?RebirthStationSnapshotEvidence.StartStationSpan(s,m):RebirthStationSnapshotEvidence.StartTerminalSpan(s,m);m.Write(parts[k]);if(k<2)RebirthStationSnapshotEvidence.CaptureStationSpan(s,m,start,k==0);else RebirthStationSnapshotEvidence.CaptureTerminalSpan(s,m,start,k==2);}RebirthStationSnapshotEvidence.Serialized(world.Chunk,m);m.Position=0;RebirthStationSnapshotEvidence.Finish(frame,m,null);var payload=Pack(m.ToArray().Skip(8).ToArray());File.WriteAllBytes(path,Region(payload));RebirthStationSnapshotEvidence.MarkPublished(request,obj,request.Generation,path,RebirthStationPublicationRecord.Digest(payload));A(RebirthStationSnapshotEvidence.TryGetPublished(request,out var proof),"actual snapshot publication");return proof;}}
 static void Main(){string root=Path.Combine(Path.GetTempPath(),"mixed-connected-"+Guid.NewGuid().ToString("N"));Directory.CreateDirectory(Path.Combine(root,"Region"));Directory.CreateDirectory(Path.Combine(root,"characters"));GameIO.Root=root;RebirthWorldCharacterRepository.RootDirectory=Path.Combine(root,"characters");string region=Path.Combine(root,"Region","r.0.0.7rg");
 try{
 var a=new RebirthStationGridAdmission();var paidQueue=new RecipeQueueItem{StartingEntityId=1,Recipe=new(){Marked=true,Name="job"}};
 var s=new TileEntityWorkstation{Queue=new[]{paidQueue},Output=new[]{new ItemStack(new ItemValue(10),3),new ItemStack(new ItemValue(0),0)}};var w=new World{Station=s};w.Player=new(){world=w};GameManager.Instance=new(){World=w};var owner=new RebirthWorldCharacterRecord();RebirthWorldCharacterService.Owner=owner;owner.Progression.StationPreparations.Add(a.JobId,a);RebirthStationObservationDispatcher.Verified=true;
 var request=RebirthStationSnapshotEvidence.Watch(w,w.Chunk,0,0,()=>true,s,(i,q)=>true,(o,r)=>true);var queuedProof=Publish(request,s,region);A(RebirthStationPublicationRecord.TryCreate(root,a,1,queuedProof,out var queued),"actual strict queued record");owner.Progression.StationPublications.Add(a.JobId,queued);request.Dispose();
 A(RebirthStationCompletionCapture.TryObserveBefore(s,1,new ItemValue(10),"job","",7,2,out var before),"actual original paid before");s.Output[0].count=5;A(RebirthStationCompletionCapture.TryAppend(s,1,new ItemValue(10),"job","",7,2,before,out var paid)&&OrdinaryNativeCallsiteCandidate.Bind(paid),"actual paid event");
 MixedExpectationCandidate.Anchor anchor=null;A(NativePaidOrdinaryRouteLink.TryStageBeforeOrdinary(paid,out var route)&&MixedExpectationCandidate.Anchor.TryCapture(paid,route,out anchor),"original anchor");A(NativePaidOrdinaryExitCandidate.AfterPaidRetained(paid,paidQueue,1,new ItemValue(10),"job","",7,2),"original exporter");s.Queue=new[]{new RecipeQueueItem{StartingEntityId=1,Recipe=new(){Name="ordinary"}}};s.ActualObservedWhile(1);NativePaidOrdinaryExitCandidate.OnOriginalExit(s,null);A(NativePaidOrdinaryExitCandidate.TryGetOriginal(paid,out var held)&&held.Witness!=null,"original exit");
 A(RebirthStationTerminalIntent.TryCreate(a,true,1,out var intent),"actual strict completion intent");owner.Progression.StationTerminalIntents.Add(a.JobId,intent);
 var peer=new MixedAtomicPublicationCandidate(w.Chunk);A(StationMixedSnapshotWatchCandidate.TryBegin(paid,held.Route,held.Witness,new TypedMixedWatchExpectationFactory(anchor),peer,out var watch),"actual watch plus concrete atomic peer");A(!watch.TryPump(out _)&&watch.RetainedRequest!=null,"pending original registration");var finalProof=Publish(watch.RetainedRequest,s,region);
 var typed=(TypedMixedWatchExpectation)typeof(StationMixedSnapshotWatchCandidate).GetField("expectation",BindingFlags.Instance|BindingFlags.NonPublic).GetValue(watch);
 var manufactured=new RebirthStationSnapshotEvidence.Publication(finalProof.Path,finalProof.PayloadDigest,finalProof.ChunkX,finalProof.ChunkZ,finalProof.InputStart,finalProof.InputLength,finalProof.QueueStart,finalProof.QueueLength,finalProof.OutputStart,finalProof.OutputLength,finalProof.CompletionStart,finalProof.CompletionLength);
 A(!new MixedAtomicPublicationCandidate(w.Chunk).TryStage(typed,manufactured,out var manufacturedStage)&&manufacturedStage==null,"identical-field manufactured publication cannot stage");
 A(!MixedLiveRecordCandidate.TryCapturePublished(typed,manufactured,out var manufacturedLive)&&manufacturedLive==null,"private live record cannot accept manufactured publication capability");
 A(!new MixedAtomicPublicationCandidate(new Chunk()).TryStage(typed,finalProof,out var wrongChunk)&&wrongChunk==null,"wrong original chunk cannot stage genuine proof");
 RebirthWorldCharacterService.ThrowDirty=true;A(!watch.TryPump(out _)&&watch.RetainedStage!=null,"dirty throws preeffect stage exposed and retained");var stage=watch.RetainedStage;RebirthStationSnapshotEvidence.Invalidate(watch.RetainedRequest.Snapshot);A(!MixedLiveRecordCandidate.TryCapturePublished(typed,finalProof,out var staleLive)&&staleLive==null,"released pooled capability cannot construct new live record");var data=owner.Progression.StationMixedCompletionRecords[a.JobId];A(!owner.Dirty&&RebirthWorldCharacterService.DirtyCalls==1,"original dirty effect absent");
 RebirthWorldCharacterService.AfterDirty=()=>GameIO.Root=root+".changed";A(!watch.TryPump(out _)&&ReferenceEquals(stage,watch.RetainedStage)&&ReferenceEquals(data,owner.Progression.StationMixedCompletionRecords[a.JobId])&&RebirthWorldCharacterRepository.Saves==0,"after dirty scope mutation retains same stage+data without save");RebirthWorldCharacterService.AfterDirty=null;GameIO.Root=root;
 A(watch.TryPump(out var published)&&ReferenceEquals(stage,published)&&ReferenceEquals(data,owner.Progression.StationMixedCompletionRecords[a.JobId]),"same stage+data retry marks saves and witnesses actual region/finalXML");A(RebirthWorldCharacterService.DirtyCalls==3&&RebirthWorldCharacterRepository.Saves==1,"same dirty obligation retries without stage remint");
 var duplicatePeer=new MixedAtomicPublicationCandidate(w.Chunk);A(!duplicatePeer.TryStage(stage.Expectation,stage.Snapshot,out var duplicateStage)&&duplicateStage==null,"new peer cannot remint stage for already original committed tuple");
 owner.Progression.StationCompletionPublications.Add(a.JobId,new());A(!peer.TrySaveAndWitness(stage)&&!RebirthWorldCharacterRepository.ValidateStationMixedProspective(owner,data),"same-job ordinary publication overlap refuses without losing mixed original");owner.Progression.StationCompletionPublications.Remove(a.JobId);
 owner.Progression.StationCompletionExpectationProjections.Add(a.JobId,new object());A(!peer.TrySaveAndWitness(stage),"same-job ordinary expectation overlap refuses");owner.Progression.StationCompletionExpectationProjections.Remove(a.JobId);
 owner.Progression.StationCompletionPublications.Add("other-job",new());owner.Progression.StationCompletionExpectationProjections.Add("other-job",new object());A(peer.TrySaveAndWitness(stage),"other-job ordinary representations coexist with original mixed");owner.Progression.StationCompletionPublications.Remove("other-job");owner.Progression.StationCompletionExpectationProjections.Remove("other-job");
 A(peer.TrySaveAndWitness(stage)&&RebirthWorldCharacterRepository.Saves==1,"clean saved exact original repeat witnesses no save");
 var live=((MixedAtomicPublicationCandidate.Stage)stage).Live;A(live.RevalidatePublished(),"actual final region typed revalidation");A(!live.Publication.Revalidate(root+".foreign",a,intent,queued,(TypedMixedWatchExpectation)stage.Expectation),"foreign save root refuses");var originalFile=File.ReadAllBytes(region);File.WriteAllBytes(region,new byte[128]);A(!peer.TrySaveAndWitness(stage),"corrupt region cannot witness");File.WriteAllBytes(region,originalFile);A(peer.TrySaveAndWitness(stage),"same original region restored retry");
 string final=Path.Combine(RebirthWorldCharacterRepository.RootDirectory,"owner.xml");var saved=File.ReadAllText(final);File.Copy(final,final+".bak");File.WriteAllText(final,"<broken>");A(!peer.TrySaveAndWitness(stage),"corrupt final valid backup refuses");File.WriteAllText(final,saved);A(peer.TrySaveAndWitness(stage),"same final restored retry");
 var old=data;owner.Progression.StationMixedCompletionRecords[a.JobId]=data.Clone();A(!peer.TrySaveAndWitness(stage),"same XML detached cache tuple refuses");owner.Progression.StationMixedCompletionRecords[a.JobId]=old;A(peer.TrySaveAndWitness(stage),"same reference restored");
 RebirthWorldCharacterRepository.FailSupport=true;A(!peer.TrySaveAndWitness(stage),"actual outer support failure no partial saved authority");RebirthWorldCharacterRepository.FailSupport=false;
 var image=live.Publication.Write();image.SetAttributeValue("payload",new string('B',64));A(MixedNativePublicationCandidate.TryRead(image,a,intent,queued,out var cold)&&!cold.Revalidate(root,a,intent,queued,(TypedMixedWatchExpectation)stage.Expectation),"well formed cold digest DATA cannot replace real final region publication");
 var admissions=owner.Progression.StationPreparations;var intents=owner.Progression.StationTerminalIntents;var qs=owner.Progression.StationPublications;
 var section=new XElement("stationCompletionPublications",new XAttribute("version",1),live.Publication.Write());A(MixedNativePublicationCandidate.ReadAll(new XElement("progression",section),admissions,intents,qs,out var parsedRows)&&parsedRows.Count==1,"typed publication section DATA valid");
 var duplicateSection=new XElement(section);duplicateSection.Add(live.Publication.Write());A(!MixedNativePublicationCandidate.ReadAll(new XElement("progression",duplicateSection),admissions,intents,qs,out parsedRows)&&parsedRows==null,"typed section duplicate failure has no partial out dictionary");
 var malformedSection=new XElement(section);malformedSection.Add(new XElement("bad",new XAttribute("job","other")));A(!MixedNativePublicationCandidate.ReadAll(new XElement("progression",malformedSection),admissions,intents,qs,out parsedRows)&&parsedRows==null,"typed section late malformed failure atomic null out");
 A(MixedNativePublicationCandidate.ReadAll(new XElement("progression"),admissions,intents,qs,out parsedRows)&&parsedRows.Count==0,"typed section old absence accepted");
 owner.Dirty=true;RebirthWorldCharacterRepository.ThrowAfterWrite=true;A(!peer.TrySaveAndWitness(stage)&&ReferenceEquals(data,owner.Progression.StationMixedCompletionRecords[a.JobId]),"after finalfile write uncertainty retains same stage DATA");A(peer.TrySaveAndWitness(stage)&&ReferenceEquals(data,owner.Progression.StationMixedCompletionRecords[a.JobId]),"same original after uncertain save retry witnesses");
 Console.WriteLine("PASS "+count+" connected actual watcher/atomic peer/strict region+intent+publication/final loader; native span and unrelated outer parser leaves explicit adapters");
 }finally{Directory.Delete(root,true);}}
}
