using System;
class World{public object Actor;public object GetEntity(int id)=>Actor;public bool Remote;public bool IsRemote()=>Remote;}
class GameManager{public static GameManager Instance=new GameManager();public World World;}
class Log{public static void Warning(string s){}}
class EntityRebirthNPC{public World world;public int Calls;public bool Admit,hasAI;public Action Callback;public bool TryAdmitPreparedAi(string replay,uint generation){Calls++;Callback?.Invoke();return Admit;}}
class Program{
 static int n;static void Check(bool ok,string name){if(!ok)throw new Exception(name);n++;}
 static void Main(){var w=new World();GameManager.Instance.World=w;var a=new EntityRebirthNPC{world=w};Check(RebirthNpcPreparedSchedulerAdmission.TrySchedule(a,"original",1),"enqueue");Check(RebirthNpcPreparedSchedulerAdmission.TrySchedule(a,"original",1),"duplicate idempotent");RebirthNpcPreparedSchedulerAdmission.Tick();Check(a.Calls==1,"duplicate single callback");RebirthNpcPreparedSchedulerAdmission.Tick();Check(a.Calls==2,"failed owner retained");var b=new EntityRebirthNPC{world=w,Admit=true};a.Callback=()=>RebirthNpcPreparedSchedulerAdmission.TrySchedule(b,"new",1);a.Admit=true;RebirthNpcPreparedSchedulerAdmission.Tick();Check(b.Calls==0,"reentrant deferred");RebirthNpcPreparedSchedulerAdmission.Tick();Check(b.Calls==1,"next tick admits");RebirthNpcPreparedSchedulerAdmission.Tick();Check(b.Calls==1,"success dequeued");a.Callback=null;a.Admit=false;RebirthNpcPreparedSchedulerAdmission.TrySchedule(a,"retained",1);GameManager.Instance.World=new World();RebirthNpcPreparedSchedulerAdmission.Tick();Check(a.Calls==3,"foreign world never admitted");RebirthNpcPreparedSchedulerAdmission.RetireSavedWorld(w,false);GameManager.Instance.World=w;RebirthNpcPreparedSchedulerAdmission.Tick();Check(a.Calls==4,"failed save retains owner");RebirthNpcPreparedSchedulerAdmission.RetireSavedWorld(w,true);RebirthNpcPreparedSchedulerAdmission.Tick();Check(a.Calls==4,"successful teardown retires scheduling");for(int i=0;i<256;i++)Check(RebirthNpcPreparedSchedulerAdmission.TrySchedule(new EntityRebirthNPC{world=w},"r"+i,1),"capacity slot");Check(!RebirthNpcPreparedSchedulerAdmission.TrySchedule(new EntityRebirthNPC{world=w},"overflow",1),"capacity bounded");RebirthNpcPreparedSchedulerAdmission.RetireSavedWorld(w,true);Check(RebirthNpcPreparedSchedulerAdmission.TrySchedule(a,"after",1),"saved retirement frees slots");n+=UnexpectedBoundaryFixture.Run();n+=AdmissionFixture.Run();Console.WriteLine(n+" PASS actual scheduler queue and extracted original admission");}
}
