using System;using System.Collections.Generic;
namespace UnityEngine {public struct Vector2 {public float x,y;public Vector2(float a,float b){x=a;y=b;}} public struct Vector3 {public float x,y,z;public Vector3(float a,float b,float c){x=a;y=b;z=c;} } }
struct Vector3i {public Vector3i(UnityEngine.Vector3 value){} }
class ThreadManager {public static bool IsMainThread()=>true;}
public class WorldState {public string Guid=System.Guid.NewGuid().ToString("N").ToUpperInvariant();}
public class World {public WorldState worldState=new WorldState();public bool Remote;public ulong worldTime=12;public EntityPlayerLocal Player;public bool IsRemote()=>Remote;public EntityPlayerLocal GetPrimaryPlayer()=>Player;public EntityPlayerLocal GetEntity(int id)=>Player!=null&&Player.entityId==id?Player:null;}
public class EntityPlayer {public World world;public QuestJournal QuestJournal;public int entityId=1;public bool Dead;public bool IsDead()=>Dead;public bool IsSpawned()=>true;} public class EntityPlayerLocal:EntityPlayer {}
public class GameManager {public static GameManager Instance;public World World;public static int Tooltips;public static void ShowTooltip(EntityPlayerLocal p,string text){Tooltips++;}}
public class NativeConnection {public bool Disconnected;public bool IsDisconnected()=>Disconnected;}
public class ConnectionManager {public List<NetPackage> Sent=new List<NetPackage>();public void SendToServer(NetPackage p){Sent.Add(p);}public Clients Clients=new Clients();public bool IsServer;public NativeConnection[] connectionToServer=new[]{new NativeConnection()};}
class SingletonMonoBehaviour<T> {public static T Instance;}
enum EnumGamePrefs {GameGuidClient}
class GamePrefs {public static string Guid;public static string GetString(EnumGamePrefs key)=>Guid;}
public class QuestClass {public int DifficultyTier=2;public bool Available=true;public bool CanActivate()=>Available;}
public class QuestJournal {public EntityPlayerLocal OwnerPlayer;public List<Quest> quests=new List<Quest>();public Quest ActiveQuest,TrackedQuest;public int Refreshes,History;public void RefreshTracked(){Refreshes++;}public void AddPOIToTraderData(int tier,UnityEngine.Vector3 a,UnityEngine.Vector3 b){History++;}}
public class Quest {public enum QuestState {InProgress,Failed}public enum PositionDataTypes {POIPosition,TraderPosition}public string ID="clear",QuestUniqueId="original-quest";public int QuestCode=-12;public int SharedOwnerID=-1;public System.Collections.Generic.List<ObjectiveRallyPoint> Objectives=new System.Collections.Generic.List<ObjectiveRallyPoint>();public byte CurrentPhase;public QuestState CurrentState=QuestState.InProgress;public bool RallyMarkerActivated,Tracked,Requirements=true;public QuestJournal OwnerJournal;public QuestClass QuestClass=new QuestClass();public Dictionary<PositionDataTypes,UnityEngine.Vector3> PositionData=new Dictionary<PositionDataTypes,UnityEngine.Vector3>();public int Removed,PartyPruned;public void RemoveSharedNotInRange(){PartyPruned++;}public bool CheckRequirements()=>Requirements;public void RemoveMapObject(){Removed++;}}
public class ObjectiveRallyPoint {public static ObjectiveRallyPoint OutstandingRallyPoint;public Quest OwnerQuest;public bool Complete;public byte Phase,CurrentValue;public int Party,Finished;public bool ThrowParty;public int startTime=-1,endTime=-1;public string activateEvent="event";public void HandleParty(){Party++;if(ThrowParty)throw new Exception("native party failure");}public void RallyPointActivated(){Finished++;CurrentValue=1;OutstandingRallyPoint=null;}}
class GameEventManager {public static GameEventManager Current=new GameEventManager();public int Events;public void HandleAction(string key,object a,EntityPlayerLocal b,bool twitchActivated,Vector3i position){Events++;}}
public class ClientInfo {public bool loginDone=true;public List<NetPackage> Sent=new List<NetPackage>();public void SendPackage(NetPackage p){Sent.Add(p);}public int entityId=1;public PlayerDataFile latestPlayerData;}
public class PlayerDataFile {public int id=1;public QuestJournal questJournal;}
public class Clients {public ClientInfo Sender;public ClientInfo ForEntityId(int id)=>Sender!=null&&Sender.entityId==id?Sender:null;}
class GameIO {public static string Save;public static string GetSaveGameDir()=>Save;}
namespace HarmonyLib {class HarmonyPatch:Attribute{public HarmonyPatch(Type t,string s){}}class HarmonyPriority:Attribute{public HarmonyPriority(int n){}}class Priority{public const int First=1;}}
namespace UnityEngine.Scripting {class PreserveAttribute:Attribute{}}
public class PooledBinaryReader:System.IO.BinaryReader{public PooledBinaryReader():base(new System.IO.MemoryStream()){}}
public class PooledBinaryWriter:System.IO.BinaryWriter{public PooledBinaryWriter():base(new System.IO.MemoryStream()){}}
public enum NetPackageDirection{ToServer,ToClient}
public class NetPackage {public ClientInfo Sender;public virtual NetPackageDirection PackageDirection=>default;public virtual void read(PooledBinaryReader r){}public virtual void write(PooledBinaryWriter w){}public virtual void ProcessPackage(World w,GameManager g){}public bool ValidEntityIdForSender(int id)=>Sender!=null&&Sender.entityId==id;}
class NetPackageManager{public static T GetPackage<T>() where T:new()=>new T();}
public class NetPackageQuestEvent:NetPackage{public enum QuestEventTypes{LockPOI,Other}public QuestEventTypes eventType;}
class RebirthPurgeReleasePolicy{public static bool Enabled=true;}
class RebirthSandboxOptionManager{public static RebirthSandboxOptionManager Current=new RebirthSandboxOptionManager();public bool PoiClearTrackingEnabled=true;}
class GameUtils{public static int WorldTimeToHours(ulong t)=>(int)t;}
class Localization{public static string Get(string key)=>key;}
class Log{public static void Warning(string text){}}
namespace Twitch{class TwitchManager{public static bool HasInstance;public static TwitchManager Current=new TwitchManager();public bool IsVoting;}}
class QuestEventManager{public enum POILockoutReasonTypes{None,QuestLock}public static QuestEventManager Current=new QuestEventManager();public POILockoutReasonTypes Reason;public POILockoutReasonTypes CheckForPOILockouts(int p,UnityEngine.Vector2 v,out ulong x){x=0;return Reason;}}
class RebirthPoiServerQuestRequirements{public static bool Allowed=true;public static bool TryCheck(Quest q,EntityPlayer p,out bool satisfied){satisfied=Allowed;return true;}}
class RebirthPoiLocalRallyOwner{public static int Starts;public static Action<RebirthPoiRallyCompletionReceipt> Completed;public static Action<bool> Failed;public static bool TryStartAuthenticated(RebirthPoiAuthenticatedRallyScope scope,Action<RebirthPoiRallyCompletionReceipt> completed,Action<bool> failed){Starts++;Completed=completed;Failed=failed;return true;}}
static class Program {
static int checks;static void Check(bool ok,string text){if(!ok)throw new Exception(text);checks++;Console.WriteLine("PASS "+text);}static RebirthPoiRallyWireFrame Frame(NetPackage p){byte[] bytes=(byte[])p.GetType().GetField("bytes",System.Reflection.BindingFlags.NonPublic|System.Reflection.BindingFlags.Instance).GetValue(p);RebirthPoiRallyWireFrame.TryDecode(bytes,out var f);return f;}
sealed class Fixture{public World World;public ConnectionManager Connection;public Quest Quest;public ObjectiveRallyPoint Objective;public ClientInfo Sender;public UnityEngine.Vector3 Poi=new UnityEngine.Vector3(10,2,30);public Guid Saved;public Fixture(bool server){RebirthPoiRemoteRallyOwner.Reset();RebirthPoiLocalRallyOwner.Starts=0;RebirthPoiServerQuestRequirements.Allowed=true;QuestEventManager.Current.Reason=QuestEventManager.POILockoutReasonTypes.None;Twitch.TwitchManager.HasInstance=false;World=new World{Remote=!server};World.Player=new EntityPlayerLocal{world=World};GameManager.Instance=new GameManager{World=World};Connection=new ConnectionManager{IsServer=server};SingletonMonoBehaviour<ConnectionManager>.Instance=Connection;Saved=server?Guid.Parse(World.worldState.Guid):Guid.NewGuid();GamePrefs.Guid=Saved.ToString("N").ToUpperInvariant();GameIO.Save=System.IO.Path.Combine(System.IO.Path.GetTempPath(),"rebirth-remote-fixture");var journal=new QuestJournal{OwnerPlayer=server?null:World.Player};World.Player.QuestJournal=journal;Quest=new Quest{OwnerJournal=journal};journal.quests.Add(Quest);Quest.PositionData.Add(Quest.PositionDataTypes.POIPosition,Poi);Objective=new ObjectiveRallyPoint{OwnerQuest=Quest};Quest.Objectives.Add(Objective);Sender=new ClientInfo{latestPlayerData=new PlayerDataFile{questJournal=journal}};Connection.Clients.Sender=Sender;}public RebirthPoiRallyWireFrame Request()=>new RebirthPoiRallyWireFrame(Guid.NewGuid(),Saved,1,Quest.ID,Quest.QuestUniqueId,Quest.QuestCode,Quest.CurrentPhase,Poi);}
static void Main(){
var f=new Fixture(false);Check(RebirthPoiRemoteRallyOwner.TryStart(f.Objective,f.Poi)&&f.Connection.Sent.Count==1&&f.Objective.Party==0&&f.Quest.PartyPruned==0&&!f.Quest.RallyMarkerActivated,"client sends original request without native party or quest success effects");var request=Frame(f.Connection.Sent[0]);RebirthPoiRemoteRallyOwner.ReceiveReply(f.World,new RebirthPoiRallyWireFrame(Guid.NewGuid(),request.World,1,request.QuestId,request.Unique,request.QuestCode,request.Phase,request.Poi,RebirthPoiRallyWireStatus.Completed,4));Check(f.Objective.Party==0,"foreign completion cannot activate pending client quest");RebirthPoiRemoteRallyOwner.ReceiveReply(f.World,request.Reply(RebirthPoiRallyWireStatus.Completed,4));Check(f.Objective.Party==1&&f.Quest.PartyPruned==1&&f.Quest.RallyMarkerActivated,"correlated server completion applies exact original client effects once");RebirthPoiRemoteRallyOwner.ReceiveReply(f.World,request.Reply(RebirthPoiRallyWireStatus.Completed,4));Check(f.Objective.Party==1&&f.Quest.PartyPruned==1,"duplicate reply cannot replay client success");
f=new Fixture(false);RebirthPoiRemoteRallyOwner.TryStart(f.Objective,f.Poi);request=Frame(f.Connection.Sent[0]);RebirthPoiRemoteRallyOwner.ReceiveReply(f.World,request.Reply(RebirthPoiRallyWireStatus.Refused));Check(f.Objective.Party==0&&f.Quest.PartyPruned==0&&!f.Quest.RallyMarkerActivated,"correlated refusal preserves original client state");RebirthPoiRemoteRallyOwner.ReceiveReply(f.World,request.Reply(RebirthPoiRallyWireStatus.Completed,4));Check(f.Objective.Party==0,"late success cannot revive a refused client request");
f=new Fixture(false);RebirthPoiRemoteRallyOwner.TryStart(f.Objective,f.Poi);request=Frame(f.Connection.Sent[0]);f.Quest.QuestUniqueId="replacement";RebirthPoiRemoteRallyOwner.ReceiveReply(f.World,request.Reply(RebirthPoiRallyWireStatus.Completed,4));Check(f.Objective.Party==0,"replacement client quest invalidates late server success");
f=new Fixture(true);request=f.Request();RebirthPoiRemoteRallyOwner.ReceiveRequest(f.World,f.Sender,request);Check(RebirthPoiLocalRallyOwner.Starts==1&&f.Sender.Sent.Count==0,"authenticated eligible server request delegates once to shared reset owner and withholds reply");RebirthPoiRemoteRallyOwner.ReceiveRequest(f.World,f.Sender,request);Check(RebirthPoiLocalRallyOwner.Starts==1,"pending duplicate request cannot start another native reset");RebirthPoiLocalRallyOwner.Completed(new RebirthPoiRallyCompletionReceipt(request.Request,request.World,request.Unique,request.QuestCode,1,4));Check(f.Sender.Sent.Count==1&&Frame(f.Sender.Sent[0]).Status==RebirthPoiRallyWireStatus.Completed&&Frame(f.Sender.Sent[0]).Revision==4,"original completion callback sends scoped durable revision");
f=new Fixture(true);request=f.Request();RebirthPoiRemoteRallyOwner.ReceiveRequest(f.World,new ClientInfo{latestPlayerData=f.Sender.latestPlayerData},request);Check(RebirthPoiLocalRallyOwner.Starts==0,"unregistered sender reference cannot start server reset");
f=new Fixture(true);request=f.Request();RebirthPoiServerQuestRequirements.Allowed=false;RebirthPoiRemoteRallyOwner.ReceiveRequest(f.World,f.Sender,request);Check(RebirthPoiLocalRallyOwner.Starts==0&&Frame(f.Sender.Sent[0]).Status==RebirthPoiRallyWireStatus.Refused,"server requirement failure rejects before native reset owner");
f=new Fixture(true);request=f.Request();QuestEventManager.Current.Reason=QuestEventManager.POILockoutReasonTypes.QuestLock;RebirthPoiRemoteRallyOwner.ReceiveRequest(f.World,f.Sender,request);Check(RebirthPoiLocalRallyOwner.Starts==0,"native server lockout prevents remote reset");
f=new Fixture(true);request=f.Request();f.Objective.startTime=20;f.Objective.endTime=6;RebirthPoiRemoteRallyOwner.ReceiveRequest(f.World,f.Sender,request);Check(RebirthPoiLocalRallyOwner.Starts==0,"native server time window prevents remote reset");
f=new Fixture(true);request=f.Request();RebirthPoiRemoteRallyOwner.ReceiveRequest(f.World,f.Sender,request);RebirthPoiLocalRallyOwner.Failed(true);Check(Frame(f.Sender.Sent[0]).Status==RebirthPoiRallyWireStatus.Unknown,"uncertain world reset cannot produce success reply");
Console.WriteLine("RESULT "+checks+" PASS; production remote owner/packages/wire/original-authenticated scopes; native connection, eligibility helper and shared reset execution are doubles.");}}