$ErrorActionPreference='Stop'
$root=(Resolve-Path "$PSScriptRoot/../..").Path
$run=Join-Path $PSScriptRoot ([Guid]::NewGuid().ToString('N'));[IO.Directory]::CreateDirectory($run)|Out-Null
$sourceDir=Join-Path $run 'src';[IO.Directory]::CreateDirectory($sourceDir)|Out-Null
$items=(Get-Content "$root/Tools/StationMixedPublicationIntegrationReview/actual_compile_items.json" -Raw|ConvertFrom-Json).Items.Compile
$replacements=@{
 'Scripts\Survivor\Domain\RebirthSurvivorRuntimeModels.cs'='Tools/StationMixedPersistenceCandidate/production_candidates/RebirthSurvivorRuntimeModels.candidate.cs.txt'
 'Scripts\Survivor\Persistence\RebirthWorldCharacterRepository.cs'='Tools/StationMixedPersistenceCandidate/production_candidates/RebirthWorldCharacterRepository.candidate.cs.txt'
}
$extra=@('Tools/StationOrdinaryAdditionProducerFixture/NativePaidOrdinaryRouteLink.cs','Tools/StationOrdinaryAdditionProducerFixture/NativePaidOrdinaryChainCodec.cs','Tools/StationOrdinaryAdditionProducerFixture/NativePaidOrdinaryExitCandidate.cs','Tools/StationOrdinaryAdditionProducerFixture/PaidExitNativeSpans.candidate.txt','Tools/StationOrdinaryAdditionProducerFixture/OrdinaryNativeCallsiteCandidate.cs','Tools/StationOrdinaryAdditionProducerFixture/OrdinaryNativeTransformCandidate.cs','Tools/StationOrdinaryAdditionProducerFixture/OrdinaryAdditionProducer.cs','Tools/StationOrdinaryAdditionProducerFixture/PaidCompletionExporterClone.candidate.txt','Tools/StationMixedPublicationIntegrationReview/MixedExpectationCandidate.cs','Tools/StationMixedPublicationIntegrationReview/MixedExitExpectationCandidate.cs','Tools/StationMixedPublicationIntegrationReview/MixedProjectionCandidate.cs','Tools/StationMixedPersistenceCandidate/MixedCompletionRecord.cs','Tools/StationMixedPersistenceCandidate/MixedLiveRecordCandidate.cs','Tools/StationMixedPersistenceCandidate/MixedNativePublicationCandidate.cs','Tools/StationMixedPersistenceCandidate/MixedAtomicPublicationCandidate.cs','Tools/SecondTeam/StationMixedSnapshotWatchCandidate/Contracts.cs','Tools/SecondTeam/StationMixedSnapshotWatchCandidate/TypedMixedWatchExpectation.cs','Tools/SecondTeam/StationMixedSnapshotWatchCandidate/StationMixedSnapshotWatchCandidate.cs')
$manifest=@();$compile=@();$i=0
foreach($item in $items){$original=$item.FullPath;$chosen=$original;if($replacements.ContainsKey($item.Identity)){$chosen=Join-Path $root $replacements[$item.Identity]};$hash=(Get-FileHash $chosen).Hash;$target=Join-Path $sourceDir ((++$i).ToString('D4')+'_'+[IO.Path]::GetFileNameWithoutExtension($chosen)+'.cs');Copy-Item -LiteralPath $chosen -Destination $target;if((Get-FileHash $chosen).Hash-ne$hash){throw 'source drift'};$compile+=$target;$manifest+=@{Original=$original;OriginalHash=(Get-FileHash $original).Hash;Chosen=$chosen;Hash=$hash;Copy=$target}}
foreach($relative in $extra){$chosen=Join-Path $root $relative;$hash=(Get-FileHash $chosen).Hash;$target=Join-Path $sourceDir ((++$i).ToString('D4')+'_'+[IO.Path]::GetFileNameWithoutExtension($chosen)+'.cs');Copy-Item -LiteralPath $chosen -Destination $target;if((Get-FileHash $chosen).Hash-ne$hash){throw 'candidate drift'};$compile+=$target;$manifest+=@{Chosen=$chosen;Hash=$hash;Copy=$target}}
[xml]$project=Get-Content "$root/RebirthUtils.csproj" -Raw
foreach($n in @($project.SelectNodes('//Compile|//EmbeddedResource|//None|//Content'))){[void]$n.ParentNode.RemoveChild($n)}
foreach($n in @($project.Project.Target|Where-Object {$_.Name-eq'RunRebirthProfilerInstrumentation'})){[void]$n.ParentNode.RemoveChild($n)}
$native='C:/Program Files (x86)/Steam/steamapps/common/7 Days To Die/7DaysToDie_Data/Managed'
foreach($n in $project.SelectNodes('//HintPath')){$p=$n.InnerText.Replace('$(RebirthManagedRoot)',$native);if(!$p.Contains('$(')-and ![IO.Path]::IsPathRooted($p)){$p=[IO.Path]::GetFullPath((Join-Path $root $p))};if($p.Contains('$(')-or !(Test-Path -LiteralPath $p)){throw "unresolved reference $p"};$n.InnerText=$p}
foreach($name in @('OutDir','OutputPath','BaseOutputPath','IntermediateOutputPath','BaseIntermediateOutputPath','MSBuildProjectExtensionsPath')){foreach($n in @($project.SelectNodes("//$name"))){$n.InnerText=if($name -match 'Intermediate|Extensions'){"$run/obj/"}else{"$run/bin/"}}}
$pg=$project.CreateElement('PropertyGroup');foreach($pair in @{EnableDefaultCompileItems='false';EnableDefaultEmbeddedResourceItems='false';EnableDefaultNoneItems='false';RebirthGameRoot='C:/Program Files (x86)/Steam/steamapps/common/7 Days To Die';RebirthManagedRoot=$native;OutDir="$run/bin/";OutputPath="$run/bin/";BaseOutputPath="$run/bin/";IntermediateOutputPath="$run/obj/";BaseIntermediateOutputPath="$run/obj/";RebirthProfilerEnableInstrumentation='false'}.GetEnumerator()){$n=$project.CreateElement($pair.Key);$n.InnerText=$pair.Value;[void]$pg.AppendChild($n)};[void]$project.Project.AppendChild($pg)
$ig=$project.CreateElement('ItemGroup');foreach($path in $compile){$n=$project.CreateElement('Compile');$n.SetAttribute('Include',$path);[void]$ig.AppendChild($n)};[void]$project.Project.AppendChild($ig)
$projectPath=Join-Path $run 'StationFullSource.csproj';$project.Save($projectPath)
[IO.File]::WriteAllText((Join-Path $run 'Directory.Build.props'),"<Project><PropertyGroup><BaseIntermediateOutputPath>$run/obj/</BaseIntermediateOutputPath><MSBuildProjectExtensionsPath>$run/obj/</MSBuildProjectExtensionsPath></PropertyGroup></Project>")
@{RootDll=(Get-FileHash "$root/RebirthUtils.dll").Hash;Project=$projectPath;SourceCount=$compile.Count;Sources=$manifest}|ConvertTo-Json -Depth 7|Set-Content (Join-Path $run 'manifest.json')
$projectPath|Set-Content (Join-Path $PSScriptRoot 'LATEST_PROJECT.txt');Write-Output $projectPath
