class Program {static int n;static void A(bool ok,string m){if(!ok)throw new Exception(m);n++;}static void Main(){GameIO.Root=Path.Combine(Path.GetTempPath(),"rebirth-late-upload-"+Guid.NewGuid().ToString("N"));Directory.CreateDirectory(GameIO.Root);var player=new EntityPlayerLocal();var world=new World{Player=player};player.world=world;var game=new GameManager{World=world};GameManager.Instance=game;var connection=new Conn();SingletonMonoBehaviour<ConnectionManager>.Instance=new(){connectionToServer=new[]{connection}};RebirthGearOwnerReservation.Session=connection;player.Buffs.CVars["rbGear_tx"]=1;player.Buffs.CVars["_rbgearintent_original"]=1;var sender=new ClientInfo();var owner=new RebirthStablePlayerIdentity();var offer=new RebirthGearTransferState();
 void Upload(int count,bool marker=true,int id=1){new NetPackagePlayerData{Sender=sender,playerDataFile=new(){Count=count,Receipt=count==0?2:1,Marker=marker,id=id}}.ProcessPackage(world,game);}
 A(!RebirthGearPlayerFileWitness.HasApplied(owner,offer),"applied request before scheduled upload cannot confirm");Upload(1);A(RebirthGearPlayerFileWitness.HasApplied(owner,offer),"native upload actual full-file witness applied");A(RebirthGearOwnerReservation.Held,"owner hold remains after upload");Upload(0);A(!RebirthGearPlayerFileWitness.HasApplied(owner,offer),"late beforeimage erases pending applied proof");A(!RebirthGearTerminalOwnerCheckpoint.TryPersist(player,connection,offer),"actual terminal refuses stale file despite live postimage");A(RebirthGearOwnerReservation.Held,"failure retains original hold");
 Upload(1);A(RebirthGearTerminalOwnerCheckpoint.TryPersist(player,connection,offer),"actual terminal retirement persists marker absence");A(!player.Buffs.CVars.ContainsKey("_rbgearintent_original"),"original marker removed");A(RebirthGearPlayerFileWitness.HasRetired(owner,offer,true),"actual retired final witness");A(RebirthGearOwnerReservation.Held,"checkpoint never releases hold itself");Upload(0);A(!RebirthGearPlayerFileWitness.HasRetired(owner,offer,true),"late postterminal native file can resurrect old image");A(!RebirthGearTerminalOwnerCheckpoint.HasSavedRetirement(player,offer,true),"cached terminal alone not release proof");
 Upload(1,false);A(RebirthGearTerminalOwnerCheckpoint.TryPersist(player,connection,offer),"exact retry retired file no item write");A(player.bag.ItemGrid.items[0].Count==1,"no inventory replay");Upload(0,true,99);A(RebirthGearPlayerFileWitness.HasRetired(owner,offer,true),"native packet wrong sender entity rejected");
 SdFile.FailFinal=true;int events=ModEvents.SavePlayerData.Count;Upload(0);A(Log.Errors>0,"native Save swallowed final copy failure");A(ModEvents.SavePlayerData.Count==events+1,"SavePlayerData event still fires after failed native Save");A(sender.latestPlayerData.Count==0,"latest packet not final witness");A(RebirthGearPlayerFileWitness.HasRetired(owner,offer,true),"final file remains authoritative despite latest stale packet");SdFile.FailFinal=false;
 connection.Disconnected=true;A(!RebirthGearTerminalOwnerCheckpoint.TryPersist(player,connection,offer),"disconnect denies actual terminal");connection.Disconnected=false;var replacement=new Conn();SingletonMonoBehaviour<ConnectionManager>.Instance.connectionToServer[0]=replacement;A(!RebirthGearTerminalOwnerCheckpoint.TryPersist(player,connection,offer),"reconnect new connection rejects original session");
 // Real native save accepts future valid updates after retirement; witness does not grant replay.
 Upload(2,false);A(!RebirthGearPlayerFileWitness.HasRetired(owner,offer,true),"later valid changed inventory no longer old postimage");A(sender.latestPlayerData.Count==2,"future normal inventory accepted by native save");
 Console.WriteLine("PASS "+n+": extracted actual native ProcessPackage/SavePlayerData/Save; linked actual GearPlayerFileWitness/TerminalOwnerCheckpoint. IO real temporary files; transport, plan, receipt and native final-file loader adapters explicit. No production authority activation.");}}


