public class World{public EntityPlayerLocal Player;public bool Remote=true;public bool IsRemote()=>Remote;public EntityPlayerLocal GetPrimaryPlayer()=>Player;public object GetEntity(int id)=>Player?.entityId==id?Player:null;}
public class EntityPlayer{public int entityId=7;}
public class EntityPlayerLocal:EntityPlayer{public FakeBuffs Buffs=new FakeBuffs();public FakeInventory bag=new FakeInventory(),inventory=new FakeInventory();public World world;public bool Dead;public bool IsSpawned()=>true;public bool IsDead()=>Dead;}
class GameManager{public static GameManager Instance=new GameManager();public World World;public int Uploads;public void TriggerSendOfLocalPlayerDataFile(float delay){Uploads++;}}
class Connection{public bool Disconnected;public bool IsDisconnected()=>Disconnected;}
class ConnectionManager{public int RejectedRequests;public NetPackageRebirthGearRejectedRequest LastRejected;public void SendToServer(NetPackageRebirthGearRejectedRequest packet){RejectedRequests++;LastRejected=packet;}public int Requests;public NetPackageRebirthGearAppliedRequest LastRequest;public void SendToServer(NetPackageRebirthGearAppliedRequest packet){Requests++;LastRequest=packet;}public int Sent;public System.Action OnSend;public System.Collections.Generic.List<RebirthGearOfferFragment> Fragments=new System.Collections.Generic.List<RebirthGearOfferFragment>();public void SendPackage(NetPackageRebirthGearOfferFragment packet,int _attachedToEntityId){Sent++;Fragments.Add(packet.Fragment);OnSend?.Invoke();}public bool IsServer;public Connection[] connectionToServer=new[]{new Connection()};}
class SingletonMonoBehaviour<T>{public static T Instance;}
static class RebirthSurvivorMode{public static bool IsEnabledForCurrentWorld()=>true;}
static class RebirthSurvivorClientState{public static string Creation;public static string GetProjectedCreationId(EntityPlayerLocal player)=>Creation;}public class ClientInfo{}
class GearSupport{public RebirthGearTransferState PendingGearTransfer;public RebirthGearTransferPhase GearTransferPhase;}
class GearRecord{public GearSupport Support=new GearSupport();}
static class RebirthWorldCharacterRepository{public static bool IsCurrentCachedRecord(GearRecord record)=>ReferenceEquals(record,RebirthRemoteGearInventorySource.Record);}
static class RebirthRemoteGearInventorySource{public static GearRecord Record=new GearRecord();public static bool TryResolve(EntityPlayer player,ClientInfo sender,string creation,out GearRecord record){record=Record;return record!=null;}}
static class RebirthRemoteGearPreparation{public static bool TryReplayBoundRetained(EntityPlayer p,ClientInfo s,string marker,out RebirthGearTransferState o,out RebirthGearTransferPhase phase){phase=RebirthRemoteGearInventorySource.Record.Support.GearTransferPhase;return TryReplayBound(p,s,marker,out o);}public static bool TryReplayBound(EntityPlayer p,ClientInfo s,string marker,out RebirthGearTransferState o)=>TryReplay(p,s,marker,out o);public static bool Saved=true;public static bool TryReplay(EntityPlayer player,ClientInfo sender,string creation,out RebirthGearTransferState offer){offer=RebirthRemoteGearInventorySource.Record?.Support.PendingGearTransfer;return Saved&&offer!=null;}}
class NetPackageRebirthGearOfferFragment{public RebirthGearOfferFragment Fragment;public NetPackageRebirthGearOfferFragment Setup(int id,RebirthGearOfferFragment fragment){Fragment=fragment;return this;}}
static class NetPackageManager{public static bool Missing;public static int GetPackageId(System.Type type){if(Missing)throw new System.Exception("mapping");return 1;}public static T GetPackage<T>()where T:new()=>new T();}public static class RebirthGearOwnerApplySequence{public enum Result{Applied,Conflict,Pending,NeedsReconciliation}}
static class RebirthGearOwnerReservation{public static bool ReleaseSettledWithTransport(EntityPlayerLocal p,object c,RebirthGearTransferState o,System.Func<bool> v,System.Func<bool> f){if(!Allowed||!v()||!f())return false;Releases++;return true;}public static int Releases;public static bool ReleaseSettled(EntityPlayerLocal player,object connection,RebirthGearTransferState offer,System.Func<bool> verify){if(!Allowed||!verify())return false;Releases++;return true;}public static bool Allowed=true;public static bool Matches(EntityPlayerLocal player,object connection,RebirthGearTransferState offer)=>Allowed;public static int Acquires;public static bool TryAcquire(EntityPlayerLocal player,object connection,RebirthGearTransferState offer){Acquires++;return Allowed;}}
static class RebirthGearOwnerInventoryAdapter{public static int Applies;public static System.Action OnApply;public static RebirthGearOwnerApplySequence.Result Apply(EntityPlayerLocal player,RebirthGearTransferState offer,object connection,System.Func<bool> current){Applies++;OnApply?.Invoke();return current()?RebirthGearOwnerApplySequence.Result.Applied:RebirthGearOwnerApplySequence.Result.NeedsReconciliation;}}
public class FakeBuffs{public float Receipt=1f;public float GetCustomVar(string key)=>Receipt;}
public class FakeInventory{public FakeGrid ItemGrid=new FakeGrid();}public class FakeGrid{public object items;}
class NetPackagePlayerData{}
public enum RebirthGearOwnerReceipt{Applied=1,Rejected=-1}
static class RebirthGearOwnerSaveCheckpoint{public static bool Saved=true;public static System.Action OnSave;public static bool TryPersist(EntityPlayerLocal player,RebirthGearTransferState offer,RebirthGearOwnerReceipt stage,System.Func<bool> current){OnSave?.Invoke();if(Saved&&current()&&stage==RebirthGearOwnerReceipt.Rejected)player.Buffs.Receipt=-1f;return Saved&&current();}}
class RebirthGearInventorySnapshot{public RebirthGearInventoryPlan.Stack[] Bag,Belt;public static bool Valid=true;public static bool TryCapture(object bag,object belt,int slots,out RebirthGearInventorySnapshot snapshot){snapshot=new RebirthGearInventorySnapshot{Bag=new RebirthGearInventoryPlan.Stack[65],Belt=new RebirthGearInventoryPlan.Stack[4]};for(int i=0;i<snapshot.Bag.Length;i++)snapshot.Bag[i]=new RebirthGearInventoryPlan.Stack();for(int i=0;i<snapshot.Belt.Length;i++)snapshot.Belt[i]=new RebirthGearInventoryPlan.Stack();return Valid;}}
public class RebirthGearSettlement{public string TransactionId,CreationId,PreparationRequestDigest;public long GearRevision;public bool Applied;public System.Xml.Linq.XElement Write()=>new("terminal");}
static class RebirthRemoteGearAppliedConfirmation{public static bool TryGetBoundTerminalOriginal(EntityPlayer p,ClientInfo s,string m,out RebirthGearTransferState o,out RebirthGearSettlement t){o=RebirthRemoteGearInventorySource.Record?.Support.PendingGearTransfer;t=new();return Confirmed&&o!=null;}public static bool Confirmed=true,Committed=true;public static int Commits;public static System.Action OnConfirm;public static bool TryFinishRecovery(EntityPlayer player,ClientInfo sender,string creation,string transfer)=>false;public static bool TryConfirm(EntityPlayer player,ClientInfo sender,string creation,string transfer){OnConfirm?.Invoke();return Confirmed;}public static bool TryCommit(EntityPlayer player,ClientInfo sender,string creation,string transfer){Commits++;return Committed;}}
class NetPackageRebirthGearAppliedRequest{public int PlayerId;public string Creation;public System.Guid Transaction;public NetPackageRebirthGearAppliedRequest Setup(int id,string creation,System.Guid transaction){PlayerId=id;Creation=creation;Transaction=transaction;return this;}}

class NetPackageRebirthGearRejectedRequest{public int PlayerId;public string Creation;public System.Guid Transaction;public NetPackageRebirthGearRejectedRequest Setup(int id,string creation,System.Guid transaction){PlayerId=id;Creation=creation;Transaction=transaction;return this;}}

static class RebirthGearRecoveryDispatcher{public static bool TryAdvance(EntityPlayer player,ClientInfo sender,string creation,string transfer)=>false;}

static class RebirthGearTerminalClient {public static RebirthGearSettlement Cached;public static bool TryGetCurrent(EntityPlayerLocal p,out string m,out RebirthGearSettlement t){m="original";t=Cached;return t!=null;} public static void Reset() {Cached=null;} }

static class RebirthGearTerminalOwnerCheckpoint {public static bool Saved;public static bool HasSavedRetirement(EntityPlayerLocal p,RebirthGearTransferState o,bool a)=>Saved;public static bool TryPersist(EntityPlayerLocal p,object s,RebirthGearTransferState o)=>Saved;}
