using System;using System.Linq;using System.Text;
class Program{
 static int checks;static void Check(bool ok,string label){if(!ok)throw new Exception(label);checks++;}
 static void Main(){var creation=Guid.NewGuid().ToString("N");var tx=Guid.NewGuid();string payload=Convert.ToBase64String(new byte[20000]);
 var plan=new RebirthGearInventoryPlan{BagSlotsBefore=52,BagSlotsAfter=65,BeltSlotsBefore=4,BeltSlotsAfter=4,GearAfter=new RebirthGearInventoryPlan.Stack{ItemData=payload,Count=1}};
 plan.Changes.Add(new RebirthGearInventoryPlan.Change{IsBag=true,Index=0,Before=new RebirthGearInventoryPlan.Stack{ItemData=payload,Count=1}});
 Check(RebirthGearTransferState.TryCreate(tx.ToString("N"),creation,"backpack",5,plan,out var offer),"real offer creation");
 Check(offer.TryBindPreparationRequest(new string('a',64),out var boundOffer)&&RebirthGearOfferWireCodec.TryEncode(boundOffer,out var boundBytes)&&RebirthGearOfferWireCodec.TryDecode(boundBytes,out var boundDecoded)&&boundDecoded.PreparationRequestDigest==new string('a',64),"bound original digest survives actual wire codec");
 Check(RebirthGearOfferWireCodec.TryEncode(offer,out var bytes)&&RebirthGearOfferWireCodec.TryDecode(bytes,out var decoded)&&decoded.ToXml().ToString()==offer.ToXml().ToString(),"exact codec roundtrip");
 Func<long,string,RebirthGearOfferAssembly> assembly=(revision,hash)=>new RebirthGearOfferAssembly(creation,tx,revision,bytes.Length,hash);
 var digest=RebirthGearOfferAssembly.ComputeDigest(bytes);var a=assembly(5,digest);Check(!a.TryFinish(out _),"incomplete refusal");
 int count=(bytes.Length+RebirthGearOfferAssembly.ChunkBytes-1)/RebirthGearOfferAssembly.ChunkBytes;
 for(int i=count-1;i>=0;i--){var chunk=bytes.Skip(i*16384).Take(16384).ToArray();Check(a.TryAdd(i,chunk)&&a.TryAdd(i,chunk),"out-of-order identical duplicate");Array.Clear(chunk,0,chunk.Length);}
 Check(a.TryFinish(out var completed)&&completed.ExpectedRevision==5&&a.TryFinish(out _),"detached fragments and repeat finish");
 var conflict=assembly(5,digest);var first=bytes.Take(16384).ToArray();Check(conflict.TryAdd(0,first),"initial fragment");first[0]^=1;Check(!conflict.TryAdd(0,first)&&!conflict.TryFinish(out _),"contradiction invalidates assembly");
 foreach(var spec in new[]{assembly(6,digest),assembly(5,new string('0',64))}){for(int i=0;i<count;i++)spec.TryAdd(i,bytes.Skip(i*16384).Take(16384).ToArray());Check(!spec.TryFinish(out _),"revision or digest refusal");}
 Check(!RebirthGearOfferWireCodec.TryDecode(new byte[]{255},out _),"invalid utf8");Check(!RebirthGearOfferWireCodec.TryDecode(Encoding.UTF8.GetBytes("<!DOCTYPE x [<!ENTITY a 'b'>]><x>&a;</x>"),out _),"DTD refusal");
 Check(!RebirthGearOfferWireCodec.TryDecode(new byte[RebirthGearOfferWireCodec.MaxBytes+1],out _),"oversize refusal");
 var framed=assembly(5,digest);
 for(int i=0;i<count;i++){Check(RebirthGearOfferFragment.TryCreate(creation,tx,5,bytes.Length,digest,i,bytes.Skip(i*16384).Take(16384).ToArray(),out var f),"fragment create");var frame=f.Encode();Check(RebirthGearOfferFragment.TryDecode(frame,out var parsed)&&framed.TryAdd(parsed),"fragment wire assembly");Check(!RebirthGearOfferFragment.TryDecode(frame.Take(frame.Length-1).ToArray(),out _),"truncated fragment refusal");Check(!RebirthGearOfferFragment.TryDecode(frame.Concat(new byte[]{0}).ToArray(),out _),"trailing bytes refusal");}
 Check(framed.TryFinish(out _),"framed offer completes");
 RebirthGearOfferFragment.TryCreate(creation,Guid.NewGuid(),5,bytes.Length,digest,0,bytes.Take(16384).ToArray(),out var foreign);Check(!assembly(5,digest).TryAdd(foreign),"foreign transaction fragment refusal");
 var owner=new object();var world=new object();var session=new object();var inbox=new RebirthGearOfferInbox(owner,world,session,creation);
 RebirthGearOfferFragment.TryCreate(creation,tx,5,bytes.Length,digest,0,bytes.Take(16384).ToArray(),out var head);
 Check(!inbox.TryReceive(new object(),world,session,creation,1,head,out _),"foreign owner inbox refusal");
 Check(!inbox.TryReceive(owner,world,new object(),creation,1,head,out _),"foreign session inbox refusal");
 Check(!inbox.TryReceive(owner,world,session,creation,1,head,out _),"incomplete inbox not delivered");
 Check(!inbox.TryReceive(owner,world,session,creation,2,foreign,out _),"another transaction cannot evict inbox");
 int deliveries=0;for(int i=1;i<count;i++){RebirthGearOfferFragment.TryCreate(creation,tx,5,bytes.Length,digest,i,bytes.Skip(i*16384).Take(16384).ToArray(),out var f);if(inbox.TryReceive(owner,world,session,creation,3,f,out _))deliveries++;}
 Check(deliveries==1&&!inbox.TryReceive(owner,world,session,creation,100,head,out _),"complete offer delivered once despite timeout");
 Check(!inbox.TryReleaseSettled(owner,world,session,creation,tx,()=>false),"unsaved settlement retains inbox");
 Check(inbox.TryReleaseSettled(owner,world,session,creation,tx,()=>true),"verified settlement permits next inbox");
 var timed=new RebirthGearOfferInbox(owner,world,session,creation);timed.TryReceive(owner,world,session,creation,1,head,out _);Check(!timed.TryReceive(owner,world,session,creation,32,head,out _),"expired incomplete assembly restarts without delivery");
 var nativeWorld=new World();var nativePlayer=new EntityPlayerLocal{world=nativeWorld};nativeWorld.Player=nativePlayer;GameManager.Instance.World=nativeWorld;var manager=new ConnectionManager();SingletonMonoBehaviour<ConnectionManager>.Instance=manager;RebirthSurvivorClientState.Creation=creation;
 for(int i=0;i<count;i++){RebirthGearOfferFragment.TryCreate(creation,tx,5,bytes.Length,digest,i,bytes.Skip(i*16384).Take(16384).ToArray(),out var f);RebirthGearOfferClient.Receive(nativeWorld,7,f);}
 Check(RebirthGearOfferClient.TryGetCurrentOffer(nativeWorld,7,out var currentOffer)&&currentOffer.TransactionId==tx.ToString("N"),"native scoped receiver completes");
 RebirthGearOwnerReservation.Allowed=false;Check(RebirthGearOfferClient.TryApplyCurrentOffer(nativeWorld,7)==RebirthGearOwnerApplySequence.Result.Pending&&RebirthGearOwnerInventoryAdapter.Applies==0,"hold refusal prevents application");RebirthGearOwnerReservation.Allowed=true;
 Check(RebirthGearOfferClient.TryApplyCurrentOffer(nativeWorld,7)==RebirthGearOwnerApplySequence.Result.Applied&&RebirthGearOwnerInventoryAdapter.Applies==1,"current retained offer routes through held owner adapter");
 Check(RebirthGearOfferClient.RequestAppliedCheckpoint(nativeWorld,7)&&GameManager.Instance.Uploads==1,"saved applied owner schedules full upload");
 RebirthGearOwnerSaveCheckpoint.Saved=false;Check(!RebirthGearOfferClient.RequestAppliedCheckpoint(nativeWorld,7)&&GameManager.Instance.Uploads==1,"unsaved applied owner cannot upload");RebirthGearOwnerSaveCheckpoint.Saved=true;
 nativePlayer.Buffs.Receipt=2f;Check(!RebirthGearOfferClient.RequestAppliedCheckpoint(nativeWorld,7)&&GameManager.Instance.Uploads==1,"applying receipt cannot request applied upload");nativePlayer.Buffs.Receipt=1f;
 RebirthGearInventorySnapshot.Valid=false;Check(!RebirthGearOfferClient.RequestAppliedCheckpoint(nativeWorld,7)&&GameManager.Instance.Uploads==1,"invalid live inventory refuses upload");RebirthGearInventorySnapshot.Valid=true;
 NetPackageManager.Missing=true;Check(!RebirthGearOfferClient.RequestAppliedCheckpoint(nativeWorld,7)&&GameManager.Instance.Uploads==1,"missing player data mapping refuses upload");NetPackageManager.Missing=false;
 Check(RebirthGearOfferClient.RequestAppliedConfirmation(nativeWorld,7)&&manager.Requests==1&&manager.LastRequest.PlayerId==7&&manager.LastRequest.Creation==creation&&manager.LastRequest.Transaction==tx,"confirmation sends exact retained identity");
 RebirthGearOwnerSaveCheckpoint.Saved=false;Check(!RebirthGearOfferClient.RequestAppliedConfirmation(nativeWorld,7)&&manager.Requests==1,"failed checkpoint prevents confirmation send");RebirthGearOwnerSaveCheckpoint.Saved=true;
 var checkpointConnection=manager.connectionToServer[0];RebirthGearOwnerSaveCheckpoint.OnSave=()=>manager.connectionToServer[0]=new Connection();Check(!RebirthGearOfferClient.RequestAppliedConfirmation(nativeWorld,7)&&manager.Requests==1,"checkpoint session replacement prevents confirmation send");manager.connectionToServer[0]=checkpointConnection;RebirthGearOwnerSaveCheckpoint.OnSave=null;
 NetPackageManager.Missing=true;int uploadsBefore=GameManager.Instance.Uploads;Check(!RebirthGearOfferClient.RequestAppliedConfirmation(nativeWorld,7)&&manager.Requests==1&&GameManager.Instance.Uploads==uploadsBefore,"missing request mapping refuses before upload");NetPackageManager.Missing=false;
 nativePlayer.Buffs.Receipt=0f;Check(!RebirthGearOfferClient.RequestRejectedConfirmation(nativeWorld,7)&&manager.RejectedRequests==0,"no saved rejection cannot send confirmation");
 Check(RebirthGearOfferClient.TryRejectCurrentOffer(nativeWorld,7)&&nativePlayer.Buffs.Receipt==-1f&&RebirthGearOwnerReservation.Releases==0,"explicit rejection uses held saved checkpoint without release");
 Check(RebirthGearOfferClient.RequestRejectedConfirmation(nativeWorld,7)&&manager.RejectedRequests==1&&manager.LastRejected.PlayerId==7&&manager.LastRejected.Creation==creation&&manager.LastRejected.Transaction==tx&&RebirthGearOwnerReservation.Releases==0,"saved rejection schedules exact request but retains hold");
 RebirthGearOwnerSaveCheckpoint.Saved=false;int rejectedUploads=GameManager.Instance.Uploads;Check(!RebirthGearOfferClient.RequestRejectedConfirmation(nativeWorld,7)&&manager.RejectedRequests==1&&GameManager.Instance.Uploads==rejectedUploads,"failed rejected save cannot upload or send");RebirthGearOwnerSaveCheckpoint.Saved=true;
 NetPackageManager.Missing=true;Check(!RebirthGearOfferClient.RequestRejectedConfirmation(nativeWorld,7)&&manager.RejectedRequests==1&&GameManager.Instance.Uploads==rejectedUploads,"missing rejected mapping refuses before upload");NetPackageManager.Missing=false;
 var rejectConnection=manager.connectionToServer[0];RebirthGearOwnerSaveCheckpoint.OnSave=()=>manager.connectionToServer[0]=new Connection();Check(!RebirthGearOfferClient.RequestRejectedConfirmation(nativeWorld,7)&&manager.RejectedRequests==1,"rejected scope changed while saving refuses send");manager.connectionToServer[0]=rejectConnection;RebirthGearOwnerSaveCheckpoint.OnSave=null;
 nativePlayer.Buffs.Receipt=1f; var savedConnection=manager.connectionToServer[0];RebirthGearOwnerInventoryAdapter.OnApply=()=>manager.connectionToServer[0]=new Connection();Check(RebirthGearOfferClient.TryApplyCurrentOffer(nativeWorld,7)==RebirthGearOwnerApplySequence.Result.NeedsReconciliation,"connection replacement during adapter refused");manager.connectionToServer[0]=savedConnection;RebirthGearOwnerInventoryAdapter.OnApply=null;
 Check(!RebirthGearOfferClient.TryGetCurrentOffer(nativeWorld,8,out _),"foreign recipient refused");nativePlayer.Dead=true;Check(!RebirthGearOfferClient.TryGetCurrentOffer(nativeWorld,7,out _),"dead owner refused");nativePlayer.Dead=false;
 manager.connectionToServer[0]=new Connection();Check(!RebirthGearOfferClient.TryGetCurrentOffer(nativeWorld,7,out _),"replacement connection refused");
 manager.connectionToServer[0]=savedConnection;
 Check(!RebirthGearOfferClient.ReceiveSettlement(nativeWorld,7,creation,tx,7,true)&&RebirthGearOwnerReservation.Releases==0,"wrong terminal revision retains hold");
 Check(!RebirthGearOfferClient.ReceiveSettlement(nativeWorld,7,creation,Guid.NewGuid(),6,true)&&RebirthGearOwnerReservation.Releases==0,"foreign terminal transaction retains hold");
 nativePlayer.Buffs.Receipt=2f;Check(!RebirthGearOfferClient.ReceiveSettlement(nativeWorld,7,creation,tx,6,true)&&RebirthGearOwnerReservation.Releases==0,"unfinished local receipt retains hold");nativePlayer.Buffs.Receipt=1f;
 Check(RebirthGearOfferClient.ReceiveSettlement(nativeWorld,7,creation,tx,6,true)&&RebirthGearOwnerReservation.Releases==1&&!RebirthGearOfferClient.TryGetCurrentOffer(nativeWorld,7,out _),"matching terminal releases hold and transport");
 Check(!RebirthGearOfferClient.ReceiveSettlement(nativeWorld,7,creation,tx,6,true)&&RebirthGearOwnerReservation.Releases==1,"duplicate terminal cannot repeat release");
 RebirthGearOfferClient.Reset();var rejectedTx=Guid.NewGuid();RebirthGearTransferState.TryCreate(rejectedTx.ToString("N"),creation,"backpack",5,plan,out var rejectedOffer);RebirthGearOfferWireCodec.TryEncode(rejectedOffer,out var rejectedBytes);var rejectedDigest=RebirthGearOfferAssembly.ComputeDigest(rejectedBytes);
 for(int i=0;i<(rejectedBytes.Length+16383)/16384;i++){RebirthGearOfferFragment.TryCreate(creation,rejectedTx,5,rejectedBytes.Length,rejectedDigest,i,rejectedBytes.Skip(i*16384).Take(16384).ToArray(),out var f);RebirthGearOfferClient.Receive(nativeWorld,7,f);}
 nativePlayer.Buffs.Receipt=-1f;
 Check(!RebirthGearOfferClient.ReceiveSettlement(nativeWorld,7,creation,rejectedTx,6,true)&&RebirthGearOwnerReservation.Releases==1,"rejected local receipt refuses applied reply");
 Check(RebirthGearOfferClient.ReceiveSettlement(nativeWorld,7,creation,rejectedTx,6,false)&&RebirthGearOwnerReservation.Releases==2&&!RebirthGearOfferClient.TryGetCurrentOffer(nativeWorld,7,out _),"original rejected terminal releases hold and inbox once");
 Check(!RebirthGearOfferClient.ReceiveSettlement(nativeWorld,7,creation,rejectedTx,6,false)&&RebirthGearOwnerReservation.Releases==2,"duplicate rejected terminal cannot release twice");
 nativePlayer.Buffs.Receipt=1f; RebirthGearOfferClient.Reset();Check(!RebirthGearOfferClient.TryGetCurrentOffer(nativeWorld,7,out _),"reset drops transport only");
 RebirthGearOfferWireCodec.TryEncode(boundOffer,out var earlyBoundBytes);
 RebirthGearOfferClient.Reset();manager.IsServer=false;nativePlayer.Buffs.Receipt=1f;
 RebirthGearTerminalClient.Cached=new(){CreationId=boundOffer.CreationId,TransactionId=boundOffer.TransactionId,GearRevision=boundOffer.ExpectedRevision+1,PreparationRequestDigest=boundOffer.PreparationRequestDigest,Applied=true};
 int earlyReleases=RebirthGearOwnerReservation.Releases,earlyApplies=RebirthGearOwnerInventoryAdapter.Applies;
 Check(!RebirthGearOfferClient.TryFinishCurrentTerminal(nativeWorld,7)&&RebirthGearTerminalClient.Cached!=null,"early terminal stays cached until exact plan available");
 for(int i=0;i<(earlyBoundBytes.Length+16383)/16384;i++){RebirthGearOfferFragment.TryCreate(creation,tx,5,earlyBoundBytes.Length,RebirthGearOfferAssembly.ComputeDigest(earlyBoundBytes),i,earlyBoundBytes.Skip(i*16384).Take(16384).ToArray(),out var f);RebirthGearOfferClient.Receive(nativeWorld,7,f);}
 Check(RebirthGearTerminalClient.Cached!=null&&RebirthGearOfferClient.TryGetCurrentOffer(nativeWorld,7,out _)&&RebirthGearOwnerReservation.Releases==earlyReleases,"assembling original preserves early terminal and uncertain saved cleanup hold");
 RebirthGearTerminalOwnerCheckpoint.Saved=true;
 Check(RebirthGearOfferClient.TryFinishCurrentTerminal(nativeWorld,7)&&RebirthGearOwnerReservation.Releases==earlyReleases+1&&RebirthGearOwnerInventoryAdapter.Applies==earlyApplies&&!RebirthGearOfferClient.TryGetCurrentOffer(nativeWorld,7,out _),"cached terminal retries cleanup exactly once without applying items");
 Check(!RebirthGearOfferClient.TryFinishCurrentTerminal(nativeWorld,7)&&RebirthGearOwnerReservation.Releases==earlyReleases+1,"duplicate cached terminal cannot release again");
 Check(RebirthGearOfferClient.TryGetSettledOriginal(nativeWorld,7,boundOffer.TransactionId,out var settledOffer)&&settledOffer.ToXml().ToString()==boundOffer.ToXml().ToString(),"saved release retains exact original presentation evidence");
 Check(!RebirthGearOfferClient.TryGetSettledOriginal(nativeWorld,7,Guid.NewGuid().ToString("N"),out _),"foreign transaction cannot pick settled item");
 var settledPeer=manager.connectionToServer[0];manager.connectionToServer[0]=new Connection();
 Check(!RebirthGearOfferClient.TryGetSettledOriginal(nativeWorld,7,boundOffer.TransactionId,out _),"replacement peer cannot use settled original");manager.connectionToServer[0]=settledPeer;
 GameManager.Instance.World=new World();Check(!RebirthGearOfferClient.TryGetSettledOriginal(nativeWorld,7,boundOffer.TransactionId,out _),"replacement world cannot use settled original");GameManager.Instance.World=nativeWorld;
 RebirthSurvivorClientState.Creation=Guid.NewGuid().ToString("N");Check(!RebirthGearOfferClient.TryGetSettledOriginal(nativeWorld,7,boundOffer.TransactionId,out _),"replacement creation cannot use settled original");RebirthSurvivorClientState.Creation=creation;
 nativePlayer.Dead=true;Check(!RebirthGearOfferClient.TryGetSettledOriginal(nativeWorld,7,boundOffer.TransactionId,out _),"dead owner cannot use settled original");nativePlayer.Dead=false;
 RebirthGearTerminalClient.Cached.Applied=false;Check(!RebirthGearOfferClient.TryGetSettledOriginal(nativeWorld,7,boundOffer.TransactionId,out _),"rejected terminal cannot use applied original");RebirthGearTerminalClient.Cached.Applied=true;
 RebirthGearTerminalClient.Cached.GearRevision++;Check(!RebirthGearOfferClient.TryGetSettledOriginal(nativeWorld,7,boundOffer.TransactionId,out _),"changed terminal revision cannot use original");RebirthGearTerminalClient.Cached.GearRevision--;
 RebirthGearTerminalClient.Cached.PreparationRequestDigest=new string('b',64);Check(!RebirthGearOfferClient.TryGetSettledOriginal(nativeWorld,7,boundOffer.TransactionId,out _),"changed terminal digest cannot use original");RebirthGearTerminalClient.Cached.PreparationRequestDigest=boundOffer.PreparationRequestDigest;
 RebirthGearTerminalOwnerCheckpoint.Saved=false;RebirthGearOfferClient.Reset();
 Check(!RebirthGearOfferClient.TryGetSettledOriginal(nativeWorld,7,boundOffer.TransactionId,out _),"explicit reset drops settled presentation evidence");
 manager.IsServer=true;var serverPlayer=new EntityPlayer();var serverSender=new ClientInfo();RebirthRemoteGearInventorySource.Record=new GearRecord();RebirthRemoteGearInventorySource.Record.Support.PendingGearTransfer=offer;
 Check(RebirthGearOfferServer.TryAdvanceApplied(serverPlayer,serverSender,creation,tx)&&RebirthRemoteGearAppliedConfirmation.Commits==1,"verified applied request advances commit");
 RebirthRemoteGearAppliedConfirmation.Confirmed=false;Check(!RebirthGearOfferServer.TryAdvanceApplied(serverPlayer,serverSender,creation,tx)&&RebirthRemoteGearAppliedConfirmation.Commits==1,"early unsaved native upload does not commit");RebirthRemoteGearAppliedConfirmation.Confirmed=true;
 Check(!RebirthGearOfferServer.TryAdvanceApplied(serverPlayer,serverSender,creation,Guid.NewGuid())&&RebirthRemoteGearAppliedConfirmation.Commits==1,"foreign transaction cannot advance");
 var advanceRecord=RebirthRemoteGearInventorySource.Record;RebirthRemoteGearAppliedConfirmation.OnConfirm=()=>RebirthRemoteGearInventorySource.Record=new GearRecord();Check(!RebirthGearOfferServer.TryAdvanceApplied(serverPlayer,serverSender,creation,tx)&&RebirthRemoteGearAppliedConfirmation.Commits==1,"record replacement after confirm refuses commit");RebirthRemoteGearInventorySource.Record=advanceRecord;RebirthRemoteGearAppliedConfirmation.OnConfirm=null;
 Check(RebirthGearOfferServer.TrySendPrepared(serverPlayer,serverSender,creation)&&manager.Sent==count,"saved sender queues all fragments");
 var sentAssembly=assembly(5,digest);foreach(var f in manager.Fragments)sentAssembly.TryAdd(f);Check(sentAssembly.TryFinish(out _),"sender fragments reconstruct exact offer");
 int terminalStart=manager.Sent;Check(RebirthGearOfferServer.TrySendTerminalOriginal(serverPlayer,serverSender,"original-marker",new RebirthGearSettlement())&&manager.Sent==terminalStart+count,"terminal exact original queues bounded fragments without advancement");
 RebirthRemoteGearAppliedConfirmation.Confirmed=false;terminalStart=manager.Sent;Check(!RebirthGearOfferServer.TrySendTerminalOriginal(serverPlayer,serverSender,"original-marker",new RebirthGearSettlement())&&manager.Sent==terminalStart,"unverified terminal original does not queue fragments");RebirthRemoteGearAppliedConfirmation.Confirmed=true;
 int boundStart=manager.Sent;Check(RebirthGearOfferServer.TrySendPreparedBound(serverPlayer,serverSender,"original-marker")&&manager.Sent==boundStart+count,"bound server path delivers only replayed saved offer");
 var retainedSupport=RebirthRemoteGearInventorySource.Record.Support;retainedSupport.GearTransferPhase=RebirthGearTransferPhase.OwnerApplied;int phaseStart=manager.Sent;
 Check(!RebirthGearOfferServer.TrySendPreparedBound(serverPlayer,serverSender,"original-marker")&&manager.Sent==phaseStart,"prepared-only delivery does not rewind applied phase");
 Check(RebirthGearOfferServer.TrySendRetainedBound(serverPlayer,serverSender,"original-marker")&&manager.Sent==phaseStart+count&&retainedSupport.GearTransferPhase==RebirthGearTransferPhase.OwnerApplied,"retained applied delivery preserves phase");
 retainedSupport.GearTransferPhase=RebirthGearTransferPhase.GearCommitted;phaseStart=manager.Sent;
 Check(RebirthGearOfferServer.TrySendRetainedBound(serverPlayer,serverSender,"original-marker")&&manager.Sent==phaseStart+count&&retainedSupport.GearTransferPhase==RebirthGearTransferPhase.GearCommitted,"retained committed delivery preserves phase");
 retainedSupport.GearTransferPhase=RebirthGearTransferPhase.Prepared;
 int sent=manager.Sent;RebirthRemoteGearPreparation.Saved=false;Check(!RebirthGearOfferServer.TrySendPrepared(serverPlayer,serverSender,creation)&&manager.Sent==sent,"unsaved offer not sent");RebirthRemoteGearPreparation.Saved=true;
 RebirthRemoteGearPreparation.Saved=false;Check(!RebirthGearOfferServer.TrySendPreparedBound(serverPlayer,serverSender,"original-marker")&&manager.Sent==sent,"bound path refuses missing saved replay");RebirthRemoteGearPreparation.Saved=true;
 NetPackageManager.Missing=true;Check(!RebirthGearOfferServer.TrySendPrepared(serverPlayer,serverSender,creation)&&manager.Sent==sent,"mapping refusal before send");NetPackageManager.Missing=false;
 var retainedRecord=RebirthRemoteGearInventorySource.Record;manager.OnSend=()=>RebirthRemoteGearInventorySource.Record=new GearRecord();Check(!RebirthGearOfferServer.TrySendPrepared(serverPlayer,serverSender,creation)&&manager.Sent==sent+1&&retainedRecord.Support.PendingGearTransfer==offer,"scope change stops remainder without deleting saved intent");manager.OnSend=null;
 var publication=Guid.NewGuid();Check(RebirthGearRecoveryIdentity.TryCreate("owner",creation,tx,publication,188,out var recoveryIdentity),"explicit recovery identity creation");var recoveryBytes=recoveryIdentity.Encode();Check(RebirthGearRecoveryIdentity.TryDecode(recoveryBytes,out var recovered)&&recovered.TransactionId==tx&&recovered.PublicationId==publication&&recovered.EntryIndex==188&&recovered.OwnerKey=="owner","exact recovery identity roundtrip");Check(!RebirthGearRecoveryIdentity.TryDecode(recoveryBytes.Take(recoveryBytes.Length-1).ToArray(),out _),"truncated recovery identity refuses");Check(!RebirthGearRecoveryIdentity.TryDecode(recoveryBytes.Concat(new byte[]{0}).ToArray(),out _),"trailing recovery identity refuses");Check(!RebirthGearRecoveryIdentity.TryCreate("owner",creation,tx,publication,189,out _),"out-of-plan recovery entry refuses");
 var recoveryPlan=new RebirthGearInventoryPlan{BagSlotsBefore=65,BagSlotsAfter=52,BeltSlotsBefore=5,BeltSlotsAfter=4,GearBefore=new RebirthGearInventoryPlan.Stack{ItemData="AQ==",Count=1},GearAfter=new RebirthGearInventoryPlan.Stack{ItemData="Ag==",Count=1}};
 recoveryPlan.Changes.Add(new RebirthGearInventoryPlan.Change{IsBag=true,Index=0,Before=new RebirthGearInventoryPlan.Stack{ItemData="Ag==",Count=1}});
 for(int i=0;i<3;i++){bool bag=i<2;int index=bag?52+i:4;var stack=new RebirthGearInventoryPlan.Stack{ItemData=Convert.ToBase64String(new[]{(byte)(3+i)}),Count=i+2};recoveryPlan.Changes.Add(new RebirthGearInventoryPlan.Change{IsBag=bag,Index=index,Before=stack});recoveryPlan.Recovery.Add(new RebirthGearInventoryPlan.RecoveryEntry{Origin=bag?RebirthGearInventoryPlan.RecoveryOrigin.Backpack:RebirthGearInventoryPlan.RecoveryOrigin.Belt,SourceIndex=index,Item=stack});}
 recoveryPlan.Recovery.Add(new RebirthGearInventoryPlan.RecoveryEntry{Origin=RebirthGearInventoryPlan.RecoveryOrigin.DisplacedGear,SourceIndex=-1,Item=new RebirthGearInventoryPlan.Stack{ItemData="AQ==",Count=1}});
 Check(RebirthGearTransferState.TryCreate(tx.ToString("N"),creation,"backpack",5,recoveryPlan,out var recoveryOffer)&&recoveryOffer.TryGetRecoveryManifest(out _),"new recovery intent includes manifest");
 recoveryOffer.TryGetRecoveryManifest(out var manifest);var manifestXml=manifest.ToXml();Check(manifestXml.Elements().Count()==3&&manifestXml.Elements().First().Elements().Count()==2,"one backpack plus distinct timed items");
 var recoveryXml=recoveryOffer.ToXml();Check(RebirthGearTransferState.TryRead(recoveryXml,out var restoredOffer)&&restoredOffer.ToXml().ToString()==recoveryXml.ToString(),"saved publication identities stable on reload");
 Check(RebirthGearOfferWireCodec.TryEncode(recoveryOffer,out var recoveryWire)&&RebirthGearOfferWireCodec.TryDecode(recoveryWire,out var recoveryDecoded)&&recoveryDecoded.ToXml().ToString()==recoveryXml.ToString(),"manifest survives actual offer wire");
 manifestXml.Elements().First().Remove();Check(manifest.ToXml().Elements().Count()==3,"manifest detached XML ownership");
 Func<System.Xml.Linq.XElement> freshManifest=()=>manifest.ToXml();var invalidManifest=freshManifest();invalidManifest.Elements().Last().Remove();Check(!RebirthGearRecoveryManifest.TryRead(invalidManifest,recoveryPlan,out _),"missing recovery entry refuses");
 invalidManifest=freshManifest();invalidManifest.Elements().Last().SetAttributeValue("id",invalidManifest.Elements().First().Attribute("id").Value);Check(!RebirthGearRecoveryManifest.TryRead(invalidManifest,recoveryPlan,out _),"duplicate publication refuses");
 invalidManifest=freshManifest();invalidManifest.Elements().First().SetAttributeValue("kind","item");Check(!RebirthGearRecoveryManifest.TryRead(invalidManifest,recoveryPlan,out _),"backpack cannot become timed drop");
 invalidManifest=freshManifest();invalidManifest.Elements().Last().Elements().First().SetAttributeValue("index",99);Check(!RebirthGearRecoveryManifest.TryRead(invalidManifest,recoveryPlan,out _),"foreign plan entry refuses");
 var legacyXml=recoveryOffer.ToXml();legacyXml.Element("recoveryManifest").Remove();Check(RebirthGearTransferState.TryRead(legacyXml,out var legacyOffer)&&!legacyOffer.TryGetRecoveryManifest(out _)&&legacyOffer.ToXml().Element("recoveryManifest")==null,"legacy pending intent loads without inventing publication IDs");
 var duplicateXml=recoveryOffer.ToXml();duplicateXml.Add(manifest.ToXml());Check(!RebirthGearTransferState.TryRead(duplicateXml,out _),"duplicate manifest refuses");
 var backpackPublication=Guid.Parse((string)manifest.ToXml().Elements().First().Attribute("id"));RebirthGearRecoveryAttempt.TryCreate(backpackPublication,501,1,2,3,4,3600,5,out var backpackAttempt);
 Check(recoveryOffer.TryAppendRecoveryAttempt(backpackAttempt,out var attemptedOffer)&&RebirthGearOfferWireCodec.TryEncode(attemptedOffer,out var attemptedWire)&&RebirthGearOfferWireCodec.TryDecode(attemptedWire,out var decodedAttempted)&&decodedAttempted.TryGetRecoveryAttempt(backpackPublication,out var attemptedResult)&&attemptedResult.LifetimeSeconds==3600,"saved attempt preserves native placement across transport");
 var itemPublication=Guid.Parse((string)manifest.ToXml().Elements().Last().Attribute("id"));RebirthGearRecoveryAttempt.TryCreate(itemPublication,501,1,2,3,4,1800,5,out var sharedEntityAttempt);Check(!attemptedOffer.TryAppendRecoveryAttempt(sharedEntityAttempt,out _),"two publications cannot claim same native entity");
 var orphanAttemptXml=attemptedOffer.ToXml();orphanAttemptXml.Element("recoveryManifest").Remove();Check(!RebirthGearTransferState.TryRead(orphanAttemptXml,out _),"attempt without saved manifest refuses");
 var malformedAttempt=backpackAttempt.ToXml();malformedAttempt.SetAttributeValue("x","Infinity");Check(!RebirthGearRecoveryAttempt.TryRead(malformedAttempt,out _),"nonfinite serialized placement refuses");
 recoveryPlan.Recovery[0].Item.Count=65536;Check(!recoveryPlan.IsConserved(),"native oversized stack cannot enter custody plan");recoveryPlan.Recovery[0].Item.Count=65535;Check(recoveryPlan.IsConserved(),"native maximum stack remains conserved");
 Func<byte[],bool> rejectedText=raw=>{try{using(var input=new System.IO.MemoryStream(raw))using(var reader=new System.IO.BinaryReader(input))RebirthGearRecoveryStringWire.Read(reader);return false;}catch{return true;}};
 using(var textBuffer=new System.IO.MemoryStream()){using(var textWriter=new System.IO.BinaryWriter(textBuffer,System.Text.Encoding.UTF8,true)){textWriter.Write("Recovery "+new string('\u03bb',4096-9));}textBuffer.Position=0;using(var textReader=new System.IO.BinaryReader(textBuffer)){Check(RebirthGearRecoveryStringWire.Read(textReader).Length==4096&&textBuffer.Position==textBuffer.Length,"bounded native-format Unicode recovery text roundtrip");}}
 Check(rejectedText(new byte[]{0x81,0x80,1}),"oversized declared recovery text refuses before payload read");Check(rejectedText(new byte[]{2,65}),"truncated recovery text refuses");Check(rejectedText(new byte[]{2,0xc0,0x80}),"invalid UTF8 recovery text refuses");Check(rejectedText(new byte[]{0x80,0}),"noncanonical text length refuses");Check(rejectedText(new byte[]{0xff,0xff,0xff,0xff,0x7f}),"overflowed recovery text length refuses");bool surrogateRejected=false;try{RebirthGearRecoveryStringWire.Validate(new string((char)0xd800,1));}catch{surrogateRejected=true;}Check(surrogateRejected,"unpaired surrogate cannot be written as different recovery text");
 Func<byte[],byte[]> wrapMetadata=metadataBytes=>{using(var stream=new System.IO.MemoryStream())using(var writer=new System.IO.BinaryWriter(stream)){writer.Write((byte)38);writer.Write(666);writer.Write(501);writer.Write(1800f);writer.Write(new byte[24]);writer.Write(false);writer.Write(4);writer.Write(0L);writer.Write(false);writer.Write((short)0);writer.Write(true);writer.Write(1);writer.Write((byte)2);writer.Write(new byte[15]);writer.Write((ushort)metadataBytes.Length);writer.Write(metadataBytes);writer.Write(false);writer.Write(0f);writer.Write(new byte[24]);return stream.ToArray();}};
 foreach(bool backpackMetadata in new[]{true,false}){byte[] raw;using(var stream=new System.IO.MemoryStream())using(var writer=new System.IO.BinaryWriter(stream)){writer.Write((byte)8);writer.Write((ulong)123);writer.Write((byte)1);writer.Write(7);if(backpackMetadata){writer.Write(false);writer.Write("cntDropBag");writer.Write("Recovery \u03bb");}else{writer.Write(9);writer.Write(7);}writer.Write((ushort)recoveryBytes.Length);writer.Write(recoveryBytes);raw=stream.ToArray();}
 var metadataFrame=wrapMetadata(raw);Check(RebirthRecoveryEntityRecord.TryRead(metadataFrame,0,666,out var metadataRecord)&&RebirthRecoveryEntityMetadata.TryRead(metadataFrame,metadataRecord,8,backpackMetadata,out _),"full record framing plus metadata decoder");RebirthRecoveryEntityMetadata.TryRead(metadataFrame,metadataRecord,8,backpackMetadata,out var decodedMetadata);Check(decodedMetadata.WorldTimeBorn==123&&decodedMetadata.Identity.Encode().SequenceEqual(recoveryBytes)&&(backpackMetadata?(decodedMetadata.Name=="Recovery \u03bb"&&decodedMetadata.LootList=="cntDropBag"&&decodedMetadata.SpawnById==7):(decodedMetadata.BelongsPlayerId==7&&decodedMetadata.ClientEntityId==9&&decodedMetadata.OwnerId==7)),"exact metadata names ownership and identity restored");Check(!RebirthRecoveryEntityMetadata.TryRead(metadataFrame,metadataRecord,9,backpackMetadata,out _),"foreign spawner source refuses");
 var trailingFrame=wrapMetadata(raw.Concat(new byte[]{0}).ToArray());RebirthRecoveryEntityRecord.TryRead(trailingFrame,0,666,out var trailingRecord);Check(!RebirthRecoveryEntityMetadata.TryRead(trailingFrame,trailingRecord,8,backpackMetadata,out _),"trailing compact metadata refuses");var truncatedFrame=wrapMetadata(raw.Take(raw.Length-1).ToArray());RebirthRecoveryEntityRecord.TryRead(truncatedFrame,0,666,out var truncatedRecord);Check(!RebirthRecoveryEntityMetadata.TryRead(truncatedFrame,truncatedRecord,8,backpackMetadata,out _),"truncated compact identity refuses");raw[9]=2;var wrongSchemaFrame=wrapMetadata(raw);RebirthRecoveryEntityRecord.TryRead(wrongSchemaFrame,0,666,out var schemaRecord);Check(!RebirthRecoveryEntityMetadata.TryRead(wrongSchemaFrame,schemaRecord,8,backpackMetadata,out _),"unknown compact schema refuses");if(backpackMetadata){raw[9]=1;raw[14]=2;var shareFrame=wrapMetadata(raw);RebirthRecoveryEntityRecord.TryRead(shareFrame,0,666,out var shareRecord);Check(!RebirthRecoveryEntityMetadata.TryRead(shareFrame,shareRecord,8,true,out _),"invalid sharing flag refuses");}}
 recoveryPlan.Recovery[0].Item.Count=2;RebirthGearTransferState.TryCreate(tx.ToString("N"),creation,"backpack",5,recoveryPlan,out var bagOffer);bagOffer.TryGetRecoveryManifest(out var bagManifest);var bagPublication=Guid.Parse((string)bagManifest.ToXml().Elements().First().Attribute("id"));byte[] exactBag;using(var stream=new System.IO.MemoryStream())using(var writer=new System.IO.BinaryWriter(stream)){writer.Write((byte)2);writer.Write((ushort)2);writer.Write(3);writer.Write(1);writer.Write((short)3);foreach(int index in new[]{0,1}){writer.Write((ushort)recoveryPlan.Recovery[index].Item.Count);writer.Write(Convert.FromBase64String(recoveryPlan.Recovery[index].Item.ItemData));}writer.Write((ushort)0);writer.Write(true);writer.Write((byte)3);writer.Write((byte)0);writer.Write(true);writer.Write(-1);writer.Write(false);writer.Write(false);writer.Write(false);writer.Write((ulong)123);writer.Write(false);exactBag=stream.ToArray();}
 Func<byte[],byte[]> wrapBag=bagBytes=>{using(var stream=new System.IO.MemoryStream())using(var writer=new System.IO.BinaryWriter(stream)){writer.Write((byte)38);writer.Write(666);writer.Write(501);writer.Write(3600f);writer.Write(new byte[24]);writer.Write(false);writer.Write(4);writer.Write(0L);writer.Write(false);writer.Write((short)0);writer.Write(true);writer.Write(bagBytes.Length);writer.Write(bagBytes);writer.Write(new byte[15]);writer.Write((ushort)1);writer.Write((byte)1);writer.Write(false);writer.Write(0f);writer.Write(new byte[24]);return stream.ToArray();}};
 var bagFrame=wrapBag(exactBag);RebirthRecoveryEntityRecord.TryRead(bagFrame,0,666,out var exactBagRecord);Check(RebirthRecoveryBagPayload.Matches(bagFrame,exactBagRecord,bagOffer,bagPublication),"exact manifest-bound bag counts metadata and empty tail");var alteredBag=(byte[])exactBag.Clone();alteredBag[15]^=1;var alteredFrame=wrapBag(alteredBag);RebirthRecoveryEntityRecord.TryRead(alteredFrame,0,666,out var alteredRecord);Check(!RebirthRecoveryBagPayload.Matches(alteredFrame,alteredRecord,bagOffer,bagPublication),"altered serialized ItemValue refuses");alteredBag=(byte[])exactBag.Clone();alteredBag[13]++;alteredFrame=wrapBag(alteredBag);RebirthRecoveryEntityRecord.TryRead(alteredFrame,0,666,out alteredRecord);Check(!RebirthRecoveryBagPayload.Matches(alteredFrame,alteredRecord,bagOffer,bagPublication),"altered stack count refuses");Check(!RebirthRecoveryBagPayload.Matches(bagFrame,exactBagRecord,bagOffer,Guid.NewGuid()),"foreign publication cannot claim bag");alteredFrame=wrapBag(exactBag.Concat(new byte[]{0}).ToArray());RebirthRecoveryEntityRecord.TryRead(alteredFrame,0,666,out alteredRecord);Check(!RebirthRecoveryBagPayload.Matches(alteredFrame,alteredRecord,bagOffer,bagPublication),"trailing bag bytes refuse");
 RebirthGearRecoveryAttempt.TryCreate(bagPublication,501,0,0,0,0,3600,123,7,out var evidenceAttempt);bagOffer.TryAppendRecoveryAttempt(evidenceAttempt,out var publicationAttemptedOffer);
 Func<string,int,ulong,byte[]> evidenceFrame=(owner,nativeOwner,time)=>{RebirthGearRecoveryIdentity.TryCreate(owner,creation,tx,bagPublication,0,out var marker);byte[] metadata;using(var ms=new System.IO.MemoryStream())using(var w=new System.IO.BinaryWriter(ms)){w.Write((byte)8);w.Write(time);w.Write((byte)1);w.Write(nativeOwner);w.Write(false);w.Write("");w.Write("");var identity=marker.Encode();w.Write((ushort)identity.Length);w.Write(identity);metadata=ms.ToArray();}using(var ms=new System.IO.MemoryStream())using(var w=new System.IO.BinaryWriter(ms)){w.Write((byte)38);w.Write(666);w.Write(501);w.Write(float.MaxValue);w.Write(new byte[24]);w.Write(false);w.Write(4);w.Write(0L);w.Write(false);w.Write((short)0);w.Write(true);w.Write(exactBag.Length);w.Write(exactBag);w.Write(new byte[15]);w.Write((ushort)metadata.Length);w.Write(metadata);w.Write(false);w.Write(0f);w.Write(new byte[24]);return ms.ToArray();}};
 var completeEvidence=evidenceFrame("owner",7,123);int evidenceEnd;
 Check(RebirthRecoveryPublicationEvidence.TryMatch(completeEvidence,0,publicationAttemptedOffer,bagPublication,"owner",7,666,667,8,out evidenceEnd)&&evidenceEnd==completeEvidence.Length,"joined original attempt identity and exact bag evidence");
 Check(!RebirthRecoveryPublicationEvidence.TryMatch(completeEvidence,0,bagOffer,bagPublication,"owner",7,666,667,8,out evidenceEnd)&&evidenceEnd==0,"unsaved attempt cannot count as publication");
 Check(!RebirthRecoveryPublicationEvidence.TryMatch(evidenceFrame("foreign",7,123),0,publicationAttemptedOffer,bagPublication,"owner",7,666,667,8,out evidenceEnd),"foreign owner marker refuses despite exact bag");
 Check(!RebirthRecoveryPublicationEvidence.TryMatch(evidenceFrame("owner",9,123),0,publicationAttemptedOffer,bagPublication,"owner",7,666,667,8,out evidenceEnd),"foreign native ownership refuses");
 Check(!RebirthRecoveryPublicationEvidence.TryMatch(evidenceFrame("owner",7,124),0,publicationAttemptedOffer,bagPublication,"owner",7,666,667,8,out evidenceEnd),"foreign birth time refuses");
 Check(!RebirthRecoveryPublicationEvidence.TryMatch(completeEvidence,0,publicationAttemptedOffer,bagPublication,"owner",7,667,666,8,out evidenceEnd),"wrong class role refuses");
 var changedEvidence=(byte[])completeEvidence.Clone();RebirthRecoveryEntityRecord.TryRead(changedEvidence,0,666,out var changedEvidenceRecord);changedEvidence[changedEvidenceRecord.BagOffset+15]^=1;
 Check(!RebirthRecoveryPublicationEvidence.TryMatch(changedEvidence,0,publicationAttemptedOffer,bagPublication,"owner",7,666,667,8,out evidenceEnd)&&evidenceEnd==0,"valid marker cannot claim altered conserved bytes");
 Check(RebirthGearRecoveryAttempt.TryRead(evidenceAttempt.ToXml(),out var ownerReload)&&ownerReload.OriginalOwnerEntityId==7,"original owner ID persists across reload");
 var legacyAttemptXml=evidenceAttempt.ToXml();legacyAttemptXml.Attribute("ownerEntity").Remove();Check(RebirthGearRecoveryAttempt.TryRead(legacyAttemptXml,out var legacyOwnerAttempt)&&legacyOwnerAttempt.OriginalOwnerEntityId==0,"legacy attempt remains readable without guessed owner");bagOffer.TryAppendRecoveryAttempt(legacyOwnerAttempt,out var legacyOwnerOffer);
 Check(!RebirthRecoveryPublicationEvidence.TryMatch(completeEvidence,0,legacyOwnerOffer,bagPublication,"owner",7,666,667,8,out evidenceEnd),"legacy missing original owner cannot authorize evidence");
 Check(!RebirthRecoveryPublicationEvidence.TryMatch(completeEvidence,0,publicationAttemptedOffer,bagPublication,"owner",9,666,667,8,out evidenceEnd),"reconnect entity ID cannot replace original owner");
 var badOwnerXml=evidenceAttempt.ToXml();badOwnerXml.SetAttributeValue("ownerEntity",0);Check(!RebirthGearRecoveryAttempt.TryRead(badOwnerXml,out _),"zero explicit original owner refuses");badOwnerXml.SetAttributeValue("ownerEntity",7);badOwnerXml.SetAttributeValue("extra",1);Check(!RebirthGearRecoveryAttempt.TryRead(badOwnerXml,out _),"unknown attempted ownership attribute refuses");
 int[] foreignSpecials={100,101,102,103,104,105,106};int foreignEnd;
 Check(RebirthRecoveryForeignRecord.TrySkip(completeEvidence,0,foreignSpecials,32768,id=>0,out foreignEnd)&&foreignEnd==completeEvidence.Length,"foreign ordinary record skips opaque bag and compact data");
 Func<int,Action<System.IO.BinaryWriter>,bool,byte[]> foreignFrame=(type,body,stats)=>{using(var ms=new System.IO.MemoryStream())using(var w=new System.IO.BinaryWriter(ms)){w.Write((byte)38);w.Write(type);w.Write(601);w.Write(new byte[28]);w.Write(false);w.Write(4);w.Write(0L);w.Write(stats);if(stats){w.Write(11);for(int k=0;k<((type==104||type==105)?4:1);k++){w.Write(6);w.Write(new byte[20]);}if(type==104||type==105)w.Write((byte)0);}w.Write((short)0);w.Write(false);w.Write(new byte[15]);body(w);w.Write((ushort)0);w.Write(false);if(type==106)w.Write(new byte[8]);w.Write(0f);w.Write(new byte[24]);return ms.ToArray();}};
 Action<System.IO.BinaryWriter> modifierStack=w=>{w.Write((ushort)1);w.Write((byte)9);w.Write((byte)0);w.Write((ushort)1);w.Write(new byte[8]);w.Write((byte)0);w.Write(new byte[4]);w.Write(false);};
 var modifierFrame=foreignFrame(100,w=>{w.Write(new byte[8]);modifierStack(w);w.Write((byte)0);},false);
 Check(RebirthRecoveryForeignRecord.TrySkip(modifierFrame,0,foreignSpecials,32768,id=>1,out foreignEnd)&&foreignEnd==modifierFrame.Length,"modifier ItemValue omits nested modification arrays");
 Check(!RebirthRecoveryForeignRecord.TrySkip(modifierFrame,0,foreignSpecials,32768,id=>-1,out foreignEnd)&&foreignEnd==0,"unresolved item class refuses foreign traversal");
 var zombieFrame=foreignFrame(200,w=>{},true);Check(RebirthRecoveryForeignRecord.TrySkip(zombieFrame,0,foreignSpecials,32768,id=>0,out foreignEnd)&&foreignEnd==zombieFrame.Length,"ordinary alive stats11 health6 skipped exactly");
 var playerFrame=foreignFrame(104,w=>{w.Write((ushort)0);w.Write((byte)0);w.Write("Player");w.Write("skin");w.Write(true);w.Write(5);w.Write("archetype");w.Write(true);w.Write("race");w.Write((byte)0);for(int j=0;j<6;j++)w.Write("");},true);
 Check(RebirthRecoveryForeignRecord.TrySkip(playerFrame,0,foreignSpecials,32768,id=>0,out foreignEnd)&&foreignEnd==playerFrame.Length,"player stats and current profile skipped");
 var fallingFrame=foreignFrame(102,w=>{w.Write(2);w.Write(new byte[48]);},false);Check(RebirthRecoveryForeignRecord.TrySkip(fallingFrame,0,foreignSpecials,32768,id=>0,out foreignEnd)&&foreignEnd==fallingFrame.Length,"falling multi-block arrays skipped without allocation");
 var oversizedFalling=foreignFrame(102,w=>w.Write(int.MaxValue),false);Check(!RebirthRecoveryForeignRecord.TrySkip(oversizedFalling,0,foreignSpecials,32768,id=>0,out foreignEnd),"unbounded falling array count refuses");
 var droneFrame=foreignFrame(106,w=>{},false);Check(RebirthRecoveryForeignRecord.TrySkip(droneFrame,0,foreignSpecials,32768,id=>0,out foreignEnd)&&foreignEnd==droneFrame.Length,"drone owner order tail skipped");
 Check(!RebirthRecoveryForeignRecord.TrySkip(playerFrame.Take(playerFrame.Length-1).ToArray(),0,foreignSpecials,32768,id=>0,out foreignEnd)&&foreignEnd==0,"truncated foreign tail refuses with no successful offset");
 var sectionWire=zombieFrame.Concat(completeEvidence).ToArray();int sectionEnd;
 Check(RebirthRecoveryEntityEvidence.TryMatch(sectionWire,0,2,publicationAttemptedOffer,bagPublication,"owner",666,667,8,foreignSpecials,32768,id=>0,out sectionEnd)&&sectionEnd==sectionWire.Length,"whole declared section locates publication after ordinary zombie");
 sectionWire=completeEvidence.Concat(zombieFrame).ToArray();Check(RebirthRecoveryEntityEvidence.TryMatch(sectionWire,0,2,publicationAttemptedOffer,bagPublication,"owner",666,667,8,foreignSpecials,32768,id=>0,out sectionEnd)&&sectionEnd==sectionWire.Length,"whole declared section validates records after publication");
 Check(!RebirthRecoveryEntityEvidence.TryMatch(sectionWire.Take(sectionWire.Length-1).ToArray(),0,2,publicationAttemptedOffer,bagPublication,"owner",666,667,8,foreignSpecials,32768,id=>0,out sectionEnd)&&sectionEnd==0,"malformed later record invalidates earlier matched publication");
 Check(!RebirthRecoveryEntityEvidence.TryMatch(completeEvidence.Concat(completeEvidence).ToArray(),0,2,publicationAttemptedOffer,bagPublication,"owner",666,667,8,foreignSpecials,32768,id=>0,out sectionEnd),"duplicate entity ID publication refuses whole section");
 Check(!RebirthRecoveryEntityEvidence.TryMatch(zombieFrame,0,1,publicationAttemptedOffer,bagPublication,"owner",666,667,8,foreignSpecials,32768,id=>0,out sectionEnd)&&sectionEnd==0,"absent publication cannot count as completion");
 Check(!RebirthRecoveryEntityEvidence.TryMatch(completeEvidence,0,1,publicationAttemptedOffer,bagPublication,"foreign",666,667,8,foreignSpecials,32768,id=>0,out sectionEnd),"whole section requires original authenticated marker owner");
 Check(!RebirthRecoveryEntityEvidence.TryMatch(completeEvidence,0,1,publicationAttemptedOffer,bagPublication,"owner",100,667,8,foreignSpecials,32768,id=>0,out sectionEnd),"native special class cannot serve as recovery class");
 byte[] chunkEvidenceBytes;using(var ms=new System.IO.MemoryStream())using(var w=new System.IO.BinaryWriter(ms)){w.Write(4);w.Write(0);w.Write(-7);w.Write(0L);w.Write(new byte[64]);Action<int> ch=bytes=>{for(int i=0;i<64;i++){w.Write(true);w.Write(new byte[bytes]);}};ch(1);w.Write(new byte[512+32+1794]);w.Write((ushort)0);w.Write(new byte[768]);ch(1);ch(1);ch(2);ch(6);ch(2);w.Write(false);w.Write(2);w.Write(zombieFrame);w.Write(completeEvidence);chunkEvidenceBytes=ms.ToArray();}
 Check(RebirthRecoveryChunkEvidence.TryMatch(chunkEvidenceBytes,46,4,0,-7,publicationAttemptedOffer,bagPublication,"owner",666,667,8,foreignSpecials,32768,id=>0,out sectionEnd)&&sectionEnd==chunkEvidenceBytes.Length,"chunk coordinates prefix and complete entity evidence connected");
 Check(!RebirthRecoveryChunkEvidence.TryMatch(chunkEvidenceBytes,46,5,0,-7,publicationAttemptedOffer,bagPublication,"owner",666,667,8,foreignSpecials,32768,id=>0,out sectionEnd)&&sectionEnd==0,"wrong chunk x refuses evidence");
 Check(!RebirthRecoveryChunkEvidence.TryMatch(chunkEvidenceBytes,46,4,1,-7,publicationAttemptedOffer,bagPublication,"owner",666,667,8,foreignSpecials,32768,id=>0,out sectionEnd),"wrong chunk y refuses evidence");
 Check(!RebirthRecoveryChunkEvidence.TryMatch(chunkEvidenceBytes,46,4,0,7,publicationAttemptedOffer,bagPublication,"owner",666,667,8,foreignSpecials,32768,id=>0,out sectionEnd),"wrong chunk z refuses evidence");
 Check(!RebirthRecoveryChunkEvidence.TryMatch(chunkEvidenceBytes,47,4,0,-7,publicationAttemptedOffer,bagPublication,"owner",666,667,8,foreignSpecials,32768,id=>0,out sectionEnd),"unknown chunk version refuses evidence");
 byte[] stationRecord;using(var ms=new System.IO.MemoryStream())using(var w=new System.IO.BinaryWriter(ms)){w.Write((ushort)19);w.Write(new byte[20]);w.Write((byte)50);w.Write(0L);for(int i=0;i<4;i++)w.Write((byte)0);w.Write((byte)1);w.Write((ushort)2);w.Write((short)3);w.Write(true);w.Write(2.5f);w.Write(false);w.Write((byte)1);w.Write(7);w.Write(1.5f);w.Write(true);w.Write((ushort)1);w.Write(1);w.Write(1);w.Write(false);w.Write(1.5f);w.Write(20);w.Write("workbench");w.Write(1);w.Write((ushort)0);w.Write((short)1);w.Write((ushort)1);w.Write(7);w.Write((ushort)0);w.Write("fixtureRecipe");w.Write(20);w.Write((ushort)1);w.Write("");w.Write(false);w.Write(0f);w.Write((byte)0);w.Write(true);w.Write((byte)0);stationRecord=ms.ToArray();}
 Check(RebirthRecoveryStationRecord.TrySkip(stationRecord,0,32768,id=>0,out sectionEnd)&&sectionEnd==stationRecord.Length,"whole workstation queue recipe completion and inventory framing");
 Check(!RebirthRecoveryStationRecord.TrySkip(stationRecord.Take(stationRecord.Length-1).ToArray(),0,32768,id=>0,out sectionEnd)&&sectionEnd==0,"truncated workstation tail refuses");
 var unknownStation=(byte[])stationRecord.Clone();unknownStation[22]=51;Check(!RebirthRecoveryStationRecord.TrySkip(unknownStation,0,32768,id=>0,out sectionEnd),"unknown workstation schema refuses");
 unknownStation=(byte[])stationRecord.Clone();unknownStation[0]=20;Check(!RebirthRecoveryStationRecord.TrySkip(unknownStation,0,32768,id=>0,out sectionEnd),"unknown tile base schema refuses workstation");
 foreach(var tileKind in new[]{RebirthRecoveryTileKind.Collector,RebirthRecoveryTileKind.Light,RebirthRecoveryTileKind.Sleeper,RebirthRecoveryTileKind.PoweredBlock,RebirthRecoveryTileKind.PowerSource,RebirthRecoveryTileKind.PoweredTrigger,RebirthRecoveryTileKind.RangedTrap,RebirthRecoveryTileKind.MeleeTrap}){byte[] tileBytes;using(var ms=new System.IO.MemoryStream())using(var w=new System.IO.BinaryWriter(ms)){w.Write((ushort)19);w.Write(new byte[20]);if(tileKind==RebirthRecoveryTileKind.Collector){w.Write((ushort)21);w.Write((ushort)0);w.Write((ushort)0);w.Write(false);w.Write(false);w.Write((ushort)0);w.Write((ushort)0);for(int j=0;j<3;j++)w.Write((short)0);}else if(tileKind==RebirthRecoveryTileKind.Light){w.Write((ushort)18);w.Write(new byte[27]);}else if(tileKind==RebirthRecoveryTileKind.Sleeper){w.Write((ushort)18);w.Write(new byte[12]);}else{w.Write(1);w.Write(false);w.Write((byte)0);w.Write((byte)1);w.Write(new byte[32]);w.Write((ushort)18);if(tileKind==RebirthRecoveryTileKind.RangedTrap||tileKind==RebirthRecoveryTileKind.MeleeTrap){w.Write((ushort)18);w.Write(true);w.Write((byte)0);w.Write("Steam");w.Write("fixtureOwner");}if(tileKind==RebirthRecoveryTileKind.PoweredTrigger){w.Write((byte)3);w.Write(false);}}tileBytes=ms.ToArray();}Check(RebirthRecoveryUtilityTileRecord.TrySkip(tileBytes,0,tileKind,32768,id=>0,out sectionEnd)&&sectionEnd==tileBytes.Length,"complete native utility tile grammar "+tileKind);Check(!RebirthRecoveryUtilityTileRecord.TrySkip(tileBytes.Take(tileBytes.Length-1).ToArray(),0,tileKind,32768,id=>0,out sectionEnd)&&sectionEnd==0,"truncated native utility tile refuses "+tileKind);}
 byte[] forgeRecord;using(var ms=new System.IO.MemoryStream())using(var w=new System.IO.BinaryWriter(ms)){w.Write((ushort)19);w.Write(new byte[20]);w.Write((ushort)18);w.Write(0L);w.Write((byte)0);w.Write((byte)0);w.Write((ushort)0);w.Write((ushort)0);w.Write(new byte[8]);w.Write((byte)0);forgeRecord=ms.ToArray();}Check(RebirthRecoveryUtilityTileRecord.TrySkip(forgeRecord,0,RebirthRecoveryTileKind.Forge,32768,id=>0,out sectionEnd)&&sectionEnd==forgeRecord.Length,"forge18 fuel input mold output burn item framing");Check(!RebirthRecoveryUtilityTileRecord.TrySkip(forgeRecord.Take(forgeRecord.Length-1).ToArray(),0,RebirthRecoveryTileKind.Forge,32768,id=>0,out sectionEnd),"truncated forge burn item refuses");
 foreach(bool rentable in new[]{false,true}){byte[] vendingRecord;using(var ms=new System.IO.MemoryStream())using(var w=new System.IO.BinaryWriter(ms)){w.Write((ushort)19);w.Write(new byte[20]);w.Write(3);w.Write(true);w.Write(false);w.Write("passwordHash");w.Write(1);w.Write(true);w.Write((byte)0);w.Write("Steam");w.Write("fixtureOwner");w.Write(5);w.Write(7);w.Write(0L);w.Write((byte)2);w.Write(0);w.Write((byte)0);w.Write(50);if(rentable)w.Write(0L);vendingRecord=ms.ToArray();}Check(RebirthRecoveryVendingRecord.TrySkip(vendingRecord,0,32768,id=>0,id=>id==7?(rentable?1:0):-1,out sectionEnd)&&sectionEnd==vendingRecord.Length,"exact configured vending rentable branch "+rentable);Check(!RebirthRecoveryVendingRecord.TrySkip(vendingRecord,0,32768,id=>0,id=>-1,out sectionEnd)&&sectionEnd==0,"unknown vending trader definition refuses "+rentable);Check(!RebirthRecoveryVendingRecord.TrySkip(vendingRecord.Take(vendingRecord.Length-1).ToArray(),0,32768,id=>0,id=>rentable?1:0,out sectionEnd),"truncated vending record refuses "+rentable);}
 byte[] compositeRecord;using(var ms=new System.IO.MemoryStream())using(var w=new System.IO.BinaryWriter(ms)){w.Write((ushort)19);w.Write(new byte[20]);w.Write((ushort)18);long mark=ms.Position;w.Write(0u);w.Write(5);w.Write(true);w.Write((byte)0);w.Write("Steam");w.Write("fixtureOwner");w.Write((byte)2);w.Write(1000);w.Write(7u);w.Write(new byte[3]);w.Write(1001);w.Write(4u);long end=ms.Position;ms.Position=mark;w.Write((uint)(end-mark));compositeRecord=ms.ToArray();}
 Check(RebirthRecoveryCompositeRecord.TrySkip(compositeRecord,0,id=>id==5,out sectionEnd)&&sectionEnd==compositeRecord.Length,"composite native inclusive outer and feature size markers");
 Check(!RebirthRecoveryCompositeRecord.TrySkip(compositeRecord,0,id=>false,out sectionEnd)&&sectionEnd==0,"unknown composite block refuses");
 Check(!RebirthRecoveryCompositeRecord.TrySkip(compositeRecord.Take(compositeRecord.Length-1).ToArray(),0,id=>true,out sectionEnd),"truncated composite marker refuses");
 var brokenComposite=(byte[])compositeRecord.Clone();System.Array.Copy(BitConverter.GetBytes(3u),0,brokenComposite,brokenComposite.Length-4,4);Check(!RebirthRecoveryCompositeRecord.TrySkip(brokenComposite,0,id=>true,out sectionEnd),"feature size smaller than own marker refuses");
 brokenComposite=compositeRecord.Concat(new byte[]{0}).ToArray();Check(RebirthRecoveryCompositeRecord.TrySkip(brokenComposite,0,id=>true,out sectionEnd)&&sectionEnd==compositeRecord.Length,"composite stops at inclusive record end preserving next field");
 byte[] fullTail;using(var ms=new System.IO.MemoryStream())using(var w=new System.IO.BinaryWriter(ms)){w.Write(2);w.Write(1);w.Write(stationRecord);w.Write(2);w.Write(compositeRecord);w.Write(false);for(int j=0;j<3;j++){w.Write((byte)1);w.Write(7);}w.Write((short)2);w.Write((byte)4);w.Write((byte)5);w.Write((byte)2);w.Write((byte)20);w.Write((byte)21);w.Write(false);w.Write((short)1);w.Write(1);w.Write(45);w.Write(3);w.Write((ushort)5);w.Write((byte)0);for(int j=0;j<3;j++)w.Write((byte)0);w.Write(false);w.Write(false);w.Write(false);fullTail=ms.ToArray();}
 Func<byte[],Func<int,int,int>> tailParser=bytes=>(type,body)=>{int end;if(type==1&&RebirthRecoveryStationRecord.TrySkip(bytes,body,32768,id=>0,out end))return end;if(type==2&&RebirthRecoveryCompositeRecord.TrySkip(bytes,body,id=>id==5,out end))return end;return -1;};
 Check(RebirthRecoveryChunkTail.TryValidate(fullTail,46,0,tailParser(fullTail)),"complete populated tail stations containers volumes devices triggers EOF");
 var shortTail=fullTail.Take(fullTail.Length-1).ToArray();Check(!RebirthRecoveryChunkTail.TryValidate(shortTail,46,0,tailParser(shortTail)),"truncated populated tail refuses");var extraTail=fullTail.Concat(new byte[]{0}).ToArray();Check(!RebirthRecoveryChunkTail.TryValidate(extraTail,46,0,tailParser(extraTail)),"extra tail byte refuses exact EOF");Check(!RebirthRecoveryChunkTail.TryValidate(fullTail,46,0,(type,body)=>-1),"unknown tile type refuses full tail");Check(!RebirthRecoveryChunkTail.TryValidate(fullTail,45,0,tailParser(fullTail)),"legacy chunk tail cannot use current grammar");
 Check(!bagOffer.TryAppendRecoveryPublicationReceipt(bagPublication,out _),"publication receipt requires saved attempt");Check(!legacyOwnerOffer.TryAppendRecoveryPublicationReceipt(bagPublication,out _),"publication receipt requires known original owner");
 Check(publicationAttemptedOffer.TryAppendRecoveryPublicationReceipt(bagPublication,out var receiptedOffer)&&receiptedOffer.HasRecoveryPublicationReceipt(bagPublication)&&!receiptedOffer.HasAllRecoveryPublicationReceipts,"partial original publication receipts retain other groups");
 Check(RebirthGearTransferState.TryRead(receiptedOffer.ToXml(),out var receiptReload)&&receiptReload.HasRecoveryPublicationReceipt(bagPublication)&&!receiptReload.HasAllRecoveryPublicationReceipts,"publication receipt survives immutable pending reload");Check(!receiptReload.TryAppendRecoveryPublicationReceipt(bagPublication,out _),"duplicate publication receipt refuses");var badReceipt=receiptedOffer.ToXml();badReceipt.Element("recoveryReceipts").Elements().First().SetAttributeValue("id",Guid.NewGuid().ToString("N"));Check(!RebirthGearTransferState.TryRead(badReceipt,out _),"foreign publication receipt cannot clear original recovery");
 var allReceiptOffer=receiptReload;int receiptEntity=902;foreach(var group in bagManifest.ToXml().Elements().Where(e=>(string)e.Attribute("id")!=bagPublication.ToString("N"))){var pub=Guid.Parse((string)group.Attribute("id"));RebirthGearRecoveryAttempt.TryCreate(pub,receiptEntity++,0,0,0,0,(string)group.Attribute("kind")=="backpack"?3600:1800,123,7,out var otherAttempt);allReceiptOffer.TryAppendRecoveryAttempt(otherAttempt,out var withOtherAttempt);withOtherAttempt.TryAppendRecoveryPublicationReceipt(pub,out allReceiptOffer);}Check(allReceiptOffer.HasAllRecoveryPublicationReceipts,"every original group receipt required for completed recovery");
 Console.WriteLine("PASS "+checks+" whole gear plan/state/wire/assembly checks; actual source, no native item decode or network dispatch");
 }
}