using System;using System.Collections.Generic;using System.Linq;
public class RebirthGearInventorySnapshot{public RebirthGearInventoryPlan.Stack[] Bag,Belt;public int OwnedBeltSlots;public bool IsUsableSource(bool b,int i)=>i>=0&&i<(b?Bag.Length:OwnedBeltSlots);public static bool TryCapture(object b,object t,int o,out RebirthGearInventorySnapshot s){s=D.Image;return D.Capture;}}
public class EntityPlayerLocal{public int entityId=7;public World world;public Buffs Buffs=new();public Bag bag=new();public Bag inventory=new();public bool Dead,Spawned=true;public bool IsSpawned()=>Spawned;public bool IsDead()=>Dead;}
public class Bag{public Grid ItemGrid=new();}public class Grid{public object items=new();}
public class Buffs{public Dictionary<string,float> CVars=new();public float GetCustomVar(string k)=>CVars.TryGetValue(k,out var v)?v:0;public void SetCustomVar(string k,float v,bool sync)=>CVars[k]=v;public void RemoveCustomVar(string k)=>CVars.Remove(k);}
public class World{public WorldState worldState=new();public EntityPlayerLocal Player,Entity;public bool Remote=true;public bool IsRemote()=>Remote;public EntityPlayerLocal GetPrimaryPlayer()=>Player;public EntityPlayerLocal GetEntity(int id)=>Entity;}
public class WorldState{public string Guid;}
public class GameManager{public static GameManager Instance;public World World;public Persistent getPersistentPlayerID(object x)=>new(){CombinedString=D.Canonical};public void SaveLocalPlayerData(){D.Saves++;D.SaveAction?.Invoke();if(D.ThrowSave)throw new Exception("save");D.Retired=D.Publish&&!World.Player.Buffs.CVars.ContainsKey(D.Marker);D.Rejected=D.Publish&&World.Player.Buffs.CVars.ContainsKey(D.Marker);D.SavedPhase=-1;}}
public class Persistent{public string CombinedString;}public class SingletonMonoBehaviour<T>{public static T Instance;}public class Peer{public bool Dead;public bool IsDisconnected()=>Dead;}
public class ConnectionManager{public bool IsServer;public Peer[] connectionToServer;public void SendToServer(object p){D.Sends++;D.SendAction?.Invoke();if(D.ThrowSend)throw new Exception("send");}}
public static class ThreadManager{public static bool IsMainThread()=>D.Main;}public enum EnumGamePrefs{GameGuidClient}
public static class GamePrefs{public static string GetString(EnumGamePrefs p)=>D.WorldGuid;}public static class GameIO{public static string GetPlayerDataDir()=>D.Root;}
public static class RebirthSurvivorMode{public static bool IsEnabledForCurrentWorld()=>D.Mode;}
public static class RebirthCharacterCreationHoldService{public static bool IsHeld(EntityPlayerLocal p)=>D.CreationHold;}
public static class RebirthSurvivorClientState{public static string GetProjectedCreationId(EntityPlayerLocal p)=>D.Creation;}
public class RebirthStablePlayerIdentity{public string CanonicalId="owner";public static bool TryFromLocalPlatform(out RebirthStablePlayerIdentity o){o=new();return D.Owner;}}
public static class RebirthGearOwnerReservation{public static bool MatchesUnpreparedIntent(EntityPlayerLocal p,object s,RebirthGearPreparationIntent i){if(D.ThrowMatch)throw new Exception("match");return D.Hold&&!D.Offer;}public static bool ReleaseRefusedOriginal(EntityPlayerLocal p,object s,RebirthGearPreparationIntent i,Func<bool> witness){if(!MatchesUnpreparedIntent(p,s,i)||!witness()||!MatchesUnpreparedIntent(p,s,i))return false;D.Hold=false;return true;}}
public static class RebirthGearPreparationPlayerFileWitness{public static bool TryReadOriginalPhase(RebirthStablePlayerIdentity o,Guid w,out string m,out RebirthGearPreparationIntent i,out RebirthGearInventorySnapshot s,out float phase){m=D.Marker;i=D.Intent;s=D.SavedImage;phase=D.SavedPhase;return D.File;}}
public static class RebirthGearPreparationRefusalPlayerFileWitness{public static bool HasRetired(RebirthStablePlayerIdentity o,RebirthGearPreparationRefusal r){D.RetiredCalls++;D.RetiredAction?.Invoke();return D.Retired;}public static bool HasRejectedOriginal(RebirthStablePlayerIdentity o,RebirthGearPreparationRefusal r)=>D.Rejected;}
public static class D{
public static bool Main=true,Mode=true,Owner=true,Hold=true,Offer,Rejected,Capture=true,File=true,Retired,Publish=true,ThrowSave,CreationHold;
public static string Canonical="owner",WorldGuid,Root=System.IO.Path.GetTempPath(),Creation,Marker;
public static RebirthGearPreparationIntent Intent;public static RebirthGearInventorySnapshot Image,SavedImage;public static float SavedPhase;public static int Saves,Sends,RetiredCalls;public static bool ThrowSend,ThrowMatch;public static Action SaveAction,SendAction,RetiredAction;}
public class Program{
static int checks;static void C(bool b,string n){if(!b)throw new Exception(n);checks++;}
static void Main(){foreach(var creation in new[]{Guid.NewGuid().ToString("N"),"legacy-"+new string('a',64)}){
var worldGuid=Guid.NewGuid();var player=new EntityPlayerLocal();var peer=new Peer();var world=new World{Player=player,Entity=player};player.world=world;
var image=new RebirthGearInventorySnapshot{Bag=Enumerable.Range(0,52).Select(_=>new RebirthGearInventoryPlan.Stack()).ToArray(),Belt=Enumerable.Range(0,4).Select(_=>new RebirthGearInventoryPlan.Stack()).ToArray(),OwnedBeltSlots=4};
RebirthGearPreparationIntent.TryCreateUnequip(creation,Guid.NewGuid(),3,"backpack",image,out var intent);RebirthGearPreparationMarker.TryEncode(worldGuid,4,intent,out var marker);RebirthGearPreparationRefusal.TryCreateStale(marker,5,out var refusal);var receipt="rbGear_"+intent.TransactionId.ToString("N");PacketTests.Run(refusal);
void Reset(){RebirthGearPreparationRefusalClient.Reset();D.Main=D.Mode=D.Owner=D.Hold=D.Capture=D.File=D.Publish=true;D.Offer=D.Rejected=D.Retired=D.ThrowSave=D.CreationHold=false;D.Canonical="owner";D.WorldGuid=worldGuid.ToString("N");D.Creation=creation;D.Marker=marker;D.Intent=intent;D.Image=D.SavedImage=image;D.SavedPhase=0;D.Saves=D.Sends=D.RetiredCalls=0;D.ThrowSend=D.ThrowMatch=false;D.SaveAction=D.SendAction=D.RetiredAction=null;D.Root=System.IO.Path.GetTempPath();world.worldState=new(){Guid=D.WorldGuid};world.Remote=true;world.Entity=world.Player=player;player.world=world;player.Dead=false;player.Spawned=true;player.Buffs=new();player.Buffs.CVars[marker]=1;peer.Dead=false;GameManager.Instance=new(){World=world};SingletonMonoBehaviour<ConnectionManager>.Instance=new(){connectionToServer=new[]{peer}};}
bool Accept()=>RebirthGearPreparationRefusalClient.Receive(world,7,refusal);
bool Persist()=>RebirthGearPreparationRefusalOwnerCheckpoint.TryPersist(player,peer,refusal);
Reset();ReservationTest.Run(player,peer,worldGuid,intent);Reset();C(!RebirthGearPreparationRefusalFlow.TryAdvance(player,peer),"flow no refusal false");
Reset();C(Accept(),"flow earlyexception setup");D.ThrowMatch=true;C(!RebirthGearPreparationRefusalFlow.TryAdvance(player,peer)&&D.Hold,"flow prerelevant exception false");Reset();C(Accept(),"flow initial accepted");C(RebirthGearPreparationRefusalFlow.TryAdvance(player,peer)&&D.Sends==2&&D.Hold&&player.Buffs.CVars.ContainsKey(marker)&&player.Buffs.GetCustomVar(receipt)==-1,"flow reject save before sends retains marker");C(RebirthGearPreparationRefusalFlow.TryAdvance(player,peer)&&D.Sends==4&&D.Saves==1,"flow same original retry no new save");
C(RebirthGearPreparationRefusalClient.ReceiveAcknowledged(world,7,refusal),"flow ack");C(RebirthGearPreparationRefusalFlow.TryAdvance(player,peer)&&!D.Hold&&!player.Buffs.CVars.ContainsKey(marker),"flow acknowledgment retirement release");
Reset();C(Accept(),"flow send throw setup");D.ThrowSend=true;C(RebirthGearPreparationRefusalFlow.TryAdvance(player,peer)&&D.Hold&&player.Buffs.CVars.ContainsKey(marker)&&D.Sends==1,"flow send exception keeps custody");
Reset();C(Accept(),"flow context send setup");D.SendAction=()=>{SingletonMonoBehaviour<ConnectionManager>.Instance.connectionToServer=new[]{new Peer()};};C(RebirthGearPreparationRefusalFlow.TryAdvance(player,peer)&&D.Sends==1&&D.Hold,"flow context change prevents second send");
Reset();C(Accept()&&Persist()&&RebirthGearPreparationRefusalClient.ReceiveAcknowledged(world,7,refusal),"flow mutation setup");D.Retired=true;D.RetiredAction=()=>{if(D.RetiredCalls>=2)player.Buffs.CVars["_rbgearintent_foreign"]=1;};var handled=RebirthGearPreparationRefusalFlow.TryAdvance(player,peer);C(handled&&D.Hold&&player.Buffs.CVars.ContainsKey("_rbgearintent_foreign"),"final witness foreign family blocks release");Reset();C(Accept()&&Persist()&&RebirthGearPreparationRefusalClient.ReceiveAcknowledged(world,7,refusal),"receipt mutation setup");D.Retired=true;D.RetiredAction=()=>{if(D.RetiredCalls>=2)player.Buffs.CVars[receipt]=0;};C(RebirthGearPreparationRefusalFlow.TryAdvance(player,peer)&&D.Hold,"final witness receipt mutation blocks release");Reset();var rejectPacket=new NetPackageRebirthGearPreparationRefusal().Setup(7,refusal,false);rejectPacket.ProcessPackage(world,new GameManager());C(!RebirthGearPreparationRefusalClient.TryGetCurrent(player,peer,out _),"packet wrong callbacks refuse dispatch");rejectPacket.ProcessPackage(world,GameManager.Instance);C(RebirthGearPreparationRefusalClient.TryGetCurrent(player,peer,out _),"packet rejection dispatch caches");C(Persist(),"packet ack setup rejected save");new NetPackageRebirthGearPreparationRefusal().Setup(7,refusal,true).ProcessPackage(world,GameManager.Instance);C(RebirthGearPreparationRefusalClient.TryGetAcknowledged(player,peer,out _),"packet distinct ack dispatch");Reset();C(Accept(),"cache accepts exact original");C(RebirthGearPreparationRefusalClient.TryGetCurrent(player,peer,out var accepted)&&accepted.OriginalMarker==marker,"cache exact current");C(Accept(),"cache duplicate exact");
C(Persist()&&D.Saves==1&&player.Buffs.GetCustomVar(receipt)==-1&&player.Buffs.CVars.ContainsKey(marker)&&D.Hold,"checkpoint saves metadata keeps hold");
Reset();C(Accept(),"accept uncertain");D.ThrowSave=true;D.Publish=false;C(!Persist()&&D.Saves==1&&D.Hold&&player.Buffs.GetCustomVar(receipt)==-1&&player.Buffs.CVars.ContainsKey(marker),"uncertain stages hold");D.ThrowSave=false;D.Publish=true;C(Persist()&&D.Saves==2,"retry same metadata save");
Reset();C(Accept(),"accept false final");D.Publish=false;C(!Persist()&&D.Saves==1,"final witness false");
Reset();C(Accept(),"accept rejected checkpoint");C(Persist()&&player.Buffs.CVars.ContainsKey(marker),"preack marker retained");C(!RebirthGearPreparationRefusalOwnerCheckpoint.TryPersistRetirement(player,peer,refusal)&&D.Saves==1,"retirement blocked without ack");C(RebirthGearPreparationRefusalClient.ReceiveAcknowledged(world,7,refusal),"ack admits saved rejected marker");C(RebirthGearPreparationRefusalOwnerCheckpoint.TryPersistRetirement(player,peer,refusal)&&D.Retired&&!player.Buffs.CVars.ContainsKey(marker)&&D.Saves==2,"ack then exact retirement");C(RebirthGearPreparationRefusalClient.ReceiveAcknowledged(world,7,refusal),"ack duplicate after retirement cache only");
Reset();C(Accept()&&Persist(),"retirement uncertain setup");C(RebirthGearPreparationRefusalClient.ReceiveAcknowledged(world,7,refusal),"retirement uncertain ack");D.ThrowSave=true;D.Publish=false;C(!RebirthGearPreparationRefusalOwnerCheckpoint.TryPersistRetirement(player,peer,refusal)&&D.Hold&&!player.Buffs.CVars.ContainsKey(marker)&&player.Buffs.GetCustomVar(receipt)==-1,"retirement uncertain staged keeps hold");D.ThrowSave=false;D.Publish=true;C(RebirthGearPreparationRefusalOwnerCheckpoint.TryPersistRetirement(player,peer,refusal)&&D.Saves==3,"retirement retry same ack");
Reset();C(Accept()&&Persist(),"cold rejected setup");RebirthGearPreparationRefusalClient.Reset();C(RebirthGearPreparationRefusalClient.ReceiveAcknowledged(world,7,refusal)&&player.Buffs.CVars.ContainsKey(marker),"fresh cache rejected original ack remains cold recoverable under hold adapter");foreach(var fault in new[]{"phase1","phase2","nomarker","foreignzero","casekey","savedphase","offer","savedimage","liveimage","owner"}){
Reset();C(Accept(),"accept preflight "+fault);switch(fault){case "phase1":player.Buffs.CVars[receipt]=1;break;case "phase2":player.Buffs.CVars[receipt]=2;break;case "nomarker":player.Buffs.RemoveCustomVar(marker);break;case "foreignzero":player.Buffs.CVars["_rbgearintent_foreign"]=0;break;case "casekey":player.Buffs.CVars[marker.ToUpperInvariant()]=1;break;case "savedphase":D.SavedPhase=1;break;case "offer":D.Offer=true;break;case "savedimage":D.SavedImage=null;break;case "liveimage":D.Image=null;break;case "owner":D.Canonical="other";break;}
C(!Persist()&&D.Saves==0,"checkpoint refuses "+fault);}
foreach(var change in new[]{"world","session","image","root","stateGuid","creation","dead"}){
Reset();C(Accept(),"accept changed "+change);D.SaveAction=()=>{switch(change){case "world":GameManager.Instance.World=new();break;case "session":SingletonMonoBehaviour<ConnectionManager>.Instance.connectionToServer=new[]{new Peer()};break;case "image":D.Image=null;break;case "root":D.Root=System.IO.Path.Combine(D.Root,"other");break;case "stateGuid":world.worldState.Guid=Guid.NewGuid().ToString();break;case "creation":D.Creation=Guid.NewGuid().ToString("N");break;case "dead":player.Dead=true;break;}};
C(!Persist()&&D.Saves==1,"checkpoint post-save rejects "+change);}
Reset();D.Offer=true;C(!Accept(),"cache no offer");Reset();D.SavedPhase=1;C(!Accept(),"cache saved phase");Reset();D.WorldGuid=Guid.NewGuid().ToString();C(!Accept(),"cache world");Reset();C(Accept(),"cache accept before session replacement");SingletonMonoBehaviour<ConnectionManager>.Instance.connectionToServer=new[]{new Peer()};C(!RebirthGearPreparationRefusalClient.TryGetCurrent(player,peer,out _),"cache foreign session");Reset();C(Accept(),"cache accept before reset");RebirthGearPreparationRefusalClient.Reset();C(!RebirthGearPreparationRefusalClient.TryGetCurrent(player,peer,out _),"cache reset");
}Console.WriteLine("PACKET PASS "+PacketTests.Count);Console.WriteLine("RESERVATION PASS "+ReservationTest.Count);Console.WriteLine("PASS "+checks+" actual whole refusal client cache + owner checkpoint; native reservation/file/capture/save adapters; no publication proof");}}
