// TOOLS ONLY: immutable stage, not paid attribution promotion/save/ordinary-event authority.
sealed class PendingPaidAttribution {
 public sealed record Cell(string NativeImage,int Count);
 public sealed class Transition {
  public string OriginalMutation {get;}public int Quantity {get;}readonly Cell[] before,after;
  internal Transition(string original,int quantity,Cell[] b,Cell[] a){OriginalMutation=original;Quantity=quantity;before=(Cell[])b.Clone();after=(Cell[])a.Clone();}
  public Cell[] Before()=>(Cell[])before.Clone();public Cell[] After()=>(Cell[])after.Clone();
 }
 public sealed class PromotionRequirements {
  public string Job{get;}public string Creation{get;}public string Owner{get;}public string World{get;}public string Root{get;}public string Iteration{get;}public int PaidQuantity{get;}public int OrdinaryTransitionCount{get;}
  public bool RequiresOriginalIterationProducer=>true;public bool RequiresAuthenticatedOrdinaryTransitionChain=>true;public bool RequiresExactSavedCompletionProjectionPair=>true;public bool RequiresFinalNativeRegionOutputMatch=>true;public bool RequiresPendingLedgerFinalSave=>true;
  readonly Cell[] final;internal PromotionRequirements(PendingPaidAttribution stage){var o=stage.completed.Original;Job=o.Admission.JobId;Creation=o.Admission.CreationId;Owner=o.Identity.StorageKey;World=o.WorldGuid;Root=o.SaveRoot;Iteration=stage.Iteration;PaidQuantity=stage.PaidQuantity;OrdinaryTransitionCount=stage.chain.Length;final=(Cell[])stage.tail.Clone();}public Cell[] ExpectedFinalOutput()=>(Cell[])final.Clone();
 }
 readonly RebirthStationCompletionCapture.SuccessfulOutput completed;readonly Cell[] paidBefore,paidAfter,tail;readonly CraftCompleteData receipt;readonly Transition[] chain;
 public string Iteration{get;}public int PaidQuantity{get;}public string Job=>completed.Original.Admission.JobId;
 PendingPaidAttribution(RebirthStationCompletionCapture.SuccessfulOutput e,string iteration,Cell[] before,Cell[] after,CraftCompleteData receipt,Transition[] chain,Cell[] tail){completed=e;Iteration=iteration;paidBefore=(Cell[])before.Clone();paidAfter=(Cell[])after.Clone();this.receipt=receipt;PaidQuantity=receipt.CraftedItemStack.count;this.chain=(Transition[])chain.Clone();this.tail=(Cell[])tail.Clone();}
 static bool Id(string s)=>s!=null&&s.Length>0&&s.Length<=256&&s.Trim()==s&&!s.Any(char.IsControl);
 static bool Freeze(ItemStack[] native,ref int budget,out Cell[] cells,out ItemStack[] snapshots){cells=null;snapshots=null;try{if(native==null||native.Length<1||native.Length>255)return false;var copy=new Cell[native.Length];var frozen=new ItemStack[native.Length];for(int i=0;i<native.Length;i++){var s=native[i];if(s?.itemValue==null||s.count<0||s.count>65535)return false;var c=s.Clone();if(!RebirthStationGridIngredients.IsSameStackSnapshot(s,c))return false;string image=RebirthNativeItemCodec.Encode(c.itemValue);if(image.Length<1||image.Length>262144||(budget-=image.Length)<0||!RebirthStationGridIngredients.IsSameStackSnapshot(s,c))return false;copy[i]=new(image,c.count);frozen[i]=c;}if(!Stable(native,frozen))return false;cells=copy;snapshots=frozen;return true;}catch{return false;}}
 static bool Stable(ItemStack[] native,ItemStack[] frozen){if(native==null||frozen==null||native.Length!=frozen.Length)return false;for(int i=0;i<native.Length;i++)if(!RebirthStationGridIngredients.IsSameStackSnapshot(native[i],frozen[i]))return false;return true;}
 static bool Same(Cell[] left,Cell[] right)=>left!=null&&right!=null&&left.SequenceEqual(right);
 public Cell[] PaidBefore()=>(Cell[])paidBefore.Clone();public Cell[] PaidAfter()=>(Cell[])paidAfter.Clone();public Cell[] CurrentPhysicalTail()=>(Cell[])tail.Clone();public Transition[] OrdinaryTransitions()=>(Transition[])chain.Clone();
 public static bool TryStage(RebirthStationCompletionCapture.SuccessfulOutput original,string originalIteration,out PendingPaidAttribution stage){stage=null;try{if(original==null||!Id(originalIteration)||!original.TryCopyPhysicalDelta(out var before,out var after,out var receipt)||!original.Original.IsCurrent())return false;int budget=8*1024*1024;if(!Freeze(before,ref budget,out var b,out var bf)||!Freeze(after,ref budget,out var a,out var af)||!original.TryCopyPhysicalDelta(out var b2,out var a2,out var r2)||!RebirthStationOutputDelta.Matches(b2,a2,r2)||!original.Original.IsCurrent())return false;int secondBudget=8*1024*1024;if(!Freeze(b2,ref secondBudget,out var stableBefore,out var b2f)||!Freeze(a2,ref secondBudget,out var stableAfter,out var a2f)||!Same(b,stableBefore)||!Same(a,stableAfter)||receipt.CrafterEntityID!=r2.CrafterEntityID||receipt.RecipeName!=r2.RecipeName||receipt.ItemScrapped!=r2.ItemScrapped||receipt.CraftExpGain!=r2.CraftExpGain||receipt.RecipeUsedCount!=r2.RecipeUsedCount||!RebirthStationGridIngredients.IsSameStackSnapshot(receipt.CraftedItemStack,r2.CraftedItemStack)||!original.Original.IsCurrent()||!original.MatchesReceipt())return false;if(!Stable(before,bf)||!Stable(after,af)||!Stable(b2,b2f)||!Stable(a2,a2f)||!original.Original.IsCurrent()||!original.MatchesReceipt())return false;stage=new(original,originalIteration,b,a,receipt,Array.Empty<Transition>(),a);return true;}catch{return false;}}
 public bool SameOriginal(PendingPaidAttribution other)=>other!=null&&ReferenceEquals(completed,other.completed)&&Iteration==other.Iteration&&Same(paidBefore,other.paidBefore)&&Same(paidAfter,other.paidAfter);
 // Supplied ordinary before/after DATA; does not authenticate native unmarked/cooking producer.
 public bool TryAppendDetachedOrdinaryAddition(string originalMutation,ItemStack[] before,ItemStack[] after,out PendingPaidAttribution next){next=null;try{if(!Id(originalMutation)||chain.Length>=64||chain.Any(x=>x.OriginalMutation==originalMutation)||!completed.Original.IsCurrent()||!completed.MatchesReceipt())return false;int budget=8*1024*1024;if(!Freeze(before,ref budget,out var b,out var bf)||!Freeze(after,ref budget,out var a,out var af)||!Same(b,tail)||a.Length!=b.Length)return false;long quantity=0;for(int i=0;i<b.Length;i++){if(a[i]==b[i])continue;if(a[i].Count<=b[i].Count||b[i].Count>0&&a[i].NativeImage!=b[i].NativeImage)return false;quantity+=(long)a[i].Count-b[i].Count;}if(quantity<1||quantity>65535)return false;long retained=paidBefore.Sum(c=>(long)c.NativeImage.Length)+paidAfter.Sum(c=>(long)c.NativeImage.Length)+b.Sum(c=>(long)c.NativeImage.Length)+a.Sum(c=>(long)c.NativeImage.Length);foreach(var t in chain)retained+=t.Before().Sum(c=>(long)c.NativeImage.Length)+t.After().Sum(c=>(long)c.NativeImage.Length);if(retained>8*1024*1024||!completed.Original.IsCurrent()||!completed.MatchesReceipt())return false;if(!Stable(before,bf)||!Stable(after,af)||!completed.Original.IsCurrent()||!completed.MatchesReceipt())return false;var transitions=new Transition[chain.Length+1];Array.Copy(chain,transitions,chain.Length);transitions[^1]=new(originalMutation,(int)quantity,b,a);next=new(completed,Iteration,paidBefore,paidAfter,receipt,transitions,a);return true;}catch{return false;}}
 public bool TryDescribePromotionRequirements(ItemStack[] finalObserved,out PromotionRequirements requirements){requirements=null;try{int budget=8*1024*1024;if(!completed.Original.IsCurrent()||!completed.MatchesReceipt()||!Freeze(finalObserved,ref budget,out var observed,out var ff)||!Same(observed,tail)||!completed.Original.IsCurrent()||!completed.MatchesReceipt())return false;if(!Stable(finalObserved,ff)||!completed.Original.IsCurrent()||!completed.MatchesReceipt())return false;requirements=new(this);return true;}catch{return false;}}
}


