$ErrorActionPreference='Stop'
$root=(Resolve-Path "$PSScriptRoot/../..").Path
$native='C:/Program Files (x86)/Steam/steamapps/common/7 Days To Die/Data/Config/XUi_InGame'
$out=Join-Path $PSScriptRoot out;[IO.Directory]::CreateDirectory($out)|Out-Null
$script:checks=0
function Assert($ok,[string]$label){$script:checks++;if(!$ok){throw $label}}
function Apply([xml]$target,[Xml.XmlNode]$node,[string]$file,[string]$mode){
if($node.NodeType -ne [Xml.XmlNodeType]::Element){return}
switch($node.LocalName){
'conditional'{$matched=$false;foreach($part in $node.ChildNodes){if($part.NodeType -ne [Xml.XmlNodeType]::Element){continue};if($part.LocalName -eq 'if'){$condition=$part.GetAttribute('cond');if($condition -ne "character_progression('Rebirth')"){throw "Unknown condition $condition"};$selected=$mode -eq 'Rebirth';$matched=$selected}elseif($part.LocalName -eq 'else'){$selected=!$matched}else{throw "Unsupported conditional branch $($part.LocalName)"};if($selected){foreach($child in $part.ChildNodes){Apply $target $child $file $mode}}};return}
'include'{$included=[IO.Path]::GetFullPath((Join-Path (Split-Path $file) $node.GetAttribute('filename')));$script:includes.Add($included);[xml]$patch=[IO.File]::ReadAllText($included);foreach($child in $patch.DocumentElement.ChildNodes){Apply $target $child $included $mode};return}
}
$targets=@($target.SelectNodes($node.GetAttribute('xpath')));$script:operations++;if($targets.Count -eq 0){$script:unmatched++;$script:misses.Add($file+" :: "+$node.GetAttribute("xpath"))}
switch($node.LocalName){
'append'{foreach($t in $targets){foreach($child in $node.ChildNodes){if($child.NodeType -eq [Xml.XmlNodeType]::Element){[void]$t.AppendChild($target.ImportNode($child,$true))}}}}
'remove'{foreach($t in $targets){if($t -is [Xml.XmlAttribute]){$t.OwnerElement.RemoveAttributeNode($t)|Out-Null}else{[void]$t.ParentNode.RemoveChild($t)}}}
'removeattribute'{foreach($t in $targets){if($t -is [Xml.XmlAttribute]){[void]$t.OwnerElement.RemoveAttributeNode($t)}else{$t.RemoveAttribute($node.GetAttribute('name'))}}}
'setattribute'{foreach($t in $targets){$t.SetAttribute($node.GetAttribute('name'),$node.InnerText)}}
'set'{foreach($t in $targets){if($t -is [Xml.XmlAttribute]){$t.Value=$node.InnerText}else{$t.InnerXml=$node.InnerXml}}}
'insertAfter'{foreach($t in $targets){$prev=$t;foreach($child in $node.ChildNodes){if($child.NodeType -eq [Xml.XmlNodeType]::Element){$prev=$t.ParentNode.InsertAfter($target.ImportNode($child,$true),$prev)}}}}
'insertBefore'{foreach($t in $targets){foreach($child in $node.ChildNodes){if($child.NodeType -eq [Xml.XmlNodeType]::Element){[void]$t.ParentNode.InsertBefore($target.ImportNode($child,$true),$t)}}}}
default{throw "Unsupported patch operation $($node.LocalName) in $file"}
}
}
function Effective([string]$name,[string]$mode){$script:includes=[Collections.Generic.List[string]]::new();$script:operations=0;$script:unmatched=0;$script:misses=[Collections.Generic.List[string]]::new();[xml]$d=[IO.File]::ReadAllText((Join-Path $native $name));$path=Join-Path $root ('Config/XUi_InGame/'+$name);[xml]$patch=[IO.File]::ReadAllText($path);foreach($n in $patch.DocumentElement.ChildNodes){Apply $d $n $path $mode};$d.Save((Join-Path $out ($mode+'_'+$name)));return $d}
$report=[Collections.Generic.List[string]]::new()
foreach($mode in @('Base','Rebirth')){
$windows=Effective 'windows.xml' $mode;$wi=$script:includes.Count;$wo=$script:operations;$wu=$script:unmatched;$windowMisses=@($script:misses)
$xui=Effective 'xui.xml' $mode;$group=$xui.SelectSingleNode("/xui/window_group[@name='questTurnIn']");Assert ($group -ne $null) 'Native questTurnIn group exists';$children=@($group.SelectNodes('./window'));$workspace=$windows.SelectSingleNode("/windows/window[@name='rebirthQuestTurnInRoot']")
if($mode -eq 'Rebirth'){
Assert ($group.controller -eq 'RebirthQuestTurnInWorkspace, RebirthUtils') 'Effective Rebirth group routing';Assert ($group.open_backpack_on_open -eq 'false') 'Separate backpack disabled';Assert ($children.Count -eq 1 -and $children[0].name -eq 'rebirthQuestTurnInRoot') 'Exactly one effective workspace';Assert ($workspace -ne $null) 'Effective workspace window exists';Assert ($windows.SelectNodes("/windows/window[@name='rebirthQuestTurnInRoot']").Count -eq 1) 'No duplicate workspace';Assert ($workspace.width -eq '1872' -and $workspace.height -eq '850') 'Wide authored root'
$rewards=$workspace.SelectSingleNode("rect[@name='questRewards']");$grid=$rewards.SelectSingleNode("rect[@name='rectOptions']/grid[@name='gridOptions']");$entries=@($grid.SelectNodes("rect[@controller='QuestTurnInEntry']"));Assert ($entries.Count -eq 7 -and $grid.rows -eq '7') 'Seven effective native choices';Assert ($grid.cell_height -eq '46') '46px row pitch';$last=$entries[-1];$lastBottom=158+6*46+[int]$last.height;Assert ($lastBottom -le 486) 'Last reward ends before claim footer';Assert (([int]$rewards.width) -eq 754) 'Wide reward column';Assert ($rewards.SelectSingleNode("rect[@name='rectAccept']/rect[@name='btnAccept']/button[@name='clickable']") -ne $null) 'Native claim path'
foreach($name in @('questDescription','questRewards','questItemInfo','questEmptyInfo','rebirthCraftingInventoryRegion')){$r=$workspace.SelectSingleNode("rect[@name='$name']");Assert ($r -ne $null) "Major region $name exists";$pos=$r.pos.Split(',');Assert (([int]$pos[0]+[int]$r.width) -le 1872) "$name right edge inside root";Assert ((-[int]$pos[1]+[int]$r.height) -le 850) "$name bottom inside root"}
$details=$workspace.SelectSingleNode("rect[@name='questItemInfo']");Assert ($details.width -eq '1070') '1070px details matching backpack';Assert ($details.controller -eq 'RebirthQuestDetails, RebirthUtils') 'Scoped detail controller';$inventory=$workspace.SelectSingleNode("rect[@name='rebirthCraftingInventoryRegion']");Assert ($inventory.width -eq '1070') 'Matching inventory column';$header=$workspace.SelectSingleNode("rect[@name='questDescription']/rect[@name='header']/label[@style='header.name']");Assert ($header.width -eq '686') 'Quest title widened alongside header';foreach($name in @('rbBackpackTheorySection','rbBackpackSellSection','btnRebirthCraftingInventorySort','btnRebirthCraftingInventoryLock')){Assert ($inventory.SelectSingleNode("button[@name='$name']") -ne $null) "$name accessible"}
$report.Add("Rebirth native reward choices=$($entries.Count), final row bottom=$lastBottom, footer starts486, root1872x850, left754/right1070. Effective journal windowQuestRewards width=$($windows.SelectSingleNode("/windows/window[@name='windowQuestRewards']").width) is separately routed.")
}else{Assert ($workspace -eq $null) 'Base does not acquire Rebirth workspace';Assert ($group.controller -ne 'RebirthQuestTurnInWorkspace, RebirthUtils') 'Base keeps native group';Assert ($children.Count -gt 1) 'Base native multiple windows retained'}
foreach($miss in $windowMisses){$report.Add("Unmatched: $miss")};$report.Add("$mode windows operations=$wo unmatched=$wu includes=$wi; xui operations=$script:operations unmatched=$script:unmatched includes=$($script:includes.Count). Unmatched historical patches logged, not treated as effective changes.")
}
$trader=[xml][IO.File]::ReadAllText((Join-Path $root 'Config/XUi_InGame/trader_workspace.xml'));$quest=[xml][IO.File]::ReadAllText((Join-Path $root 'Config/XUi_InGame/quest_turnin_workspace.xml'))
foreach($name in @('selectedName','selectedDescription','traderStat1')){$a=$trader.SelectSingleNode("//*[@name='$name']");$b=$quest.SelectSingleNode("//*[@name='$name']");Assert ($a.width -eq $b.width -and $a.height -eq $b.height -and $a.pos -eq $b.pos) "Established trader detail geometry $name reused"}
foreach($screen in @(@(1920,1080),@(1600,900),@(1280,720),@(960,540))){$top=[Math]::Min(20,[Math]::Max(8,[Math]::Round($screen[1]*.012)));$width=[Math]::Min(1872,$screen[0]-4);$height=[Math]::Min(935,$screen[1]-$top-132);$scale=[Math]::Min($width/1872.0,$height/850.0);Assert (1872*$scale -le $width+.01 -and 850*$scale -le $height+.01) 'Offline uniform fit';$report.Add("Logical screen $($screen[0])x$($screen[1]): modeled min reserve132 scale=$([Math]::Round($scale,3)),23px reward text=>$([Math]::Round(23*$scale,1))px. Native UI scale/actual vitals reserve can differ; this is algebra only.")}
[xml]$quests=[IO.File]::ReadAllText((Join-Path (Split-Path $native) 'quests.xml'));$questFile=Join-Path $root 'Config/quests.xml';[xml]$questPatch=[IO.File]::ReadAllText($questFile);foreach($n in $questPatch.DocumentElement.ChildNodes){Apply $quests $n $questFile 'Rebirth'}
$max=2;foreach($p in $quests.SelectNodes("/quests/quest/property[@name='reward_choices_count']")){$max=[Math]::Max($max,[int]$p.value)}
Assert ($max -eq 5) 'Effective authored reward base maximum5';$wave=[IO.File]::ReadAllText((Join-Path $root 'Scripts/Survivor/Progression/RebirthSkillWaveAService.cs'));Assert ($wave.Contains('TradingRewardOptionCVar, trading + 0.0001f >= RebirthProgressionRuntimeConfig.TradingRewardOptionThreshold ? 1f : 0f') -and $wave.Contains('SalespersonRewardOptionCVar, salesperson ? 1f : 0f')) 'Actual bonuses individually bounded1';Assert ($max+2 -eq 7) 'Current two bonuses fit seven rows';[xml]$progression=[IO.File]::ReadAllText((Join-Path (Split-Path $native) 'progression.xml'));Assert ($progression.SelectNodes("//passive_effect[@name='QuestRewardOptionCount']").Count -eq 0) 'No native progression option passive';$report.Add('Effective authored base option max5 + Trading1 + Salesperson1 =7. Native DaringAdventurer has claim ChoiceCount, no OptionCount. Native controller cap still requires review if future effects/quests exceed7.')
$report.Add("PASS $script:checks independent effective XML/layout checks; no native render/claims/game validation.");$report|Tee-Object (Join-Path $out 'RESULT.txt')