using System;
public static partial class Program{
static int confirmChecks;
static void ConfirmTests(RebirthWorldSupportState original,string creation,RebirthGearPreparationRefusal refusal,RebirthGearInventorySnapshot image){
void C(bool b,string n){Check(b,n);confirmChecks++;}
var sender=new ClientInfo();var player=new EntityPlayer();
void Reset(){ServerDoubles.Main=ServerDoubles.Resolve=ServerDoubles.Identity=ServerDoubles.Upload=ServerDoubles.Base=ServerDoubles.Final=true;ServerDoubles.ThrowSave=false;ServerDoubles.Owner=new();ServerDoubles.Peer=new();ServerDoubles.Image=image;ServerDoubles.Record=new(){Support=original.Clone(),Origin=new(){CreationId=creation}};ServerDoubles.Record.Support.PendingGearPreparationRefusal=refusal;ServerDoubles.Record.Support.LastGearPreparationRefusal=null;ServerDoubles.DuringSave=null;ServerDoubles.Saves=0;sender.latestPlayerData=new();RebirthGearNativePlayerFile.Valid=true;RebirthGearNativePlayerFile.Value=new();RebirthGearPreparationMarkerReader.Absent=false;RebirthGearReceiptReader.Rejected=true;ServerDoubles.Marker=refusal.OriginalMarker;RebirthGearPreparationMarker.TryRead(refusal.OriginalMarker,1,out _,out _,out ServerDoubles.Intent);GameManager.Instance=new(){World=new(){worldState=new(){Guid=refusal.SavedWorld.ToString("N")}}};SingletonMonoBehaviour<ConnectionManager>.Instance=new(){Clients=new(){Sender=sender}};}
bool Run(out RebirthGearPreparationRefusal result)=>RebirthRemoteGearRefusalRetirement.TryConfirm(player,sender,refusal.OriginalMarker,out result);
Reset();var support=ServerDoubles.Record.Support;C(Run(out var result)&&ReferenceEquals(result,refusal)&&support.PendingGearPreparationRefusal==null&&ReferenceEquals(support.LastGearPreparationRefusal,refusal)&&support.GearRevision==5&&ServerDoubles.Saves==1,"confirm exact transition no revision");
Reset();ServerDoubles.Base=false;C(!Run(out result)&&result==null&&ReferenceEquals(ServerDoubles.Record.Support.PendingGearPreparationRefusal,refusal)&&ServerDoubles.Saves==0,"confirm base no stage");
Reset();ServerDoubles.Final=false;ServerDoubles.ThrowSave=true;C(!Run(out result)&&result==null&&ServerDoubles.Record.Support.PendingGearPreparationRefusal==null&&ReferenceEquals(ServerDoubles.Record.Support.LastGearPreparationRefusal,refusal),"confirm uncertain same terminal");ServerDoubles.ThrowSave=false;ServerDoubles.Final=true;C(Run(out result)&&ReferenceEquals(result,refusal)&&ServerDoubles.Record.Touches==2&&ServerDoubles.Saves==2,"confirm retry touches");
Reset();RebirthGearPreparationMarkerReader.Absent=true;C(!Run(out result)&&ServerDoubles.Saves==0,"initial retired absent refuses without terminal");ServerDoubles.Record.Support.PendingGearPreparationRefusal=null;ServerDoubles.Record.Support.LastGearPreparationRefusal=refusal;C(Run(out result)&&ReferenceEquals(result,refusal),"existing saved terminal admits retired retransmit");foreach(var fault in new[]{"file","marker","receipt","uploadednull","image","revision","pending","sender","peer"}){
Reset();switch(fault){case "file":RebirthGearNativePlayerFile.Valid=false;break;case "marker":RebirthGearPreparationMarkerReader.Absent=true;break;case "receipt":RebirthGearReceiptReader.Rejected=false;break;case "uploadednull":sender.latestPlayerData=null;break;case "image":ServerDoubles.Image=null;break;case "revision":ServerDoubles.Record.Support.GearRevision++;break;case "pending":ServerDoubles.Record.Support.PendingMusicTransfer=new();break;case "sender":SingletonMonoBehaviour<ConnectionManager>.Instance.Clients.Sender=new();break;case "peer":ServerDoubles.Peer.StorageKey="foreign";break;}C(!Run(out result)&&result==null&&ServerDoubles.Saves==0,"confirm preflight "+fault);}
foreach(var change in new[]{"upload","revision","world","record","receipt","image"}){
Reset();ServerDoubles.DuringSave=()=>{switch(change){case "upload":sender.latestPlayerData=new();break;case "revision":ServerDoubles.Record.Support.GearRevision++;break;case "world":GameManager.Instance.World=new();break;case "record":ServerDoubles.Record=new(){Support=original.Clone()};break;case "receipt":RebirthGearReceiptReader.Rejected=false;break;case "image":ServerDoubles.Image=null;break;}};C(!Run(out result)&&result==null&&ServerDoubles.Saves==1,"confirm post-save "+change);}
}
}
