using System;
public class EntityPlayerLocal{public World world;public int entityId=7;public Buffs Buffs=new();public int Adjustments;public bool Suppress;public void AdjustItemsForSandboxOptions(){if(RebirthGearSandboxAdjustmentDeferral.AllowNative(this)&&!Suppress){Adjustments++;RebirthGearSandboxAdjustmentDeferral.NativeCompleted(this,true);}else RebirthGearSandboxAdjustmentDeferral.NativeCompleted(this,false);}public bool Dead;public bool IsSpawned()=>true;public bool IsDead()=>Dead;}
public class Buffs{public float Value;public float GetCustomVar(string k)=>Value;}
public class World{public EntityPlayerLocal Player;public bool IsRemote()=>true;public EntityPlayerLocal GetPrimaryPlayer()=>Player;public object GetEntity(int id)=>Player;}
public class GameManager{public static GameManager Instance;public World World;}
public class Connection{public bool IsDisconnected()=>false;}
public class ConnectionManager{public bool IsServer;public Connection[] connectionToServer={new()};}
public static class SingletonMonoBehaviour<T>{public static T Instance;}
public static class ThreadManager{public static bool Main=true;public static bool IsMainThread()=>Main;}
public static class RebirthSurvivorMode{public static bool IsEnabledForCurrentWorld()=>true;}
public static class RebirthSurvivorClientState{public static string Creation=Guid.NewGuid().ToString("N");public static string GetProjectedCreationId(EntityPlayerLocal p)=>Creation;}
public static class RebirthGearOwnerReservation{public static bool Held=true;public static object Initial;public static string HeldCreation;public static bool TryGetHeldOriginalCreation(EntityPlayerLocal p,out string creation){creation=HeldCreation;return creation!=null;}public static bool TryGetInitialIntent(EntityPlayerLocal p,object s,out object original){original=Initial;return original!=null;}public static bool IsHeld(EntityPlayerLocal p)=>Held;}
public class Offer{public long GearRevision;public string TransactionId="a",CreationId=RebirthSurvivorClientState.Creation;}
public static class RebirthGearPreparationClient{public static int Requests,OriginalRequests;public static object LastOriginal;public static bool TryRequestOriginal(EntityPlayerLocal p,object original){OriginalRequests++;LastOriginal=original;return false;}public static bool TryRequestSaved(EntityPlayerLocal p){Requests++;return true;}}
public static class RebirthGearOwnerApplySequence{public enum Result{Applied,Pending}}
public static class RebirthGearOfferClient{public static Offer Offer;public static int Applies,Applied,Rejected,Finishes;public static RebirthGearOwnerApplySequence.Result Result=RebirthGearOwnerApplySequence.Result.Applied;public static bool TryGetCurrentOffer(World w,int id,out Offer o){o=Offer;return o!=null;}public static bool TryFinishCurrentTerminal(World w,int id){Finishes++;return false;}public static bool RequestAppliedConfirmation(World w,int id){Applied++;return true;}public static bool RequestRejectedConfirmation(World w,int id){Rejected++;return true;}public static RebirthGearOwnerApplySequence.Result TryApplyCurrentOffer(World w,int id){Applies++;return Result;}}
public static class RebirthGearTerminalClient{public static Offer Terminal;public static bool TryGetCurrent(EntityPlayerLocal p,out object marker,out Offer t){marker=null;t=Terminal;return t!=null;}}
public static class RebirthBackpackLibraryClientViews{public static bool Available=true;public static long Revision;public static int Requests;public static bool TryGetRevision(World w,int id,out long revision){revision=Available?Revision:-1;return Available;}public static bool Request(World w,int id){Requests++;return true;}}
public static class RebirthBackpackLibraryClientOffers{public static long Revision=-1;public static bool TryGetSettledRevision(World w,int id,out long revision){revision=Revision;return Revision>=0;}}
static class Program{
 static int n;static EntityPlayerLocal p;
 static void Check(bool b,string s){if(!b)throw new Exception(s);n++;}
 static void Setup(){RebirthGearPreparationRefusalClient.Value=null;RebirthGearPreparationRefusalClient.Current=true;RebirthGearPreparationRefusalFlow.Handled=false;RebirthGearPreparationRefusalFlow.Calls=0;RebirthGearPreparationRefusalFlow.Throw=false;RebirthBackpackLibraryClientOffers.Revision=-1;RebirthBackpackLibraryClientViews.Revision=0;RebirthBackpackLibraryClientViews.Available=true;RebirthBackpackLibraryClientViews.Requests=0;RebirthGearClientTransferPump.Reset();RebirthGearSandboxAdjustmentDeferral.Reset();var w=new World();p=new(){world=w};w.Player=p;GameManager.Instance=new(){World=w};SingletonMonoBehaviour<ConnectionManager>.Instance=new();ThreadManager.Main=true;RebirthGearOwnerReservation.Held=true;RebirthGearPreparationClient.Requests=0;RebirthGearPreparationClient.OriginalRequests=0;RebirthGearPreparationClient.LastOriginal=null;RebirthGearOwnerReservation.Initial=null;RebirthGearOwnerReservation.HeldCreation=null;RebirthGearOfferClient.Offer=new();RebirthGearOfferClient.Applies=RebirthGearOfferClient.Applied=RebirthGearOfferClient.Rejected=RebirthGearOfferClient.Finishes=0;RebirthGearOfferClient.Result=RebirthGearOwnerApplySequence.Result.Applied;RebirthGearTerminalClient.Terminal=null;}
 static void Main(){foreach(var observed in new[]{-1L,0L,1L}){Setup();RebirthGearOwnerReservation.Held=false;RebirthGearPreparationRefusalClient.Value=new(){CreationId=RebirthSurvivorClientState.Creation,ObservedRevision=observed};RebirthGearClientTransferPump.Tick();RebirthGearClientTransferPump.Tick();Check(RebirthBackpackLibraryClientViews.Requests==(observed>0?1:0)&&RebirthGearPreparationClient.Requests==0&&RebirthGearPreparationClient.OriginalRequests==0,"actual refusal revision display bounded "+observed);}
Setup();RebirthGearOwnerReservation.Held=false;RebirthGearPreparationRefusalClient.Value=new(){CreationId=System.Guid.NewGuid().ToString("N"),ObservedRevision=9};RebirthGearClientTransferPump.Tick();Check(RebirthBackpackLibraryClientViews.Requests==0,"actual foreign creation hint ignored");
Setup();RebirthGearOwnerReservation.Held=false;RebirthGearPreparationRefusalClient.Value=new(){CreationId=RebirthSurvivorClientState.Creation,ObservedRevision=9};RebirthGearPreparationRefusalClient.Current=false;RebirthGearClientTransferPump.Tick();Check(RebirthBackpackLibraryClientViews.Requests==0,"actual cache scope refusal ignores hint");Setup();RebirthGearOfferClient.Offer=null;RebirthGearPreparationRefusalFlow.Handled=true;RebirthGearClientTransferPump.Tick();Check(RebirthGearPreparationRefusalFlow.Calls==1&&RebirthGearPreparationClient.Requests==0&&RebirthGearPreparationClient.OriginalRequests==0,"candidate refusal before nooffer fallback");
Setup();RebirthGearPreparationRefusalFlow.Handled=true;RebirthGearClientTransferPump.Tick();Check(RebirthGearPreparationRefusalFlow.Calls==0&&RebirthGearOfferClient.Applies==1,"candidate bound offer unchanged");
Setup();RebirthGearOfferClient.Offer=null;RebirthGearPreparationRefusalFlow.Throw=true;RebirthGearClientTransferPump.Tick();Check(RebirthGearOwnerReservation.Held&&RebirthGearPreparationClient.Requests==0,"candidate flowthrow hold no fallback");
Setup();RebirthGearOfferClient.Offer=null;RebirthGearPreparationRefusalFlow.Handled=true;RebirthGearClientTransferPump.Reset();RebirthGearClientTransferPump.Tick();Check(RebirthGearPreparationRefusalFlow.Handled&&RebirthGearPreparationRefusalFlow.Calls==1,"candidate scheduling reset preserves accepted refusal");
 Setup();RebirthGearOwnerReservation.Held=false;RebirthGearClientTransferPump.Tick();Check(RebirthGearOfferClient.Applies==0&&RebirthGearPreparationClient.Requests==0,"ordinary gameplay inert");
 Setup();RebirthGearOfferClient.Offer=null;RebirthGearClientTransferPump.Tick();RebirthGearClientTransferPump.Tick();Check(RebirthGearPreparationClient.Requests==1&&RebirthGearOwnerReservation.Held,"original query bounded and hold retained");
 Setup();RebirthGearOfferClient.Offer=null;var original=new object();RebirthGearOwnerReservation.Initial=original;RebirthGearClientTransferPump.Tick();Check(RebirthGearPreparationClient.OriginalRequests==1&&ReferenceEquals(RebirthGearPreparationClient.LastOriginal,original)&&RebirthGearPreparationClient.Requests==0&&RebirthGearOwnerReservation.Held,"unsaved initial hold retries same original without requiring nonexistent final file");
 Setup();RebirthGearClientTransferPump.Tick();Check(RebirthGearOfferClient.Applies==1&&RebirthGearOfferClient.Applied==1,"untouched original applies then requests confirmation");
 Setup();p.Buffs.Value=2;RebirthGearClientTransferPump.Tick();Check(RebirthGearOfferClient.Applies==1,"mixed original resumes same apply path");
 Setup();p.Buffs.Value=1;RebirthGearClientTransferPump.Tick();Check(RebirthGearOfferClient.Applies==0&&RebirthGearOfferClient.Applied==1,"applied receipt never reapplies");
 Setup();p.Buffs.Value=-1;RebirthGearClientTransferPump.Tick();Check(RebirthGearOfferClient.Applies==0&&RebirthGearOfferClient.Rejected==1,"rejected original requests confirmation");
 Setup();p.Buffs.Value=float.NaN;RebirthGearClientTransferPump.Tick();Check(RebirthGearOfferClient.Applies==0,"unknown receipt refuses writes");
 Setup();RebirthGearTerminalClient.Terminal=RebirthGearOfferClient.Offer;RebirthGearClientTransferPump.Tick();Check(RebirthGearOfferClient.Finishes==1&&RebirthGearOfferClient.Applies==0&&RebirthGearOwnerReservation.Held,"uncertain terminal retirement never reapplies or releases");
 Setup();RebirthGearTerminalClient.Terminal=new Offer{TransactionId="previous"};RebirthGearClientTransferPump.Tick();Check(RebirthGearOfferClient.Applies==1&&RebirthGearOfferClient.Applied==1&&RebirthGearOfferClient.Finishes==0,"previous terminal cannot suppress next original transfer");
 Setup();RebirthGearOfferClient.Result=RebirthGearOwnerApplySequence.Result.Pending;RebirthGearClientTransferPump.Tick();Check(RebirthGearOfferClient.Applied==0&&RebirthGearOwnerReservation.Held,"pending apply retains original hold");
 Setup();p.Dead=true;RebirthGearClientTransferPump.Tick();Check(RebirthGearOfferClient.Applies==0&&RebirthGearOwnerReservation.Held,"death resets scheduling only");
 Setup();ThreadManager.Main=false;RebirthGearClientTransferPump.Tick();Check(RebirthGearOfferClient.Applies==0,"background dispatch inert");
 Setup();Check(!RebirthGearSandboxAdjustmentDeferral.AllowNative(p),"held sandbox metadata change deferred");RebirthGearSandboxAdjustmentDeferral.Tick();Check(p.Adjustments==0,"hold preserves original metadata");RebirthGearOwnerReservation.Held=false;RebirthGearSandboxAdjustmentDeferral.Tick();RebirthGearSandboxAdjustmentDeferral.Tick();Check(p.Adjustments==1,"same original scope native adjustment replays once after custody");
 Setup();RebirthGearSandboxAdjustmentDeferral.AllowNative(p);RebirthGearOwnerReservation.Held=false;SingletonMonoBehaviour<ConnectionManager>.Instance.connectionToServer[0]=new();RebirthGearSandboxAdjustmentDeferral.Tick();Check(p.Adjustments==0,"replaced native peer cannot replay adjustment");
 Setup();RebirthGearSandboxAdjustmentDeferral.AllowNative(p);RebirthGearOwnerReservation.Held=false;var originalCreation=RebirthSurvivorClientState.Creation;RebirthSurvivorClientState.Creation=Guid.NewGuid().ToString("N");RebirthGearSandboxAdjustmentDeferral.Tick();Check(p.Adjustments==0,"replacement character cannot replay adjustment");RebirthSurvivorClientState.Creation=originalCreation;
 Setup();RebirthGearSandboxAdjustmentDeferral.AllowNative(p);RebirthGearOwnerReservation.Held=false;p.Suppress=true;RebirthGearSandboxAdjustmentDeferral.Tick();Check(p.Adjustments==0,"suppressed native body does not complete deferred work");p.Suppress=false;p.AdjustItemsForSandboxOptions();RebirthGearSandboxAdjustmentDeferral.Tick();Check(p.Adjustments==1,"original native completion clears retained deferred work");
 Setup();RebirthGearOwnerReservation.Held=false;Check(RebirthGearSandboxAdjustmentDeferral.AllowNative(p),"ordinary unheld sandbox behavior preserved");
 Setup();var delayedCreation=RebirthSurvivorClientState.Creation;RebirthGearOwnerReservation.HeldCreation=delayedCreation;RebirthSurvivorClientState.Creation="";Check(!RebirthGearSandboxAdjustmentDeferral.AllowNative(p),"unpublished character captures held original adjustment");RebirthGearOwnerReservation.Held=false;RebirthGearSandboxAdjustmentDeferral.Tick();Check(p.Adjustments==0,"unpublished character never authorizes replay");RebirthSurvivorClientState.Creation=delayedCreation;RebirthGearSandboxAdjustmentDeferral.Tick();Check(p.Adjustments==1,"delayed same character publication retains and replays original adjustment");
 Setup();RebirthGearOwnerReservation.Held=false;RebirthBackpackLibraryClientViews.Available=false;RebirthGearClientTransferPump.Tick();RebirthGearClientTransferPump.Tick();Check(RebirthBackpackLibraryClientViews.Requests==1&&RebirthGearPreparationClient.Requests==0&&RebirthGearOfferClient.Applies==0,"unheld missing revision requests display-only bootstrap once");
 Setup();RebirthGearOwnerReservation.Held=false;RebirthGearClientTransferPump.Tick();Check(RebirthBackpackLibraryClientViews.Requests==0,"existing revision stops bootstrap requests");
 Setup();RebirthBackpackLibraryClientViews.Available=false;RebirthGearClientTransferPump.Tick();Check(RebirthBackpackLibraryClientViews.Requests==0&&RebirthGearOfferClient.Applies==1,"held original continues without bootstrap");
 Setup();RebirthGearOwnerReservation.Held=false;RebirthBackpackLibraryClientViews.Available=false;p.Dead=true;RebirthGearClientTransferPump.Tick();Check(RebirthBackpackLibraryClientViews.Requests==0,"dead client cannot bootstrap revision");
 Setup();RebirthGearOwnerReservation.Held=false;RebirthBackpackLibraryClientViews.Available=false;ThreadManager.Main=false;RebirthGearClientTransferPump.Tick();Check(RebirthBackpackLibraryClientViews.Requests==0,"background callback cannot bootstrap revision");
 Setup();RebirthGearOwnerReservation.Held=false;RebirthBackpackLibraryClientViews.Available=false;SingletonMonoBehaviour<ConnectionManager>.Instance.connectionToServer=Array.Empty<Connection>();RebirthGearClientTransferPump.Tick();Check(RebirthBackpackLibraryClientViews.Requests==0,"missing native peer cannot bootstrap revision");
 Setup();RebirthGearOwnerReservation.Held=false;RebirthGearTerminalClient.Terminal=new Offer{GearRevision=1};RebirthGearClientTransferPump.Tick();RebirthGearClientTransferPump.Tick();Check(RebirthBackpackLibraryClientViews.Requests==1&&RebirthGearOfferClient.Applies==0&&RebirthGearPreparationClient.OriginalRequests==0,"newer exact terminal refreshes old revision without custody writes");
 Setup();RebirthGearOwnerReservation.Held=false;RebirthBackpackLibraryClientViews.Revision=1;RebirthGearTerminalClient.Terminal=new Offer{GearRevision=1};RebirthGearClientTransferPump.Tick();Check(RebirthBackpackLibraryClientViews.Requests==0,"matched terminal revision stops refresh");
 Setup();RebirthGearOwnerReservation.Held=false;RebirthBackpackLibraryClientViews.Revision=2;RebirthGearTerminalClient.Terminal=new Offer{GearRevision=1};RebirthGearClientTransferPump.Tick();Check(RebirthBackpackLibraryClientViews.Requests==0,"older terminal never rolls current hint back");
 Setup();RebirthGearOwnerReservation.Held=false;RebirthGearTerminalClient.Terminal=new Offer{GearRevision=9,CreationId=Guid.NewGuid().ToString("N")};RebirthGearClientTransferPump.Tick();Check(RebirthBackpackLibraryClientViews.Requests==0,"foreign character terminal cannot trigger refresh");
 Setup();RebirthGearOwnerReservation.Held=false;RebirthBackpackLibraryClientOffers.Revision=2;RebirthGearClientTransferPump.Tick();RebirthGearClientTransferPump.Tick();Check(RebirthBackpackLibraryClientViews.Requests==1&&RebirthGearPreparationClient.Requests==0&&RebirthGearOfferClient.Applies==0,"newer confirmed library settlement refreshes shared gear hint without mutation");
 Setup();RebirthGearOwnerReservation.Held=false;RebirthBackpackLibraryClientOffers.Revision=2;RebirthBackpackLibraryClientViews.Revision=2;RebirthGearClientTransferPump.Tick();Check(RebirthBackpackLibraryClientViews.Requests==0,"caught up library revision stops refresh");
 Setup();RebirthGearOwnerReservation.Held=false;RebirthBackpackLibraryClientOffers.Revision=1;RebirthBackpackLibraryClientViews.Revision=3;RebirthGearClientTransferPump.Tick();Check(RebirthBackpackLibraryClientViews.Requests==0,"older library settlement cannot roll hint back");
 Setup();RebirthBackpackLibraryClientOffers.Revision=9;RebirthGearClientTransferPump.Tick();Check(RebirthBackpackLibraryClientViews.Requests==0&&RebirthGearOfferClient.Applies==1,"library revision cannot replace held gear original continuation");
 Console.WriteLine($"PASS {n} actual pump/deferral checks; native scope, custody, adjustment and Harmony dispatch boundaries doubled");
 }
}
public enum EnumGamePrefs{GameGuidClient}
public static class GamePrefs{public static string GetString(EnumGamePrefs p)=>"world";}
namespace HarmonyLib{
public class HarmonyPatch:Attribute{public HarmonyPatch(Type t,string n){}}
public class HarmonyPrefix:Attribute{}public class HarmonyPostfix:Attribute{}
public class HarmonyPriority:Attribute{public HarmonyPriority(int p){}}
public static class Priority{public const int First=800;}
}