using System;
using System.Collections.Generic;

#nullable disable

/// <summary>
/// Container-result mappings recovered from the custom REBIRTH 2.6 blocks.xml.
/// The 2.6-only "_PickedUp" block layer is collapsed to an existing 3.0
/// canonical storage block. This keeps the old source-to-container behavior
/// without recreating hundreds of XML block definitions.
/// </summary>
public static class RebirthBlockPickupLegacyTargets
{
    private static readonly Dictionary<string, string> SourceToTarget =
        new Dictionary<string, string>(StringComparer.Ordinal)
        {
            { "burningBarrel", "cntBarrelGasOld" },
            { "cntAmmoPileLarge", "cntAmmoPileLarge" },
            { "cntAmmoPileMedium", "cntAmmoPileMedium" },
            { "cntAmmoPileSmall", "cntAmmoPileSmall" },
            { "cntBackpack01", "cntBackpack01" },
            { "cntBackpack03", "cntBackpack03" },
            { "cntBarrelAcidQuadA", "cntBarrelGasSingle00" },
            { "cntBarrelAcidQuadB", "cntBarrelGasSingle00" },
            { "cntBarrelAcidSingle00", "cntBarrelAcidSingle00" },
            { "cntBarrelAcidSingle45", "cntBarrelAcidSingle00" },
            { "cntBarrelGasQuadA", "cntBarrelGasSingle00" },
            { "cntBarrelGasQuadB", "cntBarrelGasSingle00" },
            { "cntBarrelGasSingle00", "cntBarrelGasSingle00" },
            { "cntBarrelGasSingle45", "cntBarrelGasSingle00" },
            { "cntBarrelGenericQuadA", "cntBarrelGasSingle00" },
            { "cntBarrelGenericQuadB", "cntBarrelGasSingle00" },
            { "cntBarrelGenericSingle00", "cntBarrelGenericSingle00" },
            { "cntBarrelGenericSingle45", "cntBarrelGenericSingle00" },
            { "cntBarrelOilQuadA", "cntBarrelGasSingle00" },
            { "cntBarrelOilQuadB", "cntBarrelGasSingle00" },
            { "cntBarrelOilSingle00", "cntBarrelOilSingle00" },
            { "cntBarrelOilSingle45", "cntBarrelOilSingle00" },
            { "cntBarrelRadiatedQuadA", "cntBarrelGasSingle00" },
            { "cntBarrelRadiatedQuadB", "cntBarrelGasSingle00" },
            { "cntBarrelRadiatedSingle00", "cntBarrelRadiatedSingle00" },
            { "cntBarrelRadiatedSingle45", "cntBarrelRadiatedSingle00" },
            { "cntBarrelWhiteQuadA", "cntBarrelGasSingle00" },
            { "cntBarrelWhiteQuadB", "cntBarrelGasSingle00" },
            { "cntBarrelWhiteSingle00", "cntBarrelWhiteSingle00" },
            { "cntBarrelWhiteSingle45", "cntBarrelWhiteSingle00" },
            { "cntBathTubEmpty", "cntBathTubGore" },
            { "cntBookShelfSingleBottomFull01", "cntBookShelfSingleBottomFull01" },
            { "cntBookcaseEmpty", "cntBookcaseFull" },
            { "cntBookcaseFull", "cntBookcaseFull" },
            { "cntBruteStyleTrashCanEmpty", "cntBruteStyleTrashCanFull" },
            { "cntBruteStyleTrashCanFull", "cntBruteStyleTrashCanFull" },
            { "cntCabinetBottomOpen", "cntCabinetBottom" },
            { "cntCabinetBottomRandomLootHelper", "cntCabinetBottom" },
            { "cntCabinetOldBottomLootHelper", "cntCabinetOldBottom" },
            { "cntCabinetOldBottomOpen", "cntCabinetOldBottom" },
            { "cntCardboardBox", "cntCardboardBox" },
            { "cntCashRegister", "cntCashRegister" },
            { "cntCashRegisterEmpty", "cntCashRegister" },
            { "cntCasketModernClosedTan", "cntCasketModernClosedTan" },
            { "cntCharcoalGrillClosed", "cntCharcoalGrillClosed" },
            { "cntCharcoalGrillOpen", "cntCharcoalGrillClosed" },
            { "cntChemPileLarge", "cntChemPileLarge" },
            { "cntChemPileMedium", "cntChemPileMedium" },
            { "cntChemPileSmall", "cntChemPileSmall" },
            { "cntClothesRackRoundPants", "cntClothesRackRoundPants" },
            { "cntClothesRackWallLongSleeve", "cntClothesRackWallLongSleeve" },
            { "cntClothesRackWallPants", "cntClothesRackWallPants" },
            { "cntClothesShelfHalfJeans01", "cntClothesShelfHalfJeans01" },
            { "cntCoffeeMaker", "cntCoffeeMaker" },
            { "cntCoffeeMakerCommercial", "cntCoffeeMakerCommercial" },
            { "cntCoffinWildWestClosed", "cntCoffinWildWestClosed" },
            { "cntCoffinWildWestOpen", "cntCoffinWildWestClosed" },
            { "cntCoolerClosed", "cntCoolerClosed" },
            { "cntCoolerClosedGreen", "cntCoolerClosedGreen" },
            { "cntCoolerClosedRed", "cntCoolerClosedRed" },
            { "cntCoolerOpen", "cntCoolerClosed" },
            { "cntCoolerOpenGreen", "cntCoolerClosedGreen" },
            { "cntCoolerOpenRed", "cntCoolerClosedRed" },
            { "cntCupboardCabinetOldTopLootHelper", "cntCupboardCabinetOldTopClosed" },
            { "cntCupboardCabinetOldTopOpen", "cntCupboardCabinetOldTopClosed" },
            { "cntCupboardCabinetOldTopClosed", "cntCupboardCabinetOldTopClosed" },
            { "cntCupboardCabinetRedTopLootHelper", "cntCupboardCabinetRedTopClosed" },
            { "cntCupboardCabinetRedTopOpen", "cntCupboardCabinetRedTopClosed" },
            { "cntCupboardCabinetRedTopClosed", "cntCupboardCabinetRedTopClosed" },
            { "cntDeskMetalEmptyArmyGreen", "cntDeskMetalEmptyArmyGreen" },
            { "cntDeskMetalEmptyBlack", "cntDeskMetalEmptyBlack" },
            { "cntDeskMetalEmptyBlue", "cntDeskMetalEmptyBlue" },
            { "cntDeskMetalEmptyBrown", "cntDeskMetalEmptyBrown" },
            { "cntDeskMetalEmptyGreen", "cntDeskMetalEmptyGreen" },
            { "cntDeskMetalEmptyGrey", "cntDeskMetalEmptyGrey" },
            { "cntDeskMetalEmptyOrange", "cntDeskMetalEmptyOrange" },
            { "cntDeskMetalEmptyPink", "cntDeskMetalEmptyPink" },
            { "cntDeskMetalEmptyPurple", "cntDeskMetalEmptyPurple" },
            { "cntDeskMetalEmptyRed", "cntDeskMetalEmptyRed" },
            { "cntDeskMetalEmptyWhite", "cntDeskMetalEmptyWhite" },
            { "cntDeskMetalEmptyYellow", "cntDeskMetalEmptyYellow" },
            { "cntDeskSafeInsecure", "cntDeskSafe" },
            { "cntDeskSafeOpen", "cntDeskSafe" },
            { "cntDomedTrashCanCornerEmpty", "cntDomedTrashCanCornerFull" },
            { "cntDomedTrashCanCornerFull", "cntDomedTrashCanCornerFull" },
            { "cntDomedTrashCanEmpty", "cntDomedTrashCanFull" },
            { "cntDomedTrashCanFull", "cntDomedTrashCanFull" },
            { "cntDryerClosed", "cntDryerClosed" },
            { "cntDryerOpen", "cntDryerClosed" },
            { "cntDuffle01", "cntDuffle01" },
            { "cntDumpster", "cntDumpster" },
            { "cntDumpsterFlies", "cntDumpsterFlies" },
            { "cntFancyGarbageCan", "cntFancyGarbageCan" },
            { "cntFileCabinetShortClosed", "cntFileCabinetShortClosed" },
            { "cntFileCabinetShortOpen", "cntFileCabinetShortClosed" },
            { "cntFileCabinetTallClosed", "cntFileCabinetTallClosed" },
            { "cntFileCabinetTallOpen", "cntFileCabinetTallClosed" },
            { "cntFridgeStainlessSteel", "cntFridgeStainlessSteel" },
            { "cntFridgeStainlessSteelVer2Open", "cntFridgeStainlessSteel" },
            { "cntGarageStorage", "cntGarageStorage" },
            { "cntGasGrillClosed", "cntGasGrillClosed" },
            { "cntGasGrillOpen", "cntGasGrillClosed" },
            { "cntGasPumpEmpty", "cntGasPumpFull" },
            { "cntGasPumpFull", "cntGasPumpFull" },
            { "cntGunRackLargeGuns01", "cntGunRackLargeGuns01" },
            { "cntGunRackLargeGunsEmpty01", "cntGunRackLargeGuns01" },
            { "cntGunRackLargeGunsEmpty02", "cntGunRackLargeGuns02" },
            { "cntGunRackSmallArmor", "cntGunRackSmallArmor" },
            { "cntGunRackSmallEmpty02", "cntGunRackSmallMagazines" },
            { "cntGunRackSmallEmpty03", "cntGunRackSmallArmor" },
            { "cntGunRackSmallMagazines", "cntGunRackSmallMagazines" },
            { "cntGunSafeInsecure", "cntGunSafe" },
            { "cntHardenedChestInsecure", "cntHardenedChestInsecure" },
            { "cntHardenedChestInsecureT5", "cntHardenedChestSecureT5" },
            { "cntHardenedChestSecureT5", "cntHardenedChestSecureT5" },
            { "cntLockersShortClosed", "cntLockersShortClosed" },
            { "cntLockersShortOpen", "cntLockersShortClosed" },
            { "cntLockersTallClosed", "cntLockersTallClosed" },
            { "cntLockersTallOpen", "cntLockersTallClosed" },
            { "cntLootChestHero", "cntLootChestHeroInsecure" },
            { "cntLootChestHeroInsecure", "cntLootChestHeroInsecure" },
            { "cntLootChestHeroInsecureT1", "cntLootChestHeroInsecureT1" },
            { "cntLootChestHeroInsecureT2", "cntLootChestHeroInsecureT2" },
            { "cntLootCrateBookstore", "cntLootCrateBookstore" },
            { "cntLootCrateCarParts", "cntLootCrateCarParts" },
            { "cntLootCrateConstructionSupplies", "cntLootCrateConstructionSupplies" },
            { "cntLootCrateHero", "cntLootCrateHero" },
            { "cntLootCrateLabEquipment", "cntLootCrateLabEquipment" },
            { "cntLootCrateMoPowerElectronics", "cntLootCrateMoPowerElectronics" },
            { "cntLootCrateSavageCountry", "cntLootCrateSavageCountry" },
            { "cntLootCrateShamway", "cntLootCrateShamway" },
            { "cntLootCrateShotgunMessiah", "cntLootCrateShotgunMessiah" },
            { "cntLootCrateWorkingStiffs", "cntLootCrateWorkingStiffs" },
            { "cntLuggagePileAOpen", "cntLuggagePileAClosed" },
            { "cntLuggagePileAClosed", "cntLuggagePileAClosed" },
            { "cntLuggagePileARandomLootHelper", "cntLuggagePileAClosed" },
            { "cntLuggagePileBOpen", "cntLuggagePileBClosed" },
            { "cntLuggagePileBClosed", "cntLuggagePileBClosed" },
            { "cntLuggagePileBRandomLootHelper", "cntLuggagePileBClosed" },
            { "cntLuggageMediumClosed", "cntLuggageMediumClosed" },
            { "cntLuggageMediumOpen", "cntLuggageMediumClosed" },
            { "cntLuggageMediumRandomLootHelper", "cntLuggageMediumClosed" },
            { "cntMedicLootPileA", "cntMedicLootPileA" },
            { "cntMedicLootPileB", "cntMedicLootPileB" },
            { "cntMedicineCabinetClosed", "cntMedicineCabinetClosed" },
            { "cntMedicineCabinetFaucetClosed", "cntMedicineCabinetFaucetClosed" },
            { "cntMedicineCabinetFaucetOpen", "cntMedicineCabinetClosed" },
            { "cntMedicineCabinetOpen", "cntMedicineCabinetClosed" },
            { "cntMicrowaveOvenVer1Closed", "cntMicrowaveOvenVer1Closed" },
            { "cntMicrowaveOvenVer1Open", "cntMicrowaveOvenVer1Closed" },
            { "cntMicrowaveOvenVer2Closed", "cntMicrowaveOvenVer2Closed" },
            { "cntMicrowaveOvenVer2Open", "cntMicrowaveOvenVer2Closed" },
            { "cntMilitaryGoodsA", "cntMilitaryGoodsA" },
            { "cntMilitaryGoodsB", "cntMilitaryGoodsB" },
            { "cntMilitaryGoodsC", "cntMilitaryGoodsC" },
            { "cntMilitaryGoodsD", "cntMilitaryGoodsD" },
            { "cntMilitaryMetalShelvesEmpty", "cntMilitaryMetalShelvesEmpty" },
            { "cntMilitaryMetalShelvesFull", "cntMilitaryMetalShelvesFull" },
            { "cntMiniBeverageCooler", "cntMiniBeverageCooler" },
            { "cntMunitionsBoxArmy", "cntMunitionsBoxArmy" },
            { "cntNewsDispenseFreeGreen", "cntNewsDispenseFreeGreen" },
            { "cntNewsDispenseFreeOrange", "cntNewsDispenseFreeOrange" },
            { "cntNewspaperDispenserStandBlue", "cntNewspaperDispenserStandBlue" },
            { "cntNewspaperDispenserStandYellow", "cntNewspaperDispenserStandYellow" },
            { "cntNightstandClosed", "cntNightstandClosed" },
            { "cntNightstandOpen", "cntNightstandClosed" },
            { "cntPillCaseClosed", "cntPillCaseClosed" },
            { "cntPillCaseEmpty", "cntPillCaseClosed" },
            { "cntPurse01", "cntPurse01" },
            { "cntQuestInfestedT1", "cntQuestInfestedT1" },
            { "cntRetroFridgeVer1Closed", "cntRetroFridgeVer1Closed" },
            { "cntRetroFridgeVer2Open", "cntRetroFridgeVer1Closed" },
            { "cntRollingToolBoxClosedBlue", "cntRollingToolBoxClosedBlue" },
            { "cntRollingToolBoxClosedGreen", "cntRollingToolBoxClosedGreen" },
            { "cntRollingToolBoxClosedGrey", "cntRollingToolBoxClosedGrey" },
            { "cntRollingToolBoxClosedRed", "cntRollingToolBoxClosedRed" },
            { "cntRollingToolBoxClosedWhite", "cntRollingToolBoxClosedWhite" },
            { "cntRollingToolBoxClosedYellow", "cntRollingToolBoxClosedYellow" },
            { "cntRollingToolBoxOpenBlue", "cntRollingToolBoxClosedBlue" },
            { "cntRollingToolBoxOpenGreen", "cntRollingToolBoxClosedGreen" },
            { "cntRollingToolBoxOpenGrey", "cntRollingToolBoxClosedGrey" },
            { "cntRollingToolBoxOpenRed", "cntRollingToolBoxClosedRed" },
            { "cntRollingToolBoxOpenWhite", "cntRollingToolBoxClosedWhite" },
            { "cntRollingToolBoxOpenYellow", "cntRollingToolBoxClosedYellow" },
            { "cntShelvesMetalEmpty", "cntShelvesMetalEmpty" },
            { "cntShelvesMetalFullA", "cntShelvesMetalFullA" },
            { "cntSodaFountain", "cntSodaFountain" },
            { "cntSportsBag01", "cntSportsBag01" },
            { "cntSportsBag02", "cntSportsBag02" },
            { "cntStoreProduceBasketApples1", "cntStoreProduceBasketApples1" },
            { "cntStoreProduceBasketApples2", "cntStoreProduceBasketApples2" },
            { "cntStoreProduceBasketCornerEmpty1", "cntStoreProduceBasketCornerEmpty1" },
            { "cntStoreProduceBasketCornerEmpty2", "cntStoreProduceBasketCornerEmpty2" },
            { "cntStoreProduceBasketEmpty1", "cntStoreProduceBasketEmpty1" },
            { "cntStoreProduceBasketEmpty2", "cntStoreProduceBasketEmpty2" },
            { "cntStoreProduceBasketGourds1", "cntStoreProduceBasketGourds1" },
            { "cntStoreProduceBasketGourds2", "cntStoreProduceBasketGourds2" },
            { "cntStoreProduceBasketLettuce1", "cntStoreProduceBasketLettuce1" },
            { "cntStoreProduceBasketLettuce2", "cntStoreProduceBasketLettuce2" },
            { "cntStoreProduceBasketMelons1", "cntStoreProduceBasketMelons1" },
            { "cntStoreProduceBasketMelons2", "cntStoreProduceBasketMelons2" },
            { "cntStoreShelfDoubleBottomEmpty", "cntStoreShelfDoubleBottomFood01" },
            { "cntStoreShelfDoubleBottomFood01", "cntStoreShelfDoubleBottomFood01" },
            { "cntStoreShelfDoubleBottomFood02", "cntStoreShelfDoubleBottomFood02" },
            { "cntStoreShelfDoubleBottomHardware01", "cntStoreShelfDoubleBottomHardware01" },
            { "cntStoreShelfDoubleBottomHardware02", "cntStoreShelfDoubleBottomHardware02" },
            { "cntStoreShelfDoubleBottomHardware03Rags", "cntStoreShelfDoubleBottomHardware03Rags" },
            { "cntStoreShelfDoubleBottomPharmaEmpty", "cntStoreShelfDoubleBottomPharmaGoods01" },
            { "cntStoreShelfDoubleBottomPharmaGoods01", "cntStoreShelfDoubleBottomPharmaGoods01" },
            { "cntStoreShelfDoubleBottomPharmaGoods02", "cntStoreShelfDoubleBottomPharmaGoods02" },
            { "cntStoreShelfDoubleBottomShoesEmpty", "cntStoreShelfDoubleBottomShoesFull" },
            { "cntStoreShelfDoubleBottomShoesFull", "cntStoreShelfDoubleBottomShoesFull" },
            { "cntStoreShelfDoubleBottomTrash01", "cntStoreShelfDoubleBottomTrash01" },
            { "cntStoreShelfDoubleBottomTrash02", "cntStoreShelfDoubleBottomTrash02" },
            { "cntStoreShelfDoubleTopEmpty", "cntStoreShelfDoubleTopFood01" },
            { "cntStoreShelfDoubleTopHardware01", "cntStoreShelfDoubleTopHardware01" },
            { "cntStoreShelfDoubleTopHardware02Rags", "cntStoreShelfDoubleTopHardware02Rags" },
            { "cntStoreShelfDoubleTopShoesEmpty", "cntStoreShelfDoubleTopShoesFull" },
            { "cntStoreShelfDoubleTopTrash01", "cntStoreShelfDoubleTopTrash01" },
            { "cntStoreShelfElectronicsSingleBottomPC", "cntStoreShelfElectronicsSingleBottomPC" },
            { "cntStoreShelfSingleBottomEmpty", "cntStoreShelfSingleBottomFood01" },
            { "cntStoreShelfSingleBottomFood01", "cntStoreShelfSingleBottomFood01" },
            { "cntStoreShelfSingleBottomFood02", "cntStoreShelfSingleBottomFood02" },
            { "cntStoreShelfSingleBottomFoodRandomLootHelper", "cntStoreShelfSingleBottomFood01" },
            { "cntStoreShelfSingleBottomHardware01", "cntStoreShelfSingleBottomHardware01" },
            { "cntStoreShelfSingleBottomHardware02", "cntStoreShelfSingleBottomHardware02" },
            { "cntStoreShelfSingleBottomPharmaEmpty", "cntStoreShelfSingleBottomPharmaGoods01" },
            { "cntStoreShelfSingleBottomPharmaGoods01", "cntStoreShelfSingleBottomPharmaGoods01" },
            { "cntStoreShelfSingleBottomPharmaGoods02", "cntStoreShelfSingleBottomPharmaGoods02" },
            { "cntStoreShelfSingleBottomShoesEmpty", "cntStoreShelfSingleBottomShoesFull" },
            { "cntStoreShelfSingleBottomTrash01", "cntStoreShelfSingleBottomTrash01" },
            { "cntStoreShelfSingleBottomTrash02", "cntStoreShelfSingleBottomTrash02" },
            { "cntStoreShelfSingleTopEmpty", "cntStoreShelfSingleTopFood01" },
            { "cntStoreShelfSingleTopFood01", "cntStoreShelfSingleTopFood01" },
            { "cntStoreShelfSingleTopHardware01", "cntStoreShelfSingleTopHardware01" },
            { "cntStoreShelfSingleTopHardware02", "cntStoreShelfSingleTopHardware02" },
            { "cntStoreShelfSingleTopShoesEmpty", "cntStoreShelfSingleTopShoesFull" },
            { "cntStoreShelfSingleTopTrash01", "cntStoreShelfSingleTopTrash01" },
            { "cntStoreShelfSingleTopTrash02", "cntStoreShelfSingleTopTrash02" },
            { "cntStoveModernVer1Closed", "cntStoveModernVer1Closed" },
            { "cntStoveModernVer2Open", "cntStoveModernVer1Closed" },
            { "cntStoveOldVer1Closed", "cntStoveOldVer1Closed" },
            { "cntStoveOldVer2Open", "cntStoveOldVer1Closed" },
            { "cntSuitcase", "cntSuitcase" },
            { "cntToilet01", "cntToilet01" },
            { "cntToolBoxClosedBlue", "cntToolBoxClosedBlue" },
            { "cntToolBoxClosedGreen", "cntToolBoxClosedGreen" },
            { "cntToolBoxClosedGrey", "cntToolBoxClosedGrey" },
            { "cntToolBoxClosedRed", "cntToolBoxClosedRed" },
            { "cntToolBoxClosedWhite", "cntToolBoxClosedWhite" },
            { "cntToolBoxClosedYellow", "cntToolBoxClosedYellow" },
            { "cntToolBoxOffsetClosedBlue", "cntToolBoxClosedBlue" },
            { "cntToolBoxOffsetClosedGreen", "cntToolBoxClosedGreen" },
            { "cntToolBoxOffsetClosedGrey", "cntToolBoxClosedGrey" },
            { "cntToolBoxOffsetClosedRed", "cntToolBoxClosedRed" },
            { "cntToolBoxOffsetClosedWhite", "cntToolBoxClosedWhite" },
            { "cntToolBoxOffsetClosedYellow", "cntToolBoxClosedYellow" },
            { "cntToolBoxOffsetOpenBlue", "cntToolBoxClosedBlue" },
            { "cntToolBoxOffsetOpenGreen", "cntToolBoxClosedGreen" },
            { "cntToolBoxOffsetOpenGrey", "cntToolBoxClosedGrey" },
            { "cntToolBoxOffsetOpenRed", "cntToolBoxClosedRed" },
            { "cntToolBoxOffsetOpenWhite", "cntToolBoxClosedWhite" },
            { "cntToolBoxOffsetOpenYellow", "cntToolBoxClosedYellow" },
            { "cntToolBoxOpenBlue", "cntToolBoxClosedBlue" },
            { "cntToolBoxOpenGreen", "cntToolBoxClosedGreen" },
            { "cntToolBoxOpenGrey", "cntToolBoxClosedGrey" },
            { "cntToolBoxOpenRed", "cntToolBoxClosedRed" },
            { "cntToolBoxOpenWhite", "cntToolBoxClosedWhite" },
            { "cntToolBoxOpenYellow", "cntToolBoxClosedYellow" },
            { "cntWallSafeInsecure", "cntWallSafe" },
            { "cntWallSafeOpen", "cntWallSafe" },
            { "cntWasherClosed", "cntWasherClosed" },
            { "cntWasherIndustrialClosed", "cntWasherIndustrialClosed" },
            { "cntWasherIndustrialOpen", "cntWasherIndustrialClosed" },
            { "cntWasherOpen", "cntWasherClosed" },
            { "cntWaterCoolerBottleSideCentered", "cntWaterCoolerBottle" },
            { "cntWaterCoolerFull", "cntWaterCoolerFull" },
            { "cntWaterCoolerFullSideCentered", "cntWaterCoolerFullSideCentered" },
            { "cntWeaponsBagLarge", "cntWeaponsBagLarge" },
            { "cntWeaponsBagSmall", "cntWeaponsBagSmall" },
            { "cntbasketLaundryEmptyWhite", "cntbasketLaundryFullWhite" },
            { "cntbasketLaundryFullWhite", "cntbasketLaundryFullWhite" },
            { "cntbinTrashRollingBlue", "cntbinTrashRollingBlue" },
            { "cntbinTrashRollingBrown", "cntbinTrashRollingBrown" },
            { "cntbinTrashRollingGreen", "cntbinTrashRollingGreen" },
            { "cntbinTrashRollingGrey", "cntbinTrashRollingGrey" },
            { "cntbinTrashRollingOrange", "cntbinTrashRollingOrange" },
            { "cntbinTrashRollingRed", "cntbinTrashRollingRed" },
            { "cntbinTrashRollingWhite", "cntbinTrashRollingWhite" },
            { "cntbinTrashRollingYellow", "cntbinTrashRollingYellow" },
            { "wallMirror", "cntMedicineCabinetClosed" },
            { "wallMirrorBroken", "cntMedicineCabinetClosed" },
            { "wineBarrel", "wineBarrelPlayer" },
            { "wineBarrelSet", "wineBarrelSetPlayer" },
            { "wineBarrelPlain", "wineBarrelPlainPlayer" },
            { "wineBarrelPlainPlayer", "wineBarrelPlainPlayer" },
            { "wineBarrelPlayer", "wineBarrelPlayer" },
            { "wineBarrelSetPlayer", "wineBarrelSetPlayer" },
        };

    public static bool TryGetTarget(string sourceBlockName, out string targetBlockName)
    {
        if (string.IsNullOrEmpty(sourceBlockName))
        {
            targetBlockName = null;
            return false;
        }

        return SourceToTarget.TryGetValue(sourceBlockName, out targetBlockName);
    }

    public static bool ContainsTarget(string blockName)
    {
        if (string.IsNullOrEmpty(blockName))
            return false;

        foreach (KeyValuePair<string, string> pair in SourceToTarget)
        {
            if (string.Equals(pair.Value, blockName, StringComparison.Ordinal))
                return true;
        }

        return false;
    }

    public static int Count { get { return SourceToTarget.Count; } }
}
