using System;
class Program{
static int n;static void C(bool b,string s){if(!b)throw new Exception(s);n++;}
static (World,ClientInfo,EntityPlayer) Setup(int id=1){var w=new World();var c=new ClientInfo{ClientNumber=id,entityId=id};var p=new EntityPlayer{entityId=id,world=w};w.Actors[id]=p;SingletonMonoBehaviour<ConnectionManager>.Instance=new ConnectionManager();SingletonMonoBehaviour<ConnectionManager>.Instance.Clients.Entries[id]=c;GameManager.Instance=new GameManager{World=w};return(w,c,p);}
static void Main(){var(w,c,p)=Setup();C(SeedPlacementSessionAuthority.TryIssue(c,w,out var e)&&e!=0,"server cryptorandom nonzero epoch");C(SeedPlacementSessionAuthority.TryIssue(c,w,out var same)&&same==e,"reissue preserves active epoch/replay memory");C(!SeedPlacementSessionAuthority.TryReserve(c,w,e,0,out _)&&!SeedPlacementSessionAuthority.TryReserve(c,w,0,1,out _),"zero rejected");C(SeedPlacementSessionAuthority.TryReserve(c,w,e,3,out var r)&&r.Actor==p&&r.Epoch==e&&r.Nonce==3,"reserve before execution immutable correlation");C(!SeedPlacementSessionAuthority.TryReserve(c,w,e,3,out _)&&!SeedPlacementSessionAuthority.TryReserve(c,w,e,2,out _),"duplicate/outoforder never replay");C(SeedPlacementSessionAuthority.TryReserve(c,w,e,ulong.MaxValue,out _)&&!SeedPlacementSessionAuthority.TryReserve(c,w,e,4,out _)&&SeedPlacementSessionAuthority.IsCurrent(r),"no nonce wrap; earlier receipt remains current");SeedPlacementSessionAuthority.Revoke(c);C(!SeedPlacementSessionAuthority.IsCurrent(r)&&!SeedPlacementSessionAuthority.TryReserve(c,w,e,9,out _),"explicit revoke invalidates old epoch");SeedPlacementSessionAuthority.Reservation second=null;C(SeedPlacementSessionAuthority.TryIssue(c,w,out var next)&&next!=0&&SeedPlacementSessionAuthority.TryReserve(c,w,next,1,out second),"new explicitly revoked session can restart nonce");SeedPlacementSessionAuthority.Clear(w);C(!SeedPlacementSessionAuthority.IsCurrent(second),"world clear invalidates receipts");
foreach(var fault in new[]{"clientreplace","actorreplace","worldreplace","remote","dead","login","attached","disconnect","entity","server","manager","connection"}){(w,c,p)=Setup();C(SeedPlacementSessionAuthority.TryIssue(c,w,out e)&&SeedPlacementSessionAuthority.TryReserve(c,w,e,1,out r),"admit before "+fault);switch(fault){case "clientreplace":SingletonMonoBehaviour<ConnectionManager>.Instance.Clients.Entries[1]=new ClientInfo{ClientNumber=1,entityId=1};break;case "actorreplace":w.Actors[1]=new EntityPlayer{entityId=1,world=w};break;case "worldreplace":GameManager.Instance.World=new World();break;case "remote":w.Remote=true;break;case "dead":p.Dead=true;break;case "login":c.loginDone=false;break;case "attached":c.bAttachedToEntity=false;break;case "disconnect":c.disconnecting=true;break;case "entity":c.entityId=0;break;case "server":SingletonMonoBehaviour<ConnectionManager>.Instance.IsServer=false;break;case "manager":GameManager.Instance=new GameManager{World=w};break;case "connection":var replacement=new ConnectionManager();replacement.Clients.Entries[1]=c;SingletonMonoBehaviour<ConnectionManager>.Instance=replacement;break;}C(!SeedPlacementSessionAuthority.IsCurrent(r)&&!SeedPlacementSessionAuthority.TryReserve(c,w,e,2,out _),"replacement/context rejects old "+fault);GameManager.Instance=new GameManager{World=w};SingletonMonoBehaviour<ConnectionManager>.Instance=new ConnectionManager();SingletonMonoBehaviour<ConnectionManager>.Instance.Clients.Entries[1]=c;c.loginDone=true;c.bAttachedToEntity=true;c.disconnecting=false;c.entityId=1;p.Dead=false;w.Remote=false;w.Actors[1]=p;C(!SeedPlacementSessionAuthority.IsCurrent(r)&&!SeedPlacementSessionAuthority.TryReserve(c,w,e,3,out _),"observed invalid epoch cannot resurrect "+fault);SeedPlacementSessionAuthority.Revoke(c);}
(w,c,p)=Setup();var forged=new ClientInfo{ClientNumber=1,entityId=1};C(!SeedPlacementSessionAuthority.TryIssue(forged,w,out _),"client booleans without registry identity cannot issue");C(!SeedPlacementSessionAuthority.TryIssue(c,new World(),out _),"foreign world cannot issue");C(!SeedPlacementSessionAuthority.TryIssue(null,w,out _)&&!SeedPlacementSessionAuthority.TryIssue(c,null,out _),"null admission refused");bool unboundRejected=false;try{new SeedPlacementSessionAuthority.Reservation(new object(),1);}catch(ArgumentException){unboundRejected=true;}C(unboundRejected,"correlation constructor cannot forge private binding");(w,c,p)=Setup();for(int i=1;i<=256;i++){var actor=new EntityPlayer{entityId=i,world=w};var sender=new ClientInfo{ClientNumber=i,entityId=i};w.Actors[i]=actor;SingletonMonoBehaviour<ConnectionManager>.Instance.Clients.Entries[i]=sender;C(SeedPlacementSessionAuthority.TryIssue(sender,w,out _),"bounded active entry "+i);}var excess=new ClientInfo{ClientNumber=257,entityId=257};w.Actors[257]=new EntityPlayer{entityId=257,world=w};SingletonMonoBehaviour<ConnectionManager>.Instance.Clients.Entries[257]=excess;C(!SeedPlacementSessionAuthority.TryIssue(excess,w,out _),"capacity refuses without evicting replay memory");SeedPlacementSessionAuthority.Clear(w);Console.WriteLine("PASS "+n+" linked session authority checks; native identity adapters, no network/placement/debit claim.");}}



