using System;using System.Collections.Generic;using System.IO;using System.Linq;using System.Xml.Linq;
public class RebirthStationGridAdmission{public string JobId,CreationId,DefinitionId;public XElement Write()=>throw new Exception("actual admission not exercised");}
class Program{
static int n;static void C(bool v,string s){if(!v)throw new Exception(s);n++;}
static RebirthStationRecipeDiscoveryRecord Record(string recipe,string creation,string owner){
var w=new XElement("stationDiscoveryWitness",new XAttribute("version",1),new XAttribute("job",Guid.NewGuid().ToString("N")),new XAttribute("creation",creation),new XAttribute("owner",owner),new XAttribute("save",new string('b',64)),new XAttribute("policy",new string('c',64)),new XAttribute("knowledge","knowledge.test"),new XAttribute("definition",new string('D',64)),new XAttribute("admission",new string('E',64)));
C(RebirthStationDiscoveryWitness.TryReadStored(w,out var witness),"actual witness stored syntax");
C(RebirthStationRecipeDiscoveryRecord.TryCreate(witness,recipe,new string('F',64),out var record),"actual DTO create");return record;}
static void Main(){
var owner=new string('a',64);
foreach(var creation in new[]{Guid.NewGuid().ToString("N"),"legacy-"+new string('a',64)}){
var a=Record("zRecipe",creation,owner);var b=Record("aRecipe",creation,owner);
var records=new Dictionary<string,RebirthStationRecipeDiscoveryRecord>(StringComparer.Ordinal){{a.CanonicalRecipe,a},{b.CanonicalRecipe,b}};
var section=RebirthStationRecipeDiscoveryPersistence.Write(records,owner);C((string)section.Elements().First().Attribute("recipe")=="aRecipe","canonical ordinal sorting");var root=new XElement("progression",section);
C(RebirthStationRecipeDiscoveryPersistence.TryRead(root,owner,out var parsed,out var error)&&parsed.Count==2&&XNode.DeepEquals(section,RebirthStationRecipeDiscoveryPersistence.Write(parsed,owner)),"wholehelper roundtrip");
C(RebirthStationRecipeDiscoveryPersistence.TryRead(new XElement("progression"),owner,out parsed,out error)&&parsed.Count==0,"optional absent valid");
C(RebirthStationRecipeDiscoveryPersistence.MatchesCreation(records.Values,creation)&&!RebirthStationRecipeDiscoveryPersistence.MatchesCreation(records.Values,Guid.NewGuid().ToString("N")),"actual parent creation gate");
var clone=new CloneSlice();clone.RecipeDiscoveries.Add(a.CanonicalRecipe,a);var copied=clone.Clone();C(!ReferenceEquals(copied.RecipeDiscoveries,clone.RecipeDiscoveries)&&!ReferenceEquals(copied.RecipeDiscoveries[a.CanonicalRecipe],a)&&XNode.DeepEquals(copied.RecipeDiscoveries[a.CanonicalRecipe].Write(),a.Write()),"actual clone slice detached DTO");C(RepoSlices.Read(RepoSlices.Write(clone,owner),owner,out var readSlice,out error)&&readSlice.RecipeDiscoveries.Count==1,"actual repo discovery hook slices");C(RepoSlices.CheckRead(readSlice,new(){CreationId=creation},out error),"actual repo outer creation accepts");bool wrongWrite=false;try{RepoSlices.CheckWrite(new(){Progression=clone,Origin=new(){CreationId=Guid.NewGuid().ToString("N")}});}catch(InvalidDataException){wrongWrite=true;}C(wrongWrite,"actual repo writer origin rejects");C(!RepoSlices.CheckRead(readSlice,new(){CreationId=Guid.NewGuid().ToString("N")},out error),"actual repo reader origin rejects");var mutated=copied.RecipeDiscoveries[a.CanonicalRecipe].Write();mutated.SetAttributeValue("recipe","other");C(a.CanonicalRecipe=="zRecipe","DTO XElement detached");
void Bad(XElement x,string label){C(!RebirthStationRecipeDiscoveryPersistence.TryRead(x,owner,out parsed,out error)&&parsed==null,"beforepublished "+label);}
Bad(null,"missing parent");var dup=new XElement(root);dup.Add(new XElement(section));Bad(dup,"duplicate section");
foreach(var fault in new[]{"sectionattr","sectionversion","unknownchild","recipe","job","owner","creation","nested","duplicateRecord","trailing"}){
var bad=new XElement(root);var s=bad.Element("recipeDiscoveries");var r=s.Elements().First();
switch(fault){case "sectionattr":s.SetAttributeValue("extra",1);break;case "sectionversion":s.SetAttributeValue("version",2);break;case "unknownchild":s.Add(new XElement("other"));break;case "recipe":r.SetAttributeValue("recipe"," bad ");break;case "job":r.SetAttributeValue("job","invalid");break;case "owner":r.SetAttributeValue("owner",new string('b',64));r.Element("stationDiscoveryWitness").SetAttributeValue("owner",new string('b',64));break;case "creation":r.SetAttributeValue("creation","broken");r.Element("stationDiscoveryWitness").SetAttributeValue("creation","broken");break;case "nested":r.Element("stationDiscoveryWitness").SetAttributeValue("admission","bad");break;case "duplicateRecord":s.Add(new XElement(r));break;case "trailing":s.Add(new XText("unexpected"));break;}Bad(bad,fault);}
var duplicateJob=new XElement(root);var reused=a.Write();reused.SetAttributeValue("recipe","otherRecipe");duplicateJob.Element("recipeDiscoveries").Add(reused);Bad(duplicateJob,"duplicate job for distinct recipe");RebirthStationRecipeDiscoveryRecord.TryReadStored(reused,out var reusedRecord);bool jobWrite=false;try{RebirthStationRecipeDiscoveryPersistence.Write(new Dictionary<string,RebirthStationRecipeDiscoveryRecord>{{a.CanonicalRecipe,a},{"otherRecipe",reusedRecord}},owner);}catch(InvalidDataException){jobWrite=true;}C(jobWrite,"writer duplicate job refuses");var caseRecord=Record("ZRecipe",creation,owner);var casing=new XElement(root);casing.Element("recipeDiscoveries").Add(caseRecord.Write());C(RebirthStationRecipeDiscoveryPersistence.TryRead(casing,owner,out parsed,out error)&&parsed.Count==3,"ordinal distinct case syntactically accepted");
foreach(var fault in new[]{"nullcollection","nullrecord","wrongkey","owner"}){
bool refused=false;try{var x=new Dictionary<string,RebirthStationRecipeDiscoveryRecord>(records);switch(fault){case "nullcollection":x=null;break;case "nullrecord":x["bad"]=null;break;case "wrongkey":x["wrong"]=a;break;}RebirthStationRecipeDiscoveryPersistence.Write(x,fault=="owner"?new string('b',64):owner);}catch(InvalidDataException){refused=true;}C(refused,"writer refuses "+fault);}
var budget=new XElement(root);budget.Element("recipeDiscoveries").Add(new XText(new string(' ',RebirthStationRecipeDiscoveryPersistence.MaximumBytes)));Bad(budget,"read byte budget");
var counted=new XElement("progression",new XElement("recipeDiscoveries",new XAttribute("version",1)));for(int i=0;i<8193;i++){var entry=a.Write();entry.SetAttributeValue("recipe","r"+i);var job=Guid.NewGuid().ToString("N");entry.SetAttributeValue("job",job);entry.Element("stationDiscoveryWitness").SetAttributeValue("job",job);counted.Element("recipeDiscoveries").Add(entry);}
var underBytes=System.Text.Encoding.UTF8.GetByteCount(counted.ToString(SaveOptions.DisableFormatting))<RebirthStationRecipeDiscoveryPersistence.MaximumBytes;Bad(counted,underBytes?"read count budget":"read bytes before count");
counted.Element("recipeDiscoveries").Elements().Last().Remove();if(System.Text.Encoding.UTF8.GetByteCount(counted.ToString(SaveOptions.DisableFormatting))<=RebirthStationRecipeDiscoveryPersistence.MaximumBytes)C(RebirthStationRecipeDiscoveryPersistence.TryRead(counted,owner,out parsed,out error)&&parsed.Count==8192,"read count boundary admitted");else Bad(counted,"legacy count boundary exceeds byte budget");var oversized=new Dictionary<string,RebirthStationRecipeDiscoveryRecord>(StringComparer.Ordinal);
for(int i=0;i<5000;i++){var x=a.Write();var recipe=new string('q',1000)+i;var job=Guid.NewGuid().ToString("N");x.SetAttributeValue("recipe",recipe);x.SetAttributeValue("job",job);x.Element("stationDiscoveryWitness").SetAttributeValue("job",job);if(!RebirthStationRecipeDiscoveryRecord.TryReadStored(x,out var large))throw new Exception("budget fixture DTO");oversized.Add(recipe,large);}
bool writeBudget=false;try{RebirthStationRecipeDiscoveryPersistence.Write(oversized,owner);}catch(InvalidDataException){writeBudget=true;}C(writeBudget,"writer byte budget below record count");var over=new Dictionary<string,RebirthStationRecipeDiscoveryRecord>();for(int i=0;i<8193;i++)over[i.ToString()]=a;bool countRefused=false;try{RebirthStationRecipeDiscoveryPersistence.Write(over,owner);}catch(InvalidDataException){countRefused=true;}C(countRefused,"writer count budget");
}
Console.WriteLine("PASS "+n+" actual helper/DTO/witness/scope + exact model declaration/clone slice; no whole repository/grant/native authority");}}
