from pathlib import Path
from lxml import etree as E
root=Path(__file__).resolve().parents[2]
cfg=E.Element('configs'); cond=E.SubElement(cfg,'conditional'); c=E.SubElement(cond,'if',cond="character_progression('Rebirth')")
base="/windows/window[@name='rebirthJournalRoot']"
def setatt(path,name,value):E.SubElement(c,'setattribute',xpath=base+path,name=name).text=str(value)
def button(parent,name,text,x,y,w=180,depth=10):
 r=E.SubElement(parent,'rect',name=name,pos=f'{x},{y}',width=str(w),height='38')
 E.SubElement(r,'button',name=name+'Hit',width=str(w),height='38',sprite='menu_empty',type='sliced',defaultcolor='30,30,37,255',hovercolor='75,65,90,255',depth=str(depth),hoverscale='1')
 E.SubElement(r,'label',name=name+'Label',text_key=text,pos=f'{w//2},-19',pivot='center',width=str(w-12),height='30',font_size='20',justify='center',depth=str(depth+1),color='245,245,245,255')
 return r
E.SubElement(c,'remove',xpath=base+"//*[@name='journalArt']")
a=E.SubElement(c,'append',xpath=base+"//*[@name='journalReaderContent']")
E.SubElement(a,'texture',name='journalArt',pos='24,-96',width='560',height='315',depth='5')
E.SubElement(a,'button',name='journalArtHit',pos='24,-96',width='560',height='315',sprite='menu_empty',defaultcolor='0,0,0,1',hovercolor='255,255,255,15',depth='6',hoverscale='1')
button(a,'journalImageOpen','xuiRebirthJournalExpand',610,-210,360)
setatt("//*[@name='journalEntryBody']",'font_size',24)
setatt("//*[@name='journalMessage']",'pos','300,-762')
setatt("//*[@name='journalMessage']",'width',600)
a=E.SubElement(c,'append',xpath=base+"//*[@name='journalReader']")
button(a,'journalReadToggle','xuiRebirthJournalMarkRead',24,-760,260)
a=E.SubElement(c,'append',xpath=base+"//*[@name='journalIndex']")
button(a,'journalReadAll','xuiRebirthJournalReadAll',300,-762,244)
button(a,'journalFilterUnread','xuiRebirthJournalUnread',220,-702,150)
setatt("//*[@name='journalFilterLoreLabel']",'text_key','xuiRebirthJournalGuide')
a=E.SubElement(c,'append',xpath=base)
o=E.SubElement(a,'panel',name='journalImageOverlay',pos='8,-70',width='1856',height='813',depth='400',visible='false')
E.SubElement(o,'button',name='journalOverlayBlocker',width='1856',height='813',sprite='menu_empty',defaultcolor='12,12,16,255',hovercolor='12,12,16,255',depth='100',hoverscale='1')
v=E.SubElement(o,'panel',name='journalImageViewport',pos='28,-16',width='1800',height='690',depth='410',clipping='SoftClip',clippingsize='1800,690',clippingcenter='900,-345',clippingsoftness='0,0')
E.SubElement(v,'texture',name='journalLargeImage',width='1226',height='690',depth='110')
E.SubElement(v,'button',name='journalImageInput',width='1800',height='690',depth='115',sprite='menu_empty',defaultcolor='0,0,0,1',hovercolor='0,0,0,1',on_scroll='true',on_drag='true',hoverscale='1')
button(o,'journalImageClose','xuiRebirthJournalCloseImage',1500,-740,320,120)
E.SubElement(o,'sprite',name='journalMagnifier',sprite='ui_game_symbol_search',pos='30,-707',width='24',height='24',depth='121')
E.SubElement(o,'label',text_key='xuiRebirthJournalMouseHint',pos='28,-745',width='1280',height='30',font_size='22',depth='121')
E.indent(cfg,space='  ');(root/'Config/XUi_InGame/journal_guides.xml').write_bytes(E.tostring(cfg,pretty_print=True,encoding='utf-8'))
p=root/'Config/XUi_InGame/windows.xml';s=p.read_text(encoding='utf-8-sig')
if 'filename="journal_guides.xml"' not in s:s=s.rsplit('</configs>',1)[0]+'<include filename="journal_guides.xml"/>\n</configs>\n';p.write_text(s,encoding='utf-8')
p=root/'Scripts/UI/RebirthScreenLayout.cs';s=p.read_text();s=s.replace('child.ViewComponent.ID != "journalContent" && child.ViewComponent.ID != "creativeCatalogue"','child.ViewComponent.ID != "journalContent" && child.ViewComponent.ID != "journalImageOverlay" && child.ViewComponent.ID != "creativeCatalogue"');p.write_text(s)
p=root/'Scripts/UI/XUiC_RebirthJournal.cs';s=p.read_text();s=s.replace('layout?.Apply();if(resetReader)', 'layout?.Apply();if(guideRevision!=RebirthJournalGuideService.Revision&&!editing){entries.RemoveAll(e=>e.Authored);entries.AddRange(RebirthJournalGuideService.Entries);guideRevision=RebirthJournalGuideService.Revision;Render();}if(resetReader)');p.write_text(s)
print('Journal UI patch generated')
