import {readFileSync,writeFileSync} from 'node:fs';
const d='Tools/GameBridge/';
let runner=readFileSync(d+'test_poi_input_owned.mjs','utf8').replace('test_poi_input_owned_fixture.cs','test_poi_transitive_owned_fixture.cs');
runner=runner.replace("const fixture=await readFile",`const player=await readFile(join(root,'Scripts/GameBridge/RebirthGameBridgePlayer.cs'),'utf8'),path=await readFile(join(root,'Scripts/GameBridge/RebirthGameBridgePath.cs'),'utf8');
const playerMembers=player.slice(player.indexOf('    private static IEnumerator TurnOwned('),player.indexOf('    // ------------------------------------------------------------------ movement'));
const pathMembers=path.slice(path.indexOf('    private static IEnumerator FollowPathOwned('),path.lastIndexOf('}'));
const fixture=await readFile`).replace(".replace('// PRODUCTION_UI',uiMembers)",".replace('// PRODUCTION_UI',uiMembers).replace('// PRODUCTION_PLAYER',playerMembers).replace('// PRODUCTION_PATH',pathMembers)");
writeFileSync(d+'test_poi_transitive_owned.mjs',runner);
let f=readFileSync(d+'test_poi_input_owned_fixture.cs','utf8');
f=f.replace('struct Vector3 {','struct Vector3 {public float magnitude{get{return (float)Math.Sqrt(sqrMagnitude);}}public static Vector3 operator +(Vector3 a,Vector3 b){return new Vector3(a.x+b.x,a.y+b.y,a.z+b.z);}');
f=f.replace('static class Mathf {','static class Mathf {public const float Rad2Deg=57.29578f;public static float Atan2(float a,float b){return (float)Math.Atan2(a,b);}public static float Abs(float a){return Math.Abs(a);}public static float DeltaAngle(float a,float b){return b-a;}public static float Max(float a,float b){return Math.Max(a,b);}public static float Min(float a,float b){return Math.Min(a,b);}');
f=f.replace('class PlayerActionsLocal {','class PlayerActionsLocal {public PlayerAction Primary=new PlayerAction{Name="Primary"},Activate=new PlayerAction{Name="Activate"},MoveForward=new PlayerAction{Name="Forward"},Run=new PlayerAction{Name="Run"},MoveLeft=new PlayerAction{Name="Left"},MoveRight=new PlayerAction{Name="Right"},Jump=new PlayerAction{Name="Jump"};');
f=f.replace('class ItemValue {','class ItemValue {public float UseTimes,MaxUseTimes=100;public string Variant="a";');
f=f.replace('class ItemStack {','class ItemStack {public int count=1;').replace('public bool IsEmpty(){return false;}public ItemStack()','public bool IsEmpty(){return count<=0;}public ItemStack()');
f=f.replace('class Inventory {public int holdingItemIdx,SelectedSlot;public Hand Hand=new Hand();public ItemStack GetItem(int slot){return new ItemStack();}}','class Inventory {public int holdingItemIdx,SelectedSlot;public Hand Hand=new Hand();public ItemStack[] Items=Enumerable.Range(0,20).Select(x=>new ItemStack{count=0}).ToArray();public ItemStack GetItem(int slot){return Items[slot];}}');
f=f.replace('class World {public EntityPlayerLocal Primary;','class World {public BlockValue Block=new BlockValue();public BlockValue GetBlock(int x,int y,int z){return Block;}public EntityPlayerLocal Primary;');
f=f.replace('class EntityPlayerLocal {','class EntityPlayerLocal {public Vector3 position,rotation;public bool onGround=true;public Stats Stats=new Stats();');
f=f.replace('private static string HeldName(EntityPlayerLocal p){return "crate";}','private static string HeldName(EntityPlayerLocal p){return p.inventory.GetItem(p.inventory.holdingItemIdx).itemValue.ItemClass.GetItemName();}public static bool HandsBusy(EntityPlayerLocal p){return false;}');
f=f.replace('public static int ToolbeltSlot(EntityPlayerLocal p,Func<ItemClass,bool> want,out string name,Func<ItemStack,bool> match=null){name="crate";return Assigned?0:-1;}','public static bool RealSlots;public static int ToolbeltSlot(EntityPlayerLocal p,Func<ItemClass,bool> want,out string name,Func<ItemStack,bool> match=null){name="crate";if(!RealSlots)return Assigned?0:-1;for(int i=0;i<20;i++){var s=p.inventory.GetItem(i);if(!s.IsEmpty()&&want(s.itemValue.ItemClass)&&(match==null||match(s))){name=s.itemValue.ItemClass.GetItemName();return i;}}return -1;}');
f=f.replace('public static string HeldItemName(){return null;}','public static string HeldItemName(){return CursorItem==null?null:"carried";}');
f=f.replace('class Driver:IDisposable',`struct Vector3i {public int x,y,z;public Vector3i(int a,int b,int c){x=a;y=b;z=c;}}
class Stats {public Stat Stamina=new Stat();}class Stat{public float Value=100,ModifiedMax=100;}
class Material {public string id="wood",DamageCategory="wood";}class Block {public Material blockMaterial=new Material();public string GetActivationText(World w,BlockValue b,Vector3i pos,EntityPlayerLocal p){return "Locked";}}
class BlockValue {public bool isair;public Block Block=new Block();}
class BridgeRequest {public string Method,Path;public bool IsAbandoned;public void Complete(object value,int code=200){}}
class JObject:Dictionary<string,object>{}
static class RebirthGameBridgeTerrain {public class Line{public bool JumpNeeded,Safe=true;public float SafeLength=3;public string Why;}public static Action Probe;public static Vector3 BestDirection(Vector3 p,Vector3 to,float length,out Line line){Probe?.Invoke();line=new Line();return to;}}
static class RebirthGameBridgePoiStorage {public static string OwnedItemKey(ItemStack s){return s==null||s.IsEmpty()?null:s.itemValue.ItemClass.Name+"/"+s.itemValue.Variant+"/"+s.itemValue.UseTimes;}}
static class RebirthGameBridgePlayer {
static int activeMoves,movementGeneration;public static string LastWalkResult;public static int Turns;public static bool Open,DoorPresent;public static float SmoothTurn(EntityPlayerLocal p,float yaw,float pitch,float time=.12f){Turns++;p.rotation=new Vector3(pitch,yaw);return 0;}public static float SmoothAimAt(EntityPlayerLocal p,Vector3 point,float time=.12f){Turns++;return 0;}public static bool DoorIsOpen(EntityPlayerLocal p,Vector3i b){return Open;}public static bool DoorAhead(EntityPlayerLocal p,out Vector3i b){b=new Vector3i();return DoorPresent;}static int BlockHitPoints(EntityPlayerLocal p,Vector3i b){return 100;}static string StripColors(string s){return s;}static bool CrosshairOnBlock(EntityPlayerLocal p,Vector3i b){return true;}static JObject DescribeTarget(EntityPlayerLocal p){return new JObject();}static object Vec(Vector3 p){return p;}static float Round(float f){return f;}
// PRODUCTION_PLAYER
}
static class RebirthGameBridgePath {public class Step{public Vector3 Pos;public bool Door;public Vector3i DoorBlock;}public static string LastFailure;public static List<Step> Planned;public static Action Planning;static List<Step> Plan(EntityPlayerLocal p,Vector3 from,Vector3 to){Planning?.Invoke();return Planned;}
// PRODUCTION_PATH
}
class Driver:IDisposable`);
f=f.replace('using System.Collections.Generic;','using System.Collections.Generic;using System.Linq;');
// Transitive suite has its own native state setup, retaining the shared driver/default dependency definitions.
let start=f.indexOf(' static void Main(){');f=f.slice(0,start)+` static ItemStack Tool(string name,string variant="a"){return new ItemStack{itemValue=new ItemValue{ItemClass=new ItemClass{Name=name},Variant=variant}};}
 static void StepAll(Driver d,EntityPlayerLocal p,Action tick=null){int n=0;while(d.Step()){if(RebirthGameBridgeInput.IsHeld(RebirthGameBridgeInput.Slot))p.inventory.holdingItemIdx=p.inventory.SelectedSlot;tick?.Invoke();if(++n>1200)throw new Exception("timeout");}}
 static EntityPlayerLocal Fresh(){var p=NewPlayer();RebirthGameBridgeNeeds.RealSlots=true;RebirthGameBridgePlayer.Turns=0;RebirthGameBridgePlayer.Open=false;RebirthGameBridgePlayer.DoorPresent=false;RebirthGameBridgeTerrain.Probe=null;RebirthGameBridgePath.Planning=null;return p;}
 static void Main(){
 var p=Fresh();var parent=new RebirthGameBridgeInput.OwnedInputScope(p,()=>true);using(var d=new Driver(RebirthGameBridgePlayer.TurnToRoutine(p,()=>{GameManager.Instance.World=new World();return new Vector3();},0,0,4,parent)))StepAll(d,p);A(RebirthGameBridgePlayer.Turns==0,"point callback replacing world refuses native camera before mutation");parent.Dispose();
 p=Fresh();parent=new RebirthGameBridgeInput.OwnedInputScope(p,()=>true);RebirthGameBridgeTerrain.Probe=()=>p.world.Primary=new EntityPlayerLocal();using(var d=new Driver(RebirthGameBridgePlayer.WalkToGuarded(p,new Vector3(0,0,10),1,10,()=>null,s=>{},parent)))StepAll(d,p);A(RebirthGameBridgePlayer.Turns==0&&!RebirthGameBridgeInput.IsHeld(RebirthGameBridgeInput.Local.MoveForward),"terrain callback swapping primary refuses camera and movement");parent.Dispose();
 p=Fresh();parent=new RebirthGameBridgeInput.OwnedInputScope(p,()=>true);RebirthGameBridgePath.Planned=new List<RebirthGameBridgePath.Step>{new RebirthGameBridgePath.Step(),new RebirthGameBridgePath.Step{Pos=new Vector3(0,0,10)}};RebirthGameBridgePath.Planning=()=>GameManager.Instance.World=new World();bool ok=true;using(var d=new Driver(RebirthGameBridgePath.GoTo(p,new Vector3(0,0,10),1,10,s=>{},r=>ok=r,parent)))StepAll(d,p);A(!ok&&RebirthGameBridgePlayer.Turns==0,"planning callback replacing world refuses route actions");parent.Dispose();
 p=Fresh();parent=new RebirthGameBridgeInput.OwnedInputScope(p,()=>true);using(var d=new Driver(RebirthGameBridgePath.GoTo(p,new Vector3(0,0,10),1,10,s=>{},r=>{},parent))){A(d.Step()&&RebirthGameBridgeInput.IsHeld(RebirthGameBridgeInput.Local.MoveForward),"owned route issues real movement entry");GameManager.Instance.World=new World();RebirthGameBridgeInput.Tick(RebirthGameBridgeInput.Local.MoveForward);A(!RebirthGameBridgeInput.IsHeld(RebirthGameBridgeInput.Local.MoveForward),"native movement injection blocked before iterator continuation");}parent.Dispose();
 const string axe="meleeToolAxeT1IronFireaxe";p=Fresh();p.inventory.Items[0]=Tool(axe);var original=p.inventory.Items[0];parent=new RebirthGameBridgeInput.OwnedInputScope(p,()=>true);string result=null;using(var d=new Driver(RebirthGameBridgePlayer.BreakBlockRoutine(p,new Vector3i(),axe,s=>result=s,parent)))StepAll(d,p,()=>{if(RebirthGameBridgeInput.IsHeld(RebirthGameBridgeInput.Local.Primary)){original.itemValue.UseTimes++;p.world.Block.isair=true;}});A(result!=null&&result.StartsWith("broke through")&&parent.Admitted&&ReferenceEquals(original,p.inventory.GetItem(0))&&original.itemValue.UseTimes==1,"positive same native original tool wear completes without obsolete fullkey restoration");parent.Dispose();
 p=Fresh();p.inventory.Items[0]=Tool("club");p.inventory.Items[1]=Tool(axe);original=p.inventory.Items[0];parent=new RebirthGameBridgeInput.OwnedInputScope(p,()=>true);result=null;using(var d=new Driver(RebirthGameBridgePlayer.BreakBlockRoutine(p,new Vector3i(),axe,s=>result=s,parent)))StepAll(d,p,()=>{if(RebirthGameBridgeInput.IsHeld(RebirthGameBridgeInput.Local.Primary)){p.inventory.GetItem(1).itemValue.UseTimes++;p.world.Block.isair=true;}});A(result.StartsWith("broke through")&&p.inventory.holdingItemIdx==0&&ReferenceEquals(original,p.inventory.GetItem(0)),"different genuine tool restores exact original fullkey");parent.Dispose();
 p=Fresh();p.inventory.Items[0]=Tool(axe);parent=new RebirthGameBridgeInput.OwnedInputScope(p,()=>true);result=null;using(var d=new Driver(RebirthGameBridgePlayer.BreakBlockRoutine(p,new Vector3i(),axe,s=>result=s,parent)))StepAll(d,p,()=>{if(RebirthGameBridgeInput.IsHeld(RebirthGameBridgeInput.Local.Primary)){p.inventory.Items[0]=Tool(axe);p.world.Block.isair=true;}});A(!parent.Admitted&&result.Contains("custody"),"samevariant native stack clone replacement refused");parent.Dispose();
 p=Fresh();p.inventory.Items[0]=Tool(axe);parent=new RebirthGameBridgeInput.OwnedInputScope(p,()=>true);result=null;using(var d=new Driver(RebirthGameBridgePlayer.BreakBlockRoutine(p,new Vector3i(),axe,s=>result=s,parent)))StepAll(d,p,()=>{if(RebirthGameBridgeInput.IsHeld(RebirthGameBridgeInput.Local.Primary)){p.inventory.Items[0].itemValue.UseTimes=100;p.world.Block.isair=true;}});A(!parent.Admitted&&result.Contains("repair"),"broken genuine original reports retained custody repair instead of success");parent.Dispose();
 p=Fresh();parent=new RebirthGameBridgeInput.OwnedInputScope(p,()=>true);result=null;using(var d=new Driver(RebirthGameBridgePlayer.BreakDoorRoutine(p,new Vector3i(),s=>result=s,parent)))StepAll(d,p);A(result.Contains("no ")&&!RebirthGameBridgeInput.IsHeld(RebirthGameBridgeInput.Local.Primary),"missing lockeddoor genuine tool never supplies or attacks");parent.Dispose();
 p=Fresh();parent=new RebirthGameBridgeInput.OwnedInputScope(p,()=>true);using(var d=new Driver(RebirthGameBridgePlayer.ApproachAndActivate(p,new Vector3i(),s=>{},2,10,parent))){A(d.Step(),"opencontainer approach yields");p.world.Primary=new EntityPlayerLocal();StepAll(d,p);}A(!RebirthGameBridgeInput.IsHeld(RebirthGameBridgeInput.Local.Activate),"opencontainer primary replacement refuses activation");parent.Dispose();
 Console.WriteLine("PASS "+ChecksRun+" actual-source guarded Player/Path transitive checks; native world/primary callbacks, route injection, genuine tool wear/restoration/replacement/repair, missingtool and activation; native dependencies doubled, no runtime claim.");
 }
}
`;
writeFileSync(d+'test_poi_transitive_owned_fixture.cs',f);
