import {readFile,writeFile} from 'node:fs/promises';
const runner=await readFile('Tools/GameBridge/test_poi_input_default.mjs','utf8');
let out=runner.replace("test_poi_input_default_fixture.cs","test_poi_input_owned_fixture.cs");
out=out.replace(/^const inputMembers=.*$/m,String.raw`const inputMembers=['    private sealed class Held','    private static void UpdateBindingsPrefix(','    private static bool CheckCursorActive(','    public static void SetCursor(','    public static void ReleaseCursor(','    public static void HoldFrames(','    public static void HoldSeconds(','    public static void Release(','    public static void ReleaseAll(','    public static bool IsHeld('].map(s=>member(input,s)).join('\n') + '\n' + input.slice(input.indexOf('    private sealed class FlagWrite'),input.indexOf('    /// <summary>UI pacing')) + '\n' + member(input,'    public sealed class OwnedInputScope');`);
out=out.replace(/^const needsMembers=.*$/m,String.raw`const needsMembers=['    public static IEnumerator Equip(','    public static IEnumerator Prepare(','    public static IEnumerator Equip(EntityPlayerLocal p, int slot, string expectName, Action<bool> done,','    private static IEnumerator EquipOwned(','    public static IEnumerator Prepare(EntityPlayerLocal p, Func<ItemClass, bool> want, string supplyItem, string label,','    private static IEnumerator PrepareOwned('].map(s=>member(needs,s)).join('\n');`);
out=out.replace(/^const uiMembers=.*$/m,String.raw`const uiMembers=['    private static IEnumerator Pause(','    public static IEnumerator GlideTo(','    public static IEnumerator DragItem(','    public static IEnumerator ClickAt(','    public static IEnumerator RunGuarded(','    public static IEnumerator GlideTo(Vector2 to,','    public static IEnumerator ClickAt(Vector2 point, RebirthGameBridgeInput.OwnedInputScope','    private static IEnumerator ClickOwned(','    public static IEnumerator DragItem(Vector2 from, Vector2 to,','    private static IEnumerator DragOwned(','    public static IEnumerator CloseMenus(RebirthGameBridgeInput.OwnedInputScope','    private static IEnumerator CloseOwned('].map(s=>member(ui,s)).join('\n');`);
await writeFile('Tools/GameBridge/test_poi_input_owned.mjs',out);
let f=await readFile('Tools/GameBridge/test_poi_input_default_fixture.cs','utf8');
f=f.replace('public static bool Shift,Control,Alt,LockCursor;','');
f=f.replace('class EntityPlayerLocal {','class World {public EntityPlayerLocal Primary;public EntityPlayerLocal GetPrimaryPlayer(){return Primary;}} class GameManager {public static GameManager Instance=new GameManager();public World World;} class EntityPlayerLocal {public World world=new World();');
f=f.replace('public ItemStack(){}','public bool IsEmpty(){return false;}public ItemStack(){}');
f=f.replace('public static PlayerAction Find(string name)', 'public static IEnumerable<PlayerAction> FindByKey(string key){return new[]{Slot};}public static PlayerAction Find(string name)');
f=f.replace('public static ItemStack HeldItem(){return null;}', 'public static ItemStack CursorItem;public static ItemStack HeldItem(){return CursorItem;}public static bool IsWindowOpen(string window){return false;}public static bool TryFindById(string id,out Vector2 p){p=new Vector2();return false;}public static bool TryFindByText(string window,string text,out Vector2 p){p=new Vector2();return false;}');
await writeFile('Tools/GameBridge/test_poi_input_owned_fixture.cs',f);

