using System;
enum RebirthMetabolismSourceKind {HeldToolbelt,Backpack,HydrationSlot}
class ItemValue {public int type=1;public string Metadata="original";public ItemValue Clone(){return (ItemValue)MemberwiseClone();}public bool Equals(ItemValue b){return b!=null&&type==b.type&&Metadata==b.Metadata;}}
class ItemStack {public ItemValue itemValue=new ItemValue();public int count=3;public static ItemStack Empty=new ItemStack {count=0};public bool IsEmpty(){return count<=0;}public ItemStack Clone(){return new ItemStack {count=count,itemValue=itemValue.Clone()};}}
class Slots {public Slots ItemGrid=>this;public ItemStack[] items=>Items;public bool IgnoreWrites;public bool AlterWrite;public ItemStack[] Items={new ItemStack(),new ItemStack()};public int Writes;public ItemStack[] GetSlots(){return Items;}public void SetSlot(int i,ItemStack s){if(AlterWrite){s.count++;s.itemValue.Metadata="setter-change";}if(!IgnoreWrites)Items[i]=s;Writes++;}public void SetItem(int i,ItemStack s){SetSlot(i,s);}}
class EntityPlayer {public Slots bag=new Slots(),inventory=new Slots();}
class RebirthMetabolismState {public ItemStack HydrationSlotItem=new ItemStack();}
static class RebirthToolbeltCapacity {public static int GetOwnedSlotCount(EntityPlayer p,int length){return length-1;}}
static class RebirthBackpackLibraryReservation {public static bool Held;public static bool BlocksResourceUse(EntityPlayer p){return Held;}}
class Check {static void Assert(bool b,string m){if(!b)throw new Exception(m);}static void Main(){var p=new EntityPlayer();var s=new RebirthMetabolismState();var expected=p.bag.Items[0].Clone();var replacement=expected.Clone();replacement.count=2;
 p.bag.Items[0].itemValue.Metadata="different";Assert(!RebirthConsumptionSourceWriteback.TryCommit(p,RebirthMetabolismSourceKind.Backpack,0,expected,replacement,s)&&p.bag.Writes==0,"metadata conflict overwritten");p.bag.Items[0]=expected.Clone();p.bag.Items[0].count=4;Assert(!RebirthConsumptionSourceWriteback.TryCommit(p,RebirthMetabolismSourceKind.Backpack,0,expected,replacement,s),"count conflict overwritten");p.bag.Items[0]=expected.Clone();Assert(RebirthConsumptionSourceWriteback.TryCommit(p,RebirthMetabolismSourceKind.Backpack,0,expected,replacement,s)&&p.bag.Items[0].count==2,"matching bag failed");replacement.itemValue.Metadata="later";Assert(p.bag.Items[0].itemValue.Metadata=="original","replacement alias");
 Assert(!RebirthConsumptionSourceWriteback.TryCommit(p,RebirthMetabolismSourceKind.HeldToolbelt,1,expected,replacement,s)&&p.inventory.Writes==0,"dummy belt accepted");Assert(!RebirthConsumptionSourceWriteback.TryCommit(p,(RebirthMetabolismSourceKind)99,0,expected,replacement,s)&&p.inventory.Writes==0,"unknown source fell through");Assert(RebirthConsumptionSourceWriteback.TryCommit(p,RebirthMetabolismSourceKind.HeldToolbelt,0,expected,null,s)&&p.inventory.Items[0].IsEmpty(),"belt clear failed");Assert(RebirthConsumptionSourceWriteback.TryCommit(p,RebirthMetabolismSourceKind.HydrationSlot,-1,expected,replacement,s)&&s.HydrationSlotItem.count==2,"hydration write failed");Assert(!RebirthConsumptionSourceWriteback.TryCommit(p,RebirthMetabolismSourceKind.Backpack,-1,expected,replacement,s),"invalid index accepted"); p.bag.Items[0]=expected.Clone();p.bag.IgnoreWrites=true;Assert(!RebirthConsumptionSourceWriteback.TryCommit(p,RebirthMetabolismSourceKind.Backpack,0,expected,replacement,s)&&p.bag.Items[0].count==3,"ignored bag setter acknowledged");
 p.inventory.Items[0]=expected.Clone();p.inventory.IgnoreWrites=true;Assert(!RebirthConsumptionSourceWriteback.TryCommit(p,RebirthMetabolismSourceKind.HeldToolbelt,0,expected,replacement,s),"ignored belt setter acknowledged");
 RebirthBackpackLibraryReservation.Held=true;int writes=p.bag.Writes;Assert(!RebirthConsumptionSourceWriteback.TryCommit(p,RebirthMetabolismSourceKind.Backpack,0,expected,replacement,s)&&p.bag.Writes==writes,"held source setter reached");s.HydrationSlotItem=expected.Clone();Assert(!RebirthConsumptionSourceWriteback.TryCommit(p,RebirthMetabolismSourceKind.HydrationSlot,-1,expected,replacement,s)&&s.HydrationSlotItem.count==3,"held hydration source changed");
 RebirthBackpackLibraryReservation.Held=false;p.bag.IgnoreWrites=false;p.bag.AlterWrite=true;p.bag.Items[0]=expected.Clone();Assert(!RebirthConsumptionSourceWriteback.TryCommit(p,RebirthMetabolismSourceKind.Backpack,0,expected,replacement,s),"setter input mutation validated itself");
 Console.WriteLine("PASS: altered setter input; custody holds and ignored setters; metadata/count conflicts, detached write, bag/belt/hydration sources, dummy slot, invalid index and unknown-source rejection.");}}
