using System;using System.Linq;using System.Collections.Generic;
class World{public bool Remote;public bool IsRemote()=>Remote;}
class EntityPlayer{public World world=new World();}
class ItemClass{public string Name;public string GetItemName()=>Name;}
class ItemValue{public ItemClass ItemClass=new ItemClass();public Dictionary<string,object> Data=new Dictionary<string,object>();public bool TryGetMetadata<T>(string k,out T v){object o;if(Data.TryGetValue(k,out o)&&o is T){v=(T)o;return true;}v=default(T);return false;}}
class Recipe{public string Name;public string GetName()=>Name;}
class RebirthStablePlayerIdentity{}
class Progression{public RebirthCookingMemory Cooking=new RebirthCookingMemory();public HashSet<string> KnowledgeIds=new HashSet<string>();}
class RebirthWorldCharacterRecord{public Progression Progression=new Progression();}
class RebirthCookingMemory{public class Ticket{public string Recipe;public int OutputCount,Portions;public float XpMultiplier=1;}public Dictionary<string,Ticket> Tickets=new Dictionary<string,Ticket>();public Dictionary<string,int> Awards=new Dictionary<string,int>();public HashSet<string> PendingUnlocks=new HashSet<string>();public bool Acknowledge(string t,string r,int o,int c,out Ticket ticket,out int n){n=0;if(!Tickets.TryGetValue(t,out ticket))return false;int prior;Awards.TryGetValue(t,out prior);n=c-prior;Awards[t]=c;return n>0;}}
static class RebirthSkillAwardService{public static int Queued;public static void QueueOwnerPublication(EntityPlayer p){Queued++;}public static bool Eligible=true,Training=true;public static int XpCalls;public static RebirthWorldCharacterRecord Record;public static bool TryGetEligible(EntityPlayer p,out RebirthStablePlayerIdentity i,out RebirthWorldCharacterRecord r){i=new RebirthStablePlayerIdentity();r=Record;return Eligible;}public static bool TryPreviewCraft(EntityPlayer p,string s,object m,int c,float mult,out float current,out float gain){current=gain=0;return Training;}public static void TryAwardCraft(EntityPlayer p,string s,object m,int n,float mult,string key){XpCalls++;}}
static class RebirthServiceCraftSkillService{public static string ClassifyRecipe(string n)=>"skill.cooking";}
static class XUiM_Recipes{public static List<Recipe> GetRecipes()=>new List<Recipe>{new Recipe{Name="foodVegetableStew"}};}
static class RebirthCookingCatalogue{public static string Tool="toolCookingPot";public class Dish{public string Tool=RebirthCookingCatalogue.Tool;public List<string> Cards=new List<string>{"card"};}public static bool Known(EntityPlayer p,Recipe r)=>RebirthSkillAwardService.Record.Progression.KnowledgeIds.Contains("cooking.recipe."+r.Name);public static Dish Get(string n)=>new Dish();}
static class RebirthTheoryProgressionService{public static int Calls;public static bool TryAwardInsight(EntityPlayer p,string id,string source,out float applied,out bool already){if(id!="insight.cooking.successful_use_of_a_major_cooking_method")throw new Exception("Wrong Insight");Calls++;applied=1;already=false;return true;}}
class RebirthLiteratureDefinition{public string KnowledgeId="literature.read.card";}
static class RebirthProgressionRuntimeConfig{public static bool TryGetLiterature(string c,out RebirthLiteratureDefinition d){d=new RebirthLiteratureDefinition();return true;}}
static class RebirthSurvivorNetworkService{public static int Sends;public static bool SendOwnerState(EntityPlayer p,long n,bool b,string s){if(!RebirthWorldCharacterService.Dirty)throw new Exception("Snapshot before revision update");if(!RebirthSkillAwardService.Record.Progression.Cooking.PendingUnlocks.Contains("foodVegetableStew"))throw new Exception("Snapshot before pending notice");Sends++;return false;}}
static class RebirthWorldCharacterService{public static bool SaveSucceeds=true;public static int Saves;public static bool Dirty;public static void MarkDirty(RebirthWorldCharacterRecord r,string s){Dirty=true;}public static bool FlushPlayer(EntityPlayer p,string s){Saves++;return SaveSucceeds;}}
static class RebirthStatisticsService{public static int Crafted;public static void RecordItemsCrafted(EntityPlayer p,string n,int count){Crafted+=count;}}
static class Subject{const string Prefix="rebirth.cooking.";public static bool Witness=true;static bool HasCompletionWitness(string t,int c)=>Witness;static object TrainingModel(EntityPlayer p,string t,string n,int o)=>new object();
// PRODUCTION_METHOD
}
class Check{static EntityPlayer player;static ItemValue receipt;static RebirthWorldCharacterRecord record;static void Reset(){RebirthTheoryProgressionService.Calls=0;RebirthCookingCatalogue.Tool="toolCookingPot";RebirthWorldCharacterService.SaveSucceeds=true;RebirthSurvivorNetworkService.Sends=0;RebirthSkillAwardService.Queued=0;RebirthWorldCharacterService.Dirty=false;player=new EntityPlayer();receipt=new ItemValue();receipt.ItemClass.Name="foodVegetableStew";receipt.Data["rebirth.cooking.token"]="ticket";receipt.Data["rebirth.cooking.completed"]=1;record=new RebirthWorldCharacterRecord();record.Progression.Cooking.Tickets["ticket"]=new RebirthCookingMemory.Ticket{Recipe="foodVegetableStew",OutputCount=1,Portions=1};RebirthSkillAwardService.Record=record;RebirthSkillAwardService.Eligible=true;RebirthSkillAwardService.Training=true;RebirthSkillAwardService.XpCalls=0;Subject.Witness=true;RebirthStatisticsService.Crafted=0;}
static void Assert(bool v,string s){if(!v)throw new Exception(s);}static void Run()=>Subject.AwardCompleted(player,"foodVegetableStew",receipt,1);
static void Main(){Reset();RebirthSkillAwardService.Training=false;Run();Assert(record.Progression.KnowledgeIds.Contains("cooking.recipe.foodVegetableStew"),"XP failure prevented discovery");Assert(record.Progression.KnowledgeIds.Contains("literature.read.card"),"card knowledge absent");Assert(record.Progression.Cooking.PendingUnlocks.Contains("foodVegetableStew"),"notification not queued");Assert(RebirthSkillAwardService.XpCalls==0,"unsupported XP awarded");Assert(RebirthSkillAwardService.Queued==1,"failed publication not queued");Assert(RebirthTheoryProgressionService.Calls==1,"witnessed method Insight missing");Run();Assert(RebirthTheoryProgressionService.Calls==1,"duplicate completion Insight");Assert(RebirthStatisticsService.Crafted==1,"duplicate completion credited");Reset();Subject.Witness=false;Run();Assert(record.Progression.KnowledgeIds.Count==0&&record.Progression.Cooking.Awards.Count==0,"unwitnessed receipt granted");Reset();player.world.Remote=true;Run();Assert(record.Progression.KnowledgeIds.Count==0,"client locally granted");Reset();RebirthSkillAwardService.Eligible=false;Run();Assert(record.Progression.KnowledgeIds.Count==0,"creation hold granted");Reset();receipt.Data["rebirth.cooking.completed"]=2;Run();Assert(record.Progression.KnowledgeIds.Count==0,"oversized receipt granted");Reset();Run();Assert(RebirthSkillAwardService.XpCalls==1,"valid XP missing");Reset();RebirthWorldCharacterService.SaveSucceeds=false;Run();Assert(RebirthSkillAwardService.Queued==1&&RebirthSurvivorNetworkService.Sends==0&&record.Progression.Cooking.PendingUnlocks.Contains("foodVegetableStew")&&record.Progression.Cooking.Awards.Count==1,"failed save retains completion without publication");Run();Assert(RebirthSkillAwardService.XpCalls==1&&RebirthStatisticsService.Crafted==1&&RebirthSkillAwardService.Queued==1,"failed-save repeat cannot reaward");Reset();RebirthCookingCatalogue.Tool="";Run();Assert(RebirthTheoryProgressionService.Calls==0,"empty tool grants Insight");Reset();RebirthCookingCatalogue.Tool="toolCookingGrill";Run();Assert(RebirthTheoryProgressionService.Calls==1,"grill Insight missing");Console.WriteLine("PASS extracted production AwardCompleted: discovery without XP; pending notification; duplicate/authority/witness/eligibility/count guards; valid XP; failed-save retained completion/no immediate publication/no duplicate awards. Native services are test doubles, not a P2P test.");}}