using System;using System.Collections;using System.Collections.Generic;using System.Linq;
struct Vector2 {public float x,y;public Vector2(float a,float b){x=a;y=b;}public static Vector2 Lerp(Vector2 a,Vector2 b,float t){return new Vector2(a.x+(b.x-a.x)*t,a.y+(b.y-a.y)*t);}public static float Distance(Vector2 a,Vector2 b){return (float)Math.Sqrt((a.x-b.x)*(a.x-b.x)+(a.y-b.y)*(a.y-b.y));}public static explicit operator Vector2(Vector3 a){return new Vector2(a.x,a.y);}}
struct Vector3 {public float magnitude{get{return (float)Math.Sqrt(sqrMagnitude);}}public static Vector3 operator +(Vector3 a,Vector3 b){return new Vector3(a.x+b.x,a.y+b.y,a.z+b.z);}public float x,y,z;public Vector3(float a,float b,float c=0){x=a;y=b;z=c;}public static Vector3 operator -(Vector3 a,Vector3 b){return new Vector3(a.x-b.x,a.y-b.y,a.z-b.z);}public float sqrMagnitude{get{return x*x+y*y+z*z;}}}
static class Mathf {public const float Rad2Deg=57.29578f;public static float Atan2(float a,float b){return (float)Math.Atan2(a,b);}public static float Abs(float a){return Math.Abs(a);}public static float DeltaAngle(float a,float b){return b-a;}public static float Max(float a,float b){return Math.Max(a,b);}public static float Min(float a,float b){return Math.Min(a,b);}public static float Clamp(float a,float min,float max){return Math.Max(min,Math.Min(max,a));}}
static class Time {public static int frameCount;public static float realtimeSinceStartup;}
static class Application {public static bool isFocused=true;}
static class Input {public static Vector3 mousePosition;}
class NativeCamera {public Action Project;public Vector3 ScreenToWorldPoint(Vector2 p){Project?.Invoke();return new Vector3(p.x,p.y);}}class UICamera{public NativeCamera Camera=new NativeCamera();public Action GetCamera;public NativeCamera cachedCamera{get{GetCamera?.Invoke();return Camera;}}}class SoftCursor{public UICamera Camera=new UICamera();public Action GetUiCamera;public UICamera uiCamera{get{GetUiCamera?.Invoke();return Camera;}}public int Writes;public Vector3 LastPosition;public Vector3 Position{set{LastPosition=value;Writes++;}}}
class PlayerAction {public Action OnUpdate;public string Name;public int Updates;public float Last;public void UpdateWithValue(float value,ulong tick,float delta){Updates++;Last=value;OnUpdate?.Invoke();}}
class Permanent {public PlayerAction Inventory=new PlayerAction{Name="Inventory"};}
class PlayerActionsLocal {public PlayerAction Primary=new PlayerAction{Name="Primary"},Activate=new PlayerAction{Name="Activate"},MoveForward=new PlayerAction{Name="Forward"},Run=new PlayerAction{Name="Run"},MoveLeft=new PlayerAction{Name="Left"},MoveRight=new PlayerAction{Name="Right"},Jump=new PlayerAction{Name="Jump"};public Permanent PermanentActions=new Permanent();}
static class RebirthGameBridgeInput {
 private static readonly Dictionary<PlayerAction,Held> held=new Dictionary<PlayerAction,Held>();public static float Pace=.55f;public static bool CursorActive{get;private set;}public static Vector2 CursorPosition{get;private set;}private static Vector3 realMouseAtActivation;
 public static PlayerAction Click=new PlayerAction{Name="gui.LeftClick"},Slot=new PlayerAction{Name="InventorySlot2"};public static PlayerActionsLocal Local=new PlayerActionsLocal();public static PlayerActionsLocal LocalActions(){return Local;}public static IEnumerable<PlayerAction> FindByKey(string key){return new[]{Slot};}public static PlayerAction Find(string name){if(name=="gui.LeftClick")return Click;Slot.Name=name;return Slot;}
 // PRODUCTION_INPUT
 public static void Tick(PlayerAction action){UpdateBindingsPrefix(action,1,.1f);}public static bool CursorCheck(){return CheckCursorActive();}public static Vector2 Screen(){var p=new Vector2(900,900);GetScreenPositionPostfix(ref p);return p;}public static void MoveCursor(SoftCursor cursor){HandleMovementPostfix(cursor);}public static bool NativeShift(bool physical){ShiftPostfix(ref physical);return physical;}
}
class ItemClass {public string Name="crate";public int Type=1;public string GetItemName(){return Name;}public static ItemValue GetItem(string name,bool unused){return new ItemValue{ItemClass=new ItemClass{Name=name}};}}
class ItemValue {public float UseTimes,MaxUseTimes=100;public string Variant="a";public int type=1;public ItemClass ItemClass=new ItemClass();public ItemValue(){}public ItemValue(int type,int a,int b,bool c){this.type=type;}public bool IsEmpty(){return false;}}
class ItemStack {public int count=1;public ItemValue itemValue=new ItemValue();public bool IsEmpty(){return count<=0;}public ItemStack Clone(){return new ItemStack{count=count,itemValue=new ItemValue{type=itemValue.type,ItemClass=itemValue.ItemClass,UseTimes=itemValue.UseTimes,MaxUseTimes=itemValue.MaxUseTimes,Variant=itemValue.Variant}};}public ItemStack(){}public ItemStack(ItemValue value,int count){itemValue=value;}}
class Hand {public bool Fault;public int Changes;public void OnSlotChanged(int slot){if(Fault)throw new InvalidOperationException();Changes++;}}
class Inventory {public int holdingItemIdx,SelectedSlot;public Hand Hand=new Hand();public Grid ItemGrid;public Inventory(){ItemGrid=new Grid{items=Items};}public ItemStack[] Items=Enumerable.Range(0,20).Select(x=>new ItemStack{count=0}).ToArray();public ItemStack GetItem(int slot){return Items[slot];}}
class Grid{public ItemStack[] items;}class Bag {public Grid ItemGrid=new Grid{items=new[]{new ItemStack()}};public bool AddItem(ItemStack stack){return true;}}
class World {public BlockValue Block=new BlockValue();public BlockValue GetBlock(int x,int y,int z){return Block;}public EntityPlayerLocal Primary;public Action PrimaryRead;public EntityPlayerLocal GetPrimaryPlayer(){var p=Primary;PrimaryRead?.Invoke();return p;}} class GameManager {public static GameManager Instance=new GameManager();public World World;} class EntityPlayerLocal {public Vector3 position,rotation;public bool onGround=true;public Stats Stats=new Stats();public World world=new World();public Inventory inventory=new Inventory();public Bag bag=new Bag();public bool Dead;public bool IsDead(){return Dead;}}
class ToolbeltConfig {public static ToolbeltConfig CurrentConfig=new ToolbeltConfig();public int SlotsPerBar=10;}
static class RebirthGameBridgeNeeds {
 public static bool Supply=false,Assigned;public static int ToolbeltSize(EntityPlayerLocal p){return 20;}private static string HeldName(EntityPlayerLocal p){return p.inventory.GetItem(p.inventory.holdingItemIdx).itemValue.ItemClass.GetItemName();}public static bool HandsBusy(EntityPlayerLocal p){return false;}public static IEnumerator WaitHandsFree(EntityPlayerLocal p,float timeout){yield return null;}private static IEnumerator Wait(float seconds){float end=Time.realtimeSinceStartup+seconds;while(Time.realtimeSinceStartup<end)yield return null;}
 public static bool RealSlots;public static int ToolbeltSlot(EntityPlayerLocal p,Func<ItemClass,bool> want,out string name,Func<ItemStack,bool> match=null){name="crate";if(!RealSlots)return Assigned?0:-1;for(int i=0;i<20;i++){var s=p.inventory.GetItem(i);if(!s.IsEmpty()&&want(s.itemValue.ItemClass)&&(match==null||match(s))){name=s.itemValue.ItemClass.GetItemName();return i;}}return -1;}private static string BestInBag(EntityPlayerLocal p,Func<ItemClass,bool> want,Func<ItemStack,bool> match){if(!RealSlots)return "crate";foreach(var s in p.bag.ItemGrid.items)if(s!=null&&!s.IsEmpty()&&want(s.itemValue.ItemClass)&&(match==null||match(s)))return s.itemValue.ItemClass.GetItemName();return null;}private static int FreeableToolbeltSlot(EntityPlayerLocal p,Func<ItemClass,bool> want){return 0;}
 // PRODUCTION_NEEDS
}
static class RebirthGameBridgeUi {
 public static object OpenWindowIds(){return null;}public static bool AnyModalOpen(){return true;}public static IEnumerator LookAtWindow(){yield return null;}public static IEnumerator CloseMenus(){yield return null;}public static bool TryFindEmptyToolbeltSlot(out Vector2 point,out int slot){point=new Vector2(20,20);slot=0;return true;}public static bool TryFindToolbeltSlot(int slot,out Vector2 point){point=new Vector2();return true;}public static bool TryFindEmptyBackpackSlot(out Vector2 point){point=new Vector2();return true;}public static bool TryFindItemSlot(string name,bool belt,out Vector2 point,Func<ItemStack,bool> match){point=new Vector2(10,10);return true;}public static ItemStack CursorItem;public static ItemStack HeldItem(){return CursorItem;}public static bool IsWindowOpen(string window){return false;}public static bool TryFindById(string id,out Vector2 p){p=new Vector2();return false;}public static bool TryFindByText(string window,string text,out Vector2 p){p=new Vector2();return false;}public static string HeldItemName(){return CursorItem==null?null:"carried";}
 public class Rect {public Vector2 center;}
 public class NativeGrid {public Action Visibility;public bool HasVisibleCenter(int i){Visibility?.Invoke();return true;}}
 public class NativeUi {public PlayerUi playerUI;}public class PlayerUi{public EntityPlayerLocal entityPlayer;}
 public class XUiC_Backpack{}public class XUiC_RebirthCraftingInventoryScroll{public bool IsSlotVisible(int i){return true;}}
 public class NativeView {public Action ReadVisible;public bool Visible=true;public bool IsVisible{get{ReadVisible?.Invoke();return Visible;}}}
 public class XUiC_TextInput{public NativeUi xui;public NativeView ViewComponent=new NativeView();public int Sets,Triggers;public Action SetText,Trigger;public string Text{set{Sets++;SetText?.Invoke();}}public void TriggerOnChangeHandler(bool ignored){Triggers++;Trigger?.Invoke();}}
 public static XUiC_TextInput TextControl;public static XUiC_RebirthContextSlot ContextControl;static T FindAncestor<T>(object o) where T:class{return null;}static T FindDescendant<T>(object o) where T:class{return null;}
 public class XUiC_ItemStack {public enum StackLocationTypes{ToolBelt,Backpack,LootContainer}public StackLocationTypes StackLocation;public NativeUi xui;public bool Foreign;public ItemStack ItemStack;public int SlotNumber;public T GetParentByType<T>() where T:class {return !Foreign&&typeof(T)==typeof(XUiC_Backpack)?new XUiC_Backpack() as T:null;}}
 public class XUiC_RebirthContextSlot:XUiC_ItemStack {public bool IsBackpack,IsPresented;public int Scrolls;public Action Scroll;public NativeGrid Grid=new NativeGrid();public void Scrolled(float d){Scrolls++;Scroll?.Invoke();}}
 public class FakeJson{readonly Dictionary<string,object> values=new Dictionary<string,object>();public object this[string key]{get{object v;return values.TryGetValue(key,out v)?v:null;}set{values[key]=value;}}}public class Node {public FakeJson Json=new FakeJson();public object Controller;public bool HasRect=true;public string Path;public Rect ScreenRect;}
 public static float SlotOffset;public static bool HideSlot,ForeignOnly,ForeignSpoofLocation;
 static IEnumerable<Node> Collect(string path,bool all){var p=GameManager.Instance.World?.GetPrimaryPlayer();if(p==null)yield break;if(path=="crafting"&&TextControl!=null){var n=new Node{Controller=TextControl};n.Json["id"]="searchInput";yield return n;yield break;}if(path==null&&ContextControl!=null){yield return new Node{Controller=ContextControl};yield break;}if(path=="dragAndDrop"){if(CursorItem!=null)yield return new Node{Path="dragAndDrop/0",Controller=new XUiC_ItemStack{xui=new NativeUi{playerUI=new PlayerUi{entityPlayer=p}},ItemStack=CursorItem},ScreenRect=new Rect()};yield break;}if(HideSlot)yield break;for(int group=0;group<2;group++){var slots=group==0?p.inventory.ItemGrid.items:p.bag.ItemGrid.items;for(int i=0;i<slots.Length;i++)yield return new Node{Path=(group==0?"toolbelt/":"bag/inventory/")+i,Controller=new XUiC_ItemStack{xui=new NativeUi{playerUI=new PlayerUi{entityPlayer=p}},Foreign=ForeignOnly,StackLocation=ForeignOnly&&!ForeignSpoofLocation?XUiC_ItemStack.StackLocationTypes.LootContainer:group==0?XUiC_ItemStack.StackLocationTypes.ToolBelt:XUiC_ItemStack.StackLocationTypes.Backpack,ItemStack=slots[i],SlotNumber=i},ScreenRect=new Rect{center=new Vector2((group==0?20:10)+i*2+SlotOffset,group==0?20:10)}};}}
 // PRODUCTION_UI
}
struct Vector3i {public int x,y,z;public Vector3i(int a,int b,int c){x=a;y=b;z=c;}}
class Stats {public Stat Stamina=new Stat();}class Stat{public float Value=100,ModifiedMax=100;}
class Material {public string id="wood",DamageCategory="wood";}class Block {public Material blockMaterial=new Material();public string GetActivationText(World w,BlockValue b,Vector3i pos,EntityPlayerLocal p){return "Locked";}}
class BlockValue {public bool isair;public Block Block=new Block();}
class BridgeRequest {public string Method,Path;public bool IsAbandoned;public void Complete(object value,int code=200){}}
class JObject:Dictionary<string,object>{}
static class RebirthGameBridgeTerrain {public class Line{public bool JumpNeeded,Safe=true;public float SafeLength=3;public string Why;}public static Action Probe;public static Vector3 BestDirection(Vector3 p,Vector3 to,float length,out Line line){Probe?.Invoke();line=new Line();return to;}}
static class RebirthGameBridgePoiStorage {public static string OwnedItemKey(ItemStack s){return s==null||s.IsEmpty()?null:s.itemValue.ItemClass.Name+"/"+s.itemValue.Variant+"/"+s.itemValue.UseTimes;}private static string RestoreKey(ItemStack s){return OwnedItemKey(s);}
// PRODUCTION_WEAR
}
static class RebirthGameBridgePlayer {
static int activeMoves,movementGeneration;public static string LastWalkResult;public static int Turns;public static bool Open,DoorPresent;public static float SmoothTurn(EntityPlayerLocal p,float yaw,float pitch,float time=.12f){Turns++;p.rotation=new Vector3(pitch,yaw);return 0;}public static float SmoothAimAt(EntityPlayerLocal p,Vector3 point,float time=.12f){Turns++;return 0;}public static bool DoorIsOpen(EntityPlayerLocal p,Vector3i b){return Open;}public static bool DoorAhead(EntityPlayerLocal p,out Vector3i b){b=new Vector3i();return DoorPresent;}static int BlockHitPoints(EntityPlayerLocal p,Vector3i b){return 100;}static string StripColors(string s){return s;}static bool CrosshairOnBlock(EntityPlayerLocal p,Vector3i b){return true;}static JObject DescribeTarget(EntityPlayerLocal p){return new JObject();}static object Vec(Vector3 p){return p;}static float Round(float f){return f;}
// PRODUCTION_PLAYER
}
static class RebirthGameBridgePath {public class Step{public Vector3 Pos;public bool Door;public Vector3i DoorBlock;}public static string LastFailure;public static List<Step> Planned;public static Action Planning;static List<Step> Plan(EntityPlayerLocal p,Vector3 from,Vector3 to){Planning?.Invoke();return Planned;}
// PRODUCTION_PATH
}
class Driver:IDisposable {public static Action BeforeInjection,AfterInjection;private readonly Stack<IEnumerator> stack=new Stack<IEnumerator>();public Driver(IEnumerator root){stack.Push(root);}public bool Step(){while(stack.Count>0){var it=stack.Peek();if(!it.MoveNext()){(stack.Pop() as IDisposable)?.Dispose();continue;}var child=it.Current as IEnumerator;if(child!=null){stack.Push(child);continue;}Time.frameCount++;Time.realtimeSinceStartup+=.1f;BeforeInjection?.Invoke();RebirthGameBridgeInput.Tick(RebirthGameBridgeInput.Click);RebirthGameBridgeInput.Tick(RebirthGameBridgeInput.Slot);AfterInjection?.Invoke();return true;}return false;}public void Dispose(){while(stack.Count>0)(stack.Pop() as IDisposable)?.Dispose();}}
class Checks {
 static int ChecksRun;static void A(bool b,string m){ChecksRun++;if(!b)throw new Exception(m);}static void Reset(){RebirthGameBridgeInput.ReleaseAll();RebirthGameBridgeInput.LockCursor=false;Time.frameCount=0;Time.realtimeSinceStartup=0;Input.mousePosition=new Vector3();Application.isFocused=true;RebirthGameBridgeUi.CursorItem=null;RebirthGameBridgeInput.Click.Updates=RebirthGameBridgeInput.Slot.Updates=0;RebirthGameBridgeNeeds.Assigned=false;}
 static EntityPlayerLocal NewPlayer(){Reset();var p=new EntityPlayerLocal();p.world.Primary=p;GameManager.Instance.World=p.world;return p;}
 static ItemStack Tool(string name,string variant="a"){return new ItemStack{itemValue=new ItemValue{ItemClass=new ItemClass{Name=name},Variant=variant}};}
 static void StepAll(Driver d,EntityPlayerLocal p,Action tick=null){int n=0;while(d.Step()){if(RebirthGameBridgeInput.IsHeld(RebirthGameBridgeInput.Slot))p.inventory.holdingItemIdx=RebirthGameBridgeInput.Slot.Name=="InventorySlot1"?0:1;tick?.Invoke();if(++n>1200)throw new Exception("timeout");}}
 static EntityPlayerLocal Fresh(){Driver.BeforeInjection=null;Driver.AfterInjection=null;RebirthGameBridgeInput.Click.OnUpdate=null;var p=NewPlayer();RebirthGameBridgeUi.TextControl=null;RebirthGameBridgeUi.ContextControl=null;RebirthGameBridgeInput.Slot.Name="InventorySlot2";RebirthGameBridgeNeeds.RealSlots=true;RebirthGameBridgePlayer.Turns=0;RebirthGameBridgePlayer.Open=false;RebirthGameBridgePlayer.DoorPresent=false;RebirthGameBridgeUi.SlotOffset=0;RebirthGameBridgeUi.HideSlot=false;RebirthGameBridgeUi.ForeignOnly=false;RebirthGameBridgeUi.ForeignSpoofLocation=false;RebirthGameBridgeTerrain.Probe=null;RebirthGameBridgePath.Planning=null;return p;}
 static IEnumerable<PlayerAction> Actions(){var a=RebirthGameBridgeInput.Local;return new[]{RebirthGameBridgeInput.Click,RebirthGameBridgeInput.Slot,a.Primary,a.Activate,a.MoveForward,a.Run,a.MoveLeft,a.MoveRight,a.Jump,a.PermanentActions.Inventory};}
 static void NativeTick(){foreach(var a in Actions())RebirthGameBridgeInput.Tick(a);}
 static void Sweep(string label,Func<EntityPlayerLocal,RebirthGameBridgeInput.OwnedInputScope,IEnumerator> make,Action<EntityPlayerLocal> setup=null,Action<EntityPlayerLocal> tick=null){
 int yields=0;var p=Fresh();setup?.Invoke(p);var root=new RebirthGameBridgeInput.OwnedInputScope(p,()=>true);using(var d=new Driver(make(p,root))){while(d.Step()){if(RebirthGameBridgeInput.IsHeld(RebirthGameBridgeInput.Slot))p.inventory.holdingItemIdx=RebirthGameBridgeInput.Slot.Name=="InventorySlot1"?0:1;tick?.Invoke(p);if(++yields>500)throw new Exception("sweep baseline timeout "+label);}}root.Dispose();
 for(int cut=0;cut<yields;cut++){p=Fresh();setup?.Invoke(p);root=new RebirthGameBridgeInput.OwnedInputScope(p,()=>true);using(var d=new Driver(make(p,root))){for(int n=0;n<=cut;n++){if(!d.Step())throw new Exception("early "+label);if(RebirthGameBridgeInput.IsHeld(RebirthGameBridgeInput.Slot))p.inventory.holdingItemIdx=RebirthGameBridgeInput.Slot.Name=="InventorySlot1"?0:1;tick?.Invoke(p);}int turns=RebirthGameBridgePlayer.Turns;GameManager.Instance.World=new World();int updates=Actions().Sum(a=>a.Updates);NativeTick();if(Actions().Sum(a=>a.Updates)!=updates)throw new Exception("late native injection "+label);StepAll(d,p);if(RebirthGameBridgePlayer.Turns!=turns)throw new Exception("late camera "+label);}root.Dispose();if(Actions().Any(RebirthGameBridgeInput.IsHeld))throw new Exception("owned hold leaked "+label);}
 A(yields>0,label+" every yielded boundary native replacement blocks further action/camera and releases only owned holds ("+yields+")");
 }
 static IEnumerator FaultAfterPickup(RebirthGameBridgeInput.OwnedInputScope scope){scope.TryHoldSeconds(RebirthGameBridgeInput.Click,0);RebirthGameBridgeUi.CursorItem=new ItemStack();yield return null;throw new InvalidOperationException("fixture move fault");}
 static void Main(){
 var p=Fresh();var parent=new RebirthGameBridgeInput.OwnedInputScope(p,()=>true);using(var d=new Driver(RebirthGameBridgePlayer.TurnToRoutine(p,()=>{GameManager.Instance.World=new World();return new Vector3();},0,0,4,parent)))StepAll(d,p);A(RebirthGameBridgePlayer.Turns==0,"point callback replacing world refuses native camera before mutation");parent.Dispose();
 p=Fresh();parent=new RebirthGameBridgeInput.OwnedInputScope(p,()=>true);RebirthGameBridgeTerrain.Probe=()=>p.world.Primary=new EntityPlayerLocal();using(var d=new Driver(RebirthGameBridgePlayer.WalkToGuarded(p,new Vector3(0,0,10),1,10,()=>null,s=>{},parent)))StepAll(d,p);A(RebirthGameBridgePlayer.Turns==0&&!RebirthGameBridgeInput.IsHeld(RebirthGameBridgeInput.Local.MoveForward),"terrain callback swapping primary refuses camera and movement");parent.Dispose();
 p=Fresh();parent=new RebirthGameBridgeInput.OwnedInputScope(p,()=>true);RebirthGameBridgePath.Planned=new List<RebirthGameBridgePath.Step>{new RebirthGameBridgePath.Step(),new RebirthGameBridgePath.Step{Pos=new Vector3(0,0,10)}};RebirthGameBridgePath.Planning=()=>GameManager.Instance.World=new World();bool ok=true;using(var d=new Driver(RebirthGameBridgePath.GoTo(p,new Vector3(0,0,10),1,10,s=>{},r=>ok=r,parent)))StepAll(d,p);A(!ok&&RebirthGameBridgePlayer.Turns==0,"planning callback replacing world refuses route actions");parent.Dispose();
 p=Fresh();parent=new RebirthGameBridgeInput.OwnedInputScope(p,()=>true);using(var d=new Driver(RebirthGameBridgePath.GoTo(p,new Vector3(0,0,10),1,10,s=>{},r=>{},parent))){A(d.Step()&&RebirthGameBridgeInput.IsHeld(RebirthGameBridgeInput.Local.MoveForward),"owned route issues real movement entry");GameManager.Instance.World=new World();RebirthGameBridgeInput.Tick(RebirthGameBridgeInput.Local.MoveForward);A(!RebirthGameBridgeInput.IsHeld(RebirthGameBridgeInput.Local.MoveForward),"native movement injection blocked before iterator continuation");}parent.Dispose();
 const string axe="meleeToolAxeT1IronFireaxe";p=Fresh();p.inventory.Items[0]=Tool(axe);var original=p.inventory.Items[0];parent=new RebirthGameBridgeInput.OwnedInputScope(p,()=>true);string result=null;using(var d=new Driver(RebirthGameBridgePlayer.BreakBlockRoutine(p,new Vector3i(),axe,s=>result=s,parent)))StepAll(d,p,()=>{if(RebirthGameBridgeInput.IsHeld(RebirthGameBridgeInput.Local.Primary)){original.itemValue.UseTimes++;p.world.Block.isair=true;}});A(result!=null&&result.StartsWith("broke through")&&parent.Admitted&&ReferenceEquals(original,p.inventory.GetItem(0))&&original.itemValue.UseTimes==1,"positive same native original tool wear completes without obsolete fullkey restoration");parent.Dispose();
 p=Fresh();p.inventory.Items[0]=Tool("club");p.inventory.Items[1]=Tool(axe);original=p.inventory.Items[0];parent=new RebirthGameBridgeInput.OwnedInputScope(p,()=>true);result=null;using(var d=new Driver(RebirthGameBridgePlayer.BreakBlockRoutine(p,new Vector3i(),axe,s=>result=s,parent)))StepAll(d,p,()=>{if(RebirthGameBridgeInput.IsHeld(RebirthGameBridgeInput.Local.Primary)){p.inventory.GetItem(1).itemValue.UseTimes++;p.world.Block.isair=true;}});A(result.StartsWith("broke through")&&p.inventory.holdingItemIdx==0&&ReferenceEquals(original,p.inventory.GetItem(0)),"different genuine tool restores exact original fullkey");parent.Dispose();
 p=Fresh();p.inventory.Items[0]=Tool(axe);parent=new RebirthGameBridgeInput.OwnedInputScope(p,()=>true);result=null;using(var d=new Driver(RebirthGameBridgePlayer.BreakBlockRoutine(p,new Vector3i(),axe,s=>result=s,parent)))StepAll(d,p,()=>{if(RebirthGameBridgeInput.IsHeld(RebirthGameBridgeInput.Local.Primary)){p.inventory.Items[0]=Tool(axe);p.world.Block.isair=true;}});A(!parent.Admitted&&result.Contains("custody"),"samevariant native stack clone replacement refused");parent.Dispose();
 p=Fresh();p.inventory.Items[0]=Tool(axe);parent=new RebirthGameBridgeInput.OwnedInputScope(p,()=>true);result=null;using(var d=new Driver(RebirthGameBridgePlayer.BreakBlockRoutine(p,new Vector3i(),axe,s=>result=s,parent)))StepAll(d,p,()=>{if(RebirthGameBridgeInput.IsHeld(RebirthGameBridgeInput.Local.Primary)){p.inventory.Items[0].itemValue.UseTimes=100;p.world.Block.isair=true;}});A(!parent.Admitted&&result.Contains("repair"),"broken genuine original reports retained custody repair instead of success");parent.Dispose();
 p=Fresh();parent=new RebirthGameBridgeInput.OwnedInputScope(p,()=>true);result=null;using(var d=new Driver(RebirthGameBridgePlayer.BreakDoorRoutine(p,new Vector3i(),s=>result=s,parent)))StepAll(d,p);A(result!=null&&!RebirthGameBridgeInput.IsHeld(RebirthGameBridgeInput.Local.Primary)&&p.inventory.Items.All(s=>s.IsEmpty()),"missing lockeddoor genuine tool never supplies or attacks");parent.Dispose();
 p=Fresh();parent=new RebirthGameBridgeInput.OwnedInputScope(p,()=>true);using(var d=new Driver(RebirthGameBridgePlayer.ApproachAndActivate(p,new Vector3i(),s=>{},2,10,parent))){A(d.Step(),"opencontainer approach yields");p.world.Primary=new EntityPlayerLocal();StepAll(d,p);}A(!RebirthGameBridgeInput.IsHeld(RebirthGameBridgeInput.Local.Activate),"opencontainer primary replacement refuses activation");parent.Dispose();

 p=Fresh();p.inventory.Items[1]=Tool(axe);parent=new RebirthGameBridgeInput.OwnedInputScope(p,()=>true);result=null;using(var d=new Driver(RebirthGameBridgePlayer.BreakBlockRoutine(p,new Vector3i(),axe,r=>result=r,parent)))StepAll(d,p,()=>{if(RebirthGameBridgeInput.IsHeld(RebirthGameBridgeInput.Local.Primary))p.world.Block.isair=true;});A(result.StartsWith("broke through")&&p.inventory.holdingItemIdx==0&&p.inventory.GetItem(0).IsEmpty(),"original genuinely empty slot restored after tool used from another slot");parent.Dispose();
 p=Fresh();p.inventory.Items[1]=Tool(axe);parent=new RebirthGameBridgeInput.OwnedInputScope(p,()=>true);result=null;using(var d=new Driver(RebirthGameBridgePlayer.BreakBlockRoutine(p,new Vector3i(),axe,r=>result=r,parent)))StepAll(d,p,()=>{if(RebirthGameBridgeInput.IsHeld(RebirthGameBridgeInput.Local.Primary)){p.inventory.Items[0]=Tool("replacement");p.world.Block.isair=true;}});A(!parent.Admitted&&p.inventory.holdingItemIdx==1,"changed original empty slot refuses selection of replacement occupant");parent.Dispose();
 p=Fresh();parent=new RebirthGameBridgeInput.OwnedInputScope(p,()=>true);var owned=new RebirthGameBridgeInput.OwnedInputScope(p,()=>true,parent);bool fault=false;using(var d=new Driver(RebirthGameBridgeUi.RunGuarded(FaultAfterPickup(owned),owned))){A(d.Step(),"fault driver reaches real picked item custody");try{d.Step();}catch(InvalidOperationException){fault=true;}}A(fault&&!RebirthGameBridgeInput.IsHeld(RebirthGameBridgeInput.Click)&&owned.CursorCustodyPending&&RebirthGameBridgeUi.CursorItem!=null,"outer MoveNext fault disposes exact owned held mouse and retains cursor item without rollback");parent.Dispose();
 p=Fresh();parent=new RebirthGameBridgeInput.OwnedInputScope(p,()=>true);using(var d=new Driver(RebirthGameBridgeUi.DragItem(new Vector2(),new Vector2(20,20),parent))){int limit=0;while(!RebirthGameBridgeInput.IsHeld(RebirthGameBridgeInput.Click)&&d.Step())if(++limit>100)throw new Exception("drag timeout");RebirthGameBridgeUi.CursorItem=new ItemStack();}A(parent.CursorCustodyPending&&!RebirthGameBridgeInput.IsHeld(RebirthGameBridgeInput.Click)&&RebirthGameBridgeUi.CursorItem!=null,"outer drag disposal propagates actual cursor custody to root without guessed return");parent.Dispose();
 Sweep("container activation",(q,r)=>RebirthGameBridgePlayer.ApproachAndActivate(q,new Vector3i(),x=>{},2,10,r));
 Sweep("locked door full genuine-tool chain",(q,r)=>RebirthGameBridgePlayer.DoorRoutine(q,new Vector3i(),x=>{},r),q=>q.inventory.Items[0]=Tool(axe),q=>{if(RebirthGameBridgeInput.IsHeld(RebirthGameBridgeInput.Local.Primary)){q.inventory.Items[0].itemValue.UseTimes++;q.world.Block.isair=true;}});
 Sweep("planned route",(q,r)=>RebirthGameBridgePath.GoTo(q,new Vector3(0,0,10),1,2,x=>{},x=>{},r),q=>RebirthGameBridgePath.Planned=new List<RebirthGameBridgePath.Step>{new RebirthGameBridgePath.Step(),new RebirthGameBridgePath.Step{Pos=new Vector3(0,0,10)}});
 Sweep("recovery walk",(q,r)=>RebirthGameBridgePlayer.WalkToGuarded(q,new Vector3(0,0,10),1,2,()=>null,x=>{},r));

 p=Fresh();p.inventory.Items[0]=Tool(axe);original=p.inventory.GetItem(0);string before=RebirthGameBridgePoiStorage.OwnedItemKey(original);parent=new RebirthGameBridgeInput.OwnedInputScope(p,()=>true);original.itemValue.UseTimes=1;RebirthGameBridgeInput.OwnedWearReceipt receipt;A(RebirthGameBridgePoiStorage.TryOwnedWearReceipt(parent,0,original,original.itemValue,1,0,before,out receipt)&&original.itemValue.UseTimes==1,"detached normalization permits scalar wear and never changes actual UseTimes");A(parent.PublishWear(receipt),"current native original wear publication admitted");string advanced;A(parent.TryConsumeWear(original,0,before,out advanced)&&advanced==RebirthGameBridgePoiStorage.OwnedItemKey(original),"root consumes exact captured original beforekey to actual afterkey");parent.Dispose();
 p=Fresh();p.inventory.Items[0]=Tool(axe);original=p.inventory.GetItem(0);before=RebirthGameBridgePoiStorage.OwnedItemKey(original);parent=new RebirthGameBridgeInput.OwnedInputScope(p,()=>true);original.itemValue.UseTimes=1;original.itemValue.Variant="changed";A(!RebirthGameBridgePoiStorage.TryOwnedWearReceipt(parent,0,original,original.itemValue,1,0,before,out receipt),"same native references changed serialized variant rejected");parent.Dispose();
 p=Fresh();p.inventory.Items[0]=Tool(axe);original=p.inventory.GetItem(0);before=RebirthGameBridgePoiStorage.OwnedItemKey(original);parent=new RebirthGameBridgeInput.OwnedInputScope(p,()=>true);original.itemValue.UseTimes=1;original.count=2;A(!RebirthGameBridgePoiStorage.TryOwnedWearReceipt(parent,0,original,original.itemValue,1,0,before,out receipt),"same native references changed count rejected");parent.Dispose();
 p=Fresh();p.inventory.Items[0]=Tool(axe);original=p.inventory.GetItem(0);before=RebirthGameBridgePoiStorage.OwnedItemKey(original);parent=new RebirthGameBridgeInput.OwnedInputScope(p,()=>true);original.itemValue.UseTimes=1;GameManager.Instance.World=new World();A(!RebirthGameBridgePoiStorage.TryOwnedWearReceipt(parent,0,original,original.itemValue,1,0,before,out receipt),"replacement current native world refuses receipt");parent.Dispose();
 p=Fresh();p.inventory.Items[0]=Tool(axe);original=p.inventory.GetItem(0);before=RebirthGameBridgePoiStorage.OwnedItemKey(original);parent=new RebirthGameBridgeInput.OwnedInputScope(p,()=>true);original.itemValue.UseTimes=1;RebirthGameBridgePoiStorage.TryOwnedWearReceipt(parent,0,original,original.itemValue,1,0,before,out receipt);parent.PublishWear(receipt);original.itemValue.UseTimes=2;A(!parent.TryConsumeWear(original,0,before,out advanced)&&!parent.Admitted,"unacknowledged later wear makes pending receipt stale and refuses root");parent.Dispose();
 p=Fresh();p.inventory.Items[0]=Tool(axe);original=p.inventory.GetItem(0);before=RebirthGameBridgePoiStorage.OwnedItemKey(original);parent=new RebirthGameBridgeInput.OwnedInputScope(p,()=>true);var nested=new RebirthGameBridgeInput.OwnedInputScope(p,()=>true,parent);original.itemValue.UseTimes=1;RebirthGameBridgePoiStorage.TryOwnedWearReceipt(nested,0,original,original.itemValue,1,0,before,out receipt);nested.PublishWear(receipt);string middle=RebirthGameBridgePoiStorage.OwnedItemKey(original);original.itemValue.UseTimes=2;RebirthGameBridgePoiStorage.TryOwnedWearReceipt(nested,0,original,original.itemValue,1,1,middle,out receipt);nested.PublishWear(receipt);A(parent.TryConsumeWear(original,0,before,out advanced)&&advanced==RebirthGameBridgePoiStorage.OwnedItemKey(original),"multiple witnessed door wear receipts combine contiguous exact key chain to current afterkey");nested.Dispose();parent.Dispose();
 p=Fresh();p.inventory.Items[0]=Tool(axe);original=p.inventory.GetItem(0);before=RebirthGameBridgePoiStorage.OwnedItemKey(original);parent=new RebirthGameBridgeInput.OwnedInputScope(p,()=>true);original.itemValue.UseTimes=1;RebirthGameBridgePoiStorage.TryOwnedWearReceipt(parent,0,original,original.itemValue,1,0,before,out receipt);parent.PublishWear(receipt);p.inventory.Items[0]=Tool(axe);A(!parent.TryConsumeWear(original,0,before,out advanced)&&!parent.Admitted,"same variant slot clone at consumption refuses receipt");parent.Dispose();
 p=Fresh();p.inventory.Items[0]=Tool(axe);original=p.inventory.GetItem(0);before=RebirthGameBridgePoiStorage.OwnedItemKey(original);parent=new RebirthGameBridgeInput.OwnedInputScope(p,()=>true);original.itemValue.UseTimes=float.NaN;A(!RebirthGameBridgePoiStorage.TryOwnedWearReceipt(parent,0,original,original.itemValue,1,0,before,out receipt),"nonfinite wear rejected");original.itemValue.UseTimes=-1;A(!RebirthGameBridgePoiStorage.TryOwnedWearReceipt(parent,0,original,original.itemValue,1,0,before,out receipt),"wear reversal rejected");parent.Dispose();

 p=Fresh();p.bag.ItemGrid.items[0]=Tool(axe);parent=new RebirthGameBridgeInput.OwnedInputScope(p,()=>true);bool changed=false;Driver.BeforeInjection=()=>{if(!changed&&RebirthGameBridgeInput.IsHeld(RebirthGameBridgeInput.Click)){changed=true;p.bag.ItemGrid.items[0]=Tool(axe);}};using(var d=new Driver(RebirthGameBridgeNeeds.Prepare(p,ic=>ic.GetItemName()==axe,null,"axe",x=>{},parent)))StepAll(d,p);A(changed&&!parent.Admitted&&RebirthGameBridgeInput.Click.Updates==0,"changed source between TryHold and first native UpdateBindings refuses injection");parent.Dispose();
 p=Fresh();p.bag.ItemGrid.items[0]=Tool(axe);parent=new RebirthGameBridgeInput.OwnedInputScope(p,()=>true);changed=false;Driver.BeforeInjection=()=>{if(!changed&&RebirthGameBridgeInput.IsHeld(RebirthGameBridgeInput.Click)){changed=true;RebirthGameBridgeUi.SlotOffset=20;}};using(var d=new Driver(RebirthGameBridgeNeeds.Prepare(p,ic=>ic.GetItemName()==axe,null,"axe",x=>{},parent)))StepAll(d,p);A(changed&&!parent.Admitted&&RebirthGameBridgeInput.Click.Updates==0,"changed UI coordinates between held entry and native injection refused");parent.Dispose();
 p=Fresh();p.bag.ItemGrid.items[0]=Tool(axe);parent=new RebirthGameBridgeInput.OwnedInputScope(p,()=>true);changed=false;RebirthGameBridgeInput.Click.OnUpdate=()=>{if(!changed){changed=true;RebirthGameBridgeUi.CursorItem=p.bag.ItemGrid.items[0];p.bag.ItemGrid.items[0]=new ItemStack{count=0};p.inventory.Items[0]=Tool("foreign target");}};using(var d=new Driver(RebirthGameBridgeNeeds.Prepare(p,ic=>ic.GetItemName()==axe,null,"axe",x=>{},parent)))StepAll(d,p);A(parent.CursorCustodyPending&&RebirthGameBridgeUi.CursorItem!=null&&p.inventory.Items[0].itemValue.ItemClass.Name=="foreign target","changed pinned target after positive native pickup retains real held cursor without guessed drop");parent.Dispose();
 p=Fresh();p.bag.ItemGrid.items[0]=Tool(axe);p.bag.ItemGrid.items[0].count=2;parent=new RebirthGameBridgeInput.OwnedInputScope(p,()=>true);changed=false;RebirthGameBridgeInput.Click.OnUpdate=()=>{if(!changed){changed=true;RebirthGameBridgeUi.CursorItem=Tool(axe);p.bag.ItemGrid.items[0]=new ItemStack{count=0};}};using(var d=new Driver(RebirthGameBridgeNeeds.Prepare(p,ic=>ic.GetItemName()==axe,null,"axe",x=>{},parent)))StepAll(d,p);A(parent.CursorCustodyPending&&RebirthGameBridgeUi.CursorItem.count==1,"partial picked stack count refused with actual cursor custody retained");parent.Dispose();
 p=Fresh();p.bag.ItemGrid.items[0]=Tool(axe);original=p.bag.ItemGrid.items[0];parent=new RebirthGameBridgeInput.OwnedInputScope(p,()=>true);changed=false;RebirthGameBridgeInput.Click.OnUpdate=()=>{if(!changed){changed=true;RebirthGameBridgeUi.CursorItem=p.bag.ItemGrid.items[0];p.bag.ItemGrid.items[0]=new ItemStack{count=0};}};Driver.AfterInjection=()=>{if(changed&&RebirthGameBridgeUi.CursorItem!=null&&!RebirthGameBridgeInput.IsHeld(RebirthGameBridgeInput.Click)&&RebirthGameBridgeInput.CursorPosition.x==20){p.inventory.Items[0]=RebirthGameBridgeUi.CursorItem;RebirthGameBridgeUi.CursorItem=null;}};using(var d=new Driver(RebirthGameBridgeNeeds.Prepare(p,ic=>ic.GetItemName()==axe,null,"axe",x=>{},parent)))StepAll(d,p);A(parent.Admitted&&ReferenceEquals(p.inventory.Items[0],original)&&RebirthGameBridgeUi.CursorItem==null,"positive fullkey/count native pickup and pinned destination deposit completes genuine preparation");parent.Dispose();

 p=Fresh();p.bag.ItemGrid.items[0]=new ItemStack{count=0};RebirthGameBridgeUi.ForeignOnly=true;Vector2 coordinate;A(!RebirthGameBridgeUi.TryOwnedInventorySlot(false,0,out coordinate),"foreign container empty same-index slot cannot satisfy backpack destination");p.bag.ItemGrid.items[0]=Tool(axe);A(!RebirthGameBridgeUi.TryOwnedInventorySlot(false,0,out coordinate),"foreign container identical fullkey/count same-index cannot satisfy backpack source");RebirthGameBridgeUi.ForeignSpoofLocation=true;A(!RebirthGameBridgeUi.TryOwnedInventorySlot(false,0,out coordinate),"foreign slot spoofing Backpack StackLocation without native backpack parent refused");
 p=Fresh();p.inventory.Items[0]=Tool(axe);parent=new RebirthGameBridgeInput.OwnedInputScope(p,()=>true);int prefixBefore=RebirthGameBridgeInput.Local.Primary.Updates;using(var d=new Driver(RebirthGameBridgePlayer.BreakBlockRoutine(p,new Vector3i(),axe,x=>{},parent))){int n=0;while(!RebirthGameBridgeInput.IsHeld(RebirthGameBridgeInput.Local.Primary)&&d.Step())if(++n>100)throw new Exception("tool prefix setup");p.inventory.Items[0].itemValue.Variant="modified";RebirthGameBridgeInput.Tick(RebirthGameBridgeInput.Local.Primary);A(!RebirthGameBridgeInput.IsHeld(RebirthGameBridgeInput.Local.Primary)&&RebirthGameBridgeInput.Local.Primary.Updates==prefixBefore,"same-ref metadata swap before native tool injection refuses attack before continuation");StepAll(d,p);}A(!parent.Admitted,"metadata proof refusal propagates through tool outer driver");parent.Dispose();
 p=Fresh();p.inventory.Items[0]=Tool(axe);parent=new RebirthGameBridgeInput.OwnedInputScope(p,()=>true);prefixBefore=RebirthGameBridgeInput.Local.Primary.Updates;using(var d=new Driver(RebirthGameBridgePlayer.BreakBlockRoutine(p,new Vector3i(),axe,x=>{},parent))){int n=0;while(!RebirthGameBridgeInput.IsHeld(RebirthGameBridgeInput.Local.Primary)&&d.Step())if(++n>100)throw new Exception("tool count setup");p.inventory.Items[0].count=2;RebirthGameBridgeInput.Tick(RebirthGameBridgeInput.Local.Primary);A(RebirthGameBridgeInput.Local.Primary.Updates==prefixBefore&&!RebirthGameBridgeInput.IsHeld(RebirthGameBridgeInput.Local.Primary),"same-ref count swap before native tool injection refuses attack");StepAll(d,p);}parent.Dispose();
 p=Fresh();parent=new RebirthGameBridgeInput.OwnedInputScope(p,()=>true);bool throwProof=false;var proofAction=new PlayerAction{Name="proof"};A(parent.TryHoldFrames(proofAction,3,1,()=>{if(throwProof)throw new InvalidOperationException();return true;}),"proof-specific owned hold acquired");throwProof=true;RebirthGameBridgeInput.Tick(proofAction);A(proofAction.Updates==0&&!RebirthGameBridgeInput.IsHeld(proofAction)&&!parent.Admitted,"native proof exception releases only owned action with no injection");parent.Dispose();

 p=Fresh();parent=new RebirthGameBridgeInput.OwnedInputScope(p,()=>true);bool selectorValid=true;changed=false;Driver.BeforeInjection=()=>{if(!changed&&RebirthGameBridgeInput.IsHeld(RebirthGameBridgeInput.Click)){changed=true;selectorValid=false;}};using(var d=new Driver(RebirthGameBridgeUi.ClickAt(new Vector2(),parent,()=>selectorValid)))StepAll(d,p);A(changed&&RebirthGameBridgeInput.Click.Updates==0&&!parent.Admitted,"revoked beforePress after TryHold before native click prefix suppresses first input");parent.Dispose();
 p=Fresh();parent=new RebirthGameBridgeInput.OwnedInputScope(p,()=>true);bool callerSideEffect=false;changed=false;Driver.BeforeInjection=()=>{if(!changed&&RebirthGameBridgeInput.IsHeld(RebirthGameBridgeInput.Click)){changed=true;Time.frameCount+=100;}};using(var d=new Driver(RebirthGameBridgeUi.ClickAt(new Vector2(),parent,()=>{callerSideEffect=true;return true;})))StepAll(d,p);A(callerSideEffect&&RebirthGameBridgeInput.Click.Updates==0&&!parent.Admitted,"expired without first native input refuses click despite caller predicate side-effect");parent.Dispose();
 p=Fresh();parent=new RebirthGameBridgeInput.OwnedInputScope(p,()=>true);selectorValid=true;RebirthGameBridgeInput.Click.OnUpdate=()=>selectorValid=false;using(var d=new Driver(RebirthGameBridgeUi.ClickAt(new Vector2(),parent,()=>selectorValid)))StepAll(d,p);A(parent.Admitted&&RebirthGameBridgeInput.Click.Updates>0,"first actual forward latches click allowing subsequent intentional selector change while context remains current");parent.Dispose();
 p=Fresh();parent=new RebirthGameBridgeInput.OwnedInputScope(p,()=>true);int notifications=0;var firstAction=new PlayerAction{Name="notify"};parent.TryHoldFrames(firstAction,5,1,null,()=>notifications++);RebirthGameBridgeInput.Tick(firstAction);RebirthGameBridgeInput.Tick(firstAction);A(notifications==1&&firstAction.Updates==2,"first-injection notification at most once after successful native forwarding");parent.Dispose();
 p=Fresh();parent=new RebirthGameBridgeInput.OwnedInputScope(p,()=>true);firstAction=new PlayerAction{Name="notify fault"};parent.TryHoldFrames(firstAction,5,1,null,()=>{notifications++;throw new InvalidOperationException();});RebirthGameBridgeInput.Tick(firstAction);RebirthGameBridgeInput.Tick(firstAction);A(firstAction.Updates==1&&!parent.Admitted&&!RebirthGameBridgeInput.IsHeld(firstAction),"notification exception occurs after one forward then refuses and prevents further owned input");parent.Dispose();
 p=Fresh();parent=new RebirthGameBridgeInput.OwnedInputScope(p,()=>true);firstAction=new PlayerAction{Name="replace notify fault"};parent.TryHoldFrames(firstAction,5,1,null,()=>{RebirthGameBridgeInput.HoldFrames(firstAction,5);throw new InvalidOperationException();});RebirthGameBridgeInput.Tick(firstAction);A(firstAction.Updates==1&&RebirthGameBridgeInput.IsHeld(firstAction)&&!parent.Admitted,"notification callback replaces hold then faults; exact-owned cleanup preserves foreign newer entry");parent.Dispose();
 p=Fresh();parent=new RebirthGameBridgeInput.OwnedInputScope(p,()=>true);notifications=0;firstAction=new PlayerAction{Name="forward fault",OnUpdate=()=>{throw new InvalidOperationException();}};parent.TryHoldFrames(firstAction,5,1,null,()=>notifications++);fault=false;try{RebirthGameBridgeInput.Tick(firstAction);}catch(InvalidOperationException){fault=true;}A(fault&&notifications==0&&!parent.Admitted&&!RebirthGameBridgeInput.IsHeld(firstAction),"native forwarding exception propagates with owned cleanup and no successful-forward notification");parent.Dispose();

 p=Fresh();bool armed=false;RebirthGameBridgeInput.OwnedInputScope reentrant=null;firstAction=new PlayerAction{Name="released by predicate"};reentrant=new RebirthGameBridgeInput.OwnedInputScope(p,()=>{if(armed)reentrant.Release(firstAction);return true;});reentrant.TryHoldFrames(firstAction,5);armed=true;RebirthGameBridgeInput.Tick(firstAction);A(firstAction.Updates==0&&!RebirthGameBridgeInput.IsHeld(firstAction),"admission releases own held token then returns true; final exact entry fence prevents forwarding");reentrant.Dispose();
 p=Fresh();armed=false;reentrant=new RebirthGameBridgeInput.OwnedInputScope(p,()=>{if(armed)GameManager.Instance.World=new World();return true;});armed=true;A(!reentrant.TrySetCursor(new Vector2(1,1))&&!RebirthGameBridgeInput.CursorActive,"callback native-world swap cannot publish owned cursor after stale admission");reentrant.Dispose();
 p=Fresh();parent=new RebirthGameBridgeInput.OwnedInputScope(p,()=>true);parent.TrySetCursor(new Vector2(1,1));GameManager.Instance.World=new World();A(RebirthGameBridgeInput.Screen().x==900&&!RebirthGameBridgeInput.CursorActive,"native cursor position getter preserves physical result in replacement world before continuation");parent.Dispose();
 p=Fresh();armed=false;reentrant=new RebirthGameBridgeInput.OwnedInputScope(p,()=>{if(armed)RebirthGameBridgeInput.SetCursor(new Vector2(44,44));return true;});reentrant.TrySetCursor(new Vector2());armed=true;A(RebirthGameBridgeInput.Screen().x==900&&RebirthGameBridgeInput.CursorActive&&RebirthGameBridgeInput.CursorPosition.x==44,"reentrant cursor admission preserves newer anonymous writer and refuses old frame override");reentrant.Dispose();
 p=Fresh();parent=new RebirthGameBridgeInput.OwnedInputScope(p,()=>true);parent.TrySetCursor(new Vector2());var sprite=new SoftCursor();sprite.Camera.Camera.Project=()=>GameManager.Instance.World=new World();RebirthGameBridgeInput.MoveCursor(sprite);A(sprite.Writes==0,"projection callback changes native world; pure last fence prevents visible cursor Position mutation");parent.Dispose();
 p=Fresh();parent=new RebirthGameBridgeInput.OwnedInputScope(p,()=>true);parent.TrySetCursor(new Vector2());sprite=new SoftCursor();sprite.GetUiCamera=()=>RebirthGameBridgeInput.SetCursor(new Vector2(55,55));RebirthGameBridgeInput.MoveCursor(sprite);A(sprite.Writes==0&&RebirthGameBridgeInput.CursorPosition.x==55,"camera getter replaces virtual writer; old sprite setter suppressed and newer cursor preserved");parent.Dispose();
 p=Fresh();armed=false;reentrant=new RebirthGameBridgeInput.OwnedInputScope(p,()=>{if(armed)RebirthGameBridgeInput.Shift=true;return true;});reentrant.TrySetShift(true);armed=true;A(!RebirthGameBridgeInput.NativeShift(false)&&RebirthGameBridgeInput.Shift,"reentrant same-value legacy flag token preserved while stale owned native contribution false");reentrant.Dispose();A(RebirthGameBridgeInput.NativeShift(true),"physical native modifier result preserved after owned refusal");
 p=Fresh();armed=false;reentrant=new RebirthGameBridgeInput.OwnedInputScope(p,()=>{if(armed)RebirthGameBridgeInput.Shift=true;return true;});reentrant.TrySetShift(true);var cleanupChild=new RebirthGameBridgeInput.OwnedInputScope(p,()=>true,reentrant);cleanupChild.TrySetShift(true);armed=true;cleanupChild.Dispose();A(RebirthGameBridgeInput.Shift,"child flag restore callback installs foreign same-value writer; frozen commit preserves foreign");reentrant.Dispose();
 p=Fresh();armed=false;reentrant=new RebirthGameBridgeInput.OwnedInputScope(p,()=>{if(armed)RebirthGameBridgeInput.SetCursor(new Vector2(66,66));return true;});reentrant.TrySetCursor(new Vector2());cleanupChild=new RebirthGameBridgeInput.OwnedInputScope(p,()=>true,reentrant);cleanupChild.TrySetCursor(new Vector2(2,2));armed=true;cleanupChild.Dispose();A(RebirthGameBridgeInput.CursorActive&&RebirthGameBridgeInput.CursorPosition.x==66,"child cursor restore callback installs newer writer; old restore commit abandoned");reentrant.Dispose();
 p=Fresh();parent=new RebirthGameBridgeInput.OwnedInputScope(p,()=>true);p.world.PrimaryRead=()=>GameManager.Instance.World=new World();A(!parent.ContextCurrent,"native primary getter artificial world swap checked by final direct world refs");parent.Dispose();
 p=Fresh();parent=new RebirthGameBridgeInput.OwnedInputScope(p,()=>true);var text=new RebirthGameBridgeUi.XUiC_TextInput{xui=new RebirthGameBridgeUi.NativeUi{playerUI=new RebirthGameBridgeUi.PlayerUi{entityPlayer=p}}};RebirthGameBridgeUi.TextControl=text;text.ViewComponent.ReadVisible=()=>GameManager.Instance.World=new World();A(!RebirthGameBridgeUi.TypeInput("crafting","searchInput","crate",parent)&&text.Sets==0,"visible getter artificial world swap refuses Text setter at final pure fence");parent.Dispose();
 p=Fresh();parent=new RebirthGameBridgeInput.OwnedInputScope(p,()=>true);text=new RebirthGameBridgeUi.XUiC_TextInput{xui=new RebirthGameBridgeUi.NativeUi{playerUI=new RebirthGameBridgeUi.PlayerUi{entityPlayer=p}}};RebirthGameBridgeUi.TextControl=text;text.SetText=()=>GameManager.Instance.World=new World();A(!RebirthGameBridgeUi.TypeInput("crafting","searchInput","crate",parent)&&text.Sets==1&&text.Triggers==0,"authorized first text mutation then setter callback context change prevents subsequent TriggerOnChange");parent.Dispose();
 p=Fresh();parent=new RebirthGameBridgeInput.OwnedInputScope(p,()=>true);var context=new RebirthGameBridgeUi.XUiC_RebirthContextSlot{IsBackpack=true,IsPresented=true,xui=new RebirthGameBridgeUi.NativeUi{playerUI=new RebirthGameBridgeUi.PlayerUi{entityPlayer=p}}};RebirthGameBridgeUi.ContextControl=context;context.Grid.Visibility=()=>GameManager.Instance.World=new World();A(!RebirthGameBridgeUi.ScrollContextBackpack(-.1f,parent)&&context.Scrolls==0,"visible grid callback context change refuses scoped scroll before mutation");parent.Dispose();

 p=Fresh();parent=new RebirthGameBridgeInput.OwnedInputScope(p,()=>true);parent.TrySetCursor(new Vector2());cleanupChild=new RebirthGameBridgeInput.OwnedInputScope(p,()=>true,parent);cleanupChild.TrySetCursor(new Vector2(2,2));Input.mousePosition=new Vector3(26,0);A(!parent.TrySetCursor(new Vector2(3,3))&&RebirthGameBridgeInput.CursorActive,"parent physical handoff refuses reacquire while newer child remains exact cursor owner until its check");A(!cleanupChild.TrySetCursor(new Vector2(4,4))&&!RebirthGameBridgeInput.CursorActive,"nested child physical handoff releases only its current owned cursor with no disposed parent resurrection");cleanupChild.Dispose();parent.Dispose();

 p=Fresh();p.inventory.Items[0]=Tool(axe);p.inventory.Hand.Fault=true;parent=new RebirthGameBridgeInput.OwnedInputScope(p,()=>true);int equippedCallbacks=0;bool equipResult=true;using(var d=new Driver(RebirthGameBridgeNeeds.Equip(p,0,axe,r=>{equippedCallbacks++;equipResult=r;},parent)))StepAll(d,p);A(equippedCallbacks==1&&!equipResult&&!parent.Admitted&&!RebirthGameBridgeInput.IsHeld(RebirthGameBridgeInput.Local.Primary),"native same-slot Hand re-equip fault reports one failed callback and refuses further owned attacks");parent.Dispose();

 p=Fresh();RebirthGameBridgeInput.SetCursor(new Vector2(10,10));sprite=new SoftCursor();sprite.Camera.GetCamera=()=>RebirthGameBridgeInput.SetCursor(new Vector2(77,77));RebirthGameBridgeInput.MoveCursor(sprite);A(sprite.Writes==1&&sprite.LastPosition.x==77,"anonymous legacy camera getter evaluation reads updated CursorPosition after camera getter exactly as before");
 p=Fresh();RebirthGameBridgeInput.SetCursor(new Vector2(10,10));RebirthGameBridgeInput.ReleaseCursor();RebirthGameBridgeInput.SetCursor(new Vector2(10,10));sprite=new SoftCursor();RebirthGameBridgeInput.OwnedInputScope introduced=null;sprite.Camera.GetCamera=()=>{RebirthGameBridgeInput.ReleaseCursor();introduced=new RebirthGameBridgeInput.OwnedInputScope(p,()=>true);introduced.TrySetCursor(new Vector2(88,88));GameManager.Instance.World=new World();};RebirthGameBridgeInput.MoveCursor(sprite);A(sprite.Writes==0,"anonymous getter introduces owned writer then swaps world; no unchecked owned visible cursor publication");introduced.Dispose();
 Console.WriteLine("PASS "+ChecksRun+" actual-source guarded Player/Path transitive checks; native world/primary callbacks, route injection, genuine tool wear/restoration/replacement/repair, missingtool and activation; native dependencies doubled, no runtime claim.");
 }
}
