using System;using System.IO;using System.Collections;using System.Collections.Generic;
namespace UnityEngine {public static class Time {public static float realtimeSinceStartup;}}
namespace UnityEngine.Scripting {public class PreserveAttribute:Attribute{}}
public struct Vector3i {public int x,y,z;public Vector3i(int a,int b,int c){x=a;y=b;z=c;}}
public class World {public bool Remote=true;public EntityPlayer Player;public bool IsRemote(){return Remote;}public object GetEntity(int id){return Player!=null&&Player.entityId==id?Player:null;}}
public class EntityPlayer {public int entityId=7;public World world;public bool IsDead(){return false;}}
public class EntityPlayerLocal:EntityPlayer{}
public class PrefabInstance {public int id=3;public Vector3i boundingBoxPosition,boundingBoxSize=new Vector3i(10,10,10);}
public class Decorator {public List<PrefabInstance> allPrefabs=new List<PrefabInstance>();}
public class GameManager {public Decorator Prefabs=new Decorator();public Decorator GetDynamicPrefabDecorator(){return Prefabs;}}
public enum NetPackageDirection {ToServer,ToClient}
public class PooledBinaryReader:BinaryReader {public PooledBinaryReader(Stream s):base(s){}}
public class PooledBinaryWriter:BinaryWriter {public PooledBinaryWriter(Stream s):base(s){}}
public class NetPackage {public object Sender;public bool SenderValid=true;public bool ValidEntityIdForSender(int id){return SenderValid;}public virtual NetPackageDirection PackageDirection{get{return NetPackageDirection.ToClient;}}public virtual void read(PooledBinaryReader r){}public virtual void write(PooledBinaryWriter w){}public virtual void ProcessPackage(World w,GameManager g){}}
public class ConnectionManager {public NetPackage Last;public void SendToServer(NetPackage p){Last=p;}public void SendPackage(NetPackage p,int _attachedToEntityId){Last=p;}}
public class SingletonMonoBehaviour<T> where T:new(){public static T Instance=new T();}
public static class NetPackageManager {public static T GetPackage<T>() where T:new(){return new T();}}
internal static class RebirthPoiCrateLedgerService {public static int Calls;public static bool Snapshot(EntityPlayer p,PrefabInstance poi,out List<RebirthPoiCrateExpectation> list,out string error){Calls++;list=null;error="double";return false;}}
class Checks {
static void A(bool c,string m){if(!c)throw new Exception(m);}
static byte[] Save(NetPackage p){using(var s=new MemoryStream()){var w=new PooledBinaryWriter(s);p.write(w);w.Flush();return s.ToArray();}}
static void Read(NetPackage p,byte[] b){using(var s=new MemoryStream(b))using(var r=new PooledBinaryReader(s))p.read(r);}
static void Invalid(byte[] b,string reason){bool fail=false;try{Read(new NetPackageRebirthPoiCrateRecoveryResult(),b);}catch(InvalidDataException){fail=true;}catch(EndOfStreamException){fail=true;}A(fail,reason);}
static void Main(){var world=new World();var player=new EntityPlayerLocal{world=world};world.Player=player;var poi=new PrefabInstance();bool called=false;List<RebirthPoiCrateExpectation> delivered=null;string error=null;var work=RebirthPoiCrateRecovery.Request(player,poi,(list,e)=>{called=true;delivered=list;error=e;});A(work.MoveNext(),"request awaits server");byte[] request=Save(SingletonMonoBehaviour<ConnectionManager>.Instance.Last);byte[] raw=new byte[16];Array.Copy(request,5,raw,0,16);Guid nonce=new Guid(raw);var entry=new RebirthPoiCrateExpectation("owner",poi.id,poi.boundingBoxPosition,poi.boundingBoxSize,new Vector3i(),Guid.NewGuid());var records=new List<RebirthPoiCrateExpectation>{entry};
RebirthPoiCrateRecovery.Receive(world,player.entityId,Guid.NewGuid(),poi.id,poi.boundingBoxPosition,poi.boundingBoxSize,true,records);A(work.MoveNext()&&!called,"unknown nonce rejected");RebirthPoiCrateRecovery.Receive(new World{Player=player},player.entityId,nonce,poi.id,poi.boundingBoxPosition,poi.boundingBoxSize,true,records);A(work.MoveNext()&&!called,"world substitute rejected");RebirthPoiCrateRecovery.Receive(world,99,nonce,poi.id,poi.boundingBoxPosition,poi.boundingBoxSize,true,records);A(work.MoveNext()&&!called,"wrong player rejected");RebirthPoiCrateRecovery.Receive(world,player.entityId,nonce,poi.id+1,poi.boundingBoxPosition,poi.boundingBoxSize,true,records);A(work.MoveNext()&&!called,"wrong scope rejected");
var packet=new NetPackageRebirthPoiCrateRecoveryResult().Setup(player.entityId,nonce,poi,true,records);byte[] wire=Save(packet);var parsed=new NetPackageRebirthPoiCrateRecoveryResult();Read(parsed,wire);parsed.ProcessPackage(world,null);A(!work.MoveNext()&&called&&error==null&&delivered.Count==1&&delivered[0].Placement==entry.Placement,"valid exact response admitted");
for(int i=0;i<wire.Length;i++){var cut=new byte[i];Array.Copy(wire,cut,i);Invalid(cut,"truncation "+i);}var bad=(byte[])wire.Clone();bad[49]=2;Invalid(bad,"invalid status");bad=(byte[])wire.Clone();bad[50]=129;Invalid(bad,"oversized count");bad=(byte[])wire.Clone();bad[49]=0;Invalid(bad,"failure cannot carry entries");var duplicate=Save(new NetPackageRebirthPoiCrateRecoveryResult().Setup(player.entityId,nonce,poi,true,new List<RebirthPoiCrateExpectation>{entry,entry}));Invalid(duplicate,"duplicate GUID/position");var samePosition=new RebirthPoiCrateExpectation("owner",poi.id,poi.boundingBoxPosition,poi.boundingBoxSize,new Vector3i(),Guid.NewGuid());Invalid(Save(new NetPackageRebirthPoiCrateRecoveryResult().Setup(player.entityId,nonce,poi,true,new List<RebirthPoiCrateExpectation>{entry,samePosition})),"duplicate position");
called=false;work=RebirthPoiCrateRecovery.Request(player,poi,(list,e)=>{called=true;delivered=list;error=e;});A(work.MoveNext(),"timeout setup");UnityEngine.Time.realtimeSinceStartup=6;A(!work.MoveNext()&&called&&delivered==null&&error!=null,"timeout distinct from empty success");var server=new World{Remote=false};var remotePlayer=new EntityPlayer{world=server};server.Player=remotePlayer;var callbacks=new GameManager();callbacks.Prefabs.allPrefabs.Add(poi);var incoming=new NetPackageRebirthPoiCrateRecoveryRequest().Setup(remotePlayer.entityId,Guid.NewGuid(),poi);incoming.ProcessPackage(server,callbacks);A(RebirthPoiCrateLedgerService.Calls==0,"missing sender rejected");incoming.Sender=new object();incoming.SenderValid=false;incoming.ProcessPackage(server,callbacks);A(RebirthPoiCrateLedgerService.Calls==0,"sender entity spoof rejected");incoming.SenderValid=true;remotePlayer.world=world;incoming.ProcessPackage(server,callbacks);A(RebirthPoiCrateLedgerService.Calls==0,"server player world mismatch rejected");remotePlayer.world=server;incoming.ProcessPackage(server,callbacks);A(RebirthPoiCrateLedgerService.Calls==1&&SingletonMonoBehaviour<ConnectionManager>.Instance.Last is NetPackageRebirthPoiCrateRecoveryResult,"authenticated exact native POI emits response");
UnityEngine.Time.realtimeSinceStartup=0;called=false;work=RebirthPoiCrateRecovery.Request(player,poi,(list,e)=>{called=true;delivered=list;error=e;});A(work.MoveNext(),"world change setup");player.world=new World{Player=player};A(!work.MoveNext()&&called&&delivered==null&&error!=null,"world change cancels pending request");Console.WriteLine("PASS actual POI recovery wire/admission: roundtrip, every truncated prefix, bounded count/status, duplicate identity/position, nonce/world/player/scope refusal and timeout failure. Native networking and authority adapters doubled.");
}}