using System;
class ItemValue {public int type;public float Remaining;public string Metadata;public ItemValue Clone(){return (ItemValue)MemberwiseClone();}}
class ItemStack {public ItemValue itemValue;public int count;public static ItemStack Empty=new ItemStack(new ItemValue(),0);public ItemStack(ItemValue v,int c){itemValue=v;count=c;}public bool IsEmpty(){return count<=0||itemValue==null||itemValue.type==0;}public ItemStack Clone(){return new ItemStack(itemValue.Clone(),count);}}
class RebirthConsumableDefinition {public bool ReusableContainer;public string EmptyItem;}
static class ItemClass {public static ItemValue GetItem(string n){return new ItemValue {type=n=="emptyJar"?2:0};}}
static class RebirthLiquidContainerService {public static void SetRemainingMl(ItemValue v,RebirthConsumableDefinition d,float ml){v.Remaining=ml;}}
class Check {static void Assert(bool b,string m){if(!b)throw new Exception(m);}static void Main(){
 var source=new ItemStack(new ItemValue {type=1,Remaining=500,Metadata="quality/custom preparation"},3);var def=new RebirthConsumableDefinition {EmptyItem="emptyJar"};
 var partial=RebirthDrinkSourcePlan.Create(source,def,375);Assert(source.count==3&&source.itemValue.Remaining==500,"planning mutated live source");Assert(partial.Replacement.count==1&&partial.Replacement.itemValue.Remaining==375&&partial.Replacement.itemValue.Metadata==source.itemValue.Metadata,"partial exact value lost");Assert(partial.ConsumedSource.itemValue.Remaining==500&&partial.UntouchedSiblings.count==2&&partial.UntouchedSiblings.itemValue.Remaining==500,"siblings/use identity changed");partial.Replacement.itemValue.Metadata="changed";Assert(source.itemValue.Metadata!="changed"&&partial.ConsumedSource.itemValue.Metadata!="changed"&&partial.UntouchedSiblings.itemValue.Metadata!="changed","ItemValue alias");
 var last=RebirthDrinkSourcePlan.Create(source,def,0.5f);Assert(last.RemainingMl==0&&last.CreatedEmptyItem&&last.Replacement.itemValue.type==2&&last.UntouchedSiblings.count==2,"last sip jar replacement");def.ReusableContainer=true;var reusable=RebirthDrinkSourcePlan.Create(source,def,0);Assert(!reusable.CreatedEmptyItem&&reusable.Replacement.itemValue.type==1&&reusable.Replacement.itemValue.Remaining==0&&reusable.Replacement.itemValue.Metadata==source.itemValue.Metadata,"reusable metadata lost");def.ReusableContainer=false;def.EmptyItem=null;source.count=1;var consumed=RebirthDrinkSourcePlan.Create(source,def,0);Assert(consumed.Replacement.IsEmpty()&&!consumed.CreatedEmptyItem&&consumed.UntouchedSiblings==null,"disposable single container");bool rejected=false;try{RebirthDrinkSourcePlan.Create(ItemStack.Empty,def,0);}catch(ArgumentException){rejected=true;}Assert(rejected,"invalid source accepted");Console.WriteLine("PASS: detached partial container, exact metadata and clone isolation, stacked siblings, empty jar, reusable container, single disposable and invalid source.");}}
