using System;using System.Collections.Generic;
class EntityPlayerLocal{public World world;public int entityId=1;public bool IsDead(){return false;}}
class World{public bool Remote=true;public EntityPlayerLocal Player;public bool IsRemote(){return Remote;}public EntityPlayerLocal GetPrimaryPlayer(){return Player;}}
class GameManager{public static GameManager Instance=new GameManager();public World World;}
class Origin{public string CreationId;}
class AudioSupport{public long AudiobookRevision;}
class RebirthWorldCharacterRecord{public bool IsComplete=true;public Origin Origin=new Origin();public AudioSupport Support=new AudioSupport();}
static class RebirthWorldCharacterService{public static RebirthWorldCharacterRecord Record;public static bool TryGet(EntityPlayerLocal p,out RebirthWorldCharacterRecord r){r=Record;return r!=null;}}
static class RebirthSurvivorClientState{public static string Id;public static string GetProjectedCreationId(EntityPlayerLocal p){return Id;}}
static class RebirthMusicTransferClient{public static int Resets;public static void Reset(){Resets++;}}
class ItemValue{public int Type=1;public bool IsEmpty(){return Type==0;}public ItemValue Clone(){return new ItemValue{Type=Type};}}
static class RebirthBackpackLibraryReservation{public static bool Held;public static bool IsHeld(EntityPlayerLocal p){return Held;}}
class ConnectionManager{}
class SingletonMonoBehaviour<T> where T:new(){public static T Instance=new T();}
class NetPackageRebirthMusicLibraryRequest{}
static class NetPackageManager{public static T GetPackage<T>() where T:new(){return new T();}}
static class RebirthAudiobookLibraryClient{public static void Reset(){}}
// PRODUCTION_SCOPE
static class Client{
public static string CreationId="";public static long Revision=-1,Generation;public static bool PendingTransfer,Shuffle;public static List<string> Items=new List<string>();
public static List<int> Sent=new List<int>();public static bool CanSend(ConnectionManager c,NetPackageRebirthMusicLibraryRequest r){return true;}public static void Dispatch(EntityPlayerLocal p,int op,int index=0,ItemValue item=null){Sent.Add(op);}
// PRODUCTION_CLIENT
}
class Checks{static void A(bool b,string m){if(!b)throw new Exception(m);}static void Main(){var w=new World();w.Player=new EntityPlayerLocal{world=w};GameManager.Instance.World=w;string a=Guid.NewGuid().ToString("N"),b=Guid.NewGuid().ToString("N");RebirthSurvivorClientState.Id=a;Client.Receive(a,10,true,new[]{"first"},true);A(Client.Items[0]=="first"&&Client.PendingTransfer,"valid scope");int reset=RebirthMusicTransferClient.Resets;long generation=Client.Generation;RebirthSurvivorClientState.Id=b;Client.Receive(a,11,false,new[]{"stale"},false);A(Client.Items[0]=="first"&&Client.PendingTransfer&&reset==RebirthMusicTransferClient.Resets&&generation==Client.Generation,"delayed old does not reset receipt");Client.Receive(b,1,false,new[]{"new"},true);A(Client.Items[0]=="new"&&Client.Revision==1,"new character low revision");Client.Receive(b,0,true,new[]{"older"});A(Client.Items[0]=="new","older revision");w.Player=null;Client.Receive(b,2,true,new[]{"missing"});A(Client.Items[0]=="new","missing player");w.Player=new EntityPlayerLocal{world=w};w.Remote=false;RebirthWorldCharacterService.Record=new RebirthWorldCharacterRecord{Origin=new Origin{CreationId=b}};Client.Receive(b,2,true,new[]{"host"});A(Client.Items[0]=="host","host record");Client.Receive(b,3,false,null);A(Client.Items[0]=="host","null entries");RebirthWorldCharacterService.Record.Origin.CreationId=a;A(!Client.EnsureCurrent(w.Player)&&Client.Items.Count==0&&Client.Revision==-1,"cached old character cleared before use");int cleared=RebirthMusicTransferClient.Resets;A(!Client.EnsureCurrent(w.Player)&&RebirthMusicTransferClient.Resets==cleared,"empty cache not repeatedly reset");var legacy="legacy-"+new string('a',64);w.Remote=true;RebirthSurvivorClientState.Id=legacy;Client.Receive(legacy,1,false,new[]{"legacy-song"});A(Client.CreationId==legacy&&Client.Items[0]=="legacy-song"&&Client.EnsureCurrent(w.Player),"migrated remote snapshot accepted");
Client.Receive("legacy-"+new string('b',64),2,true,new[]{"wrong-owner"});A(Client.Items[0]=="legacy-song"&&Client.Revision==1,"different migrated owner refused");
w.Remote=false;RebirthWorldCharacterService.Record.Origin.CreationId=legacy;Client.Receive(legacy,2,true,new[]{"legacy-host"});A(Client.Items[0]=="legacy-host"&&Client.EnsureCurrent(w.Player),"migrated host snapshot accepted");
RebirthWorldCharacterService.Record.Origin.CreationId=a;A(!Client.EnsureCurrent(w.Player)&&Client.Items.Count==0,"migrated cache cleared on character replacement");w.Remote=true;RebirthSurvivorClientState.Id=a;Client.Sent.Clear();
A(Client.RequestUse(w.Player,new ItemValue())&&Client.Sent.Count==1&&Client.Sent[0]==0,"cold music use requests refresh only");
A(!Client.RequestUse(w.Player,new ItemValue()),"second cold use cannot duplicate pending intent");
Client.Receive(a,1,false,new string[0]);A(Client.Sent.Count==2&&Client.Sent[1]==1,"current snapshot loads queued tape without playback");
Client.Receive(a,1,false,new string[0]);A(Client.Sent.Count==2,"repeated snapshot cannot reload queued tape");
RebirthBackpackLibraryReservation.Held=true;A(!Client.RequestUse(w.Player,new ItemValue()),"custody-held music use refused");RebirthBackpackLibraryReservation.Held=false;
Client.Reset();Client.Sent.Clear();A(Client.RequestUse(w.Player,new ItemValue()),"second cold request admitted");RebirthSurvivorClientState.Id=b;Client.Receive(b,1,false,new string[0]);A(Client.Sent.Count==1,"new character cancels prior queued music load");
var replacementWorld=new World();replacementWorld.Player=new EntityPlayerLocal{world=replacementWorld};GameManager.Instance.World=replacementWorld;RebirthSurvivorClientState.Id=b;A(!Client.EnsureCurrent(replacementWorld.Player)&&Client.Items.Count==0,"same creation new world invalidates cache");Client.Receive(b,20,false,new[]{"fresh-world"});replacementWorld.Player=new EntityPlayerLocal{world=replacementWorld,entityId=2};A(!Client.EnsureCurrent(replacementWorld.Player),"same creation replacement entity invalidates cache");Client.Receive(b,1,false,new[]{"fresh-entity"});A(Client.Revision==1&&Client.Items[0]=="fresh-entity","new entity accepts lower revision");Client.Receive(b,40,false,new[]{"held"},true,7);int heldResets=RebirthMusicTransferClient.Resets;Client.Receive(b,40,false,new[]{"stale-clear"},false,7);A(Client.PendingTransfer&&Client.Items[0]=="held"&&RebirthMusicTransferClient.Resets==heldResets,"same revisions delayed unheld snapshot cannot abandon offer");Client.Receive(b,41,false,new[]{"music-settled"},false,7);A(!Client.PendingTransfer&&Client.Revision==41,"music terminal revision clears hold");Client.Receive(b,41,false,new[]{"audio-held"},true,7);Client.Receive(b,41,false,new[]{"stale-audio-clear"},false,7);A(Client.PendingTransfer&&Client.Items[0]=="audio-held","audiobook same revisions hold retained");Client.Receive(b,41,false,new[]{"audio-settled"},false,8);A(!Client.PendingTransfer&&Client.Items[0]=="audio-settled","audiobook terminal revision clears music projection hold");Client.Receive(b,42,false,new[]{"stale-audio"},false,7);A(Client.Revision==41&&Client.Items[0]=="audio-settled","older audiobook revision rejects mixed stale snapshot");Console.WriteLine("PASS 6 actual music Use assertions: cold refresh, duplicate refusal, one load after snapshot, no playback operation, custody hold and changed-character cancellation; native transport/items doubled.");Console.WriteLine("PASS: actual music snapshot Receive/GUID scope; delayed character cannot reset receipts, new/older revisions, missing owner, host and null data. Native transport/owner records doubled.");}}
