#requires -Version 7.0
$ErrorActionPreference='Stop'
$root=Split-Path -Parent (Split-Path -Parent $PSScriptRoot)
$source=[IO.File]::ReadAllText((Join-Path $root 'Scripts/Crafting/UI/RebirthStationRefundReceiptReader.cs'))
$fixture=@"
public static class EntityBuffs{public const int Version=2;}public class BuffValue{public void Read(Reader r,int v){r.ReadInt32();}}public class Reader:System.IO.BinaryReader{public Reader():base(new System.IO.MemoryStream()){}public void SetBaseStream(System.IO.Stream s){stream=s;}private System.IO.Stream stream;private System.IO.BinaryReader Inner{get{return new System.IO.BinaryReader(stream,System.Text.Encoding.UTF8,true);}}public new byte ReadByte(){return Inner.ReadByte();}public new ushort ReadUInt16(){return Inner.ReadUInt16();}public new int ReadInt32(){return Inner.ReadInt32();}public new string ReadString(){return Inner.ReadString();}public new float ReadSingle(){return Inner.ReadSingle();}}public class Pool{public Reader AllocSync(bool b){return new Reader();}}public static class MemoryPools{public static Pool poolBinaryReader=new Pool();}
public static class Fixture{static int n;static void Check(bool b){n++;if(!b)throw new Exception("receipt "+n);}static byte[] Blob(string key,float value,bool duplicate=false){using(var s=new MemoryStream()){using(var w=new BinaryWriter(s,System.Text.Encoding.UTF8,true)){w.Write((byte)2);w.Write((ushort)1);w.Write(123);w.Write((ushort)(duplicate?2:1));w.Write(key);w.Write(value);if(duplicate){w.Write(key);w.Write(value);}}return s.ToArray();}}public static string Run(){var id=Guid.NewGuid();var key="rbStationRefund_"+id.ToString("N");var applied=Blob(key,1f);Check(RebirthStationRefundReceiptReader.Contains(applied,id,true));Check(!RebirthStationRefundReceiptReader.Contains(applied,id,false));Check(RebirthStationRefundReceiptReader.Contains(Blob(key,2f),id,false));Check(!RebirthStationRefundReceiptReader.Contains(Blob(key,2f),id,true));Check(!RebirthStationRefundReceiptReader.Contains(Blob(key,1f,true),id,true));Check(!RebirthStationRefundReceiptReader.Contains(Blob(key,float.NaN),id,true));Check(!RebirthStationRefundReceiptReader.Contains(applied,Guid.NewGuid(),true));Check(!RebirthStationRefundReceiptReader.Contains(applied,Guid.Empty,true));Check(!RebirthStationRefundReceiptReader.Contains(null,id,true));Check(!RebirthStationRefundReceiptReader.Contains(new byte[1024*1024+1],id,true));var trailing=new byte[applied.Length+1];Array.Copy(applied,trailing,applied.Length);Check(!RebirthStationRefundReceiptReader.Contains(trailing,id,true));Array.Resize(ref applied,applied.Length-1);Check(!RebirthStationRefundReceiptReader.Contains(applied,id,true));return "PASS "+n+" actual detached native refund receipt parser with pooled-reader/buff doubles; no file durability proof";}}
"@
Add-Type -TypeDefinition ($source+$fixture)
[Fixture]::Run()