import {readFile,writeFile,mkdtemp,unlink,rmdir} from 'node:fs/promises';import {execFile} from 'node:child_process';import {promisify} from 'node:util';import {tmpdir} from 'node:os';import {join,resolve,dirname} from 'node:path';import {fileURLToPath} from 'node:url';
const run=promisify(execFile),here=dirname(fileURLToPath(import.meta.url)),root=resolve(here,'../..');
const source=await readFile(join(root,'Scripts/Survivor/Progression/RebirthNativeBackpackMagazinePatches.cs'),'utf8');
const fixture=`
namespace HarmonyLib{[System.AttributeUsage(System.AttributeTargets.Class|System.AttributeTargets.Method,AllowMultiple=true)]class HarmonyPatch:System.Attribute{public HarmonyPatch(){}public HarmonyPatch(System.Type t,string n){}}class HarmonyPrefix:System.Attribute{}}
public class ItemClass{public string Name;public string GetItemName(){return Name;}}
public class ItemValue{public ItemClass ItemClass;public int Seed=42;public float UseTimes=3;}
public class ItemStack{public int count=3;public ItemValue itemValue;public bool IsEmpty(){return count<=0;}}
public class EntityAlive{public bool RightArmAnimationUse;}public class EntityPlayerLocal:EntityAlive{}
public class ItemInventoryData{public ItemStack itemStack;public EntityAlive holdingEntity;}
public class ItemActionData{public ItemInventoryData invData;}public class ItemActionEat{public void ExecuteAction(){}public void ExecuteInstantAction(){}public class MyInventoryData:ItemActionData{public bool bEatingStarted,bEatingFinished;}}
static class RebirthSurvivorMode{public static bool Enabled;public static bool IsEnabledForCurrentWorld(){return Enabled;}}
static class Localization{public static string Get(string key){return key;}}static class GameManager{public static int Messages;public static void ShowTooltip(EntityPlayerLocal p,string s){Messages++;}}
class Check{static void A(bool value,string message){if(!value)throw new System.Exception(message);}static void Main(){
var stack=new ItemStack{itemValue=new ItemValue{ItemClass=new ItemClass{Name="backpackSkillMagazine"}}};var player=new EntityPlayerLocal{RightArmAnimationUse=true};var data=new ItemActionEat.MyInventoryData{invData=new ItemInventoryData{itemStack=stack,holdingEntity=player},bEatingStarted=true};
bool result=true;RebirthSurvivorMode.Enabled=false;A(RebirthNativeBackpackMagazinePatches.ExecutePrefix(data,true)&&RebirthNativeBackpackMagazinePatches.InstantPrefix(player,stack,ref result)&&RebirthNativeBackpackMagazinePatches.ConsumePrefix(data),"native mode intercepted");A(result&&data.bEatingStarted&&player.RightArmAnimationUse&&GameManager.Messages==0,"native mode mutated");
RebirthSurvivorMode.Enabled=true;A(!RebirthNativeBackpackMagazinePatches.InstantPrefix(player,stack,ref result)&&!result,"inventory read accepted");A(!RebirthNativeBackpackMagazinePatches.ExecutePrefix(data,true)&&!data.bEatingStarted&&data.bEatingFinished&&!player.RightArmAnimationUse,"held read admitted");
data.bEatingStarted=true;player.RightArmAnimationUse=true;A(!RebirthNativeBackpackMagazinePatches.ConsumePrefix(data)&&!data.bEatingStarted&&!player.RightArmAnimationUse,"pending animation debit admitted");int messages=GameManager.Messages;A(!RebirthNativeBackpackMagazinePatches.ConsumePrefix(data)&&GameManager.Messages==messages,"idle completion notification repeated");A(stack.count==3&&stack.itemValue.Seed==42&&stack.itemValue.UseTimes==3,"magazine custody changed");
stack.itemValue.ItemClass.Name="medicalSkillMagazine";result=true;data.bEatingStarted=true;A(RebirthNativeBackpackMagazinePatches.ExecutePrefix(data,true)&&RebirthNativeBackpackMagazinePatches.InstantPrefix(player,stack,ref result)&&RebirthNativeBackpackMagazinePatches.ConsumePrefix(data)&&result&&data.bEatingStarted,"unrelated literature intercepted");
A(!RebirthNativeBackpackMagazinePatches.ShouldSuppress(null)&&!RebirthNativeBackpackMagazinePatches.ShouldSuppress(new ItemStack())&&RebirthNativeBackpackMagazinePatches.ExecutePrefix(null,true)&&RebirthNativeBackpackMagazinePatches.ConsumePrefix(null),"missing context failed");
stack.itemValue.ItemClass.Name="backpackSkillMagazine";stack.count=0;A(!RebirthNativeBackpackMagazinePatches.ShouldSuppress(stack),"empty item suppressed");
System.Console.WriteLine("PASS actual magazine policy/prefixes: mode-specific exact item admission, unchanged vanilla/unrelated behavior, inventory+held+pending animation refusal, preserved count/seed/wear, local feedback and no repeated completion notice. Native callbacks/Harmony/input adapters doubled.");}}
`;
const temp=await mkdtemp(join(tmpdir(),'rebirth-magazine-'));try{const cs=join(temp,'check.cs'),exe=join(temp,'check.exe');await writeFile(cs,source+'\n'+fixture);await run('C:/Program Files/dotnet/dotnet.exe',['C:/Program Files/dotnet/sdk/9.0.301/Roslyn/bincore/csc.dll','/nologo','/target:exe','/out:'+exe,...['mscorlib','System','System.Core'].map(x=>'/r:C:/Windows/Microsoft.NET/Framework64/v4.0.30319/'+x+'.dll'),cs],{windowsHide:true,timeout:10000});console.log((await run(exe,[],{windowsHide:true,timeout:10000})).stdout.trim());}finally{for(const n of ['check.cs','check.exe'])await unlink(join(temp,n)).catch(e=>{if(e.code!=='ENOENT')throw e;});await rmdir(temp);}