#requires -Version 7.0
$ErrorActionPreference='Stop'
$root=Split-Path -Parent (Split-Path -Parent $PSScriptRoot)
$source=[IO.File]::ReadAllText((Join-Path $root 'Scripts/Survivor/Persistence/RebirthWorldCharacterRepository.cs'))
$start=$source.IndexOf('    internal static bool HasSavedStationRefundArchive(')
$end=$source.IndexOf('    internal static bool HasSavedTheoryStudy(',$start)
if($start-lt0-or$end-lt$start){throw 'Witness extraction boundary missing'}
$method=$source.Substring($start,$end-$start)
$fixture=@"
using System;using System.Xml.Linq;using System.Collections.Generic;
public class RebirthStablePlayerIdentity{public string StorageKey="owner";}public class RebirthStationRefundArchive{public string JobId="job",CreationId="creation",Data="exact";public static bool Valid=true;public XElement Write(){return new XElement("archive",new XAttribute("data",Data));}public static bool TryRead(XElement n,string owner,out RebirthStationRefundArchive a){a=new RebirthStationRefundArchive{Data=(string)n.Attribute("data")};return Valid&&owner=="owner";}}public static class RebirthSurvivorRequestScope{public static bool Matches(string a,string b){return a==b;}}public class Origin{public string CreationId="creation";}public class Progression{public Dictionary<string,RebirthStationRefundArchive> StationRefundArchives=new Dictionary<string,RebirthStationRefundArchive>();public Dictionary<string,object> StationPreparations=new Dictionary<string,object>(),StationPublications=new Dictionary<string,object>(),StationTerminalIntents=new Dictionary<string,object>(),StationCancellationRefunds=new Dictionary<string,object>(),StationCancellationAttempts=new Dictionary<string,object>(),StationCancellationPublications=new Dictionary<string,object>(),StationRefundDeliveries=new Dictionary<string,object>();}public class Record{public Origin Origin=new Origin();public Progression Progression=new Progression();}
public static class Repository{public static bool serverAuthority=true,Load=true,Migrated=false;public static int Reads;public static Record Saved=new Record();private static object sync=new object();private static string GetPath(string key){return key=="owner"?"final":"";}private static object GetWriteLock(string key){return sync;}private static bool TryLoadValidatedRecord(string path,RebirthStablePlayerIdentity id,out Record saved,out bool migrated,out string one,out string two){Reads++;saved=Saved;migrated=Migrated;one=two=null;return Load;}
$method
}
public static class Fixture{static int n;static void Check(bool b){n++;if(!b)throw new Exception("archive witness "+n);}public static string Run(){var owner=new RebirthStablePlayerIdentity();var archive=new RebirthStationRefundArchive();var state=Repository.Saved.Progression;state.StationRefundArchives["job"]=new RebirthStationRefundArchive();Check(Repository.HasSavedStationRefundArchive(owner,archive));Repository.Load=false;Check(!Repository.HasSavedStationRefundArchive(owner,archive));Repository.Load=true;Repository.Migrated=true;Check(!Repository.HasSavedStationRefundArchive(owner,archive));Repository.Migrated=false;Repository.Saved.Origin.CreationId="other";Check(!Repository.HasSavedStationRefundArchive(owner,archive));Repository.Saved.Origin.CreationId="creation";state.StationRefundArchives["job"].Data="changed";Check(!Repository.HasSavedStationRefundArchive(owner,archive));state.StationRefundArchives["job"].Data="exact";foreach(var active in new[]{state.StationPreparations,state.StationPublications,state.StationTerminalIntents,state.StationCancellationRefunds,state.StationCancellationAttempts,state.StationCancellationPublications,state.StationRefundDeliveries}){active["job"]=new object();Check(!Repository.HasSavedStationRefundArchive(owner,archive));active.Clear();}state.StationRefundArchives.Clear();Check(!Repository.HasSavedStationRefundArchive(owner,archive));state.StationRefundArchives["job"]=archive;Repository.serverAuthority=false;int reads=Repository.Reads;Check(!Repository.HasSavedStationRefundArchive(owner,archive)&&reads==Repository.Reads);Repository.serverAuthority=true;RebirthStationRefundArchive.Valid=false;Check(!Repository.HasSavedStationRefundArchive(owner,archive)&&reads==Repository.Reads);RebirthStationRefundArchive.Valid=true;Check(!Repository.HasSavedStationRefundArchive(null,archive));Check(!Repository.HasSavedStationRefundArchive(owner,null));Check(Repository.HasSavedStationRefundArchive(owner,archive));return "PASS "+n+" actual final-file archive witness with record/codec/storage doubles; no native durability proof";}}
"@
Add-Type -TypeDefinition $fixture
[Fixture]::Run()