using System;using System.Collections.Generic;
class Recipe {public string Name,Area;public bool Cooking;public string GetName()=>Name;}
class Station {public string Workstation;}
static class Localization {public static string Get(string name)=>name;}
static class RebirthCookingCatalogue {public static bool IsCooking(Recipe r)=>r.Cooking;public static bool AtStation(Recipe r,string s)=>r.Area==s;public static int Projected;public static Recipe ForStation(Recipe r,string s){Projected++;return new Recipe{Name=r.Name,Area=s,Cooking=r.Cooking};}}
class Workspace {internal Station station=new Station();internal List<Recipe> catalogue=new List<Recipe>(),matchingCatalogue=new List<Recipe>();
// PRODUCTION_CLASS
internal void Open(IList<Recipe> recipes)=>RefreshStationCatalogue(recipes);
}
class Check {static void Assert(bool v,string reason){if(!v)throw new Exception(reason);}static void Main(){var w=new Workspace();w.station.Workstation="mortar";var z=new Recipe{Name="Z",Area="mortar",Cooking=true};var a=new Recipe{Name="A",Area="mortar",Cooking=true};var excluded=new Recipe{Name="B",Area="workbench",Cooking=true};var nonfood=new Recipe{Name="C",Area="mortar",Cooking=false};var all=new List<Recipe>{z,excluded,a,nonfood};w.Open(all);Assert(w.matchingCatalogue.Count==2&&w.matchingCatalogue[0].Name=="Z"&&w.matchingCatalogue[1].Name=="A","Native match order retained");Assert(w.catalogue[0].Name=="A"&&w.catalogue[1].Name=="Z","Display sort separate");Assert(RebirthCookingCatalogue.Projected==2&&all[0]==z,"Project only eligible candidates without source mutation");w.Open(new[]{a});Assert(w.matchingCatalogue.Count==1&&w.catalogue.Count==1,"Reopen discards previous candidates");w.station.Workstation="workbench";w.Open(all);Assert(w.matchingCatalogue.Count==1&&w.matchingCatalogue[0].Name=="B","Changed station rebuilds candidates");w.Open(new Recipe[0]);Assert(w.matchingCatalogue.Count==0&&w.catalogue.Count==0,"Empty reopen clears both views");Console.WriteLine("PASS actual per-open catalogue refresh with disclosed filter/projection/localization doubles: native match order, independent display sort, candidate filtering, station switch and empty/repeated opens");}}
