using UnityEngine;
using System;using System.Collections.Generic;
namespace UnityEngine{public struct Vector3{public static Vector3 zero;}}
enum QuickStackRadialAction:byte{Deposit=0,PullVehicle=5,PullDrone=7,CompanionInventoryPull=8,PullVehicleCredits=9,PullDroneCredits=10}
class ItemValue{public string Id;public override bool Equals(object o){return o is ItemValue&&((ItemValue)o).Id==Id;}public override int GetHashCode(){return Id.GetHashCode();}}
class ItemStack{public ItemValue itemValue;public int count;public bool IsEmpty(){return count<=0;}public ItemStack Clone(){return new ItemStack{itemValue=new ItemValue{Id=itemValue.Id},count=count};}}
class Bag{public int Capacity=2,Added,Unrelated=9;}
class EntityPlayerLocal{public Bag bag=new Bag();public UnityEngine.Vector3 position;public int entityId=7;}
class World{public EntityPlayerLocal Player=new EntityPlayerLocal();public EntityPlayerLocal GetPrimaryPlayer(){return Player;}}
class GameManager{public static GameManager Instance=new GameManager();public World World=new World();public int Dropped;public void ItemDropServer(ItemStack s,UnityEngine.Vector3 p,UnityEngine.Vector3 v,int id,float lifetime,bool b){if(id!=7)throw new Exception("owner");Dropped+=s.count;}}
static class LogisticsTransferService{public static void MoveIntoBag(EntityPlayerLocal p,ItemStack s){int n=Math.Min(p.bag.Capacity,s.count);p.bag.Added+=n;p.bag.Capacity-=n;s.count-=n;}}
// PRODUCTION_METHOD
class Check{static ItemStack S(string id,int n){return new ItemStack{itemValue=new ItemValue{Id=id},count=n};}static int Count(ItemStack[] stacks,string id){int n=0;foreach(var s in stacks)if(s.itemValue.Id==id)n+=s.count;return n;}
static void Main(){for(int i=0;i<256;i++){var action=(QuickStackRadialAction)i;var mapped=LogisticsInventoryCredits.RequestAction(action);if((byte)mapped!=(i==5?9:i==7?10:i)||LogisticsInventoryCredits.UsesReceipt(action)!=(i>=8&&i<=10)||(byte)LogisticsInventoryCredits.ExecutionAction(action)!=(i==9?5:i==10?7:i))throw new Exception("wire action mapping");}var before=new[]{S("a-quality1",4),S("a-quality1",2),S("a-quality2",3)};var after=new[]{S("a-quality2",3),S("a-quality1",3),S("new-metadata",5),S("a-quality1",6)};var credits=LogisticsInventoryCredits.Capture(before,after);if(Count(credits,"a-quality1")!=3||Count(credits,"a-quality2")!=0||Count(credits,"new-metadata")!=5||before[0].count!=4||after[3].count!=6)throw new Exception("delta");if(LogisticsInventoryCredits.Capture(before,new[]{S("a-quality2",3),S("a-quality1",6)}).Length!=0)throw new Exception("slot move grant");LogisticsInventoryCredits.Apply(credits);var bag=GameManager.Instance.World.Player.bag;if(bag.Unrelated!=9||bag.Added!=2||GameManager.Instance.Dropped!=6||Count(credits,"a-quality1")!=3)throw new Exception("current backpack conservation/receipt mutation");if(LogisticsInventoryCredits.Capture(null,null).Length!=0)throw new Exception("null delta");Console.WriteLine("PASS: exact metadata credits across split/reordered stacks; source snapshots unchanged; current unrelated items retained; overflow conserved without mutating receipt");}}
