// ADAPTER
namespace UnityEngine{public class Component{} public class Transform:Component{public Transform parent;public Component component;public Component GetComponent(string n){return component;}}public static class Mathf{public static float Clamp01(float f){return f<0?0:f>1?1:f;}}}
public class XUiController{public View ViewComponent;}
public class View{public UnityEngine.Transform UiTransform;}
public class Bar{public float value{get;set;}public float barSize{get;set;}}
public class Scroll:UnityEngine.Component{public Bar verticalScrollBar;public int invalidated,updated;public void InvalidateBounds(){invalidated++;}public void UpdateScrollbars(bool force){if(!force)throw new Exception();updated++;}}
public class FieldBar{public float value;public float barSize;}
public class OldScroll:UnityEngine.Component{public FieldBar verticalScrollBar;public int reset;public void ResetPosition(){reset++;}}
public class Check{static void Need(bool b,string m){if(!b)throw new Exception(m);}static int Main(){var a=new Scroll{verticalScrollBar=new Bar{value=.2f}};var t=new UnityEngine.Transform{component=a};var c=new XUiController{ViewComponent=new View{UiTransform=t}};float v;
for(int i=0;i<100;i++)Need(RebirthNativeScrollbarUtil.TryGetValue(c,out v)&&v==.2f,"property read");Need(RebirthNativeScrollbarUtil.TrySetValue(c,2)&&a.verticalScrollBar.value==1,"clamp");RebirthNativeScrollbarUtil.Refresh(c);Need(a.updated==1&&a.invalidated==1,"refresh");var b=new Scroll{verticalScrollBar=new Bar{value=.7f}};t.component=b;Need(RebirthNativeScrollbarUtil.TryGetValue(c,out v)&&v==.7f,"reopened component");Need(RebirthNativeScrollbarUtil.TrySetValue(c,.4f)&&b.verticalScrollBar.value==.4f&&a.verticalScrollBar.value==1,"no old instance mutation");b.verticalScrollBar=new Bar{value=.9f};Need(RebirthNativeScrollbarUtil.TryGetValue(c,out v)&&v==.9f,"replacement bar");var old=new OldScroll{verticalScrollBar=new FieldBar{value=.6f}};t.component=null;t.parent=new UnityEngine.Transform{component=old};Need(RebirthNativeScrollbarUtil.TryGetValue(c,out v)&&v==.6f,"parent field read");Need(RebirthNativeScrollbarUtil.TrySetValue(c,-1)&&old.verticalScrollBar.value==0,"field write");RebirthNativeScrollbarUtil.Refresh(c);Need(old.reset==1,"legacy reset");t.parent=null;Need(!RebirthNativeScrollbarUtil.TryGetValue(c,out v),"missing component");Need(!RebirthNativeScrollbarUtil.TrySetValue(null,.2f),"null controller");Console.WriteLine("PASS: cached adapter reads/writes live reopened components, replacement bars, fields/properties, clamping and refresh fallback");return 0;}}
