using System;
using System.Linq;

// Live preparation producer; publication/payment remains a separate durable commit.
public static class RebirthStationPreparationService
{
    public static bool TryPrepare(EntityPlayer player,Vector3i position,string creationId,Guid job,
        Recipe recipe,int batches,out RebirthStationGridAdmission admission)
    {
        admission=null;
        if(job==Guid.Empty||recipe==null||RebirthStationGridQueue.IsMarked(recipe)||
            !RebirthStationLiveAccess.TryResolve(player,position,creationId,out var station,out var owner))return false;
        var definitions=XUiM_Recipes.GetRecipes();
        if(definitions==null||!definitions.Any(r=>ReferenceEquals(r,recipe))||!recipe.IsUnlocked(player))return false;
        var block=station.block;
        if(block==null)return false;
        string areas=block.Properties.Contains("Workstation","CraftingAreaRecipes")
            ?block.Properties.GetString("Workstation","CraftingAreaRecipes"):block.GetBlockName();
        if(string.IsNullOrEmpty(areas)||!areas.Split(',').Any(a=>
            string.Equals(a.Trim()=="player"?string.Empty:a.Trim(),recipe.craftingArea??string.Empty,StringComparison.OrdinalIgnoreCase)))return false;
        if(recipe.craftingToolType!=0&&(station.Tools==null||!station.Tools.Any(s=>
            s!=null&&!s.IsEmpty()&&s.itemValue.type==recipe.craftingToolType)))return false;
        int tier=Math.Max(1,Math.Min(XUiM_Recipes.CraftingMaxTier,recipe.GetCraftingTier(player)));
        float seconds=EffectManager.GetValue(PassiveEffects.CraftingTime,_originalValue:recipe.craftingTime,
            _entity:player,_recipe:recipe,tags:recipe.tags)*XUiM_Recipes.CraftingTimeModifier;
        if(float.IsNaN(seconds)||float.IsInfinity(seconds))return false;
        seconds=Math.Max(0,seconds);
        var input=station.Input;
        if(input==null||!RebirthStationGridIngredients.TryPlan(player,recipe,input,batches,tier,out var plan)||
            !RebirthStationGridAdmission.TryCreate(job,creationId,position.x,position.y,position.z,
                block.GetBlockName(),plan,input,seconds,definitions,out var prepared))return false;
        // Recheck live custody and exact input after allocation/serialization, before saving intent.
        if(!RebirthStationLiveAccess.TryResolve(player,position,creationId,out var current,out var currentOwner)||
            !ReferenceEquals(current,station)||!ReferenceEquals(currentOwner,owner)||
            !RebirthStationGridIngredients.TryBuildDebitedGrid(plan,current.Input,out _))return false;
        if(!RebirthStationPreparationReservation.TryRegister(player.world,owner,prepared,()=>
        {
            if(!RebirthWorldCharacterService.TryGetIdentity(player,out var identity))return false;
            RebirthWorldCharacterService.MarkDirty(owner,"station-preparation");
            return RebirthWorldCharacterRepository.SaveIfDirty(identity,"station-preparation");
        }))return false;
        admission=prepared;return true;
    }
}
public struct Vector3i {public int x,y,z;}
public class World {}
public class EntityPlayer {public int entityId=42;public World world=new World();}
public class ItemValue {public int type;}
public class ItemStack {public ItemStack Clone(){return new ItemStack{count=count,itemValue=new ItemValue{type=itemValue.type}};}public static ItemStack[] CreateArray(int n){var a=new ItemStack[n];for(int i=0;i<n;i++)a[i]=new ItemStack{count=0};return a;}public int count=1;public ItemValue itemValue=new ItemValue();public bool IsEmpty(){return count<1;}}
public class Properties {public string Areas;public bool Contains(string a,string b){return Areas!=null;}public string GetString(string a,string b){return Areas;}}
public class Block {public Properties Properties=new Properties();public string GetBlockName(){return "workbench";}}
public static class RebirthStationNativeInputCodec {public static bool Valid=true;public static bool IsRoundTrippable(System.Collections.Generic.IList<ItemStack> input){return Valid;}}
public class RecipeQueueItem {public Recipe Recipe;}
public class TileEntityWorkstation {public bool bDisableModifiedCheck;public void SetDisableModifiedCheck(bool b){bDisableModifiedCheck=b;}public int Notifications;public bool FailQueue,FailNotify;public void SetModified(){Notifications++;if(FailNotify)throw new System.Exception("notification fault");}public int InputSlotCount=3;public string[] MaterialNames=new string[0];private RecipeQueueItem[] queue=new RecipeQueueItem[0];public RecipeQueueItem[] Queue{get{return queue;}set{if(FailQueue)throw new System.Exception("queue setter fault");queue=value;}}public Block block=new Block();public ItemStack[] Input={new ItemStack(),new ItemStack(),new ItemStack()};public ItemStack[] Tools=new ItemStack[0];}
public class Progression {public System.Collections.Generic.Dictionary<string,object> StationPublications=new System.Collections.Generic.Dictionary<string,object>();public System.Collections.Generic.Dictionary<string,RebirthStationGridAdmission> StationPreparations=new System.Collections.Generic.Dictionary<string,RebirthStationGridAdmission>();}
public class RebirthWorldCharacterRecord {public Progression Progression=new Progression();}
public class Recipe {public string GetName(){return "testRecipe";}public string JobId;public bool Unlocked=true,Marked;public string craftingArea="workbench";public int craftingToolType;public float craftingTime=10;public object tags;public bool IsUnlocked(EntityPlayer p){return Unlocked;}public int GetCraftingTier(EntityPlayer p){return 3;}}
public static class XUiM_Recipes {public static int CraftingMaxTier=6;public static float CraftingTimeModifier=2;public static System.Collections.Generic.List<Recipe> Definitions=new System.Collections.Generic.List<Recipe>();public static System.Collections.Generic.List<Recipe> GetRecipes(){return Definitions;}}
public enum PassiveEffects {CraftingTime}
public static class EffectManager {public static float Value=4;public static float GetValue(PassiveEffects e,float _originalValue,EntityPlayer _entity,Recipe _recipe,object tags){return Value;}}
public static class RebirthStationGridQueue {public static bool TryGetJobId(Recipe r,out string id){id=r.JobId;return id!=null;}public static bool TryGetAdmittedSource(Recipe q,System.Collections.Generic.IList<Recipe> d,out Recipe source){source=d.Count>0?d[0]:null;return source!=null;}public static bool IsMarked(Recipe r){return r.Marked;}}
public static class RebirthStationLiveAccess {public static int FailAt;public static bool Allowed=true,FailSecond;public static int Calls;public static TileEntityWorkstation Station=new TileEntityWorkstation();public static RebirthWorldCharacterRecord Owner=new RebirthWorldCharacterRecord();public static bool TryResolve(EntityPlayer p,Vector3i v,string c,out TileEntityWorkstation s,out RebirthWorldCharacterRecord o){Calls++;s=Station;o=Owner;return Allowed&&Calls!=FailAt&&!(FailSecond&&Calls==2);}}
public static class RebirthStationGridIngredients {public static bool IsSameStackSnapshot(ItemStack a,ItemStack b){return a!=null&&b!=null&&a.count==b.count&&a.itemValue.type==b.itemValue.type;}public class Plan {}public static bool Exact=true;public static int GridCount;public static int Tier;public static bool TryPlan(EntityPlayer p,Recipe r,ItemStack[] input,int batches,int tier,out Plan plan){GridCount=input.Length;Tier=tier;plan=new Plan();return batches>0;}public static bool TryBuildDebitedGrid(Plan p,ItemStack[] input,out ItemStack[] remainder){remainder=null;return Exact;}}
public class RebirthStationGridAdmission {public bool IsPublicationAttempted;public string CreationId="creation";public int X,Y,Z;public System.Xml.Linq.XElement Write(){return new System.Xml.Linq.XElement("admission",new System.Xml.Linq.XAttribute("x",X),new System.Xml.Linq.XAttribute("y",Y),new System.Xml.Linq.XAttribute("z",Z));}public static ItemStack[] Before,After;public static bool Unpaid=true;public RebirthStationGridAdmission Clone(){return this;}public bool MatchesUnpaidObservation(string c,int x,int y,int z,string block,ItemStack[] i){return Unpaid&&!IsPublicationAttempted;}public bool TryMaterialize(System.Collections.Generic.IList<Recipe> d,out Recipe q,out ItemStack[] a,out ItemStack[] b){q=d.Count>0?d[0]:null;a=Before;b=After;return q!=null;}public static float Seconds;public static bool TryCreate(System.Guid j,string c,int x,int y,int z,string block,RebirthStationGridIngredients.Plan p,ItemStack[] input,float seconds,System.Collections.Generic.IList<Recipe> defs,out RebirthStationGridAdmission result){Seconds=seconds;result=new RebirthStationGridAdmission();return true;}}
public static class RebirthStationPreparationReservation {public static bool TryMarkPublicationAttempt(object w,RebirthWorldCharacterRecord o,RebirthStationGridAdmission p,System.Func<RebirthStationGridAdmission,bool> save,out RebirthStationGridAdmission attempted){attempted=null;if(!Acquired||p.IsPublicationAttempted)return false;AttemptCalls++;p.IsPublicationAttempted=true;attempted=p;return save(p);}public static bool TryAcquire(object w,RebirthWorldCharacterRecord o,RebirthStationGridAdmission a){return Acquired;}public static bool TryConsumeNativeAttempt(object w,RebirthWorldCharacterRecord o,RebirthStationGridAdmission a){ConsumeCalls++;return Consumable&&a.IsPublicationAttempted;}public static bool Consumable=true;public static int ConsumeCalls;public static int AttemptCalls;public static bool Acquired=true;public static int Registrations;public static RebirthStationGridAdmission Pending;public static bool TryRegister(object w,RebirthWorldCharacterRecord owner,RebirthStationGridAdmission a,System.Func<bool> save){Registrations++;Pending=a;return save();}}
public static class RebirthWorldCharacterService {public static bool TryGet(EntityPlayer p,out RebirthWorldCharacterRecord r){r=RebirthStationLiveAccess.Owner;return true;}public static bool Identity=true;public static bool TryGetIdentity(EntityPlayer p,out object identity){identity=new object();return Identity;}public static void MarkDirty(RebirthWorldCharacterRecord r,string s){}}
public static class RebirthWorldCharacterRepository {public static bool IsCurrentCachedRecord(RebirthWorldCharacterRecord r){return object.ReferenceEquals(r,RebirthStationLiveAccess.Owner);}public static int WitnessCalls,FailWitnessAt;public static bool Witness=true;public static bool HasSavedStationPreparation(object i,RebirthStationGridAdmission a){WitnessCalls++;return Witness&&WitnessCalls!=FailWitnessAt;}public static int SaveCalls,FailSaveAt;public static bool Saved=true;public static bool SaveIfDirty(object i,string s){SaveCalls++;return Saved&&SaveCalls!=FailSaveAt;}}
public static class StationPreparationFixture {
static int checks;
static void Check(bool condition,string name){checks++;if(!condition)throw new System.Exception(name);}
static Recipe Reset(){RebirthRecipeDiscoveryRules.Allowed=true;RebirthWorldCharacterRepository.WitnessCalls=0;RebirthWorldCharacterRepository.FailWitnessAt=0;RebirthStationPreparationReservation.Consumable=true;RebirthStationPreparationReservation.ConsumeCalls=0;RebirthStationNativeQueueSnapshot.Capturable=true;RebirthStationNativeQueueSnapshot.Unchanged=true;RebirthStationLiveAccess.FailAt=0;RebirthStationNativeQueueEntry.EntryValid=true;RebirthStationNativeQueueEntry.Vacant=true;RebirthStationPreparationReservation.AttemptCalls=0;RebirthWorldCharacterRepository.SaveCalls=0;RebirthWorldCharacterRepository.FailSaveAt=0;RebirthStationGridAdmission.Before=null;RebirthStationGridAdmission.After=null;RebirthStationPreparationReservation.Acquired=true;RebirthStationNativeInputCodec.Valid=true;RebirthStationLiveAccess.Owner=new RebirthWorldCharacterRecord();RebirthStationGridAdmission.Unpaid=true;RebirthStationLiveAccess.Calls=0;RebirthStationLiveAccess.Allowed=true;RebirthStationLiveAccess.FailSecond=false;RebirthStationLiveAccess.Station=new TileEntityWorkstation();RebirthStationGridIngredients.Exact=true;RebirthWorldCharacterRepository.Saved=true;RebirthWorldCharacterRepository.Witness=true;RebirthWorldCharacterService.Identity=true;EffectManager.Value=4;RebirthStationPreparationReservation.Registrations=0;RebirthStationPreparationReservation.Pending=null;var r=new Recipe();XUiM_Recipes.Definitions.Clear();XUiM_Recipes.Definitions.Add(r);RebirthStationGridAdmission.Before=RebirthStationLiveAccess.Station.Input.Select(x=>x.Clone()).ToArray();RebirthStationGridAdmission.After=RebirthStationGridAdmission.Before.Select(x=>x.Clone()).ToArray();return r;}
static bool Prepare(Recipe r){RebirthStationGridAdmission a;return RebirthStationPreparationService.TryPrepare(new EntityPlayer(),new Vector3i(),"creation",System.Guid.NewGuid(),r,2,out a);}
public static string Run(){
var r=Reset();Check(Prepare(r)&&RebirthStationGridIngredients.Tier==3&&RebirthStationGridAdmission.Seconds==8,"derived timing/tier");Check(RebirthStationLiveAccess.Station.Input[0].count==1,"input untouched");
r=Reset();Check(!Prepare(new Recipe())&&RebirthStationPreparationReservation.Registrations==0,"foreign recipe");
r=Reset();r.Unlocked=false;Check(!Prepare(r),"locked recipe");
r=Reset();RebirthStationLiveAccess.Allowed=false;Check(!Prepare(r),"live access denied");
r=Reset();r.craftingArea="forge";Check(!Prepare(r),"wrong physical area");
r=Reset();RebirthStationLiveAccess.Station.block.Properties.Areas="forge, player";r.craftingArea="";Check(Prepare(r),"hand alias");
r=Reset();r.craftingToolType=42;Check(!Prepare(r),"missing tool");RebirthStationLiveAccess.Station.Tools=new[]{new ItemStack{itemValue=new ItemValue{type=42}}};Check(Prepare(r),"present tool");
r=Reset();EffectManager.Value=float.NaN;Check(!Prepare(r),"nonfinite timing");
r=Reset();RebirthStationGridIngredients.Exact=false;Check(!Prepare(r)&&RebirthStationPreparationReservation.Registrations==0,"changed snapshot");
r=Reset();RebirthStationLiveAccess.FailSecond=true;Check(!Prepare(r)&&RebirthStationPreparationReservation.Registrations==0,"lost access before save");
r=Reset();RebirthWorldCharacterRepository.Saved=false;Check(!Prepare(r)&&RebirthStationPreparationReservation.Pending!=null&&RebirthStationLiveAccess.Station.Input[0].count==1,"failed save retains intent without debit");
r=Reset();RebirthWorldCharacterRepository.Witness=false;Check(!Prepare(r)&&RebirthStationPreparationReservation.Pending!=null,"readback mismatch retains intent");
r=Reset();r.Marked=true;Check(!Prepare(r),"paid recipe rejection");
r=Reset();var job=System.Guid.NewGuid();var pending=new RebirthStationGridAdmission();RebirthStationLiveAccess.Owner.Progression.StationPreparations.Add(job.ToString("N"),pending);EffectManager.Value=float.NaN;RebirthStationGridAdmission retried;Check(RebirthStationPreparationService.TryRetryUnpaid(new EntityPlayer(),new Vector3i(),"creation",job,out retried),"retry preserved intent without recalculating timing");RebirthStationGridAdmission.Unpaid=false;Check(!RebirthStationPreparationService.TryRetryUnpaid(new EntityPlayer(),new Vector3i(),"creation",job,out retried),"retry rejects changed before grid");RebirthStationGridAdmission.Unpaid=true;r.Unlocked=false;Check(!RebirthStationPreparationService.TryRetryUnpaid(new EntityPlayer(),new Vector3i(),"creation",job,out retried),"retry requires current unlock");
r.Unlocked=true;RebirthStationLiveAccess.Owner.Progression.StationPublications.Add(job.ToString("N"),new object());Check(!RebirthStationPreparationService.TryRetryUnpaid(new EntityPlayer(),new Vector3i(),"creation",job,out retried),"published intent cannot retry unpaid");RebirthStationLiveAccess.Owner.Progression.StationPublications.Clear();RebirthStationLiveAccess.Station.Queue=new[]{new RecipeQueueItem{Recipe=new Recipe{Marked=true,JobId=job.ToString("N")}}};Check(!RebirthStationPreparationService.TryRetryUnpaid(new EntityPlayer(),new Vector3i(),"creation",job,out retried),"native queued job cannot retry unpaid");RebirthStationLiveAccess.Station.Queue[0].Recipe.JobId=null;Check(!RebirthStationPreparationService.TryRetryUnpaid(new EntityPlayer(),new Vector3i(),"creation",job,out retried),"malformed marked job holds retry");
r=Reset();RebirthStationLiveAccess.Station.MaterialNames=new[]{"iron","brass","lead"};RebirthStationLiveAccess.Station.Input=ItemStack.CreateArray(6);RebirthStationLiveAccess.Station.Input[5].count=999;Check(Prepare(r)&&RebirthStationGridIngredients.GridCount==3&&RebirthStationLiveAccess.Station.Input[5].count==999,"legacy forge totals excluded from plan and unchanged");r=Reset();RebirthStationLiveAccess.Station.MaterialNames=new[]{"iron"};RebirthStationLiveAccess.Station.InputSlotCount=9;RebirthStationLiveAccess.Station.Input=ItemStack.CreateArray(10);RebirthStationLiveAccess.Station.Input[9].count=777;Check(Prepare(r)&&RebirthStationGridIngredients.GridCount==9&&RebirthStationLiveAccess.Station.Input[9].count==777,"nine-slot forge physical projection excludes totals");r=Reset();RebirthStationLiveAccess.Station.MaterialNames=null;Check(!Prepare(r),"unknown material layout held");
r=Reset();job=System.Guid.NewGuid();RebirthStationLiveAccess.Owner.Progression.StationPreparations.Add(job.ToString("N"),new RebirthStationGridAdmission());RebirthStationNativeInputCodec.Valid=false;Check(!RebirthStationPreparationService.TryRetryUnpaid(new EntityPlayer(),new Vector3i(),"creation",job,out retried)&&RebirthStationPreparationReservation.Registrations==0,"retry rejects native payload loss before save");
r=Reset();job=System.Guid.NewGuid();RebirthStationLiveAccess.Owner.Progression.StationPreparations.Add(job.ToString("N"),new RebirthStationGridAdmission());RebirthStationLiveAccess.FailSecond=true;Check(!RebirthStationPreparationService.TryRetryUnpaid(new EntityPlayer(),new Vector3i(),"creation",job,out retried)&&RebirthStationPreparationReservation.Registrations==0,"retry rejects lost custody before save");
r=Reset();job=System.Guid.NewGuid();pending=new RebirthStationGridAdmission();RebirthStationLiveAccess.Owner.Progression.StationPreparations.Add(job.ToString("N"),pending);var station=RebirthStationLiveAccess.Station;station.MaterialNames=new[]{"iron"};station.Input=ItemStack.CreateArray(4);station.Input[0].count=5;station.Input[0].itemValue.type=7;station.Input[3].count=777;
RebirthStationInputLayout.TryReadPhysical(station.Input,3,1,out RebirthStationGridAdmission.Before);RebirthStationGridAdmission.After=RebirthStationGridAdmission.Before.Select(x=>x.Clone()).ToArray();RebirthStationGridAdmission.After[0].count=2;
Recipe queued;ItemStack[] merged;RebirthStationGridAdmission built;
Check(RebirthStationPreparationService.TryBuildPublicationInputs(new EntityPlayer(),new Vector3i(),"creation",job,out built,out queued,out merged)&&built!=null&&queued!=null&&merged[0].count==2&&merged[3].count==777&&station.Input[0].count==5,"publication inputs preserve forge totals without native debit");
station.Input[0].count=4;Check(!RebirthStationPreparationService.TryBuildPublicationInputs(new EntityPlayer(),new Vector3i(),"creation",job,out built,out queued,out merged)&&built==null&&queued==null&&merged==null,"changed native input holds publication preparation");station.Input[0].count=5;
RebirthStationPreparationReservation.Acquired=false;Check(!RebirthStationPreparationService.TryBuildPublicationInputs(new EntityPlayer(),new Vector3i(),"creation",job,out built,out queued,out merged),"reservation loss holds publication preparation");RebirthStationPreparationReservation.Acquired=true;
r.Unlocked=false;Check(!RebirthStationPreparationService.TryBuildPublicationInputs(new EntityPlayer(),new Vector3i(),"creation",job,out built,out queued,out merged),"lost recipe unlock holds publication preparation");
r=Reset();job=System.Guid.NewGuid();pending=new RebirthStationGridAdmission{IsPublicationAttempted=true};RebirthStationLiveAccess.Owner.Progression.StationPreparations.Add(job.ToString("N"),pending);
Check(RebirthStationPreparationService.TryConfirmPublicationAttempt(new EntityPlayer(),new Vector3i(),"creation",job,out built)&&built!=null&&RebirthStationLiveAccess.Station.Input[0].count==1&&RebirthStationPreparationReservation.Registrations==0,"attempt confirmation saves only without debit or registration");
RebirthWorldCharacterRepository.Saved=false;Check(!RebirthStationPreparationService.TryConfirmPublicationAttempt(new EntityPlayer(),new Vector3i(),"creation",job,out built)&&built==null&&RebirthStationLiveAccess.Owner.Progression.StationPreparations[job.ToString("N")]==pending,"failed attempt save retains exact intent");RebirthWorldCharacterRepository.Saved=true;
RebirthWorldCharacterRepository.Witness=false;Check(!RebirthStationPreparationService.TryConfirmPublicationAttempt(new EntityPlayer(),new Vector3i(),"creation",job,out built)&&built==null,"attempt readback mismatch holds confirmation");RebirthWorldCharacterRepository.Witness=true;
RebirthStationPreparationReservation.Acquired=false;Check(!RebirthStationPreparationService.TryConfirmPublicationAttempt(new EntityPlayer(),new Vector3i(),"creation",job,out built),"attempt lost reservation refused");RebirthStationPreparationReservation.Acquired=true;
pending.CreationId="other";Check(!RebirthStationPreparationService.TryConfirmPublicationAttempt(new EntityPlayer(),new Vector3i(),"creation",job,out built),"attempt different character refused");pending.CreationId="creation";
pending.X=1;Check(!RebirthStationPreparationService.TryConfirmPublicationAttempt(new EntityPlayer(),new Vector3i(),"creation",job,out built),"attempt different position refused");pending.X=0;
pending.IsPublicationAttempted=false;Check(!RebirthStationPreparationService.TryConfirmPublicationAttempt(new EntityPlayer(),new Vector3i(),"creation",job,out built),"unpaid intent cannot confirm attempted save");pending.IsPublicationAttempted=true;
RebirthStationLiveAccess.Owner.Progression.StationPublications.Add(job.ToString("N"),new object());Check(!RebirthStationPreparationService.TryConfirmPublicationAttempt(new EntityPlayer(),new Vector3i(),"creation",job,out built),"already published attempt refused");RebirthStationLiveAccess.Owner.Progression.StationPublications.Clear();
RebirthStationLiveAccess.Allowed=false;Check(!RebirthStationPreparationService.TryConfirmPublicationAttempt(new EntityPlayer(),new Vector3i(),"creation",job,out built),"attempt lost live custody refused");RebirthStationLiveAccess.Allowed=true;
Check(RebirthStationPreparationService.TryConfirmPublicationAttempt(new EntityPlayer(),new Vector3i(),"creation",job,out built)&&RebirthStationPreparationService.TryConfirmPublicationAttempt(new EntityPlayer(),new Vector3i(),"creation",job,out built)&&RebirthStationLiveAccess.Station.Queue.Length==0&&RebirthStationLiveAccess.Station.Input[0].count==1,"repeat confirmation never queues or debits");
r=Reset();job=System.Guid.NewGuid();pending=new RebirthStationGridAdmission();RebirthStationLiveAccess.Owner.Progression.StationPreparations.Add(job.ToString("N"),pending);
RebirthStationNativeQueueEntry.Vacant=false;Check(!RebirthStationPreparationService.TryBeginPublicationAttempt(new EntityPlayer(),new Vector3i(),"creation",job,out built)&&!pending.IsPublicationAttempted&&RebirthStationPreparationReservation.AttemptCalls==0,"full queue refuses attempt transition");
RebirthStationNativeQueueEntry.Vacant=true;Check(RebirthStationPreparationService.TryBeginPublicationAttempt(new EntityPlayer(),new Vector3i(),"creation",job,out built)&&built.IsPublicationAttempted&&RebirthWorldCharacterRepository.SaveCalls==3&&RebirthStationLiveAccess.Station.Input[0].count==1,"attempt saves transitioned intent after unpaid witness without native debit");
Check(!RebirthStationPreparationService.TryBeginPublicationAttempt(new EntityPlayer(),new Vector3i(),"creation",job,out built)&&RebirthStationPreparationReservation.AttemptCalls==1,"attempt cannot restart through unpaid route");
r=Reset();job=System.Guid.NewGuid();pending=new RebirthStationGridAdmission();RebirthStationLiveAccess.Owner.Progression.StationPreparations.Add(job.ToString("N"),pending);RebirthWorldCharacterRepository.FailSaveAt=2;
Check(!RebirthStationPreparationService.TryBeginPublicationAttempt(new EntityPlayer(),new Vector3i(),"creation",job,out built)&&built==pending&&pending.IsPublicationAttempted&&RebirthStationLiveAccess.Station.Input[0].count==1,"failed transitioned save retains attempted intent without payment");
Check(RebirthStationPreparationService.TryConfirmPublicationAttempt(new EntityPlayer(),new Vector3i(),"creation",job,out built)&&RebirthStationPreparationReservation.AttemptCalls==1,"failed transition can confirm save without repeating attempt");
r=Reset();job=System.Guid.NewGuid();pending=new RebirthStationGridAdmission();RebirthStationLiveAccess.Owner.Progression.StationPreparations.Add(job.ToString("N"),pending);RebirthStationNativeQueueEntry.EntryValid=false;
Check(!RebirthStationPreparationService.TryBeginPublicationAttempt(new EntityPlayer(),new Vector3i(),"creation",job,out built)&&!pending.IsPublicationAttempted&&RebirthStationPreparationReservation.AttemptCalls==0,"invalid native entry refuses attempt before phase transition");RebirthStationNativeQueueEntry.EntryValid=true;
Check(!RebirthStationPreparationService.TryBeginPublicationAttempt(new EntityPlayer{entityId=0},new Vector3i(),"creation",job,out built)&&!pending.IsPublicationAttempted&&RebirthStationPreparationReservation.AttemptCalls==0,"invalid native actor refuses attempt before phase transition");
r=Reset();job=System.Guid.NewGuid();pending=new RebirthStationGridAdmission();RebirthStationLiveAccess.Owner.Progression.StationPreparations.Add(job.ToString("N"),pending);RebirthStationGridAdmission.After[0].count=2;
Check(!RebirthStationPreparationService.TryBeginPublicationAttempt(new EntityPlayer(),new Vector3i(),"creation",job,out built)&&!pending.IsPublicationAttempted&&RebirthStationPreparationReservation.AttemptCalls==0,"increasing remainder refuses attempt before transition");
RebirthStationGridAdmission.After[0].count=1;RebirthStationGridAdmission.After[0].itemValue.type=999;
Check(!RebirthStationPreparationService.TryBeginPublicationAttempt(new EntityPlayer(),new Vector3i(),"creation",job,out built)&&!pending.IsPublicationAttempted&&RebirthStationPreparationReservation.AttemptCalls==0,"substituted remainder refuses attempt before transition");
r=Reset();job=System.Guid.NewGuid();pending=new RebirthStationGridAdmission();RebirthStationLiveAccess.Owner.Progression.StationPreparations.Add(job.ToString("N"),pending);RebirthStationLiveAccess.FailAt=4;
Check(!RebirthStationPreparationService.TryBeginPublicationAttempt(new EntityPlayer(),new Vector3i(),"creation",job,out built)&&!pending.IsPublicationAttempted&&RebirthStationPreparationReservation.AttemptCalls==0&&RebirthWorldCharacterRepository.SaveCalls==1,"lost final custody holds attempt before transition save");
r=Reset();job=System.Guid.NewGuid();pending=new RebirthStationGridAdmission();RebirthStationLiveAccess.Owner.Progression.StationPreparations.Add(job.ToString("N"),pending);RebirthStationNativeQueueSnapshot.Capturable=false;
Check(!RebirthStationPreparationService.TryBeginPublicationAttempt(new EntityPlayer(),new Vector3i(),"creation",job,out built)&&!pending.IsPublicationAttempted&&RebirthStationPreparationReservation.AttemptCalls==0,"unserializable queue refuses attempt transition");RebirthStationNativeQueueSnapshot.Capturable=true;RebirthStationNativeQueueSnapshot.Unchanged=false;
Check(!RebirthStationPreparationService.TryBeginPublicationAttempt(new EntityPlayer(),new Vector3i(),"creation",job,out built)&&!pending.IsPublicationAttempted&&RebirthStationPreparationReservation.AttemptCalls==0,"changed unrelated queue state refuses attempt transition");
r=Reset();job=System.Guid.NewGuid();pending=new RebirthStationGridAdmission();RebirthStationLiveAccess.Owner.Progression.StationPreparations.Add(job.ToString("N"),pending);RebirthStationGridAdmission.After[0].count=0;
Check(RebirthStationPreparationService.TryPublishPrepared(new EntityPlayer(),new Vector3i(),"creation",job)&&pending.IsPublicationAttempted&&RebirthStationLiveAccess.Station.Input[0].count==0&&RebirthStationLiveAccess.Station.Queue.Length==1&&RebirthStationLiveAccess.Station.Notifications==1&&!RebirthStationLiveAccess.Station.bDisableModifiedCheck,"publisher applies saved payment and queue with one final notification");
Check(!RebirthStationPreparationService.TryPublishPrepared(new EntityPlayer(),new Vector3i(),"creation",job)&&RebirthStationLiveAccess.Station.Notifications==1,"published attempt cannot replay through unpaid producer");
r=Reset();job=System.Guid.NewGuid();pending=new RebirthStationGridAdmission();RebirthStationLiveAccess.Owner.Progression.StationPreparations.Add(job.ToString("N"),pending);RebirthStationLiveAccess.Station.bDisableModifiedCheck=true;
Check(!RebirthStationPreparationService.TryPublishPrepared(new EntityPlayer(),new Vector3i(),"creation",job)&&!pending.IsPublicationAttempted&&RebirthStationLiveAccess.Station.bDisableModifiedCheck,"externally suppressed station refused without stealing gate");
r=Reset();job=System.Guid.NewGuid();pending=new RebirthStationGridAdmission();RebirthStationLiveAccess.Owner.Progression.StationPreparations.Add(job.ToString("N"),pending);RebirthStationGridAdmission.After[0].count=0;RebirthStationLiveAccess.Station.FailQueue=true;
Check(!RebirthStationPreparationService.TryPublishPrepared(new EntityPlayer(),new Vector3i(),"creation",job)&&pending.IsPublicationAttempted&&RebirthStationLiveAccess.Station.Input[0].count==0&&RebirthStationLiveAccess.Station.Queue.Length==0&&!RebirthStationLiveAccess.Station.bDisableModifiedCheck&&RebirthStationLiveAccess.Station.Notifications==1&&RebirthStationPreparationReservation.ConsumeCalls==1,"queue setter failure retains paid uncertain intent and restores notification gate");
Check(!RebirthStationPreparationService.TryPublishPrepared(new EntityPlayer(),new Vector3i(),"creation",job)&&RebirthStationPreparationReservation.ConsumeCalls==1,"partial publisher cannot repeat mutation");
r=Reset();job=System.Guid.NewGuid();pending=new RebirthStationGridAdmission();RebirthStationLiveAccess.Owner.Progression.StationPreparations.Add(job.ToString("N"),pending);RebirthStationGridAdmission.After[0].count=0;RebirthStationLiveAccess.Station.FailNotify=true;
Check(!RebirthStationPreparationService.TryPublishPrepared(new EntityPlayer(),new Vector3i(),"creation",job)&&pending.IsPublicationAttempted&&RebirthStationLiveAccess.Station.Input[0].count==0&&RebirthStationLiveAccess.Station.Queue.Length==1&&!RebirthStationLiveAccess.Station.bDisableModifiedCheck&&RebirthStationPreparationReservation.ConsumeCalls==1,"notification failure retains applied queue and attempted intent without rollback");
Check(!RebirthStationPreparationService.TryPublishPrepared(new EntityPlayer(),new Vector3i(),"creation",job)&&RebirthStationPreparationReservation.ConsumeCalls==1,"notification failure cannot repeat mutation");
r=Reset();job=System.Guid.NewGuid();pending=new RebirthStationGridAdmission();RebirthStationLiveAccess.Owner.Progression.StationPreparations.Add(job.ToString("N"),pending);RebirthStationGridAdmission.After[0].count=0;RebirthStationLiveAccess.FailAt=9;
Check(!RebirthStationPreparationService.TryPublishPrepared(new EntityPlayer(),new Vector3i(),"creation",job)&&pending.IsPublicationAttempted&&RebirthStationLiveAccess.Station.Input[0].count==1&&RebirthStationLiveAccess.Station.Queue.Length==0&&RebirthStationPreparationReservation.ConsumeCalls==0,"postsave custody loss prevents native effects");
r=Reset();job=System.Guid.NewGuid();pending=new RebirthStationGridAdmission();RebirthStationLiveAccess.Owner.Progression.StationPreparations.Add(job.ToString("N"),pending);RebirthStationGridAdmission.After[0].count=0;RebirthWorldCharacterRepository.FailWitnessAt=4;
Check(!RebirthStationPreparationService.TryPublishPrepared(new EntityPlayer(),new Vector3i(),"creation",job)&&pending.IsPublicationAttempted&&RebirthStationLiveAccess.Station.Input[0].count==1&&RebirthStationLiveAccess.Station.Queue.Length==0&&RebirthStationPreparationReservation.ConsumeCalls==0,"postsave final witness loss prevents native effects");
r=Reset();job=System.Guid.NewGuid();pending=new RebirthStationGridAdmission();RebirthStationLiveAccess.Owner.Progression.StationPreparations.Add(job.ToString("N"),pending);RebirthStationGridAdmission.After[0].count=0;RebirthStationPreparationReservation.Consumable=false;
Check(!RebirthStationPreparationService.TryPublishPrepared(new EntityPlayer(),new Vector3i(),"creation",job)&&pending.IsPublicationAttempted&&RebirthStationLiveAccess.Station.Input[0].count==1&&RebirthStationLiveAccess.Station.Queue.Length==0&&RebirthStationLiveAccess.Station.Notifications==0,"postsave unavailable oneuse permission prevents native effects");
r=Reset();RebirthRecipeDiscoveryRules.Allowed=false;Check(!Prepare(r)&&RebirthStationPreparationReservation.Registrations==0&&RebirthStationLiveAccess.Station.Input[0].count==1,"configured reading gate before preparation save/payment");
r=Reset();job=System.Guid.NewGuid();pending=new RebirthStationGridAdmission();RebirthStationLiveAccess.Owner.Progression.StationPreparations.Add(job.ToString("N"),pending);RebirthRecipeDiscoveryRules.Allowed=false;
Check(!RebirthStationPreparationService.TryRetryUnpaid(new EntityPlayer(),new Vector3i(),"creation",job,out built)&&RebirthWorldCharacterRepository.SaveCalls==0,"retained unpaid retry rechecks reading policy");
Check(!RebirthStationPreparationService.TryBeginPublicationAttempt(new EntityPlayer(),new Vector3i(),"creation",job,out built)&&!pending.IsPublicationAttempted&&RebirthStationPreparationReservation.AttemptCalls==0,"reading denial prevents attempt phase");
Check(!RebirthStationPreparationService.TryPublishPrepared(new EntityPlayer(),new Vector3i(),"creation",job)&&RebirthStationLiveAccess.Station.Input[0].count==1&&RebirthStationLiveAccess.Station.Queue.Length==0,"reading denial prevents native publication");
RebirthRecipeDiscoveryRules.Allowed=true;Check(RebirthStationPreparationService.TryRetryUnpaid(new EntityPlayer(),new Vector3i(),"creation",job,out built),"reading restored permits same unpaid retry");
return "PASS "+checks+" actual preparation-service checks with explicit native/allocation/reservation/persistence doubles; not native qualification";
}}
public static class RebirthStationNativeQueueEntry{public static bool EntryValid=true;public static bool TryCreate(Recipe r,System.Collections.Generic.IList<Recipe> d,int actor,out RecipeQueueItem entry){entry=new RecipeQueueItem{Recipe=r};return EntryValid&&actor>0;}public static bool TryBuildReplacement(System.Collections.Generic.IList<RecipeQueueItem> q,System.Guid job,RecipeQueueItem entry,out RecipeQueueItem[] replacement){replacement=new[]{entry};return Vacant;}public static bool Vacant=true;public static bool TryFindVacantSlot(System.Collections.Generic.IList<RecipeQueueItem> q,System.Guid job,out int slot){slot=Vacant?0:-1;return Vacant;}}
public static class RebirthSurvivorRequestScope{public static bool Matches(string a,string b){return a==b;}}

public class RebirthStationNativeQueueSnapshot{public static bool Capturable=true,Unchanged=true;public static bool TryCapture(System.Collections.Generic.IList<RecipeQueueItem> q,out RebirthStationNativeQueueSnapshot s){s=Capturable?new RebirthStationNativeQueueSnapshot():null;return Capturable;}public bool Matches(System.Collections.Generic.IList<RecipeQueueItem> q){return Unchanged;}}

public static class RebirthStationObservationDispatcher{public static bool TrySavePreparation(EntityPlayer p,RebirthStationGridAdmission a){object identity;return RebirthWorldCharacterService.TryGetIdentity(p,out identity)&&RebirthWorldCharacterRepository.SaveIfDirty(identity,"fixture-dispatch")&&RebirthWorldCharacterRepository.HasSavedStationPreparation(identity,a);}public static bool Watchable=true;public static bool TryWatchQueued(EntityPlayer p,RebirthStationGridAdmission a){return Watchable;}}

public static class RebirthRecipeDiscoveryRules{public static bool Allowed=true;public static bool Allows(EntityPlayer p,string recipe){return Allowed;}}
