using System;
class IntValue {public int Value=5;}
class ItemClass {public ItemAction[] Actions={new ItemActionConsumeMetabolismRebirth()};public IntValue Stacknumber=new IntValue();}
class ItemValue {public int type;public string Metadata="full";public ItemClass ItemClass=new ItemClass();public ItemValue Clone(){return (ItemValue)MemberwiseClone();}public bool Equals(ItemValue b){return b!=null&&type==b.type&&Metadata==b.Metadata;}}
class ItemStack {public ItemValue itemValue;public int count;public static ItemStack Empty=new ItemStack(new ItemValue(),0);public ItemStack(ItemValue v,int c){itemValue=v;count=c;}public bool IsEmpty(){return count<=0||itemValue==null||itemValue.type==0;}public ItemStack Clone(){return new ItemStack(itemValue.Clone(),count);}public bool CanStackPartlyWith(ItemStack other,out int amount){amount=itemValue.Equals(other.itemValue)?Math.Min(other.count,Math.Max(0,itemValue.ItemClass.Stacknumber.Value-count)):0;return amount>0;}}
class PackedBoolArray {bool[] values;public PackedBoolArray(int n){values=new bool[n];}public int Length{get{return values.Length;}}public bool this[int i]{get{return values[i];}set{values[i]=value;}}}
class EntityPlayer {public int entityId=1;}
class Bag {public ItemStack[] Items;public PackedBoolArray LockedSlots;public int Writes;public ItemStack[] GetSlots(){return Items;}public void SetSlots(ItemStack[] x){Items=x;Writes++;}public void SetSlot(int i,ItemStack x){Items[i]=x;Writes++;}}
class EntityDrone {public Bag bag=new Bag();public int belongsPlayerId=1;public bool Dead;public int Syncs;public bool IsDead(){return Dead;}public void SendSyncData(ushort x){Syncs++;}}
class ItemAction {public static int InstantCalls;public virtual bool ExecuteInstantAction(EntityPlayer p,ItemStack s,bool h,object c){InstantCalls++;return true;}}
class ItemActionConsumeMetabolismRebirth:ItemAction {}
class ItemActionUseMedRebirth:ItemAction {public bool CanUseTreatment(EntityPlayer p){return true;}}
class RebirthConsumableDefinition {}
static class RebirthConsumableResolver {public static bool TryResolve(ItemValue v,out RebirthConsumableDefinition d){d=new RebirthConsumableDefinition();return true;}}
struct RebirthConsumeResult {public bool Success;}
static class RebirthMetabolismService {public static int Effects;public static RebirthConsumeResult ConsumeExternalSource(EntityPlayer p,ItemStack source,Func<ItemStack,ItemStack,ItemStack,bool> commit){var replacement=new ItemStack(source.itemValue.Clone(),1);replacement.itemValue.Metadata="partial";bool ok=commit(source.Clone(),replacement,source.count>1?new ItemStack(source.itemValue.Clone(),source.count-1):null);if(ok)Effects++;return new RebirthConsumeResult {Success=ok};}}
static class Log {public static void Warning(string x){}}
static class Subject {public static RebirthConsumeResult Last;static bool CanUseFromManagement(int t){return true;}static void SendConsumptionResult(EntityPlayer p,RebirthConsumeResult r){Last=r;}
// PRODUCTION_METHOD
public static void Use(EntityPlayer p,EntityDrone d,int slot,int type){UseDroneItem(p,d,slot,type);}}
class Check {static void Assert(bool b,string m){if(!b)throw new Exception(m);}static ItemStack Make(int count){return new ItemStack(new ItemValue {type=1},count);}static void Main(){var p=new EntityPlayer();var d=new EntityDrone();d.bag.Items=new[]{Make(2),ItemStack.Empty.Clone()};Subject.Use(p,d,0,1);Assert(Subject.Last.Success&&d.bag.Items[0].count==1&&d.bag.Items[0].itemValue.Metadata=="partial"&&d.bag.Items[1].count==1&&d.Syncs==1&&ItemAction.InstantCalls==0,"source-aware path failed");d.bag.Items=new[]{Make(2)};Subject.Use(p,d,0,1);Assert(!Subject.Last.Success&&d.bag.Items[0].count==2&&d.Syncs==1&&RebirthMetabolismService.Effects==1,"full storage had effects");d.bag.Items=new[]{Make(1)};d.belongsPlayerId=2;Subject.Use(p,d,0,1);Assert(!Subject.Last.Success&&d.Syncs==1,"changed owner accepted");d.belongsPlayerId=1;d.Dead=true;Subject.Use(p,d,0,1);Assert(!Subject.Last.Success&&d.Syncs==1,"dead drone accepted");d.Dead=false;Subject.Use(p,d,-1,1);Subject.Use(p,d,99,1);Subject.Use(p,d,0,2);Assert(d.Syncs==1&&d.bag.Items[0].count==1,"invalid request changed source");Console.WriteLine("PASS: actual drone method routes selected source, retains partial/siblings, syncs once, rejects full/changed-owner/dead/invalid sources and bypasses native instant food use.");}}
