$ErrorActionPreference='Stop'
$root=Split-Path (Split-Path $PSScriptRoot -Parent) -Parent
function Assert($v,$r){if(!$v){throw $r}}
[xml]$native=Get-Content (Join-Path $root '../../Data/Config/blocks.xml') -Raw
[xml]$patch=Get-Content (Join-Path $root 'Config/_Rebirth/industrial_power_blocks.xml') -Raw
[xml]$recipes=Get-Content (Join-Path $root 'Config/_Rebirth/industrial_power_recipes.xml') -Raw
[xml]$items=Get-Content (Join-Path $root '../../Data/Config/items.xml') -Raw
[xml]$caps=Get-Content (Join-Path $root 'Config/_Survivor/capabilities.xml') -Raw
[xml]$knowledge=Get-Content (Join-Path $root 'Config/_Survivor/recipe_knowledge.xml') -Raw
$service=Get-Content (Join-Path $root 'Scripts/Survivor/Progression/RebirthInfrastructureWorkService.cs') -Raw
foreach($block in $patch.configs.append.block){$id=$block.name;$parent=$block.SelectSingleNode('property[@name="Extends"]').value;$base=$native.SelectSingleNode("/blocks/block[@name='$parent']");Assert ($null -ne $base) 'native parent';$merged=@{};foreach($p in $base.SelectNodes('property[@name]')){$merged[$p.name]=$p.value};foreach($p in $block.SelectNodes('property[@name]')){$merged[$p.name]=$p.value};Assert ($merged.Class -in @('Generator','BatteryBank')) 'native tile class';Assert ($merged.Model.StartsWith('@:')) 'installed native model';Assert ($null -ne $base.SelectSingleNode('property[@class="RepairItems"]')) 'native physical repair';Assert ($null -ne $base.SelectSingleNode('drop[@event="Destroy" and @count="0"]')) 'no free block destroy duplication';$r=$recipes.SelectSingleNode("/configs/append/recipe[@name='$id']");Assert ($r.craft_area -eq 'workbench' -and $r.ingredient.Count -eq 3) 'fabrication';foreach($i in $r.ingredient){Assert ($null -ne $items.SelectSingleNode("/items/item[@name='$($i.name)']")) 'ingredient'};Assert ($null -ne $caps.SelectSingleNode("//capability[@target_id='$id']/requires_all/knowledge[@id='recipe.$id']")) 'exact gate';Assert ($null -ne $knowledge.SelectSingleNode("//recipe[@name='$id' and @knowledge='recipe.$id']")) 'exact manual recipe mapping';if($parent -eq 'generatorbank'){Assert ($merged.OutputPerStack -eq '150' -and $merged.MaxFuel -eq '2000' -and $merged.OutputPerFuel -eq '11250' -and $merged.MaxPower -eq '12250') 'generator bounded ratio/unchanged efficiency'}else{Assert ($merged.OutputPerStack -eq '75' -and $merged.MaxPower -eq '600' -and $merged.InputPerTick -eq '10' -and $merged.OutputPerCharge -eq '90' -and $merged.ChargePerInput -eq '1') 'battery ratio/unchanged efficiency'}}
Assert ($service.Contains('n.Contains("generator")') -and $service.Contains('n.Contains("batterybank")')) 'variant service class route';foreach($id in @('rebirthElectricalFuse','rebirthElectricalWiringHarness','rebirthElectricalTerminalBlock')){Assert ($service.Contains('ItemClass.GetItem("'+$id+'"')) 'existing service component preserved'}
[xml]$rootBlocks=Get-Content (Join-Path $root 'Config/blocks.xml') -Raw;Assert ($null -ne $rootBlocks.SelectSingleNode('/configs/conditional/if[@cond="character_progression(''Rebirth'')"]/include[@filename="_Rebirth/industrial_power_blocks.xml"]')) 'mode scope'
'PASS industrial power XML inheritance/gate assertions: native class/model/repair/drop, fixed ratios, unchanged fuel/charge efficiency, ingredients/exact knowledge, service classification and REBIRTH scope. Native placement/power/UI/save not exercised.'