#requires -Version 7.0
$ErrorActionPreference='Stop'
$taskRoot=Split-Path -Parent (Split-Path -Parent $PSScriptRoot)
$source=[IO.File]::ReadAllText((Join-Path $taskRoot 'Scripts/Crafting/UI/RebirthStationNativeQueueSnapshot.cs'))
$doubles=@"
public class FixtureWriter:BinaryWriter{public FixtureWriter():base(new MemoryStream()){}public void SetBaseStream(Stream s){OutStream=s;}protected override void Dispose(bool d){Flush();}}public class FixturePool{public FixtureWriter AllocSync(bool b){return new FixtureWriter();}}public static class MemoryPools{public static FixturePool poolBinaryWriter=new FixturePool();}public class Recipe{public int craftingToolType,craftingTier,unlockExpGain;public bool UseIngredientModifier,wildcardForgeCategory,wildcardCampfireCategory,materialBasedRecipe,IsLearnable,IsTrackable,isQuest,isChallenge,IsTracked;public string tooltip;public object tags="tag";}public class RecipeQueueItem{public Recipe Recipe;public short Multiplier;public float CraftingTimeLeft,OneItemCraftTime=-1;public ushort AmountToRepair;public byte[] Payload=new byte[0];public bool Fail;public void Write(BinaryWriter w){if(Fail)throw new Exception();w.Write(Multiplier);w.Write(CraftingTimeLeft);w.Write(OneItemCraftTime);w.Write(Payload.Length);w.Write(Payload);}}
public static class QueueSnapshotFixture{static int checks;static void Check(bool b,string n){checks++;if(!b)throw new Exception(n);}public static string Run(){
var q=new[]{new RecipeQueueItem(),new RecipeQueueItem{Multiplier=2,CraftingTimeLeft=8,Payload=new byte[]{1,2,3}}};RebirthStationNativeQueueSnapshot s;
Check(RebirthStationNativeQueueSnapshot.TryCapture(q,out s)&&s.Matches(q),"same native image");var digest=s.Digest();RebirthStationNativeQueueSnapshot duplicate;Check(RebirthStationNativeQueueSnapshot.TryCapture(q,out duplicate)&&duplicate.Digest()==digest&&digest.Length==64,"same detached queue fingerprints");q[1].Multiplier++;Check(RebirthStationNativeQueueSnapshot.TryCapture(q,out duplicate)&&duplicate.Digest()!=digest&&s.Digest()==digest,"changed queue fingerprint leaves old snapshot immutable");q[1].Multiplier--;q[1].CraftingTimeLeft=7;Check(!s.Matches(q),"changed timer");q[1].CraftingTimeLeft=8;
q[1].Payload[1]=9;Check(!s.Matches(q),"changed payload");q[1].Payload[1]=2;
q[0].AmountToRepair=1;Check(!s.Matches(q),"native omitted repair amount");q[0].AmountToRepair=0;
Check(s.Matches(q),"snapshot remains immutable");q[1].Fail=true;Check(!s.Matches(q),"writer failure");q[1].Fail=false;
q[0]=null;Check(!RebirthStationNativeQueueSnapshot.TryCapture(q,out s)&&s==null,"null entry");q[0]=new RecipeQueueItem{CraftingTimeLeft=float.NaN};Check(!RebirthStationNativeQueueSnapshot.TryCapture(q,out s),"nonfinite timer");
q[0]=new RecipeQueueItem{Payload=new byte[1024*1024]};Check(!RebirthStationNativeQueueSnapshot.TryCapture(q,out s),"bounded writer");
Check(!RebirthStationNativeQueueSnapshot.TryCapture(new RecipeQueueItem[256],out s),"native count bound");
q=new[]{new RecipeQueueItem{Recipe=new Recipe{craftingTier=4,craftingToolType=7,tooltip="hint"}}};Check(RebirthStationNativeQueueSnapshot.TryCapture(q,out s),"live recipe extras captured");q[0].Recipe.craftingTier=5;Check(!s.Matches(q),"native omitted tier change");q[0].Recipe.craftingTier=4;q[0].Recipe.craftingToolType=8;Check(!s.Matches(q),"native omitted tool change");q[0].Recipe.craftingToolType=7;q[0].Recipe.tags="changed";Check(!s.Matches(q),"native omitted tags change");
q=new[]{new RecipeQueueItem{Multiplier=1,Payload=new byte[]{1,2}}};Check(RebirthStationNativeQueueSnapshot.TryCapture(q,out s),"serialized queue expected snapshot");byte[] wire;using(var stream=new MemoryStream())using(var writer=new BinaryWriter(stream)){writer.Write((byte)q.Length);foreach(var e in q)e.Write(writer);writer.Flush();wire=stream.ToArray();}Check(s.MatchesSerializedQueue(wire),"native-only bytes match without observation extras");wire[wire.Length-1]++;Check(!s.MatchesSerializedQueue(wire),"changed serialized payload refused");wire[wire.Length-1]--;Check(!s.MatchesSerializedQueue(wire.Concat(new byte[]{0}).ToArray()),"trailing bytes refused");Check(!s.MatchesSerializedQueue(null)&&!s.MatchesSerializedQueue(new byte[0]),"missing serialized queue refused");
return "PASS "+checks+" actual queue snapshot checks with explicit native writer doubles; not native serialization qualification";}}
"@
Add-Type -TypeDefinition ("using System.Linq;"+$source+$doubles)
[QueueSnapshotFixture]::Run()