#requires -Version 7.0
$ErrorActionPreference='Stop'
$root=Split-Path -Parent (Split-Path -Parent $PSScriptRoot)
$source=[IO.File]::ReadAllText((Join-Path $root 'Scripts/Crafting/UI/RebirthStationCancellationSession.cs'))
$fixture=@"
public struct Vector3i{}public class World{public object Primary;public object GetPrimaryPlayer(){return Primary;}}public class EntityPlayerLocal{public int entityId=42;public World world=new World();}public class RebirthStationCancellationObservation:IDisposable{public static int Disposals;public void Dispose(){Disposals++;}}public static class RebirthStationCancellationRequest{public static int Calls;public static bool Allowed=true;public static bool TryRequest(EntityPlayerLocal p,Vector3i pos,string c,Guid j,out RebirthStationCancellationObservation o){Calls++;o=Allowed?new RebirthStationCancellationObservation():null;return Allowed;}}public static class RebirthStationCancellationAttemptService{public static bool Published=false;public static int Calls;public static bool TryConfirmPublication(EntityPlayerLocal p,Vector3i pos,string c,Guid j,string root,out object o){Calls++;o=null;return Published;}}public static class RebirthStationRefundPreparationService{public static int Begins,Applies,Confirms;public static bool Begin=true,Apply=true,Saved=false;public class ApplicationPermit{public bool TryApply(){Applies++;return Apply;}public bool TryConfirmSaved(){Confirms++;return Saved;}}public static bool TryBeginApplication(EntityPlayerLocal p,Vector3i pos,string c,Guid j,Guid d,string root,out ApplicationPermit permit){Begins++;permit=Begin?new ApplicationPermit():null;return Begin;}}public static class RebirthStationRefundArchiveService{public static bool Archived=false;public static int Calls;public static bool TryArchive(EntityPlayerLocal p,Vector3i pos,string c,Guid j,Guid d){Calls++;return Archived;}}
public static class Fixture{static int n;static void Check(bool b){n++;if(!b)throw new Exception("session "+n);}public static string Run(){var p=new EntityPlayerLocal();p.world.Primary=p;var job=Guid.NewGuid();RebirthStationCancellationSession s;Check(RebirthStationCancellationSession.TryBegin(p,new Vector3i(),"creation",job,out s));Check(!s.Advance("save")&&RebirthStationRefundPreparationService.Begins==0);RebirthStationCancellationAttemptService.Published=true;RebirthStationRefundPreparationService.Begin=false;Check(!s.Advance("save")&&RebirthStationRefundPreparationService.Applies==0);RebirthStationRefundPreparationService.Begin=true;Check(!s.Advance("save")&&RebirthStationRefundPreparationService.Applies==1);Check(!s.Advance("save")&&RebirthStationRefundPreparationService.Applies==1&&RebirthStationRefundPreparationService.Begins==2);RebirthStationRefundPreparationService.Saved=true;Check(!s.Advance("save")&&RebirthStationRefundArchiveService.Calls==1);int publicationCalls=RebirthStationCancellationAttemptService.Calls,confirmCalls=RebirthStationRefundPreparationService.Confirms;RebirthStationCancellationAttemptService.Published=false;RebirthStationRefundPreparationService.Saved=false;Check(!s.Advance("save")&&RebirthStationCancellationAttemptService.Calls==publicationCalls&&RebirthStationRefundPreparationService.Confirms==confirmCalls);RebirthStationRefundArchiveService.Archived=true;Check(s.Advance("save")&&s.IsCompleted&&RebirthStationCancellationObservation.Disposals==1);Check(s.Advance("save")&&RebirthStationRefundPreparationService.Applies==1&&RebirthStationCancellationRequest.Calls==1);RebirthStationCancellationAttemptService.Published=true;RebirthStationRefundArchiveService.Archived=false;RebirthStationRefundPreparationService.Apply=false;Check(RebirthStationCancellationSession.TryBegin(p,new Vector3i(),"creation",job,out s));Check(!s.Advance("save")&&RebirthStationRefundPreparationService.Applies==2);Check(!s.Advance("save")&&RebirthStationRefundPreparationService.Applies==2);s.Dispose();Check(!s.Advance("save"));RebirthStationRefundPreparationService.Apply=true;Check(RebirthStationCancellationSession.TryBegin(p,new Vector3i(),"creation",job,out s));p.entityId=99;Check(!s.Advance("save")&&RebirthStationRefundPreparationService.Applies==2);p.entityId=42;Check(!s.Advance("save"));RebirthStationCancellationRequest.Allowed=false;Check(!RebirthStationCancellationSession.TryBegin(p,new Vector3i(),"creation",job,out s)&&s==null);return "PASS "+n+" actual original cancellation session with native/service/permit doubles; no native async proof";}}
"@
Add-Type -TypeDefinition ($source+$fixture)
[Fixture]::Run()