using System;
class IntValue {public int Value=5;}
class ItemClass {public IntValue Stacknumber=new IntValue();}
class ItemValue {public int type;public string Metadata="full";public ItemClass ItemClass=new ItemClass();public ItemValue Clone(){return (ItemValue)MemberwiseClone();}public bool Equals(ItemValue b){return b!=null&&type==b.type&&Metadata==b.Metadata;}}
class ItemStack {public ItemValue itemValue;public int count;public static ItemStack Empty=new ItemStack(new ItemValue(),0);public ItemStack(ItemValue v,int c){itemValue=v;count=c;}public bool IsEmpty(){return count<=0||itemValue==null||itemValue.type==0;}public ItemStack Clone(){return new ItemStack(itemValue.Clone(),count);}public bool CanStackPartlyWith(ItemStack other,out int amount){amount=itemValue.Equals(other.itemValue)?Math.Min(other.count,Math.Max(0,itemValue.ItemClass.Stacknumber.Value-count)):0;return amount>0;}}
class PackedBoolArray {bool[] values;public PackedBoolArray(int n){values=new bool[n];}public int Length{get{return values.Length;}}public bool this[int i]{get{return values[i];}set{values[i]=value;}}}
class Check {static void Assert(bool b,string m){if(!b)throw new Exception(m);}static ItemStack Make(int type,int count,string meta="full"){return new ItemStack(new ItemValue {type=type,Metadata=meta},count);}static void Main(){var observed=new[]{Make(1,3),ItemStack.Empty.Clone()};var expected=observed[0].Clone();var replacement=Make(1,1,"partial");var siblings=Make(1,2);ItemStack[] plan;
 Assert(RebirthCompanionConsumptionSlots.TryPlan(observed,null,0,expected,replacement,siblings,out plan)&&plan[0].itemValue.Metadata=="partial"&&plan[1].count==2,"partial split failed");Assert(observed[0].count==3&&observed[1].IsEmpty()&&siblings.count==2,"planning mutated input");plan[0].itemValue.Metadata="edit";Assert(replacement.itemValue.Metadata=="partial","replacement alias");
 var locks=new PackedBoolArray(2);locks[1]=true;Assert(!RebirthCompanionConsumptionSlots.TryPlan(observed,locks,0,expected,replacement,siblings,out plan)&&plan==null&&observed[0].count==3,"locked empty accepted or partial write");
 observed[1]=Make(1,3);Assert(RebirthCompanionConsumptionSlots.TryPlan(observed,locks,0,expected,replacement,siblings,out plan)&&plan[1].count==5,"locked existing stack cannot top up");
 observed[1]=Make(2,5);Assert(!RebirthCompanionConsumptionSlots.TryPlan(observed,null,0,expected,replacement,siblings,out plan)&&plan==null,"overflow discarded");
 Assert(!RebirthCompanionConsumptionSlots.TryPlan(observed,null,0,Make(1,2),replacement,null,out plan),"stale count accepted");Assert(!RebirthCompanionConsumptionSlots.TryPlan(observed,null,0,Make(1,3,"different"),replacement,null,out plan),"stale metadata accepted");
 locks[0]=true;Assert(RebirthCompanionConsumptionSlots.TryPlan(observed,locks,0,expected,ItemStack.Empty,siblings,out plan)&&plan[0].count==2,"intentional used source siblings lost");
 Assert(RebirthCompanionConsumptionSlots.TryPlan(observed,null,0,expected,Make(1,2),null,out plan)&&plan[0].count==2&&plan[1].count==5,"food decrement plan");Console.WriteLine("PASS: split partial drink, source immutability, exact metadata, locked destination, stack top-up, overflow rejection, stale source and food plan.");}}
