using System;using System.Collections.Generic;using System.Linq;using System.Xml.Linq;
// Actual dispatcher save method; world, repository/file witness, identity and registration adapters doubled.
class World{public EntityPlayer Player;public bool IsRemote(){return false;}public object GetEntity(int id){return Player;}}
class EntityPlayer{public int entityId=1;public World world;public bool IsDead(){return false;}}
class GameManager{public static GameManager Instance=new GameManager();public World World;}
class Origin{public string CreationId;}
class Progression{public Dictionary<string,RebirthStationGridAdmission> StationPreparations=new Dictionary<string,RebirthStationGridAdmission>();}
class Record{public bool IsComplete=true;public Origin Origin=new Origin();public Progression Progression=new Progression();public string StablePlayerKey="owner",StablePlayerId="identity";}
class Identity{public string StorageKey="owner",CanonicalId="identity";}
class RebirthStationGridAdmission{public string JobId="job",CreationId,Payload="original";public RebirthStationGridAdmission Clone(){return new RebirthStationGridAdmission{JobId=JobId,CreationId=CreationId,Payload=Payload};}public XElement Write(){return new XElement("admission",new XAttribute("payload",Payload));}public bool SharesStation(RebirthStationGridAdmission other){return true;}public static bool TryNormalizeCreation(string value,out string result){result=value;return !string.IsNullOrEmpty(value);}}
static class RebirthSurvivorMode{public static bool IsEnabledForCurrentWorld(){return true;}}
static class RebirthSurvivorRequestScope{public static bool Matches(string a,string b){return !string.IsNullOrEmpty(a)&&a==b;}}
static class RebirthWorldCharacterService{public static Record Record;public static bool Flush=true;public static Action SaveHook;public static int Saves;public static bool TryGet(EntityPlayer p,out Record record){record=Record;return record!=null;}public static string LiveCanonical="identity";public static bool TryGetIdentity(EntityPlayer p,out Identity identity){identity=new Identity{CanonicalId=LiveCanonical};return true;}public static void MarkDirty(Record record,string reason){}public static bool FlushPlayer(EntityPlayer p,string reason){Saves++;SaveHook?.Invoke();return Flush;}}
static class RebirthWorldCharacterRepository{public static bool IsServerAuthority=true,Witness=true,Exclusive=true;public static bool IsCurrentCachedRecord(Record r){return ReferenceEquals(r,RebirthWorldCharacterService.Record);}public static bool HasExclusiveStationPreparation(Record r,RebirthStationGridAdmission a){return Exclusive;}public static bool HasSavedStationPreparation(Identity id,RebirthStationGridAdmission a){return Witness;}}
static class RebirthStationPreparationPersistence{public const int MaximumRecords=64;
// REGISTRATION
}
class Checks{static int authorityThreadId=System.Threading.Thread.CurrentThread.ManagedThreadId;static World authorityWorld;static bool IsCurrentAuthorityThread(World w){return ReferenceEquals(w,authorityWorld)&&ReferenceEquals(w,GameManager.Instance.World);}
// SOURCE
static void A(bool b,string msg){if(!b)throw new Exception(msg);}static void Main(){var player=new EntityPlayer();var world=new World{Player=player};player.world=world;authorityWorld=world;GameManager.Instance.World=world;var record=new Record{Origin=new Origin{CreationId="creation"}};RebirthWorldCharacterService.Record=record;var admission=new RebirthStationGridAdmission{CreationId="creation"};
A(TrySavePreparation(player,admission),"current final-file witness accepts preparation");RebirthWorldCharacterRepository.Witness=false;A(!TrySavePreparation(player,admission),"save return without final witness refused");RebirthWorldCharacterRepository.Witness=true;RebirthWorldCharacterService.Flush=false;A(!TrySavePreparation(player,admission),"failed save refused");RebirthWorldCharacterService.Flush=true;
RebirthWorldCharacterService.SaveHook=()=>GameManager.Instance.World=new World();A(!TrySavePreparation(player,admission),"world replaced during save refused");GameManager.Instance.World=world;RebirthWorldCharacterService.SaveHook=()=>record.Origin.CreationId="replacement";A(!TrySavePreparation(player,admission),"creation replaced during save refused");record.Origin.CreationId="creation";RebirthWorldCharacterService.SaveHook=()=>{throw new Exception("save failure");};A(!TrySavePreparation(player,admission),"save exception contained");RebirthWorldCharacterService.SaveHook=null;record.StablePlayerId="spoofed";int saves=RebirthWorldCharacterService.Saves;A(!TrySavePreparation(player,admission)&&saves==RebirthWorldCharacterService.Saves,"mismatched stable identity refused before save");record.StablePlayerId="identity";RebirthWorldCharacterService.Flush=false;A(!TrySavePreparation(player,admission)&&record.Progression.StationPreparations.ContainsKey(admission.JobId),"failed save retains actual registered intent");RebirthWorldCharacterService.Flush=true;RebirthWorldCharacterRepository.Witness=false;A(!TrySavePreparation(player,admission),"exact retained retry still requires final witness");RebirthWorldCharacterRepository.Witness=true;A(TrySavePreparation(player,admission)&&record.Progression.StationPreparations.Count==1,"successful exact retry preserves one intent");var changed=admission.Clone();changed.Payload="tampered";saves=RebirthWorldCharacterService.Saves;A(!TrySavePreparation(player,changed)&&saves==RebirthWorldCharacterService.Saves,"changed retry denied before persistence callback");
RebirthWorldCharacterService.SaveHook=()=>{var nextWorld=new World{Player=player};player.world=nextWorld;authorityWorld=nextWorld;GameManager.Instance.World=nextWorld;};A(!TrySavePreparation(player,admission),"world/entity migration cannot rebind original save admission");player.world=world;authorityWorld=world;GameManager.Instance.World=world;
RebirthWorldCharacterService.SaveHook=()=>RebirthWorldCharacterService.LiveCanonical="replacement-identity";A(!TrySavePreparation(player,admission),"live identity remapping during save denied");RebirthWorldCharacterService.LiveCanonical="identity";RebirthWorldCharacterService.SaveHook=null;
Console.WriteLine("PASS2 original binding checks: migrated owner world and identity remapping during checkpoint refused.");Console.WriteLine("PASS4 actual registration/dispatcher retry checks: failed save retained intent, repeated witness refusal, exact durable retry and changed admission rejection; native codec/repository adapters doubled.");Console.WriteLine("PASS7 actual dispatcher preparation checks: current saved witness, absent witness, failed/throwing saves, replaced world/creation and stable identity mismatch; native persistence adapters doubled.");}}