#requires -Version 7.0
$ErrorActionPreference='Stop'
$root=Split-Path -Parent (Split-Path -Parent $PSScriptRoot)
$source=[IO.File]::ReadAllText((Join-Path $root 'Scripts/Crafting/UI/RebirthStationRefundPlayerFileWitness.cs'))
$fixture=@"
public class RebirthStablePlayerIdentity{public string CanonicalId="owner";}public class ItemStack{public int Count;}public class RebirthStationRefundBackpackPlan{public bool MatchesAfter(ItemStack[] s){return s!=null&&s.Length==1&&s[0].Count==10;}}public static class GameIO{public static string GetPlayerDataDir(){return System.IO.Path.GetTempPath();}}public static class SdFile{public static byte[] Data;public static bool Present=true;public static int Opens;public static bool Exists(string p){return Present;}public static System.IO.Stream OpenRead(string p){if(p.EndsWith(".bak"))throw new Exception("backup forbidden");Opens++;return new MemoryStream(Data,false);}}public class Reader:System.IO.BinaryReader{private System.IO.BinaryReader inner;public Reader():base(new MemoryStream()){}public void SetBaseStream(System.IO.Stream s){inner=new System.IO.BinaryReader(s,System.Text.Encoding.UTF8,true);}public new char ReadChar(){return inner.ReadChar();}public new byte ReadByte(){return inner.ReadByte();}public new int ReadInt32(){return inner.ReadInt32();}public new byte[] ReadBytes(int n){return inner.ReadBytes(n);}}public class Pool{public Reader AllocSync(bool b){return new Reader();}}public static class MemoryPools{public static Pool poolBinaryReader=new Pool();}public enum StreamModeRead{Persistency}public class PlayerDataFile{public static string EXT="ttp";public const int cFileVersion=62;public MemoryStream buffData,bagData;public void Read(Reader r,uint v,StreamModeRead m){int b=r.ReadInt32();buffData=new MemoryStream(r.ReadBytes(b));int a=r.ReadInt32();bagData=new MemoryStream(r.ReadBytes(a));}}public class XUiC_ItemStack{public enum StackLocationTypes{Backpack}}public class Grid{public ItemStack[] items;}public class Bag{public const byte Version=2;public Grid ItemGrid;public static Bag Read(Reader r,XUiC_ItemStack.StackLocationTypes l,StreamModeRead m,object h){r.ReadByte();return new Bag{ItemGrid=new Grid{items=new[]{new ItemStack{Count=r.ReadInt32()}}}};}}public static class RebirthStationRefundReceiptReader{public static bool Contains(byte[] b,Guid id,bool applied){return b.Length==1&&b[0]==1;}}
public static class Fixture{static int n;static void Check(bool b){n++;if(!b)throw new Exception("file witness "+n);}static byte[] File(int count=10,byte marker=1,byte version=62,byte bagVersion=2,bool trailing=false,bool bagTrailing=false){using(var s=new MemoryStream()){using(var w=new BinaryWriter(s,System.Text.Encoding.UTF8,true)){w.Write(new[]{'t','t','p','\0'});w.Write(version);w.Write(1);w.Write(marker);w.Write(bagTrailing?6:5);w.Write(bagVersion);w.Write(count);if(bagTrailing)w.Write((byte)0);if(trailing)w.Write((byte)0);}return s.ToArray();}}public static string Run(){var owner=new RebirthStablePlayerIdentity();var id=Guid.NewGuid();var plan=new RebirthStationRefundBackpackPlan();SdFile.Data=File();Check(RebirthStationRefundPlayerFileWitness.HasSaved(owner,id,plan));Check(!RebirthStationRefundPlayerFileWitness.HasSaved(null,id,plan));Check(!RebirthStationRefundPlayerFileWitness.HasSaved(owner,Guid.Empty,plan));Check(!RebirthStationRefundPlayerFileWitness.HasSaved(owner,id,null));owner.CanonicalId="../escape";int opens=SdFile.Opens;Check(!RebirthStationRefundPlayerFileWitness.HasSaved(owner,id,plan)&&opens==SdFile.Opens);owner.CanonicalId="owner";SdFile.Present=false;Check(!RebirthStationRefundPlayerFileWitness.HasSaved(owner,id,plan)&&opens==SdFile.Opens);SdFile.Present=true;SdFile.Data=File(count:9);Check(!RebirthStationRefundPlayerFileWitness.HasSaved(owner,id,plan));SdFile.Data=File(marker:2);Check(!RebirthStationRefundPlayerFileWitness.HasSaved(owner,id,plan));SdFile.Data=File(version:61);Check(!RebirthStationRefundPlayerFileWitness.HasSaved(owner,id,plan));SdFile.Data=File(bagVersion:1);Check(!RebirthStationRefundPlayerFileWitness.HasSaved(owner,id,plan));SdFile.Data=File(trailing:true);Check(!RebirthStationRefundPlayerFileWitness.HasSaved(owner,id,plan));SdFile.Data=File(bagTrailing:true);Check(!RebirthStationRefundPlayerFileWitness.HasSaved(owner,id,plan));SdFile.Data=new byte[]{0};Check(!RebirthStationRefundPlayerFileWitness.HasSaved(owner,id,plan));SdFile.Data=File();SdFile.Data[0]=0;Check(!RebirthStationRefundPlayerFileWitness.HasSaved(owner,id,plan));SdFile.Data=new byte[16*1024*1024+1];Check(!RebirthStationRefundPlayerFileWitness.HasSaved(owner,id,plan));return "PASS "+n+" actual final-file witness with file/native decoder/plan/receipt doubles; no native disk durability proof";}}
"@
Add-Type -TypeDefinition ($source+$fixture)
[Fixture]::Run()