using System;using System.IO;using System.Linq;using System.Reflection;
class RecoveryBlobCheck {
 static string phase="initial";static int checks;static void Check(bool value,string label){if(!value)throw new Exception(label);checks++;}
 static int Main(string[] args){try{
 string managed=args[1];AppDomain.CurrentDomain.AssemblyResolve+=(s,e)=>{string file=Path.Combine(managed,new AssemblyName(e.Name).Name+".dll");return File.Exists(file)?Assembly.LoadFrom(file):null;};
 var assembly=Assembly.LoadFrom(Path.Combine(managed,"Assembly-CSharp.dll"));var utils=assembly.GetType("StreamUtils",true);var writerType=assembly.GetType("PooledBinaryWriter",true);var readerType=assembly.GetType("PooledBinaryReader",true);
 foreach(int length in new[]{0,65536,3*1024*1024}){
 var bytes=new byte[length];for(int i=0;i<length;i++)bytes[i]=(byte)(i*17+3);
 var source=new MemoryStream(bytes);source.Position=source.Length;
 var wire=new MemoryStream();var writer=Activator.CreateInstance(writerType);writerType.GetMethod("SetBaseStream").Invoke(writer,new object[]{wire});
 utils.GetMethod("WriteBlob").Invoke(null,new object[]{writer,source});((BinaryWriter)writer).Write((ushort)7);((BinaryWriter)writer).Write(new byte[]{1,2,3,4,5,6,7});
 Check(wire.Length==4L+length+2+7,"full native int-length blob framing "+length);
 wire.Position=0;var reader=Activator.CreateInstance(readerType);readerType.GetMethod("SetBaseStream").Invoke(reader,new object[]{wire});var restored=(MemoryStream)utils.GetMethod("ReadBlob").Invoke(null,new object[]{reader});
 Check(restored.ToArray().SequenceEqual(bytes),"native full payload roundtrip "+length);Check(((BinaryReader)reader).ReadUInt16()==7&&((BinaryReader)reader).ReadBytes(7).SequenceEqual(new byte[]{1,2,3,4,5,6,7})&&wire.Position==wire.Length,"following compact entity payload remains aligned "+length);
 }
 var ecdType=assembly.GetType("EntityCreationData",true);var original=Activator.CreateInstance(ecdType);var nativeBytes=new byte[70000];for(int i=0;i<nativeBytes.Length;i++)nativeBytes[i]=(byte)i;var compactBytes=new byte[]{1,3,5,7,9};
 ecdType.GetField("entityClass").SetValue(original,123456789);ecdType.GetField("id").SetValue(original,501);ecdType.GetField("bagData").SetValue(original,new MemoryStream(nativeBytes));ecdType.GetField("entityData").SetValue(original,new MemoryStream(compactBytes));ecdType.GetField("spawnById").SetValue(original,77);
 var bodyField=ecdType.GetField("bodyDamage");bodyField.SetValue(original,Activator.CreateInstance(bodyField.FieldType));
 var writeModeType=assembly.GetType("StreamModeWrite",true);var readModeType=assembly.GetType("StreamModeRead",true);
 var ecdWire=new MemoryStream();var ecdWriter=Activator.CreateInstance(writerType);writerType.GetMethod("SetBaseStream").Invoke(ecdWriter,new object[]{ecdWire});ecdType.GetMethod("write").Invoke(original,new object[]{ecdWriter,Enum.Parse(writeModeType,"Persistency")});
 ecdWire.Position=0;var ecdReader=Activator.CreateInstance(readerType);readerType.GetMethod("SetBaseStream").Invoke(ecdReader,new object[]{ecdWire});var restoredEcd=Activator.CreateInstance(ecdType);ecdType.GetMethod("read").Invoke(restoredEcd,new object[]{ecdReader,Enum.Parse(readModeType,"Persistency")});
 Check(((MemoryStream)ecdType.GetField("bagData").GetValue(restoredEcd)).ToArray().SequenceEqual(nativeBytes),"installed EntityCreationData preserves bag blob above ushort");Check(((MemoryStream)ecdType.GetField("entityData").GetValue(restoredEcd)).ToArray().SequenceEqual(compactBytes)&&ecdWire.Position==ecdWire.Length,"installed full entity record remains aligned");Check((int)ecdType.GetField("spawnById").GetValue(restoredEcd)==-1,"installed Persistency omits native spawn owner field");
 var bagType=assembly.GetType("Bag",true);var stackType=assembly.GetType("ItemStack",true);var itemType=assembly.GetType("ItemValue",true);var vectorType=assembly.GetType("Vector2i",true);var locationType=assembly.GetType("XUiC_ItemStack+StackLocationTypes",true);
 phase="item class setup";var nativeClassType=assembly.GetType("ItemClass",true);var nativeClasses=Array.CreateInstance(nativeClassType,2);nativeClasses.SetValue(Activator.CreateInstance(nativeClassType),1);nativeClassType.GetField("list",BindingFlags.Public|BindingFlags.NonPublic|BindingFlags.Static).SetValue(null,nativeClasses);
 phase="item setup";var item=Activator.CreateInstance(itemType);itemType.GetProperty("type").SetValue(item,1,null);string metadata=new string('m',70000);itemType.GetMethod("SetMetadata",new[]{typeof(string),typeof(string)}).Invoke(item,new object[]{"recoveryFixture",metadata});
 phase="bag setup";var stack=Activator.CreateInstance(stackType,new object[]{item,17});var stacks=Array.CreateInstance(stackType,1);stacks.SetValue(stack,0);var size=Activator.CreateInstance(vectorType,new object[]{1,1});var location=Enum.Parse(locationType,"LootContainer");var bag=Activator.CreateInstance(bagType,new object[]{size,location,null});bagType.GetMethod("SetSlots").Invoke(bag,new object[]{stacks,true});
 phase="bag write";var bagWire=new MemoryStream();var bagWriter=Activator.CreateInstance(writerType);writerType.GetMethod("SetBaseStream").Invoke(bagWriter,new object[]{bagWire});bagType.GetMethod("Write").Invoke(bag,new object[]{bagWriter,Enum.Parse(writeModeType,"Persistency")});Check(bagWire.Length>65535,"actual native bag metadata exceeds ushort safely");
 phase="bag read";bagWire.Position=0;var bagReader=Activator.CreateInstance(readerType);readerType.GetMethod("SetBaseStream").Invoke(bagReader,new object[]{bagWire});var restoredBag=Activator.CreateInstance(bagType,new object[]{size,location,null});bagType.GetMethod("ReadInto").Invoke(restoredBag,new object[]{bagReader,Enum.Parse(readModeType,"Persistency")});phase="bag assertions";var grid=bagType.GetProperty("ItemGrid").GetValue(restoredBag,null);var restoredStack=((Array)grid.GetType().GetField("items",BindingFlags.Public|BindingFlags.NonPublic|BindingFlags.Instance).GetValue(grid)).GetValue(0);var restoredItem=stackType.GetProperty("itemValue").GetValue(restoredStack,null);object[] metadataArgs=new object[]{"recoveryFixture",null};var metadataGetter=itemType.GetMethod("TryGetMetadata",new[]{typeof(string),typeof(string).MakeByRefType()});
 Check((int)stackType.GetProperty("count").GetValue(restoredStack,null)==17&&(bool)metadataGetter.Invoke(restoredItem,metadataArgs)&&(string)metadataArgs[1]==metadata&&bagWire.Position==bagWire.Length,"actual native bag preserves exact count and large metadata");
 stackType.GetProperty("count").SetValue(stack,65536,null);var oversizedWire=new MemoryStream();var oversizedWriter=Activator.CreateInstance(writerType);writerType.GetMethod("SetBaseStream").Invoke(oversizedWriter,new object[]{oversizedWire});stackType.GetMethod("Write",new[]{writerType}).Invoke(stack,new[]{oversizedWriter});oversizedWire.Position=0;Check(new BinaryReader(oversizedWire).ReadUInt16()==65535,"installed native ItemStack silently caps count to ushort");
 var modAssembly=Assembly.LoadFrom(Path.Combine(args[0],"RebirthUtils.dll"));var boundedTextType=modAssembly.GetType("RebirthGearRecoveryStringWire",true);string nativeText="Recovery "+new string((char)0x03bb,4087);var textWire=new MemoryStream();var nativeTextWriter=Activator.CreateInstance(writerType);writerType.GetMethod("SetBaseStream").Invoke(nativeTextWriter,new object[]{textWire});((BinaryWriter)nativeTextWriter).Write(nativeText);textWire.Position=0;var nativeTextReader=Activator.CreateInstance(readerType);readerType.GetMethod("SetBaseStream").Invoke(nativeTextReader,new object[]{textWire});string restoredText=(string)boundedTextType.GetMethod("Read",BindingFlags.Static|BindingFlags.NonPublic).Invoke(null,new[]{nativeTextReader});Check(restoredText==nativeText&&textWire.Position==textWire.Length,"built bounded recovery reader accepts installed native Unicode framing");
 var recordType=modAssembly.GetType("RebirthRecoveryEntityRecord",true);object[] recordArgs=new object[]{ecdWire.ToArray(),0,123456789,null};Check((bool)recordType.GetMethod("TryRead").Invoke(null,recordArgs),"bounded reader accepts actual installed custom ECD wire");var framedRecord=recordArgs[3];Check((int)recordType.GetProperty("BagLength").GetValue(framedRecord,null)==70000&&(int)recordType.GetProperty("MetadataLength").GetValue(framedRecord,null)==compactBytes.Length&&(int)recordType.GetProperty("EndOffset").GetValue(framedRecord,null)==ecdWire.Length,"bounded reader native bag/metadata/end offsets match");
 var oversizedRecord=ecdWire.ToArray();int nativeBagOffset=(int)recordType.GetProperty("BagOffset").GetValue(framedRecord,null);Array.Copy(BitConverter.GetBytes(4*1024*1024+1),0,oversizedRecord,nativeBagOffset-4,4);object[] refusedRecord=new object[]{oversizedRecord,0,123456789,null};Check(!(bool)recordType.GetMethod("TryRead").Invoke(null,refusedRecord)&&refusedRecord[3]==null,"oversized declared native bag refuses without copying bytes");
 var recoveryIdentityType=modAssembly.GetType("RebirthGearRecoveryIdentity",true);object[] identityArgs=new object[]{"owner",Guid.NewGuid().ToString("N"),Guid.NewGuid(),Guid.NewGuid(),3,null};Check((bool)recoveryIdentityType.GetMethod("TryCreate").Invoke(null,identityArgs),"built production recovery identity setup");var markerBytes=(byte[])recoveryIdentityType.GetMethod("Encode").Invoke(identityArgs[5],null);var metadataType=modAssembly.GetType("RebirthRecoveryEntityMetadata",true);
 foreach(bool pack in new[]{true,false}){var bodyWire=new MemoryStream();var bodyWriter=Activator.CreateInstance(writerType);writerType.GetMethod("SetBaseStream").Invoke(bodyWriter,new object[]{bodyWire});var binaryBody=(BinaryWriter)bodyWriter;binaryBody.Write((byte)1);binaryBody.Write(7);if(pack){binaryBody.Write(false);binaryBody.Write("cntDropBag");binaryBody.Write(nativeText);}else{binaryBody.Write(9);binaryBody.Write(7);}binaryBody.Write((ushort)markerBytes.Length);binaryBody.Write(markerBytes);bodyWire.Position=0;var bodyReader=Activator.CreateInstance(readerType);readerType.GetMethod("SetBaseStream").Invoke(bodyReader,new object[]{bodyWire});var decodedBody=metadataType.GetMethod("ReadBody",BindingFlags.Static|BindingFlags.NonPublic).Invoke(null,new object[]{bodyReader,pack});var decodedMarker=metadataType.GetProperty("Identity").GetValue(decodedBody,null);Check(((byte[])recoveryIdentityType.GetMethod("Encode").Invoke(decodedMarker,null)).SequenceEqual(markerBytes)&&bodyWire.Position==bodyWire.Length&&(pack?(string)metadataType.GetProperty("Name").GetValue(decodedBody,null)==nativeText:(int)metadataType.GetProperty("OwnerId").GetValue(decodedBody,null)==7),"built compact metadata decoder with installed native writer/reader "+pack);}
 var valueWire=new MemoryStream();var valueWriter=Activator.CreateInstance(writerType);writerType.GetMethod("SetBaseStream").Invoke(valueWriter,new object[]{valueWire});itemType.GetMethod("Write",new[]{writerType}).Invoke(item,new[]{valueWriter});string exactPayload=Convert.ToBase64String(valueWire.ToArray());Guid bagPublicationId=Guid.NewGuid();string pendingXml="<pendingGearTransfer version='1' transactionId='"+Guid.NewGuid().ToString("N")+"' creationId='"+Guid.NewGuid().ToString("N")+"' slot='backpack' revision='2'><gearPlan version='1' bagBefore='65' bagAfter='52' beltBefore='4' beltAfter='4'><gearBefore count='0' data=''/><gearAfter count='1' data='Ag=='/><changes><change bag='true' index='0'><before count='1' data='Ag=='/><after count='0' data=''/></change><change bag='true' index='52'><before count='17' data='"+exactPayload+"'/><after count='0' data=''/></change></changes><recovery><entry origin='0' index='52'><item count='17' data='"+exactPayload+"'/></entry></recovery></gearPlan><recoveryManifest version='1'><publication id='"+bagPublicationId.ToString("N")+"' kind='backpack'><entry index='0'/></publication></recoveryManifest></pendingGearTransfer>";
 var transferType=modAssembly.GetType("RebirthGearTransferState",true);object[] transferArgs=new object[]{System.Xml.Linq.XElement.Parse(pendingXml),null};Check((bool)transferType.GetMethod("TryRead").Invoke(null,transferArgs),"built conserved native-metadata recovery plan setup");
 ecdType.GetField("bagData").SetValue(original,new MemoryStream(bagWire.ToArray()));var actualBagEcdWire=new MemoryStream();var actualBagEcdWriter=Activator.CreateInstance(writerType);writerType.GetMethod("SetBaseStream").Invoke(actualBagEcdWriter,new object[]{actualBagEcdWire});ecdType.GetMethod("write").Invoke(original,new object[]{actualBagEcdWriter,Enum.Parse(writeModeType,"Persistency")});object[] actualBagRecordArgs=new object[]{actualBagEcdWire.ToArray(),0,123456789,null};Check((bool)recordType.GetMethod("TryRead").Invoke(null,actualBagRecordArgs),"bounded record framing locates actual native bag");var bagWitnessType=modAssembly.GetType("RebirthRecoveryBagPayload",true);Check((bool)bagWitnessType.GetMethod("Matches").Invoke(null,new object[]{actualBagEcdWire.ToArray(),actualBagRecordArgs[3],transferArgs[1],bagPublicationId}),"built exact bag witness matches installed large native metadata payload/count");
 phase="joined native publication evidence";
 var attemptedXml=System.Xml.Linq.XElement.Parse(pendingXml);attemptedXml.Add(new System.Xml.Linq.XElement("recoveryAttempts",new System.Xml.Linq.XAttribute("version",1),new System.Xml.Linq.XElement("attempt",new System.Xml.Linq.XAttribute("id",bagPublicationId.ToString("N")),new System.Xml.Linq.XAttribute("entity",501),new System.Xml.Linq.XAttribute("ownerEntity",7),new System.Xml.Linq.XAttribute("x",0),new System.Xml.Linq.XAttribute("y",0),new System.Xml.Linq.XAttribute("z",0),new System.Xml.Linq.XAttribute("yaw",0),new System.Xml.Linq.XAttribute("lifetime",3600),new System.Xml.Linq.XAttribute("worldTime",123))));
 object[] attemptedArgs=new object[]{attemptedXml,null};Check((bool)transferType.GetMethod("TryRead").Invoke(null,attemptedArgs),"built owner-bound native attempt reload");
 object[] joinedIdentityArgs=new object[]{"owner",(string)attemptedXml.Attribute("creationId"),Guid.Parse((string)attemptedXml.Attribute("transactionId")),bagPublicationId,0,null};Check((bool)recoveryIdentityType.GetMethod("TryCreate").Invoke(null,joinedIdentityArgs),"joined native publication marker");var joinedMarker=(byte[])recoveryIdentityType.GetMethod("Encode").Invoke(joinedIdentityArgs[5],null);
 byte staticSource=Convert.ToByte(Enum.Parse(assembly.GetType("EnumSpawnerSource",true),"StaticSpawner"));var joinedMetadata=new MemoryStream();var joinedWriter=Activator.CreateInstance(writerType);writerType.GetMethod("SetBaseStream").Invoke(joinedWriter,new object[]{joinedMetadata});var joinedBinary=(BinaryWriter)joinedWriter;joinedBinary.Write(staticSource);joinedBinary.Write((ulong)123);joinedBinary.Write((byte)1);joinedBinary.Write(7);joinedBinary.Write(false);joinedBinary.Write("");joinedBinary.Write("");joinedBinary.Write((ushort)joinedMarker.Length);joinedBinary.Write(joinedMarker);
 ecdType.GetField("entityData").SetValue(original,new MemoryStream(joinedMetadata.ToArray()));ecdType.GetField("lifetime").SetValue(original,float.MaxValue);
 var joinedWire=new MemoryStream();var joinedEcdWriter=Activator.CreateInstance(writerType);writerType.GetMethod("SetBaseStream").Invoke(joinedEcdWriter,new object[]{joinedWire});ecdType.GetMethod("write").Invoke(original,new object[]{joinedEcdWriter,Enum.Parse(writeModeType,"Persistency")});
 var evidenceType=modAssembly.GetType("RebirthRecoveryPublicationEvidence",true);object[] evidenceArgs=new object[]{joinedWire.ToArray(),0,attemptedArgs[1],bagPublicationId,"owner",7,123456789,123456790,staticSource,0};
 Check((bool)evidenceType.GetMethod("TryMatch").Invoke(null,evidenceArgs)&&(int)evidenceArgs[9]==joinedWire.Length,"joined built evidence accepts actual native ECD and large exact bag");
 evidenceArgs[5]=8;Check(!(bool)evidenceType.GetMethod("TryMatch").Invoke(null,evidenceArgs)&&(int)evidenceArgs[9]==0,"native joined evidence refuses reconnect owner substitution");evidenceArgs[5]=7;
 var changedJoined=joinedWire.ToArray();object[] joinedRecordArgs=new object[]{changedJoined,0,123456789,null};recordType.GetMethod("TryRead").Invoke(null,joinedRecordArgs);int joinedBagOffset=(int)recordType.GetProperty("BagOffset").GetValue(joinedRecordArgs[3],null);changedJoined[joinedBagOffset+20]^=1;evidenceArgs[0]=changedJoined;
 Check(!(bool)evidenceType.GetMethod("TryMatch").Invoke(null,evidenceArgs)&&(int)evidenceArgs[9]==0,"native marker cannot authorize altered actual ItemValue bytes");
 phase="native foreign entity framing";var foreignType=modAssembly.GetType("RebirthRecoveryForeignRecord",true);int[] foreignIds={100,101,102,103,104,105,106};Func<int,int> knownOrdinary=id=>id==1?0:-1;object[] foreignArgs=new object[]{joinedWire.ToArray(),0,foreignIds,32768,knownOrdinary,0};Check((bool)foreignType.GetMethod("TrySkip").Invoke(null,foreignArgs)&&(int)foreignArgs[5]==joinedWire.Length,"foreign scanner aligns actual ordinary native ECD blob");
 var entityClassType=assembly.GetType("EntityClass",true);string[] nativeSpecialFields={"itemClass","fallingBlockClass","fallingBlocksClass","fallingTreeClass","playerMaleClass","playerFemaleClass","junkDroneClass"};for(int k=0;k<7;k++)foreignIds[k]=(int)entityClassType.GetField(nativeSpecialFields[k]).GetValue(null);
 ecdType.GetField("id").SetValue(original,602);ecdType.GetField("entityClass").SetValue(original,foreignIds[0]);stackType.GetProperty("count").SetValue(stack,17,null);ecdType.GetField("itemStack").SetValue(original,stack);var itemRecordWire=new MemoryStream();var itemRecordWriter=Activator.CreateInstance(writerType);writerType.GetMethod("SetBaseStream").Invoke(itemRecordWriter,new object[]{itemRecordWire});ecdType.GetMethod("write").Invoke(original,new object[]{itemRecordWriter,Enum.Parse(writeModeType,"Persistency")});foreignArgs[0]=itemRecordWire.ToArray();Check((bool)foreignType.GetMethod("TrySkip").Invoke(null,foreignArgs)&&(int)foreignArgs[5]==itemRecordWire.Length,"foreign scanner aligns actual native item ECD with large metadata");
 foreignArgs[4]=new Func<int,int>(id=>-1);Check(!(bool)foreignType.GetMethod("TrySkip").Invoke(null,foreignArgs)&&(int)foreignArgs[5]==0,"native item traversal refuses unavailable class definition");
 phase="native declared entity list";var sectionType=modAssembly.GetType("RebirthRecoveryEntityEvidence",true);var nativeSection=itemRecordWire.ToArray().Concat(joinedWire.ToArray()).ToArray();object[] sectionArgs=new object[]{nativeSection,0,2,attemptedArgs[1],bagPublicationId,"owner",123456789,123456790,staticSource,foreignIds,32768,knownOrdinary,0};Check((bool)sectionType.GetMethod("TryMatch").Invoke(null,sectionArgs)&&(int)sectionArgs[12]==nativeSection.Length,"built whole entity list finds recovery after native item record");
 sectionArgs[0]=joinedWire.ToArray().Concat(itemRecordWire.ToArray().Take((int)itemRecordWire.Length-1)).ToArray();Check(!(bool)sectionType.GetMethod("TryMatch").Invoke(null,sectionArgs)&&(int)sectionArgs[12]==0,"malformed native suffix invalidates earlier recovery match");
 phase="native workstation queue framing";var queueType=assembly.GetType("RecipeQueueItem",true);var completionType=assembly.GetType("CraftCompleteData",true);var nativeQueue=Activator.CreateInstance(queueType);queueType.GetField("RepairItem").SetValue(nativeQueue,item);queueType.GetField("AmountToRepair").SetValue(nativeQueue,(ushort)12);queueType.GetField("Multiplier").SetValue(nativeQueue,(short)3);var nativeCompletion=Activator.CreateInstance(completionType);completionType.GetField("CraftedItemStack").SetValue(nativeCompletion,stack);completionType.GetField("RecipeName").SetValue(nativeCompletion,"nativeFixtureRecipe");
 var stationWire=new MemoryStream();var stationWriter=Activator.CreateInstance(writerType);writerType.GetMethod("SetBaseStream").Invoke(stationWriter,new object[]{stationWire});var stationBinary=(BinaryWriter)stationWriter;stationBinary.Write((ushort)19);stationBinary.Write(new byte[20]);stationBinary.Write((byte)50);stationBinary.Write(0L);for(int k=0;k<4;k++)stationBinary.Write((byte)0);stationBinary.Write((byte)1);queueType.GetMethod("Write").Invoke(nativeQueue,new[]{stationWriter});stationBinary.Write((short)1);completionType.GetMethod("Write").Invoke(nativeCompletion,new[]{stationWriter});stationBinary.Write(false);stationBinary.Write(0f);stationBinary.Write((byte)0);stationBinary.Write(false);stationBinary.Write((byte)0);
 var stationRecordType=modAssembly.GetType("RebirthRecoveryStationRecord",true);object[] stationArgs=new object[]{stationWire.ToArray(),0,32768,knownOrdinary,0};Check((bool)stationRecordType.GetMethod("TrySkip").Invoke(null,stationArgs)&&(int)stationArgs[4]==stationWire.Length,"built workstation cursor aligns actual native repair queue and completion with large metadata");stationArgs[3]=new Func<int,int>(id=>-1);Check(!(bool)stationRecordType.GetMethod("TrySkip").Invoke(null,stationArgs)&&(int)stationArgs[4]==0,"native workstation repair payload refuses unknown item class");
 Console.WriteLine("PASS "+checks+" installed native StreamUtils/PooledBinaryWriter/Reader and EntityCreationData checks. Synthetic native item type/metadata; actual Bag/ItemValue framing, no entity factory/game execution.");return 0;
 }catch(Exception e){Console.Error.WriteLine(phase+": "+e);return 1;}}
}