#requires -Version 7.0
$ErrorActionPreference='Stop'
$root=Split-Path -Parent (Split-Path -Parent $PSScriptRoot)
$source=[IO.File]::ReadAllText((Join-Path $root 'Scripts/Crafting/UI/RebirthStationCancellationRequest.cs'))
$fixture=@"
public struct Vector3i{}public class World{public object Primary;public object GetPrimaryPlayer(){return Primary;}}public class EntityPlayerLocal{public World world=new World();}public class RebirthStationCancellationObservation:IDisposable{public void Dispose(){}}public static class RebirthStationTerminalIntentService{public static bool Allowed=true;public static int Calls;public static bool TrySave(EntityPlayerLocal p,Vector3i pos,string c,Guid j,bool completion,out object i){Calls++;if(completion)throw new Exception();i=null;return Allowed;}}public static class RebirthStationCancellationAttemptService{public static bool Allowed=true,Apply=true,Throw=false;public static int Begins,Writes;public class Permit{public bool TryApply(out RebirthStationCancellationObservation o){Writes++;o=null;if(Throw)throw new Exception();if(!Apply)return false;o=new RebirthStationCancellationObservation();return true;}}public static bool TryBeginRemoval(EntityPlayerLocal p,Vector3i pos,string c,Guid j,out Permit permit){Begins++;permit=Allowed?new Permit():null;return Allowed;}}
public static class Fixture{static int n;static void Check(bool b){n++;if(!b)throw new Exception("request "+n);}public static string Run(){var p=new EntityPlayerLocal();p.world.Primary=p;var job=Guid.NewGuid();RebirthStationCancellationObservation o;Check(!RebirthStationCancellationRequest.TryRequest(null,new Vector3i(),"creation",job,out o));Check(!RebirthStationCancellationRequest.TryRequest(p,new Vector3i(),"creation",Guid.Empty,out o)&&RebirthStationTerminalIntentService.Calls==0);p.world.Primary=new object();Check(!RebirthStationCancellationRequest.TryRequest(p,new Vector3i(),"creation",job,out o)&&RebirthStationTerminalIntentService.Calls==0);p.world.Primary=p;RebirthStationTerminalIntentService.Allowed=false;Check(!RebirthStationCancellationRequest.TryRequest(p,new Vector3i(),"creation",job,out o)&&RebirthStationCancellationAttemptService.Begins==0);RebirthStationTerminalIntentService.Allowed=true;RebirthStationCancellationAttemptService.Allowed=false;Check(!RebirthStationCancellationRequest.TryRequest(p,new Vector3i(),"creation",job,out o)&&RebirthStationCancellationAttemptService.Writes==0);RebirthStationCancellationAttemptService.Allowed=true;RebirthStationCancellationAttemptService.Apply=false;Check(!RebirthStationCancellationRequest.TryRequest(p,new Vector3i(),"creation",job,out o)&&o==null);RebirthStationCancellationAttemptService.Apply=true;Check(RebirthStationCancellationRequest.TryRequest(p,new Vector3i(),"creation",job,out o)&&o!=null);RebirthStationCancellationAttemptService.Throw=true;Check(!RebirthStationCancellationRequest.TryRequest(p,new Vector3i(),"creation",job,out o)&&o==null);return "PASS "+n+" actual cancellation request orchestration with intent/permit/native doubles; no native cancellation proof";}}
"@
Add-Type -TypeDefinition ($source+$fixture)
[Fixture]::Run()