using System;
struct Vector3 {public float x,y,z;public Vector3(float x,float y,float z){this.x=x;this.y=y;this.z=z;}}
struct Vector3i {public int x,y,z;public Vector3i(int x,int y,int z){this.x=x;this.y=y;this.z=z;}public Vector3 ToVector3(){return new Vector3(x,y,z);}}
struct BlockValue {public bool isair;}
class World {public bool Ground=true,Occupied,Above;public BlockValue GetBlock(Vector3i p){return new BlockValue{isair=!Occupied};}public BlockValue GetBlock(int x,int y,int z){return new BlockValue{isair=y==11?!Above:!Ground};}}
class EntityPlayerLocal {public World world;public Inventory inventory=new Inventory();public bool Dead;public bool IsDead(){return Dead;}}
class ItemClass {public string Name="cntWoodWritableCrate";public string GetItemName(){return Name;}}
class ItemValue {public ItemClass ItemClass=new ItemClass();}
class ItemStack {public ItemValue itemValue=new ItemValue();public int count=1;public bool IsEmpty(){return count<=0;}}
class HandState {public bool IsSwitching;}
class Inventory {public HandState Hand {get {if(Throw)throw new Exception("missing hand state");return new HandState{IsSwitching=Switching};}} public int holdingItemIdx;public ItemClass holdingItem=new ItemClass();public ItemStack Selected=new ItemStack();public bool Switching,Running,Throw;public ItemStack GetItem(int slot){return Selected;}public bool GetIsFinishedSwitchingHeldItem(){if(Throw)throw new Exception("missing hand state");return !Switching;}public bool IsHoldingItemActionRunning(){return Running;}}
class RebirthGameBridgeNeeds {public static int ToolbeltSize(EntityPlayerLocal player){return 10;}}
class RebirthGameBridgeEntry {public static bool Roof;public static bool Roofed(EntityPlayerLocal p,Vector3 v){return Roof;}}
class Storage {
const string CrateName = "cntWoodWritableCrate";
public static bool Ready(EntityPlayerLocal player,int slot=0){return HasReadyPlacementItem(player,slot);}
// PRODUCTION_CLASS
public static bool Valid(EntityPlayerLocal p,float entranceY=10){return IsPlacementSite(p,new Vector3i(1,10,1),new Vector3(1,entranceY,1));}}
class Checks {static void A(bool b,string m){if(!b)throw new Exception(m);}static void Main(){var w=new World();var p=new EntityPlayerLocal{world=w};A(Storage.Valid(p),"clear exterior supported ground");w.Occupied=true;A(!Storage.Valid(p),"new occupant refused");w.Occupied=false;w.Above=true;A(!Storage.Valid(p),"headroom refused");w.Above=false;w.Ground=false;A(!Storage.Valid(p),"support removed refused");w.Ground=true;RebirthGameBridgeEntry.Roof=true;A(!Storage.Valid(p),"roof refused");RebirthGameBridgeEntry.Roof=false;A(!Storage.Valid(p,7),"height mismatch refused");A(!Storage.Valid(null),"missing player");p.world=null;A(!Storage.Valid(p),"missing world");p.world=w;A(Storage.Ready(p),"settled crate accepted");p.Dead=true;A(!Storage.Ready(p),"dead refused");p.Dead=false;p.inventory.holdingItemIdx=1;A(!Storage.Ready(p),"selection changed refused");p.inventory.holdingItemIdx=0;p.inventory.Selected.count=0;A(!Storage.Ready(p),"depleted stack refused");p.inventory.Selected.count=1;p.inventory.Selected.itemValue.ItemClass.Name="bat";A(!Storage.Ready(p),"slot replaced refused");p.inventory.Selected.itemValue.ItemClass.Name="cntWoodWritableCrate";p.inventory.holdingItem.Name="bat";A(!Storage.Ready(p),"stale equipped action refused");p.inventory.holdingItem.Name="cntWoodWritableCrate";p.inventory.Switching=true;A(!Storage.Ready(p),"switch animation refused");p.inventory.Switching=false;p.inventory.Running=true;A(!Storage.Ready(p),"active action refused");p.inventory.Running=false;p.inventory.Throw=true;A(!Storage.Ready(p),"unavailable hand state refused");p.inventory.Throw=false;A(!Storage.Ready(p,-1)&&!Storage.Ready(p,10),"invalid slot refused");p.inventory.Selected=null;A(!Storage.Ready(p),"missing selected stack refused");p.inventory=null;A(!Storage.Ready(p),"missing inventory refused");A(!Storage.Ready(null),"missing player refused");Console.WriteLine("PASS: actual exterior placement and held-item admission predicates; geometry changes, death, changed selection/stack/equipped action, switching/busy/missing hand state and invalid slots. Native world, inventory and roof detection doubled.");}}
