using System;
public class EntityPlayer {}
public class RebirthMetabolismState {public string SurvivorCreationId;}
class Origin {public string CreationId;}
class RebirthWorldCharacterRecord {public bool IsComplete=true;public Origin Origin=new Origin();}
class RebirthSurvivorMode {public static bool IsEnabledForCurrentWorld(){return true;}}
class RebirthStablePlayerIdentity {public static bool Available=true;public static bool TryResolveServerEntity(EntityPlayer p,out RebirthStablePlayerIdentity id){id=Available?new RebirthStablePlayerIdentity():null;return Available;}}
class RebirthWorldCharacterRepository {public static bool IsServerAuthority=true;public static RebirthWorldCharacterRecord Record=new RebirthWorldCharacterRecord();public static bool TryGet(RebirthStablePlayerIdentity id,out RebirthWorldCharacterRecord record){record=Record;return id!=null&&record!=null;}}
// PRODUCTION_SCOPE
// PRODUCTION_CLIENT
class Check {static void Assert(bool p,string label){if(!p)throw new Exception(label);}static void Main(){var player=new EntityPlayer();var state=new RebirthMetabolismState();var record=RebirthWorldCharacterRepository.Record;var id=Guid.NewGuid();record.Origin.CreationId=id.ToString("N");state.SurvivorCreationId=id.ToString("D");Assert(!RebirthSurvivorMetabolismCreationGate.ShouldDefer(player)&&RebirthSurvivorMetabolismCreationGate.IsLinkedToCommittedOrigin(player,state),"completed identity links across GUID formats");state.SurvivorCreationId=Guid.NewGuid().ToString("N");Assert(!RebirthSurvivorMetabolismCreationGate.IsLinkedToCommittedOrigin(player,state),"different character refused");state.SurvivorCreationId="";Assert(!RebirthSurvivorMetabolismCreationGate.IsLinkedToCommittedOrigin(player,state),"missing modern marker refused");record.Origin.CreationId="legacy-owner";Assert(RebirthSurvivorMetabolismCreationGate.IsLinkedToCommittedOrigin(player,state),"explicit empty legacy migration preserved");state.SurvivorCreationId="legacy-owner";Assert(RebirthSurvivorMetabolismCreationGate.IsLinkedToCommittedOrigin(player,state),"exact legacy marker preserved");state.SurvivorCreationId="legacy-other";Assert(!RebirthSurvivorMetabolismCreationGate.IsLinkedToCommittedOrigin(player,state),"different legacy marker refused");record.Origin.CreationId=state.SurvivorCreationId=Guid.Empty.ToString("N");Assert(!RebirthSurvivorMetabolismCreationGate.IsLinkedToCommittedOrigin(player,state),"empty GUID cannot link");record.IsComplete=false;Assert(RebirthSurvivorMetabolismCreationGate.ShouldDefer(player),"unfinished creation held");record.IsComplete=true;RebirthStablePlayerIdentity.Available=false;Assert(RebirthSurvivorMetabolismCreationGate.ShouldDefer(player),"unauthenticated identity held");Console.WriteLine("PASS actual metabolism creation gate and request scope: GUID formats, cross-character refusal, modern/legacy markers, incomplete and unauthenticated creation; repository/native adapters doubled");}}