using System;using System.Collections;using System.Collections.Generic;
struct Vector2 {public float x,y;public Vector2(float a,float b){x=a;y=b;}public static Vector2 Lerp(Vector2 a,Vector2 b,float t){return new Vector2(a.x+(b.x-a.x)*t,a.y+(b.y-a.y)*t);}public static float Distance(Vector2 a,Vector2 b){return (float)Math.Sqrt((a.x-b.x)*(a.x-b.x)+(a.y-b.y)*(a.y-b.y));}public static explicit operator Vector2(Vector3 a){return new Vector2(a.x,a.y);}}
struct Vector3 {public float x,y,z;public Vector3(float a,float b,float c=0){x=a;y=b;z=c;}public static Vector3 operator -(Vector3 a,Vector3 b){return new Vector3(a.x-b.x,a.y-b.y,a.z-b.z);}public float sqrMagnitude{get{return x*x+y*y+z*z;}}}
static class Mathf {public static float Clamp(float a,float min,float max){return Math.Max(min,Math.Min(max,a));}}
static class Time {public static int frameCount;public static float realtimeSinceStartup;}
static class Application {public static bool isFocused=true;}
static class Input {public static Vector3 mousePosition;}
class NativeCamera {public Action Project;public Vector3 ScreenToWorldPoint(Vector2 p){Project?.Invoke();return new Vector3(p.x,p.y);}}class UICamera{public NativeCamera Camera=new NativeCamera();public Action GetCamera;public NativeCamera cachedCamera{get{GetCamera?.Invoke();return Camera;}}}class SoftCursor{public UICamera Camera=new UICamera();public Action GetUiCamera;public UICamera uiCamera{get{GetUiCamera?.Invoke();return Camera;}}public int Writes;public Vector3 Position{set{Writes++;}}}
class PlayerAction {public string Name;public int Updates;public float Last;public void UpdateWithValue(float value,ulong tick,float delta){Updates++;Last=value;}}
class Permanent {public PlayerAction Inventory=new PlayerAction{Name="Inventory"};}
class PlayerActionsLocal {public Permanent PermanentActions=new Permanent();}
static class RebirthGameBridgeInput {
 private static readonly Dictionary<PlayerAction,Held> held=new Dictionary<PlayerAction,Held>();public static float Pace=.55f;public static bool CursorActive{get;private set;}public static Vector2 CursorPosition{get;private set;}private static Vector3 realMouseAtActivation;
 public static PlayerAction Click=new PlayerAction{Name="gui.LeftClick"},Slot=new PlayerAction{Name="InventorySlot2"};public static PlayerActionsLocal Local=new PlayerActionsLocal();public static PlayerActionsLocal LocalActions(){return Local;}public static IEnumerable<PlayerAction> FindByKey(string key){return new[]{Slot};}public static PlayerAction Find(string name){return name=="gui.LeftClick"?Click:Slot;}
 // PRODUCTION_INPUT
 public static void Tick(PlayerAction action){UpdateBindingsPrefix(action,1,.1f);}public static bool CursorCheck(){return CheckCursorActive();}public static Vector2 Screen(){var p=new Vector2(900,900);GetScreenPositionPostfix(ref p);return p;}public static void MoveCursor(SoftCursor cursor){HandleMovementPostfix(cursor);}public static bool NativeShift(bool physical){ShiftPostfix(ref physical);return physical;}
}
class ItemClass {public string Name="crate";public int Type=1;public string GetItemName(){return Name;}public static ItemValue GetItem(string name,bool unused){return new ItemValue{ItemClass=new ItemClass{Name=name}};}}
class ItemValue {public int type=1;public ItemClass ItemClass=new ItemClass();public ItemValue(){}public ItemValue(int type,int a,int b,bool c){this.type=type;}public bool IsEmpty(){return false;}}
class ItemStack {public int count=1;public ItemValue itemValue=new ItemValue();public bool IsEmpty(){return false;}public ItemStack(){}public ItemStack(ItemValue value,int count){itemValue=value;}}
class Hand {public int Changes;public void OnSlotChanged(int slot){Changes++;}}
class Inventory {public Grid ItemGrid=new Grid{items=new ItemStack[20]};public int holdingItemIdx,SelectedSlot;public Hand Hand=new Hand();public ItemStack GetItem(int slot){return new ItemStack();}}
class Grid{public ItemStack[] items;}class Bag {public Grid ItemGrid=new Grid{items=new[]{new ItemStack()}};public bool AddItem(ItemStack stack){return true;}}
class World {public EntityPlayerLocal Primary;public EntityPlayerLocal GetPrimaryPlayer(){return Primary;}} class GameManager {public static GameManager Instance=new GameManager();public World World;} class EntityPlayerLocal {public World world=new World();public Inventory inventory=new Inventory();public Bag bag=new Bag();public bool Dead;public bool IsDead(){return Dead;}}
class ToolbeltConfig {public static ToolbeltConfig CurrentConfig=new ToolbeltConfig();public int SlotsPerBar=10;}
static class RebirthGameBridgeNeeds {
 public static bool Supply=false,Assigned;public static int ToolbeltSize(EntityPlayerLocal p){return 20;}private static string HeldName(EntityPlayerLocal p){return "crate";}public static IEnumerator WaitHandsFree(EntityPlayerLocal p,float timeout){yield return null;}private static IEnumerator Wait(float seconds){float end=Time.realtimeSinceStartup+seconds;while(Time.realtimeSinceStartup<end)yield return null;}
 public static int ToolbeltSlot(EntityPlayerLocal p,Func<ItemClass,bool> want,out string name,Func<ItemStack,bool> match=null){name="crate";return Assigned?0:-1;}private static string BestInBag(EntityPlayerLocal p,Func<ItemClass,bool> want,Func<ItemStack,bool> match){return "crate";}private static int FreeableToolbeltSlot(EntityPlayerLocal p,Func<ItemClass,bool> want){return 0;}
 // PRODUCTION_NEEDS
}
static class RebirthGameBridgeUi {
 public static bool AnyModalOpen(){return true;}public static IEnumerator LookAtWindow(){yield return null;}public static IEnumerator CloseMenus(){yield return null;}public static bool TryFindEmptyToolbeltSlot(out Vector2 point,out int slot){point=new Vector2(20,20);slot=0;return true;}public static bool TryFindToolbeltSlot(int slot,out Vector2 point){point=new Vector2();return true;}public static bool TryFindEmptyBackpackSlot(out Vector2 point){point=new Vector2();return true;}public static bool TryFindItemSlot(string name,bool belt,out Vector2 point,Func<ItemStack,bool> match){point=new Vector2(10,10);return true;}public static ItemStack CursorItem;public static ItemStack HeldItem(){return CursorItem;}public static bool IsWindowOpen(string window){return false;}public static bool TryFindById(string id,out Vector2 p){p=new Vector2();return false;}public static bool TryFindByText(string window,string text,out Vector2 p){p=new Vector2();return false;}public static string HeldItemName(){return null;}
 public class Rect {public Vector2 center;}
 public class NativeGrid {public Action Visibility;public bool HasVisibleCenter(int i){Visibility?.Invoke();return true;}}
 public class NativeUi {public PlayerUi playerUI;}public class PlayerUi{public EntityPlayerLocal entityPlayer;}
 public class XUiC_Backpack{}public class XUiC_RebirthCraftingInventoryScroll{public bool IsSlotVisible(int i){return true;}}
 public class NativeView {public Action ReadVisible;public bool Visible=true;public bool IsVisible{get{ReadVisible?.Invoke();return Visible;}}}
 public class XUiC_TextInput{public NativeUi xui;public NativeView ViewComponent=new NativeView();public int Sets,Triggers;public Action SetText,Trigger;public string Text{set{Sets++;SetText?.Invoke();}}public void TriggerOnChangeHandler(bool ignored){Triggers++;Trigger?.Invoke();}}
 public static XUiC_TextInput TextControl;public static XUiC_RebirthContextSlot ContextControl;static T FindAncestor<T>(object o) where T:class{return null;}static T FindDescendant<T>(object o) where T:class{return null;}
 public class XUiC_ItemStack {public enum StackLocationTypes{ToolBelt,Backpack,LootContainer}public StackLocationTypes StackLocation;public NativeUi xui;public bool Foreign;public ItemStack ItemStack;public int SlotNumber;public T GetParentByType<T>() where T:class {return !Foreign&&typeof(T)==typeof(XUiC_Backpack)?new XUiC_Backpack() as T:null;}}
 public class XUiC_RebirthContextSlot:XUiC_ItemStack {public bool IsBackpack,IsPresented;public int Scrolls;public Action Scroll;public NativeGrid Grid=new NativeGrid();public void Scrolled(float d){Scrolls++;Scroll?.Invoke();}}
 public class FakeJson{readonly Dictionary<string,object> values=new Dictionary<string,object>();public object this[string key]{get{object v;return values.TryGetValue(key,out v)?v:null;}set{values[key]=value;}}}public class Node {public FakeJson Json=new FakeJson();public object Controller;public bool HasRect=true;public string Path;public Rect ScreenRect;}
 public static float SlotOffset;public static bool HideSlot,ForeignOnly,ForeignSpoofLocation;
 static IEnumerable<Node> Collect(string path,bool all){var p=GameManager.Instance.World?.GetPrimaryPlayer();if(p==null)yield break;if(path=="crafting"&&TextControl!=null){var n=new Node{Controller=TextControl};n.Json["id"]="searchInput";yield return n;yield break;}if(path==null&&ContextControl!=null){yield return new Node{Controller=ContextControl};yield break;}if(path=="dragAndDrop"){if(CursorItem!=null)yield return new Node{Path="dragAndDrop/0",Controller=new XUiC_ItemStack{xui=new NativeUi{playerUI=new PlayerUi{entityPlayer=p}},ItemStack=CursorItem},ScreenRect=new Rect()};yield break;}if(HideSlot)yield break;for(int group=0;group<2;group++){var slots=group==0?p.inventory.ItemGrid.items:p.bag.ItemGrid.items;for(int i=0;i<slots.Length;i++)yield return new Node{Path=(group==0?"toolbelt/":"bag/inventory/")+i,Controller=new XUiC_ItemStack{xui=new NativeUi{playerUI=new PlayerUi{entityPlayer=p}},Foreign=ForeignOnly,StackLocation=ForeignOnly&&!ForeignSpoofLocation?XUiC_ItemStack.StackLocationTypes.LootContainer:group==0?XUiC_ItemStack.StackLocationTypes.ToolBelt:XUiC_ItemStack.StackLocationTypes.Backpack,ItemStack=slots[i],SlotNumber=i},ScreenRect=new Rect{center=new Vector2((group==0?20:10)+i*2+SlotOffset,group==0?20:10)}};}}
 // PRODUCTION_UI
}
class Driver:IDisposable {private readonly Stack<IEnumerator> stack=new Stack<IEnumerator>();public Driver(IEnumerator root){stack.Push(root);}public bool Step(){while(stack.Count>0){var it=stack.Peek();if(!it.MoveNext()){(stack.Pop() as IDisposable)?.Dispose();continue;}var child=it.Current as IEnumerator;if(child!=null){stack.Push(child);continue;}Time.frameCount++;Time.realtimeSinceStartup+=.1f;RebirthGameBridgeInput.Tick(RebirthGameBridgeInput.Click);RebirthGameBridgeInput.Tick(RebirthGameBridgeInput.Slot);return true;}return false;}public void Dispose(){while(stack.Count>0)(stack.Pop() as IDisposable)?.Dispose();}}
class Checks {
 static int ChecksRun;static void A(bool b,string m){ChecksRun++;if(!b)throw new Exception(m);}static void Reset(){RebirthGameBridgeInput.ReleaseAll();RebirthGameBridgeInput.LockCursor=false;Time.frameCount=0;Time.realtimeSinceStartup=0;Input.mousePosition=new Vector3();Application.isFocused=true;RebirthGameBridgeUi.CursorItem=null;RebirthGameBridgeInput.Click.Updates=RebirthGameBridgeInput.Slot.Updates=0;RebirthGameBridgeNeeds.Assigned=false;}
 static EntityPlayerLocal NewPlayer(){Reset();var p=new EntityPlayerLocal();p.world.Primary=p;GameManager.Instance.World=p.world;return p;}
 static void Main(){
 Reset();var action=new PlayerAction{Name="test"};RebirthGameBridgeInput.HoldFrames(action,0,.7f);RebirthGameBridgeInput.Tick(action);A(action.Updates==1&&action.Last==.7f,"actual hold injects chosen value");Time.frameCount=1;RebirthGameBridgeInput.Tick(action);A(RebirthGameBridgeInput.IsHeld(action),"inclusive frame deadline");Time.frameCount=2;RebirthGameBridgeInput.Tick(action);A(!RebirthGameBridgeInput.IsHeld(action),"frame deadline expiry");
 Reset();RebirthGameBridgeInput.HoldSeconds(action,1);Time.realtimeSinceStartup=1;RebirthGameBridgeInput.Tick(action);A(RebirthGameBridgeInput.IsHeld(action),"inclusive time deadline");Time.realtimeSinceStartup=1.01f;RebirthGameBridgeInput.Tick(action);A(!RebirthGameBridgeInput.IsHeld(action),"time expiry");RebirthGameBridgeInput.HoldSeconds(action,0);Time.realtimeSinceStartup=100;RebirthGameBridgeInput.Tick(action);A(RebirthGameBridgeInput.IsHeld(action),"zero seconds holds until release");RebirthGameBridgeInput.Release(null);A(RebirthGameBridgeInput.IsHeld(action),"null release no effect");RebirthGameBridgeInput.HoldFrames(action,50,.4f);RebirthGameBridgeInput.Release(action);A(!RebirthGameBridgeInput.IsHeld(action),"legacy release removes current replacement entry (existing ownership gap)");
 Reset();RebirthGameBridgeInput.SetCursor(new Vector2(10,20));A(RebirthGameBridgeInput.CursorActive&&RebirthGameBridgeInput.CursorPosition.x==10,"cursor activates chosen point");Input.mousePosition=new Vector3(25,0);A(RebirthGameBridgeInput.CursorCheck(),"exact25px threshold stays active");Input.mousePosition=new Vector3(26,0);A(!RebirthGameBridgeInput.CursorCheck(),"focused real mouse returns cursor");RebirthGameBridgeInput.SetCursor(new Vector2());Application.isFocused=false;Input.mousePosition=new Vector3(100,0);A(RebirthGameBridgeInput.CursorCheck(),"unfocused real movement leaves legacy cursor");Application.isFocused=true;RebirthGameBridgeInput.LockCursor=true;A(RebirthGameBridgeInput.CursorCheck(),"legacy lock ignores handback");RebirthGameBridgeInput.ReleaseCursor();A(!RebirthGameBridgeInput.CursorActive&&RebirthGameBridgeInput.LockCursor,"ReleaseCursor doesn't clear LockCursor (existing cleanup gap)");
 Reset();using(var driver=new Driver(RebirthGameBridgeUi.GlideTo(new Vector2(100,100)))){A(driver.Step(),"actual glide yields");Input.mousePosition=new Vector3(100,0);A(!RebirthGameBridgeInput.CursorCheck(),"physical takeover before next glide write");A(driver.Step()&&RebirthGameBridgeInput.CursorActive,"legacy glide reactivates after takeover (existing gap)");}
 Reset();using(var driver=new Driver(RebirthGameBridgeUi.DragItem(new Vector2(),new Vector2(20,20)))){int limit=0;while(!RebirthGameBridgeInput.IsHeld(RebirthGameBridgeInput.Click)&&driver.Step())if(++limit>100)throw new Exception("drag setup timeout");A(RebirthGameBridgeInput.IsHeld(RebirthGameBridgeInput.Click),"actual drag holds native mouse before carry");}A(RebirthGameBridgeInput.IsHeld(RebirthGameBridgeInput.Click),"disposing legacy nested drag leaves held click (confirmed gap)");
 Reset();var player=new EntityPlayerLocal();using(var driver=new Driver(RebirthGameBridgeNeeds.Prepare(player,ic=>true,null,"a crate",s=>{}))){int limit=0;while(!RebirthGameBridgeInput.IsHeld(RebirthGameBridgeInput.Click)&&driver.Step())if(++limit>100)throw new Exception("Prepare timeout");A(RebirthGameBridgeInput.LockCursor&&RebirthGameBridgeInput.IsHeld(RebirthGameBridgeInput.Click),"actual Prepare reaches nested drag");}A(RebirthGameBridgeInput.LockCursor&&RebirthGameBridgeInput.IsHeld(RebirthGameBridgeInput.Click),"disposing legacy Prepare leaves lock and click (confirmed gap)");
 Reset();player=new EntityPlayerLocal();bool done=false,ok=false;using(var driver=new Driver(RebirthGameBridgeNeeds.Equip(player,11,"crate",v=>{done=true;ok=v;}))){int limit=0;while(driver.Step()){if(RebirthGameBridgeInput.IsHeld(RebirthGameBridgeInput.Slot)){A(RebirthGameBridgeInput.Shift,"second toolbelt bar uses Shift");player.inventory.holdingItemIdx=11;}if(++limit>100)throw new Exception("Equip timeout");}}A(done&&ok&&!RebirthGameBridgeInput.Shift,"legacy Equip succeeds and restores Shift");
 Reset();player=new EntityPlayerLocal();using(var driver=new Driver(RebirthGameBridgeNeeds.Equip(player,1,"crate",v=>{}))){int limit=0;while(!RebirthGameBridgeInput.IsHeld(RebirthGameBridgeInput.Slot)&&driver.Step())if(++limit>100)throw new Exception("Equip cancel timeout");RebirthGameBridgeInput.Shift=true;}A(!RebirthGameBridgeInput.Shift,"legacy Equip disposal restores old bool over newer same-value writer (confirmed ownership gap)");
 var native=NewPlayer();var parent=new RebirthGameBridgeInput.OwnedInputScope(native,()=>true);A(parent.TryHoldSeconds(action,0,.8f),"owned hold admitted");RebirthGameBridgeInput.HoldSeconds(action,0,.8f);A(!parent.Admitted,"same value newer legacy action invalidates");parent.Dispose();A(RebirthGameBridgeInput.IsHeld(action),"owned disposal preserves newer hold");
 native=NewPlayer();RebirthGameBridgeInput.HoldSeconds(action,0);parent=new RebirthGameBridgeInput.OwnedInputScope(native,()=>true);A(!parent.TryHoldFrames(action,3),"foreign held entry refused");parent.Dispose();A(RebirthGameBridgeInput.IsHeld(action),"foreign hold survives refusal cleanup");
 native=NewPlayer();parent=new RebirthGameBridgeInput.OwnedInputScope(native,()=>true);parent.TryHoldFrames(action,1);Time.frameCount=2;RebirthGameBridgeInput.Tick(action);A(!RebirthGameBridgeInput.IsHeld(action)&&parent.Admitted,"owned natural expiry doesn't invalidate operation");parent.Dispose();
 native=NewPlayer();parent=new RebirthGameBridgeInput.OwnedInputScope(native,()=>true);A(parent.TrySetShift(true),"parent shift acquired");var child=new RebirthGameBridgeInput.OwnedInputScope(native,()=>true,parent);A(child.TrySetShift(false)&&parent.Admitted,"nested flag write preserves parent admission");child.Dispose();A(RebirthGameBridgeInput.Shift,"child restores live parent flag");parent.Dispose();A(!RebirthGameBridgeInput.Shift,"parent restores original flag");
 native=NewPlayer();parent=new RebirthGameBridgeInput.OwnedInputScope(native,()=>true);parent.TrySetShift(true);RebirthGameBridgeInput.Shift=true;A(!parent.Admitted,"same value legacy flag write invalidates");parent.Dispose();A(RebirthGameBridgeInput.Shift,"same value external flag survives cleanup");
 native=NewPlayer();parent=new RebirthGameBridgeInput.OwnedInputScope(native,()=>true);parent.TrySetShift(true);child=new RebirthGameBridgeInput.OwnedInputScope(native,()=>true,parent);child.TrySetShift(true);parent.Dispose();child.Dispose();A(!RebirthGameBridgeInput.Shift,"disposed parent not resurrected by child flag cleanup");
 native=NewPlayer();parent=new RebirthGameBridgeInput.OwnedInputScope(native,()=>true);A(parent.TrySetCursor(new Vector2(10,10)),"parent cursor acquired");child=new RebirthGameBridgeInput.OwnedInputScope(native,()=>true,parent);A(child.TrySetCursor(new Vector2(20,20))&&parent.Admitted,"nested cursor admission");RebirthGameBridgeInput.SetCursor(new Vector2(20,20));A(!child.Admitted&&!parent.Admitted,"same-value legacy cursor invalidates entire nested chain");child.Dispose();parent.Dispose();A(RebirthGameBridgeInput.CursorActive&&RebirthGameBridgeInput.CursorPosition.x==20,"newer cursor survives nested disposal");A(!parent.TrySetCursor(new Vector2()),"old parent cannot reacquire");
 native=NewPlayer();parent=new RebirthGameBridgeInput.OwnedInputScope(native,()=>true);parent.TrySetCursor(new Vector2());child=new RebirthGameBridgeInput.OwnedInputScope(native,()=>true,parent);child.TrySetCursor(new Vector2());RebirthGameBridgeInput.ReleaseCursor();A(!child.Admitted&&!parent.Admitted,"legacy release invalidates entire nested chain");child.Dispose();parent.Dispose();A(!RebirthGameBridgeInput.CursorActive,"release handoff stays inactive");
 native=NewPlayer();parent=new RebirthGameBridgeInput.OwnedInputScope(native,()=>true);parent.TrySetCursor(new Vector2());Input.mousePosition=new Vector3(26,0);A(!parent.TrySetCursor(new Vector2(30,30))&&!RebirthGameBridgeInput.CursorActive,"user takeover before write refuses cursor reacquisition");parent.Dispose();
 native=NewPlayer();parent=new RebirthGameBridgeInput.OwnedInputScope(native,()=>true);parent.TrySetShift(true);parent.TryHoldSeconds(action,0);GameManager.Instance.World=new World();A(!RebirthGameBridgeInput.Shift,"native getter removes owned Shift before coroutine resumes in replaced world");RebirthGameBridgeInput.Tick(action);A(!RebirthGameBridgeInput.IsHeld(action),"native action injection refuses replaced world");RebirthGameBridgeInput.Shift=true;A(RebirthGameBridgeInput.Shift,"anonymous legacy Shift preserved across native world change");parent.Dispose();
 native=NewPlayer();parent=new RebirthGameBridgeInput.OwnedInputScope(native,()=>true);parent.TrySetShift(true);native.world.Primary=new EntityPlayerLocal();A(!RebirthGameBridgeInput.Shift&&!parent.Admitted,"native primary replacement masks owned modifier before continuation");parent.Dispose();
 native=NewPlayer();parent=new RebirthGameBridgeInput.OwnedInputScope(native,()=>true);using(var driver=new Driver(RebirthGameBridgeUi.DragItem(new Vector2(),new Vector2(20,20),parent))){int limit=0;while(!RebirthGameBridgeInput.IsHeld(RebirthGameBridgeInput.Click)&&driver.Step())if(++limit>100)throw new Exception("owned drag setup timeout");A(RebirthGameBridgeInput.IsHeld(RebirthGameBridgeInput.Click),"owned drag reaches held mouse");}A(!RebirthGameBridgeInput.IsHeld(RebirthGameBridgeInput.Click),"outer driver disposal releases only owned drag mouse");parent.Dispose();
 native=NewPlayer();parent=new RebirthGameBridgeInput.OwnedInputScope(native,()=>true);RebirthGameBridgeInput.HoldSeconds(RebirthGameBridgeInput.Click,0);using(var driver=new Driver(RebirthGameBridgeUi.ClickAt(new Vector2(),parent))){int limit=0;while(driver.Step())if(++limit>100)throw new Exception("owned click refusal timeout");}A(!parent.Admitted&&RebirthGameBridgeInput.IsHeld(RebirthGameBridgeInput.Click),"foreign-click refusal propagated and foreign hold survives");parent.Dispose();
 native=NewPlayer();parent=new RebirthGameBridgeInput.OwnedInputScope(native,()=>true);int callbacks=0;using(var driver=new Driver(RebirthGameBridgeNeeds.Equip(native,1,"crate",v=>callbacks++,parent))){int limit=0;while(!RebirthGameBridgeInput.IsHeld(RebirthGameBridgeInput.Slot)&&driver.Step())if(++limit>100)throw new Exception("owned equip setup timeout");}A(callbacks==1&&!RebirthGameBridgeInput.IsHeld(RebirthGameBridgeInput.Slot)&&!RebirthGameBridgeInput.Shift,"equip cancellation callback once and exact cleanup");parent.Dispose();
 native=NewPlayer();parent=new RebirthGameBridgeInput.OwnedInputScope(native,()=>true);using(var driver=new Driver(RebirthGameBridgeNeeds.Prepare(native,ic=>true,null,"crate",s=>{},parent))){int limit=0;while(!RebirthGameBridgeInput.IsHeld(RebirthGameBridgeInput.Click)&&driver.Step())if(++limit>100)throw new Exception("owned prepare setup timeout");RebirthGameBridgeUi.CursorItem=new ItemStack();}A(!RebirthGameBridgeInput.IsHeld(RebirthGameBridgeInput.Click)&&!RebirthGameBridgeInput.LockCursor&&parent.CursorCustodyPending,"prepare cancellation releases own input and reports real cursor custody pending");parent.Dispose();
 Console.WriteLine("PASS "+ChecksRun+" actual default + owned input/Needs/UI checks; ownership replacement/nesting/native world+primary/user handoff/outer disposal/callback/cursor custody qualified with native doubles; NO running-game claim.");
 }
}

static class RebirthGameBridgePoiStorage {public static string OwnedItemKey(ItemStack s){return s==null?null:"stub";}}
