using System;using System.Collections.Generic;
class EntityPlayer{}
class RebirthStablePlayerIdentity{}
class RebirthSkillDefinition{}
class RebirthSkillKnowledgeRuntimeState {public float Value=10;}
class Progression {public Dictionary<string,RebirthSkillKnowledgeRuntimeState> SkillKnowledge=new Dictionary<string,RebirthSkillKnowledgeRuntimeState>{{"skill",new RebirthSkillKnowledgeRuntimeState()}};public HashSet<string> KnowledgeIds=new HashSet<string>();}
class RebirthWorldCharacterRecord {public Progression Progression=new Progression();public string Dirty;public void Touch(string reason){Dirty=reason;}}
static class RebirthSkillAwardService {public static int Queued;public static EntityPlayer QueuedPlayer;public static void QueueOwnerPublication(EntityPlayer p){Queued++;QueuedPlayer=p;}public static RebirthWorldCharacterRecord Record=new RebirthWorldCharacterRecord();public static bool TryGetEligible(EntityPlayer p,out RebirthStablePlayerIdentity identity,out RebirthWorldCharacterRecord record){identity=new RebirthStablePlayerIdentity();record=Record;return true;}}
static class RebirthSurvivorDefinitionRegistry {public static bool TryGetSkill(string id,out RebirthSkillDefinition d){d=new RebirthSkillDefinition();return true;}}
static class RebirthTeachingService {public static float GetSubjectLearningMultiplier(EntityPlayer p,string skill)=>1;}
static class RebirthWorldCharacterRepository {public static bool Saved;public static bool SaveIfDirty(RebirthStablePlayerIdentity id,string reason)=>Saved;}
static class RebirthSurvivorNetworkService {public static bool SendSucceeds=true;public static int Sent;public static bool SendOwnerState(EntityPlayer p,long id,bool all,string reason){Sent++;return SendSucceeds;}}
static class RebirthLogSettings {public static bool LiteratureLoggingEnabled=false;public static void TraceLiterature(string text){}}
class Service {static readonly object Gate=new object();static float GetMinimum()=>0;static float GetMaximum()=>100;
// PRODUCTION_CLASS
}
class Check {static void Assert(bool v,string reason){if(!v)throw new Exception(reason);}static void Main(){var p=new EntityPlayer();var r=RebirthSkillAwardService.Record;float applied;bool already;Assert(!Service.TryStudyLiterature(p,"skill",5,"marker","book",out applied,out already)&&applied==0&&r.Progression.SkillKnowledge["skill"].Value==10&&!r.Progression.KnowledgeIds.Contains("marker")&&RebirthSurvivorNetworkService.Sent==0,"Failed new lesson rolled back without success publication");RebirthWorldCharacterRepository.Saved=true;Assert(Service.TryStudyLiterature(p,"skill",5,"marker","book",out applied,out already)&&applied==5&&!already&&r.Progression.SkillKnowledge["skill"].Value==15,"Retry awards one saved lesson");Assert(Service.TryStudyLiterature(p,"skill",5,"marker","cassette",out applied,out already)&&applied==0&&already&&r.Progression.SkillKnowledge["skill"].Value==15,"Equivalent medium cannot double award");RebirthWorldCharacterRepository.Saved=false;int sent=RebirthSurvivorNetworkService.Sent;Assert(!Service.TryStudyLiterature(p,"skill",5,"marker","book",out applied,out already)&&r.Progression.SkillKnowledge["skill"].Value==15&&r.Progression.KnowledgeIds.Contains("marker")&&RebirthSurvivorNetworkService.Sent==sent,"Existing marker still requires persistence but earned lesson retained");RebirthWorldCharacterRepository.Saved=true;RebirthSurvivorNetworkService.SendSucceeds=false;Assert(Service.TryStudyLiterature(p,"skill",5,"second","book",out applied,out already)&&applied==5&&r.Progression.SkillKnowledge["skill"].Value==20&&r.Progression.KnowledgeIds.Contains("second")&&RebirthSkillAwardService.Queued==1&&Object.ReferenceEquals(RebirthSkillAwardService.QueuedPlayer,p),"Saved lesson queues exact owner after send failure");Assert(Service.TryStudyLiterature(p,"skill",5,"second","cassette",out applied,out already)&&applied==0&&already&&r.Progression.SkillKnowledge["skill"].Value==20,"Publication failure cannot reaward lesson");Assert(!Service.TryStudyLiterature(p,"skill",float.NaN,"other","book",out applied,out already),"Invalid lesson rejected");Console.WriteLine("PASS actual one-time literature theory award with persistence/player/registry doubles: failed-save rollback, retry once, cross-medium idempotence, existing-marker save failure no unsaved owner publication, failed-send exact-owner queue and no reaward");}}
