using System.IO;
using System;using System.Linq;using System.Collections.Generic;using System.Collections.ObjectModel;
public class EntityPlayer{}
public class ItemValue {public void Write(BinaryWriter w){w.Write(type);w.Write(Metadata??"");w.Write(HasModSlots);w.Write(Mods);}public int type;public bool HasModSlots,Mods;public string Metadata;public bool IsEmpty(){return type==0;}public bool HasMods(){return Mods;}public ItemValue Clone(){return (ItemValue)MemberwiseClone();}}
public class ItemStack {public static ItemStack Empty=>new ItemStack(0,0);public ItemValue itemValue;public int count;public ItemStack(int type,int n,string metadata=""){itemValue=new ItemValue{type=type,Metadata=metadata};count=n;}public bool IsEmpty(){return count<=0||itemValue==null||itemValue.IsEmpty();}public ItemStack Clone(){return new ItemStack(itemValue.type,count){itemValue=itemValue.Clone()};}}
public class Recipe {public List<ItemStack> ingredients=new List<ItemStack>();public bool materialBasedRecipe,wildcardForgeCategory,wildcardCampfireCategory,UseIngredientModifier,IsTrackable,isQuest,isChallenge,IsTracked,IsScrap,IsLearnable;public ushort Version=1;public int itemValueType=5,count=2,craftingToolType=7,unlockExpGain,craftExpGain=3,craftingTier;public float craftingTime;public string craftingArea="workbench",tooltip;public object tags,Effects;}
static class XUiM_Recipes {public static IList<Recipe> Last;public static string Station;public static List<Recipe> FilterRecipesByWorkstation(string s,IList<Recipe> r){Station=s;Last=r;return r.ToList();}}
static class RebirthCraftingIngredientQuantity {public static int Adjusted=-1;public static bool Valid=true;public static bool TryResolveTotal(EntityPlayer p,Recipe r,ItemStack i,int t,int batches,out int n){long wide=(long)(Adjusted>=0?Adjusted:i.count)*batches;n=wide>int.MaxValue?0:(int)wide;return Valid&&wide<=int.MaxValue&&wide>=0;}}
static class RebirthStationGridQueue { public static bool Stamp(Recipe c,Recipe a,int b,int t){return true;} }
// PRODUCTION_CLASS
class Check {
 static void Assert(bool v,string m){if(!v)throw new Exception(m);}
 static void Main(){var submitted=new ItemStack(1,3,"receipt-a");var changed=submitted.Clone();Assert(RebirthStationGridIngredients.IsSameStackSnapshot(changed,submitted),"Identical full submitted payload accepted");changed.itemValue.Metadata="receipt-b";Assert(!RebirthStationGridIngredients.IsSameStackSnapshot(changed,submitted),"Same type/count changed metadata rejected");changed=submitted.Clone();changed.itemValue.Mods=true;Assert(!RebirthStationGridIngredients.IsSameStackSnapshot(changed,submitted),"Same type/count changed mods rejected");changed=submitted.Clone();changed.count--;Assert(!RebirthStationGridIngredients.IsSameStackSnapshot(changed,submitted),"Changed submitted count rejected");var r=new Recipe();r.ingredients.Add(new ItemStack(1,4));var grid=new List<ItemStack>{new ItemStack(1,3,"A"),new ItemStack(1,7,"B")};RebirthStationGridIngredients.Plan plan;
 Assert(RebirthStationGridIngredients.TryPlan(null,r,grid,2,1,out plan),"Split input payloads must cover batch");Assert(plan.Inputs.Count==2&&plan.Inputs[0].Count==3&&plan.Inputs[1].Count==5,"Exact slot allocation"); Recipe concrete;Assert(RebirthStationGridIngredients.TryBuildQueueRecipe(plan,15,out concrete),"Concrete native batch");Assert(concrete.count==4&&concrete.craftingTime==30&&concrete.craftExpGain==6&&concrete.craftingToolType==7&&concrete.craftingTier==1&&!concrete.UseIngredientModifier,"Output/time/XP/tool/tier preservation");Assert(concrete.ingredients[0].count==3&&concrete.ingredients[1].count==5&&concrete.ingredients[0].itemValue.Metadata=="A"&&concrete.ingredients[1].itemValue.Metadata=="B","Indivisible fragments conserved without per-portion truncation");concrete.ingredients[0].itemValue.Metadata="queue mutation";Assert(plan.Inputs[0].Snapshot().itemValue.Metadata=="A","Queue recipe is detached");r.count=999;r.craftingToolType=99;Assert(RebirthStationGridIngredients.TryBuildQueueRecipe(plan,15,out concrete)&&concrete.count==4&&concrete.craftingToolType==7,"Plan owns admitted native recipe snapshot");r.count=2;r.craftingToolType=7;Assert(!RebirthStationGridIngredients.TryBuildQueueRecipe(plan,float.NaN,out concrete)&&!RebirthStationGridIngredients.TryBuildQueueRecipe(plan,float.PositiveInfinity,out concrete)&&!RebirthStationGridIngredients.TryBuildQueueRecipe(plan,-1,out concrete),"Invalid timing rejected");
 ItemStack[] remainder;Assert(RebirthStationGridIngredients.TryBuildDebitedGrid(plan,grid,out remainder),"Admitted debit snapshot");Assert(remainder[0].IsEmpty()&&remainder[1].count==2&&remainder[1].itemValue.Metadata=="B","Exact paid slots and leftovers");remainder[1].itemValue.Metadata="detached";Assert(grid[1].itemValue.Metadata=="B","Debit result detached");grid[1].count++;Assert(!RebirthStationGridIngredients.TryBuildDebitedGrid(plan,grid,out remainder)&&remainder==null,"Changed slot count rejected");grid[1].count--;grid[1].itemValue.Metadata="substitution";Assert(!RebirthStationGridIngredients.TryBuildDebitedGrid(plan,grid,out remainder),"Same-type metadata substitution rejected");grid[1].itemValue.Metadata="B";Assert(grid[0].count==3&&grid[1].count==7&&r.ingredients[0].count==4,"No source mutation");grid[0].itemValue.Metadata="changed";Assert(plan.Inputs[0].Snapshot().itemValue.Metadata=="A","Detached input metadata");var snapshot=plan.Inputs[1].Snapshot();snapshot.itemValue.Metadata="changed";snapshot.count=999;Assert(plan.Inputs[1].Snapshot().itemValue.Metadata=="B"&&plan.Inputs[1].Snapshot().count==5,"Snapshot must not mutate plan");
 Assert(!RebirthStationGridIngredients.TryPlan(null,r,grid,3,1,out plan),"Insufficient inputs");grid.Add(new ItemStack(2,1));Assert(!RebirthStationGridIngredients.TryPlan(null,r,grid,1,1,out plan),"Extra ingredient rejects match");grid.RemoveAt(2);grid[0].itemValue.HasModSlots=true;grid[0].itemValue.Mods=true;Assert(!RebirthStationGridIngredients.TryPlan(null,r,grid,1,1,out plan),"Modified equipment excluded");grid[0].itemValue.Mods=false;Assert(RebirthStationGridIngredients.TryPlan(null,r,grid,1,1,out plan),"Unmodified equipment permitted");
 grid[0].count=-1;Assert(!RebirthStationGridIngredients.TryPlan(null,r,grid,1,1,out plan),"Negative slot count rejected");grid[0].count=65536;Assert(!RebirthStationGridIngredients.TryPlan(null,r,grid,1,1,out plan),"Native ushort codec bound");grid[0].count=3;var validValue=grid[0].itemValue;grid[0].itemValue=null;Assert(!RebirthStationGridIngredients.TryPlan(null,r,grid,1,1,out plan),"Null item payload fails closed without native IsEmpty crash");grid[0].itemValue=validValue;grid.Add(new ItemStack(0,1));Assert(!RebirthStationGridIngredients.TryPlan(null,r,grid,1,1,out plan),"Positive count with none identity rejected");grid.RemoveAt(grid.Count-1); RebirthCraftingIngredientQuantity.Adjusted=2;Assert(RebirthStationGridIngredients.TryPlan(null,r,grid,2,1,out plan)&&plan.Inputs.Sum(x=>x.Count)==4,"Modified native quantities used");RebirthCraftingIngredientQuantity.Adjusted=0;Assert(RebirthStationGridIngredients.TryPlan(null,r,new List<ItemStack>(),1,1,out plan)&&plan.Inputs.Count==0,"Zero cost handled");RebirthCraftingIngredientQuantity.Adjusted=int.MaxValue;Assert(!RebirthStationGridIngredients.TryPlan(null,r,grid,2,1,out plan),"Overflow rejected");RebirthCraftingIngredientQuantity.Adjusted=-1;r.ingredients.Add(new ItemStack(1,int.MaxValue));Assert(!RebirthStationGridIngredients.TryPlan(null,r,grid,1,1,out plan),"Duplicate native requirements cannot overflow");r.ingredients.RemoveAt(1);r.materialBasedRecipe=true;Assert(!RebirthStationGridIngredients.TryPlan(null,r,grid,1,1,out plan),"Forge material ledger remains specialized");r.materialBasedRecipe=false;r.IsScrap=true;Assert(!RebirthStationGridIngredients.TryPlan(null,r,grid,1,1,out plan),"Scrapping excluded from exact crafting grid");r.IsScrap=false;Assert(!RebirthStationGridIngredients.TryPlan(null,r,Enumerable.Range(0,10).Select(x=>new ItemStack(0,0)).ToList(),1,1,out plan),"Grid bound");Assert(!RebirthStationGridIngredients.TryPlan(null,r,grid,0,1,out plan),"Batch bound");var recipes=new List<Recipe>{r};RebirthStationGridIngredients.Candidates("forge",recipes);Assert(XUiM_Recipes.Station=="forge"&&object.ReferenceEquals(XUiM_Recipes.Last,recipes),"Native catalogue filtering delegated");
 Console.WriteLine("PASS: actual station grid allocator; split metadata custody, detached snapshots, exact modified totals, leftovers, extra/missing/modded inputs, zero-cost and overflow bounds, specialized forge exclusion and native catalogue delegation");}
}