using System;
struct RebirthNpcStableId {}
class ItemClass {public string Name="item";}
class ItemValue {public ItemClass ItemClass=new ItemClass();}
class ItemStack {public int count;public ItemValue itemValue=new ItemValue();public bool IsEmpty(){return count==0;}}
class PackedBoolArray {public int Length=1;public bool this[int i]{get{return false;}}}
class RebirthNpcInventorySlotRecord {public bool Locked,Reserved;public string ItemValueSerialization,MetadataOrCustomData;public int ItemCount;}
class Inventory {public uint InventoryRevision;public RebirthNpcInventorySlotRecord[] SlotRecords=new[]{new RebirthNpcInventorySlotRecord()};public string ContentChecksum;}
class RebirthNpcPersistentRecord {public Inventory Inventory;public uint AggregateRevision=1;}
class RebirthNpcPersistentRecordView {public uint AggregateRevision;}
class RebirthDogPersistentRecordView {}
static class RebirthNpcAggregatePersistenceStore {public static RebirthNpcPersistentRecord Record;public static int Published;public static bool Reject;public static bool TryMutateExisting(RebirthNpcStableId id,uint revision,Func<RebirthNpcPersistentRecord,bool> f){if(Reject||Record.AggregateRevision!=revision)return false;if(!f(Record))return false;Record.AggregateRevision++;Published++;return true;}}
static class RebirthDogStateService {public static int Normalized;public static bool TryGetView(RebirthNpcStableId id,out RebirthNpcPersistentRecordView r,out RebirthDogPersistentRecordView d){r=new RebirthNpcPersistentRecordView {AggregateRevision=RebirthNpcAggregatePersistenceStore.Record.AggregateRevision};d=new RebirthDogPersistentRecordView();return true;}public static bool IsDog(RebirthNpcPersistentRecord r){return true;}public static void EnsureInventoryRecord(RebirthNpcPersistentRecord r){Normalized++;if(r.Inventory==null)r.Inventory=new Inventory {InventoryRevision=1};}}
class Subject {public const int Capacity=1;public static int Changes;static string SerializeItemValue(ItemValue v){return "item";}static string ComputeChecksum(RebirthNpcInventorySlotRecord[] s){return "sum";}static void Invalidate(RebirthNpcStableId id,string why){Changes++;}static void SynchronizeActiveInventoryEffects(RebirthNpcStableId id){}
// COMMIT
}
class Check {static void Main(){var r=new RebirthNpcPersistentRecord();RebirthNpcAggregatePersistenceStore.Record=r;string e;var items=new[]{new ItemStack {count=3}};if(!Subject.CommitWorkingSlots(new RebirthNpcStableId(),0,items,null,out e)||r.Inventory.InventoryRevision!=2)throw new Exception("first initialization");int n=RebirthDogStateService.Normalized;int published=RebirthNpcAggregatePersistenceStore.Published;if(Subject.CommitWorkingSlots(new RebirthNpcStableId(),0,new[]{new ItemStack {count=9}},null,out e)||r.Inventory.SlotRecords[0].ItemCount!=3||RebirthDogStateService.Normalized!=n)throw new Exception("stale zero overwrite");if(RebirthNpcAggregatePersistenceStore.Published!=published)throw new Exception("rejected commit published");if(!Subject.CommitWorkingSlots(new RebirthNpcStableId(),2,items,null,out e))throw new Exception("matching revision");if(Subject.CommitWorkingSlots(new RebirthNpcStableId(),2,items,null,out e))throw new Exception("stale nonzero");r.Inventory.InventoryRevision=0;if(!Subject.CommitWorkingSlots(new RebirthNpcStableId(),0,items,null,out e)||r.Inventory.InventoryRevision!=1)throw new Exception("real zero revision");RebirthNpcAggregatePersistenceStore.Reject=true;published=Subject.Changes;if(Subject.CommitWorkingSlots(new RebirthNpcStableId(),1,items,null,out e)||Subject.Changes!=published||string.IsNullOrEmpty(e))throw new Exception("aggregate conflict reported success");Console.WriteLine("PASS initialization, exact revisions, rejection without publication, aggregate conflict without effects");}}
