#requires -Version 7.0
$ErrorActionPreference='Stop'
$root=Split-Path -Parent (Split-Path -Parent $PSScriptRoot)
$source=[IO.File]::ReadAllText((Join-Path $root 'Scripts/Crafting/UI/RebirthStationRefundBackpackPlan.cs'))
$fixture=@"
public class ItemClass{public int MaxCount=100;}public class ItemValue{public int type=1;public string Data="exact";public ItemClass ItemClass=new ItemClass();public ItemValue Clone(){return new ItemValue{type=type,Data=Data,ItemClass=ItemClass};}}public class XUiC_ItemStack{public enum StackLocationTypes{Backpack}}public class ItemStack{public static ItemStack Empty=new ItemStack(new ItemValue{type=0,Data="empty"},0);public ItemValue itemValue;public int count;public ItemStack(ItemValue v,int n){itemValue=v;count=n;}public ItemStack Clone(){return new ItemStack(itemValue.Clone(),count);}public bool IsEmpty(){return count==0||itemValue.type==0;}public bool CanMoveTo(XUiC_ItemStack.StackLocationTypes l){return true;}public bool CanStackPartlyWith(ItemStack s,out int available){available=Math.Max(0,itemValue.ItemClass.MaxCount-count);return itemValue.Data==s.itemValue.Data;}}public static class RebirthNativeItemCodec{public static string Encode(ItemValue v){return v.type+":"+v.Data;}public static bool TryDecode(string data,out ItemValue v){v=null;int split=data==null?-1:data.IndexOf(':');int type;if(split<0||!int.TryParse(data.Substring(0,split),out type))return false;if(type==0)return false;v=new ItemValue{type=type,Data=data.Substring(split+1)};return true;}}public static class RebirthStationGridIngredients{public static bool IsSameStackSnapshot(ItemStack a,ItemStack b){return a!=null&&b!=null&&a.itemValue!=null&&b.itemValue!=null&&a.count==b.count&&RebirthNativeItemCodec.Encode(a.itemValue)==RebirthNativeItemCodec.Encode(b.itemValue);}}public class RebirthStationCancellationRefund{public ItemStack[] Items;public ItemStack[] CopyRefunds(){return Array.ConvertAll(Items,s=>s.Clone());}}
public static class RefundPlanFixture{static int checks;static void Check(bool b){checks++;if(!b)throw new Exception("refund plan "+checks);}static ItemStack Stack(int n,string data="exact"){return n==0?ItemStack.Empty.Clone():new ItemStack(new ItemValue{Data=data},n);}public static string Run(){var live=new[]{Stack(90),Stack(0),Stack(0)};var refund=new RebirthStationCancellationRefund{Items=new[]{Stack(110)}};RebirthStationRefundBackpackPlan plan;Check(RebirthStationRefundBackpackPlan.TryCreate(live,2,null,refund,out plan));var after=plan.CopyAfter();Check(after[0].count==100&&after[1].count==100&&after[2].count==0&&live[0].count==90&&live[1].count==0);Check(plan.MatchesBefore(live,2,null));Check(plan.MatchesAfter(after));Check(!plan.MatchesAfter(live));Check(!plan.MatchesAfter(null));Check(!plan.MatchesAfter(new[]{Stack(100),Stack(100)}));after[2].itemValue.Data="foreign-slot";Check(!plan.MatchesAfter(after));after=plan.CopyAfter();after[0].itemValue.Data="changed-payload";Check(!plan.MatchesAfter(after));after=plan.CopyAfter();after[0].count=1;Check(!plan.MatchesAfter(after));Check(plan.CopyAfter()[0].count==100);live[0].itemValue.Data="changed";Check(!plan.MatchesBefore(live,2,null));live[0].itemValue.Data="exact";Check(!plan.MatchesBefore(live,1,null)&&!plan.MatchesBefore(live,2,i=>i==0));
refund.Items=new[]{Stack(111)};Check(!RebirthStationRefundBackpackPlan.TryCreate(live,2,null,refund,out plan)&&plan==null&&live[0].count==90);refund.Items=new[]{Stack(110)};Check(!RebirthStationRefundBackpackPlan.TryCreate(live,3,i=>i==1||i==2,refund,out plan));refund.Items=new[]{Stack(10,"different")};Check(RebirthStationRefundBackpackPlan.TryCreate(live,2,null,refund,out plan)&&plan.CopyAfter()[0].count==90&&plan.CopyAfter()[1].itemValue.Data=="different");refund.Items=new[]{Stack(10),Stack(100,"different")};Check(RebirthStationRefundBackpackPlan.TryCreate(live,2,null,refund,out plan)&&plan.CopyAfter()[0].count==100&&plan.CopyAfter()[1].count==100);refund.Items=new[]{Stack(11),Stack(100,"different")};Check(!RebirthStationRefundBackpackPlan.TryCreate(live,2,null,refund,out plan));Check(!RebirthStationRefundBackpackPlan.TryCreate(new ItemStack[]{null},1,null,refund,out plan));live=new[]{Stack(90),Stack(0),Stack(0)};refund.Items=new[]{Stack(110)};Check(RebirthStationRefundBackpackPlan.TryCreate(live,2,null,refund,out plan));var node=plan.Write();RebirthStationRefundBackpackPlan parsed;Check(RebirthStationRefundBackpackPlan.TryRead(node,refund,out parsed)&&parsed.MatchesBefore(live,2,null)&&parsed.CopyAfter()[1].count==100);node.Elements().First().SetAttributeValue("afterCount",101);Check(!RebirthStationRefundBackpackPlan.TryRead(node,refund,out parsed));node=plan.Write();node.Elements().Last().SetAttributeValue("afterCount",1);Check(!RebirthStationRefundBackpackPlan.TryRead(node,refund,out parsed));node=plan.Write();node.Elements().First().SetAttributeValue("locked","1");Check(!RebirthStationRefundBackpackPlan.TryRead(node,refund,out parsed));node=plan.Write();node.SetAttributeValue("extra",1);Check(!RebirthStationRefundBackpackPlan.TryRead(node,refund,out parsed));node=plan.Write();node.Elements().First().SetAttributeValue("after","invalid-codec");Check(!RebirthStationRefundBackpackPlan.TryRead(node,refund,out parsed));node=plan.Write();node.Elements().First().SetAttributeValue("beforeCount",-1);Check(!RebirthStationRefundBackpackPlan.TryRead(node,refund,out parsed));node=plan.Write();node.Elements().Last().SetAttributeValue("locked","1");Check(!RebirthStationRefundBackpackPlan.TryRead(node,refund,out parsed));refund.Items=new[]{Stack(109)};Check(!RebirthStationRefundBackpackPlan.TryRead(plan.Write(),refund,out parsed));
return "PASS "+checks+" actual detached refund backpack planner with item/codec/capacity/refund doubles; no delivery";}}
"@
Add-Type -TypeDefinition ($source+$fixture)
[RefundPlanFixture]::Run()