using System;using System.IO;using System.Collections.Generic;
// Actual original-character save binding; native world/identity/cache/disk adapters doubled.
class World{public EntityPlayer Player;public bool IsRemote(){return false;}public object GetEntity(int id){return Player;}}
class EntityPlayer{public World world;public int entityId=1;}
class GameManager{public static GameManager Instance=new GameManager();public World World;}
class GameIO{public static string Root="fixture-save";public static string GetSaveGameDir(){return Root;}}
class Origin{public string CreationId;}
class Progression{public Dictionary<string,float>LiteratureStudyProgress=new Dictionary<string,float>();}
class RebirthWorldCharacterRecord{public bool IsComplete=true;public string StablePlayerKey="owner",StablePlayerId="canonical";public Origin Origin=new Origin();public Progression Progression=new Progression();public void Touch(string reason){}}
class RebirthStablePlayerIdentity{public string StorageKey="owner",CanonicalId="canonical";public static void ResetRuntimeCache(){}}
static class RebirthWorldCharacterService{public static RebirthWorldCharacterRecord Record;public static bool TryGet(EntityPlayer p,out RebirthWorldCharacterRecord r){r=Record;return r!=null;}public static bool TryGetIdentity(EntityPlayer p,out RebirthStablePlayerIdentity i){i=new RebirthStablePlayerIdentity();return true;}}
static class RebirthWorldCharacterRepository{public static bool IsServerAuthority=true,Save=true,Throw;public static int Saves;public static int Resets;public static void Reset(bool ignored){Resets++;RebirthWorldCharacterService.Record=null;}public static bool IsCurrentCachedRecord(RebirthWorldCharacterRecord r){return ReferenceEquals(r,RebirthWorldCharacterService.Record);}public static bool SaveIfDirty(RebirthStablePlayerIdentity i,string reason){Saves++;if(Throw)throw new Exception("disk failure");return Save;}}
class Session{public RebirthStudySessionSaveBinding SaveBinding;public float Progress;public bool CompletedAwaitingSave;}
static class RebirthLiteratureStudySessionService{public static Dictionary<int,Session> Active=new Dictionary<int,Session>();
// READING_CHECKPOINT
}
static class RebirthAudiobookListeningSessionService{public static Dictionary<int,Session> Active=new Dictionary<int,Session>();
// AUDIO_CHECKPOINT
}
static class RebirthMetabolismStateRepository{public static void Reset(bool ignored){}}
class Lifecycle{public static bool Flushed;static void FlushAll(string reason){var p=RebirthWorldCharacterService.Record.Progression.LiteratureStudyProgress;if(p["book"]!=.77f||p["audioBook"]!=.88f)throw new Exception("reset/flush preceded latest study checkpoints");Flushed=true;}
// LIFECYCLE
public static void Run(){FlushAndReset("test-shutdown");}}
// SCOPE
// SOURCE
class Checks{static void A(bool b,string label){if(!b)throw new Exception(label);}static void Main(){var p=new EntityPlayer();var w=new World{Player=p};p.world=w;GameManager.Instance.World=w;var r=new RebirthWorldCharacterRecord{Origin=new Origin{CreationId=Guid.NewGuid().ToString("N")}};RebirthWorldCharacterService.Record=r;
A(RebirthStudySessionSaveBinding.TryCapture(p,r,"title",out var binding),"authenticated current binding captured");w.Player=null;A(binding.TrySave(.47f,false)&&r.Progression.LiteratureStudyProgress["title"]==.47f,"missing native entity still saves original fraction");RebirthWorldCharacterRepository.Save=false;A(!binding.TrySave(.61f,false)&&r.Progression.LiteratureStudyProgress["title"]==.61f,"failed disconnected save retains dirty latest fraction");RebirthWorldCharacterRepository.Throw=true;A(!binding.TrySave(.61f,false),"disconnected exception contained");RebirthWorldCharacterRepository.Throw=false;RebirthWorldCharacterRepository.Save=true;r.Progression.LiteratureStudyProgress.Remove("title");A(binding.TrySave(1f,true)&&!r.Progression.LiteratureStudyProgress.ContainsKey("title"),"completed disconnected checkpoint does not recreate progress");int saves=RebirthWorldCharacterRepository.Saves;string creation=r.Origin.CreationId;r.Origin.CreationId=Guid.NewGuid().ToString("N");A(!binding.TrySave(.9f,false)&&RebirthWorldCharacterRepository.Saves==saves,"changed character refused");r.Origin.CreationId=creation;RebirthWorldCharacterService.Record=new RebirthWorldCharacterRecord();A(!binding.TrySave(.9f,false),"replaced cached record refused");RebirthWorldCharacterService.Record=r;GameIO.Root="other-save";A(!binding.TrySave(.9f,false),"save root change refused");GameIO.Root="fixture-save";GameManager.Instance.World=new World();A(!binding.TrySave(.9f,false),"replacement world refused");GameManager.Instance.World=w;A(!binding.TrySave(float.NaN,false)&&!binding.TrySave(float.PositiveInfinity,false),"nonfinite progress refused");A(!RebirthStudySessionSaveBinding.TryCapture(p,r,"title",out var invalid),"capture requires original live entity");w.Player=p;RebirthWorldCharacterService.Record=r;r.Progression.LiteratureStudyProgress.Clear();RebirthStudySessionSaveBinding readingBinding=null,audioBinding=null;A(RebirthStudySessionSaveBinding.TryCapture(p,r,"book",out readingBinding)&&RebirthStudySessionSaveBinding.TryCapture(p,r,"audioBook",out audioBinding),"shutdown session captures");
RebirthLiteratureStudySessionService.Active[1]=new Session{SaveBinding=readingBinding,Progress=.77f};RebirthAudiobookListeningSessionService.Active[1]=new Session{SaveBinding=audioBinding,Progress=.88f};w.Player=null;Lifecycle.Run();A(Lifecycle.Flushed&&RebirthWorldCharacterRepository.Resets==1&&RebirthWorldCharacterService.Record==null,"actual lifecycle checkpoints both missing-entity sessions before flush/reset");
A(RebirthLiteratureStudySessionService.CheckpointForShutdown()==1&&RebirthAudiobookListeningSessionService.CheckpointForShutdown()==1,"stale shutdown binding refused after cache reset");Console.WriteLine("PASS3 actual lifecycle shutdown assertions: both checkpoints before flush/reset, missing native entity and stale cache refusal; native repository/adapters doubled.");Console.WriteLine("PASS11 actual disconnected-session binding assertions: original identity/fraction, failed/throwing save, completion, changed character/cache/root/world, finite progress and capture ownership; native persistence adapters doubled. No real save/reconnect proof.");}}