using System;using System.IO;using System.Collections.Generic;
class World {}
static class Mathf {public static float Clamp(float v,float a,float b){return Math.Max(a,Math.Min(b,v));}public static int Clamp(int v,int a,int b){return Math.Max(a,Math.Min(b,v));}public static float Clamp01(float v){return Clamp(v,0,1);}public static float Max(float a,float b){return Math.Max(a,b);}}
class ItemClass {public int Id;public string GetItemName(){return Id==1?"part":"other";}public static ItemClass GetItemClass(string name,bool flag){return name=="part"?new ItemClass{Id=1}:null;}}
class ItemValue {public ushort Quality=1;public float UseTimes;public float MaxUseTimes=100;public string Extra;public bool HasRoll=true;public int Roll=500000;public ItemClass ItemClass;public ItemValue(int id){ItemClass=new ItemClass{Id=id};}public bool TryGetMetadata(string key,out int n){n=Roll;return HasRoll;}}
class ItemStack {public ItemValue itemValue;public int count;public ItemStack(ItemValue v,int n){itemValue=v;count=n;}public static ItemStack Empty=new ItemStack(null,0);public ItemStack Clone(){return new ItemStack(itemValue,count);}}
static class RebirthNativeItemCodec {static Dictionary<string,ItemValue> values=new Dictionary<string,ItemValue>();public static string Encode(ItemValue value){string key=value.ItemClass.GetItemName()+"|"+value.Quality+"|"+value.UseTimes+"|"+value.Extra+"|"+value.HasRoll;values[key]=value;return key;}public static bool TryDecode(string data,out ItemValue value){return values.TryGetValue(data,out value);}}
static class RebirthVehiclePartMetadata {public const string RollKey="roll";public static float ReadOrCreateRoll(ItemValue v,World w){return v.Roll/1000000f;}public static void WriteRoll(ItemValue v,float roll){v.Roll=(int)(roll*1000000);}}
// METHODS
static void Main(){var original=new ItemValue(1){Quality=5,UseTimes=14,Extra="seed/mods/textures/metadata"};var part=FromItemValue(original,null);var returned=CreateItemStack(part);if(returned.count!=1||returned.itemValue.Extra!=original.Extra||returned.itemValue.Quality!=5||returned.itemValue.UseTimes!=14)throw new Exception("Payload lost");var offered=part.Clone();offered.Quality=1;offered.UseTimes=0;var sanitized=SanitizeOfferedPart(offered,"part");if(sanitized.Quality!=5||sanitized.UseTimes!=14||sanitized.SerializedItemValue!=part.SerializedItemValue)throw new Exception("Did not derive from payload");
offered.SerializedItemValue="bad";if(SanitizeOfferedPart(offered,"part")!=null)throw new Exception("Malformed accepted");bool rejected=false;try{CreateItemStack(offered);}catch(InvalidDataException){rejected=true;}if(!rejected)throw new Exception("Malformed downgraded");offered.SerializedItemValue=RebirthNativeItemCodec.Encode(new ItemValue(2));if(SanitizeOfferedPart(offered,"part")!=null)throw new Exception("Wrong item accepted");offered.SerializedItemValue=RebirthNativeItemCodec.Encode(new ItemValue(1){HasRoll=false});if(SanitizeOfferedPart(offered,"part")!=null)throw new Exception("Missing roll accepted");var legacy=CreateItemStack(new RebirthInstalledVehiclePart{ItemName="part",Quality=4,UseTimes=8,Roll=.25f});if(legacy.itemValue.Quality!=4||legacy.itemValue.UseTimes!=8||legacy.itemValue.Roll!=250000)throw new Exception("Legacy failed");Console.WriteLine("PASS: actual capture/restore/sanitize preserve codec payload, derive offered scalars from it, reject invalid/wrong-item/missing-roll data, and preserve legacy reconstruction. Native ItemValue/codec substituted; engine roundtrip pending.");}}
