using System.Xml;
using System.Globalization;
using System.Linq;using System.Xml.Linq;
using System;using System.IO;using System.Text;using System.Collections.Generic;
static class Mathf {public static float Clamp01(float v){return Math.Max(0,Math.Min(1,v));}}
public class RebirthVehiclePerformanceSnapshot {}
static class RebirthVehiclePerformanceCompiler {public static RebirthVehiclePerformanceSnapshot Compile(RebirthVehicleAssembly a){return null;}}
public class ItemValue { public ItemClass ItemClass=new ItemClass(); public ItemValue(){} public ItemValue(int id){} }
public class ItemClass {public int Id=1;public string Name="ammoGasCan";public string GetItemName(){return Name;}public static ItemClass GetItemClass(string name,bool unused){return name=="ammoGasCan"?new ItemClass():null;}}
static class RebirthNativeItemCodec { public static string Encode(ItemValue value){return "full-native-item";} public static bool TryDecode(string data,out ItemValue value){value=data=="repair-kit"?new ItemValue{ItemClass=new ItemClass{Name="resourceRepairKit"}}:data=="full-native-item"?new ItemValue():null;return value!=null;} }
struct Vector3i {public int x,y,z;public Vector3i(int a,int b,int c){x=a;y=b;z=c;}}
class TileEntityRepairableVehicleRebirth {public RebirthVehicleAssembly Assembly;}
static class RebirthVehicleAssemblyIndex {
public static readonly Dictionary<Vector3i,TileEntityRepairableVehicleRebirth> Blocks=new Dictionary<Vector3i,TileEntityRepairableVehicleRebirth>();
public static readonly Dictionary<int,RebirthVehicleAssembly> Entities=new Dictionary<int,RebirthVehicleAssembly>();
static readonly object Sync=new object();
// INDEX METHOD
}
public class ItemStack {public ItemValue itemValue=new ItemValue();public int count=1;public bool IsEmpty(){return count<=0;}}
static class RebirthVehicleDefinitionRegistry {public static RebirthVehicleFamilyDefinition GetFamily(string id){return id=="bike"?new RebirthVehicleFamilyDefinition("bike","bike",new[]{new RebirthVehicleSlotDefinition("Engine","part","engine",true,1f)}):null;}}
static class RebirthVehicleInventoryTransactions {
public static RebirthInstalledVehiclePart SanitizeOfferedPart(RebirthInstalledVehiclePart p,string name){return p.ItemName==name?p.Clone():null;}
public static ItemStack CreateItemStack(RebirthInstalledVehiclePart p){return p.ItemName=="part"?new ItemStack():null;}
}
public class EntityPlayer {}
static class RebirthServiceCraftSkillService {public static int Amount=2500;public static int AdjustVehicleRepairAmount(EntityPlayer p,int original){if(original!=2500)throw new Exception("Changed repair baseline");return Amount;}}
// METHODS
class Check {
static void RejectMalformed(string slot, bool duplicate) {
 using(var m=new MemoryStream()) {
 var w=new BinaryWriter(m); w.Write(0x52564241);w.Write(3);w.Write(Guid.NewGuid().ToByteArray());w.Write("c");w.Write("f");w.Write(0L);w.Write(.5f);w.Write(duplicate?2:1);
 for(int i=0;i<(duplicate?2:1);i++){w.Write(slot);w.Write("part");w.Write(1);w.Write(0f);w.Write(.5f);w.Write("");}
 w.Flush();bool rejected=false;try{RebirthVehicleAssemblySerializer.FromBase64(Convert.ToBase64String(m.ToArray()));}catch(InvalidDataException){rejected=true;}if(!rejected)throw new Exception("Malformed slot accepted");
 }
}
static void Main(){
var beforePlan=new RebirthVehicleAssembly{AssemblyId=Guid.NewGuid(),ContentId="bike",FamilyId="bike",Revision=3};var planId=Guid.NewGuid();var afterPlan=beforePlan.DeepClone();afterPlan.Revision++;afterPlan.LastAppliedInventoryTransferId=planId;
var plan=RebirthVehicleTransferPlan.Create(planId,Guid.NewGuid(),"owner","fingerprint",beforePlan,afterPlan);beforePlan.Revision=100;afterPlan.Revision=101;if(plan.ReadBefore().Revision!=3||plan.ReadAfter().Revision!=4)throw new Exception("Plan aliases input");string migrated="legacy-"+new string('a',64);
var migratedPlan=RebirthVehicleTransferPlan.Create(planId,migrated,"owner","legacy",plan.ReadBefore(),plan.ReadAfter());
if(RebirthVehicleTransferPlan.Read(migratedPlan.ToXml()).CreationId!=migrated)throw new Exception("Migrated plan identity lost");
var invalidIdentity=migratedPlan.ToXml();invalidIdentity.SetAttributeValue("creationId","legacy-"+new string('A',64));bool identityRejected=false;try{RebirthVehicleTransferPlan.Read(invalidIdentity);}catch(InvalidDataException){identityRejected=true;}if(!identityRejected)throw new Exception("Noncanonical legacy accepted");
var returned=plan.ReadAfter();returned.Revision=100;if(plan.ReadAfter().Revision!=4)throw new Exception("Plan aliases output");
var debit=new RebirthVehicleTransferItem(Guid.NewGuid(),true,"full-native-item",2,RebirthVehiclePartSourceLocation.Backpack,3);
var credit=new RebirthVehicleTransferItem(Guid.NewGuid(),false,"full-native-item",1,RebirthVehiclePartSourceLocation.None,-1);
var inputItems=new[]{debit,credit};plan=RebirthVehicleTransferPlan.Create(planId,plan.CreationId,"owner","fingerprint",plan.ReadBefore(),plan.ReadAfter(),inputItems);inputItems[0]=credit;
var itemsReloaded=RebirthVehicleTransferPlan.Read(plan.ToXml());if(itemsReloaded.Items.Count!=2||itemsReloaded.Items[0].ReceiptId!=debit.ReceiptId||itemsReloaded.Items[0].Count!=2||itemsReloaded.Items[0].Slot!=3||itemsReloaded.Items[1].Debit)throw new Exception("Item custody changed");
bool duplicateReceipt=false;try{RebirthVehicleTransferPlan.Create(planId,plan.CreationId,"owner","fingerprint",plan.ReadBefore(),plan.ReadAfter(),new[]{debit,debit});}catch(InvalidDataException){duplicateReceipt=true;}if(!duplicateReceipt)throw new Exception("Duplicate receipt accepted");
bool badItem=false;try{new RebirthVehicleTransferItem(Guid.NewGuid(),true,"invalid",1,RebirthVehiclePartSourceLocation.Backpack,0);}catch(InvalidDataException){badItem=true;}if(!badItem)throw new Exception("Bad item payload accepted");
bool badCredit=false;try{new RebirthVehicleTransferItem(Guid.NewGuid(),false,"full-native-item",1,RebirthVehiclePartSourceLocation.Backpack,0);}catch(InvalidDataException){badCredit=true;}if(!badCredit)throw new Exception("Credit source accepted");
var legacyPlan=plan.ToXml();legacyPlan.SetAttributeValue("version",1);legacyPlan.Element("inventory").Remove();if(RebirthVehicleTransferPlan.Read(legacyPlan).Items.Count!=0)throw new Exception("Legacy plan failed");
var blockTarget=new RebirthVehicleTransferTarget(RebirthVehicleAssemblyCarrier.RepairableBlock,-12,45,900);
var targetedPlan=RebirthVehicleTransferPlan.Create(planId,plan.CreationId,"owner","fingerprint",plan.ReadBefore(),plan.ReadAfter(),plan.Items,blockTarget);var targetReload=RebirthVehicleTransferPlan.Read(targetedPlan.ToXml());if((string)targetedPlan.ToXml().Attribute("version")!="3"||targetReload.Target.Carrier!=RebirthVehicleAssemblyCarrier.RepairableBlock||targetReload.Target.X!=-12||targetReload.Target.Y!=45||targetReload.Target.Z!=900)throw new Exception("Block recovery target lost");
var entityTarget=new RebirthVehicleTransferTarget(RebirthVehicleAssemblyCarrier.VehicleEntity);var entityPlan=RebirthVehicleTransferPlan.Create(planId,plan.CreationId,"owner","fingerprint",plan.ReadBefore(),plan.ReadAfter(),plan.Items,entityTarget);if(RebirthVehicleTransferPlan.Read(entityPlan.ToXml()).Target.Carrier!=RebirthVehicleAssemblyCarrier.VehicleEntity)throw new Exception("Entity recovery target lost");
if(RebirthVehicleTransferPlan.Read(plan.ToXml()).Target!=null||RebirthVehicleTransferPlan.Read(legacyPlan).Target!=null)throw new Exception("Legacy target invented");
var missingTarget=targetedPlan.ToXml();missingTarget.Element("target").Remove();bool targetMissing=false;try{RebirthVehicleTransferPlan.Read(missingTarget);}catch(InvalidDataException){targetMissing=true;}if(!targetMissing)throw new Exception("Targeted plan missing target accepted");
var badTarget=entityPlan.ToXml();badTarget.Element("target").SetAttributeValue("x",1);bool entityCoordinate=false;try{RebirthVehicleTransferPlan.Read(badTarget);}catch(InvalidDataException){entityCoordinate=true;}if(!entityCoordinate)throw new Exception("Entity coordinates accepted");
var invalidCarrier=targetedPlan.ToXml();invalidCarrier.Element("target").SetAttributeValue("carrier",255);bool carrierRejected=false;try{RebirthVehicleTransferPlan.Read(invalidCarrier);}catch(InvalidDataException){carrierRejected=true;}if(!carrierRejected)throw new Exception("Unknown carrier accepted");
Vector3i resolvedPosition;int resolvedEntity;RebirthVehicleAssembly resolvedSnapshot;
if(RebirthVehicleAssemblyIndex.TryLocateTransferTarget(blockTarget,plan.ReadBefore().AssemblyId,out resolvedPosition,out resolvedEntity,out resolvedSnapshot)||resolvedSnapshot!=null||resolvedEntity!=-1)throw new Exception("Missing target resolved");
var blockAssembly=plan.ReadBefore();RebirthVehicleAssemblyIndex.Blocks[new Vector3i(-12,45,900)]=new TileEntityRepairableVehicleRebirth{Assembly=blockAssembly};
if(!RebirthVehicleAssemblyIndex.TryLocateTransferTarget(blockTarget,blockAssembly.AssemblyId,out resolvedPosition,out resolvedEntity,out resolvedSnapshot)||resolvedPosition.x!=-12||resolvedEntity!=-1)throw new Exception("Block target not resolved");resolvedSnapshot.Revision=999;if(blockAssembly.Revision==999)throw new Exception("Resolver aliases live assembly");
if(RebirthVehicleAssemblyIndex.TryLocateTransferTarget(new RebirthVehicleTransferTarget(RebirthVehicleAssemblyCarrier.RepairableBlock,1,2,3),blockAssembly.AssemblyId,out resolvedPosition,out resolvedEntity,out resolvedSnapshot))throw new Exception("Wrong block location resolved");
RebirthVehicleAssemblyIndex.Entities[77]=blockAssembly.DeepClone();if(RebirthVehicleAssemblyIndex.TryLocateTransferTarget(blockTarget,blockAssembly.AssemblyId,out resolvedPosition,out resolvedEntity,out resolvedSnapshot)||RebirthVehicleAssemblyIndex.TryLocateTransferTarget(entityTarget,blockAssembly.AssemblyId,out resolvedPosition,out resolvedEntity,out resolvedSnapshot))throw new Exception("Cross-carrier duplicate resolved");
RebirthVehicleAssemblyIndex.Blocks.Clear();if(!RebirthVehicleAssemblyIndex.TryLocateTransferTarget(entityTarget,blockAssembly.AssemblyId,out resolvedPosition,out resolvedEntity,out resolvedSnapshot)||resolvedEntity!=77)throw new Exception("Stable entity target not resolved");RebirthVehicleAssemblyIndex.Entities[99]=blockAssembly.DeepClone();if(RebirthVehicleAssemblyIndex.TryLocateTransferTarget(entityTarget,blockAssembly.AssemblyId,out resolvedPosition,out resolvedEntity,out resolvedSnapshot))throw new Exception("Duplicate entity resolved");RebirthVehicleAssemblyIndex.Entities.Remove(77);if(!RebirthVehicleAssemblyIndex.TryLocateTransferTarget(entityTarget,blockAssembly.AssemblyId,out resolvedPosition,out resolvedEntity,out resolvedSnapshot)||resolvedEntity!=99)throw new Exception("Reload entity identity not resolved");RebirthVehicleAssemblyIndex.Entities.Clear();
var partBefore=plan.ReadBefore();var offered=new RebirthInstalledVehiclePart{ItemName="part",SerializedItemValue="full-native-item",Quality=4};
var installPlan=RebirthVehicleTransferPlanner.PartChange(Guid.NewGuid(),plan.CreationId,"owner","install",blockTarget,partBefore,partBefore.Revision,RebirthVehicleAssemblyAction.Install,"Engine",offered,RebirthVehiclePartSourceLocation.Toolbelt,2);
if(partBefore.Parts.Count!=0||installPlan.Items.Count!=1||!installPlan.Items[0].Debit||installPlan.Items[0].Source!=RebirthVehiclePartSourceLocation.Toolbelt||installPlan.ReadAfter().Parts["Engine"].SerializedItemValue!="full-native-item")throw new Exception("Install custody incorrect");
partBefore.Parts["Engine"]=offered.Clone();var replacement=RebirthVehicleTransferPlanner.PartChange(Guid.NewGuid(),plan.CreationId,"owner","replace",entityTarget,partBefore,partBefore.Revision,RebirthVehicleAssemblyAction.Replace,"Engine",offered,RebirthVehiclePartSourceLocation.Backpack,3);if(replacement.Items.Count!=2||!replacement.Items[0].Debit||replacement.Items[1].Debit||replacement.Items[0].ReceiptId==replacement.Items[1].ReceiptId)throw new Exception("Replacement legs lost");
var pickup=RebirthVehicleTransferPlanner.PartChange(Guid.NewGuid(),plan.CreationId,"owner","pickup",blockTarget,partBefore,partBefore.Revision,RebirthVehicleAssemblyAction.Pickup,"Engine",null,RebirthVehiclePartSourceLocation.None,-1);if(pickup.Items.Count!=1||pickup.Items[0].Debit||pickup.ReadAfter().Parts.Count!=0||partBefore.Parts.Count!=1)throw new Exception("Pickup custody incorrect");
bool cursorRejected=false;try{RebirthVehicleTransferPlanner.PartChange(Guid.NewGuid(),plan.CreationId,"owner","cursor",blockTarget,partBefore,partBefore.Revision,RebirthVehicleAssemblyAction.Install,"Engine",offered,RebirthVehiclePartSourceLocation.None,-1);}catch(InvalidDataException){cursorRejected=true;}if(!cursorRejected)throw new Exception("Cursor offer accepted as ownership");
bool stalePart=false;try{RebirthVehicleTransferPlanner.PartChange(Guid.NewGuid(),plan.CreationId,"owner","stale",blockTarget,partBefore,partBefore.Revision-1,RebirthVehicleAssemblyAction.Remove,"Engine",null,RebirthVehiclePartSourceLocation.None,-1);}catch(InvalidDataException){stalePart=true;}if(!stalePart)throw new Exception("Stale part plan accepted");
var fuelBefore=plan.ReadBefore();fuelBefore.FuelPercent=.5f;var fuelAfter=plan.ReadAfter();fuelAfter.FuelPercent=0f;var fuelPlan=RebirthVehicleTransferPlan.Create(planId,plan.CreationId,"owner","siphon",fuelBefore,fuelAfter,new[]{credit},entityTarget,new RebirthVehicleTransferFuel(20f,0f,40f));var fuelReload=RebirthVehicleTransferPlan.Read(fuelPlan.ToXml());if((string)fuelPlan.ToXml().Attribute("version")!="4"||fuelReload.Fuel.BeforeLevel!=20f||fuelReload.Fuel.Capacity!=40f||fuelReload.Fuel.AfterLevel!=0f)throw new Exception("Fuel persistence lost");
bool badFuel=false;try{new RebirthVehicleTransferFuel(float.NaN,0f,40f);}catch(InvalidDataException){badFuel=true;}if(!badFuel)throw new Exception("Nonfinite fuel accepted");bool mismatchedFuel=false;try{RebirthVehicleTransferPlan.Create(planId,plan.CreationId,"owner","bad fuel",plan.ReadBefore(),fuelAfter,new[]{credit},entityTarget,new RebirthVehicleTransferFuel(20f,0f,40f));}catch(InvalidDataException){mismatchedFuel=true;}if(!mismatchedFuel)throw new Exception("Fuel snapshot mismatch accepted");
Guid fuelNext;var fuelReceipts=new Dictionary<Guid,RebirthVehicleOwnerTransferResult>{{credit.ReceiptId,RebirthVehicleOwnerTransferResult.Pending}};if(RebirthVehicleTransferRecovery.Next(fuelPlan,fuelAfter,fuelReceipts,true,out fuelNext)!=RebirthVehicleTransferStep.WaitForEvidence)throw new Exception("Fuel credit without native evidence");if(RebirthVehicleTransferRecovery.Next(fuelPlan,fuelAfter,fuelReceipts,true,out fuelNext,20f,40f)!=RebirthVehicleTransferStep.Reconcile)throw new Exception("Unsiphoned native fuel ignored");if(RebirthVehicleTransferRecovery.Next(fuelPlan,fuelAfter,fuelReceipts,true,out fuelNext,0f,40f)!=RebirthVehicleTransferStep.ApplyCredit)throw new Exception("Fuel credit evidence ignored");
var siphonBefore=plan.ReadBefore();siphonBefore.FuelPercent=.5f;var blockSiphon=RebirthVehicleTransferPlanner.Siphon(Guid.NewGuid(),plan.CreationId,"owner","block siphon",blockTarget,siphonBefore,siphonBefore.Revision);if(blockSiphon.Items.Count!=1||blockSiphon.Items[0].Debit||blockSiphon.Items[0].Count!=250||blockSiphon.ReadAfter().FuelPercent!=0f||siphonBefore.FuelPercent!=.5f||blockSiphon.Fuel!=null)throw new Exception("Block siphon custody incorrect");
var entitySiphon=RebirthVehicleTransferPlanner.Siphon(Guid.NewGuid(),plan.CreationId,"owner","entity siphon",entityTarget,siphonBefore,siphonBefore.Revision,20f,40f);if(entitySiphon.Items[0].Count!=500||entitySiphon.Fuel.BeforeLevel!=20f||entitySiphon.Fuel.AfterLevel!=0f)throw new Exception("Native tank siphon custody incorrect");
var largeSiphon=RebirthVehicleTransferPlanner.Siphon(Guid.NewGuid(),plan.CreationId,"owner","large tank",entityTarget,siphonBefore,siphonBefore.Revision,200f,400f);if(largeSiphon.Items[0].Count!=5000)throw new Exception("Tank capacity ignored");
bool missingFuel=false;try{RebirthVehicleTransferPlanner.Siphon(Guid.NewGuid(),plan.CreationId,"owner","missing fuel",entityTarget,siphonBefore,siphonBefore.Revision);}catch(InvalidDataException){missingFuel=true;}if(!missingFuel)throw new Exception("Native fuel guessed");
var emptyFuel=siphonBefore.DeepClone();emptyFuel.FuelPercent=0f;bool emptySiphon=false;try{RebirthVehicleTransferPlanner.Siphon(Guid.NewGuid(),plan.CreationId,"owner","empty",blockTarget,emptyFuel,emptyFuel.Revision);}catch(InvalidDataException){emptySiphon=true;}if(!emptySiphon)throw new Exception("Empty fuel credit created");
var refillBefore=plan.ReadBefore();refillBefore.FuelPercent=0f;var gasDebit=new RebirthVehicleTransferItem(Guid.NewGuid(),true,"full-native-item",2500,RebirthVehiclePartSourceLocation.Backpack,0);var refill=RebirthVehicleTransferPlanner.Refuel(Guid.NewGuid(),plan.CreationId,"owner","refill",entityTarget,refillBefore,refillBefore.Revision,"ammoGasCan",0f,400f,new[]{gasDebit});if(refill.Fuel.AfterLevel!=100f||refill.ReadAfter().FuelPercent!=.25f||refill.Items[0].ReceiptId!=gasDebit.ReceiptId||refillBefore.FuelPercent!=0f)throw new Exception("Native refill cap/identity incorrect");
var smallDebit=new RebirthVehicleTransferItem(Guid.NewGuid(),true,"full-native-item",10,RebirthVehiclePartSourceLocation.Toolbelt,1);var smallRefill=RebirthVehicleTransferPlanner.Refuel(Guid.NewGuid(),plan.CreationId,"owner","partial refill",entityTarget,refillBefore,refillBefore.Revision,"ammoGasCan",0f,40f,new[]{smallDebit});if(smallRefill.Fuel.AfterLevel!=.4f)throw new Exception("Partial refill arithmetic incorrect");
bool oversizedRefill=false;try{RebirthVehicleTransferPlanner.Refuel(Guid.NewGuid(),plan.CreationId,"owner","overflow refill",entityTarget,refillBefore,refillBefore.Revision,"ammoGasCan",0f,40f,new[]{gasDebit});}catch(InvalidDataException){oversizedRefill=true;}if(!oversizedRefill)throw new Exception("Overtank debit accepted");
bool mixedRefill=false;try{RebirthVehicleTransferPlanner.Refuel(Guid.NewGuid(),plan.CreationId,"owner","mixed",entityTarget,refillBefore,refillBefore.Revision,"ammoGasCan",0f,400f,new[]{gasDebit,smallDebit});}catch(InvalidDataException){mixedRefill=true;}if(!mixedRefill)throw new Exception("Mixed inventory native policy ignored");
bool wrongFuel=false;try{RebirthVehicleTransferPlanner.Refuel(Guid.NewGuid(),plan.CreationId,"owner","wrong item",entityTarget,refillBefore,refillBefore.Revision,"wrongFuel",0f,40f,new[]{smallDebit});}catch(InvalidDataException){wrongFuel=true;}if(!wrongFuel)throw new Exception("Wrong native fuel accepted");
var fuelBelt=new[]{new ItemStack{count=3},new ItemStack{count=50}};var fuelBag=new[]{new ItemStack{count=100},new ItemStack{count=80}};
var beltSelected=RebirthVehicleFuelSelection.Select(fuelBelt,1,fuelBag,i=>false,"ammoGasCan",20);if(beltSelected.Count!=1||beltSelected[0].Count!=3||beltSelected[0].Source!=RebirthVehiclePartSourceLocation.Toolbelt||fuelBelt[0].count!=3||fuelBag[0].count!=100)throw new Exception("Native partial belt priority broken");
var bagSelected=RebirthVehicleFuelSelection.Select(fuelBelt,0,fuelBag,i=>i==0,"ammoGasCan",90);if(bagSelected.Count!=1||bagSelected[0].Slot!=1||bagSelected[0].Count!=80||bagSelected[0].Source!=RebirthVehiclePartSourceLocation.Backpack)throw new Exception("Locked/owned fuel selection incorrect");
var splitSelected=RebirthVehicleFuelSelection.Select(new ItemStack[0],0,fuelBag,i=>false,"ammoGasCan",150);if(splitSelected.Count!=2||splitSelected[0].Count!=100||splitSelected[1].Count!=50||splitSelected[0].ReceiptId==splitSelected[1].ReceiptId)throw new Exception("Multi-slot fuel selection incorrect");
if(RebirthVehicleFuelSelection.Select(new ItemStack[0],0,fuelBag,i=>true,"ammoGasCan",20).Count!=0||RebirthVehicleFuelSelection.Select(fuelBelt,2,fuelBag,null,"differentItem",20).Count!=0)throw new Exception("Unavailable fuel selection invented");
var repairPlan=RebirthVehicleTransferPlan.Create(planId,plan.CreationId,"owner","repair",plan.ReadBefore(),plan.ReadAfter(),new[]{debit},entityTarget,null,new RebirthVehicleTransferHealth(100,2600,5000));var repairReload=RebirthVehicleTransferPlan.Read(repairPlan.ToXml());if((string)repairPlan.ToXml().Attribute("version")!="5"||repairReload.Health.Before!=100||repairReload.Health.After!=2600||repairReload.Health.Maximum!=5000)throw new Exception("Repair health persistence lost");
var healthReceipts=new Dictionary<Guid,RebirthVehicleOwnerTransferResult>{{debit.ReceiptId,RebirthVehicleOwnerTransferResult.Applied}};Guid healthNext;if(RebirthVehicleTransferRecovery.Next(repairPlan,repairPlan.ReadAfter(),healthReceipts,true,out healthNext)!=RebirthVehicleTransferStep.WaitForEvidence)throw new Exception("Repair completed without native health");if(RebirthVehicleTransferRecovery.Next(repairPlan,repairPlan.ReadAfter(),healthReceipts,true,out healthNext,null,null,100,5000)!=RebirthVehicleTransferStep.Reconcile)throw new Exception("Unrepaired native health ignored");if(RebirthVehicleTransferRecovery.Next(repairPlan,repairPlan.ReadAfter(),healthReceipts,true,out healthNext,null,null,2600,5000)!=RebirthVehicleTransferStep.Complete)throw new Exception("Verified repair health ignored");
bool invalidHealth=false;try{new RebirthVehicleTransferHealth(5000,5000,5000);}catch(InvalidDataException){invalidHealth=true;}if(!invalidHealth)throw new Exception("No-op repair accepted");var missingHealth=repairPlan.ToXml();missingHealth.Element("health").Remove();bool missingRepair=false;try{RebirthVehicleTransferPlan.Read(missingHealth);}catch(InvalidDataException){missingRepair=true;}if(!missingRepair)throw new Exception("Repair record without health accepted");
var kitDebit=new RebirthVehicleTransferItem(Guid.NewGuid(),true,"repair-kit",1,RebirthVehiclePartSourceLocation.Backpack,0);var producedRepair=RebirthVehicleTransferPlanner.Repair(Guid.NewGuid(),plan.CreationId,"owner","native repair",entityTarget,plan.ReadBefore(),plan.ReadBefore().Revision,new EntityPlayer(),100,5000,kitDebit);if(producedRepair.Health.After!=2600||producedRepair.Items[0].ItemData!="repair-kit"||producedRepair.Items[0].ReceiptId!=kitDebit.ReceiptId)throw new Exception("Repair producer lost kit/health");
RebirthServiceCraftSkillService.Amount=1000;var cappedRepair=RebirthVehicleTransferPlanner.Repair(Guid.NewGuid(),plan.CreationId,"owner","capped repair",entityTarget,plan.ReadBefore(),plan.ReadBefore().Revision,new EntityPlayer(),4900,5000,kitDebit);if(cappedRepair.Health.After!=5000)throw new Exception("Repair maximum clamp ignored");RebirthServiceCraftSkillService.Amount=2500;
bool wrongKit=false;try{RebirthVehicleTransferPlanner.Repair(Guid.NewGuid(),plan.CreationId,"owner","bad kit",entityTarget,plan.ReadBefore(),plan.ReadBefore().Revision,new EntityPlayer(),100,5000,debit);}catch(InvalidDataException){wrongKit=true;}if(!wrongKit)throw new Exception("Wrong repair debit accepted");
Guid next;var receipts=new Dictionary<Guid,RebirthVehicleOwnerTransferResult>{{debit.ReceiptId,RebirthVehicleOwnerTransferResult.Pending},{credit.ReceiptId,RebirthVehicleOwnerTransferResult.Pending}};
if(RebirthVehicleTransferRecovery.Next(plan,plan.ReadBefore(),null,false,out next)!=RebirthVehicleTransferStep.WaitForEvidence)throw new Exception("Missing receipts dispatched");
if(RebirthVehicleTransferRecovery.Next(plan,plan.ReadBefore(),receipts,false,out next)!=RebirthVehicleTransferStep.ReserveAssembly)throw new Exception("Reservation skipped");
var held=plan.ReadBefore();RebirthVehicleTransferReservation.TryReserve(held,planId,held.Revision);
if(RebirthVehicleTransferRecovery.Next(plan,held,receipts,false,out next)!=RebirthVehicleTransferStep.ApplyDebit||next!=debit.ReceiptId)throw new Exception("Wrong debit sequence");
receipts[debit.ReceiptId]=RebirthVehicleOwnerTransferResult.Applied;if(RebirthVehicleTransferRecovery.Next(plan,held,receipts,false,out next)!=RebirthVehicleTransferStep.ApplyAssembly)throw new Exception("Saved debit repeated");
if(RebirthVehicleTransferRecovery.Next(plan,plan.ReadAfter(),receipts,false,out next)!=RebirthVehicleTransferStep.WaitForAssemblySave)throw new Exception("Unverified assembly allowed credit");
if(RebirthVehicleTransferRecovery.Next(plan,plan.ReadAfter(),receipts,true,out next)!=RebirthVehicleTransferStep.ApplyCredit||next!=credit.ReceiptId)throw new Exception("Credit sequence failed");
receipts[credit.ReceiptId]=RebirthVehicleOwnerTransferResult.Applied;if(RebirthVehicleTransferRecovery.Next(plan,plan.ReadAfter(),receipts,true,out next)!=RebirthVehicleTransferStep.Complete)throw new Exception("Complete evidence ignored");
if(RebirthVehicleTransferRecovery.Next(plan,held,receipts,true,out next)!=RebirthVehicleTransferStep.Reconcile)throw new Exception("Early credit ignored");
receipts[credit.ReceiptId]=RebirthVehicleOwnerTransferResult.Pending;receipts[debit.ReceiptId]=RebirthVehicleOwnerTransferResult.Indeterminate;if(RebirthVehicleTransferRecovery.Next(plan,held,receipts,true,out next)!=RebirthVehicleTransferStep.Reconcile)throw new Exception("Uncertain receipt retried");
receipts[debit.ReceiptId]=RebirthVehicleOwnerTransferResult.Rejected;if(RebirthVehicleTransferRecovery.Next(plan,held,receipts,false,out next)!=RebirthVehicleTransferStep.CancelRejected)throw new Exception("Proven rejection ignored");
var secondDebit=new RebirthVehicleTransferItem(Guid.NewGuid(),true,"full-native-item",1,RebirthVehiclePartSourceLocation.Backpack,4);var multi=RebirthVehicleTransferPlan.Create(planId,plan.CreationId,"owner","fingerprint",plan.ReadBefore(),plan.ReadAfter(),new[]{debit,secondDebit,credit});receipts[secondDebit.ReceiptId]=RebirthVehicleOwnerTransferResult.Pending;if(RebirthVehicleTransferRecovery.Next(multi,held,receipts,false,out next)!=RebirthVehicleTransferStep.Reconcile)throw new Exception("Missing second receipt treated as safe rejection");
receipts[debit.ReceiptId]=RebirthVehicleOwnerTransferResult.Pending;receipts[secondDebit.ReceiptId]=RebirthVehicleOwnerTransferResult.Pending;
if(RebirthVehicleTransferRecovery.Next(multi,held,receipts,false,out next)!=RebirthVehicleTransferStep.ApplyDebitBatch||next!=Guid.Empty)throw new Exception("Multi-debit dispatched one receipt");IReadOnlyList<RebirthVehicleTransferItem> debitBatch;if(!RebirthVehicleTransferRecovery.TryGetDebitBatch(multi,out debitBatch)||debitBatch.Count!=2||debitBatch[0].ReceiptId!=debit.ReceiptId||debitBatch[1].ReceiptId!=secondDebit.ReceiptId)throw new Exception("Debit batch lost custody");
receipts[debit.ReceiptId]=RebirthVehicleOwnerTransferResult.Applied;if(RebirthVehicleTransferRecovery.Next(multi,held,receipts,false,out next)!=RebirthVehicleTransferStep.Reconcile)throw new Exception("Partly applied batch retried remainder");receipts[secondDebit.ReceiptId]=RebirthVehicleOwnerTransferResult.Applied;if(RebirthVehicleTransferRecovery.Next(multi,held,receipts,false,out next)!=RebirthVehicleTransferStep.ApplyAssembly)throw new Exception("Saved full batch repeated");
held.FuelPercent=.9f;if(RebirthVehicleTransferRecovery.Next(plan,held,receipts,false,out next)!=RebirthVehicleTransferStep.Reconcile)throw new Exception("Changed assembly overwritten");
var tempSave=Path.Combine(Path.GetTempPath(),"rebirth-transfer-store-"+Guid.NewGuid().ToString("N"));Directory.CreateDirectory(tempSave);string currentSave=tempSave;bool sessionActive=true;
try {
var store=new RebirthVehicleTransferPlanStore(tempSave,()=>currentSave,()=>sessionActive);if(store.Discover().Count!=0)throw new Exception("Fresh store not empty");store.Prepare(plan);store.Prepare(plan);if(store.Read(planId).Items.Count!=2)throw new Exception("Stored operations lost");
var freshStore=new RebirthVehicleTransferPlanStore(tempSave,()=>currentSave,()=>sessionActive);var discovered=freshStore.Discover();if(discovered.Count!=1||discovered[0].TransactionId!=planId||discovered[0].ActorId!="owner")throw new Exception("Reconnect discovery lost plan");
var independentBefore=plan.ReadBefore();independentBefore.AssemblyId=Guid.NewGuid();var independentId=Guid.NewGuid();var independentAfter=independentBefore.DeepClone();independentAfter.Revision++;independentAfter.LastAppliedInventoryTransferId=independentId;
var actorConflict=RebirthVehicleTransferPlan.Create(independentId,Guid.NewGuid(),"owner","new-request",independentBefore,independentAfter);bool actorHeld=false;try{freshStore.Prepare(actorConflict);}catch(InvalidDataException){actorHeld=true;}if(!actorHeld||freshStore.Discover().Count!=1)throw new Exception("Actor custody released on reconnect");
var assemblyConflictAfter=plan.ReadAfter();assemblyConflictAfter.LastAppliedInventoryTransferId=independentId;var assemblyConflict=RebirthVehicleTransferPlan.Create(independentId,Guid.NewGuid(),"other-owner","new-request",plan.ReadBefore(),assemblyConflictAfter);bool assemblyHeld=false;try{freshStore.Prepare(assemblyConflict);}catch(InvalidDataException){assemblyHeld=true;}if(!assemblyHeld)throw new Exception("Assembly custody double-booked");
var reusedReceipt=RebirthVehicleTransferPlan.Create(independentId,Guid.NewGuid(),"other-owner","new-request",independentBefore,independentAfter,new[]{debit});bool receiptHeld=false;try{freshStore.Prepare(reusedReceipt);}catch(InvalidDataException){receiptHeld=true;}if(!receiptHeld)throw new Exception("Receipt reused across plans");
var independent=RebirthVehicleTransferPlan.Create(independentId,Guid.NewGuid(),"other-owner","new-request",independentBefore,independentAfter);freshStore.Prepare(independent);freshStore.Prepare(independent);if(freshStore.Discover().Count!=2)throw new Exception("Independent transfer blocked");
var independentPath=Path.Combine(tempSave,"RebirthVehicleTransfers",independentId.ToString("N")+".xml");File.WriteAllText(independentPath,actorConflict.ToXml().ToString());bool injectedConflict=false;try{freshStore.Discover();}catch(InvalidDataException){injectedConflict=true;}if(!injectedConflict)throw new Exception("Conflicting catalogue published");File.Delete(independentPath);
int scopeCalls=0;var invalidated=new RebirthVehicleTransferPlanStore(tempSave,()=>currentSave,()=>++scopeCalls<3);bool duringDiscovery=false;try{invalidated.Discover();}catch(InvalidOperationException){duringDiscovery=true;}if(!duringDiscovery)throw new Exception("Invalidated discovery published");

var conflicting=RebirthVehicleTransferPlan.Create(planId,plan.CreationId,"other-owner","fingerprint",plan.ReadBefore(),plan.ReadAfter(),plan.Items);bool conflict=false;try{store.Prepare(conflicting);}catch(InvalidDataException){conflict=true;}if(!conflict||store.Read(planId).ActorId!="owner")throw new Exception("Plan overwritten");
sessionActive=false;bool stale=false;try{store.Read(planId);}catch(InvalidOperationException){stale=true;}if(!stale)throw new Exception("Old session read allowed");sessionActive=true;
currentSave=tempSave+"-other";bool wrongWorld=false;try{store.Read(planId);}catch(InvalidOperationException){wrongWorld=true;}if(!wrongWorld)throw new Exception("Other world read allowed");currentSave=tempSave;
var storeDir=Path.Combine(tempSave,"RebirthVehicleTransfers");var interrupted=Path.Combine(storeDir,"interrupted.tmp");File.WriteAllText(interrupted,"partial");bool interruptedBlocked=false;try{store.Prepare(plan);}catch(InvalidDataException){interruptedBlocked=true;}if(!interruptedBlocked)throw new Exception("Interrupted write admitted");File.Delete(interrupted);
var recordPath=Path.Combine(storeDir,planId.ToString("N")+".xml");File.WriteAllText(recordPath,"broken");bool corrupt=false;try{store.Prepare(plan);}catch(XmlException){corrupt=true;}if(!corrupt||File.ReadAllText(recordPath)!="broken")throw new Exception("Corrupt plan overwritten");
bool corruptDiscovery=false;try{freshStore.Discover();}catch(XmlException){corruptDiscovery=true;}if(!corruptDiscovery)throw new Exception("Partial corrupt catalogue accepted");

} finally {var storeDir=Path.Combine(tempSave,"RebirthVehicleTransfers");if(Directory.Exists(storeDir)){foreach(var file in Directory.GetFiles(storeDir))File.Delete(file);Directory.Delete(storeDir);}Directory.Delete(tempSave);}
var reloaded=RebirthVehicleTransferPlan.Read(plan.ToXml());if(reloaded.TransactionId!=planId||reloaded.ReadAfter().LastAppliedInventoryTransferId!=planId)throw new Exception("Plan identity roundtrip");
var invalid=plan.ToXml();invalid.Add(new XElement(invalid.Element("before")));bool malformedPlan=false;try{RebirthVehicleTransferPlan.Read(invalid);}catch(InvalidDataException){malformedPlan=true;}if(!malformedPlan)throw new Exception("Duplicate snapshot accepted");
var wrongAfter=plan.ReadAfter();wrongAfter.AssemblyId=Guid.NewGuid();bool wrongIdentity=false;try{RebirthVehicleTransferPlan.Create(planId,Guid.NewGuid(),"owner","fingerprint",plan.ReadBefore(),wrongAfter);}catch(InvalidDataException){wrongIdentity=true;}if(!wrongIdentity)throw new Exception("Different assembly accepted");
wrongAfter=plan.ReadAfter();wrongAfter.Revision++;bool wrongRevision=false;try{RebirthVehicleTransferPlan.Create(planId,Guid.NewGuid(),"owner","fingerprint",plan.ReadBefore(),wrongAfter);}catch(InvalidDataException){wrongRevision=true;}if(!wrongRevision)throw new Exception("Multiple revisions accepted");

var candidate=new RebirthVehicleAssembly{AssemblyId=Guid.NewGuid(),Revision=8};var tx=Guid.NewGuid();var other=Guid.NewGuid();
if(RebirthVehicleTransferReservation.TryReserve(candidate,tx,7)||RebirthVehicleTransferReservation.TryReserve(candidate,Guid.Empty,8))throw new Exception("Invalid reservation accepted");
if(!RebirthVehicleTransferReservation.TryReserve(candidate,tx,8)||!RebirthVehicleTransferReservation.TryReserve(candidate,tx,8)||RebirthVehicleTransferReservation.TryReserve(candidate,other,8))throw new Exception("Reservation identity lost");
candidate=RebirthVehicleAssemblySerializer.FromBase64(RebirthVehicleAssemblySerializer.ToBase64(candidate));
if(RebirthVehicleTransferReservation.TryMarkApplied(candidate,other)||candidate.PendingInventoryTransferId!=tx)throw new Exception("Other transaction completed reservation");
if(!RebirthVehicleTransferReservation.TryMarkApplied(candidate,tx)||candidate.PendingInventoryTransferId!=Guid.Empty||candidate.LastAppliedInventoryTransferId!=tx||!RebirthVehicleTransferReservation.TryMarkApplied(candidate,tx))throw new Exception("Completion failed");
if(RebirthVehicleTransferReservation.TryReserve(candidate,tx,8))throw new Exception("Applied transaction reserved again");
if(!RebirthVehicleTransferReservation.TryReserve(candidate,other,8)||RebirthVehicleTransferReservation.TryMarkApplied(candidate,tx)||candidate.PendingInventoryTransferId!=other)throw new Exception("Stale completion cleared new reservation");
RejectMalformed("Engine",true);RejectMalformed("",false);
var valid=Convert.FromBase64String(RebirthVehicleAssemblySerializer.ToBase64(new RebirthVehicleAssembly()));var extra=new byte[valid.Length+1];Array.Copy(valid,extra,valid.Length);bool trailing=false;try{RebirthVehicleAssemblySerializer.FromBase64(Convert.ToBase64String(extra));}catch(InvalidDataException){trailing=true;}if(!trailing)throw new Exception("Trailing data accepted");
bool tileTrailing=false;try{RebirthVehicleAssemblySerializer.ReadPayload(extra);}catch(InvalidDataException){tileTrailing=true;}if(!tileTrailing)throw new Exception("Tile envelope trailing data accepted");
var envelope=RebirthVehicleAssemblySerializer.ReadPayload(valid);if(envelope==null)throw new Exception("Valid tile envelope failed");

using(var m=new MemoryStream(new byte[]{255,255,127})){bool denied=false;try{RebirthVehicleAssemblySerializer.ReadBoundedPayload(new BinaryReader(m),262144);}catch(InvalidDataException){denied=true;}if(!denied||m.Position!=3)throw new Exception("Oversized prefix not rejected");}using(var m=new MemoryStream(new byte[]{4,65})){bool denied=false;try{RebirthVehicleAssemblySerializer.ReadBoundedPayload(new BinaryReader(m),10);}catch(EndOfStreamException){denied=true;}if(!denied)throw new Exception("Truncation accepted");}for(int version=1;version<=3;version++){using(var m=new MemoryStream()){var w=new BinaryWriter(m);w.Write(0x52564241);w.Write(version);w.Write(Guid.NewGuid().ToByteArray());w.Write("c");w.Write("f");w.Write(4L);if(version>=2)w.Write(.25f);w.Write(1);w.Write("Engine");w.Write("part");w.Write(3);w.Write(4f);w.Write(.5f);if(version>=3)w.Write("legacy-payload");w.Flush();m.Position=0;var a=RebirthVehicleAssemblySerializer.Read(new BinaryReader(m));if(a.SchemaVersion!=version||a.Parts["Engine"].SerializedItemValue!=(version>=3?"legacy-payload":null)||a.PendingInventoryTransferId!=Guid.Empty||a.LastAppliedInventoryTransferId!=Guid.Empty||a.Parts["Engine"].Quality!=3)throw new Exception("Legacy failed");}}
var source=new RebirthVehicleAssembly{PendingInventoryTransferId=Guid.NewGuid(),LastAppliedInventoryTransferId=Guid.NewGuid()};var assemblyClone=source.DeepClone();if(assemblyClone.PendingInventoryTransferId!=source.PendingInventoryTransferId||assemblyClone.LastAppliedInventoryTransferId!=source.LastAppliedInventoryTransferId)throw new Exception("Clone lost transaction identity");source.Parts["Engine"]=new RebirthInstalledVehiclePart{ItemName="part",Quality=4,SerializedItemValue="complete-native-payload"};var clone=source.Parts["Engine"].Clone();if(clone.SerializedItemValue!="complete-native-payload"||ReferenceEquals(clone,source.Parts["Engine"]))throw new Exception("Clone");string data=RebirthVehicleAssemblySerializer.ToBase64(source);var decoded=RebirthVehicleAssemblySerializer.FromBase64(data);if(decoded.SchemaVersion!=4||decoded.PendingInventoryTransferId!=source.PendingInventoryTransferId||decoded.LastAppliedInventoryTransferId!=source.LastAppliedInventoryTransferId||decoded.Parts["Engine"].SerializedItemValue!=clone.SerializedItemValue)throw new Exception("Payload lost");var truncated=Convert.FromBase64String(data);Array.Resize(ref truncated,truncated.Length-1);bool shortMarker=false;try{RebirthVehicleAssemblySerializer.ReadPayload(truncated);}catch(EndOfStreamException){shortMarker=true;}if(!shortMarker)throw new Exception("Truncated transaction marker accepted");source.Parts["Engine"].SerializedItemValue=new string('x',262144);bool rejected=false;try{RebirthVehicleAssemblySerializer.ToBase64(source);}catch(InvalidDataException){rejected=true;}if(!rejected)throw new Exception("Oversized assembly accepted");source.Parts["Engine"].SerializedItemValue="ok";source.ContentId=new string('x',262144);rejected=false;try{RebirthVehicleAssemblySerializer.ValidateSize(source);}catch(InvalidDataException){rejected=true;}if(!rejected)throw new Exception("Oversized header accepted");Console.WriteLine("PASS: actual assembly/part clone and serializer preserve v4 transaction identities/full payload, read v1/v2/v3 legacy records and reject oversized assembly/header, duplicate/empty slots and trailing data. Immutable custody plan roundtrip/isolation and invalid identity/revision tests PASS. Item receipt/count/source roundtrip and rejection tests PASS (native codec substituted). Real temporary-file prepare/retry/conflict/session/interruption/corruption checks PASS. Recovery sequencing and uncertainty tests PASS. Gameplay not executed.");}}
