using System;using System.Collections.Generic;
enum RebirthVehicleAssemblyCarrier {RepairableBlock,VehicleEntity}enum RebirthVehicleRequestOutcome {Applied,Rejected,Indeterminate}
class RebirthVehicleAssembly {}class ItemStack {public bool IsEmpty(){return false;}}
struct Vector3i {public int x;public static bool operator ==(Vector3i a,Vector3i b){return a.x==b.x;}public static bool operator !=(Vector3i a,Vector3i b){return a.x!=b.x;}public override bool Equals(object o){return o is Vector3i && ((Vector3i)o).x==x;}public override int GetHashCode(){return x;}}
class XUiC_RebirthVehicleRestoration {
class PendingClientRequest {public XUiC_RebirthVehicleRestoration Controller;public RebirthVehicleAssemblyCarrier Carrier;public Vector3i Position;public int EntityId;public long ExpectedRevision;public ItemStack ReservedCursorItem,PickedCursorItem;}
static Dictionary<Guid,PendingClientRequest> PendingClientRequests=new Dictionary<Guid,PendingClientRequest>();static object PendingClientSync=new object();static XUiC_RebirthVehicleRestoration current;
RebirthVehicleAssemblyCarrier carrier;Vector3i position;int entityId;Guid lastCompletedRequestId,pendingRequestId;long pendingExpectedRevision;RebirthVehicleAssembly assembly;int restored,cleared,delivered;
void RestoreReservedCursorItem(ItemStack s){restored++;}void DeliverConfirmedPickup(ItemStack s){delivered++;}void SetStatus(string s){}void Refresh(){}
// METHODS
static void Main(){var id=Guid.NewGuid();var c=new XUiC_RebirthVehicleRestoration{carrier=RebirthVehicleAssemblyCarrier.VehicleEntity,entityId=7,pendingRequestId=id};current=c;var p=new PendingClientRequest{Controller=c,Carrier=c.carrier,EntityId=7,ReservedCursorItem=new ItemStack(),PickedCursorItem=new ItemStack()};PendingClientRequests[id]=p;
Receive(id,c.carrier,new Vector3i(),8,null,"",RebirthVehicleRequestOutcome.Rejected);if(!PendingClientRequests.ContainsKey(id)||c.restored!=0)throw new Exception("Mismatched response consumed request");
var stale=new RebirthVehicleAssembly();Receive(Guid.NewGuid(),c.carrier,new Vector3i(),7,stale,"",RebirthVehicleRequestOutcome.Applied);Receive(Guid.Empty,c.carrier,new Vector3i(),7,stale,"",RebirthVehicleRequestOutcome.Applied);if(c.assembly!=null||c.pendingRequestId!=id)throw new Exception("Untracked reply altered active UI");
p.EntityId=8;Receive(id,c.carrier,new Vector3i(),7,null,"",RebirthVehicleRequestOutcome.Rejected);if(!PendingClientRequests.ContainsKey(id))throw new Exception("Pending identity ignored");p.EntityId=7;
Receive(id,c.carrier,new Vector3i(),7,null,"",RebirthVehicleRequestOutcome.Rejected);if(PendingClientRequests.ContainsKey(id)||c.restored!=1||c.cleared!=0||c.pendingRequestId!=Guid.Empty)throw new Exception("Valid rejection failed");
Receive(id,c.carrier,new Vector3i(),7,null,"",RebirthVehicleRequestOutcome.Rejected);if(c.restored!=1||c.cleared!=0)throw new Exception("Duplicate replay");c.lastCompletedRequestId=Guid.Empty;Receive(id,c.carrier,new Vector3i(),7,stale,"",RebirthVehicleRequestOutcome.Applied);if(c.assembly!=null)throw new Exception("Late completed reply applied after reopen");var accepted=Guid.NewGuid();c.pendingRequestId=accepted;PendingClientRequests[accepted]=new PendingClientRequest{Controller=c,Carrier=c.carrier,EntityId=7,PickedCursorItem=new ItemStack()};Receive(accepted,c.carrier,new Vector3i(),7,null,"",RebirthVehicleRequestOutcome.Applied);Receive(accepted,c.carrier,new Vector3i(),7,null,"",RebirthVehicleRequestOutcome.Applied);if(c.delivered!=1)throw new Exception("Pickup not delivered exactly once");Console.WriteLine("PASS: actual Receive retains pending state for mismatched responses and resolves matching rejection once. Cursor compensation methods stubbed; runtime untested.");}}
