#requires -Version 7.0
$ErrorActionPreference='Stop'
$root=Split-Path -Parent (Split-Path -Parent $PSScriptRoot)
$source=[IO.File]::ReadAllText((Join-Path $root 'Scripts/Survivor/Persistence/RebirthStationCancellationAttempt.cs'))
$fixture=@"
internal class RebirthStationGridAdmission{}internal class RebirthStationTerminalIntent{public bool IsCompletion;public int Actor=42;public XElement Write(){return new XElement("stationTerminalIntent",new XAttribute("job","job"),new XAttribute("actor",Actor));}public static bool TryRead(XElement n,RebirthStationGridAdmission a,out RebirthStationTerminalIntent i){i=new RebirthStationTerminalIntent();return a!=null;}}internal class RebirthStationCancellationRefund{public int Count=12;public XElement Write(){return new XElement("stationCancellationRefund",new XAttribute("count",Count));}public static bool TryReadStored(XElement n,RebirthStationGridAdmission a,RebirthStationTerminalIntent i,out RebirthStationCancellationRefund r){r=new RebirthStationCancellationRefund();return a!=null&&!i.IsCompletion;}}internal class RebirthStationNativeQueueSnapshot{public string Hash;public string Digest(){return Hash;}}internal class RebirthStationTerminalSnapshot{public string Digest(){return new string('C',64);}}
public static class AttemptFixture{static int checks;static void Check(bool value){checks++;if(!value)throw new Exception("attempt "+checks);}public static string Run(){var a=new RebirthStationGridAdmission();var intent=new RebirthStationTerminalIntent();var refund=new RebirthStationCancellationRefund();var before=new RebirthStationNativeQueueSnapshot{Hash=new string('A',64)};var after=new RebirthStationNativeQueueSnapshot{Hash=new string('B',64)};RebirthStationCancellationAttempt attempt,parsed;
Check(RebirthStationCancellationAttempt.TryCreate(a,intent,refund,before,after,new RebirthStationTerminalSnapshot(),out attempt));Check(RebirthStationCancellationAttempt.TryRead(attempt.Write(),a,intent,refund,out parsed)&&parsed.JobId=="job");
var node=attempt.Write();node.SetAttributeValue("phase","cancelled");Check(!RebirthStationCancellationAttempt.TryRead(node,a,intent,refund,out parsed));node=attempt.Write();node.SetAttributeValue("after",before.Hash);Check(!RebirthStationCancellationAttempt.TryRead(node,a,intent,refund,out parsed));node=attempt.Write();node.SetAttributeValue("terminal",new string('c',64));Check(!RebirthStationCancellationAttempt.TryRead(node,a,intent,refund,out parsed));node=attempt.Write();node.SetAttributeValue("extra",1);Check(!RebirthStationCancellationAttempt.TryRead(node,a,intent,refund,out parsed));
intent.Actor=99;Check(!RebirthStationCancellationAttempt.TryRead(attempt.Write(),a,intent,refund,out parsed));intent.Actor=42;refund.Count=99;Check(!RebirthStationCancellationAttempt.TryRead(attempt.Write(),a,intent,refund,out parsed));refund.Count=12;intent.IsCompletion=true;Check(!RebirthStationCancellationAttempt.TryRead(attempt.Write(),a,intent,refund,out parsed));intent.IsCompletion=false;
var clone=attempt.Clone();node=clone.Write();node.SetAttributeValue("before",new string('D',64));Check(RebirthStationCancellationAttempt.TryRead(clone.Write(),a,intent,refund,out parsed)&&clone.Write().Attribute("before").Value==before.Hash);var records=new Dictionary<string,RebirthStationCancellationAttempt>{{"job",attempt}};var admissions=new Dictionary<string,RebirthStationGridAdmission>{{"job",a}};var intents=new Dictionary<string,RebirthStationTerminalIntent>{{"job",intent}};var refunds=new Dictionary<string,RebirthStationCancellationRefund>{{"job",refund}};Dictionary<string,RebirthStationCancellationAttempt> loaded;
Check(RebirthStationCancellationAttempt.ReadAll(new XElement("progression"),admissions,intents,refunds,out loaded)&&loaded.Count==0);
var section=RebirthStationCancellationAttempt.WriteAll(records,admissions,intents,refunds);Check(RebirthStationCancellationAttempt.ReadAll(new XElement("progression",section),admissions,intents,refunds,out loaded)&&loaded.Count==1);
Check(attempt.Write().Element("stationCancellationRefund")==null&&attempt.Write().Attribute("refund").Value.Length==64);
section.Add(attempt.Write());Check(!RebirthStationCancellationAttempt.ReadAll(new XElement("progression",section),admissions,intents,refunds,out loaded));
Check(!RebirthStationCancellationAttempt.ReadAll(new XElement("progression",RebirthStationCancellationAttempt.WriteAll(records,admissions,intents,refunds)),admissions,intents,new Dictionary<string,RebirthStationCancellationRefund>(),out loaded));
Check(!RebirthStationCancellationAttempt.ReadAll(new XElement("progression",RebirthStationCancellationAttempt.WriteAll(records,admissions,intents,refunds),RebirthStationCancellationAttempt.WriteAll(records,admissions,intents,refunds)),admissions,intents,refunds,out loaded));
return "PASS "+checks+" actual cancellation-attempt codec with intent/refund/snapshot doubles; no save or native attempt";}}
"@
Add-Type -TypeDefinition ($source+$fixture)
[AttemptFixture]::Run()