#requires -Version 7.0
$ErrorActionPreference='Stop'
$root=Split-Path -Parent (Split-Path -Parent $PSScriptRoot)
$source=[IO.File]::ReadAllText((Join-Path $root 'Scripts/Survivor/Persistence/RebirthStationCancellationAttempt.cs'))
$publication=[IO.File]::ReadAllText((Join-Path $root 'Scripts/Survivor/Persistence/RebirthStationCancellationPublication.cs'))
$fixture=@"
internal class RebirthStationGridAdmission{public string JobId="job",CreationId="creation";public XElement Write(){return new XElement("admission",new XAttribute("x",0),new XAttribute("z",0));}}internal class RebirthStationTerminalIntent{public bool IsCompletion=false;public int Actor=42;public XElement Write(){return new XElement("stationTerminalIntent",new XAttribute("job","job"),new XAttribute("actor",Actor));}public static bool TryRead(XElement n,RebirthStationGridAdmission a,out RebirthStationTerminalIntent i){i=new RebirthStationTerminalIntent();return a!=null;}}internal class RebirthStationCancellationRefund{public int Count=12;public XElement Write(){return new XElement("stationCancellationRefund",new XAttribute("count",Count));}public static bool TryReadStored(XElement n,RebirthStationGridAdmission a,RebirthStationTerminalIntent i,out RebirthStationCancellationRefund r){r=new RebirthStationCancellationRefund();return a!=null&&!i.IsCompletion;}}internal class RebirthStationNativeQueueSnapshot{public string Hash;public string Digest(){return Hash;}}internal class RebirthStationTerminalSnapshot{public string Digest(){return new string('C',64);}}
public static class RebirthStationPublicationRecord{public static string Digest(byte[] bytes){using(var sha=System.Security.Cryptography.SHA256.Create())return BitConverter.ToString(sha.ComputeHash(bytes)).Replace("-","");}}
public static class RebirthStationSnapshotEvidence{public const int MaximumSnapshotBytes=8*1024*1024;public class Publication{public string Path="C:/save/Region/r.0.0.7rg",PayloadDigest;public int ChunkX,ChunkZ,InputStart=8,InputLength=4,QueueStart=12,QueueLength=4,OutputStart=16,OutputLength=4,CompletionStart=20,CompletionLength=4;}}
public static class SdFile{public static Stream Open(string path,FileMode mode,FileAccess access,FileShare share){return new MemoryStream(new byte[1]);}}
public static class RebirthStationRegionPayload{public static byte[] Payload=new byte[]{1,2,3};public static bool TryRead(Stream stream,int x,int z,out byte[] bytes){bytes=Payload;return true;}}
public static class RebirthStationChunkInflate{public static bool Changed;public static bool TryDecode(byte[] p,int bound,out byte[] bytes){bytes=Enumerable.Range(1,16).Select(x=>(byte)x).ToArray();if(Changed)bytes[0]++;return true;}}
internal class RebirthStationCancellationExpectation{public bool Valid=true;public bool MatchesStation(byte[] i,byte[] q){return Valid;}public bool MatchesTerminal(byte[] o,byte[] c){return Valid;}}
public static class PublicationFixture{static int checks;static void Check(bool b){checks++;if(!b)throw new Exception("publication "+checks);}public static string Run(){var a=new RebirthStationGridAdmission();var intent=new RebirthStationTerminalIntent();var refund=new RebirthStationCancellationRefund();RebirthStationCancellationAttempt attempt;Check(RebirthStationCancellationAttempt.TryCreate(a,intent,refund,new RebirthStationNativeQueueSnapshot{Hash=new string('A',64)},new RebirthStationNativeQueueSnapshot{Hash=new string('B',64)},new RebirthStationTerminalSnapshot(),out attempt));var proof=new RebirthStationSnapshotEvidence.Publication{PayloadDigest=RebirthStationPublicationRecord.Digest(RebirthStationRegionPayload.Payload)};var expected=new RebirthStationCancellationExpectation();RebirthStationCancellationPublication result,parsed;
Check(RebirthStationCancellationPublication.TryCreate("C:/save",a,intent,refund,attempt,expected,proof,out result));Check(result.Revalidate("C:/save",a,intent,refund,attempt));var node=result.Write();Check(RebirthStationCancellationPublication.TryRead(node,a,intent,refund,attempt,out parsed));node.SetAttributeValue("outputStart",12);Check(!RebirthStationCancellationPublication.TryRead(node,a,intent,refund,attempt,out parsed));node=result.Write();node.SetAttributeValue("region","../elsewhere");Check(!RebirthStationCancellationPublication.TryRead(node,a,intent,refund,attempt,out parsed));node=result.Write();node.SetAttributeValue("completionLength",0);Check(!RebirthStationCancellationPublication.TryRead(node,a,intent,refund,attempt,out parsed));node=result.Write();node.SetAttributeValue("chunkX",1);Check(!RebirthStationCancellationPublication.TryRead(node,a,intent,refund,attempt,out parsed));node=result.Write();node.SetAttributeValue("extra",1);Check(!RebirthStationCancellationPublication.TryRead(node,a,intent,refund,attempt,out parsed));
RebirthStationRegionPayload.Payload[0]++;Check(!result.Revalidate("C:/save",a,intent,refund,attempt));RebirthStationRegionPayload.Payload[0]--;RebirthStationChunkInflate.Changed=true;Check(!result.Revalidate("C:/save",a,intent,refund,attempt));RebirthStationChunkInflate.Changed=false;
expected.Valid=false;Check(!RebirthStationCancellationPublication.TryCreate("C:/save",a,intent,refund,attempt,expected,proof,out parsed));expected.Valid=true;proof.CompletionLength=0;Check(!RebirthStationCancellationPublication.TryCreate("C:/save",a,intent,refund,attempt,expected,proof,out parsed));proof.CompletionLength=4;proof.Path="C:/other/region";Check(!RebirthStationCancellationPublication.TryCreate("C:/save",a,intent,refund,attempt,expected,proof,out parsed));
var records=new Dictionary<string,RebirthStationCancellationPublication>{{"job",result}};var admissions=new Dictionary<string,RebirthStationGridAdmission>{{"job",a}};var intents=new Dictionary<string,RebirthStationTerminalIntent>{{"job",intent}};var refunds=new Dictionary<string,RebirthStationCancellationRefund>{{"job",refund}};var attempts=new Dictionary<string,RebirthStationCancellationAttempt>{{"job",attempt}};Dictionary<string,RebirthStationCancellationPublication> loaded;Check(RebirthStationCancellationPublication.ReadAll(new XElement("progression"),admissions,intents,refunds,attempts,out loaded)&&loaded.Count==0);var section=RebirthStationCancellationPublication.WriteAll(records,admissions,intents,refunds,attempts);Check(RebirthStationCancellationPublication.ReadAll(new XElement("progression",section),admissions,intents,refunds,attempts,out loaded)&&loaded.Count==1);Check(!RebirthStationCancellationPublication.ReadAll(new XElement("progression",section,section),admissions,intents,refunds,attempts,out loaded));var duplicate=new XElement(section);duplicate.Add(result.Write());Check(!RebirthStationCancellationPublication.ReadAll(new XElement("progression",duplicate),admissions,intents,refunds,attempts,out loaded));attempts.Clear();Check(!RebirthStationCancellationPublication.ReadAll(new XElement("progression",section),admissions,intents,refunds,attempts,out loaded));
Check(result.Clone().Write().ToString()==result.Write().ToString());return "PASS "+checks+" actual cancelled publication codec/readback with region/inflate/expectation/admission doubles; no native file";}}
"@
Add-Type -TypeDefinition ($source+"`n"+[regex]::Replace($publication,'(?m)^using [^;]+;\r?\n','')+$fixture)
[PublicationFixture]::Run()