#requires -Version 7.0
$ErrorActionPreference='Stop'
$root=Split-Path -Parent (Split-Path -Parent $PSScriptRoot)
$s=[IO.File]::ReadAllText((Join-Path $root 'Scripts/Survivor/Progression/RebirthStationObservationDispatcher.cs'))
$a=$s.IndexOf('    internal static bool CanProcessNativeQueue(');$b=$s.IndexOf('    internal static bool TryGetVerifiedQueuedAdmission(',$a)
if($a-lt0-or$b-lt$a){throw 'Current native hold method missing'}
$method=$s.Substring($a,$b-$a)
$repo=[IO.File]::ReadAllText((Join-Path $root 'Scripts/Survivor/Persistence/RebirthWorldCharacterRepository.cs'))
$begin=$repo.IndexOf('    internal static bool IsCurrentCachedRecord(');$end=$repo.IndexOf('    public static bool TryGet(RebirthStablePlayerIdentity identity,',$begin)
if($begin-lt0-or$end-le$begin){throw 'Cached record method missing'};$cached=$repo.Substring($begin,$end-$begin)
$code=@"
using System;using System.Collections.Generic;
public class RebirthWorldCharacterRecord{public bool IsComplete=true;public string StablePlayerKey="owner";public Progression Progression=new Progression();}public class Progression{public Dictionary<string,object> StationTerminalIntents=new Dictionary<string,object>();}public static class RebirthWorldCharacterRepository{public static bool serverAuthority=true;static object Sync=new object();public static Dictionary<string,RebirthWorldCharacterRecord> Cache=new Dictionary<string,RebirthWorldCharacterRecord>();
$cached
}public class World{}public class GameManager{public static GameManager Instance=new GameManager();public World World=new World();}
public class RebirthStationGridAdmission{public bool MatchesQueuedQuality(Recipe r,int m,int quality){return r.Exact&&quality==4;}}public class Recipe{public bool Exact=true;public bool Marked;public string Job;}
public class RecipeQueueItem{public Recipe Recipe;public byte Quality=4;public short Multiplier=1;public int StartingEntityId=42;}
public class TileEntityWorkstation{public RecipeQueueItem[] Queue;}
public static class RebirthStationGridQueue{public static bool IsMarked(Recipe r){return r.Marked;}public static bool TryGetJobId(Recipe r,out string job){job=r.Job;return job!=null;}}
public static class HoldFixture{static HashSet<string> verifiedQueuedJobs=new HashSet<string>();static Dictionary<string,Tuple<TileEntityWorkstation,int>> verifiedQueuedStations=new Dictionary<string,Tuple<TileEntityWorkstation,int>>();static Dictionary<string,RebirthStationGridAdmission> verifiedQueuedAdmissions=new Dictionary<string,RebirthStationGridAdmission>();static Dictionary<string,RebirthWorldCharacterRecord> verifiedQueuedOwners=new Dictionary<string,RebirthWorldCharacterRecord>();static bool Authority=true;static bool IsCurrentAuthorityThread(World w){return Authority;}
$method
static int checks;static void Check(bool b){checks++;if(!b)throw new Exception("hold assertion");}
public static string Run(){var tile=new TileEntityWorkstation{Queue=new[]{new RecipeQueueItem{Recipe=new Recipe()}}};Check(CanProcessNativeQueue(tile));tile.Queue[0].Recipe.Marked=true;tile.Queue[0].Recipe.Job="job";Check(!CanProcessNativeQueue(tile));verifiedQueuedJobs.Add("job");verifiedQueuedAdmissions["job"]=new RebirthStationGridAdmission();verifiedQueuedStations["job"]=Tuple.Create(tile,42);Check(!CanProcessNativeQueue(tile));var owner=new RebirthWorldCharacterRecord();verifiedQueuedOwners["job"]=owner;Check(!CanProcessNativeQueue(tile));RebirthWorldCharacterRepository.Cache["owner"]=owner;Check(CanProcessNativeQueue(tile));RebirthWorldCharacterRepository.Cache["owner"]=new RebirthWorldCharacterRecord();Check(!CanProcessNativeQueue(tile));RebirthWorldCharacterRepository.Cache["owner"]=owner;owner.IsComplete=false;Check(!CanProcessNativeQueue(tile));owner.IsComplete=true;RebirthWorldCharacterRepository.Cache.Clear();Check(!CanProcessNativeQueue(tile));RebirthWorldCharacterRepository.Cache["owner"]=owner;Check(CanProcessNativeQueue(tile));owner.Progression.StationTerminalIntents["job"]=new object();Check(!CanProcessNativeQueue(tile));owner.Progression.StationTerminalIntents.Clear();Check(CanProcessNativeQueue(tile));owner.Progression.StationTerminalIntents["other"]=new object();Check(CanProcessNativeQueue(tile));owner.Progression.StationTerminalIntents.Clear();tile.Queue[0].Multiplier=2;Check(!CanProcessNativeQueue(tile));tile.Queue[0].Multiplier=1;var single=tile.Queue[0];tile.Queue=new[]{single,single};Check(!CanProcessNativeQueue(tile));tile.Queue=new[]{single,new RecipeQueueItem{Recipe=new Recipe{Marked=true,Job="job"}}};Check(!CanProcessNativeQueue(tile));tile.Queue=new[]{single};tile.Queue[0].Recipe.Exact=false;Check(!CanProcessNativeQueue(tile));tile.Queue[0].Recipe.Exact=true;tile.Queue[0].Quality=5;Check(!CanProcessNativeQueue(tile));tile.Queue[0].Quality=4;var other=new TileEntityWorkstation{Queue=tile.Queue};Check(!CanProcessNativeQueue(other));tile.Queue[0].StartingEntityId=99;Check(!CanProcessNativeQueue(tile));tile.Queue[0].StartingEntityId=42;Authority=false;Check(!CanProcessNativeQueue(tile));Authority=true;tile.Queue[0].Recipe.Job=null;Check(!CanProcessNativeQueue(tile));tile.Queue[0].Recipe.Job="job";tile.Queue=new[]{tile.Queue[0],new RecipeQueueItem{Recipe=new Recipe{Marked=true,Job="other"}}};Check(!CanProcessNativeQueue(tile));verifiedQueuedJobs.Clear();tile.Queue=new[]{new RecipeQueueItem{Recipe=new Recipe()}};Check(CanProcessNativeQueue(tile));return "PASS "+checks+" actual hold method checks with explicit queue/authority doubles; no native processing or saved publication proof";}}
"@
Add-Type -TypeDefinition $code
[HoldFixture]::Run()