using System;using System.Collections;using System.Collections.Generic;
struct Vector2 {public float x,y;public Vector2(float a,float b){x=a;y=b;}public static Vector2 Lerp(Vector2 a,Vector2 b,float t){return new Vector2(a.x+(b.x-a.x)*t,a.y+(b.y-a.y)*t);}public static float Distance(Vector2 a,Vector2 b){return (float)Math.Sqrt((a.x-b.x)*(a.x-b.x)+(a.y-b.y)*(a.y-b.y));}public static explicit operator Vector2(Vector3 a){return new Vector2(a.x,a.y);}}
struct Vector3 {public float x,y,z;public Vector3(float a,float b,float c=0){x=a;y=b;z=c;}public static Vector3 operator -(Vector3 a,Vector3 b){return new Vector3(a.x-b.x,a.y-b.y,a.z-b.z);}public float sqrMagnitude{get{return x*x+y*y+z*z;}}}
static class Mathf {public static float Clamp(float a,float min,float max){return Math.Max(min,Math.Min(max,a));}}
static class Time {public static int frameCount;public static float realtimeSinceStartup;}
static class Application {public static bool isFocused=true;}
static class Input {public static Vector3 mousePosition;}
class PlayerAction {public string Name;public int Updates;public float Last;public void UpdateWithValue(float value,ulong tick,float delta){Updates++;Last=value;}}
class Permanent {public PlayerAction Inventory=new PlayerAction{Name="Inventory"};}
class PlayerActionsLocal {public Permanent PermanentActions=new Permanent();}
static class RebirthGameBridgeInput {
 private static readonly Dictionary<PlayerAction,Held> held=new Dictionary<PlayerAction,Held>();public static bool Shift,Control,Alt,LockCursor;public static float Pace=.55f;public static bool CursorActive{get;private set;}public static Vector2 CursorPosition{get;private set;}private static Vector3 realMouseAtActivation;
 public static PlayerAction Click=new PlayerAction{Name="gui.LeftClick"},Slot=new PlayerAction{Name="InventorySlot2"};public static PlayerActionsLocal Local=new PlayerActionsLocal();public static PlayerActionsLocal LocalActions(){return Local;}public static PlayerAction Find(string name){return name=="gui.LeftClick"?Click:Slot;}
 // PRODUCTION_INPUT
 public static void Tick(PlayerAction action){UpdateBindingsPrefix(action,1,.1f);}public static bool CursorCheck(){return CheckCursorActive();}
}
class ItemClass {public string Name="crate";public int Type=1;public string GetItemName(){return Name;}public static ItemValue GetItem(string name,bool unused){return new ItemValue{ItemClass=new ItemClass{Name=name}};}}
class ItemValue {public int type=1;public ItemClass ItemClass=new ItemClass();public ItemValue(){}public ItemValue(int type,int a,int b,bool c){this.type=type;}public bool IsEmpty(){return false;}}
class ItemStack {public ItemValue itemValue=new ItemValue();public ItemStack(){}public ItemStack(ItemValue value,int count){itemValue=value;}}
class Hand {public int Changes;public void OnSlotChanged(int slot){Changes++;}}
class Inventory {public int holdingItemIdx,SelectedSlot;public Hand Hand=new Hand();public ItemStack GetItem(int slot){return new ItemStack();}}
class Bag {public bool AddItem(ItemStack stack){return true;}}
class EntityPlayerLocal {public Inventory inventory=new Inventory();public Bag bag=new Bag();public bool Dead;public bool IsDead(){return Dead;}}
class ToolbeltConfig {public static ToolbeltConfig CurrentConfig=new ToolbeltConfig();public int SlotsPerBar=10;}
static class RebirthGameBridgeNeeds {
 public static bool Supply=false,Assigned;public static int ToolbeltSize(EntityPlayerLocal p){return 20;}private static string HeldName(EntityPlayerLocal p){return "crate";}public static IEnumerator WaitHandsFree(EntityPlayerLocal p,float timeout){yield return null;}private static IEnumerator Wait(float seconds){float end=Time.realtimeSinceStartup+seconds;while(Time.realtimeSinceStartup<end)yield return null;}
 public static int ToolbeltSlot(EntityPlayerLocal p,Func<ItemClass,bool> want,out string name,Func<ItemStack,bool> match=null){name="crate";return Assigned?0:-1;}private static string BestInBag(EntityPlayerLocal p,Func<ItemClass,bool> want,Func<ItemStack,bool> match){return "crate";}private static int FreeableToolbeltSlot(EntityPlayerLocal p,Func<ItemClass,bool> want){return 0;}
 // PRODUCTION_NEEDS
}
static class RebirthGameBridgeUi {
 public static bool AnyModalOpen(){return true;}public static IEnumerator LookAtWindow(){yield return null;}public static IEnumerator CloseMenus(){yield return null;}public static bool TryFindEmptyToolbeltSlot(out Vector2 point,out int slot){point=new Vector2(20,20);slot=0;return true;}public static bool TryFindToolbeltSlot(int slot,out Vector2 point){point=new Vector2();return true;}public static bool TryFindEmptyBackpackSlot(out Vector2 point){point=new Vector2();return true;}public static bool TryFindItemSlot(string name,bool belt,out Vector2 point,Func<ItemStack,bool> match){point=new Vector2(10,10);return true;}public static ItemStack HeldItem(){return null;}public static string HeldItemName(){return null;}
 // PRODUCTION_UI
}
class Driver:IDisposable {private readonly Stack<IEnumerator> stack=new Stack<IEnumerator>();public Driver(IEnumerator root){stack.Push(root);}public bool Step(){while(stack.Count>0){var it=stack.Peek();if(!it.MoveNext()){(stack.Pop() as IDisposable)?.Dispose();continue;}var child=it.Current as IEnumerator;if(child!=null){stack.Push(child);continue;}Time.frameCount++;Time.realtimeSinceStartup+=.1f;RebirthGameBridgeInput.Tick(RebirthGameBridgeInput.Click);RebirthGameBridgeInput.Tick(RebirthGameBridgeInput.Slot);return true;}return false;}public void Dispose(){while(stack.Count>0)(stack.Pop() as IDisposable)?.Dispose();}}
class Checks {
 static int ChecksRun;static void A(bool b,string m){ChecksRun++;if(!b)throw new Exception(m);}static void Reset(){RebirthGameBridgeInput.ReleaseAll();RebirthGameBridgeInput.LockCursor=false;Time.frameCount=0;Time.realtimeSinceStartup=0;Input.mousePosition=new Vector3();Application.isFocused=true;RebirthGameBridgeInput.Click.Updates=RebirthGameBridgeInput.Slot.Updates=0;RebirthGameBridgeNeeds.Assigned=false;}
 static void Main(){
 Reset();var action=new PlayerAction{Name="test"};RebirthGameBridgeInput.HoldFrames(action,0,.7f);RebirthGameBridgeInput.Tick(action);A(action.Updates==1&&action.Last==.7f,"actual hold injects chosen value");Time.frameCount=1;RebirthGameBridgeInput.Tick(action);A(RebirthGameBridgeInput.IsHeld(action),"inclusive frame deadline");Time.frameCount=2;RebirthGameBridgeInput.Tick(action);A(!RebirthGameBridgeInput.IsHeld(action),"frame deadline expiry");
 Reset();RebirthGameBridgeInput.HoldSeconds(action,1);Time.realtimeSinceStartup=1;RebirthGameBridgeInput.Tick(action);A(RebirthGameBridgeInput.IsHeld(action),"inclusive time deadline");Time.realtimeSinceStartup=1.01f;RebirthGameBridgeInput.Tick(action);A(!RebirthGameBridgeInput.IsHeld(action),"time expiry");RebirthGameBridgeInput.HoldSeconds(action,0);Time.realtimeSinceStartup=100;RebirthGameBridgeInput.Tick(action);A(RebirthGameBridgeInput.IsHeld(action),"zero seconds holds until release");RebirthGameBridgeInput.Release(null);A(RebirthGameBridgeInput.IsHeld(action),"null release no effect");RebirthGameBridgeInput.HoldFrames(action,50,.4f);RebirthGameBridgeInput.Release(action);A(!RebirthGameBridgeInput.IsHeld(action),"legacy release removes current replacement entry (existing ownership gap)");
 Reset();RebirthGameBridgeInput.SetCursor(new Vector2(10,20));A(RebirthGameBridgeInput.CursorActive&&RebirthGameBridgeInput.CursorPosition.x==10,"cursor activates chosen point");Input.mousePosition=new Vector3(25,0);A(RebirthGameBridgeInput.CursorCheck(),"exact25px threshold stays active");Input.mousePosition=new Vector3(26,0);A(!RebirthGameBridgeInput.CursorCheck(),"focused real mouse returns cursor");RebirthGameBridgeInput.SetCursor(new Vector2());Application.isFocused=false;Input.mousePosition=new Vector3(100,0);A(RebirthGameBridgeInput.CursorCheck(),"unfocused real movement leaves legacy cursor");Application.isFocused=true;RebirthGameBridgeInput.LockCursor=true;A(RebirthGameBridgeInput.CursorCheck(),"legacy lock ignores handback");RebirthGameBridgeInput.ReleaseCursor();A(!RebirthGameBridgeInput.CursorActive&&RebirthGameBridgeInput.LockCursor,"ReleaseCursor doesn't clear LockCursor (existing cleanup gap)");
 Reset();using(var driver=new Driver(RebirthGameBridgeUi.GlideTo(new Vector2(100,100)))){A(driver.Step(),"actual glide yields");Input.mousePosition=new Vector3(100,0);A(!RebirthGameBridgeInput.CursorCheck(),"physical takeover before next glide write");A(driver.Step()&&RebirthGameBridgeInput.CursorActive,"legacy glide reactivates after takeover (existing gap)");}
 Reset();using(var driver=new Driver(RebirthGameBridgeUi.DragItem(new Vector2(),new Vector2(20,20)))){int limit=0;while(!RebirthGameBridgeInput.IsHeld(RebirthGameBridgeInput.Click)&&driver.Step())if(++limit>100)throw new Exception("drag setup timeout");A(RebirthGameBridgeInput.IsHeld(RebirthGameBridgeInput.Click),"actual drag holds native mouse before carry");}A(RebirthGameBridgeInput.IsHeld(RebirthGameBridgeInput.Click),"disposing legacy nested drag leaves held click (confirmed gap)");
 Reset();var player=new EntityPlayerLocal();using(var driver=new Driver(RebirthGameBridgeNeeds.Prepare(player,ic=>true,null,"a crate",s=>{}))){int limit=0;while(!RebirthGameBridgeInput.IsHeld(RebirthGameBridgeInput.Click)&&driver.Step())if(++limit>100)throw new Exception("Prepare timeout");A(RebirthGameBridgeInput.LockCursor&&RebirthGameBridgeInput.IsHeld(RebirthGameBridgeInput.Click),"actual Prepare reaches nested drag");}A(RebirthGameBridgeInput.LockCursor&&RebirthGameBridgeInput.IsHeld(RebirthGameBridgeInput.Click),"disposing legacy Prepare leaves lock and click (confirmed gap)");
 Reset();player=new EntityPlayerLocal();bool done=false,ok=false;using(var driver=new Driver(RebirthGameBridgeNeeds.Equip(player,11,"crate",v=>{done=true;ok=v;}))){int limit=0;while(driver.Step()){if(RebirthGameBridgeInput.IsHeld(RebirthGameBridgeInput.Slot)){A(RebirthGameBridgeInput.Shift,"second toolbelt bar uses Shift");player.inventory.holdingItemIdx=11;}if(++limit>100)throw new Exception("Equip timeout");}}A(done&&ok&&!RebirthGameBridgeInput.Shift,"legacy Equip succeeds and restores Shift");
 Reset();player=new EntityPlayerLocal();using(var driver=new Driver(RebirthGameBridgeNeeds.Equip(player,1,"crate",v=>{}))){int limit=0;while(!RebirthGameBridgeInput.IsHeld(RebirthGameBridgeInput.Slot)&&driver.Step())if(++limit>100)throw new Exception("Equip cancel timeout");RebirthGameBridgeInput.Shift=true;}A(!RebirthGameBridgeInput.Shift,"legacy Equip disposal restores old bool over newer same-value writer (confirmed ownership gap)");
 Console.WriteLine("PASS "+ChecksRun+" current default API/coroutine compatibility observations; existing ownership/cursor/cancellation defects explicitly reproduced, NO new owned API acceptance claim. Actual Hold/Release/expiry/cursor and Prepare/Equip/Drag/Glide/Click methods extracted; native inventory/actions/time/UI doubled.");
 }
}