using System;using System.Collections.Generic;
// Actual reading/audio persistence and shared creation scope; native identity/disk adapters doubled.
class EntityPlayer{public int entityId=1;}
class Origin{public string CreationId;}
class Progression{public Dictionary<string,float>LiteratureStudyProgress=new Dictionary<string,float>();}
class RebirthWorldCharacterRecord{public bool IsComplete=true;public Origin Origin=new Origin();public Progression Progression=new Progression();public int Touches;public void Touch(string reason){Touches++;}}
class Session{public string CreationId,ItemId="title",SourceLiteratureId="title";public float Progress=.47f;public bool CompletedAwaitingSave,CancelAwaitingSave,Paused;public string AudiobookItemId="audio";public int EntityId=1;public float SaveAccumulator;}
class RebirthStablePlayerIdentity{public static bool Ready=true;public static bool TryResolveServerEntity(EntityPlayer p,out RebirthStablePlayerIdentity i){i=Ready?new RebirthStablePlayerIdentity():null;return Ready;}}
static class RebirthWorldCharacterRepository{public static bool Save=true,Throw;public static int Saves;public static bool SaveIfDirty(RebirthStablePlayerIdentity i,string reason){Saves++;if(Throw)throw new Exception("disk fault");return Save;}}
static class Mathf{public static float Clamp(float v,float lo,float hi){return Math.Max(lo,Math.Min(hi,v));}}
static class RebirthWorldCharacterService{public static RebirthWorldCharacterRecord Record;public static bool TryGet(EntityPlayer p,out RebirthWorldCharacterRecord r){r=Record;return r!=null;}}
static class RebirthStudyHudNetworkService{public static int Clears;public static void SendClear(EntityPlayer p){Clears++;}}
static class RebirthLogSettings{public static bool LiteratureLoggingEnabled=false;public static void TraceLiterature(string text){}}
// SCOPE
class Reading{public static Dictionary<int,Session>Active=new Dictionary<int,Session>();public static int Notices;static void Send(EntityPlayer p,bool ok,string message){Notices++;}
// CANCEL
public static void Stop(EntityPlayer p,Session s){Cancel(p,s,"stopped",true);}public static bool Retry(EntityPlayer p,RebirthWorldCharacterRecord r,Session s,float dt){return RetryCancelledSave(p,r,s,dt);}
// READING
public static bool Run(EntityPlayer p,RebirthWorldCharacterRecord r,Session s){return Persist(p,r,s);}}
class Audio{public static Dictionary<int,Session>Active=new Dictionary<int,Session>();public static int Notices;static void Send(EntityPlayer p,bool ok,string message){Notices++;}
// AUDIO_CANCEL
public static void Stop(EntityPlayer p,Session s){Cancel(p,s,"stopped",true);}public static bool Retry(EntityPlayer p,RebirthWorldCharacterRecord r,Session s,float dt){return RetryCancelledSave(p,r,s,dt);}
// AUDIO
public static bool Run(EntityPlayer p,RebirthWorldCharacterRecord r,Session s){return Persist(p,r,s);}}
class Checks{static void A(bool ok,string label){if(!ok)throw new Exception(label);}static void Main(){foreach(var persist in new Func<EntityPlayer,RebirthWorldCharacterRecord,Session,bool>[] {Reading.Run,Audio.Run}){
var p=new EntityPlayer();var r=new RebirthWorldCharacterRecord{Origin=new Origin{CreationId=Guid.NewGuid().ToString("N")}};var s=new Session{CreationId=r.Origin.CreationId};RebirthWorldCharacterRepository.Saves=0;RebirthWorldCharacterRepository.Save=true;RebirthWorldCharacterRepository.Throw=false;
A(persist(p,r,s)&&r.Progression.LiteratureStudyProgress["title"]==.47f&&r.Touches==1,"latest progress saved");RebirthWorldCharacterRepository.Save=false;s.Progress=.61f;A(!persist(p,r,s)&&r.Progression.LiteratureStudyProgress["title"]==.61f,"failed save retains latest dirty progress");RebirthWorldCharacterRepository.Throw=true;A(!persist(p,r,s),"save exception contained");RebirthWorldCharacterRepository.Throw=false;RebirthWorldCharacterRepository.Save=true;int saves=RebirthWorldCharacterRepository.Saves;r.Origin.CreationId=Guid.NewGuid().ToString("N");A(!persist(p,r,s)&&RebirthWorldCharacterRepository.Saves==saves,"replacement character not saved");r.Origin.CreationId=s.CreationId;r.IsComplete=false;A(!persist(p,r,s)&&RebirthWorldCharacterRepository.Saves==saves,"incomplete character not saved");r.IsComplete=true;s.CompletedAwaitingSave=true;r.Progression.LiteratureStudyProgress.Remove("title");A(persist(p,r,s)&&!r.Progression.LiteratureStudyProgress.ContainsKey("title"),"pending completion saves without recreating partial progress");A(!persist(null,r,s)&&!persist(p,null,s)&&!persist(p,r,null),"null scope refused");RebirthStablePlayerIdentity.Ready=false;A(!persist(p,r,s),"missing native owner identity refused");RebirthStablePlayerIdentity.Ready=true;
}var cancelPlayer=new EntityPlayer();var cancelRecord=new RebirthWorldCharacterRecord{Origin=new Origin{CreationId=Guid.NewGuid().ToString("N")}};var cancelled=new Session{CreationId=cancelRecord.Origin.CreationId};RebirthWorldCharacterService.Record=cancelRecord;Reading.Active[1]=cancelled;RebirthWorldCharacterRepository.Save=false;
Reading.Stop(cancelPlayer,cancelled);A(cancelled.CancelAwaitingSave&&Reading.Active.ContainsKey(1)&&Reading.Notices==1,"failed cancellation checkpoint retained without reading");int attempts=RebirthWorldCharacterRepository.Saves;
A(Reading.Retry(cancelPlayer,cancelRecord,cancelled,.3f)&&RebirthWorldCharacterRepository.Saves==attempts,"cancellation retry throttled");A(Reading.Retry(cancelPlayer,cancelRecord,cancelled,.7f)&&Reading.Active.ContainsKey(1)&&Reading.Notices==1,"retry failure retains stopped session without duplicate message");RebirthWorldCharacterRepository.Save=true;A(Reading.Retry(cancelPlayer,cancelRecord,cancelled,1f)&&!Reading.Active.ContainsKey(1)&&Reading.Notices==1,"successful stopped save removes retained session without second message");A(!Reading.Retry(cancelPlayer,cancelRecord,new Session(),1f),"ordinary session bypasses stopped retry");Console.WriteLine("PASS5 actual physical cancellation checkpoint assertions; native save/HUD/notification adapters doubled.");var audioCancelled=new Session{CreationId=cancelRecord.Origin.CreationId};Audio.Active[1]=audioCancelled;RebirthWorldCharacterRepository.Save=false;
Audio.Stop(cancelPlayer,audioCancelled);A(audioCancelled.CancelAwaitingSave&&audioCancelled.Paused&&Audio.Active.ContainsKey(1)&&Audio.Notices==1,"failed audio cancellation retains stopped session");attempts=RebirthWorldCharacterRepository.Saves;A(Audio.Retry(cancelPlayer,cancelRecord,audioCancelled,.3f)&&RebirthWorldCharacterRepository.Saves==attempts,"audio cancellation retry throttled");A(Audio.Retry(cancelPlayer,cancelRecord,audioCancelled,.7f)&&Audio.Active.ContainsKey(1)&&Audio.Notices==1,"failed audio retry retains session without duplicate message");RebirthWorldCharacterRepository.Save=true;A(Audio.Retry(cancelPlayer,cancelRecord,audioCancelled,1f)&&!Audio.Active.ContainsKey(1)&&Audio.Notices==1,"successful audio stopped checkpoint removes once");A(!Audio.Retry(cancelPlayer,cancelRecord,new Session(),1f),"ordinary audio session bypasses cancelled retry");Console.WriteLine("PASS5 actual audiobook cancellation checkpoint assertions; native save/HUD/notification adapters doubled.");Console.WriteLine("PASS16 actual reading/audio persisted-progress assertions: latest fraction, false/throwing save, character scope, completion fraction removal, null scope and missing identity. Native identity/repository/disk adapters doubled.");}}