// CODEC
namespace HarmonyLib {[AttributeUsage(AttributeTargets.Class)]class HarmonyPatch:Attribute{public HarmonyPatch(Type t,string n){}}class HarmonyPrefix:Attribute{}class HarmonyPostfix:Attribute{}}
public class PooledBinaryReader:BinaryReader{public PooledBinaryReader():base(new MemoryStream()){}public void SetBaseStream(Stream s){m_stream=s;}private Stream m_stream;public override byte ReadByte(){return (byte)m_stream.ReadByte();}public override ushort ReadUInt16(){return (ushort)(ReadByte()|ReadByte()<<8);}}
public class PooledBinaryWriter{public Stream BaseStream;}
public class Pool{public PooledBinaryReader AllocSync(bool reset){return new PooledBinaryReader();}}
public static class MemoryPools{public static Pool poolBinaryReader=new Pool();}
public class ItemValue {public int type;}
public class Props {public string Materials;public bool Contains(string a,string b){return Materials!=null;}public string GetString(string a,string b){return Materials;}}
public class Block {public Props Properties=new Props();public static Block GetBlockByName(string name){return new Block{Properties=new Props{Materials=name=="forge"?"iron":null}};}}
public class ItemClass {public int Id=42;public static ItemClass GetItemClass(string name){return name=="unit_iron"?new ItemClass():null;}}
public class ItemStack{public ItemValue itemValue=new ItemValue();public int count;public ItemStack Read(PooledBinaryReader r){count=r.ReadByte();itemValue.type=count==200?42:0;return this;}}
public class Recipe{public string Job;public int Count;}
public class RecipeQueueItem{public Recipe Recipe;public int StartingEntityId,Multiplier,AmountToRepair;public object RepairItem;public void Read(PooledBinaryReader r){r.ReadUInt16();StartingEntityId=r.ReadByte();Multiplier=r.ReadByte();byte job=r.ReadByte();Recipe=new Recipe{Job=job==1?"a":"b",Count=r.ReadByte()};if(r.ReadByte()!=0)RepairItem=new object();}}
public class RebirthStationGridAdmission{public bool TryGetPhysicalSlotCount(out int count){count=3;return true;}public string JobId="a";public bool MatchesQueuedObservation(string c,int x,int y,int z,string b,ItemStack[] input,Recipe recipe,int multiplier){return input.Length==(b=="forge"?3:1)&&input[0].count==7&&recipe.Count==9&&multiplier==1;}}
public static class RebirthStationGridQueue{public static bool TryGetJobId(Recipe r,out string id){id=r.Job;return true;}}
public class TileEntityWorkstation{public ItemStack[] Input;public void writeItemStackArray(){}public void writeRecipeStackArray(){}}
public static class RebirthStationSnapshotEvidence{public static long StartStationSpan(object t,Stream s){return -1;}public static void CaptureStationSpan(object t,Stream s,long p,bool i){}}
class Check{
static void A(bool value,string why){if(!value)throw new Exception(why);}
static bool Match(byte[] i,byte[] q){return RebirthStationSerializedContents.Matches(i,q,new RebirthStationGridAdmission(),"c",0,0,0,"workbench",5);}
static void Main(){byte[] input={1,7},queue={1,2,0,5,1,1,9,0};A(Match(input,queue),"exact serialized pair");A(!Match(new byte[]{1,8},queue),"different serialized input");A(!Match(new byte[]{10},queue),"input count bound");A(!Match(input,new byte[]{17}),"queue bound");var bad=(byte[])queue.Clone();bad[1]=3;A(!Match(input,bad),"unknown queue version");bad=(byte[])queue.Clone();bad[3]=6;A(!Match(input,bad),"wrong queued owner");bad=(byte[])queue.Clone();bad[7]=1;A(!Match(input,bad),"repair entry refusal");bad=new byte[queue.Length+1];Buffer.BlockCopy(queue,0,bad,0,queue.Length);A(!Match(input,bad),"trailing queue bytes");bad=new byte[15];bad[0]=2;Buffer.BlockCopy(queue,1,bad,1,7);Buffer.BlockCopy(queue,1,bad,8,7);A(!Match(input,bad),"duplicate serialized job");A(RebirthStationSerializedContents.Matches(new byte[]{4,7,0,0,200},queue,new RebirthStationGridAdmission(),"c",0,0,0,"forge",5),"forge physical comparison excludes validated unit suffix");A(!RebirthStationSerializedContents.Matches(new byte[]{4,7,0,0,201},queue,new RebirthStationGridAdmission(),"c",0,0,0,"forge",5),"wrong unit suffix rejected");A(!RebirthStationSerializedContents.Matches(new byte[]{3,7,0,0},queue,new RebirthStationGridAdmission(),"c",0,0,0,"forge",5),"missing configured material suffix rejected");A(RebirthStationSerializedContents.Matches(new byte[]{4,7,0,0,0},queue,new RebirthStationGridAdmission(),"c",0,0,0,"forge",5),"zero material total decoded as native empty accepted");Console.WriteLine("PASS actual serialized station comparator: version/count/owner/exact inputs/repair/duplicate/trailing refusal; ItemStack and queue native codecs doubled");}
}