#requires -Version 7.0
$ErrorActionPreference='Stop'
$root=Split-Path -Parent (Split-Path -Parent $PSScriptRoot)
$source=[IO.File]::ReadAllText((Join-Path $root 'Scripts/Survivor/Persistence/RebirthWorldCharacterRepository.cs'))
$start=$source.IndexOf('    internal static bool HasSavedStationTerminalIntent(')
$end=$source.IndexOf('    // Current final-file evidence;', $start)
if($start-lt0-or$end-le$start){throw 'Actual method boundary missing'}
$method=$source.Substring($start,$end-$start)
$intent=[IO.File]::ReadAllText((Join-Path $root 'Scripts/Survivor/Persistence/RebirthStationTerminalIntent.cs'))
$fixture=@"
public class RebirthStablePlayerIdentity{public string StorageKey="owner";}public class RebirthStationGridAdmission{public bool IsPublicationAttempted=true;public string JobId="job",CreationId="creation";public int Revision;public XElement Write(){return new XElement("admission",new XAttribute("job",JobId),new XAttribute("creation",CreationId),new XAttribute("revision",Revision));}}
public class Origin{public string CreationId="creation";}public class RebirthStationCancellationRefund{public int Count=12;public XElement Write(){return new XElement("refund",new XAttribute("count",Count));}public static bool TryReadStored(XElement n,RebirthStationGridAdmission a,RebirthStationTerminalIntent i,out RebirthStationCancellationRefund r){r=new RebirthStationCancellationRefund();return !i.IsCompletion;}}public class RebirthStationCancellationAttempt{public string Fingerprint="before";public bool Valid=true;public XElement Write(){return new XElement("attempt",new XAttribute("fingerprint",Fingerprint),new XAttribute("valid",Valid));}public static bool TryRead(XElement n,RebirthStationGridAdmission a,RebirthStationTerminalIntent i,RebirthStationCancellationRefund r,out RebirthStationCancellationAttempt attempt){attempt=new RebirthStationCancellationAttempt();return (bool)n.Attribute("valid");}}public class RebirthStationCancellationPublication{public string Payload="exact";public bool Valid=true;public XElement Write(){return new XElement("publication",new XAttribute("payload",Payload),new XAttribute("valid",Valid));}public static bool TryRead(XElement node,RebirthStationGridAdmission a,RebirthStationTerminalIntent i,RebirthStationCancellationRefund r,RebirthStationCancellationAttempt t,out RebirthStationCancellationPublication p){p=new RebirthStationCancellationPublication();return (bool)node.Attribute("valid");}}
public class RebirthStationRefundDelivery{public string Owner="owner",Plan="exact";public bool Valid=true;public XElement Write(){return new XElement("delivery",new XAttribute("owner",Owner),new XAttribute("plan",Plan),new XAttribute("valid",Valid));}public static bool TryRead(XElement n,string owner,RebirthStationGridAdmission a,RebirthStationTerminalIntent i,RebirthStationCancellationRefund r,RebirthStationCancellationAttempt t,RebirthStationCancellationPublication p,out RebirthStationRefundDelivery d){d=new RebirthStationRefundDelivery();return (bool)n.Attribute("valid")&&(string)n.Attribute("owner")==owner;}}
public class Progression{public Dictionary<string,RebirthStationRefundDelivery> StationRefundDeliveries=new Dictionary<string,RebirthStationRefundDelivery>();public Dictionary<string,RebirthStationCancellationPublication> StationCancellationPublications=new Dictionary<string,RebirthStationCancellationPublication>();public Dictionary<string,RebirthStationCancellationAttempt> StationCancellationAttempts=new Dictionary<string,RebirthStationCancellationAttempt>();public Dictionary<string,RebirthStationCancellationRefund> StationCancellationRefunds=new Dictionary<string,RebirthStationCancellationRefund>();public Dictionary<string,RebirthStationGridAdmission> StationPreparations=new Dictionary<string,RebirthStationGridAdmission>();public Dictionary<string,RebirthStationTerminalIntent> StationTerminalIntents=new Dictionary<string,RebirthStationTerminalIntent>();}public class Record{public Origin Origin=new Origin();public Progression Progression=new Progression();}public static class RebirthSurvivorRequestScope{public static bool Matches(string a,string b){return a==b;}}
public static class ReadbackHost{static bool serverAuthority=true,Load=true,Migrated,Throw;static string Path="final";static Record Saved;static object Gate=new object();static string GetPath(string key){return Path;}static object GetWriteLock(string key){return Gate;}static bool TryLoadValidatedRecord(string p,RebirthStablePlayerIdentity i,out Record r,out bool migrated,out string x,out string y){if(Throw)throw new Exception();r=Saved;migrated=Migrated;x=y=null;return Load;}
$method
static int checks;static void Check(bool value){checks++;if(!value)throw new Exception("readback "+checks);}public static string Run(){var identity=new RebirthStablePlayerIdentity();var admission=new RebirthStationGridAdmission();RebirthStationTerminalIntent completion,cancel;RebirthStationTerminalIntent.TryCreate(admission,true,42,out completion);RebirthStationTerminalIntent.TryCreate(admission,false,42,out cancel);Saved=new Record();Saved.Progression.StationPreparations[admission.JobId]=admission;Saved.Progression.StationTerminalIntents[admission.JobId]=completion;
Check(HasSavedStationTerminalIntent(identity,admission,completion));Check(!HasSavedStationTerminalIntent(identity,admission,cancel));
serverAuthority=false;Check(!HasSavedStationTerminalIntent(identity,admission,completion));serverAuthority=true;Migrated=true;Check(!HasSavedStationTerminalIntent(identity,admission,completion));Migrated=false;Load=false;Check(!HasSavedStationTerminalIntent(identity,admission,completion));Load=true;
Path="";Check(!HasSavedStationTerminalIntent(identity,admission,completion));Path="final";Saved.Origin.CreationId="foreign";Check(!HasSavedStationTerminalIntent(identity,admission,completion));Saved.Origin.CreationId="creation";
Saved.Progression.StationPreparations[admission.JobId]=new RebirthStationGridAdmission{Revision=1};Check(!HasSavedStationTerminalIntent(identity,admission,completion));Saved.Progression.StationPreparations[admission.JobId]=admission;
Saved.Progression.StationTerminalIntents.Clear();Check(!HasSavedStationTerminalIntent(identity,admission,completion));Saved.Progression.StationTerminalIntents[admission.JobId]=completion;
Throw=true;Check(!HasSavedStationTerminalIntent(identity,admission,completion));Throw=false;Check(!HasSavedStationTerminalIntent(null,admission,completion));Check(HasSavedStationTerminalIntent(identity,admission,completion));var refund=new RebirthStationCancellationRefund();Saved.Progression.StationTerminalIntents[admission.JobId]=cancel;Saved.Progression.StationCancellationRefunds[admission.JobId]=refund;
Check(HasSavedStationCancellationRefund(identity,admission,cancel,refund));Check(!HasSavedStationCancellationRefund(identity,admission,completion,refund));
Check(!HasSavedStationCancellationRefund(identity,admission,cancel,new RebirthStationCancellationRefund{Count=99}));Saved.Progression.StationCancellationRefunds.Clear();Check(!HasSavedStationCancellationRefund(identity,admission,cancel,refund));
Saved.Progression.StationCancellationRefunds[admission.JobId]=refund;var attempt=new RebirthStationCancellationAttempt();Check(!HasSavedStationCancellationAttempt(identity,admission,cancel,refund,attempt));Saved.Progression.StationCancellationAttempts[admission.JobId]=attempt;
Check(HasSavedStationCancellationAttempt(identity,admission,cancel,refund,attempt));Check(!HasSavedStationCancellationAttempt(identity,admission,cancel,refund,new RebirthStationCancellationAttempt{Fingerprint="foreign"}));
Check(!HasSavedStationCancellationAttempt(identity,admission,cancel,refund,new RebirthStationCancellationAttempt{Valid=false}));Migrated=true;Check(!HasSavedStationCancellationAttempt(identity,admission,cancel,refund,attempt));Migrated=false;
Saved.Progression.StationCancellationRefunds.Clear();Check(!HasSavedStationCancellationAttempt(identity,admission,cancel,refund,attempt));Saved.Progression.StationCancellationRefunds[admission.JobId]=refund;
Check(HasSavedStationCancellationAttempt(identity,admission,cancel,refund,attempt));
var publication=new RebirthStationCancellationPublication();Check(!HasSavedStationCancellationPublication(identity,admission,cancel,refund,attempt,publication));Saved.Progression.StationCancellationPublications[admission.JobId]=publication;Check(HasSavedStationCancellationPublication(identity,admission,cancel,refund,attempt,publication));Check(!HasSavedStationCancellationPublication(identity,admission,cancel,refund,attempt,new RebirthStationCancellationPublication{Payload="changed"}));Check(!HasSavedStationCancellationPublication(identity,admission,cancel,refund,attempt,new RebirthStationCancellationPublication{Valid=false}));Migrated=true;Check(!HasSavedStationCancellationPublication(identity,admission,cancel,refund,attempt,publication));Migrated=false;Saved.Progression.StationCancellationAttempts.Clear();Check(!HasSavedStationCancellationPublication(identity,admission,cancel,refund,attempt,publication));Saved.Progression.StationCancellationAttempts[admission.JobId]=attempt;Check(HasSavedStationCancellationPublication(identity,admission,cancel,refund,attempt,publication));
var delivery=new RebirthStationRefundDelivery();Check(!HasSavedStationRefundDelivery(identity,admission,cancel,refund,attempt,publication,delivery));Saved.Progression.StationRefundDeliveries[admission.JobId]=delivery;Check(HasSavedStationRefundDelivery(identity,admission,cancel,refund,attempt,publication,delivery));Check(!HasSavedStationRefundDelivery(identity,admission,cancel,refund,attempt,publication,new RebirthStationRefundDelivery{Owner="foreign"}));Check(!HasSavedStationRefundDelivery(identity,admission,cancel,refund,attempt,publication,new RebirthStationRefundDelivery{Plan="changed"}));Check(!HasSavedStationRefundDelivery(identity,admission,cancel,refund,attempt,publication,new RebirthStationRefundDelivery{Valid=false}));Migrated=true;Check(!HasSavedStationRefundDelivery(identity,admission,cancel,refund,attempt,publication,delivery));Migrated=false;Saved.Progression.StationCancellationPublications.Clear();Check(!HasSavedStationRefundDelivery(identity,admission,cancel,refund,attempt,publication,delivery));Saved.Progression.StationCancellationPublications[admission.JobId]=publication;Check(HasSavedStationRefundDelivery(identity,admission,cancel,refund,attempt,publication,delivery));
return "PASS "+checks+" actual repository terminal intent witness with storage/admission doubles; no native final-file read";}}
"@
Add-Type -TypeDefinition ($intent+$fixture)
[ReadbackHost]::Run()