using System;using System.IO;using System.Collections.Generic;using System.Linq;
public class PooledBinaryWriter:BinaryWriter {public PooledBinaryWriter(Stream s):base(s){}}public class PooledBinaryReader:BinaryReader {public PooledBinaryReader(Stream s):base(s){}}
public enum NetPackageDirection {Both,ToServer,ToClient}public abstract class NetPackage {public ClientInfo Sender;public bool AllowedBeforeAuth;public virtual bool ShouldProcess(World w,GameManager g)=>true;public virtual void HandleSkipped(World w,GameManager g){}public virtual NetPackageDirection PackageDirection=>NetPackageDirection.Both;public virtual void write(PooledBinaryWriter w){}public abstract void read(PooledBinaryReader r);public abstract void ProcessPackage(World w,GameManager g);}public static class NetPackageManager{public static int Freed;public static void FreePackage(NetPackage p){Freed++;}public static T GetPackage<T>()where T:NetPackage,new()=>new();}
public interface INetConnection{bool IsDisconnected();void GetPackages(List<NetPackage> list);}public class Peer:INetConnection{public bool Dead;public List<NetPackage> Incoming=new();public bool IsDisconnected()=>Dead;public void GetPackages(List<NetPackage> list){list.Clear();list.AddRange(Incoming);Incoming.Clear();}}
public class ClientInfo{public int ClientNumber,entityId;public bool loginDone=true,bAttachedToEntity=true,disconnecting;public INetConnection[] netConnection;public NetPackage Sent;public void SendPackage(NetPackage p){Sent=p;}}
public class ClientInfoCollection{public Dictionary<int,ClientInfo> Entries=new();public ClientInfo ForClientNumber(int n)=>Entries.TryGetValue(n,out var c)?c:null;}
public partial class ConnectionManager{public List<NetPackage> packagesToProcess=new();public bool IsServer;public ClientInfoCollection Clients=new();public INetConnection[] connectionToServer;public NetPackage Sent;public void SendToServer(NetPackage p){Sent=p;}}
public static class SingletonMonoBehaviour<T> where T:new(){public static T Instance=new T();}public class GameManager{public static GameManager Instance;public World World;}
public class WorldState{public string Guid;}public class World{public WorldState worldState=new();public bool Remote;public Dictionary<int,EntityPlayer> Actors=new();public EntityPlayerLocal Primary;public bool IsRemote()=>Remote;public EntityPlayer GetEntity(int id)=>Actors.TryGetValue(id,out var p)?p:null;public EntityPlayerLocal GetPrimaryPlayer()=>Primary;}
public class EntityPlayer{public int entityId;public World world;public bool Dead;public bool IsDead()=>Dead;}public class EntityPlayerLocal:EntityPlayer{public bool Spawned=true;public bool IsSpawned()=>Spawned;}
public class RebirthWorldCharacterRecord{public Origin Origin=new();}public class Origin{public string CreationId;}public static class RebirthWorldCharacterService{public static RebirthWorldCharacterRecord Owner;public static bool TryGet(ClientInfo c,out RebirthWorldCharacterRecord o){o=Owner;return o!=null;}}
public static class RebirthSurvivorClientState{public static string Creation;public static Action Callback;public static string GetProjectedCreationId(EntityPlayer p){var result=Creation;Callback?.Invoke();return result;}}
public static class ThreadManager{public static bool Main=true;public static bool IsMainThread()=>Main;public static void AddSingleTaskMainThread(string key,Action<object> action){action(null);}}public enum EnumGamePrefs{GameGuidClient}public static class GamePrefs{public static string World;public static string GetString(EnumGamePrefs p)=>World;} public static class Log{public static void Error(string x){}public static void Warning(string x){}}