using Old=Before.RebirthTraderJobCompletionStats;
using New=After.RebirthTraderJobCompletionStats;
public class BaseObjective{} public class ObjectiveFetchFromTreasure:BaseObjective{} public class ObjectiveTreasureChest:BaseObjective{} public class ObjectiveFetchFromContainer:BaseObjective{} public class ObjectiveClearSleepers:BaseObjective{} public class ObjectivePOIBlockActivate:BaseObjective{}
public class QuestClass { public string ID,QuestType; public int DifficultyTier; }
public class Quest { public enum QuestState {NotStarted,InProgress,Completed} public enum PositionDataTypes{TraderPosition} public QuestClass QuestClass; public string ID,Prefab;public QuestState CurrentState; public int QuestGiverID;public List<BaseObjective> Objectives;public Dictionary<PositionDataTypes,int> PositionData;public string GetPOIName()=>Prefab; }
public class QuestJournal { public List<Quest> quests=new(); }
static class RebirthUtilities { public static bool IsVanillaTrader(int id)=>id==1; }
static class RebirthInfestedJobsRuntimePolicy {public static bool HideIdentity; public static bool IsInfestedId(string id)=>!string.IsNullOrEmpty(id)&&id.IndexOf("_infested",StringComparison.OrdinalIgnoreCase)>=0;}
static class RebirthTraderPoiHistory {public static int GetTier(Quest q)=>q?.QuestClass==null?1:Math.Max(1,Math.Min(6,q.QuestClass.DifficultyTier));}
struct RebirthTraderPoiIdentity {public string PrefabName;public static RebirthTraderPoiIdentity FromQuest(Quest q)=>new(){PrefabName=q.Prefab};public static string Normalize(string s)=>string.IsNullOrWhiteSpace(s)?string.Empty:s.Trim().ToLowerInvariant();}
static class Program {
 static Random r=new(20261010);
 static Quest Make(){if(r.Next(20)==0)return null;return new(){QuestClass=r.Next(20)==0?null:new(){ID=new[]{"TIER1_CLEAR","tier2_fetch_clear_infested","custom","tier3_buried_supplies","tier4_restore_power",null,"tier5_fetch"}[r.Next(7)],QuestType=r.Next(5)==0?"special":"",DifficultyTier=r.Next(0,8)},ID="custom",Prefab=new[]{"house"," HOUSE ","shop",null,""}[r.Next(5)],CurrentState=(Quest.QuestState)r.Next(3),QuestGiverID=r.Next(3),Objectives=new(){r.Next(2)==0?new ObjectiveFetchFromContainer():new ObjectiveClearSleepers(),r.Next(2)==0?new ObjectivePOIBlockActivate():new BaseObjective()},PositionData=r.Next(2)==0?null:new(){{Quest.PositionDataTypes.TraderPosition,1}}};}
 static void Check(QuestJournal j,Quest offered){if(Old.GetCompletionCount(j,offered)!=New.GetCompletionCount(j,offered))throw new Exception("Count mismatch");foreach(var q in j.quests)if(Old.IsRecognizedNormalTraderJob(q)!=New.IsRecognizedNormalTraderJob(q))throw new Exception("Recognition mismatch");}
 static long Alloc(Func<int> a){for(int i=0;i<20;i++)a();long b=GC.GetAllocatedBytesForCurrentThread();for(int i=0;i<1000;i++)a();return GC.GetAllocatedBytesForCurrentThread()-b;}
 static void Main(){for(int t=0;t<1000;t++){var j=new QuestJournal();for(int i=0;i<100;i++)j.quests.Add(Make());var offered=Make();RebirthInfestedJobsRuntimePolicy.HideIdentity=t%2==0;Check(j,offered);foreach(var q in j.quests)if(q!=null)q.CurrentState=Quest.QuestState.Completed;Check(j,offered);}Console.WriteLine("PASS 2000 history comparisons and public recognition parity, including state mutations and HideIdentity.");var dense=new QuestJournal();for(int i=0;i<1000;i++)dense.quests.Add(new(){QuestClass=new(){ID="TIER1_CLEAR",DifficultyTier=1},CurrentState=Quest.QuestState.Completed,Prefab="house"});var offer=dense.quests[0];Check(dense,offer);Console.WriteLine($"1000 reads of1000 completed mixed-case quests: beforeBytes={Alloc(()=>Old.GetCompletionCount(dense,offer))}, afterBytes={Alloc(()=>New.GetCompletionCount(dense,offer))}");Console.WriteLine("Actual old/new complete class; .NET9 with native identity, quest and policy doubles; native runtime/FPS not measured.");}
}
