using System;using System.IO;using System.Xml.Linq;
namespace UnityEngine.Scripting{public class PreserveAttribute:Attribute{}}
public enum NetPackageDirection{ToServer,ToClient}
public class PooledBinaryReader:BinaryReader{public PooledBinaryReader(Stream s):base(s,System.Text.Encoding.UTF8,true){}}
public class PooledBinaryWriter:BinaryWriter{public PooledBinaryWriter(Stream s):base(s,System.Text.Encoding.UTF8,true){}}
public abstract class NetPackage{
 public ClientInfo Sender;public abstract NetPackageDirection PackageDirection{get;}public abstract void read(PooledBinaryReader r);public virtual void write(PooledBinaryWriter w){w.Write((ushort)0);}public abstract void ProcessPackage(World w,GameManager g);
 public bool ValidEntityIdForSender(int id)=>Sender!=null&&Sender.EntityId==id;
}
public class ClientInfo{public int EntityId=7;}
public class EntityPlayer{public int entityId=7;}
public class World{public bool Remote;public EntityPlayer Player=new();public bool IsRemote()=>Remote;public object GetEntity(int id)=>id==Player.entityId?Player:null;}
public class GameManager{public static GameManager Instance;public World World;}
public class SingletonMonoBehaviour<T>{public static T Instance;}
public class ConnectionManager{public bool IsServer=true;public int Sends,Attached;public NetPackageRebirthGearSettled Last;public void SendPackage(NetPackageRebirthGearSettled p,int _attachedToEntityId){Sends++;Attached=_attachedToEntityId;Last=p;}public void SendPackage(NetPackageRebirthGearOfferFragment p,int _attachedToEntityId){}}
public static class NetPackageManager{public static bool Missing;public static int GetPackageId(Type t){if(Missing)throw new InvalidOperationException("mapping");return 1;}public static T GetPackage<T>()where T:new()=>new();}
public class RebirthGearSettlement{public XElement Write()=>new("terminal");public bool Applied;public string CreationId,TransactionId;}
public class NetPackageRebirthGearSettled{public RebirthGearSettlement Value;public NetPackageRebirthGearSettled Setup(int id,RebirthGearSettlement v){Value=v;return this;}}
public enum RebirthGearTransferPhase{Prepared,OwnerApplied,GearCommitted}
public class RebirthGearTransferState{public string TransactionId,CreationId;public long ExpectedRevision;public bool HasAllRecoveryPublicationReceipts;public XElement ToXml()=>new XElement("offer",new XAttribute("id",TransactionId));}
public class GearSupport{public RebirthGearTransferState PendingGearTransfer;public RebirthGearTransferPhase GearTransferPhase;}
public class GearRecord{public GearSupport Support=new();}
public static class RebirthRemoteGearInventorySource{
 public static GearRecord Record;public static bool Valid=true;public static bool TryResolve(EntityPlayer p,ClientInfo s,string c,out GearRecord r){r=Record;return Valid&&p!=null&&s!=null&&s.EntityId==p.entityId&&r!=null&&c==RebirthRemoteGearAppliedConfirmation.Creation;}}
public static class RebirthWorldCharacterRepository{public static bool Cached=true;public static bool IsCurrentCachedRecord(GearRecord r)=>Cached&&ReferenceEquals(r,RebirthRemoteGearInventorySource.Record);}
public static class RebirthRemoteGearPreparation{public static bool TryReplayBoundRetained(EntityPlayer p,ClientInfo s,string marker,out RebirthGearTransferState o,out RebirthGearTransferPhase phase){phase=RebirthGearTransferPhase.Prepared;return TryReplayBound(p,s,marker,out o);}public static bool TryReplayBound(EntityPlayer p,ClientInfo s,string marker,out RebirthGearTransferState o){o=null;return false;}public static bool TryReplay(EntityPlayer p,ClientInfo s,string c,out RebirthGearTransferState o){o=null;return false;}}
public static class RebirthGearOfferWireCodec{public static bool TryEncode(RebirthGearTransferState s,out byte[] b){b=null;return false;}}
public static class RebirthGearOfferAssembly{public const int ChunkBytes=4096;public static string ComputeDigest(byte[] b)=>"unused";}
public class RebirthGearOfferFragment{public static bool TryCreate(string c,Guid t,long r,int n,string h,int i,byte[] b,out RebirthGearOfferFragment f){f=null;return false;}}
public class NetPackageRebirthGearOfferFragment{public NetPackageRebirthGearOfferFragment Setup(int id,RebirthGearOfferFragment f)=>this;}
public static class RebirthGearRecoveryDispatcher{
 public static int Calls;public static bool Allowed=true,Complete;public static Action OnAdvance;
 public static bool TryAdvance(EntityPlayer p,ClientInfo s,string c,string t){Calls++;OnAdvance?.Invoke();if(!Allowed)return false;if(Complete)RebirthRemoteGearInventorySource.Record.Support.PendingGearTransfer.HasAllRecoveryPublicationReceipts=true;return true;}}
public static class RebirthRemoteGearAppliedConfirmation{public static bool TryGetBoundTerminalOriginal(EntityPlayer p,ClientInfo s,string m,out RebirthGearTransferState o,out RebirthGearSettlement t){o=null;t=null;return false;}
 public static bool Ready,Applied=true,Confirmed=true,Committed=true,FinishAllowed=true;public static int Confirms,Commits,Finishes;public static Action OnConfirm,OnFinish;
 public static string Creation,Transaction;
 public static bool TryGetSettlement(EntityPlayer p,ClientInfo s,string c,string t,out RebirthGearSettlement v){v=null;if(!Ready||p==null||s==null||s.EntityId!=p.entityId||c!=Creation||t!=Transaction)return false;v=new(){Applied=Applied,CreationId=c,TransactionId=t};return true;}
 public static bool TryConfirm(EntityPlayer p,ClientInfo s,string c,string t){Confirms++;OnConfirm?.Invoke();return Confirmed;}
 public static bool TryCommit(EntityPlayer p,ClientInfo s,string c,string t){Commits++;if(!Committed)return false;RebirthRemoteGearInventorySource.Record.Support.GearTransferPhase=RebirthGearTransferPhase.GearCommitted;return true;}
 public static bool TryFinishRecovery(EntityPlayer p,ClientInfo s,string c,string t){Finishes++;OnFinish?.Invoke();var pending=RebirthRemoteGearInventorySource.Record?.Support.PendingGearTransfer;if(!FinishAllowed||pending==null||!pending.HasAllRecoveryPublicationReceipts)return false;Ready=true;RebirthRemoteGearInventorySource.Record.Support.PendingGearTransfer=null;return true;}
}
class Program{
 static int checks;static World world;static ConnectionManager manager;static ClientInfo sender;static string creation;static Guid tx;
 static void Check(bool ok,string label){if(!ok)throw new Exception(label);checks++;}
 static void Throws(Action action,string label){bool thrown=false;try{action();}catch(ArgumentException){thrown=true;}catch(InvalidDataException){thrown=true;}catch(EndOfStreamException){thrown=true;}catch(InvalidOperationException){thrown=true;}Check(thrown,label);}
 static void Reset(bool complete=false){world=new();GameManager.Instance=new(){World=world};manager=new();SingletonMonoBehaviour<ConnectionManager>.Instance=manager;sender=new();creation=Guid.NewGuid().ToString("N");tx=Guid.NewGuid();NetPackageManager.Missing=false;RebirthRemoteGearInventorySource.Valid=true;RebirthWorldCharacterRepository.Cached=true;RebirthRemoteGearInventorySource.Record=new(){Support=new(){PendingGearTransfer=new(){TransactionId=tx.ToString("N"),CreationId=creation,HasAllRecoveryPublicationReceipts=complete},GearTransferPhase=RebirthGearTransferPhase.Prepared}};RebirthRemoteGearAppliedConfirmation.Ready=false;RebirthRemoteGearAppliedConfirmation.Applied=RebirthRemoteGearAppliedConfirmation.Confirmed=RebirthRemoteGearAppliedConfirmation.Committed=RebirthRemoteGearAppliedConfirmation.FinishAllowed=true;RebirthRemoteGearAppliedConfirmation.Confirms=RebirthRemoteGearAppliedConfirmation.Commits=RebirthRemoteGearAppliedConfirmation.Finishes=0;RebirthRemoteGearAppliedConfirmation.OnConfirm=RebirthRemoteGearAppliedConfirmation.OnFinish=null;RebirthRemoteGearAppliedConfirmation.Creation=creation;RebirthRemoteGearAppliedConfirmation.Transaction=tx.ToString("N");RebirthGearRecoveryDispatcher.Calls=0;RebirthGearRecoveryDispatcher.Allowed=true;RebirthGearRecoveryDispatcher.Complete=false;RebirthGearRecoveryDispatcher.OnAdvance=null;}
 static NetPackageRebirthGearAppliedRequest Request(){var p=new NetPackageRebirthGearAppliedRequest().Setup(7,creation,tx);p.Sender=sender;return p;}
 static byte[] Encode(NetPackageRebirthGearAppliedRequest p){using var s=new MemoryStream();using var w=new PooledBinaryWriter(s);p.write(w);return s.ToArray();}
 static NetPackageRebirthGearAppliedRequest Decode(byte[] bytes){using var s=new MemoryStream(bytes);using var r=new PooledBinaryReader(s);r.ReadUInt16();var p=new NetPackageRebirthGearAppliedRequest();p.read(r);Check(s.Position==s.Length,"exact wire consumed");p.Sender=sender;return p;}
 static void Main(){
 Reset(true);var p=Request();var wire=Encode(p);Check(p.PackageDirection==NetPackageDirection.ToServer&&wire.Length==p.GetLength(),"direction/frame length");Decode(wire).ProcessPackage(world,GameManager.Instance);Check(manager.Sends==1&&manager.Last.Value.Applied&&manager.Last.Value.TransactionId==tx.ToString("N")&&RebirthGearRecoveryDispatcher.Calls==0,"saved empty/completed recovery settles exact identity without publication");Request().ProcessPackage(world,GameManager.Instance);Check(manager.Sends==2&&RebirthRemoteGearAppliedConfirmation.Commits==1,"saved terminal replay no reapplication");
 Reset();Request().ProcessPackage(world,GameManager.Instance);Check(RebirthGearRecoveryDispatcher.Calls==1&&manager.Sends==0&&RebirthRemoteGearInventorySource.Record.Support.PendingGearTransfer!=null,"one first publication retains pending and no ack");RebirthGearRecoveryDispatcher.Complete=true;Request().ProcessPackage(world,GameManager.Instance);Check(RebirthGearRecoveryDispatcher.Calls==2&&manager.Sends==1&&RebirthRemoteGearInventorySource.Record.Support.PendingGearTransfer==null,"original followup complete saved receipts settle");
 Reset();RebirthGearRecoveryDispatcher.Allowed=false;Request().ProcessPackage(world,GameManager.Instance);Check(manager.Sends==0&&RebirthRemoteGearInventorySource.Record.Support.PendingGearTransfer!=null&&RebirthGearRecoveryDispatcher.Calls==1,"failed or uncertain publication remains pending");
 Reset();RebirthGearRecoveryDispatcher.Complete=true;RebirthRemoteGearAppliedConfirmation.FinishAllowed=false;Request().ProcessPackage(world,GameManager.Instance);Check(manager.Sends==0&&RebirthRemoteGearInventorySource.Record.Support.PendingGearTransfer!=null,"failed terminal save retains custody despite receipt readiness");
 Reset();RebirthRemoteGearAppliedConfirmation.Confirmed=false;Request().ProcessPackage(world,GameManager.Instance);Check(RebirthRemoteGearAppliedConfirmation.Commits==0&&RebirthGearRecoveryDispatcher.Calls==0&&manager.Sends==0,"failed saved owner confirmation prevents publication");
 Reset();RebirthRemoteGearAppliedConfirmation.Committed=false;Request().ProcessPackage(world,GameManager.Instance);Check(RebirthGearRecoveryDispatcher.Calls==0&&manager.Sends==0,"failed saved gear commit prevents publication");
 Reset();RebirthRemoteGearAppliedConfirmation.OnConfirm=()=>SingletonMonoBehaviour<ConnectionManager>.Instance=new();Request().ProcessPackage(world,GameManager.Instance);Check(RebirthRemoteGearAppliedConfirmation.Commits==0&&RebirthGearRecoveryDispatcher.Calls==0&&manager.Sends==0,"manager change during confirmation refuses next effect");
 Reset();RebirthGearRecoveryDispatcher.OnAdvance=()=>GameManager.Instance.World=new();Request().ProcessPackage(world,GameManager.Instance);Check(manager.Sends==0&&RebirthRemoteGearAppliedConfirmation.Finishes==1,"world change during publication refuses finishing");
 Reset();RebirthRemoteGearAppliedConfirmation.OnFinish=()=>SingletonMonoBehaviour<ConnectionManager>.Instance=new();Request().ProcessPackage(world,GameManager.Instance);Check(RebirthGearRecoveryDispatcher.Calls==0&&manager.Sends==0,"manager change during first terminal attempt refuses publication");
 Reset();RebirthWorldCharacterRepository.Cached=false;Request().ProcessPackage(world,GameManager.Instance);Check(RebirthGearRecoveryDispatcher.Calls==0&&manager.Sends==0,"retired cached record cannot publish");
 Reset();p=Request();sender.EntityId=8;p.ProcessPackage(world,GameManager.Instance);Check(RebirthRemoteGearAppliedConfirmation.Confirms==0&&RebirthGearRecoveryDispatcher.Calls==0,"foreign sender refused beforeeffects");
 Reset();world.Remote=true;Request().ProcessPackage(world,GameManager.Instance);Check(RebirthRemoteGearAppliedConfirmation.Confirms==0,"remote world refused");Reset();GameManager.Instance.World=new();Request().ProcessPackage(world,GameManager.Instance);Check(RebirthRemoteGearAppliedConfirmation.Confirms==0,"retired world refused");Reset();manager.IsServer=false;Request().ProcessPackage(world,GameManager.Instance);Check(RebirthRemoteGearAppliedConfirmation.Confirms==0,"nonserver refused");
 Reset();RebirthRemoteGearAppliedConfirmation.Ready=true;RebirthRemoteGearAppliedConfirmation.Applied=false;Request().ProcessPackage(world,GameManager.Instance);Check(manager.Sends==0&&RebirthGearRecoveryDispatcher.Calls==0,"rejected terminal cannot answer applied request");
 Reset();NetPackageManager.Missing=true;Throws(()=>Request().ProcessPackage(world,GameManager.Instance),"missing terminal mapping");Check(RebirthRemoteGearAppliedConfirmation.Confirms==0&&RebirthGearRecoveryDispatcher.Calls==0,"mapping missing before effects");
 Reset(true);creation="legacy-"+new string('a',64);RebirthRemoteGearAppliedConfirmation.Creation=creation;RebirthRemoteGearInventorySource.Record.Support.PendingGearTransfer.CreationId=creation;wire=Encode(Request());Check(wire.Length==Request().GetLength(),"full migrated frame length");Decode(wire).ProcessPackage(world,GameManager.Instance);Check(manager.Sends==1&&manager.Last.Value.CreationId==creation,"full migrated identity retained");
 Reset();Throws(()=>new NetPackageRebirthGearAppliedRequest().Setup(7,creation,Guid.Empty),"empty transaction refused");Throws(()=>new NetPackageRebirthGearAppliedRequest().Setup(7,"bad",tx),"invalid creation refused");Throws(()=>Encode(new()),"uninitialized write refused");wire=Encode(Request());Array.Resize(ref wire,wire.Length-1);Throws(()=>Decode(wire),"truncated request refused");
 Console.WriteLine("PASS "+checks+" actual applied packet/server orchestration checks; native transport/authentication, saved journal and recovery publication services doubled. No actual native spawn/disk/network execution.");
 }
}