using System;
using System.Collections.Generic;
// Authored English fallback when localization is not ready; never expose internal bonus IDs.
public static class RebirthBackgroundBonusTextFallback
{
    private static readonly Dictionary<string,string> Text=new Dictionary<string,string>(StringComparer.Ordinal)
    {
        {"xuiRebirthBackgroundBonusEfficientMovement","Efficient Movement"},
        {"xuiRebirthBackgroundBonusEfficientMovementDesc","Sprinting and jumping and swimming use 15% less movement Energy. Mining and attacks are unaffected."},
        {"xuiRebirthBackgroundBonusTraumaSpecialist","Trauma Specialist"},
        {"xuiRebirthBackgroundBonusTraumaSpecialistDesc","Properly treated injuries heal twice as fast when treated by a Paramedic."},
        {"xuiRebirthBackgroundBonusPharmacyEye","Pharmacy Eye"},
        {"xuiRebirthBackgroundBonusPharmacyEyeDesc","Pharmaceutical containers yield substantially more useful medication-related supplies."},
        {"xuiRebirthBackgroundBonusReagentRecovery","Reagent Recovery"},
        {"xuiRebirthBackgroundBonusReagentRecoveryDesc","Some lab and chemistry work recovers reagents that would normally be consumed."},
        {"xuiRebirthBackgroundBonusBookworm","Bookworm"},
        {"xuiRebirthBackgroundBonusBookwormDesc","Bookcases and similar literature containers provide twice as much readable or Knowledge-related content."},
        {"xuiRebirthBackgroundBonusPartsSalvager","Parts Salvager"},
        {"xuiRebirthBackgroundBonusPartsSalvagerDesc","Dismantled vehicles provide significantly more usable mechanical parts."},
        {"xuiRebirthBackgroundBonusPowerSaver","Power Saver"},
        {"xuiRebirthBackgroundBonusPowerSaverDesc","Electrical systems built or configured by an Electrician consume less generator and battery power."},
        {"xuiRebirthBackgroundBonusBuiltToLast","Built to Last"},
        {"xuiRebirthBackgroundBonusBuiltToLastDesc","Structures built by a Construction Worker have 15% greater maximum durability."},
        {"xuiRebirthBackgroundBonusHeatTreatment","Heat Treatment"},
        {"xuiRebirthBackgroundBonusHeatTreatmentDesc","Metal tools melee weapons and fabricated metal equipment made by a Metal Worker have 15% greater maximum durability."},
        {"xuiRebirthBackgroundBonusNothingIsDisposable","Nothing Is Disposable / Tools at Hand"},
        {"xuiRebirthBackgroundBonusNothingIsDisposableDesc","Repairs cause 50% less permanent maximum-condition loss. Tools at Hand gives 2 extra toolbelt slots with any belt or without one."},
        {"xuiRebirthBackgroundBonusEngineeredReliability","Engineered Reliability"},
        {"xuiRebirthBackgroundBonusEngineeredReliabilityDesc","Electrical and automated traps built by an Engineer have 50% greater maximum durability."},
        {"xuiRebirthBackgroundBonusOreSense","Ore Sense"},
        {"xuiRebirthBackgroundBonusOreSenseDesc","Miners can toggle Ore Sense to locate nearby ore deposits through surrounding rock."},
        {"xuiRebirthBackgroundBonusProfessionalLogging","Professional Logging"},
        {"xuiRebirthBackgroundBonusProfessionalLoggingDesc","Trees provide substantially more wood when brought down and cutting them consumes less Stamina and Energy."},
        {"xuiRebirthBackgroundBonusFireResistant","Fire Resistant"},
        {"xuiRebirthBackgroundBonusFireResistantDesc","Firefighters take substantially less damage from fire and burning and burning ends sooner."},
        {"xuiRebirthBackgroundBonusCombatMomentum","Combat Momentum"},
        {"xuiRebirthBackgroundBonusCombatMomentumDesc","Qualifying combat kills build up to three stacks of improved reload speed and weapon handling."},
        {"xuiRebirthBackgroundBonusPatrolCarFamiliarity","Patrol Car Familiarity"},
        {"xuiRebirthBackgroundBonusPatrolCarFamiliarityDesc","Police vehicles provide three times the normal ammunition when searched by a Police Officer."},
        {"xuiRebirthBackgroundBonusHuntersMark","Hunter's Mark"},
        {"xuiRebirthBackgroundBonusHuntersMarkDesc","Hunters can observe and track individual natural animals and unharvested animal carcasses remain visible on their compass."},
        {"xuiRebirthBackgroundBonusCalmingPresence","Calming Presence"},
        {"xuiRebirthBackgroundBonusCalmingPresenceDesc","Wildlife takes significantly longer to become hostile around a Park Ranger."},
        {"xuiRebirthBackgroundBonusGunsmithMasterRestoration","Master Restoration"},
        {"xuiRebirthBackgroundBonusGunsmithMasterRestorationDesc","Repairing firearms can recover maximum durability previously lost to permanent degradation."},
        {"xuiRebirthBackgroundBonusProfessionalCooking","Professional Cooking"},
        {"xuiRebirthBackgroundBonusProfessionalCookingDesc","Chef-prepared meals provide stronger Energy recovery and make absorbed Nutrition sustain Energy more efficiently."},
        {"xuiRebirthBackgroundBonusTailorMasterRestoration","Master Restoration"},
        {"xuiRebirthBackgroundBonusTailorMasterRestorationDesc","Repairing armor and clothing can recover maximum durability previously lost to permanent degradation."},
        {"xuiRebirthBackgroundBonusRapidCultivation","Rapid Cultivation"},
        {"xuiRebirthBackgroundBonusRapidCultivationDesc","Crops grown by a Farmer reach maturity substantially faster."},
        {"xuiRebirthBackgroundBonusWholeAnimal","Whole Animal"},
        {"xuiRebirthBackgroundBonusWholeAnimalDesc","Butchers recover substantially more usable resources from animal carcasses."},
        {"xuiRebirthBackgroundBonusMasterMixologist","Master Mixologist"},
        {"xuiRebirthBackgroundBonusMasterMixologistDesc","Special effects from drinks prepared by a Bartender last twice as long."},
        {"xuiRebirthBackgroundBonusMoreOptions","More Options"},
        {"xuiRebirthBackgroundBonusMoreOptionsDesc","Trader quest rewards provide one additional reward option to choose from; it does not increase how many rewards are claimed."},
        {"xuiRebirthBackgroundBonusScholarAndMentor","Scholar and Mentor"},
        {"xuiRebirthBackgroundBonusScholarAndMentorDesc","Teachers learn Knowledge faster from books and training materials and students they teach gain a temporary learning bonus in that subject."},
        {"xuiRebirthBackgroundBonusNothingIsJunk","Nothing Is Junk / Expert Packing"},
        {"xuiRebirthBackgroundBonusNothingIsJunkDesc","Recover more useful materials when dismantling. Expert Packing adds 13 usable backpack slots (one full inventory row). The extra row also adds 13 slots you can fill without becoming encumbered."},
    };
    public static string Get(string key,string fallback) => key!=null&&Text.TryGetValue(key,out var text)?text:fallback;
}
