using System;using System.Collections.Generic;using System.Linq;using System.Xml.Linq;using System.Globalization;
// Completed native original deaths, not arbitrary client kill notifications or practical-XP receipts.
public sealed class RebirthTheorySoloCombatLedger
{
 public sealed class Original{public long Ordinal;public string Id,Generation,Creation,Subject,Family;public int Actor,Target,NativeMaxHealth;public float Difficulty;public bool EvidenceAttempted;public Original Clone()=>(Original)MemberwiseClone();}
 public long Issued{get;private set;}public readonly List<Original> Pending=new List<Original>();
 public RebirthTheorySoloCombatLedger Clone(){var c=new RebirthTheorySoloCombatLedger{Issued=Issued};c.Pending.AddRange(Pending.Select(x=>x.Clone()));return c;}
 public Original Reserve(string id,string generation,string creation,string subject,string family,int actor,int target,int maxHealth,float difficulty){var a=new Original{Id=id,Generation=generation,Creation=creation,Subject=subject,Family=family,Actor=actor,Target=target,NativeMaxHealth=maxHealth,Difficulty=difficulty};if(!Valid(a))return null;var old=Pending.FirstOrDefault(x=>x.Id==id);if(old!=null)return Same(old,a)?old:null;if(Pending.Count>=128||Issued==long.MaxValue)return null;a.Ordinal=++Issued;Pending.Add(a);return a;}
 public bool TryGet(long ordinal,string id,out Original a){a=Pending.FirstOrDefault(x=>x.Ordinal==ordinal&&x.Id==id);return a!=null;}
 public bool MarkEvidence(long ordinal,string id,out bool already){already=false;if(!TryGet(ordinal,id,out var a))return false;already=a.EvidenceAttempted;a.EvidenceAttempted=true;return true;}
 public bool Retire(long ordinal,string id){if(!TryGet(ordinal,id,out var a))return false;return Pending.Remove(a);}
 public XElement Write(){var n=new XElement("combatOriginal",new XAttribute("issued",Issued));foreach(var a in Pending.OrderBy(x=>x.Ordinal))n.Add(new XElement("death",new XAttribute("ordinal",a.Ordinal),new XAttribute("id",a.Id),new XAttribute("generation",a.Generation),new XAttribute("creation",a.Creation),new XAttribute("subject",a.Subject),new XAttribute("family",a.Family),new XAttribute("actor",a.Actor),new XAttribute("target",a.Target),new XAttribute("nativeMaxHealth",a.NativeMaxHealth),new XAttribute("difficulty",a.Difficulty.ToString("R",CultureInfo.InvariantCulture)),new XAttribute("evidence",a.EvidenceAttempted?"1":"0")));return n;}
 public static bool TryRead(XElement node,string creation,out RebirthTheorySoloCombatLedger ledger){ledger=null;try{if(node==null||node.Name!="combatOriginal"||node.Attributes().Count()!=1)return false;var c=new RebirthTheorySoloCombatLedger{Issued=(long)node.Attribute("issued")};if(c.Issued<0||node.Elements().Count()>128)return false;foreach(var row in node.Elements()){var a=new Original{Ordinal=(long)row.Attribute("ordinal"),Id=(string)row.Attribute("id"),Generation=(string)row.Attribute("generation"),Creation=(string)row.Attribute("creation"),Subject=(string)row.Attribute("subject"),Family=(string)row.Attribute("family"),Actor=(int)row.Attribute("actor"),Target=(int)row.Attribute("target"),NativeMaxHealth=(int)row.Attribute("nativeMaxHealth"),Difficulty=(float)row.Attribute("difficulty"),EvidenceAttempted=(string)row.Attribute("evidence")=="1"};if(row.Name!="death"||!Valid(a)||a.Creation!=creation||a.Ordinal<1||a.Ordinal>c.Issued||c.Pending.Any(x=>x.Ordinal==a.Ordinal||x.Id==a.Id))return false;c.Pending.Add(a);}if(!XNode.DeepEquals(c.Write(),node))return false;ledger=c;return true;}catch{return false;}}
 static bool Id(string x)=>Guid.TryParseExact(x,"N",out var g)&&g!=Guid.Empty;
 static bool Valid(Original a)=>a!=null&&Id(a.Id)&&Id(a.Generation)&&RebirthTheorySoloState.Text(a.Creation,71)&&RebirthTheorySoloState.Text(a.Subject,128)&&RebirthTheorySoloState.Text(a.Family,64)&&a.Actor>=0&&a.Target>=0&&a.Actor!=a.Target&&a.NativeMaxHealth>0&&RebirthTheorySoloState.Finite(a.Difficulty)&&a.Difficulty>=0&&a.Difficulty<=100;
 static bool Same(Original a,Original b)=>a.Id==b.Id&&a.Generation==b.Generation&&a.Creation==b.Creation&&a.Subject==b.Subject&&a.Family==b.Family&&a.Actor==b.Actor&&a.Target==b.Target&&a.NativeMaxHealth==b.NativeMaxHealth&&a.Difficulty==b.Difficulty;
}
