using System;
class Program{
static int n;static void C(bool v,string s){if(!v)throw new Exception(s);n++;}
class Setup{public World W=new World();public EntityPlayer P;public ClientInfo Sender=new ClientInfo{ClientNumber=1,entityId=1};public Vector3i Pos=new Vector3i(1,2,3);public BlockPlantGrowingRebirth Crop=new BlockPlantGrowingRebirth{nextPlant=new BlockValue{type=3}};public BlockValue Target,Old=new BlockValue{type=0};public TileEntityPlantGrowingRebirth T=new TileEntityPlantGrowingRebirth{PlantIncarnation=50,StateRevision=3};public SeedPlacementSessionAuthority.Reservation R;public SeedPlacementOriginalCommandReview Command;
public Setup(){AdvancedFarmingHoverTextService.Reset();P=new EntityPlayer{entityId=1,world=W};W.Actors[1]=P;GameManager.Instance=new GameManager{World=W};SingletonMonoBehaviour<ConnectionManager>.Instance=new ConnectionManager();SingletonMonoBehaviour<ConnectionManager>.Instance.Clients.Entries[1]=Sender;Target=new BlockValue{type=2,meta=9,Block=Crop};W.Blocks[Pos]=Old;SeedPlacementSessionAuthority.TryIssue(Sender,W,out var epoch);SeedPlacementSessionAuthority.TryReserve(Sender,W,epoch,1,out R);Command=SeedPlacementOriginalCommandReview.Capture(epoch,1,1,1,new SeedPlacementIntentCodecReview.Intent{Slot=0,Position=Pos,Target=Target,ExpectedOld=Old,Seed=new byte[]{1},Flags=0x15});}
public AdvancedFarmingRemotePlantingAdmissionReview.RemoteScope Begin()=>AdvancedFarmingRemotePlantingAdmissionReview.Begin(R,Command,W,P);
public bool Add(){W.Blocks[Pos]=Target;W.Tiles[Pos]=T;AdvancedFarmingPlantOriginService.OnNativePlantAdded(W,Pos,Target,T);return T.PlantOrigin==AdvancedFarmingPlantOrigin.Player;}
public void End(){SeedPlacementSessionAuthority.Revoke(Sender);}}
static void Main(){AdvancedFarmingRemotePlantingAdmissionReview.InstallHooksForReview();AdvancedFarmingRemotePlantingAdmissionReview.InstallHooksForReview();C(true,"explicit same-owner typed hook installation idempotent");var s=new Setup();using(var scope=s.Begin()){C(scope!=null&&scope.BeforeNativeExecution(),"bound command admits one execution");C(s.Add()&&s.T.PlantOrigin==AdvancedFarmingPlantOrigin.Player,"own native Added admitted before schedule");C(scope.Complete()&&!scope.Complete(),"completion oneuse");}C(s.T.PlantOrigin==AdvancedFarmingPlantOrigin.Player&&s.T.Modified==1&&s.Crop.Scheduled==0,"committed disposal leaves native schedule untouched");s.End();
foreach(var fault in new[]{"noBefore","doubleBefore","oldChanged","nested","session","target","duplicate","revision","incarnation","replace","callback","hover","throw","world"}){s=new Setup();var scope=s.Begin();if(fault=="oldChanged")s.W.Blocks[s.Pos]=new BlockValue{type=8};if(fault=="nested")C(s.Begin()==null,"nested attempt invalidates first");if(fault!="noBefore")scope.BeforeNativeExecution();if(fault=="doubleBefore")C(!scope.BeforeNativeExecution(),"second execution refuses");if(fault=="session")SeedPlacementSessionAuthority.Revoke(s.Sender);if(fault=="target")s.Target.meta++;bool added=s.Add();if(added){switch(fault){case "duplicate":C(!s.Add(),"duplicate add invalidates");break;case "revision":s.T.StateRevision++;break;case "incarnation":s.T.PlantIncarnation++;break;case "replace":s.W.Tiles[s.Pos]=new TileEntityPlantGrowingRebirth{PlantOrigin=AdvancedFarmingPlantOrigin.Player,PlantIncarnation=99,StateRevision=99};break;case "callback":s.T.OnModified=()=>s.T.StateRevision++;break;case "hover":AdvancedFarmingHoverTextService.OnInvalidate=()=>s.T.StateRevision++;break;case "throw":s.T.OnModified=()=>{if(s.T.Modified==1)throw new InvalidOperationException();};break;case "world":GameManager.Instance.World=new World();break;}}
bool complete=false;try{complete=scope.Complete();}catch(InvalidOperationException){}C(!complete,"fault never completes "+fault);scope.Dispose();scope.Dispose();if(fault=="replace")C(s.W.Tiles[s.Pos].StateRevision==99&&s.Crop.Scheduled==0,"replacement not cleaned");else if(fault=="revision"||fault=="incarnation"||fault=="callback"||fault=="hover"||fault=="world")C(s.T.PlantOrigin==AdvancedFarmingPlantOrigin.Player&&s.Crop.Scheduled==0,"newer/context state not cleaned "+fault);else if(added)C(s.T.PlantOrigin==AdvancedFarmingPlantOrigin.Unknown&&s.Crop.Scheduled==1,"failed exact own admission resets and native fallback "+fault);s.End();}
foreach(var fault in new[]{"editor","mature","existing","actor","nonce"}){s=new Setup();if(fault=="editor")GameManager.Instance.Editor=true;if(fault=="mature")s.Crop.Name="crop3Harvest";if(fault=="existing")s.W.Tiles[s.Pos]=s.T;EntityPlayer actor=fault=="actor"?new EntityPlayer{world=s.W,entityId=1}:s.P;if(fault=="nonce")s.Command=SeedPlacementOriginalCommandReview.Capture(s.R.Epoch,2,1,1,new SeedPlacementIntentCodecReview.Intent{Slot=0,Position=s.Pos,Target=s.Target,ExpectedOld=s.Old,Seed=new byte[]{1}});C(AdvancedFarmingRemotePlantingAdmissionReview.Begin(s.R,s.Command,s.W,actor)==null,"begin policy rejects "+fault);s.End();}
s=new Setup();var failed=s.Begin();failed.BeforeNativeExecution();s.Add();s.T.OnModified=()=>throw new InvalidOperationException();bool cleanupThrow=false;try{failed.Dispose();}catch(InvalidOperationException){cleanupThrow=true;}C(cleanupThrow&&s.T.PlantOrigin==AdvancedFarmingPlantOrigin.Unknown&&s.Crop.Scheduled==1,"cleanup finally fallback despite native fault");failed.Dispose();s.End();foreach(var reset in new[]{"ownReset","foreignUnknown","newer"}){s=new Setup();var scope=s.Begin();scope.BeforeNativeExecution();s.Add();if(reset=="ownReset"){C(!s.Add()&&s.T.PlantOrigin==AdvancedFarmingPlantOrigin.Unknown,"actual root repeat Added observes own reset then invalidates duplicate");}else if(reset=="foreignUnknown")s.T.PlantOrigin=AdvancedFarmingPlantOrigin.Unknown;else{s.T.StateRevision++;AdvancedFarmingPlantOriginService.OnNativePlantAdded(s.W,s.Pos,s.Target,s.T);C(s.T.PlantOrigin==AdvancedFarmingPlantOrigin.Player,"actual root protects newer Added before reset");}scope.Dispose();if(reset=="ownReset")C(s.Crop.Scheduled==1,"own observed reset recovers native schedule");else C(s.Crop.Scheduled==0,"foreign/newer cleanup never adopted "+reset);s.End();}
foreach(bool alias in new[]{false,true}){s=new Setup();var scope=s.Begin();scope.BeforeNativeExecution();s.Add();int key=WorldBlockTickerEntry.ToHashCode(s.Pos,s.Target.type);var entry=new WorldBlockTickerEntry{worldPos=s.Pos,blockID=s.Target.type};if(alias){entry.worldPos=new Vector3i(8,9,10);entry.blockID=(entry.worldPos.GetHashCode()*397)^key;}s.W.Scheduler.scheduledTicksDict[key]=entry;scope.Dispose();C(alias?s.W.Scheduler.scheduledTicksDict.ContainsKey(key)&&s.Crop.Scheduled==0:!s.W.Scheduler.scheduledTicksDict.ContainsKey(key)&&s.Crop.Scheduled==1,"exact ticker custody "+alias);s.End();}foreach(bool remote in new[]{false,true}){s=new Setup();var scope=s.Begin();scope.BeforeNativeExecution();s.W.Blocks[s.Pos]=s.Target;s.W.Tiles[s.Pos]=s.T;if(remote)s.W.Remote=true;else GameManager.Instance.World=new World();AdvancedFarmingPlantOriginService.OnNativePlantAdded(s.W,s.Pos,s.Target,s.T);C(s.T.PlantOrigin==AdvancedFarmingPlantOrigin.Unknown&&!scope.Complete(),"actual root remote/currentworld boundary no admission "+remote);scope.Dispose();C(s.Crop.Scheduled==0,"no cleanup into replacement/remote world "+remote);s.End();}
s=new Setup();var boundary=s.Begin();boundary.BeforeNativeExecution();s.W.Blocks[s.Pos]=s.Target;s.W.Tiles[s.Pos]=s.T;var foreign=new TileEntityPlantGrowingRebirth{PlantOrigin=AdvancedFarmingPlantOrigin.Player,PlantIncarnation=77,StateRevision=8};AdvancedFarmingPlantOriginService.OnNativePlantAdded(s.W,s.Pos,s.Target,foreign);C(foreign.PlantOrigin==AdvancedFarmingPlantOrigin.Player&&s.T.PlantOrigin==AdvancedFarmingPlantOrigin.Unknown,"root rejects noncurrent TE before remote hooks");boundary.Dispose();s.End();
bool nullHook=false;try{AdvancedFarmingPlantOriginService.RegisterRemoteAdmissionHooks(null);}catch(ArgumentNullException){nullHook=true;}C(nullHook,"root typed installer null fails closed");bool foreignOwner=false;try{AdvancedFarmingPlantOriginService.RegisterRemoteAdmissionHooks(new ForeignHooks());}catch(InvalidOperationException){foreignOwner=true;}C(foreignOwner,"different owner cannot replace singleton hooks");Console.WriteLine("PASS "+n+" linked remote admission/session/original-command checks; exact revision/ticker methods, explicit native callback adapters, no placement/debit/engine claim.");}}


class ForeignHooks:AdvancedFarmingPlantOriginService.IRemoteAdmissionHooks{public bool ProtectNewerAdded(WorldBase w,Vector3i p,TileEntityPlantGrowingRebirth t)=>false;public bool ObserveAddedReset(WorldBase w,Vector3i p,BlockValue b,TileEntityPlantGrowingRebirth t)=>false;public bool TryAdmit(WorldBase w,Vector3i p,BlockValue b,TileEntityPlantGrowingRebirth t)=>false;}
