using System;using System.Collections.Generic;using System.Linq;using System.Xml.Linq;
public class XmlFile{public XDocument XmlDoc;}
public static class Localization{public static Dictionary<string,string[]> Dictionary=new Dictionary<string,string[]>();public static bool Exists(string key)=>Dictionary.ContainsKey(key);}
public static class TEFeatureStorage{public const string PropLootList="LootList";}
public static class TEFeatureRebirthContainerName{public const string FeatureName="TEFeatureRebirthContainerName";}
public static class RebirthContainerSizeService{public const string PropertyContainerSize="RebirthContainerSize",PropertyLegacyContainerSize="ContainerSize",PropertyLootContainerSize="LootContainerSize";}
public static class RebirthBlockPickupClassifier{public const string PropertyVanillaCanPickup="RebirthVanillaCanPickup";}
public static class RebirthBlockPickupTargetResolver{public const string PropertyVanillaPickupTarget="RebirthVanillaPickupTarget";}
public static class RebirthBlockPickupLegacyTargets{public static bool TryGetTarget(string source,out string target){target=null;return false;}}
public static class RebirthLogSettings{public static bool BlockPickupLoggingEnabled=false;}
public static class Log{public static void Out(string s){}public static void Warning(string s){throw new Exception(s);}}
class Program{
 static int count;static void Check(bool ok,string name){if(!ok)throw new Exception(name);count++;}
 static XElement Block(string name,string parent=null,string downgrade=null,bool storage=false){var b=new XElement("block",new XAttribute("name",name));if(parent!=null)b.Add(new XElement("property",new XAttribute("name","Extends"),new XAttribute("value",parent)));if(downgrade!=null)b.Add(new XElement("property",new XAttribute("name","DowngradeBlock"),new XAttribute("value",downgrade)));if(storage)b.Add(new XElement("property",new XAttribute("class","CompositeFeatures"),new XElement("property",new XAttribute("class","TEFeatureStorage"),new XElement("property",new XAttribute("name","LootList"),new XAttribute("value","medicalPillCase")))));return b;}
 static void Main(){Localization.Dictionary["cntPillCaseClosed"]=new[]{"Medical Cabinet","Armoire médicale","药柜"};Localization.Dictionary["cntPillCaseEmpty"]=new[]{"Medical Cabinet Empty","Armoire médicale vide","空藥櫃"};Localization.Dictionary["xuiStorage"]=new[]{"Storage","Stockage","储存"};var empty=Block("cntPillCaseEmpty");var closed=Block("cntPillCaseClosed","cntPillCaseEmpty","cntPillCaseEmpty",true);var root=new XElement("blocks",empty,closed);var file=new XmlFile{XmlDoc=new XDocument(root)};var nativeEmpty=new XElement(empty);var nativeClosed=new XElement(closed);var nativeRow=Localization.Dictionary["cntPillCaseEmpty"].ToArray();RebirthBlockPickupEmptyVariantGenerator.Prepare(file);
 foreach(var key in new[]{"cntPillCaseClosedRebirthPlayer","cntPillCaseEmptyRebirthPlayer"}){Check(Localization.Dictionary[key].SequenceEqual(Localization.Dictionary["cntPillCaseClosed"]),"all language cells neutral "+key);Check(!ReferenceEquals(Localization.Dictionary[key],Localization.Dictionary["cntPillCaseClosed"]),"locale array cloned "+key);var b=root.Elements().Single(x=>(string)x.Attribute("name")==key);Check(b.Elements("property").Any(x=>(string)x.Attribute("name")=="Extends"&&(string)x.Attribute("value")=="cntPillCaseEmpty"),"empty model preserved");}
 Check(XNode.DeepEquals(nativeEmpty,empty)&&XNode.DeepEquals(nativeClosed,closed),"native POI definitions untouched");Check(Localization.Dictionary["cntPillCaseEmpty"].SequenceEqual(nativeRow),"native actual-empty locale untouched");Localization.Dictionary["cntPillCaseEmptyRebirthPlayer"]=nativeRow.ToArray();var placed=root.Elements().Single(x=>(string)x.Attribute("name")=="cntPillCaseEmptyRebirthPlayer");placed.Add(new XElement("property",new XAttribute("name","FixtureCustomName"),new XAttribute("value","My Meds")));var before=new XElement(placed);RebirthBlockPickupEmptyVariantGenerator.Prepare(file);Check(Localization.Dictionary["cntPillCaseEmptyRebirthPlayer"].SequenceEqual(Localization.Dictionary["cntPillCaseClosed"]),"already existing legacy key migrated");Check(XNode.DeepEquals(before,placed),"placed metadata/custom name untouched");Check(WorldTitle("cntPillCaseEmptyRebirthPlayer",null)==LootTitle("cntPillCaseEmptyRebirthPlayer",null)&&WorldTitle("cntPillCaseEmptyRebirthPlayer",null)=="Medical Cabinet","world and loot shared generated key callback double");Check(WorldTitle("cntPillCaseEmptyRebirthPlayer","My Meds")=="My Meds"&&LootTitle("cntPillCaseEmptyRebirthPlayer","My Meds")=="My Meds","custom rename precedence callback double");
 root.Add(Block("cntPillCaseOther","cntPillCaseEmpty","cntPillCaseEmpty",true));Localization.Dictionary["cntPillCaseOther"]=new[]{"Medical Cabinet","Autre armoire","药柜"};RebirthBlockPickupEmptyVariantGenerator.Prepare(file);Check(Localization.Dictionary["cntPillCaseEmptyRebirthPlayer"].SequenceEqual(Localization.Dictionary["xuiStorage"]),"ambiguity detected across non-English cells");Check(Localization.Dictionary["cntPillCaseClosedRebirthPlayer"].SequenceEqual(Localization.Dictionary["cntPillCaseClosed"]),"unambiguous direct source preserved");var freshRoot=new XElement("blocks",Block("cntPillCaseEmpty",storage:true),Block("cntPillCaseClosed","cntPillCaseEmpty","cntPillCaseEmpty",true));var fresh=new XmlFile{XmlDoc=new XDocument(freshRoot)};RebirthBlockPickupEmptyVariantGenerator.Prepare(fresh);Check(Localization.Dictionary["cntPillCaseEmptyRebirthPlayer"].SequenceEqual(Localization.Dictionary["cntPillCaseClosed"]),"source-specific Empty generated pickup gets neutral family name");Check(freshRoot.Elements().Single(x=>(string)x.Attribute("name")=="cntPillCaseEmptyRebirthPlayer").Descendants("property").Any(x=>(string)x.Attribute("name")=="LootList"&&(string)x.Attribute("value")=="playerWoodWritableStorage"),"existing compatibility loot-list policy preserved");
var unowned=Block("unownedRebirthPlayer","cntPillCaseEmpty",storage:true);unowned.Add(new XElement("property",new XAttribute("name","RebirthGeneratedSourceBlock"),new XAttribute("value","cntPillCaseEmpty")),new XElement("property",new XAttribute("name","RebirthGeneratedPlayerStorage"),new XAttribute("value","cntPillCaseEmpty")));freshRoot.Add(unowned);Localization.Dictionary["unownedRebirthPlayer"]=new[]{"Authored label","Nom choisi"};RebirthBlockPickupEmptyVariantGenerator.Prepare(fresh);Check(Localization.Dictionary["unownedRebirthPlayer"][0]=="Authored label","mismatched generated provenance not migrated");
Localization.Dictionary["cntPillCaseOther"]=Localization.Dictionary["cntPillCaseClosed"].ToArray();root.Add(Block("cycleA","cycleB","cycleB"),Block("cycleB","cycleA","cycleA"));Localization.Dictionary["cycleA"]=new[]{"Cycle"};RebirthBlockPickupEmptyVariantGenerator.Prepare(file);Check(Localization.Dictionary["cntPillCaseEmptyRebirthPlayer"].SequenceEqual(Localization.Dictionary["cntPillCaseClosed"]),"equivalent all-language inverse candidates stable and cyclic graph bounded");Console.WriteLine(count+" PASS actual generator naming; native localization/UI callbacks explicitly doubled");}
 static string WorldTitle(string key,string custom)=>custom??Localization.Dictionary[key][0];static string LootTitle(string key,string custom)=>custom??Localization.Dictionary[key][0];
}
