from pathlib import Path
import json,hashlib,zipfile
r=Path('.');d=r/'_Documentation/GearTransfers'
rows=json.loads((d/'full_gear_results.json').read_text());assert len(rows)==14
bg=json.loads((d/'background_storage_results.json').read_text());assert len(bg)==4
ov=json.loads((d/'overflow_results.json').read_text());assert ov['backpackRecovered'] and ov['beltRecovered'];assert ov['backpackDrop']['configuredLifetimeSeconds']==3600
errors=json.loads((d/'final_errors.json').read_text(encoding='utf-8-sig'));assert errors['count']==0
craft=json.loads((r/'Tools/GameBridge/out/starter_belt_final_results.txt').read_text(encoding='utf-8-sig').splitlines()[-1]);assert craft['passed']
summary={'status':'PASS','scope':'Local single-player disposable CodexTest on installed 3.2 b10','gearItems':14,'belts':6,'backpacks':8,'realInputTransfers':56,'allTransfers':['shift in','shift out','drag in','drag out'],'beltCapacities':[6,8,10,12,14,16],'packCapacities':[50,55,60,65,70,75,80,90],'encumbranceSlotsEveryTier':18,'maintenanceTechnicianMaxBelt':18,'scavengerBasePack':50,'scavengerMaxPack':95,'backgroundChecks':4,'requirementRejection':'PASS','starterCraftSteps':18,'starterCraftIngredients':{'resourceCloth':6,'resourceScrapIron':2},'overflowRecovery':'PASS both stacks recovered through real input','backpackLifetimeSeconds':3600,'beltDropLifetimeSeconds':1800,'newRuntimeErrors':0,'buildErrors':0,'buildWarnings':9,'warnings':'Existing GameBridge unused variables','gameClosedAfterTesting':True,'commitsMade':False,'limitations':['No remote-client/dedicated-server live qualification.','Lifetimes verified from live entities and native tick conversion; no 30/60-minute elapsed-expiry test.','New advanced recipes and loot-stage mappings statically audited; only the default starter recipe was crafted live.','Fixture attributes/backgrounds prepare test conditions; this does not prove earned progression.'],'evidence':['full_gear_results.json','background_storage_results.json','overflow_results.json','requirement_rejection.json','static_six_tiers.json','final_errors.json']}
(d/'final_validation.json').write_text(json.dumps(summary,indent=2))
(d/'starter_crafting_results.json').write_text(json.dumps(craft,indent=2))
log=r/'_Documentation/Codex_Changes/CUMULATIVE_LOG.txt'
with log.open('a',encoding='utf-8') as f:f.write('''

2026-10-02 — Gear transfer qualification, six distinct belt models and background storage perks
Fixed missing explicit registration of RebirthSurvivorGearQuickEquip and assembly-qualified gear-slot controllers; use native InputUtils.ShiftKeyPressed and authoritative equipment state instead of a stale presentation label. Verified shift-click and drag in both directions through Game Bridge.
Replaced belt art with six distinct generated constructions and 160x160 RGBA atlas icons: Utility single cloth pouch, Field leather split apron, Tactical compact webbing, Artisan hanging roll/parts bag, Industrial riveted metal cases, Expedition roll-top saddlebags. Preserved high-resolution masters and six_belt_models.png. Utility recipe now 6 cloth +2 scrap iron; higher recipes match visible materials. Starter challenge icon/text updated.
Added Artisan/Industrial/Expedition toolbelts (+8/+10/+12), item definitions, support profiles, recipes, Tailoring 40/55/70 capability gates, Backpack Expansion knowledge mappings, loot-stage 140/180/220 entries and localization. Six equipped totals now 6/8/10/12/14/16; removed automatic level-based capacity growth. Existing base remains 4. Starter excluded from loot.
Approved backgrounds: Maintenance Technician Tools at Hand +2 toolbelt slots, maximum 18; Scavenger Expert Packing +5 usable pack slots (one Character row). Existing repair/salvage benefits retained. Added data-driven tuning to existing signature records, source runtime consumer, owner-state-safe projections and descriptions. No world-origin migration required for ordinary players.
Backpack gear and Scavenger expansion now contribute the same number of native CarryCapacity slots as physical slots via a separate CVar, preserving the count of encumbrance slots. Native passive refresh settles on its game tick.
Expanded bridge diagnostics for capacities/gear/attributes and recovery contents/lifetimes; CodexTest-only attribute/background fixture; drag now follows a selected cell when a shrinking grid moves it. Corrected recovery lifetime readout: native loot-container timeStayAfterDeath is 20 ticks per second, deathUpdateTime is elapsed ticks. No production timer change.
Local runtime PASS: all 6 belts +8 packs; 56 real-input transfers, item conservation and empty cursors; capacities 6..16 and 50..90; encumbrance remained 18 throughout. Maintenance Technician reached 18 visible belt slots; Scavenger reached 50 bare/95 maximum pack slots, same encumbrance count. Requirement rejection conserved gear. Starter crafting passed 18/18 checks, consumed exactly 6 cloth/2 iron and produced one belt. Backpack overflow gold and belt overflow ammo spawned with 3600/1800-second configurations and were recovered through actual loot input. No new runtime errors. Final build: 0 errors, 9 existing GameBridge warnings. Test background and original attributes restored; god buff removed; game closed after testing.
Limits: local host only, no remote/dedicated qualification; timers checked from runtime configuration, not elapsed 30/60-minute expiry; advanced recipes/loot mappings checked statically, not all crafted/rolled live. Detailed evidence: _Documentation/GearTransfers/final_validation.json and README.txt. No commits; Claude retains commit ownership. Changed-files overlay targets this cumulative workspace, not a standalone PASS7 package.
''')
# Exact active scope, without unrelated pending changes or bridge session credentials.
files=['Config/Localization.csv','Config/XUi_InGame/windows.xml','Config/_Survivor/background_bonuses.xml','Config/_Survivor/capabilities.xml','Config/_Survivor/crafting_progression.xml','Config/_Survivor/items.xml','Config/_Survivor/recipes.xml','Config/_Survivor/recipe_knowledge.xml','Config/_Survivor/support_profiles.xml','Config/_Rebirth/storage_loot.xml','Config/buffs.xml','Config/entityclasses.xml','Scripts/UI/RebirthToolbeltCapacity.cs','Scripts/Survivor/Support/RebirthBackgroundStorageService.cs','Scripts/Survivor/Support/RebirthSurvivorGearService.cs','Scripts/Survivor/Support/RebirthSurvivorBackpackCapacityPatches.cs','Scripts/Survivor/Support/RebirthGearOverflow.cs','Scripts/Survivor/UI/XUiC_RebirthSurvivorGearSlot.cs','Scripts/Survivor/UI/RebirthSurvivorUiInstaller.cs','Scripts/Survivor/Progression/RebirthTraitGameplayModifierService.cs','Scripts/GameBridge/RebirthGameBridgeHandlers.cs','Scripts/GameBridge/RebirthGameBridgeGearFixture.cs','Scripts/GameBridge/RebirthGameBridgeUi.cs','RebirthUtils.dll','RebirthUtils.pdb','Tools/GameBridge/tests/storage_gear.json','Tools/GameBridge/tests/starter_belt_crafting.json','Tools/GameBridge/tests/README.md','_Documentation/Codex_Changes/CUMULATIVE_LOG.txt']
files += [str(p) for p in (r/'Tools/StorageGear').glob('test*live.py')]
files += ['Tools/StorageGear/audit_six_tiers.py','Tools/StorageGear/install_six_belt_art.py']
files += [f'UIAtlases/ItemIconAtlas/rebirthGear{n}Belt.png' for n in ['Utility','Field','Tactical','Artisan','Industrial','Expedition']]+['UIAtlases/UIAtlas/rb_challenge_StorageBelt.png']
files += [str(p) for p in d.rglob('*') if p.is_file() and p.suffix not in ('.zip','.sha256')]
files=sorted(set(f.replace('\\','/') for f in files));missing=[f for f in files if not (r/f).is_file()];assert not missing,missing
(d/'changed_files.json').write_text(json.dumps(files,indent=2));files.append(str(d/'changed_files.json'))
package=r/'_Documentation/REBIRTH_20261002_SIX_BELTS_GEAR_QUALIFIED.zip'
with zipfile.ZipFile(package,'w',zipfile.ZIP_DEFLATED) as z:
 for f in files:z.write(r/f,f)
sha=hashlib.sha256(package.read_bytes()).hexdigest();package.with_suffix('.zip.sha256').write_text(sha+'  '+package.name+'\n')
print(json.dumps({'status':'PASS','files':len(files),'package':str(package),'sha256':sha},indent=2))
