import{readFile,writeFile,mkdir}from'node:fs/promises';import{execFile}from'node:child_process';import{promisify}from'node:util';import{join,resolve,dirname}from'node:path';import{fileURLToPath}from'node:url';import{createHash}from'node:crypto';
const run=promisify(execFile),here=dirname(fileURLToPath(import.meta.url)),root=resolve(here,'../../../..'),hashes={};
async function load(p){let s=await readFile(join(root,p),'utf8');hashes[p]=createHash('sha256').update(s).digest('hex').toUpperCase();return s;}
function member(s,sig){let a=s.indexOf(sig);if(a<0)throw Error(sig);let b=s.indexOf('{',a),d=1,i=b+1;for(;d&&i<s.length;i++){if(s[i]==='{')d++;if(s[i]==='}')d--;}if(d)throw Error('unbalanced');return s.slice(a,i);}
await load('Tools/DemoInventoryAcceptanceTeam/Walkman/CallbackContext/run.mjs');
let baseline=await load('Scripts/Survivor/Network/RebirthAudiobookLibraryClient.cs');if(hashes['Scripts/Survivor/Network/RebirthAudiobookLibraryClient.cs']!=='2E2C5E2B83438BFE7025BB9B6AC63BF3D50E759EDDB3A1A11266DADE6ACE3C87')throw Error('baseline drift');
let candidate=await load('Tools/DemoInventoryAcceptanceTeam/Walkman/CallbackContext/RebirthAudiobookLibraryClient.CALLBACK_CANDIDATE.cs.txt');
let old=await load('Tools/DemoInventoryAcceptanceTeam/Walkman/ReservationCounterexample/fixture.cs');let f='using System.IO;'+old.slice(0,old.indexOf('static int failures;'));
f=f.replace('public EntityPlayerLocal GetPrimaryPlayer(){return Player;}','public EntityPlayerLocal GetPrimaryPlayer(){return Player;}public EntityPlayerLocal GetEntity(int id){return Player!=null&&Player.entityId==id?Player:null;}');
f=f.replace('public bool Dead;','public bool Spawned=true;public bool IsSpawned(){return Spawned;}public Serializer inventory=new Serializer(),bag=new Serializer(),equipment=new Serializer();public ItemStack DragAndDropItem=new ItemStack();public bool Dead;');
f=f.replace('public static string CreationId;public static bool Current','public static long Generation;public static string CreationId;public static bool Current');
f=f.replace('public static T GetPackage<T>()where T:new(){return new T();}','public static T GetPackage<T>()where T:new(){Hooks.OnAllocate?.Invoke();return new T();}');
f=f.replace('static void Setup(bool remote=true){','static void Setup(bool remote=true){Hooks.Reset();RebirthMusicLibraryClient.Generation=3;');
f=f.replace('public void SendToServer(NetPackage p){Sent.Add(p);}','public void SendToServer(NetPackage p){Hooks.SendCalls++;if(Hooks.ThrowSend==Hooks.SendCalls)throw new Exception("injected uncertain send");Sent.Add(p);}');
f=f.replace('public static string Encode(ItemValue v){return Convert.ToBase64String','public static string Encode(ItemValue v){Hooks.Proof?.Invoke();return Convert.ToBase64String');
let packet=await load('Scripts/Survivor/Network/RebirthMusicLibraryNetPackage.cs');let start=f.indexOf('public class NetPackageRebirthMusicLibraryRequest:NetPackage'),end=f.indexOf('public class Channel',start);
f=f.slice(0,start)+'public class NetPackageRebirthMusicLibraryRequest:NetPackage{private int playerId,operation,index,itemType;private ushort seed;private long revision;private string expectedCreationId,sourceProof;public int Operation=>operation;public string Proof=>sourceProof;public string Creation=>expectedCreationId;public long Revision=>revision;'+member(packet,'    public NetPackageRebirthMusicLibraryRequest Setup(')+'}\n'+f.slice(end);
let native=await load('Tools/SecondTeam/MusicUseProducer/native/NetPackagePlayerInventory.cs'),blob=await load('Tools/StorageGear/inspect/out-gear-recovery-installed/StreamUtils.cs');
f=f.replace('public class NetPackagePlayerInventory:NetPackage{public NetPackagePlayerInventory Setup(params object[] args){return this;}}','public class NetPackagePlayerInventory:NetPackage{public MemoryStream inventoryData,bagData,equipmentData;public ItemStack dragAndDropItem;'+member(native,'public NetPackagePlayerInventory Setup(')+'}');
for(const[m,p]of[['SCOPE','Network/RebirthSurvivorRequestScope.cs'],['PROOF','Support/RebirthMusicSourceProof.cs']]){let s=await load('Scripts/Survivor/'+p);f=f.replace('// '+m,s.slice(s.indexOf('public static class')));}
let action=await load('Scripts/Survivor/Progression/ItemActionListenAudiobookRebirth.cs');f=f.replace('// DISPATCH',member(action,'    internal static void Dispatch(')).replace('// SEND',member(packet,'    internal static bool CanSend('));
f+='static int failures;static void Case(string n,Action a){try{a();Console.WriteLine("PASS "+n);}catch(Exception e){failures++;Console.WriteLine("FAIL "+n+": "+e.Message);}}\nstatic void Main(){\n';
const tests=String.raw`
foreach(int mode in new[]{0,1,2,3,4,5,6,7,8,9,10,11,12}){int m=mode;Case("inventory serializer context refusal "+m,()=>{Setup();Snapshot();conn.Sent.Clear();Hooks.Serialize=()=>{Hooks.Serialize=null;switch(m){case 0:p.world=new World();break;case 1:GameManager.Instance.World=new World{Player=p};break;case 2:p.world.Player=new EntityPlayerLocal();break;case 3:p.entityId=8;break;case 4:p.Dead=true;break;case 5:RebirthSurvivorClientState.Projected="55555555555555555555555555555555";break;case 6:RebirthAudiobookLibraryClient.Receive(RebirthSurvivorClientState.Projected,3,new List<string>(),new List<string>());break;case 7:RebirthMusicLibraryClient.Generation++;break;case 8:SingletonMonoBehaviour<ConnectionManager>.Instance=new ConnectionManager();break;case 9:RebirthBackpackLibraryReservation.Held=true;break;case 10:RebirthMusicLibraryClient.PendingTransfer=true;break;case 11:conn.Channels[0].Disconnected=true;break;case 12:GameManager.Instance=new GameManager{World=p.world};break;}};A(!RebirthAudiobookLibraryClient.RequestTransfer(p,true,0,item)&&conn.Sent.Count==0,"must refuse before any inventory/request send");});}
Case("request proof Setup completes before first send",()=>{Setup();Snapshot();conn.Sent.Clear();bool before=false;Hooks.Proof=()=>{Hooks.Proof=null;before=conn.Sent.Count==0;RebirthBackpackLibraryReservation.Held=true;};A(!RebirthAudiobookLibraryClient.RequestTransfer(p,true,0,item)&&conn.Sent.Count==0&&before,"proof-induced hold refuses both packages before any send");});
Case("reentrant warm insertion suppressed",()=>{Setup();Snapshot();conn.Sent.Clear();bool nested=true;Hooks.Serialize=()=>{Hooks.Serialize=null;nested=RebirthAudiobookLibraryClient.RequestTransfer(p,true,0,item);};A(RebirthAudiobookLibraryClient.RequestTransfer(p,true,0,item),"outer stable insertion admits");A(!nested&&conn.Sent.Count==2,"nested must refuse and outer sends one pair");});
Case("deferred preadmission serializer exception retains original intent",()=>{Setup();RebirthAudiobookLibraryClient.RequestUse(p,item);var intent=Queued();Hooks.Serialize=()=>{throw new Exception("injected serializer fault");};bool threw=false;try{Snapshot();}catch(Exception){threw=true;}A(threw&&ReferenceEquals(intent,Queued())&&conn.Sent.Count==1,"unsent intent must remain after Setup exception");Hooks.Serialize=null;Snapshot();A(Queued()==null&&conn.Sent.Count==3,"finally guard releases; later valid snapshot admits once");});
Case("deferred replaced scope never rebinds old intent",()=>{Setup();RebirthAudiobookLibraryClient.RequestUse(p,item);Hooks.Serialize=()=>{Hooks.Serialize=null;RebirthSurvivorClientState.Projected="55555555555555555555555555555555";RebirthMusicLibraryClient.CreationId=RebirthSurvivorClientState.Projected;RebirthAudiobookLibraryClient.Reset();RebirthAudiobookLibraryClient.Receive(RebirthSurvivorClientState.Projected,2,new List<string>(),new List<string>());};Snapshot();A(conn.Sent.Count==1&&Queued()==null,"no send and no restored old item in replacement scope");});
Case("removal preserves selected slot after pool callback",()=>{Setup();Snapshot();RebirthAudiobookLibraryClient.Items.Add("old");RebirthAudiobookLibraryClient.SlotIds.Add("22222222222222222222222222222222");conn.Sent.Clear();Hooks.OnAllocate=()=>{Hooks.OnAllocate=null;RebirthAudiobookLibraryClient.SlotIds[0]="33333333333333333333333333333333";};A(!RebirthAudiobookLibraryClient.RequestTransfer(p,false,0,null)&&conn.Sent.Count==0,"changed slot must refuse op6");});
Case("reentrant cold producer cannot replace original intent",()=>{Setup();RebirthAudiobookLibraryClient.RequestUse(p,item);var intent=Queued();bool nested=true;Hooks.Serialize=()=>{Hooks.Serialize=null;RebirthMusicLibraryClient.Current=false;nested=RebirthAudiobookLibraryClient.RequestUse(p,new ItemValue{Metadata="new"});RebirthMusicLibraryClient.Current=true;};Snapshot();A(!nested&&conn.Sent.Count==3&&Queued()==null,"nested producer refuses original outer admission stays unique");});
Case("unspawned during inventory Setup refused",()=>{Setup();Snapshot();conn.Sent.Clear();Hooks.Serialize=()=>{Hooks.Serialize=null;p.Spawned=false;};A(!RebirthAudiobookLibraryClient.RequestTransfer(p,true,0,item)&&conn.Sent.Count==0,"unspawned owner refuses both sends");});
Case("removal item identity preserved after pool callback",()=>{Setup();Snapshot();RebirthAudiobookLibraryClient.Items.Add("old");RebirthAudiobookLibraryClient.SlotIds.Add("22222222222222222222222222222222");conn.Sent.Clear();Hooks.OnAllocate=()=>{Hooks.OnAllocate=null;RebirthAudiobookLibraryClient.Items[0]="new";};A(!RebirthAudiobookLibraryClient.RequestTransfer(p,false,0,null)&&conn.Sent.Count==0,"changed item must refuse op6");});
Case("Reset cannot release preparing guard for nested cold use",()=>{Setup();RebirthAudiobookLibraryClient.RequestUse(p,item);bool nested=true;Hooks.Serialize=()=>{Hooks.Serialize=null;RebirthAudiobookLibraryClient.Reset();RebirthMusicLibraryClient.Current=false;nested=RebirthAudiobookLibraryClient.RequestUse(p,new ItemValue());RebirthMusicLibraryClient.Current=true;};Snapshot();A(!nested&&conn.Sent.Count==1&&Queued()==null,"Reset invalidates intent; busy guard remains until outer finally");});
Case("stable admission ordering and duplicate replay control",()=>{Setup();RebirthAudiobookLibraryClient.RequestUse(p,item);Snapshot();A(conn.Sent.Count==3&&conn.Sent[1]is NetPackagePlayerInventory&&((NetPackageRebirthMusicLibraryRequest)conn.Sent[2]).Operation==5&&Queued()==null,"one complete pair after stable preparation");Snapshot();A(conn.Sent.Count==3,"no admitted deferred replay");});Case("healthy direct removal admits selected slot once",()=>{Setup();Snapshot();RebirthAudiobookLibraryClient.Items.Add("old");RebirthAudiobookLibraryClient.SlotIds.Add("22222222222222222222222222222222");conn.Sent.Clear();A(RebirthAudiobookLibraryClient.RequestTransfer(p,false,0,null)&&conn.Sent.Count==1&&((NetPackageRebirthMusicLibraryRequest)conn.Sent[0]).Operation==6,"stable stored removal sends one op6");});foreach(int throwAt in new[]{1,2}){int at=throwAt;Case("uncertain admitted send never restores intent "+at,()=>{Setup();RebirthAudiobookLibraryClient.RequestUse(p,item);Hooks.SendCalls=0;Hooks.ThrowSend=at;bool threw=false;try{Snapshot();}catch(Exception){threw=true;}A(threw&&Queued()==null,"admitted intent stays cleared after send exception");int sent=conn.Sent.Count;Hooks.ThrowSend=0;Snapshot();A(conn.Sent.Count==sent,"later snapshot never replays ambiguous admission");});}
Console.WriteLine("SUMMARY cases=26 assertions="+checks+" failures="+failures+"; complete actual audio client/request Setup/native inventory Setup/ToBlob; injected adapter serializer/pool context changes; no observed native replacement, custody, MP or gameplay");Environment.ExitCode=failures==0?0:1;}}
`;
f+=tests;
f+='public enum StreamModeWrite{Persistency}public class ItemStack{public ItemStack Clone(){return new ItemStack();}}public class Serializer{public void Write(PooledBinaryWriter w,StreamModeWrite m){Hooks.Serialize?.Invoke();w.Stream.WriteByte(123);}}public class PooledBinaryWriter:IDisposable{public Stream Stream;public void SetBaseStream(Stream s){Stream=s;}public void Dispose(){}}public class Pool{public PooledBinaryWriter AllocSync(bool _bReset){return new PooledBinaryWriter();}}public static class MemoryPools{public static Pool poolBinaryWriter=new Pool();}public static class StreamUtils{'+member(blob,'public static MemoryStream ToBlob(')+'}public static class Hooks{public static Action Serialize,Proof,OnAllocate;public static int SendCalls,ThrowSend;public static void Reset(){Serialize=Proof=OnAllocate=null;SendCalls=ThrowSend=0;}}';
await writeFile(join(here,'fixture.template.cs.txt'),f);
const results={};for(const[n,s]of[['Baseline',baseline],['Candidate',candidate]]){let out=join(here,n);await mkdir(out,{recursive:true});let cs=join(out,'actual_source_fixture.cs'),exe=join(out,'check.exe');await writeFile(cs,f.replace('// CLIENT',s.slice(s.indexOf('public static class'))));await run('C:/Program Files/dotnet/dotnet.exe',['C:/Program Files/dotnet/sdk/9.0.301/Roslyn/bincore/csc.dll','/nologo','/target:exe','/out:'+exe,...['mscorlib','System','System.Core'].map(n=>'/r:C:/Windows/Microsoft.NET/Framework64/v4.0.30319/'+n+'.dll'),cs],{windowsHide:true,timeout:10000});try{let r=await run(exe,[],{windowsHide:true,timeout:10000});results[n]={exitCode:0,stdout:r.stdout};}catch(e){if(typeof e.code!=='number')throw e;results[n]={exitCode:e.code,stdout:e.stdout,stderr:e.stderr};}await writeFile(join(out,'RESULT.txt'),results[n].stdout);console.log(n+' exit='+results[n].exitCode+'\n'+results[n].stdout.trim());}
await writeFile(join(here,'SOURCE_HASHES.json'),JSON.stringify(hashes,null,2));await writeFile(join(here,'RESULTS.json'),JSON.stringify(results,null,2));if(results.Baseline.exitCode!==1||results.Candidate.exitCode!==0)throw Error('unexpected outcomes');