// Outer admission/recipe identity adapters; production terminal filter and native receipt/item wire are actual sources.
public class Recipe{}
public class RebirthStationGridAdmission{public string JobId="original";}
public static class RebirthStationGridIngredients{public static bool IsSameStackSnapshot(ItemStack a,ItemStack b){return a.count==b.count&&RebirthNativeItemCodec.Encode(a.itemValue)==RebirthNativeItemCodec.Encode(b.itemValue);}}
public static class RebirthStationCompletionReceipt{
public const string Prefix="rebirth.station.receipt.";public class Identity{public string Job;}
public static bool TryReadIdentity(CraftCompleteData d,out Identity id){id=null;string job;if(!d.CraftedItemStack.itemValue.TryGetMetadata(Prefix+"job",out job)||job=="")return false;id=new Identity{Job=job};return true;}
public static bool MatchesAdmission(RebirthStationGridAdmission a,Recipe r,CraftCompleteData d){Identity id;return a!=null&&r!=null&&d!=null&&TryReadIdentity(d,out id)&&id.Job==a.JobId;}}
public static class TerminalCompletionCheck{
static int checks;static void A(bool b,string label){checks++;if(!b)throw new Exception(label);}
static ItemValue V(int type){return new ItemValue(type){Meta=-1,Seed=17,TextureFullArray=new TextureFullArray(-23)};}
static byte[] Wire(CraftCompleteData[] rows){using(var stream=new MemoryStream()){var w=MemoryPools.poolBinaryWriter.Value;var old=w.Encoding;try{w.Encoding=new UTF8Encoding(false,false);w.SetBaseStream(stream);w.Write((short)rows.Length);foreach(var row in rows)row.Write(w);w.Flush();return stream.ToArray();}finally{w.Encoding=old;}}}
static byte[] Output(ItemStack stack){using(var stream=new MemoryStream()){var w=MemoryPools.poolBinaryWriter.Value;var old=w.Encoding;try{w.Encoding=new UTF8Encoding(false,false);w.SetBaseStream(stream);w.Write((byte)1);stack.Write(w);w.Flush();return stream.ToArray();}finally{w.Encoding=old;}}}
static void Bad(byte[] bytes){int before=ItemStack.Reads;CraftCompleteData[] result;A(!RebirthNativeItemConformanceReader.TryDecodeStationCompletions(bytes,out result),"invalid refused");A(result==null,"atomic null");A(before==ItemStack.Reads,"no native allocation on preflight fault");}
public static int Main(){ItemClass.list[1]=new ItemClass{Name="output"};ItemClass.list[2]=new ItemClassModifier{Name="mod"};var stack=new ItemStack{count=2,itemValue=V(1)};stack.itemValue.modifications=new[]{V(2)};stack.itemValue.cosmeticMods=new[]{V(2)};stack.itemValue.SetMetadata(RebirthStationCompletionReceipt.Prefix+"job","original");var receipt=new CraftCompleteData(42,stack,"recipeé🙂","",37,1);var ordinary=new CraftCompleteData(19,new ItemStack{count=1,itemValue=V(1)},"other","scrap",12,2);var rows=new[]{ordinary,receipt};var bytes=Wire(rows);CraftCompleteData[] result;var re=Encoding.Unicode;var we=Encoding.BigEndianUnicode;MemoryPools.poolBinaryReader.Value.Encoding=re;MemoryPools.poolBinaryWriter.Value.Encoding=we;
A(RebirthNativeItemConformanceReader.TryDecodeStationCompletions(bytes,out result),"actual native receipts decoded");A(result.Length==2&&result[1].CrafterEntityID==42&&result[1].RecipeName==receipt.RecipeName&&result[1].CraftExpGain==37&&result[1].RecipeUsedCount==1&&result[0].ItemScrapped=="scrap","actual field order");A(RebirthNativeItemCodec.Encode(result[1].CraftedItemStack.itemValue)==RebirthNativeItemCodec.Encode(stack.itemValue),"all receipt textures restored");A(object.ReferenceEquals(re,MemoryPools.poolBinaryReader.Value.Encoding)&&object.ReferenceEquals(we,MemoryPools.poolBinaryWriter.Value.Encoding),"pooled encodings restored");A(Wire(result).SequenceEqual(bytes),"exact native full reencode");var output=Output(stack);var admission=new RebirthStationGridAdmission();var recipe=new Recipe();A(RebirthStationTerminalContents.Matches(output,bytes,admission,recipe,receipt,new[]{stack}),"whole terminal accepts original marked plus ordinary receipt");A(!RebirthStationTerminalContents.Matches(output,Wire(new[]{receipt,receipt}),admission,recipe,receipt,new[]{stack}),"duplicate original refused");A(!RebirthStationTerminalContents.Matches(output,Wire(new[]{ordinary}),admission,recipe,receipt,new[]{stack}),"unmarked only refused");var altered=new CraftCompleteData(41,stack,receipt.RecipeName,"",37,1);A(!RebirthStationTerminalContents.Matches(output,Wire(new[]{altered}),admission,recipe,receipt,new[]{stack}),"actor mismatch refused");var invalidStack=new ItemStack{count=2,itemValue=V(1)};invalidStack.itemValue.SetMetadata(RebirthStationCompletionReceipt.Prefix+"job",7,TypedMetadataValue.TypeTag.Integer);var invalidReceipt=new CraftCompleteData(42,invalidStack,receipt.RecipeName,"",37,1);A(!RebirthStationTerminalContents.Matches(Output(invalidStack),Wire(new[]{invalidReceipt}),admission,recipe,receipt,new[]{invalidStack}),"wrong marker type refused");
for(int i=0;i<bytes.Length;i++)Bad(bytes.Take(i).ToArray());Bad(bytes.Concat(new byte[]{0}).ToArray());Bad(null);Bad(new byte[256*1024+1]);var bad=(byte[])bytes.Clone();bad[2]=2;Bad(bad);bad=(byte[])bytes.Clone();bad[0]=255;bad[1]=127;Bad(bad);var many=new CraftCompleteData[4097];for(int i=0;i<many.Length;i++)many[i]=new CraftCompleteData(1,new ItemStack{count=1,itemValue=V(1)},"","",0,0);Bad(Wire(many));var textRows=new CraftCompleteData[3];for(int i=0;i<3;i++)textRows[i]=new CraftCompleteData(1,new ItemStack{count=1,itemValue=V(1)},new string('a',45000),"",0,0);Bad(Wire(textRows));var marker=Encoding.UTF8.GetBytes(receipt.RecipeName);var utf=(byte[])bytes.Clone();int index=-1;for(int i=0;i<=utf.Length-marker.Length;i++)if(marker.Select((b,j)=>utf[i+j]==b).All(x=>x)){index=i;break;}A(index>=0,"locate actual native recipe string");utf[index]=255;Bad(utf);PooledBinaryWriter.FlushFault=true;A(!RebirthNativeItemConformanceReader.TryDecodeStationCompletions(bytes,out result)&&result==null,"native reencode exception atomic");A(object.ReferenceEquals(re,MemoryPools.poolBinaryReader.Value.Encoding)&&object.ReferenceEquals(we,MemoryPools.poolBinaryWriter.Value.Encoding),"exception encodings restored");PooledBinaryWriter.FlushFault=false;var registry=ItemClass.list;ItemStack.AfterNativeRead=row=>{ItemClass.list=(ItemClass[])registry.Clone();};A(!RebirthNativeItemConformanceReader.TryDecodeStationCompletions(bytes,out result)&&result==null,"registry replacement during native read refused");ItemClass.list=registry;ItemStack.AfterNativeRead=row=>{if(row.count>0)row.itemValue.Seed++;};A(!RebirthNativeItemConformanceReader.TryDecodeStationCompletions(bytes,out result)&&result==null,"native hydration binding failure refused");ItemStack.AfterNativeRead=row=>{throw new IOException("native read injected failure");};A(!RebirthNativeItemConformanceReader.TryDecodeStationCompletions(bytes,out result)&&result==null,"native reader exception atomic");A(object.ReferenceEquals(re,MemoryPools.poolBinaryReader.Value.Encoding)&&object.ReferenceEquals(we,MemoryPools.poolBinaryWriter.Value.Encoding),"native read failure encoding restored");ItemStack.AfterNativeRead=null;Console.WriteLine("PASS "+checks+" actual native receipt reader and whole terminal filter checks (outer identity adapters explicit)");return 0;}}