using System;
using System.Collections.Generic;
using System.Linq;
using System.IO;
class Vec { public int x,y,z; public Vec(int a=0,int b=0,int c=0){x=a;y=b;z=c;} public static Vec operator +(Vec a,Vec b)=>new Vec(a.x+b.x,a.y+b.y,a.z+b.z);public override bool Equals(object o)=>o is Vec v&&x==v.x&&y==v.y&&z==v.z;public override int GetHashCode()=>x; }
class Definition { public Vec startPos=new Vec(),size=new Vec(10,10,10);public short spawnCountMin=1,spawnCountMax=2;public int flags;public string minScript; }
class Prefab {public bool bTraderArea;public string PrefabName="house";public List<Definition> SleeperVolumeList=new List<Definition>{new Definition()};}
class PrefabInstance {public Prefab prefab=new Prefab();public Vec boundingBoxPosition=new Vec(),boundingBoxSize=new Vec(10,10,10);public byte rotation;public List<SleeperVolume> sleeperVolumes=new List<SleeperVolume>();}
class Biome {public string m_sBiomeName="forest";}
class WorldState {public string Guid=System.Guid.NewGuid().ToString("N").ToUpperInvariant();}
class World {public WorldState worldState=new WorldState();public ulong worldTime=1;public Dictionary<int,EntityAlive> Entities=new Dictionary<int,EntityAlive>();public List<SleeperVolume> Volumes=new List<SleeperVolume>(); public bool IsRemote()=>false;public EntityAlive GetEntity(int id)=>Entities.TryGetValue(id,out var e)?e:null;public int FindSleeperVolume(Vec min,Vec max)=>Volumes.FindIndex(v=>v.BoxMin.Equals(min)&&v.BoxMax.Equals(max));public SleeperVolume GetSleeperVolume(int id)=>id>=0&&id<Volumes.Count?Volumes[id]:null;public Biome GetBiome(int x,int z)=>new Biome();}
class EntityBuffs {public Dictionary<string,float> Vars=new Dictionary<string,float>();public bool HasCustomVar(string key)=>Vars.ContainsKey(key);public float GetCustomVar(string key)=>Vars[key];public void SetCustomVar(string key,float value,bool netSync){Vars[key]=value;} }
class EntityAlive {public EntityBuffs Buffs=new EntityBuffs();public World world;public int entityId;public bool Dead;public bool IsDead()=>Dead;}
class EntityPlayer:EntityAlive {public bool IsSpectator;public bool IsAlive()=>!Dead;public Vec GetBlockPosition()=>new Vec();}
class Script {public bool Running;public bool IsRunning()=>Running;}
class Handle {public bool IsCompleted=true;public Action onComplete;}
class SleeperVolume {public PrefabInstance prefabInstance;public Vec BoxMin=new Vec(),BoxMax=new Vec(10,10,10);public short spawnCountMin=1,spawnCountMax=2;public int flags,numSpawned;public bool isSpawning,wasCleared;public Script minScript;public Dictionary<int,object> respawnMap=new Dictionary<int,object>();public HashSet<int> pendingSpawnMap=new HashSet<int>();public Queue<Handle> pendingSpawnOps=new Queue<Handle>();}
class Decorator {public PrefabInstance Prefab;public PrefabInstance GetPrefabFromWorldPos(int x,int z)=>Prefab;}
class GameStateManager {public bool IsGameStarted()=>true;}
class GameManager {public static GameManager Instance;public World World;public bool IsStartingGame;public GameStateManager gameStateManager=new GameStateManager();public bool IsEditMode()=>false;public Decorator Decorator=new Decorator();public Decorator GetDynamicPrefabDecorator()=>Decorator;}
class ConnectionManager {public bool IsServer=true;}
class SingletonMonoBehaviour<T> {public static T Instance;}
class ThreadManager {public static bool IsMainThread()=>true;}
class GameIO {public static string GetSaveGameDir()=>"unused";}
class Log {public static void Warning(string s){} }
static class Program
{
 static int count;static void Check(bool yes,string name){if(!yes)throw new Exception(name);count++;Console.WriteLine("PASS "+name);}
 static void Main()
 {
  var world=new World();GameManager.Instance=new GameManager{World=world};var prefab=new PrefabInstance();var volume=new SleeperVolume{prefabInstance=prefab};prefab.sleeperVolumes.Add(volume);world.Volumes.Add(volume);GameManager.Instance.Decorator.Prefab=prefab;
  string dir=Path.Combine(Path.GetTempPath(),"rebirth-purge-evidence-"+Guid.NewGuid().ToString("N"));Directory.CreateDirectory(dir);var binding=new RebirthPoiWorldBinding(world,world.worldState.Guid,dir,()=>ReferenceEquals(GameManager.Instance.World,world));
  Check(RebirthPoiWorldStore.TryOpen(binding,out var store)==RebirthPoiStoreResult.Published,"real store opens");double time=0;var producer=new RebirthPoiNativeEvidence(()=>store,()=>time);Action pulse=()=>{time++;producer.Pulse();};
  RebirthPoiNativeManifest.TryResolve(world,prefab,out var manifest);Check(manifest!=null,"complete authored native mapping");producer.PlayerTouch(world,new EntityPlayer{world=world});pulse();Check(store.Published.Count==1,"passive discovery saves");
  volume.wasCleared=true;volume.numSpawned=1;producer.NativeDirty(world,volume);pulse();store.Published.TryGet(manifest.Identity,out var record);Check(record.State==RebirthPoiClearanceState.Discovered,"wasCleared and numSpawned alone never proof");
  var entity=new EntityAlive{world=world,entityId=42};world.Entities.Add(42,entity);volume.respawnMap.Add(42,new object());volume.pendingSpawnMap.Add(42);volume.pendingSpawnOps.Enqueue(new Handle());producer.NativeSpawn(world,volume,entity);entity.Dead=true;var witness=producer.BeforeDeath(volume,entity);Check(witness!=null,"successful native entity plus original membership death witness");volume.respawnMap.Remove(42);producer.AfterDeath(witness);pulse();store.Published.TryGet(manifest.Identity,out record);Check(record.State==RebirthPoiClearanceState.Cleared,"retained finished async handles and historical IDs permit verified clear");producer.AfterDeath(witness);pulse();Check(store.Published.Revision==2,"duplicate death does not republish");
  var cold=new RebirthPoiNativeEvidence(()=>store,()=>time);cold.NativeDirty(world,volume);time++;cold.Pulse();Check(store.Published.Revision==2,"cold producer does not invent reload causality");
  var second=new EntityAlive{world=world,entityId=43};world.Entities.Add(43,second);volume.respawnMap.Add(43,new object());producer.NativeSpawn(world,volume,second);pulse();store.Published.TryGet(manifest.Identity,out record);Check(record.Epoch==1 && record.State==RebirthPoiClearanceState.Discovered,"actual live repopulation invalidates clear with epoch");
  second.Dead=true;var secondWitness=producer.BeforeDeath(volume,second);volume.respawnMap.Remove(43);producer.AfterDeath(secondWitness);volume.numSpawned=2;var unfinished=new Handle{IsCompleted=false};volume.pendingSpawnOps.Enqueue(unfinished);producer.NativeDirty(world,volume);pulse();store.Published.TryGet(manifest.Identity,out record);Check(record.State==RebirthPoiClearanceState.Discovered,"unfinished callback blocks clear");unfinished.IsCompleted=true;unfinished.onComplete=()=>{};producer.NativeDirty(world,volume);pulse();store.Published.TryGet(manifest.Identity,out record);Check(record.State==RebirthPoiClearanceState.Discovered,"failed completion callback blocks clear");unfinished.onComplete=null;producer.NativeDirty(world,volume);pulse();store.Published.TryGet(manifest.Identity,out record);Check(record.State==RebirthPoiClearanceState.Cleared,"completed native actors re-clear new epoch");
  volume.wasCleared=false;volume.numSpawned=0;producer.NativeReset(world,volume);Check(producer.IsWithheld(manifest.Identity),"observed native reset withholds volatile marker authority");
  world.Volumes.Clear();Check(!RebirthPoiNativeManifest.TryResolve(world,prefab,out _),"missing authored native volume refuses manifest");world.Volumes.Add(volume);var extra=new SleeperVolume{prefabInstance=prefab,BoxMin=new Vec(20),BoxMax=new Vec(30)};prefab.sleeperVolumes.Add(extra);Check(!RebirthPoiNativeManifest.TryResolve(world,prefab,out _),"extra combat runtime volume refuses manifest");prefab.sleeperVolumes.Remove(extra);prefab.prefab.bTraderArea=true;Check(!RebirthPoiNativeManifest.TryResolve(world,prefab,out _),"trader exclusion explicit");prefab.prefab.bTraderArea=false;GameManager.Instance.World=new World();Check(!RebirthPoiNativeManifest.TryResolve(world,prefab,out _),"replacement world rejects late native evidence");
  GameManager.Instance.World=world;var stamped=new EntityAlive{world=world,entityId=90};world.Entities.Add(90,stamped);Check(RebirthPoiNativeActorStamp.TryAssignForVerifiedEnrollment(stamped,out var stamp),"verified native actor stamp assigns exact128bit token");Check(stamped.Buffs.Vars.Count==8&&stamped.Buffs.Vars.Values.All(v=>v>=1&&v<=65536),"stamp segments exact nonzero float save range");Check(RebirthPoiNativeActorStamp.TryAssignForVerifiedEnrollment(stamped,out var again)&&stamp==again,"stamp assignment retry immutable");var loaded=new EntityAlive{world=world,entityId=90};loaded.Buffs.Vars=new Dictionary<string,float>(stamped.Buffs.Vars);Check(RebirthPoiNativeActorStamp.TryRead(loaded,out var restored)&&restored==stamp,"restored native CVar values retain exact token");loaded.Buffs.Vars.Remove("_rbPoiActorGuid0");Check(!RebirthPoiNativeActorStamp.TryRead(loaded,out _),"partial native stamp refused");world.Entities[90]=loaded;Check(!RebirthPoiNativeActorStamp.TryAssignForVerifiedEnrollment(loaded,out _),"partial native stamp never repaired by minting");loaded.Buffs.Vars["_rbPoiActorGuid0"]=float.NaN;Check(!RebirthPoiNativeActorStamp.TryRead(loaded,out _),"NaN stamp refuses");loaded.Buffs.Vars["_rbPoiActorGuid0"]=1.5f;Check(!RebirthPoiNativeActorStamp.TryRead(loaded,out _),"fractional stamp refuses");
  // Independent fault fixture preserves the original proof receipt/world time on retry.
  var faultWorld=new World();GameManager.Instance.World=faultWorld;var faultPrefab=new PrefabInstance();var fv=new SleeperVolume{prefabInstance=faultPrefab};faultPrefab.sleeperVolumes.Add(fv);faultWorld.Volumes.Add(fv);GameManager.Instance.Decorator.Prefab=faultPrefab;
  var faultDir=Path.Combine(Path.GetTempPath(),"rebirth-purge-evidence-fault-"+Guid.NewGuid().ToString("N"));Directory.CreateDirectory(faultDir);bool armed=false;var faultBinding=new RebirthPoiWorldBinding(faultWorld,faultWorld.worldState.Guid,faultDir,()=>ReferenceEquals(GameManager.Instance.World,faultWorld));RebirthPoiWorldStore.TryOpen(faultBinding,out var faultStore,stage=>{if(armed&&stage=="afterManifestCandidateWritten")throw new IOException("fixture fault");});
  var fp=new RebirthPoiNativeEvidence(()=>faultStore,()=>time);fp.PlayerTouch(faultWorld,new EntityPlayer{world=faultWorld});time++;fp.Pulse();RebirthPoiNativeManifest.TryResolve(faultWorld,faultPrefab,out var fm);
  var fe=new EntityAlive{world=faultWorld,entityId=70};faultWorld.Entities.Add(70,fe);fv.respawnMap.Add(70,new object());fp.NativeSpawn(faultWorld,fv,fe);fe.Dead=true;var fw=fp.BeforeDeath(fv,fe);fv.respawnMap.Remove(70);fp.AfterDeath(fw);fv.wasCleared=true;fv.numSpawned=2;time++;fp.Pulse();faultStore.Published.TryGet(fm.Identity,out var fr);Check(fr.State==RebirthPoiClearanceState.Discovered,"missing class count cannot stand in for successful actor");fv.numSpawned=1;
  armed=true;fp.NativeDirty(faultWorld,fv);time++;fp.Pulse();Check(faultStore.HasPending,"failed clear publication retains durable original candidate");string candidate=File.ReadAllText(Path.Combine(faultBinding.Directory,"world.xml.candidate"));faultWorld.worldTime=400;armed=false;Check(faultStore.TryRetryPending()==RebirthPoiStoreResult.Published,"original clear candidate retry publishes");time++;fp.Pulse();faultStore.Published.TryGet(fm.Identity,out fr);Check(fr.State==RebirthPoiClearanceState.Cleared&&faultStore.Published.Manifest==candidate,"producer does not replace successful pending proof after time advances");
  var re=new EntityAlive{world=faultWorld,entityId=71};faultWorld.Entities.Add(71,re);fv.respawnMap.Add(71,new object());fp.NativeSpawn(faultWorld,fv,re);armed=true;time++;fp.Pulse();Check(faultStore.HasPending,"uncertain repopulation retains original generation candidate");
  re.Dead=true;var rw=fp.BeforeDeath(fv,re);fv.respawnMap.Remove(71);fp.AfterDeath(rw);fv.numSpawned=2;faultWorld.worldTime=800;armed=false;Check(faultStore.TryRetryPending()==RebirthPoiStoreResult.Published,"repopulation original receipt publishes after actor death");time++;fp.Pulse();faultStore.Published.TryGet(fm.Identity,out fr);Check(fr.Epoch==1&&fr.State==RebirthPoiClearanceState.Cleared,"exact persisted repopulation receipt reconciles epoch and allows subsequent verified clear");
  fp.Reset();var late=fp.BeforeDeath(fv,fe);Check(late==null,"reset session cannot re-enroll dead entity");
  // Missing a second authored combat volume is never waived by clearing the first.
  var secondDef=new Definition{startPos=new Vec(20)};faultPrefab.prefab.SleeperVolumeList.Add(secondDef);Check(!RebirthPoiNativeManifest.TryResolve(faultWorld,faultPrefab,out _),"unloaded second authored room withholds full clearance");var sv=new SleeperVolume{prefabInstance=faultPrefab,BoxMin=new Vec(20),BoxMax=new Vec(30,10,10)};faultWorld.Volumes.Add(sv);faultPrefab.sleeperVolumes.Add(sv);Check(RebirthPoiNativeManifest.TryResolve(faultWorld,faultPrefab,out var two)&&two.Volumes.Length==2,"complete second room mapping includes both combat volumes");
  Console.WriteLine("RESULT "+count+" PASS; actual production manifest/evidence/store; native methods and events doubled, real temp files. Harmony installation separately parent compiled.");
 }
}



