using System;using System.IO;using System.Linq;using System.Collections.Generic;using System.Reflection;using System.Reflection.Emit;using System.Reflection.Metadata;using System.Reflection.Metadata.Ecma335;using System.Reflection.PortableExecutable;using System.Security.Cryptography;
class P {
 static void Main(string[] args){using var f=File.OpenRead(args[0]);using var pe=new PEReader(f);var m=pe.GetMetadataReader();var text=new List<string>();text.Add("MVID="+m.GetGuid(m.GetModuleDefinition().Mvid));text.Add("SHA256="+Convert.ToHexString(SHA256.HashData(File.ReadAllBytes(args[0]))));
 var ops=typeof(OpCodes).GetFields(BindingFlags.Public|BindingFlags.Static).Where(x=>x.FieldType==typeof(OpCode)).Select(x=>(OpCode)x.GetValue(null)).ToDictionary(x=>(ushort)x.Value);
 string Token(int t){try{var h=MetadataTokens.EntityHandle(t);return h.Kind switch{HandleKind.MethodDefinition=>m.GetString(m.GetMethodDefinition((MethodDefinitionHandle)h).Name),HandleKind.MemberReference=>m.GetString(m.GetMemberReference((MemberReferenceHandle)h).Name),HandleKind.FieldDefinition=>m.GetString(m.GetFieldDefinition((FieldDefinitionHandle)h).Name),HandleKind.TypeDefinition=>m.GetString(m.GetTypeDefinition((TypeDefinitionHandle)h).Name),HandleKind.TypeReference=>m.GetString(m.GetTypeReference((TypeReferenceHandle)h).Name),_=>h.Kind.ToString()};}catch{return "unresolved";}}
 var select=new Dictionary<string,string[]>{{"TileEntityWorkstation",new[]{"HandleRecipeQueue","UpdateTick"}},{"NetPackageTileEntity",new[]{"ProcessPackage"}}};
 foreach(var th in m.TypeDefinitions){var td=m.GetTypeDefinition(th);var tn=m.GetString(td.Name);if(!select.TryGetValue(tn,out var names))continue;foreach(var mh in td.GetMethods()){var md=m.GetMethodDefinition(mh);var mn=m.GetString(md.Name);if(!names.Contains(mn)||md.RelativeVirtualAddress==0)continue;var il=pe.GetMethodBody(md.RelativeVirtualAddress).GetILBytes();text.Add("\nMETHOD "+tn+"."+mn+" token="+MetadataTokens.GetToken(mh).ToString("X8")+" signature="+Convert.ToHexString(m.GetBlobBytes(md.Signature))+" IL_SHA256="+Convert.ToHexString(SHA256.HashData(il)));
 for(int p=0;p<il.Length;){int at=p;ushort key=il[p++];if(key==0xfe)key=(ushort)(0xfe00|il[p++]);var op=ops[key];string operand="";int n=0;switch(op.OperandType){case OperandType.InlineNone:break;case OperandType.ShortInlineBrTarget:operand="IL_"+(p+1+(sbyte)il[p]).ToString("X4");n=1;break;case OperandType.InlineBrTarget:operand="IL_"+(p+4+BitConverter.ToInt32(il,p)).ToString("X4");n=4;break;case OperandType.ShortInlineI:case OperandType.ShortInlineVar:operand=il[p].ToString();n=1;break;case OperandType.InlineVar:operand=BitConverter.ToUInt16(il,p).ToString();n=2;break;case OperandType.InlineI:operand=BitConverter.ToInt32(il,p).ToString();n=4;break;case OperandType.InlineI8:operand=BitConverter.ToInt64(il,p).ToString();n=8;break;case OperandType.ShortInlineR:operand=BitConverter.ToSingle(il,p).ToString();n=4;break;case OperandType.InlineR:operand=BitConverter.ToDouble(il,p).ToString();n=8;break;case OperandType.InlineSwitch:int c=BitConverter.ToInt32(il,p);operand="switch count="+c;n=4+4*c;break;default:int t=BitConverter.ToInt32(il,p);operand=t.ToString("X8")+" "+Token(t);n=4;break;}text.Add("IL_"+at.ToString("X4")+" "+op.Name+" "+operand);p+=n;}
 }} var handle=text.FindIndex(x=>x.TrimStart().StartsWith("METHOD TileEntityWorkstation.HandleRecipeQueue"));
 if(handle<0)throw new Exception("Missing native method");
 var end=text.FindIndex(handle+1,x=>x.TrimStart().StartsWith("METHOD "));if(end<0)end=text.Count;
 var body=text.Skip(handle+1).Take(end-handle-1).ToArray();
 if(!text[0].EndsWith("1a9a4203-3d95-4c90-b094-8926dec1ee9c")||!text[1].EndsWith("FCEEC27300FFD3A1F97B097E43B60F3B07597F441E7ECBC6E1B59EEBB234C705")||!text[handle].Contains("9D6DD060B6343C7D0F0A11E724C33C8CFAD4E5E802E7D878D99A99A834BBC1DD"))throw new Exception("Unsupported original DLL/IL");
 if(!body[0].StartsWith("IL_0000 ldarg.0")||!body[1].EndsWith(" bUserAccessing")||!body[2].Contains("brfalse.s IL_0009")||!body[3].StartsWith("IL_0008 ret"))throw new Exception("Original user access guard differs");
 if(body.Count(x=>x.EndsWith(" AddToItemStackArray"))!=1||body.Count(x=>x.EndsWith(" AddCraftComplete"))!=1)throw new Exception("Original insertion/completion sites differ");
 text.Add("CANDIDATE PIN PASS: original guard/insertion/completion sites exact. Detached source candidate only; no installed Harmony transform.");
 File.WriteAllLines(args[1],text);Console.WriteLine(text[0]);Console.WriteLine(text[1]);Console.WriteLine("Raw IL listing lines="+text.Count);
 }
}



