using System;using System.Collections.Generic;using System.Security.Cryptography;using System.Text;using System.Reflection;
public class ItemValue{public int type=1;public ushort Seed=5;public string Metadata="exact";public bool IsEmpty(){return type==0;}public ItemValue Clone(){return new ItemValue{type=type,Seed=Seed,Metadata=Metadata};}}
public class World{public bool Remote=true;public EntityPlayerLocal Player;public bool IsRemote(){return Remote;}public EntityPlayerLocal GetPrimaryPlayer(){return Player;}}
public class EntityPlayer{}
public class EntityPlayerLocal:EntityPlayer{public World world;public int entityId=7;public bool Dead;public bool IsDead(){return Dead;}}
public class GameManager{public static GameManager Instance;public World World;}
public class RebirthMusicCassetteState{public string ItemId;}
public class RebirthAudiobookCassetteState{public string SlotId,ItemId;}
public class RebirthWorldSupportState{public long MusicRevision=3,AudiobookRevision=2;public bool MusicShuffle;public object PendingMusicTransfer;public List<RebirthMusicCassetteState> MusicCassettes=new List<RebirthMusicCassetteState>();public List<RebirthAudiobookCassetteState>AudiobookCassettes=new List<RebirthAudiobookCassetteState>();}
public class Origin{public string CreationId="11111111111111111111111111111111";}
public class RebirthWorldCharacterRecord{public bool IsComplete=true;public Origin Origin=new Origin();public RebirthWorldSupportState Support=new RebirthWorldSupportState();}
public static class RebirthWorldCharacterService{public static RebirthWorldCharacterRecord Record;public static bool TryGet(EntityPlayerLocal p,out RebirthWorldCharacterRecord r){r=Record;return r!=null;}}
public static class RebirthSurvivorClientState{public static string Projected="11111111111111111111111111111111";public static string GetProjectedCreationId(EntityPlayerLocal p){return Projected;}}
public static class RebirthBackpackLibraryReservation{public static bool Held;public static bool IsHeld(EntityPlayerLocal p){return Held;}}
public static class RebirthSurvivorSupportUiFeedback{public static int Failures;public static void Receive(bool ok,string m){if(!ok)Failures++;}}
public static class Localization{public static string Get(string s){return s;}}
public class NetPackage{public int Channel;}
public class NetPackagePlayerInventory:NetPackage{public NetPackagePlayerInventory Setup(params object[] args){return this;}}
public class NetPackageRebirthMusicLibraryRequest:NetPackage{public int Operation;public ItemValue Item;public string Proof,Creation;public long Revision;public NetPackageRebirthMusicLibraryRequest Setup(int p,int op,int index,ItemValue item,long revision,string creation){Operation=op;Item=item;Revision=revision;Creation=creation;RebirthMusicSourceProof.TryCreate(item,out Proof);return this;}}
public class Channel{public bool Disconnected;public bool IsDisconnected(){return Disconnected;}}
public class ConnectionManager{public bool IsServer,IsConnected=true;public Channel[] Channels=new[]{new Channel()};public List<NetPackage>Sent=new List<NetPackage>();public Channel[]GetConnectionToServer(){return Channels;}public void SendToServer(NetPackage p){Sent.Add(p);}}
public class SingletonMonoBehaviour<T>where T:new(){public static T Instance=new T();}
public static class NetPackageManager{public static T GetPackage<T>()where T:new(){return new T();}}
public static class RebirthMusicLibraryClient{public static string CreationId;public static bool Current,PendingTransfer;public static int Refreshes;public static bool EnsureCurrent(EntityPlayerLocal p){return Current&&p!=null&&ReferenceEquals(p.world,GameManager.Instance.World)&&ReferenceEquals(p,GameManager.Instance.World.Player)&&RebirthSurvivorRequestScope.Matches(CreationId,RebirthSurvivorClientState.Projected);}
// SEND
public static void Receive(string creation,long rev,bool shuffle,IEnumerable<string>ids,bool pending){CreationId=creation;Current=true;PendingTransfer=pending;}
public static void Dispatch(EntityPlayerLocal p,int op){if(op!=0)throw new Exception("music manual");Refreshes++;if(!p.world.IsRemote()){RebirthMusicTransferServer.ApplyLocalPending(p,CreationId);RebirthAudiobookLibraryClient.RefreshLocal(p);}else SingletonMonoBehaviour<ConnectionManager>.Instance.SendToServer(new NetPackageRebirthMusicLibraryRequest().Setup(p.entityId,0,0,null,-1,CreationId));}}
public static class RebirthMusicLibraryService{public static string Encode(ItemValue v){return Convert.ToBase64String(Encoding.UTF8.GetBytes(v.type+":"+v.Seed+":"+v.Metadata));}}
public class RebirthMusicTransferState{}
public static class RebirthMusicTransferServer{public static int Prepares,Applies;public static bool PrepareResult=true,SettleResult=true;public static object OriginalPending;public static List<object>Applied=new List<object>();public static string LastProof;public static bool PrepareLocalAudiobookSource(EntityPlayerLocal p,int op,int index,int type,ushort seed,long rev,string creation,string proof,out RebirthMusicTransferState offer){offer=new RebirthMusicTransferState();LastProof=proof;if(!PrepareResult)return false;if(RebirthWorldCharacterService.Record.Support.PendingMusicTransfer==null){Prepares++;OriginalPending=new object();RebirthWorldCharacterService.Record.Support.PendingMusicTransfer=OriginalPending;}return true;}public static bool ApplyLocalPending(EntityPlayerLocal p,string creation){if(RebirthWorldCharacterService.Record.Support.PendingMusicTransfer==null)return false;Applies++;Applied.Add(RebirthWorldCharacterService.Record.Support.PendingMusicTransfer);if(SettleResult){RebirthWorldCharacterService.Record.Support.PendingMusicTransfer=null;RebirthWorldCharacterService.Record.Support.AudiobookRevision++;return true;}return false;}}
public static class RebirthAudiobookListeningSessionService{public static bool TryResume(EntityPlayerLocal p,out string m){m="";return true;}public static bool TryPause(EntityPlayerLocal p,out string m){m="";return true;}public static bool TryBeginStored(EntityPlayerLocal p,string slot,out string m){m="";return true;}}
public static class RebirthAudiobookLibraryPersistence{public const int Capacity=24;}
// SCOPE
// PROOF
// CLIENT
public static class ItemActionListenAudiobookRebirth{
// DISPATCH
}
public static class Check{static int checks;static EntityPlayerLocal p;static ItemValue item;static ConnectionManager conn;static void A(bool ok,string why){checks++;if(!ok)throw new Exception(why);}static ItemValue Queued(){return(ItemValue)typeof(RebirthAudiobookLibraryClient).GetField("pendingUse",BindingFlags.Static|BindingFlags.NonPublic).GetValue(null);}static void Setup(bool remote=true){var w=new World{Remote=remote};p=new EntityPlayerLocal{world=w};w.Player=p;GameManager.Instance=new GameManager{World=w};item=new ItemValue();conn=new ConnectionManager{IsServer=!remote};SingletonMonoBehaviour<ConnectionManager>.Instance=conn;RebirthWorldCharacterService.Record=new RebirthWorldCharacterRecord();RebirthSurvivorClientState.Projected=RebirthWorldCharacterService.Record.Origin.CreationId;RebirthMusicLibraryClient.Current=false;RebirthMusicLibraryClient.CreationId=RebirthSurvivorClientState.Projected;RebirthMusicLibraryClient.PendingTransfer=false;RebirthMusicLibraryClient.Refreshes=0;RebirthAudiobookLibraryClient.Reset();RebirthMusicTransferServer.Prepares=RebirthMusicTransferServer.Applies=0;RebirthMusicTransferServer.Applied.Clear();RebirthMusicTransferServer.PrepareResult=RebirthMusicTransferServer.SettleResult=true;RebirthBackpackLibraryReservation.Held=false;RebirthSurvivorSupportUiFeedback.Failures=0;}
static void Snapshot(long rev=2,bool pending=false,string creation=null){RebirthMusicLibraryClient.Receive(creation??RebirthSurvivorClientState.Projected,3,false,new string[0],pending);RebirthAudiobookLibraryClient.Receive(creation??RebirthSurvivorClientState.Projected,rev,new List<string>(),new List<string>());}
static int failures;
static void Case(string name,Action body){try{body();Console.WriteLine("PASS "+name);}catch(Exception e){failures++;Console.WriteLine("FAIL "+name+": "+e.Message);}}
static void Main(){
Case("cold held RequestUse refuses without refresh or intent",()=>{Setup();RebirthBackpackLibraryReservation.Held=true;A(!RebirthAudiobookLibraryClient.RequestUse(p,item)&&conn.Sent.Count==0&&Queued()==null,"live reservation must refuse cold admission");});
Case("warm held RequestUse refuses inventory and op5",()=>{Setup();Snapshot();conn.Sent.Clear();RebirthBackpackLibraryReservation.Held=true;A(!RebirthAudiobookLibraryClient.RequestUse(p,item)&&conn.Sent.Count==0&&Queued()==null,"live reservation must refuse warm admission");});
Case("cold intent retains during held snapshot and sends once after unheld",()=>{Setup();A(RebirthAudiobookLibraryClient.RequestUse(p,item),"initial cold admission");var intent=Queued();RebirthBackpackLibraryReservation.Held=true;Snapshot();A(ReferenceEquals(intent,Queued())&&conn.Sent.Count==1,"held callback must preserve original queued intent without send");Snapshot();A(ReferenceEquals(intent,Queued())&&conn.Sent.Count==1,"repeated held callback remains unsent");RebirthBackpackLibraryReservation.Held=false;Snapshot();A(Queued()==null&&conn.Sent.Count==3&&conn.Sent[1]is NetPackagePlayerInventory&&((NetPackageRebirthMusicLibraryRequest)conn.Sent[2]).Operation==5,"unheld callback admits inventory then op5 exactly once");Snapshot();A(conn.Sent.Count==3,"duplicate accepted snapshot must not replay admission");});
Case("direct held insertion refuses",()=>{Setup();Snapshot();conn.Sent.Clear();RebirthBackpackLibraryReservation.Held=true;A(!RebirthAudiobookLibraryClient.RequestTransfer(p,true,0,item)&&conn.Sent.Count==0,"direct insertion must refuse before sends");});
Case("direct held removal refuses",()=>{Setup();Snapshot();RebirthAudiobookLibraryClient.Items.Add("stored");RebirthAudiobookLibraryClient.SlotIds.Add("22222222222222222222222222222222");conn.Sent.Clear();RebirthBackpackLibraryReservation.Held=true;A(!RebirthAudiobookLibraryClient.RequestTransfer(p,false,0,null)&&conn.Sent.Count==0,"direct removal must refuse before send");});
Console.WriteLine("SUMMARY cases=5 assertions="+checks+" failures="+failures+"; actual complete client source; native world/item/transport/reservation/server/playback adapted; no native custody or gameplay acceptance");Environment.ExitCode=failures==0?0:1;
}}