<Project Sdk="Microsoft.NET.Sdk"><PropertyGroup><OutputType>Exe</OutputType><TargetFramework>net9.0</TargetFramework><EnableDefaultCompileItems>false</EnableDefaultCompileItems><UseSharedCompilation>false</UseSharedCompilation><BaseIntermediateOutputPath>obj-binding/</BaseIntermediateOutputPath><OutputPath>bin-binding/</OutputPath></PropertyGroup><ItemGroup><Compile Include="../SeedNativeBindingCandidate.cs"/><Compile Include="../../Debit/SeedDebitReceipt.cs"/><Compile Include="Doubles.cs"/><Compile Include="Program.cs"/></ItemGroup></Project>
