using System;
class Program
{
 static int n;static void Check(bool x,string why){n++;if(!x)throw new Exception(why);}
 static TileEntityWorkstation Setup(){GameIO.Root=System.IO.Path.Combine(System.IO.Path.GetTempPath(),"station-original-a");var s=new TileEntityWorkstation{Queue=new[]{new RecipeQueueItem{StartingEntityId=1,Recipe=new(){Marked=true,Name="job"}}}};var w=new World{Station=s};w.Player=new(){world=w};GameManager.Instance=new(){World=w};RebirthWorldCharacterService.Owner=new();var o=RebirthWorldCharacterService.Owner;o.Progression.StationPreparations.Add("job",new());o.Progression.StationPublications.Add("job",new());RebirthStationObservationDispatcher.Verified=true;RebirthWorldCharacterRepository.Save=true;RebirthWorldCharacterRepository.SavedCompletion=true;RebirthWorldCharacterRepository.OnSave=null;RebirthWorldCharacterRepository.OnPublicationRead=null;RebirthStationSnapshotEvidence.Capacity=true;RebirthStationSnapshotEvidence.Published=false;return s;}
 static RebirthStationCompletionCapture.SuccessfulOutput Complete(TileEntityWorkstation s){var v=new ItemValue(10);Check(RebirthStationCompletionCapture.TryObserveBefore(s,1,v,"job","",7,2,out var before),"pre-output scope");s.Output[0]=new(v.Clone(),2);Check(RebirthStationCompletionCapture.TryAppend(s,1,v,"job","",7,2,before,out var completed)&&completed!=null,"actual committed event");Check(!RebirthStationCompletionCapture.TryAppend(s,1,v,"job","",7,2,before,out _),"event cannot reissue");return completed;}
 static void Main(){
 var s=Setup();var e=Complete(s);Check(!RebirthStationCompletionObservation.TryBegin(e,out _)&&RebirthWorldCharacterService.Owner.Progression.StationTerminalIntents.Count==0,"premature queue exit no intent");s.Queue=Array.Empty<RecipeQueueItem>();Check(RebirthStationCompletionObservation.TryBegin(e,out var watch),"closed-UI independent begin");Check(!RebirthStationCompletionObservation.TryBegin(e,out _),"single claimed event");Check(!watch.TrySavePublication(out _)&&RebirthWorldCharacterService.Owner.Progression.StationCompletionPublications.Count==0,"no published proof no record");RebirthStationSnapshotEvidence.Published=true;RebirthWorldCharacterRepository.Save=false;Check(!watch.TrySavePublication(out _)&&RebirthWorldCharacterService.Owner.Progression.StationCompletionPublications.Count==1,"failed save retains record");RebirthWorldCharacterRepository.Save=true;RebirthWorldCharacterRepository.SavedCompletion=false;Check(!watch.TrySavePublication(out _),"final saved witness mandatory");RebirthWorldCharacterRepository.SavedCompletion=true;Check(watch.TrySavePublication(out var record)&&record!=null,"exact original retry saves");watch.Dispose();Check(!watch.TrySavePublication(out _),"disposed producer refuses");
 s=Setup();e=Complete(s);s.Queue=Array.Empty<RecipeQueueItem>();RebirthStationSnapshotEvidence.Capacity=false;Check(!RebirthStationCompletionObservation.TryBegin(e,out _),"capacity retains event");RebirthStationSnapshotEvidence.Capacity=true;Check(RebirthStationCompletionObservation.TryBegin(e,out watch),"capacity exact event retry");watch.Dispose();
 s=Setup();e=Complete(s);s.Queue=Array.Empty<RecipeQueueItem>();GameIO.Root=System.IO.Path.Combine(System.IO.Path.GetTempPath(),"station-original-b");Check(!RebirthStationCompletionObservation.TryBegin(e,out _),"same images different real root refuse");
 s=Setup();var v=new ItemValue(10);RebirthWorldCharacterRepository.OnPublicationRead=()=>GameIO.Root=System.IO.Path.Combine(System.IO.Path.GetTempPath(),"station-original-b");Check(!RebirthStationCompletionCapture.TryObserveBefore(s,1,v,"job","",7,2,out _),"reentrant root during saved read refuses pre-output");
 s=Setup();e=Complete(s);s.Queue=Array.Empty<RecipeQueueItem>();RebirthWorldCharacterRepository.OnSave=()=>GameManager.Instance.World.worldState.Guid="replacement";Check(!RebirthStationCompletionObservation.TryBegin(e,out _),"reentrant native guid during intent save refuses");
 s=Setup();e=Complete(s);s.Queue=Array.Empty<RecipeQueueItem>();Check(RebirthStationCompletionObservation.TryBegin(e,out watch),"original watch");GameManager.Instance.World=new World();RebirthStationSnapshotEvidence.Published=true;Check(!watch.TrySavePublication(out _),"replacement world cannot publish");watch.Dispose();
 s=Setup();e=Complete(s);s.Queue=Array.Empty<RecipeQueueItem>();Check(RebirthStationCompletionObservation.TryBegin(e,out watch),"original receipt watch");s.CraftCompleteList[0].CraftedItemStack.itemValue.Metadata["tampered"]=1;Check(!watch.TrySavePublication(out _),"receipt full identity tamper refuses");watch.Dispose();
 s=Setup();v=new ItemValue(10);Check(RebirthStationCompletionCapture.TryObserveBefore(s,1,v,"job","",7,2,out var observation),"modified throw original");s.Output[0]=new(v.Clone(),2);s.ThrowModified=true;Check(!RebirthStationCompletionCapture.TryAppend(s,1,v,"job","",7,2,observation,out e)&&e==null&&s.CraftCompleteList.Count==1,"modified throw no event retained receipt");
 Check(!RebirthStationCompletionCapture.SuccessfulOutput.TryMint(new object(),observation,s,s.CraftCompleteList[0],out _),"caller cannot mint failed modified event");
 s=Setup();var owner=RebirthWorldCharacterService.Owner;owner.Progression.StationPreparations.Add("job2",new(){JobId="job2"});owner.Progression.StationPublications.Add("job2",new());
 s.Queue=new[]{new RecipeQueueItem{StartingEntityId=1,Recipe=new(){Marked=true,Name="job2"}},new RecipeQueueItem{StartingEntityId=1,Recipe=new(){Marked=true,Name="job"}}};
 GameSparksCollector.Throw=false;s.ActualNativeHandleRecipeQueue(0);Check(s.CraftCompleteList.Count==2&&s.Output[0].count==4,"actual installed while produces two distinct paid events");
 RebirthStationSnapshotEvidence.Capacity=false;Check(RebirthStationPaidCompletionCallsite.FinalizeIteration(s,null)==null&&owner.Progression.StationCompletionPublications.Count==0,"successful original exit preserves capacity retries");
 RebirthStationSnapshotEvidence.Capacity=true;RebirthStationSnapshotEvidence.Published=true;Check(RebirthStationPaidCompletionCallsite.TrySuccessfulOriginalExit(s)&&owner.Progression.StationCompletionPublications.Count==2,"two exact pending events finish independent save witnesses");
 Check(!RebirthStationPaidCompletionCallsite.TrySuccessfulOriginalExit(s),"retired original events cannot replay save");
 s=Setup();GameSparksCollector.Throw=true;Exception thrown=null;try{s.ActualNativeHandleRecipeQueue(0);}catch(Exception ex){thrown=ex;}
 Check(object.ReferenceEquals(thrown,GameSparksCollector.Failure)&&s.CraftCompleteList.Count==1&&s.Output[0].count==2,"actual native post-completion exception preserves effect");
 Check(object.ReferenceEquals(RebirthStationPaidCompletionCallsite.FinalizeIteration(s,thrown),thrown)&&RebirthStationPaidCompletionCallsite.HasUncertainEffect(s),"exception exit never begins completion producer");
 Check(!RebirthStationPaidCompletionCallsite.TrySuccessfulOriginalExit(s)&&RebirthWorldCharacterService.Owner.Progression.StationTerminalIntents.Count==0,"exceptional original event remains unresolved");GameSparksCollector.Throw=false;
 Console.WriteLine($"PASS {n}: actual Capture/OriginalScope/CompletionObservation/Delta; explicit native owner/publication/repository adapters, no live engine or real repository claim.");
 }
}
