using System;using System.Collections;using System.Collections.Generic;using System.Linq;
namespace HarmonyLib{class HarmonyPatch:Attribute{public HarmonyPatch(Type t,string s){}}}
namespace GameEvent.SequenceActions{class BaseAction{public enum ActionCompleteStates{InComplete,InCompleteRefund,Complete}}class ActionPOIReset:BaseAction{public enum State{Start,Wait}public State _state=State.Wait;public ActionCompleteStates _retVal;public Owner Owner=new Owner();public IEnumerator onPerformAction()=>null;public void OnReset(){}}class Owner{public PrefabInstance POIInstance=new PrefabInstance();public Entity Requester=new Entity();}}
class Entity{public int entityId=7;}class PrefabInstance{}
class World{public bool Remote;public EntityPlayer Player=new EntityPlayer();public bool IsRemote()=>Remote;public EntityPlayer GetEntity(int id)=>Player.entityId==id?Player:null;public EntityPlayer[] GetLocalPlayers()=>new[]{Player};public static int toChunkXZ(int n)=>n>>4;}
class Decorator{public List<PrefabInstance> Targets=new List<PrefabInstance>{new PrefabInstance()};public List<PrefabInstance> GetPrefabsIntersecting(PrefabInstance p)=>Targets;public List<PrefabInstance> GetPrefabsFromWorldPosInside(Position p,FastTags<TagGroup.Global> tags)=>Targets;}
class GameManager{public static bool IsDedicatedServer;public static GameManager Instance=new GameManager();public World World=new World();public Decorator Decorator=new Decorator();public Decorator GetDynamicPrefabDecorator()=>Decorator;public bool IsEditMode()=>false;}
class GameUtils{public static bool IsPlaytesting()=>false;}
class RebirthPurgeReleasePolicy{public static bool Enabled=true;}
class RebirthSandboxOptionManager{public static RebirthSandboxOptionManager Current=new RebirthSandboxOptionManager();public bool PoiClearTrackingEnabled=true;}
class ThreadManager{public static List<IEnumerator> Pending=new List<IEnumerator>();public static void StartCoroutine(IEnumerator e){Pending.Add(e);}}
class TagGroup{public class Global{}}struct FastTags<T>{public static FastTags<T> none;}class QuestClass{}class QuestEventManager{public static FastTags<TagGroup.Global> manualResetTag=new FastTags<TagGroup.Global>();}
class RebirthPoiWorldBinding{public Guid WorldId=Guid.NewGuid();}class Snapshot{public RebirthPoiWorldBinding Binding=new RebirthPoiWorldBinding();public bool Found=true;public bool TryGet(object key,out RebirthPoiClearanceRecord r){r=new RebirthPoiClearanceRecord();return Found;}}class RebirthPoiClearanceRecord{}
class RebirthPoiWorldStore{public Snapshot Published=new Snapshot();public bool HasPending;public bool TryDiscover(Snapshot s,object identity,bool resetOnly=false){s.Found=true;return true;}}
class RebirthPoiWorldLifecycle{public static RebirthPoiWorldLifecycle Instance=new RebirthPoiWorldLifecycle();public RebirthPoiWorldStore Store=new RebirthPoiWorldStore();public bool Ready=true;public bool TryGetStore(out RebirthPoiWorldStore s){s=Ready?Store:null;return Ready;}}
class Expected{public bool Combat=true;}class Slot{public Expected Expected=new Expected();}
class RebirthPoiNativeAuthoredManifest{public object Identity=new object();public Slot[] Slots=new[]{new Slot()};public static bool Accept=true;public static bool TryCapture(RebirthPoiWorldBinding b,World w,PrefabInstance p,out RebirthPoiNativeAuthoredManifest a){a=new RebirthPoiNativeAuthoredManifest();return Accept;}}
enum RebirthPoiResetCaller{Event,ManualPoi}enum RebirthPoiResetProtocolState{PendingAdmission,Ready,Completed,Unknown,Refused}
class RebirthPoiResetBatchCompletion{public object Scope;public Guid World,Transaction;}
class Batch{public RebirthPoiResetProtocolState State=RebirthPoiResetProtocolState.Ready;public RebirthPoiResetBatchCompletion Receipt;public int Drains;public bool TryGetCompleted(out RebirthPoiResetBatchCompletion r){r=Receipt;return State==RebirthPoiResetProtocolState.Completed;}public bool PollCancellation(){Drains++;return true;}}
class RebirthPoiNativeResetExecution:IEnumerator{public static RebirthPoiNativeResetExecution Latest;public static int Created,Moves;public static bool Admit=true,Uncertain,WrongReceipt;public Batch Batch=new Batch();public object Current=>null;public bool TryAdmitBeforeMutation()=>Admit;public bool MoveNext(){Moves++;Batch.State=Uncertain?RebirthPoiResetProtocolState.Unknown:RebirthPoiResetProtocolState.Completed;return false;}public void Reset(){}public bool Disposed;public void Dispose(){Disposed=true;}public static bool TryCreateWorldReset(RebirthPoiWorldStore s,World w,List<PrefabInstance> p,FastTags<TagGroup.Global> tag,int player,object guests,QuestClass quest,RebirthPoiResetCaller role,Guid tx,Func<bool> current,Func<double> clock,out RebirthPoiNativeResetExecution e){Created++;Latest=e=new RebirthPoiNativeResetExecution();e.Batch.Receipt=new RebirthPoiResetBatchCompletion{Scope=w,World=s.Published.Binding.WorldId,Transaction=WrongReceipt?Guid.NewGuid():tx};return true;}}
struct Position{public float x,z;}class EntityPlayer:Entity{public Position position;}
class ClientInfo{public bool loginDone=true;public int entityId=7;}
class Clients{public ClientInfo Sender;public ClientInfo ForEntityId(int id)=>Sender!=null&&Sender.entityId==id?Sender:null;}
class ConnectionManager{public Clients Clients=new Clients();}
class SingletonMonoBehaviour<T> where T:new(){public static T Instance=new T();}
class CommandSenderInfo{public ClientInfo RemoteClientInfo;public bool IsLocalGame;}
class ConsoleCmdChunkReset{public void Execute(List<string> p,CommandSenderInfo s){}}
class SdtdConsole{public List<string> Lines=new List<string>();public void Output(string s){Lines.Add(s);}}
class Localization{public static string Get(string key)=>key;}
class DynamicMeshManager{public static DynamicMeshManager Instance=new DynamicMeshManager();public int Updates;public void AddChunk(long k,bool addToThread,bool primary,object last){Updates++;}}
class WorldChunkCache{public static long MakeChunkKey(int x,int z)=>((long)x<<32)|(uint)z;}
static class Program{static int n;static void Check(bool ok,string label){if(!ok)throw new Exception(label);Console.WriteLine("PASS "+label);n++;}static GameEvent.SequenceActions.ActionPOIReset Fresh(){RebirthPoiScriptResetOwner.Reset();GameManager.Instance=new GameManager();RebirthPoiWorldLifecycle.Instance=new RebirthPoiWorldLifecycle();RebirthPoiNativeAuthoredManifest.Accept=true;RebirthPoiNativeResetExecution.Created=RebirthPoiNativeResetExecution.Moves=0;RebirthPoiNativeResetExecution.Admit=true;RebirthPoiNativeResetExecution.Uncertain=RebirthPoiNativeResetExecution.WrongReceipt=false;ThreadManager.Pending.Clear();return new GameEvent.SequenceActions.ActionPOIReset();}static void Finish(IEnumerator e){int bound=100;while(e.MoveNext()&&--bound>0){}if(bound==0)throw new Exception("unbounded fixture");}
static void Main(){var a=Fresh();var e=RebirthPoiScriptResetOwner.Capture(a);Check(RebirthPoiNativeResetExecution.Created==0,"capture does not advance reset");Finish(e);Check(a._retVal==GameEvent.SequenceActions.BaseAction.ActionCompleteStates.Complete&&RebirthPoiNativeResetExecution.Moves==1,"exact completed reset applies native action success");Check(RebirthPoiNativeResetExecution.Latest.Disposed,"completed action releases execution");
a=Fresh();GameManager.Instance.World.Remote=true;Finish(RebirthPoiScriptResetOwner.Capture(a));Check(a._retVal==GameEvent.SequenceActions.BaseAction.ActionCompleteStates.InCompleteRefund&&RebirthPoiNativeResetExecution.Created==0,"remote script cannot reset world");
a=Fresh();RebirthPoiNativeAuthoredManifest.Accept=false;Finish(RebirthPoiScriptResetOwner.Capture(a));Check(RebirthPoiNativeResetExecution.Created==0&&a._retVal!=GameEvent.SequenceActions.BaseAction.ActionCompleteStates.Complete,"unqualified target refuses before native work");
a=Fresh();RebirthPoiNativeResetExecution.Uncertain=true;Finish(RebirthPoiScriptResetOwner.Capture(a));Check(a._retVal!=GameEvent.SequenceActions.BaseAction.ActionCompleteStates.Complete,"uncertain execution withholds script success");
a=Fresh();RebirthPoiNativeResetExecution.WrongReceipt=true;Finish(RebirthPoiScriptResetOwner.Capture(a));Check(a._retVal!=GameEvent.SequenceActions.BaseAction.ActionCompleteStates.Complete,"foreign transaction cannot complete script");
a=Fresh();RebirthPoiNativeResetExecution.Admit=false;e=RebirthPoiScriptResetOwner.Capture(a);Check(e.MoveNext()&&RebirthPoiNativeResetExecution.Moves==0,"durable admission waits without native advance");RebirthPoiScriptResetOwner.Invalidate(a);a._state=GameEvent.SequenceActions.ActionPOIReset.State.Start;Finish(e);Check(a._retVal==GameEvent.SequenceActions.BaseAction.ActionCompleteStates.InComplete&&RebirthPoiNativeResetExecution.Moves==0,"reused action cannot receive original success or refund");
a=Fresh();RebirthPoiNativeResetExecution.Admit=false;e=RebirthPoiScriptResetOwner.Capture(a);e.MoveNext();GameManager.Instance.World=new World();Finish(e);Check(RebirthPoiNativeResetExecution.Moves==0&&a._retVal!=GameEvent.SequenceActions.BaseAction.ActionCompleteStates.Complete,"replacement world invalidates pending reset");
a=Fresh();RebirthPoiNativeResetExecution.Admit=false;e=RebirthPoiScriptResetOwner.Capture(a);e.MoveNext();GameManager.Instance.Decorator.Targets.Add(new PrefabInstance());Finish(e);Check(RebirthPoiNativeResetExecution.Moves==0,"changed original target list invalidates reset");var prefix=typeof(RebirthPoiAdministrativeResetHook).GetMethod("Prefix",System.Reflection.BindingFlags.NonPublic|System.Reflection.BindingFlags.Static);
a=Fresh();SingletonMonoBehaviour<ConnectionManager>.Instance=new ConnectionManager();SingletonMonoBehaviour<SdtdConsole>.Instance=new SdtdConsole();DynamicMeshManager.Instance=new DynamicMeshManager();
Check(!(bool)prefix.Invoke(null,new object[]{new List<string>(),new CommandSenderInfo{IsLocalGame=true}})&&RebirthPoiNativeResetExecution.Moves==0,"admin POI request captures before any native mutation");Finish(ThreadManager.Pending[0]);Check(SingletonMonoBehaviour<SdtdConsole>.Instance.Lines.Single()=="xuiRebirthPoiResetCompleted"&&DynamicMeshManager.Instance.Updates==9,"admin success and mesh updates follow original durable receipt");
a=Fresh();var remote=new ClientInfo();SingletonMonoBehaviour<ConnectionManager>.Instance.Clients.Sender=remote;Check(!(bool)prefix.Invoke(null,new object[]{new List<string>(),new CommandSenderInfo{RemoteClientInfo=remote}}),"authenticated remote administrator uses shared reset owner");SingletonMonoBehaviour<ConnectionManager>.Instance.Clients.Sender=new ClientInfo();Finish(ThreadManager.Pending[0]);Check(RebirthPoiNativeResetExecution.Moves==0,"changed admin connection cannot reset original POI");
a=Fresh();Check(!(bool)prefix.Invoke(null,new object[]{new List<string>(),new CommandSenderInfo{RemoteClientInfo=new ClientInfo()}})&&ThreadManager.Pending.Count==0,"unregistered admin sender refused before scheduling");
a=Fresh();Check((bool)prefix.Invoke(null,new object[]{new List<string>{"u"},new CommandSenderInfo{IsLocalGame=true}}),"non-POI admin command remains native");
a=Fresh();GameManager.Instance.Decorator.Targets.Clear();Check((bool)prefix.Invoke(null,new object[]{new List<string>(),new CommandSenderInfo{IsLocalGame=true}}),"terrain-only command retains separate native owner");
a=Fresh();var throwFinish=RebirthPoiOwnedWorldReset.Run(GameManager.Instance.World,GameManager.Instance.Decorator.Targets,QuestEventManager.manualResetTag,-1,null,RebirthPoiResetCaller.Event,()=>true,success=>throw new Exception("notification"));try{Finish(throwFinish);}catch(Exception error){if(error.Message!="notification")throw;}Check(RebirthPoiNativeResetExecution.Latest.Disposed,"notification failure cannot retain native execution");
Console.WriteLine("RESULT "+n+" PASS; production scripted owner, native reset/store/engine doubles; game not run.");}}