using System;using System.Collections.Generic;using System.Xml.Linq;
class BlockStub{public string GetBlockName()=>"station";}
struct Vector3i{public int x,y,z;public Vector3i(int x,int y,int z){this.x=x;this.y=y;this.z=z;}}
class State{public string Guid="cccccccccccccccccccccccccccccccc";}class Chunk{}
class World{public bool IsRemote()=>false;public State worldState=new();public EntityPlayer Player;public TileEntityWorkstation Station;public Chunk Chunk=new();public object GetEntity(int id)=>Player?.entityId==id?Player:null;public object GetTileEntity(Vector3i p)=>Station;public object GetChunkSync(int x,int z)=>Chunk;}
class EntityPlayer{public int entityId=1;public World world;public bool IsDead()=>false;}
class GameManager{public static GameManager Instance=new();public World World;}
static class GameIO{public static string Root=System.IO.Path.Combine(System.IO.Path.GetTempPath(),"station-original-a");public static string GetSaveGameDir()=>Root;}
class RebirthStablePlayerIdentity{public string StorageKey="owner",CanonicalId="canonical";}
class Origin{public string CreationId="bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb";}
class RebirthWorldCharacterRecord{public string StablePlayerKey="owner",StablePlayerId="canonical";public Origin Origin=new();public RebirthWorldProgressionState Progression=new();}
class RebirthWorldProgressionState{public Dictionary<string,RebirthStationDiscoveryAdmissionBinding> StationDiscoveryAdmissions=new();public Dictionary<string,RebirthStationGridAdmission> StationPreparations=new();public Dictionary<string,RebirthStationPublicationRecord> StationPublications=new();public Dictionary<string,RebirthStationTerminalIntent> StationTerminalIntents=new();public Dictionary<string,object> StationCancellationAttempts=new(),StationCancellationRefunds=new();public Dictionary<string,RebirthStationCompletionPublication> StationCompletionPublications=new();}
class RebirthStationPublicationRecord{public XElement Write()=>new("queued");public RebirthStationPublicationRecord Clone()=>new();}
static class RebirthWorldCharacterService{public static RebirthWorldCharacterRecord Owner;public static bool TryGet(EntityPlayer p,out RebirthWorldCharacterRecord o){o=Owner;return true;}public static bool TryGetIdentity(EntityPlayer p,out RebirthStablePlayerIdentity i){i=new(){StorageKey=Owner.StablePlayerKey,CanonicalId=Owner.StablePlayerId};return true;}public static void MarkDirty(RebirthWorldCharacterRecord o,string why){}}
static class RebirthWorldCharacterRepository{public static bool IsServerAuthority=true;public static bool SavedBinding=true;public static Action BindingRead;public static bool HasSavedStationDiscoveryAdmission(RebirthStablePlayerIdentity i,RebirthStationGridAdmission a,RebirthStationDiscoveryAdmissionBinding b){var action=BindingRead;BindingRead=null;action?.Invoke();return SavedBinding;}public static bool Save=true,SavedCompletion=true;public static Action OnPublicationRead,OnSave;public static int Saves;public static bool IsCurrentCachedRecord(RebirthWorldCharacterRecord o)=>ReferenceEquals(o,RebirthWorldCharacterService.Owner);public static bool HasSavedStationPublication(RebirthStablePlayerIdentity i,RebirthStationGridAdmission a,RebirthStationPublicationRecord q){var call=OnPublicationRead;OnPublicationRead=null;call?.Invoke();return true;}public static bool SaveIfDirty(RebirthStablePlayerIdentity i,string why){Saves++;var call=OnSave;OnSave=null;call?.Invoke();return Save;}public static bool HasSavedStationTerminalIntent(RebirthStablePlayerIdentity i,RebirthStationGridAdmission a,RebirthStationTerminalIntent t)=>true;public static bool HasSavedStationCompletionPublication(RebirthStablePlayerIdentity i,RebirthStationGridAdmission a,RebirthStationTerminalIntent t,RebirthStationPublicationRecord q,RebirthStationCompletionPublication c)=>SavedCompletion;}
class RebirthStationTerminalIntent{public XElement Write()=>new("intent");public RebirthStationTerminalIntent Clone()=>new();public static bool TryCreate(RebirthStationGridAdmission a,bool c,int actor,out RebirthStationTerminalIntent i){i=new();return true;}}
static class XUiM_Recipes{public static IList<Recipe> GetRecipes()=>new List<Recipe>();}
class RebirthStationCompletionExpectation{private TileEntityWorkstation station;public static bool TryCreate(TileEntityWorkstation s,RebirthStationGridAdmission a,RebirthStationTerminalIntent i,RebirthStationPublicationRecord q,IList<Recipe> d,out RebirthStationCompletionExpectation e){e=null;if(System.Linq.Enumerable.Any(s.Queue,q=>q?.Recipe!=null))return false;e=new(){station=s};return true;}public bool MatchesLive(TileEntityWorkstation s)=>ReferenceEquals(s,station)&&!System.Linq.Enumerable.Any(s.Queue,q=>q?.Recipe!=null);public bool MatchesStation(byte[] a,byte[] b)=>true;public bool MatchesTerminal(byte[] a,byte[] b)=>true;}
class RebirthStationCompletionPublication{public XElement Write()=>new("completed");public RebirthStationCompletionPublication Clone()=>new();public bool Revalidate(string r,RebirthStationGridAdmission a,RebirthStationTerminalIntent i,RebirthStationPublicationRecord q,RebirthStationCompletionExpectation e)=>true;public static bool TryCreate(string r,RebirthStationGridAdmission a,RebirthStationTerminalIntent i,RebirthStationPublicationRecord q,RebirthStationCompletionExpectation e,RebirthStationSnapshotEvidence.Publication p,out RebirthStationCompletionPublication c){c=new();return true;}}
class RebirthStationSnapshotEvidence{public class Request:IDisposable{public bool Closed;public Func<bool> Current;public void Dispose(){Closed=true;}}public class Publication{}public static bool Capacity=true,Published;public static Request Watch(object w,object c,int x,int z,Func<bool> current,object t,Func<byte[],byte[],bool> s,Func<byte[],byte[],bool> e)=>Capacity?new(){Current=current}:null;public static bool TryGetPublished(Request r,out Publication p){p=null;if(r.Closed||!Published||!r.Current())return false;p=new();return true;}}
