using System;using System.IO;
class Program{
 const string Job="11111111111111111111111111111111";static int n;static void Check(bool x,string why){n++;if(!x)throw new Exception(why);}
 static TileEntityWorkstation Setup(){var s=new TileEntityWorkstation{Queue=new[]{new RecipeQueueItem{StartingEntityId=1,Recipe=new(){Marked=true,Name=Job}}}};var w=new World{Station=s};w.Player=new(){world=w};GameManager.Instance=new(){World=w};GameIO.Root=Path.Combine(Path.GetTempPath(),"queued-discovery-a");RebirthWorldCharacterService.Owner=new(){StablePlayerKey=new string('a',64)};var owner=RebirthWorldCharacterService.Owner;var current=new RebirthStationGridAdmission();owner.Progression.StationPreparations.Add(Job,current);owner.Progression.StationPublications.Add(Job,new());var frozen=current.Clone();frozen.IsPublicationAttempted=false;
 Check(RebirthStationDiscoveryWitness.TryCreate(frozen,owner.StablePlayerKey,RebirthStationDiscoveryAuthorityScope.Digest(RebirthStationDiscoveryAuthorityScope.Root(),Guid.Parse(w.worldState.Guid)),new string('d',64),"knowledge",out var witness),"actual original witness");Check(RebirthStationDiscoveryAdmissionBinding.TryCreateDetached("nativeRecipe",witness,frozen,out var binding),"actual frozen binding");owner.Progression.StationDiscoveryAdmissions.Add(Job,binding);RebirthCookingBatch.Cooking=false;RebirthStationObservationDispatcher.Verified=true;RebirthWorldCharacterRepository.SavedBinding=true;RebirthWorldCharacterRepository.BindingRead=null;RebirthWorldCharacterRepository.OnPublicationRead=null;RebirthStationDiscoveryCanonicalRecipe.Valid=true;RebirthStationDiscoveryCanonicalRecipe.Canonical="nativeRecipe";RebirthCraftingProgressionRegistry.SemanticHash=new string('d',64);RebirthStationDiscoveryScope.Unlocked=true;RebirthRecipeDiscoveryRules.AllowsDiscovery=true;RebirthCapabilityService.Skills=true;RebirthCapabilityService.Known=false;RebirthCapabilityService.DiscoveryCalls=0;RebirthCapabilityService.NormalCalls=0;RebirthCapabilityService.OnDiscovery=null;return s;}
 static bool Evaluate(TileEntityWorkstation s,out bool allowed)=>RebirthStationQueuedDiscoveryAuthorization.TryEvaluate(s,s.Queue[0],GameManager.Instance.World.Player,out allowed,out _);
 static void Main(){var s=Setup();Check(!RebirthCapabilityService.EvaluateRecipe(GameManager.Instance.World.Player,"nativeRecipe").IsAllowed,"unknown normal denied");Check(Evaluate(s,out var allowed)&&allowed&&RebirthCapabilityService.DiscoveryCalls==1,"bound unknown discovery permitted closed station");
 s=Setup();RebirthCapabilityService.Skills=false;Check(Evaluate(s,out allowed)&&!allowed,"current skill denied despite discovery");
 s=Setup();RebirthWorldCharacterService.Owner.Progression.StationDiscoveryAdmissions.Clear();Check(!Evaluate(s,out allowed)&&!allowed&&RebirthCapabilityService.DiscoveryCalls==0,"normal marked absent binding retains ordinary gate");
 s=Setup();s.Queue[0].Recipe.Marked=false;Check(!Evaluate(s,out allowed)&&RebirthCapabilityService.DiscoveryCalls==0,"external universal unmarked unchanged");
 s=Setup();RebirthCookingBatch.Cooking=true;Check(!Evaluate(s,out allowed)&&RebirthCapabilityService.DiscoveryCalls==0,"cooking untouched");
 s=Setup();RebirthWorldCharacterRepository.SavedBinding=false;Check(Evaluate(s,out allowed)&&!allowed&&RebirthCapabilityService.DiscoveryCalls==0,"unsaved binding denied");
 s=Setup();RebirthCraftingProgressionRegistry.SemanticHash=new string('e',64);Check(Evaluate(s,out allowed)&&!allowed,"stale policy denied");
 s=Setup();GameIO.Root=Path.Combine(Path.GetTempPath(),"queued-discovery-b");Check(Evaluate(s,out allowed)&&!allowed,"same data other save denied");
 s=Setup();GameManager.Instance.World.worldState.Guid="eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee";Check(Evaluate(s,out allowed)&&!allowed,"other native world denied");
 s=Setup();RebirthWorldCharacterService.Owner.StablePlayerKey=new string('f',64);Check(Evaluate(s,out allowed)&&!allowed,"other authenticated owner denied");
 s=Setup();RebirthStationDiscoveryCanonicalRecipe.Canonical="aliasRecipe";Check(Evaluate(s,out allowed)&&!allowed,"canonical alias denied");
 s=Setup();RebirthStationDiscoveryCanonicalRecipe.Valid=false;Check(Evaluate(s,out allowed)&&!allowed,"unresolved native definition denied");
 s=Setup();RebirthCapabilityService.OnDiscovery=()=>GameIO.Root=Path.Combine(Path.GetTempPath(),"queued-discovery-b");Check(Evaluate(s,out allowed)&&!allowed,"reentrant save switch denied after evaluator");
 s=Setup();RebirthWorldCharacterRepository.BindingRead=()=>GameManager.Instance.World.worldState.Guid="eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee";Check(Evaluate(s,out allowed)&&!allowed,"saved binding callback world mutation denied");
 s=Setup();RebirthRecipeDiscoveryRules.AllowsDiscovery=false;Check(Evaluate(s,out allowed)&&!allowed,"required reading policy still denied");
 s=Setup();Check(RebirthRecipeCapabilityIntegration.AuthorizeActiveQueue(s)&&RebirthCapabilityService.DiscoveryCalls==1&&RebirthCapabilityService.NormalCalls==0,"whole closed gate routes unknown paid discovery only");
 RebirthCapabilityService.Skills=false;Check(!RebirthRecipeCapabilityIntegration.AuthorizeActiveQueue(s)&&RebirthRecipeCapabilityIntegration.Held(s)!=null,"whole gate holds current capability");RebirthCapabilityService.Skills=true;Check(RebirthRecipeCapabilityIntegration.AuthorizeActiveQueue(s)&&RebirthRecipeCapabilityIntegration.Held(s)==null,"restored capability clears held queue");
 s=Setup();RebirthWorldCharacterService.Owner.Progression.StationDiscoveryAdmissions.Clear();Check(!RebirthRecipeCapabilityIntegration.AuthorizeActiveQueue(s)&&RebirthCapabilityService.NormalCalls==1&&RebirthCapabilityService.DiscoveryCalls==0,"ordinary marked unknown uses normal denied gate");RebirthCapabilityService.Known=true;Check(RebirthRecipeCapabilityIntegration.AuthorizeActiveQueue(s)&&RebirthCapabilityService.NormalCalls==2,"ordinary marked known retains normal allowed gate");
 s=Setup();RebirthWorldCharacterService.Owner.Progression.StationDiscoveryAdmissions[Job]=null;RebirthCapabilityService.Known=true;Check(!RebirthRecipeCapabilityIntegration.AuthorizeActiveQueue(s)&&RebirthCapabilityService.NormalCalls==0,"invalid retained binding cannot fallback normal allowed gate");
 s=Setup();RebirthCookingBatch.Cooking=true;RebirthCapabilityService.Skills=false;Check(RebirthRecipeCapabilityIntegration.AuthorizeActiveQueue(s)&&RebirthCapabilityService.DiscoveryCalls==0&&RebirthCapabilityService.NormalCalls==0,"whole gate cooking unchanged");
 s=Setup();RebirthStationGridQueue.MultiplierValid=false;Check(!RebirthRecipeCapabilityIntegration.AuthorizeActiveQueue(s)&&RebirthCapabilityService.DiscoveryCalls==0,"multiplier refused before discovery");RebirthStationGridQueue.MultiplierValid=true;
 s=Setup();RebirthStationGridQueue.DefinitionValid=false;Check(!RebirthRecipeCapabilityIntegration.AuthorizeActiveQueue(s)&&RebirthCapabilityService.DiscoveryCalls==0,"unresolved definition refused before discovery");RebirthStationGridQueue.DefinitionValid=true;
 s=Setup();s.Queue[0].StartingEntityId=999;Check(!RebirthRecipeCapabilityIntegration.AuthorizeActiveQueue(s)&&RebirthCapabilityService.DiscoveryCalls==0,"unavailable original crafter remains held");
 s=Setup();s.Queue[0].Recipe.Marked=false;RebirthCapabilityService.Known=true;Check(RebirthRecipeCapabilityIntegration.AuthorizeActiveQueue(s)&&RebirthCapabilityService.NormalCalls==1&&RebirthCapabilityService.DiscoveryCalls==0,"unmarked universal external retains normal route");
 Console.WriteLine($"PASS {n}: actual queued helper/original scope/witness/binding/phase pairing/save fingerprint; native canonical/current policy/repository adapters explicit.");}}
