using System;
class Program{
 static int n;static void Check(bool x,string why){n++;if(!x)throw new Exception(why);}
 static XUiC_WorkstationWindowGroup Setup(bool mixed=false){var s=new TileEntityWorkstation{bUserAccessing=true,Queue=new[]{new RecipeQueueItem{StartingEntityId=1,Recipe=new(){Marked=true,Name="paid"}}}};if(mixed)s.Queue=new[]{new RecipeQueueItem{StartingEntityId=1,Recipe=new(){Marked=false,Name="ordinary"}},s.Queue[0]};var w=new World{Station=s};w.Player=new(){world=w};GameManager.Instance=new(){World=w};RebirthWorldCharacterService.Owner=new();RebirthWorldCharacterService.Owner.Progression.StationPreparations.Add("paid",new(){JobId="paid"});RebirthWorldCharacterService.Owner.Progression.StationPublications.Add("paid",new());GameIO.Root=System.IO.Path.Combine(System.IO.Path.GetTempPath(),"open-paid-original");RebirthStationObservationDispatcher.Verified=true;RebirthStationLiveAccess.Locked=true;RebirthCapabilityService.Allowed=true;RebirthStationQueuedDiscoveryAuthorization.Discovery=false;RebirthStationQueuedDiscoveryAuthorization.Allowed=true;RebirthWorldCharacterRepository.OnSave=null;RebirthWorldCharacterRepository.OnPublicationRead=null;RebirthWorldCharacterRepository.Save=true;GameSparksCollector.Throw=false;ItemStack.Full=false;ItemStack.ThrowAfter=false;ItemStack.MutateContext=false;return new(){xui=new(){playerUI=new(){entityPlayer=w.Player}},WorkstationData=new(){TileEntity=s}};}
 static void Main(){var g=Setup(true);var s=g.WorkstationData.TileEntity;Check(RebirthStationOpenPaidExecutionLease.ShouldBlockUserAccess(s,true),"unleased native open guard intact");Check(RebirthStationOpenPaidExecutionLease.TryEnter(g,out var lease),"authentic local server window admitted");Check(!RebirthStationOpenPaidExecutionLease.ShouldBlockUserAccess(s,true),"exact paid guard admitted");Check(!RebirthStationOpenPaidExecutionLease.TryEnter(g,out _),"reentrant lease refused before effect");s.ActualNativeCandidateWhile(0);Check(s.Output[0].count==2&&s.CraftCompleteList.Count==1&&s.NativeCalls==0,"exact native paid output/marked receipt once");Check(lease.YieldedToUiOwnedJob&&s.Queue[1].Recipe.Name=="ordinary"&&s.Queue[1].Multiplier==1,"mixed while yields before ordinary effect without throw");Check(s.CraftCompleteList[0].RecipeName=="paid","ordinary no reward after paid");lease.Dispose();Check(RebirthStationOpenPaidExecutionLease.ShouldBlockUserAccess(s,true),"dispose restores original guard");Check(!RebirthStationOpenPaidExecutionLease.ShouldBlockUserAccess(s,false),"closed native guard false unchanged");
 g=Setup();s=g.WorkstationData.TileEntity;s.isModuleUsed[3]=true;Check(RebirthStationOpenPaidExecutionLease.TryEnter(g,out lease),"native fuel lease");s.ActualNativeCandidateUpdateTick(GameManager.Instance.World);Check(s.FuelUsed==1&&s.MaterialTime==1&&s.lastTickTime==200&&s.LightUpdates==1&&s.VisibleUpdates==1,"extracted UpdateTick fuel/time/material/light bookkeeping intact");Check(s.Output[0].count==2,"native UpdateTick paid once");lease.Dispose();
 g=Setup();s=g.WorkstationData.TileEntity;Check(RebirthStationOpenPaidExecutionLease.TryEnter(g,out lease),"full output lease");ItemStack.Full=true;s.ActualNativeCandidateWhile(0);Check(s.Output[0].count==0&&s.CraftCompleteList==null&&s.Queue[0].Multiplier==1&&!RebirthStationPaidCompletionCallsite.HasUncertainEffect(s),"genuine full paid holds without fallback");lease.Dispose();
 g=Setup();s=g.WorkstationData.TileEntity;Check(RebirthStationOpenPaidExecutionLease.TryEnter(g,out lease),"window original");g.windowGroup.isShowing=false;Check(RebirthStationOpenPaidExecutionLease.ShouldBlockUserAccess(s,true)&&!RebirthStationOpenPaidExecutionLease.AllowsInsertion(s,s.Queue[0]),"window retirement denies before effect");lease.Dispose();
 g=Setup();Check(RebirthStationOpenPaidExecutionLease.TryEnter(g,out lease),"recipe original");s=g.WorkstationData.TileEntity;s.Queue[0].Recipe=new(){Marked=true,Name="paid"};Check(RebirthStationOpenPaidExecutionLease.ShouldBlockUserAccess(s,true),"same marker replacement recipe ref denied");lease.Dispose();
 g=Setup();Check(RebirthStationOpenPaidExecutionLease.TryEnter(g,out lease),"root original");GameIO.Root=System.IO.Path.Combine(System.IO.Path.GetTempPath(),"open-paid-other");Check(RebirthStationOpenPaidExecutionLease.ShouldBlockUserAccess(g.WorkstationData.TileEntity,true),"alternate root denies");lease.Dispose();
 g=Setup();GameManager.Instance.World.Remote=true;Check(!RebirthStationOpenPaidExecutionLease.TryEnter(g,out _),"remote client window cannot mint server lease");
 g=Setup();RebirthStationLiveAccess.Locked=false;Check(!RebirthStationOpenPaidExecutionLease.TryEnter(g,out _),"missing native original lock denied");
 g=Setup();RebirthCapabilityService.Allowed=false;Check(!RebirthStationOpenPaidExecutionLease.TryEnter(g,out _),"normal paid current capability denied");
 g=Setup();RebirthStationQueuedDiscoveryAuthorization.Discovery=true;RebirthStationQueuedDiscoveryAuthorization.Allowed=false;Check(!RebirthStationOpenPaidExecutionLease.TryEnter(g,out _),"bound discovery denied still denied");
 Console.WriteLine($"PASS {n}: actual inactive lease + original completion source; installed native while/UpdateTick extraction, native UI/lock/policy/fuel adapters explicit.");}}
