using System;using System.Linq;using System.Collections.Generic;
namespace NativeLifecycle {
public enum PassiveEffects {CraftingSmeltTime}
public static class TagGroup {public class Global{}}
public struct FastTags<T> {public string Name;public static FastTags<T> Parse(string name)=>new FastTags<T>{Name=name};}
public static class ToolEffects {public static int Calls;public static float Multiplier=1f;}
public static class StringExtensions {public static bool EqualsCaseInsensitive(this string a,string b)=>string.Equals(a,b,StringComparison.OrdinalIgnoreCase);}
public static class XUiM_Recipes {public static bool DisableSmelter;}
public partial class MappedReviewTile:TileEntityWorkstation {
public bool Proof;public int Physical=9;public string[] ExpectedNames=Array.Empty<string>();public MappedReviewTile(Chunk c):base(c){}
bool Qualify(string[] actual,out int physical){physical=Physical;return Proof&&(Physical==3||Physical==9)&&actual!=null&&actual.SequenceEqual(ExpectedNames,StringComparer.Ordinal)&&input.Length==Physical+ExpectedNames.Length&&lastInput.Length==Physical&&currentMeltTimesLeft.Length==Physical;}
bool OriginalOwnerTryQualifySetupBeforeMutation(TileEntityWorkstation tile,Block block,out int physical){physical=Physical;string[] authored=block.Properties.Materials==null?Array.Empty<string>():block.Properties.Materials.Replace(" ","").Split(',');return ReferenceEquals(tile,this)&&Qualify(authored,out physical);}
bool OriginalOwnerTryQualifyMaterialProcessing(TileEntityWorkstation tile,out int physical){physical=Physical;return ReferenceEquals(tile,this)&&Qualify(materialNames,out physical);}
bool OriginalOwnerTryQualifyMappedDestruction(TileEntityWorkstation tile,out int physical){physical=Physical;return ReferenceEquals(tile,this)&&Qualify(materialNames,out physical);}
}
public static class MappedNativeChecks {
static int n;static void Check(bool b,string s){if(!b)throw new Exception(s);n++;}
static void Registry(){ItemClass.Units=new Dictionary<string,ItemClass>{{"unit_iron",new ItemClass{Id=31,Name="iron",MaxCount=100,MadeOfMaterial=new Material{ForgeCategory="iron"}}},{"unit_lead",new ItemClass{Id=32,Name="lead",MaxCount=100,MadeOfMaterial=new Material{ForgeCategory="lead"}}},{"oreIron",new ItemClass{Id=601,Name="oreIron",Weight=2,MeltTimePerUnit=.5f,MadeOfMaterial=new Material{ForgeCategory="iron"}}},{"oreLead",new ItemClass{Id=602,Name="oreLead",Weight=3,MeltTimePerUnit=1,MadeOfMaterial=new Material{ForgeCategory="lead"}}}};CraftingManager.Recipes=new List<Recipe>{new Recipe{itemValueType=701,ingredients=new List<ItemStack>{new ItemStack(new ItemValue(31),2)}},new Recipe{itemValueType=702,ingredients=new List<ItemStack>{new ItemStack(new ItemValue(32),2)}}};}
static T Fill<T>(T tile,int physical) where T:TileEntityWorkstation {
tile.materialNames=new[]{"iron","lead"};tile.chunk.Value.Block.Properties.Materials="iron, lead";tile.chunk.Value.Block.Properties.Modules="MaterialInput";tile.input=ItemStack.CreateArray(physical+2);tile.lastInput=ItemStack.CreateArray(physical);tile.currentMeltTimesLeft=new float[physical];tile.isModuleUsed[4]=true;tile.isModuleUsed[1]=true;
tile.input[0]=new ItemStack(new ItemValue(601){Seed=111,Data="iron ingredient"},3);tile.lastInput[0]=tile.input[0].Clone();tile.currentMeltTimesLeft[0]=.25f;tile.input[1]=new ItemStack(new ItemValue(602){Seed=112,Data="lead ingredient"},1);tile.lastInput[1]=tile.input[1].Clone();tile.currentMeltTimesLeft[1]=-.5f;
tile.input[physical]=new ItemStack(new ItemValue(31){Seed=321,Data="unit iron metadata"},5);tile.input[physical+1]=new ItemStack(new ItemValue(32){Seed=322,Data="unit lead metadata"},7);tile.tools=ItemStack.CreateArray(3);tile.fuel=ItemStack.CreateArray(3);tile.output=ItemStack.CreateArray(6);return tile;}
static string State(TileEntityWorkstation t)=>string.Join("|",t.input.Select(s=>$"{s.count}:{s.itemValue.type}:{s.itemValue.Seed}:{s.itemValue.Data}"))+";"+string.Join("|",t.lastInput.Select(s=>$"{s.count}:{s.itemValue.type}:{s.itemValue.Data}"))+";"+string.Join(",",t.currentMeltTimesLeft);
static string Drops()=>string.Join("|",GameManager.Instance.Dropped.Select(s=>$"{s.count}:{s.itemValue.type}:{s.itemValue.Seed}:{s.itemValue.Data}"));
static void Processing(TileEntityWorkstation t,float dt){if(t is MappedReviewTile mapped)mapped.HandleMaterialInput(dt);else t.HandleMaterialInput(dt);}
public static string Run(){Registry();
var legacy=Fill(new TileEntityWorkstation(new Chunk()),3);var mapped=Fill(new MappedReviewTile(new Chunk()){Proof=true,Physical=9,ExpectedNames=new[]{"iron","lead"}},3);
Check(RebirthPlainStationNativeMigrationCandidate.TryExpandProvenMappedInput(true,3,legacy.materialNames,legacy.materialNames,mapped.input,mapped.lastInput,mapped.currentMeltTimesLeft,out var input,out var previous,out var timers),"mapped3to9 prepared under fixture proof");mapped.input=input;mapped.lastInput=previous;mapped.currentMeltTimesLeft=timers;var unit0=input[9];var unit1=input[10];var oldPrevious=previous;var oldTimers=timers;mapped.OnSetLocalChunkPosition();Check(ReferenceEquals(mapped.input,input)&&ReferenceEquals(mapped.input[9],unit0)&&ReferenceEquals(mapped.input[10],unit1)&&ReferenceEquals(mapped.lastInput,oldPrevious)&&ReferenceEquals(mapped.currentMeltTimesLeft,oldTimers)&&mapped.input[9].itemValue.Data=="unit iron metadata"&&mapped.input[10].itemValue.Seed==322,"paired setup keeps accepted unit references metadata all arrays");Check(mapped.materialNames.SequenceEqual(new[]{"iron","lead"})&&mapped.isModuleUsed[4]&&mapped.isModuleUsed[1],"native ordered mapping/module setup retained");
var nativeThree=Fill(new TileEntityWorkstation(new Chunk()),3);var reviewedThree=Fill(new MappedReviewTile(new Chunk()){Proof=true,Physical=3,ExpectedNames=new[]{"iron","lead"}},3);nativeThree.OnSetLocalChunkPosition();reviewedThree.OnSetLocalChunkPosition();int nativeEvents=0,reviewEvents=0;nativeThree.InputChanged+=()=>nativeEvents++;reviewedThree.InputChanged+=()=>reviewEvents++;
foreach(float step in new[]{0f,.5f,3.5f}){Processing(nativeThree,step);Processing(reviewedThree,step);Check(State(nativeThree)==State(reviewedThree)&&nativeEvents==reviewEvents,"review physical3 native count/timer/event differential");}
var nine=Fill(new MappedReviewTile(new Chunk()){Proof=true,Physical=9,ExpectedNames=new[]{"iron","lead"}},9);nine.input[3]=new ItemStack(new ItemValue(601){Seed=113,Data="ingredient cell three"},4);nine.lastInput[3]=nine.input[3].Clone();nine.currentMeltTimesLeft[3]=.25f;int events=0;nine.InputChanged+=()=>events++;nine.OnSetLocalChunkPosition();Processing(nine,.5f);Check(nine.input[9].count==9&&nine.input[10].count==10&&nine.input[3].count==3&&nine.input[3].itemValue.type==601,"processing credits9plusj instead of ingredient3");Check(nine.currentMeltTimesLeft[0]==.75f&&nine.currentMeltTimesLeft[3]==.75f&&events==9,"nine native arithmetic countdown clear/emission events");Check(nine.input[9].itemValue.Seed==321&&nine.input[9].itemValue.Data=="unit iron metadata","processing retains existing credited unit metadata");
// Compare destruction logical prefix + native material suffix after equivalent processing.
var legacyDrop=Fill(new TileEntityWorkstation(new Chunk()),3);var mappedDrop=Fill(new MappedReviewTile(new Chunk()){Proof=true,Physical=9,ExpectedNames=new[]{"iron","lead"}},9);Processing(legacyDrop,.5f);Processing(mappedDrop,.5f);GameManager.Instance=new GameManager();legacyDrop.ReplacedBy(new BlockValue(),new BlockValue(),new TileBase(new Chunk()));var nativeDrops=Drops();GameManager.Instance=new GameManager();mappedDrop.ReplacedBy(new BlockValue(),new BlockValue(),new TileBase(new Chunk()));Check(Drops()==nativeDrops&&GameManager.Instance.Drops==1,"mapped nine physical/suffix destruction equals native material conversion/order single drop");
GameManager.Instance=new GameManager();nine.ReplacedBy(new BlockValue(),new BlockValue(),new TileBase(new Chunk()));Check(GameManager.Instance.Drops==1&&GameManager.Instance.Dropped.Contains(nine.input[3])&&GameManager.Instance.Dropped.Any(s=>s.itemValue.type==701)&&GameManager.Instance.Dropped.Any(s=>s.itemValue.type==702),"extra physical3 and suffix conversions included once");
foreach(bool reordered in new[]{false,true}){var refused=Fill(new MappedReviewTile(new Chunk()){Proof=reordered,Physical=9,ExpectedNames=reordered?new[]{"lead","iron"}:new[]{"iron","lead"}},9);var before=State(refused);var originalInput=refused.input;var originalNames=refused.materialNames;refused.localChunkPos=new Vector3i(33,34,35);Check(ReferenceEquals(refused.input,originalInput)&&ReferenceEquals(refused.materialNames,originalNames)&&State(refused)==before,"setup unknown/reordered refuses before array/material mutation");Check(refused.chunkPos==new Vector3i(33,34,35),"actual native setter position already changed before refusing setup gate");Processing(refused,10);Check(State(refused)==before,"processing unknown/reordered gate prevents counts/timer/events writes");GameManager.Instance=new GameManager();refused.ReplacedBy(new BlockValue(),new BlockValue(),new TileBase(new Chunk()));Check(GameManager.Instance.Drops==0&&State(refused)==before,"destruction refused leaves removed custody recovery unresolved not conservation");}
var smelterOff=Fill(new MappedReviewTile(new Chunk()){Proof=true,Physical=9,ExpectedNames=new[]{"iron","lead"}},9);string off=State(smelterOff);XUiM_Recipes.DisableSmelter=true;Processing(smelterOff,10);XUiM_Recipes.DisableSmelter=false;Check(State(smelterOff)==off,"native DisableSmelter early gate preserved");
return "PASS "+n+" changed paired setup/material processing/mapped destruction native-body checks; owner gates and item/world/tool effects adapted, no production authority";
}
}
}