using System;using System.IO;using System.Linq;
namespace NativeLifecycle {
public static class MappedRemoteChecks {
static int n;static void Check(bool b,string s){if(!b)throw new Exception(s);n++;}
static ItemStack[] Payload(int cells,int marker)=>Enumerable.Range(0,cells).Select(i=>new ItemStack(new ItemValue(marker+i){Seed=(ushort)(marker+i),Data="mapped payload"+(marker+i)},marker+i)).ToArray();
static string[] Names(int m)=>Enumerable.Range(0,m).Select(i=>"material"+i).ToArray();
static MappedReviewTile Tile(int m){var names=Names(m);var tile=new MappedReviewTile(new Chunk()){Proof=true,Physical=9,ExpectedNames=(string[])names.Clone(),materialNames=(string[])names.Clone(),chunkPos=new Vector3i(5,6,7),input=Payload(9+m,91),lastInput=Payload(9,81),currentMeltTimesLeft=Enumerable.Repeat(77f,9).ToArray(),fuel=Payload(3,71),toolsNet=Payload(3,61),output=Payload(6,51),lockHandleWaitingFor=17,lastTickTime=123,isBurning=true,currentBurnTimeLeft=99,isPlayerPlaced=true};tile.chunk.Value.Block.Properties.Materials=m==0?null:string.Join(",",names);return tile;}
static byte[] Frame(int m,bool remote,int inputCount=-1,int previous=9,int timerCount=9){var tile=Tile(m);tile.input=Payload(inputCount<0?9+m:inputCount,11);tile.lastInput=Payload(previous,21);tile.currentMeltTimesLeft=Enumerable.Range(0,timerCount).Select(i=>i+.5f).ToArray();using var stream=new MemoryStream();tile.write(new PooledBinaryWriter(stream),remote?StreamModeWrite.ToClient:StreamModeWrite.ToServer);return stream.ToArray();}
static bool Tail(PooledBinaryReader reader,int full,int previous,int timers){for(int i=0;i<full;i++)new ItemStack().Read(reader);for(int array=0;array<2;array++){int count=reader.ReadByte();for(int i=0;i<count;i++)new ItemStack().Read(reader);}reader.ReadBoolean();reader.ReadSingle();int timerCount=reader.ReadByte();for(int i=0;i<timerCount;i++)reader.ReadSingle();reader.ReadBoolean();reader.ReadUInt64();int lastCount=reader.ReadByte();for(int i=0;i<lastCount;i++)new ItemStack().Read(reader);return timerCount==timers&&lastCount==previous;}
static bool Dispatch(NetPackageTileEntity package,World world,string[] names,bool proof,out bool downgrade,bool ownerAbi=true,Func<PooledBinaryReader,bool> header=null,Func<PooledBinaryReader,int,int,int,bool> tail=null){var tile=(MappedReviewTile)world.Tile;long position=package.ms.Position;bool valid;using(var reader=new PooledBinaryReader(package.ms)){package.ms.Position=0;try{valid=RebirthPlainStationRemoteFrameGuardCandidate.TryPreflightMappedBeforeLiveRead(reader,world.Remote?StreamModeRead.FromServer:StreamModeRead.FromClient,proof,names,ownerAbi,tile.input.Length,tile.lastInput.Length,tile.currentMeltTimesLeft.Length,true,header??(r=>RebirthPlainStationRemoteFrameGuardCandidate.TryReadCurrentRemoteBaseHeader(r,tile.chunkPos)),tail??Tail,out downgrade);}finally{package.ms.Position=position;}}if(!valid)return false;package.ProcessPackage(world,new GameManager());return true;}
static string Arrays(ItemStack[] a)=>string.Join("|",a.Select(s=>$"{s.count}:{s.itemValue.type}:{s.itemValue.Seed}:{s.itemValue.Data}"));
static string State(MappedReviewTile t)=>$"{t.chunkPos.x},{t.chunkPos.y},{t.chunkPos.z};{t.lastTickTime};{t.lockHandleWaitingFor};{t.isBurning};{t.currentBurnTimeLeft};{t.isPlayerPlaced};{t.Notifications};{t.Modified};"+Arrays(t.input)+Arrays(t.lastInput)+Arrays(t.fuel)+Arrays(t.toolsNet)+Arrays(t.output)+string.Join(",",t.currentMeltTimesLeft)+string.Join("|",t.materialNames);
static NetPackageTileEntity Package(byte[] frame)=>new NetPackageTileEntity{ms=new MemoryStream(frame),teBlockId=17};
public static string Run(){
foreach(int m in new[]{0,1,2,246})foreach(bool remote in new[]{false,true})foreach(bool accessed in new[]{false,true})foreach(bool waiting in new[]{false,true}){
var tile=Tile(m);tile.bUserAccessing=accessed;tile.bWaitingForServerResponse=waiting;var world=new World{Tile=tile,Remote=remote};var packet=Package(Frame(m,remote));SingletonMonoBehaviour<ConnectionManager>.Instance=new ConnectionManager{IsServer=!remote};Check(Dispatch(packet,world,Names(m),true,out var downgrade)&&!downgrade,"mapped full9plusM fixture frame accepted");Check(tile.input.Length==9+m&&tile.lastInput.Length==9&&tile.currentMeltTimesLeft.Length==9&&tile.materialNames.SequenceEqual(Names(m)),"accepted mapped frame retains exact aligned arrays/material order with reviewed setup");Check(tile.input[^1].itemValue.Data=="mapped payload"+((accessed?91:11)+9+m-1)&&tile.lockHandleWaitingFor==byte.MaxValue&&tile.Notifications==1&&SingletonMonoBehaviour<ConnectionManager>.Instance.Broadcasts==(remote?0:1),"accepted accessed/waiting native apply-discard and outer transport");
Check(tile.currentMeltTimesLeft[0]==(remote&&accessed?77f:.5f)&&tile.lastInput[8].itemValue.Data=="mapped payload"+((accessed?81:21)+8),"accepted native mode-specific timers and previous apply-discard");foreach(int mismatch in new[]{0,1,2,3}){tile=Tile(m);tile.bUserAccessing=accessed;tile.bWaitingForServerResponse=waiting;world.Tile=tile;packet=Package(Frame(m,remote,mismatch==0?3+m:mismatch==3?8+m:9+m,mismatch==1?3:9,mismatch==2?3:9));packet.ms.Position=1;var before=State(tile);var input=tile.input;var previous=tile.lastInput;var timer=tile.currentMeltTimesLeft;var suffix=m>0?tile.input[9]:null;SingletonMonoBehaviour<ConnectionManager>.Instance=new ConnectionManager{IsServer=!remote};Check(!Dispatch(packet,world,Names(m),true,out downgrade)&&downgrade==(mismatch==0),"mapped input3plusM flags downgrade and other shape refusal");Check(State(tile)==before&&ReferenceEquals(tile.input,input)&&ReferenceEquals(tile.lastInput,previous)&&ReferenceEquals(tile.currentMeltTimesLeft,timer)&&(m==0||ReferenceEquals(tile.input[9],suffix)),"refusal before mapped live arrays/base mutation");Check(tile.lockHandleWaitingFor==17&&tile.Notifications==0&&tile.Modified==0&&SingletonMonoBehaviour<ConnectionManager>.Instance.Broadcasts==0&&packet.ms.Position==1,"refusal preserves waiting handle reader notification broadcast");}
}
foreach(string reason in new[]{"unknown","ownerAbi","nullnames","duplicate","alias","trim","headerMutation","tailMutation","malformed","extra"}){var names=Names(2);var tile=Tile(2);var world=new World{Tile=tile};byte[] frame=Frame(2,false);if(reason=="duplicate")names[1]=names[0];if(reason=="alias")names[1]=names[0].ToUpperInvariant();if(reason=="trim")names[0]=" material0 ";if(reason=="malformed")frame=frame.Take(frame.Length-1).ToArray();if(reason=="extra")frame=frame.Concat(new byte[]{1}).ToArray();var packet=Package(frame);packet.ms.Position=2;var before=State(tile);Func<PooledBinaryReader,bool> header=reason=="headerMutation"?r=>{names[0]="header mutated";return RebirthPlainStationRemoteFrameGuardCandidate.TryReadCurrentRemoteBaseHeader(r,tile.chunkPos);}:null;Func<PooledBinaryReader,int,int,int,bool> tail=reason=="tailMutation"?(r,f,p,t)=>{bool valid=Tail(r,f,p,t);names[0]="tail mutated";return valid;}:null;SingletonMonoBehaviour<ConnectionManager>.Instance=new ConnectionManager{IsServer=true};Check(!Dispatch(packet,world,reason=="nullnames"?null:names,reason!="unknown",out _,reason!="ownerAbi",header,tail),"mapped "+reason+" refuses");Check(State(tile)==before&&packet.ms.Position==2&&tile.lockHandleWaitingFor==17&&SingletonMonoBehaviour<ConnectionManager>.Instance.Broadcasts==0,"mapped "+reason+" no live mutation or reader movement");}
using(var reader=new PooledBinaryReader(new MemoryStream(Frame(0,false)))){reader.BaseStream.Position=1;int callbacks=0;Check(!RebirthPlainStationRemoteFrameGuardCandidate.TryPreflightMappedBeforeLiveRead(reader,StreamModeRead.FromClient,true,Names(247),true,256,9,9,true,r=>{callbacks++;return true;},(r,f,p,t)=>{callbacks++;return true;},out _)&&callbacks==0&&reader.BaseStream.Position==1,"247 witness refused before clone/parsing sourcepreflight");}
return "PASS "+n+" changed mapped remote-guard full-shape/name-freeze/transport checks; accepted frames use reviewed OnSet + timer adapter and partial codec, no vanilla/native ABI claim";
}
}
}