using System;using System.Linq;using System.Collections.Generic;
namespace NativeCloneBoundary {
public static class CopyChecks {
static int n;static void Check(bool b,string name){if(!b)throw new Exception(name);n++;}
static ItemValue Value(ushort seed){return new ItemValue(){type=0,Meta=38,UseTimes=-0.25f,Quality=4,SelectedAmmoTypeIndex=3,Flags=7,Seed=seed,TextureFullArray=new TextureFullArray{Bits=unchecked((long)0xF0E1D2C3B4A59687)},Stats=new[]{new ItemValue.Stat{type=3,isBoosted=true,value=-321}},Metadata=new Dictionary<string,TypedMetadataValue>(StringComparer.OrdinalIgnoreCase){{"float",new TypedMetadataValue(float.NaN,TypedMetadataValue.TypeTag.Float)},{"integer",new TypedMetadataValue(-7,TypedMetadataValue.TypeTag.Integer)},{"text",new TypedMetadataValue("custody",TypedMetadataValue.TypeTag.String)},{"null",null}}};}
static bool Expand(ItemStack[] input,ItemStack[] previous,out ItemStack[] next,out ItemStack[] last,out float[] timers)=>RebirthPlainStationNativeMigrationCandidate.TryExpandProvenPlainInput(true,input.Length,Array.Empty<string>(),Array.Empty<string>(),input,previous,new float[input.Length],out next,out last,out timers);
static void SetContainer(ItemValue v,int kind,int size){switch(kind){case 0:v.Stats=new ItemValue.Stat[size];break;case 1:v.modifications=new ItemValue[size];break;case 2:v.cosmeticMods=new ItemValue[size];break;case 3:v.Metadata=new Dictionary<string,TypedMetadataValue>(StringComparer.OrdinalIgnoreCase);for(int i=0;i<size;i++)v.Metadata["key"+i]=null;break;}}
static object Container(ItemValue v,int kind)=>kind==0?(object)v.Stats:kind==1?v.modifications:kind==2?v.cosmeticMods:v.Metadata;
static int ContainerCount(ItemValue v,int kind)=>kind==0?v.Stats.Length:kind==1?v.modifications.Length:kind==2?v.cosmeticMods.Length:v.Metadata.Count;
static void BoundsChecks(){
foreach(int cells in new[]{3,9})foreach(int kind in new[]{0,1,2,3}){
var input=ItemStack.CreateArray(cells);var previous=ItemStack.CreateArray(cells);var source=Value(121);SetContainer(source,kind,255);input[0]=new ItemStack(source,0);object before=Container(source,kind);int beforeCalls=ItemValue.NonemptyConstructorCalls;
Check(Expand(input,previous,out var next,out var last,out var timers),"byte count255 representable accepted");Check(ContainerCount(next[0].itemValue,kind)==255&&!ReferenceEquals(Container(next[0].itemValue,kind),before),"accepted255 count detached incl all-null arrays");Check(source.Seed==121&&ReferenceEquals(Container(source,kind),before)&&ContainerCount(source,kind)==255&&ItemValue.NonemptyConstructorCalls==beforeCalls,"accepted255 source and constructor unchanged");
SetContainer(source,kind,256);before=Container(source,kind);Check(!Expand(input,previous,out next,out last,out timers)&&next==null&&last==null&&timers==null,"256 refuses no partial output");Check(source.Seed==121&&ReferenceEquals(Container(source,kind),before)&&ContainerCount(source,kind)==256&&ItemValue.NonemptyConstructorCalls==beforeCalls,"256 all-null oversized container source unchanged");
var nested=Value(122);SetContainer(nested,kind,256);previous[cells-1]=new ItemStack(Value(123),0);previous[cells-1].itemValue.modifications=new[]{nested};SetContainer(source,kind,1);Check(!Expand(input,previous,out next,out last,out timers)&&next==null&&last==null&&timers==null,"late nested256 refusal no output");Check(source.Seed==121&&previous[cells-1].itemValue.Seed==123&&nested.Seed==122&&ContainerCount(nested,kind)==256&&ItemValue.NonemptyConstructorCalls==beforeCalls,"late nested oversized source unchanged");
}
foreach(int cells in new[]{3,9}){
var input=ItemStack.CreateArray(cells);var previous=ItemStack.CreateArray(cells);var leaf=Value(501);var root=Value(502);root.modifications=new ItemValue[17];for(int i=0;i<17;i++){root.modifications[i]=Value((ushort)(503+i));root.modifications[i].modifications=Enumerable.Repeat(leaf,i==16?238:240).ToArray();}input[cells-1]=new ItemStack(root,0);int beforeCalls=ItemValue.NonemptyConstructorCalls;
Check(1+root.modifications.Sum(v=>1+v.modifications.Length)==4096&&root.modifications.All(v=>v.modifications.Length<=255),"exact4096 source graph each container representable");Check(Expand(input,previous,out var next,out var last,out var timers),"exact4096 copied-value node budget accepted");Check(next[cells-1].itemValue.modifications.Length==17&&!ReferenceEquals(next[cells-1].itemValue.modifications[0].modifications[0],leaf)&&root.Seed==502&&leaf.Seed==501,"4096 graph detached source unchanged");
var finalGroup=root.modifications[16];finalGroup.modifications=Enumerable.Repeat(leaf,239).ToArray();Check(1+root.modifications.Sum(v=>1+v.modifications.Length)==4097&&root.modifications.Length<=255&&root.modifications.All(v=>v.modifications.Length<=255),"4097 graph still representable percontainer and shallow");Check(!Expand(input,previous,out next,out last,out timers)&&next==null&&last==null&&timers==null,"true4097 node budget refusal no output");Check(root.Seed==502&&leaf.Seed==501&&finalGroup.Seed==519&&finalGroup.modifications.All(v=>ReferenceEquals(v,leaf))&&ItemValue.NonemptyConstructorCalls==beforeCalls,"true node-budget refusal source/constructor unchanged");
}
}
static bool SamePayload(ItemValue source,ItemValue copy){if(source==null||copy==null)return source==copy;return source.type==copy.type&&source.Meta==copy.Meta&&source.UseTimes==copy.UseTimes&&source.Quality==copy.Quality&&source.SelectedAmmoTypeIndex==copy.SelectedAmmoTypeIndex&&source.Flags==copy.Flags&&source.Seed==copy.Seed&&source.TextureFullArray.Bits==copy.TextureFullArray.Bits&&source.Stats.SequenceEqual(copy.Stats)&&source.Metadata.Count==copy.Metadata.Count&&source.Metadata.All(e=>copy.Metadata.ContainsKey(e.Key)&&(e.Value==null?copy.Metadata[e.Key]==null:Equals(e.Value.GetValue(),copy.Metadata[e.Key].GetValue())));}
static ItemStack[] MappedStacks(int size,int start)=>Enumerable.Range(0,size).Select(i=>new ItemStack(Value((ushort)(start+i)),i%2==0?0:i+1)).ToArray();
static void MappedChecks(){
foreach(int physical in new[]{3,9})foreach(int materials in new[]{0,1,2,246}){
var names=Enumerable.Range(0,materials).Select(i=>"material"+i).ToArray();var input=MappedStacks(physical+materials,1000);var previous=MappedStacks(physical,2000);var time=Enumerable.Range(0,physical).Select(i=>i-0.75f).ToArray();int beforeCalls=ItemValue.NonemptyConstructorCalls;
Check(RebirthPlainStationNativeMigrationCandidate.TryExpandProvenMappedInput(true,physical,names,names,input,previous,time,out var next,out var last,out var timers),"ordered mapped physical3or9 plus suffix accepted");Check(next.Length==9+materials&&next.Length<=255&&last.Length==9&&timers.Length==9,"mapped arrays exact physicalnine plus ordered suffix");
for(int i=0;i<physical;i++)Check(SamePayload(input[i].itemValue,next[i].itemValue)&&SamePayload(previous[i].itemValue,last[i].itemValue)&&next[i].count==input[i].count&&last[i].count==previous[i].count&&timers[i]==time[i]&&!ReferenceEquals(next[i].itemValue,input[i].itemValue),"mapped prefix previous timer full empty metadata preserved");
for(int i=physical;i<9;i++)Check(next[i].count==0&&last[i].count==0&&timers[i]==0,"new physical cells empty no suffix overlap");
for(int j=0;j<materials;j++){Check(SamePayload(input[physical+j].itemValue,next[9+j].itemValue)&&input[physical+j].count==next[9+j].count&&!ReferenceEquals(input[physical+j].itemValue,next[9+j].itemValue)&&!ReferenceEquals(input[physical+j].itemValue.Metadata,next[9+j].itemValue.Metadata),"every ordered suffix full seededempty payload at9plusj");next[9+j].itemValue.Seed=0;Check(input[physical+j].itemValue.Seed==1000+physical+j,"suffix copy mutation detached");}
Check(ItemValue.NonemptyConstructorCalls==beforeCalls&&previous[^1].itemValue.Seed==2000+physical-1,"mapped source constructor and previous metadata unchanged");
}
foreach(int physical in new[]{3,9})foreach(string failure in new[]{"unknown","reorder","changed","duplicate","alias","nullname","blankname","trimname","materialcount","inputcount","previouscount","timercount","physical","nullslot","negative","nan","latepayload","over247"}){
int materials=failure=="over247"?247:2;var prior=Enumerable.Range(0,materials).Select(i=>"material"+i).ToArray();var current=prior.ToArray();var input=MappedStacks(physical+materials,1000);var previous=MappedStacks(physical,2000);var timers=new float[physical];int suppliedPhysical=physical;bool proof=failure!="unknown";
switch(failure){case "reorder":Array.Reverse(current);break;case "changed":current[1]="different";break;case "duplicate":prior[1]=prior[0];current[1]=current[0];break;case "alias":prior[1]=prior[0].ToUpperInvariant();current[1]=prior[1];break;case "nullname":prior[0]=null;current[0]=null;break;case "blankname":prior[0]=" ";current[0]=" ";break;case "trimname":prior[0]=" material0 ";current[0]=" material0 ";break;case "materialcount":current=current.Take(1).ToArray();break;case "inputcount":input=input.Concat(new[]{new ItemStack(Value(777),0)}).ToArray();break;case "previouscount":previous=previous.Concat(new[]{new ItemStack(Value(778),0)}).ToArray();break;case "timercount":timers=new float[physical+1];break;case "physical":suppliedPhysical=6;break;case "nullslot":input[^1]=null;break;case "negative":input[^1].count=-1;break;case "nan":timers[^1]=float.NaN;break;case "latepayload":input[^1].itemValue.Metadata["unsupported"]=new TypedMetadataValue(new object(),TypedMetadataValue.TypeTag.None);break;}
var sourceInput=input;var sourcePrevious=previous;var sourceTimers=timers;var sourceSuffix=input[^1];var suffixSeed=sourceSuffix?.itemValue.Seed;var suffixMetadata=sourceSuffix?.itemValue.Metadata;int beforeCalls=ItemValue.NonemptyConstructorCalls;
Check(!RebirthPlainStationNativeMigrationCandidate.TryExpandProvenMappedInput(proof,suppliedPhysical,prior,current,input,previous,timers,out var next,out var last,out var time)&&next==null&&last==null&&time==null,"mapped refusal "+failure+" no partial output");Check(ReferenceEquals(input,sourceInput)&&ReferenceEquals(previous,sourcePrevious)&&ReferenceEquals(timers,sourceTimers)&&ReferenceEquals(input[^1],sourceSuffix)&&input[^1]?.itemValue.Seed==suffixSeed&&ReferenceEquals(input[^1]?.itemValue.Metadata,suffixMetadata)&&previous[0].itemValue.Seed==2000&&ItemValue.NonemptyConstructorCalls==beforeCalls,"mapped refusal "+failure+" source graph/ctor unchanged");
}
}
public static string Run(){
for(int cells=3;cells<=9;cells+=6){var input=ItemStack.CreateArray(cells);var previous=ItemStack.CreateArray(cells);input[0]=new ItemStack(Value(123),0);previous[1]=new ItemStack(Value(456),0);var nested=Value(789);input[0].itemValue.modifications=new[]{nested,null};input[0].itemValue.cosmeticMods=new[]{Value(876)};nested.modifications=Array.Empty<ItemValue>();nested.cosmeticMods=null;int beforeCalls=ItemValue.NonemptyConstructorCalls;
Check(Expand(input,previous,out var next,out var last,out var times),"empty/full field copy accepted");var source=input[0].itemValue;var copy=next[0].itemValue;Check(source.Seed==123&&previous[1].itemValue.Seed==456&&nested.Seed==789&&source.cosmeticMods[0].Seed==876,"source empty/nested seeds unchanged");Check(copy.Seed==123&&last[1].itemValue.Seed==456&&copy.modifications[0].Seed==789&&copy.cosmeticMods[0].Seed==876,"copied empty/nested seeds exact");Check(copy.type==source.type&&copy.Meta==source.Meta&&copy.UseTimes==source.UseTimes&&copy.Quality==source.Quality&&copy.SelectedAmmoTypeIndex==source.SelectedAmmoTypeIndex&&copy.Flags==source.Flags&&copy.TextureFullArray.Bits==source.TextureFullArray.Bits,"all captured native payload fields exact");Check(copy.Stats[0].type==3&&copy.Stats[0].isBoosted&&copy.Stats[0].value==-321&&!ReferenceEquals(source.Stats,copy.Stats),"native value-stat array detached");Check(copy.Metadata.Count==4&&copy.Metadata.ContainsKey("TEXT")&&copy.Metadata.Comparer==source.Metadata.Comparer&&copy.Metadata["null"]==null&&float.IsNaN((float)copy.Metadata["float"].GetValue()),"metadata comparer null NaN retained");Check(!ReferenceEquals(copy.Metadata,source.Metadata)&&!ReferenceEquals(copy.Metadata["text"],source.Metadata["text"]),"metadata graph detached");Check(copy.modifications[1]==null&&copy.modifications[0].modifications.Length==0&&copy.modifications[0].cosmeticMods==null,"null and empty nested arrays distinct retained");Check(!ReferenceEquals(copy.modifications,source.modifications)&&!ReferenceEquals(copy.modifications[0],nested)&&!ReferenceEquals(copy.cosmeticMods[0],source.cosmeticMods[0]),"nested empty item graph detached");
copy.Stats[0].value=42;copy.Metadata["text"].value="changed";copy.modifications[0].Seed=0;copy.TextureFullArray=new TextureFullArray{Bits=0};Check(source.Stats[0].value==-321&&(string)source.Metadata["text"].GetValue()=="custody"&&nested.Seed==789&&source.TextureFullArray.Bits!=0,"copy mutation cannot reach source");Check(ItemValue.NonemptyConstructorCalls==beforeCalls,"no nonempty constructor/time/random path");
var cycle=Value(911);cycle.modifications=new[]{cycle};input[cells-1]=new ItemStack(cycle,0);Check(!Expand(input,previous,out var refused,out var refusedLast,out var refusedTimes)&&refused==null&&refusedLast==null&&refusedTimes==null,"cycle refuses without partial output");Check(cycle.Seed==911&&ReferenceEquals(cycle.modifications[0],cycle)&&source.Seed==123&&previous[1].itemValue.Seed==456,"cycle late failure source unchanged");
var chain=Value(101);var nodes=new List<ItemValue>{chain};for(int i=0;i<34;i++){var child=Value((ushort)(102+i));nodes[^1].cosmeticMods=new[]{child};nodes.Add(child);}input[cells-1]=new ItemStack(chain,0);Check(!Expand(input,previous,out refused,out refusedLast,out refusedTimes)&&refused==null&&refusedLast==null&&refusedTimes==null,"depth refuses without partial output");Check(nodes.Select((v,i)=>v.Seed==(ushort)(101+i)).All(v=>v),"deep failure original seeds unchanged");
input[cells-1]=new ItemStack(Value(615),0);previous[cells-1]=new ItemStack(Value(616),0);var unsupported=new object();previous[cells-1].itemValue.Metadata["unsupported"]=new TypedMetadataValue(unsupported,TypedMetadataValue.TypeTag.None);Check(!Expand(input,previous,out refused,out refusedLast,out refusedTimes)&&refused==null&&refusedLast==null&&refusedTimes==null,"unsupported metadata late failure no output");Check(previous[cells-1].itemValue.Seed==616&&ReferenceEquals(previous[cells-1].itemValue.Metadata["unsupported"].GetValue(),unsupported)&&input[cells-1].itemValue.Seed==615,"unsupported payload custody unchanged");
var shared=Value(999);var dag=Value(998);dag.modifications=Enumerable.Repeat(shared,4097).ToArray();input[cells-1]=new ItemStack(dag,0);previous[cells-1]=ItemStack.CreateArray(1)[0];Check(!Expand(input,previous,out refused,out refusedLast,out refusedTimes)&&refused==null&&refusedLast==null&&refusedTimes==null,"flat4097 container refuses byte-count bound");Check(dag.Seed==998&&shared.Seed==999&&dag.modifications.All(v=>ReferenceEquals(v,shared)),"flat oversized container source unchanged");Check(ItemValue.NonemptyConstructorCalls==beforeCalls,"no random constructor on refusal");
}
BoundsChecks();MappedChecks();return "PASS "+n+" changed-candidate adversarial empty/nested/metadata/stat/depth/cycle/DAG checks; native fields and scalar constructors adapted, no runtime hook";
}
}
}