using System;
using System.IO;
using System.Linq;
namespace NativeLifecycle {
public enum StreamModeRead { Persistency, FromClient, FromServer }
public enum StreamModeWrite { Persistency, ToServer, ToClient }
public enum Module { Tools, Input, Output, Fuel, MaterialInput }
public class PooledBinaryReader:BinaryReader {BinaryReader inner;public PooledBinaryReader():this(new MemoryStream()){}public PooledBinaryReader(Stream s):base(s,System.Text.Encoding.UTF8,true){inner=new BinaryReader(s,System.Text.Encoding.UTF8,true);}public void SetBaseStream(Stream s){inner=new BinaryReader(s,System.Text.Encoding.UTF8,true);}public override Stream BaseStream=>inner.BaseStream;public override byte ReadByte()=>inner.ReadByte();public override ushort ReadUInt16()=>inner.ReadUInt16();public override int ReadInt32()=>inner.ReadInt32();public override ulong ReadUInt64()=>inner.ReadUInt64();public override float ReadSingle()=>inner.ReadSingle();public override bool ReadBoolean()=>inner.ReadBoolean();public override string ReadString()=>inner.ReadString();}
public class PooledBinaryWriter:BinaryWriter { public PooledBinaryWriter(Stream s):base(s,System.Text.Encoding.UTF8,true){} }
public class TypedMetadataValue {public object value;public TypedMetadataValue(object v){value=v;}public object GetValue()=>value;public TypedMetadataValue Clone()=>new TypedMetadataValue(value);}
public struct TextureFullArray {public long Bits;}
public class ItemValue {public struct Stat {public int type;public bool isBoosted;public short value;}public int type,Meta;public float UseTimes;public ushort Quality,Seed;public byte SelectedAmmoTypeIndex,Flags;public Stat[] Stats;public ItemValue[] modifications,cosmeticMods;public System.Collections.Generic.Dictionary<string,TypedMetadataValue> Metadata;public TextureFullArray TextureFullArray;public string Data{get=>Metadata!=null&&Metadata.TryGetValue("fixture",out var v)?(string)v.GetValue():"";set{Metadata??=new System.Collections.Generic.Dictionary<string,TypedMetadataValue>();Metadata["fixture"]=new TypedMetadataValue(value);}}public ItemValue(){}public ItemValue(int t){type=t;}public ItemClass ItemClass=>ItemClass.Find(type);public void ModifyValue(object a,object b,PassiveEffects e,ref float original,ref float percent,FastTags<TagGroup.Global> tags){ToolEffects.Calls++;original*=ToolEffects.Multiplier;}public ItemValue Clone()=>new ItemValue(type){Data=Data};}
public class ItemStack {public ItemValue itemValue;public int count;public ItemStack(){itemValue=new ItemValue();}public ItemStack(ItemValue v,int n){itemValue=v;count=n;}public static ItemStack Empty=>new ItemStack(new ItemValue(),0);public void Clear(){count=0;itemValue.type=0;itemValue.Seed=0;itemValue.Metadata=null;}public bool IsEmpty(){if(count>=1)return itemValue.type==0;return true;}public ItemStack Clone()=>new ItemStack(itemValue.Clone(),count);public static ItemStack[] CreateArray(int n)=>Enumerable.Range(0,n).Select(_=>Empty).ToArray();public static ItemStack[] Clone(ItemStack[] a)=>a.Select(x=>x.Clone()).ToArray();public void Read(BinaryReader r){itemValue=new ItemValue(r.ReadInt32()){Data=r.ReadString()};count=r.ReadInt32();}public void Write(BinaryWriter w){w.Write(itemValue.type);w.Write(itemValue.Data);w.Write(count);}}
public struct Vector3i {public int x,y,z;public Vector3i(int a,int b,int c){x=a;y=b;z=c;}public static Vector3i zero=>default;public static bool operator==(Vector3i a,Vector3i b)=>a.x==b.x&&a.y==b.y&&a.z==b.z;public static bool operator!=(Vector3i a,Vector3i b)=>!(a==b);public override bool Equals(object o)=>o is Vector3i v&&this==v;public override int GetHashCode()=>x^y^z;}
public class Properties {public string Materials,Modules;public bool Contains(string a,string b)=>b=="InputMaterials"?Materials!=null:b=="Modules"&&Modules!=null;public string GetString(string a,string b)=>b=="InputMaterials"?Materials:Modules;}
public class Block {public Properties Properties=new Properties();}
public class BlockValue {public int type=17;public Block Block=new Block();}
public class Chunk {public BlockValue Value=new BlockValue();public BlockValue GetBlock(int x,int y,int z)=>Value;}
public class World {public TileBase Tile;public bool Remote;public BlockValue Value=new BlockValue();public static int toBlockXZ(int x)=>x;public TileBase GetTileEntity(Vector3i p)=>Tile;public BlockValue GetBlock(Vector3i p)=>Value;public bool IsRemote()=>Remote;}
public static class EnumUtils {public static T Parse<T>(string s,bool _ignoreCase)=> (T)Enum.Parse(typeof(T),s,_ignoreCase);}
public class Material {public string ForgeCategory;}public class ItemClass {public int Id;public int MaxCount=2,Weight=1;public float MeltTimePerUnit=1f;public string Name;public int GetWeight()=>Weight;public static ItemClass GetForId(int id)=>Find(id);public Material MadeOfMaterial=new Material();public static System.Collections.Generic.Dictionary<string,ItemClass> Units=new System.Collections.Generic.Dictionary<string,ItemClass>();public static ItemClass GetItemClass(string n)=>Units.TryGetValue(n,out var unit)?unit:new ItemClass{Id=100+n.Length};public static ItemClass Find(int id)=>Units.Values.FirstOrDefault(x=>x.Id==id)??new ItemClass{Id=id,MaxCount=2};public string GetItemName()=>Name??"item"+Id;}
public class GameTimer {public static GameTimer Instance=new GameTimer();public ulong ticks=1000;}
public class RecipeQueueItem {}
public partial class TileBase {public Vector3i chunkPos=new Vector3i(1,0,0);public ushort readVersion;public ulong heapMapUpdateTime,heapMapLastTime;public byte lockHandleWaitingFor=byte.MaxValue;public int Notifications,Modified;public Chunk chunk;public bool bWaitingForServerResponse;public TileBase(Chunk c){chunk=c;}public virtual void OnSetLocalChunkPosition(){}public void NotifyListeners(){Notifications++;}public void SetChunkModified(){Modified++;}public Vector3 ToWorldCenterPos()=>new Vector3(1,1,1); }
// Native constructor/setup/read/write and stack-array framing are extracted by PrepareNativeLifecycle.ps1.
public partial class TileEntityWorkstation:TileBase {public Action InputChanged;public ItemStack[] fuel,tools,toolsNet=ItemStack.CreateArray(3),output,input,lastInput;public RecipeQueueItem[] queue;public string[] materialNames;public bool[] isModuleUsed;public float[] currentMeltTimesLeft;public ulong lastTickTime;public bool bUserAccessing,isBurning,isPlayerPlaced;public float currentBurnTimeLeft;public ItemStack[] Input{get=>input;set=>input=value;}public void readRecipeStackArray(PooledBinaryReader r,int v,ref RecipeQueueItem[] q){}public void readCraftCompleteData(PooledBinaryReader r,int v){}public void writeRecipeStackArray(PooledBinaryWriter w,int v){}public void writeCraftCompleteData(PooledBinaryWriter w,int v){}public void SetDataFromNet(){} }
public class XUiC_ItemInfoWindow{}
public class Xui {public T GetChildByType<T>() where T:new()=>new T();}
public class XUiC_ItemStack {public event Action SlotChangedEvent {add{} remove{}}public ItemStack ItemStack=ItemStack.Empty;public int SlotNumber,StackLocation;public XUiC_ItemInfoWindow InfoWindow;}
public partial class XUiC_ItemStackGrid {public Xui xui=new Xui();public XUiC_ItemStack[] itemControllers;public Action handleSlotChangedDelegate=()=>{};public int StackLocation;public XUiC_ItemStackGrid(int n){itemControllers=Enumerable.Range(0,n).Select(_=>new XUiC_ItemStack()).ToArray();} }
public partial class XUiC_WorkstationGrid:XUiC_ItemStackGrid {public XUiC_WorkstationGrid(int n):base(n){} }
public partial class XUiM_Workstation {public TileEntityWorkstation tileEntity;public XUiM_Workstation(TileEntityWorkstation t){tileEntity=t;} }
public static class NativeLifecycleFixture {
static int n;static void Check(bool b,string s){if(!b)throw new Exception(s);n++;}static ItemStack[] Payload(int count)=>Enumerable.Range(0,count).Select(i=>new ItemStack(new ItemValue(i+1){Data="metadata"+i},i+10)).ToArray();
public static string Run(){
foreach(int size in new[]{3,9})foreach(StreamModeWrite mode in Enum.GetValues<StreamModeWrite>()) {
var c=new Chunk();var src=new TileEntityWorkstation(c);src.input=Payload(size);src.lastInput=Payload(size);src.currentMeltTimesLeft=Enumerable.Range(0,size).Select(i=>i+0.25f).ToArray();src.lastTickTime=900;
using var ms=new MemoryStream();src.write(new PooledBinaryWriter(ms),mode);ms.Position=0;var target=new TileEntityWorkstation(c);Check(target.currentMeltTimesLeft.Length==3&&target.lastInput.Length==3,"native constructor is three");
var rm=mode==StreamModeWrite.Persistency?StreamModeRead.Persistency:mode==StreamModeWrite.ToServer?StreamModeRead.FromClient:StreamModeRead.FromServer;
if(size==9){bool threw=false;try{target.read(new PooledBinaryReader(ms),rm);}catch(IndexOutOfRangeException){threw=true;}Check(threw,"native nine timer read refuses fresh three capacity");ms.Position=0;target=new TileEntityWorkstation(c);target.currentMeltTimesLeft=new float[9];}
if(size==3||target.currentMeltTimesLeft.Length==9){target.read(new PooledBinaryReader(ms),rm);Check(target.input.Length==size&&target.lastInput.Length==size,"read native stack counts preserved");for(int i=0;i<size;i++)Check(target.input[i].itemValue.Data=="metadata"+i&&target.lastInput[i].count==i+10&&target.currentMeltTimesLeft[i]==i+0.25f,"timer and metadata payload preserved after prerequisite capacity");}
}
foreach(StreamModeWrite mode in Enum.GetValues<StreamModeWrite>()) {
var src=new TileEntityWorkstation(new Chunk());src.input=Payload(3);src.lastInput=Payload(3);src.currentMeltTimesLeft=new[]{1.25f,2.25f,3.25f};using var ms=new MemoryStream();src.write(new PooledBinaryWriter(ms),mode);ms.Position=0;
var target=new TileEntityWorkstation(new Chunk());target.input=Payload(9);target.lastInput=Payload(9);target.currentMeltTimesLeft=Enumerable.Repeat(77f,9).ToArray();target.bUserAccessing=true;
var rm=mode==StreamModeWrite.Persistency?StreamModeRead.Persistency:mode==StreamModeWrite.ToServer?StreamModeRead.FromClient:StreamModeRead.FromServer;target.read(new PooledBinaryReader(ms),rm);
Check(target.input.Length==3&&target.input.All(x=>x.count==0)&&target.lastInput.Length==3&&target.lastInput.All(x=>x.count==0),"native accessed shape mismatch resizes before payload discard");
Check(target.currentMeltTimesLeft[0]==(rm==StreamModeRead.FromClient?1.25f:77f)&&target.currentMeltTimesLeft[3]==77f,"native accessed timer branch and untouched capacity tail");
ms.Position=0;target=new TileEntityWorkstation(new Chunk());target.currentMeltTimesLeft=new float[9];target.read(new PooledBinaryReader(ms),rm);Check(target.input.Length==3&&target.lastInput.Length==3&&target.currentMeltTimesLeft.Length==9&&target.currentMeltTimesLeft[3]==0,"old three stream does not align preallocated nine arrays by itself");
}
foreach(int size in new[]{3,9})foreach(StreamModeWrite mode in Enum.GetValues<StreamModeWrite>()) {
var src=new TileEntityWorkstation(new Chunk());src.input=Payload(size);src.lastInput=Payload(size);src.currentMeltTimesLeft=Enumerable.Range(0,size).Select(i=>i+0.25f).ToArray();using var ms=new MemoryStream();src.write(new PooledBinaryWriter(ms),mode);ms.Position=0;var target=new CandidateTileEntityWorkstation(new Chunk());
var rm=mode==StreamModeWrite.Persistency?StreamModeRead.Persistency:mode==StreamModeWrite.ToServer?StreamModeRead.FromClient:StreamModeRead.FromServer;target.read(new PooledBinaryReader(ms),rm);Check(target.input.Length==size&&target.lastInput.Length==size&&target.currentMeltTimesLeft.Length==size,"candidate native stored read size");for(int i=0;i<size;i++)Check(target.currentMeltTimesLeft[i]==i+0.25f&&target.input[i].itemValue.Data=="metadata"+i&&target.lastInput[i].count==i+10,"candidate read full payload");
var original=target.input;Check(!RebirthPlainStationNativeMigrationCandidate.TryExpandProvenPlainInput(false,size,Array.Empty<string>(),Array.Empty<string>(),target.input,target.lastInput,target.currentMeltTimesLeft,out _,out _,out _)&&ReferenceEquals(original,target.input),"unproven refuses without publication");Check(RebirthPlainStationNativeMigrationCandidate.TryExpandProvenPlainInput(true,size,Array.Empty<string>(),Array.Empty<string>(),target.input,target.lastInput,target.currentMeltTimesLeft,out var nine,out var previous,out var timers),"fixture-proven plain conversion");Check(nine.Length==9&&previous.Length==9&&timers.Length==9,"all candidate arrays nine");for(int i=0;i<size;i++)Check(nine[i].itemValue.Data==target.input[i].itemValue.Data&&previous[i].count==target.lastInput[i].count&&timers[i]==target.currentMeltTimesLeft[i],"candidate index payload preserved under clone double");Check(!RebirthPlainStationNativeMigrationCandidate.TryExpandProvenPlainInput(true,size,new[]{"iron"},new[]{"iron"},target.input,target.lastInput,target.currentMeltTimesLeft,out _,out _,out _),"material candidate refused");var grid=new XUiC_WorkstationGrid(9);grid.SetSlots(nine);Check(grid.GetSlots().Length==9&&grid.GetSlots()[size-1].itemValue.Data==nine[size-1].itemValue.Data,"native nine UI roundtrip");
}
Console.WriteLine(MappedNativeChecks.Run());Console.WriteLine(ReplacedByChecks.Run());Console.WriteLine(RemoteGuardChecks.Run());Console.WriteLine(NativeCloneBoundary.CopyChecks.Run());Check(NativeCloneBoundary.Probe.Run(),"actual native clone baseline mutation and corrected candidate seed preservation");
foreach(int materialCount in new[]{1,2}){var names=Enumerable.Range(0,materialCount).Select(i=>"material"+i).ToArray();var chunk=new Chunk();chunk.Value.Block.Properties.Materials=string.Join(",",names);var mappedTile=new TileEntityWorkstation(chunk);mappedTile.input=Payload(3+materialCount);mappedTile.lastInput=Payload(3);mappedTile.currentMeltTimesLeft=new[]{1f,2f,3f};Check(RebirthPlainStationNativeMigrationCandidate.TryExpandProvenMappedInput(true,3,names,names,mappedTile.input,mappedTile.lastInput,mappedTile.currentMeltTimesLeft,out var mapped,out var prior,out var time),"mapped helper result prepared only under fixture proof");mappedTile.input=mapped;mappedTile.lastInput=prior;mappedTile.currentMeltTimesLeft=time;bool throws=false;try{mappedTile.OnSetLocalChunkPosition();}catch(IndexOutOfRangeException){throws=true;}Check(throws&&ReferenceEquals(mappedTile.input,mapped)&&mappedTile.input[9].itemValue.Data=="metadata3","actual vanilla material setup still overruns accepted helper result; no engine authorization");}
var forgeChunk=new Chunk();forgeChunk.Value.Block.Properties.Materials="iron, lead";var forge=new TileEntityWorkstation(forgeChunk);forge.OnSetLocalChunkPosition();Check(forge.input.Length==5&&forge.materialNames.SequenceEqual(new[]{"iron","lead"})&&forge.lastInput.Length==3,"native legacy material suffix three");forge.input=Payload(11);bool overrun=false;try{forge.OnSetLocalChunkPosition();}catch(IndexOutOfRangeException){overrun=true;}Check(overrun&&forge.input.Length==11,"native expanded forge setup throws before replacement publication");
var te=new TileEntityWorkstation(new Chunk());te.input=Payload(9);var model=new XUiM_Workstation(te);foreach(int cells in new[]{3,9}){var grid=new XUiC_WorkstationGrid(cells);grid.SetSlots(model.GetInputStacks());Check(grid.itemControllers.Length==cells&&grid.itemControllers[cells-1].ItemStack.itemValue.Data=="metadata"+(cells-1),"native SetSlots applies controller bound");grid.itemControllers[0].ItemStack.itemValue.Data="edit";Check(te.input[0].itemValue.Data=="metadata0","UI stack clones metadata");}
Console.WriteLine("LIMIT: prerequisite nine timer capacity is fixture setup, not installed hook. Stack payload codecs, block definitions, heat delay, recipe/completion streams and UI services explicitly doubled; actual native base read/write/SetHandle and workstation field framing/control flow extracted. No native nine compatibility claimed.");return "PASS "+n+" actual-native initialization/read/write/SetSlots boundary checks";
}
}
}