using System;using System.IO;using System.Linq;
namespace NativeLifecycle {
public static class AIDirector {public static ulong GetActivityWorldTimeDelay()=>5;}
public struct Vector3 {public float x,y,z;public Vector3(float a,float b,float c){x=a;y=b;z=c;}public static Vector3 zero=>default;public static bool operator==(Vector3 a,Vector3 b)=>a.x==b.x&&a.y==b.y&&a.z==b.z;public static bool operator!=(Vector3 a,Vector3 b)=>!(a==b);public override bool Equals(object o)=>o is Vector3 v&&this==v;public override int GetHashCode()=>x.GetHashCode()^y.GetHashCode()^z.GetHashCode();}
public partial class GameManager{}
public static class Log {public static void Warning(string s){} }
public class ConnectionManager {public bool IsServer;public int Broadcasts;public void SendPackage(NetPackageTileEntity p,bool _onlyClientsAttachedToAnEntity,int a,int b,int c,Vector3? v){Broadcasts++;}}
public static class SingletonMonoBehaviour<T> where T:new(){public static T Instance=new T();}
public static class NetPackageManager {public static T GetPackage<T>() where T:new()=>new T();}
public static class MemoryPools {public static ReaderPool poolBinaryReader=new ReaderPool();}
public class ReaderPool {public PooledBinaryReader AllocSync(bool _bReset)=>new PooledBinaryReader();}
public class PackageBase {public virtual void ProcessPackage(World w,GameManager g){} }
public partial class NetPackageTileEntity:PackageBase {public byte handle=17;public Vector3i teWorldPos;public int teBlockId=17;public MemoryStream ms=new MemoryStream();public NetPackageTileEntity Setup(TileBase t,StreamModeWrite m,byte h){return this;} }
public class NonSeekStream:Stream {readonly MemoryStream inner;public NonSeekStream(byte[] b){inner=new MemoryStream(b);}public override bool CanRead=>true;public override bool CanSeek=>false;public override bool CanWrite=>false;public override long Length=>throw new NotSupportedException();public override long Position{get=>throw new NotSupportedException();set=>throw new NotSupportedException();}public override int Read(byte[] b,int o,int n)=>inner.Read(b,o,n);public override void Flush(){}public override long Seek(long o,SeekOrigin s)=>throw new NotSupportedException();public override void SetLength(long n)=>throw new NotSupportedException();public override void Write(byte[] b,int o,int n)=>throw new NotSupportedException();}
public static class RemoteGuardChecks {
static int n;static void Check(bool b,string s){if(!b)throw new Exception(s);n++;}
static ItemStack[] Payload(int size,int add)=>Enumerable.Range(0,size).Select(i=>new ItemStack(new ItemValue(i+add){Data="source"+(i+add),Seed=(ushort)(i+add)},i+add)).ToArray();
static CandidateTileEntityWorkstation Target(int cells){return new CandidateTileEntityWorkstation(new Chunk()){chunkPos=new Vector3i(5,6,7),input=Payload(cells,91),lastInput=Payload(cells,81),currentMeltTimesLeft=Enumerable.Repeat(77f,cells).ToArray(),fuel=Payload(3,71),toolsNet=Payload(3,61),output=Payload(6,51),lockHandleWaitingFor=17,lastTickTime=123,heapMapUpdateTime=45,heapMapLastTime=40,isBurning=true,currentBurnTimeLeft=99,isPlayerPlaced=true};}
static byte[] Frame(int input,int previous,int timers,bool remote){var source=Target(input);source.input=Payload(input,11);source.lastInput=Payload(previous,21);source.currentMeltTimesLeft=Enumerable.Range(0,timers).Select(i=>i+0.5f).ToArray();using var s=new MemoryStream();source.write(new PooledBinaryWriter(s),remote?StreamModeWrite.ToClient:StreamModeWrite.ToServer);return s.ToArray();}
// Native stack payload read and recipe/completion streams are adapters, not full native codec ABI.
static bool Tail(PooledBinaryReader r){for(int i=0;i<9;i++)new ItemStack().Read(r);for(int arrays=0;arrays<2;arrays++){int count=r.ReadByte();for(int i=0;i<count;i++)new ItemStack().Read(r);}r.ReadBoolean();r.ReadSingle();int timerCount=r.ReadByte();for(int i=0;i<timerCount;i++)r.ReadSingle();r.ReadBoolean();r.ReadUInt64();int previousCount=r.ReadByte();for(int i=0;i<previousCount;i++)new ItemStack().Read(r);return timerCount==9&&previousCount==9;}
static bool Dispatch(NetPackageTileEntity package,World world,bool proven,bool abi=true,Func<PooledBinaryReader,bool> tail=null){var tile=(CandidateTileEntityWorkstation)world.Tile;long packetPosition=package.ms.Position;bool allowed;using(var reader=new PooledBinaryReader(package.ms)){package.ms.Position=0;try{allowed=RebirthPlainStationRemoteFrameGuardCandidate.TryPreflightBeforeLiveRead(reader,world.Remote?StreamModeRead.FromServer:StreamModeRead.FromClient,proven,tile.input.Length,tile.lastInput.Length,tile.currentMeltTimesLeft.Length,abi,r=>RebirthPlainStationRemoteFrameGuardCandidate.TryReadCurrentRemoteBaseHeader(r,tile.chunkPos),tail??Tail,out _);}finally{package.ms.Position=packetPosition;}}if(!allowed)return false;package.ProcessPackage(world,new GameManager());return true;}
static string Values(ItemStack[] a)=>string.Join("|",a.Select(s=>$"{s.count}:{s.itemValue.type}:{s.itemValue.Data}:{s.itemValue.Seed}"));
static string Snapshot(CandidateTileEntityWorkstation t)=>$"{t.chunkPos.x},{t.chunkPos.y},{t.chunkPos.z};{t.readVersion};{t.heapMapUpdateTime};{t.heapMapLastTime};{t.lastTickTime};{t.lockHandleWaitingFor};{t.isBurning};{t.currentBurnTimeLeft};{t.isPlayerPlaced};{t.Notifications};{t.Modified};"+Values(t.input)+Values(t.lastInput)+Values(t.fuel)+Values(t.toolsNet)+Values(t.output)+string.Join(",",t.currentMeltTimesLeft);
static NetPackageTileEntity Package(byte[] bytes){return new NetPackageTileEntity{ms=new MemoryStream(bytes),teBlockId=17};}
public static string Run(){
foreach(bool remote in new[]{false,true})foreach(bool accessed in new[]{false,true})foreach(bool waiting in new[]{false,true})foreach(int mismatch in new[]{0,1,2}){
var tile=Target(9);tile.bUserAccessing=accessed;tile.bWaitingForServerResponse=waiting;var world=new World{Tile=tile,Remote=remote};var packet=Package(Frame(mismatch==0?3:9,mismatch==1?3:9,mismatch==2?3:9,remote));packet.ms.Position=2;var snapshot=Snapshot(tile);var originalInput=tile.input;var originalLast=tile.lastInput;var originalTimer=tile.currentMeltTimesLeft;var originalFuel=tile.fuel;SingletonMonoBehaviour<ConnectionManager>.Instance=new ConnectionManager{IsServer=!remote};
Check(!Dispatch(packet,world,true),"proven nine incompatible frame refused before transport");Check(Snapshot(tile)==snapshot&&ReferenceEquals(tile.input,originalInput)&&ReferenceEquals(tile.lastInput,originalLast)&&ReferenceEquals(tile.currentMeltTimesLeft,originalTimer)&&ReferenceEquals(tile.fuel,originalFuel),"all captured live fields/arrays unchanged on refusal");Check(tile.lockHandleWaitingFor==17&&tile.Notifications==0&&tile.Modified==0&&SingletonMonoBehaviour<ConnectionManager>.Instance.Broadcasts==0&&packet.ms.Position==2,"waiting lock reader notify broadcast unchanged");
}
foreach(bool remote in new[]{false,true}){
var tile=Target(9);var world=new World{Tile=tile,Remote=remote};var packet=Package(Frame(9,9,9,remote));SingletonMonoBehaviour<ConnectionManager>.Instance=new ConnectionManager{IsServer=!remote};Check(Dispatch(packet,world,true),"qualified fixture nine frame allowed");Check(tile.input.Length==9&&tile.lastInput.Length==9&&tile.currentMeltTimesLeft.Length==9&&tile.input[8].itemValue.Data=="source19","actual native accepted nine read");Check(tile.lockHandleWaitingFor==byte.MaxValue&&tile.Notifications==1&&SingletonMonoBehaviour<ConnectionManager>.Instance.Broadcasts==(remote?0:1),"actual native accepted transport order");
var legacy=Target(3);world.Tile=legacy;packet=Package(Frame(3,3,3,remote));SingletonMonoBehaviour<ConnectionManager>.Instance=new ConnectionManager{IsServer=!remote};Check(Dispatch(packet,world,false)&&legacy.input.Length==3&&legacy.Notifications==1,"legacy three pass-through");
var unguarded=Target(9);world.Tile=unguarded;packet=Package(Frame(3,3,3,remote));using(var edit=new PooledBinaryWriter(packet.ms)){packet.ms.Position=0;StreamUtils.Write(edit,new Vector3i(88,89,90));}packet.ms.Position=0;SingletonMonoBehaviour<ConnectionManager>.Instance=new ConnectionManager{IsServer=!remote};packet.ProcessPackage(world,new GameManager());Check(unguarded.chunkPos==new Vector3i(88,89,90)&&unguarded.lockHandleWaitingFor==byte.MaxValue&&unguarded.input.Length==3,"unguarded actual base/handle/input mutation demonstrated");
}
var current=Target(9);var valid=Frame(9,9,9,false);foreach(byte[] malformed in new[]{valid.Take(valid.Length-1).ToArray(),valid.Concat(new byte[]{1}).ToArray(),new byte[65536]}){var p=Package(malformed);p.ms.Position=1;var w=new World{Tile=current};var before=Snapshot(current);Check(!Dispatch(p,w,true)&&p.ms.Position==1&&Snapshot(current)==before,"truncated trailing oversized refused without live write");}
using(var nonseek=new PooledBinaryReader(new NonSeekStream(valid)))Check(!RebirthPlainStationRemoteFrameGuardCandidate.TryPreflightBeforeLiveRead(nonseek,StreamModeRead.FromClient,true,9,9,9,true,r=>true,Tail,out _),"nonseekable refuses");
using(var r=new PooledBinaryReader(new MemoryStream(valid))){Check(!RebirthPlainStationRemoteFrameGuardCandidate.TryPreflightBeforeLiveRead(r,StreamModeRead.FromClient,true,9,9,9,false,x=>true,Tail,out _)&&r.BaseStream.Position==0,"missing ABI refuses untouched reader");Check(!RebirthPlainStationRemoteFrameGuardCandidate.TryPreflightBeforeLiveRead(r,StreamModeRead.FromClient,true,9,9,9,true,null,Tail,out _),"missing header refuses");Check(!RebirthPlainStationRemoteFrameGuardCandidate.TryPreflightBeforeLiveRead(r,StreamModeRead.FromClient,true,9,9,9,true,x=>true,null,out _),"missing tail refuses");Check(!RebirthPlainStationRemoteFrameGuardCandidate.TryPreflightBeforeLiveRead(r,StreamModeRead.Persistency,true,9,9,9,true,x=>true,Tail,out _),"persistency not remote parser");}
Console.WriteLine(MappedRemoteChecks.Run());return "PASS "+n+" changed remote-guard actual base/transport ordering checks; tail ItemStack/recipe/completion codec adapters remain partial; no production hook";
}
}
}