using System;using System.Linq;using System.Collections.Generic;
namespace NativeLifecycle {
public static class FeatureExtension {public static bool TryGetSelfOrFeature<T>(this TileBase tile,out T value) where T:class {value=tile as T;return value!=null;}}
public class Recipe {public List<ItemStack> ingredients=new List<ItemStack>();public bool UseIngredientModifier;public int itemValueType;}
public static class CraftingManager {public static List<Recipe> Recipes=new List<Recipe>();public static List<Recipe> GetAllRecipes()=>Recipes;}
public static class Mathf {public static int Min(int a,int b)=>Math.Min(a,b);}
public partial class GameManager {public static GameManager Instance=new GameManager();public int Drops;public ItemStack[] Dropped;public int Actor;public string Container;public Vector3 DropPosition;public bool SkipIfEmpty;public void DropContentInLootContainerServer(int actor,string name,Vector3 pos,ItemStack[] stacks,bool _skipIfEmpty){Drops++;Actor=actor;Container=name;DropPosition=pos;Dropped=stacks;SkipIfEmpty=_skipIfEmpty;}}
public static class ReplacedByChecks {
static int n;static void Check(bool b,string s){if(!b)throw new Exception(s);n++;}
static ItemStack[] Stacks(int count,int basis)=>Enumerable.Range(0,count).Select(i=>new ItemStack(new ItemValue(basis+i){Data="full-metadata"+(basis+i),Seed=(ushort)(basis+i),Meta=17,Quality=6,UseTimes=-0.25f,TextureFullArray=new TextureFullArray{Bits=12345}},basis+i)).ToArray();
static T Populate<T>(T tile,int cells) where T:TileEntityWorkstation {tile.input=Stacks(cells,100);tile.lastInput=Stacks(cells,200);tile.currentMeltTimesLeft=new float[cells];tile.fuel=Stacks(3,300);tile.tools=Stacks(3,400);tile.output=Stacks(6,500);return tile;}
static void Drop(TileEntityWorkstation tile,TileBase replacement=null){GameManager.Instance=new GameManager();tile.ReplacedBy(new BlockValue(),new BlockValue(),replacement??new TileBase(new Chunk()));}
static void CheckOrder(TileEntityWorkstation tile,int physical){var actual=GameManager.Instance.Dropped;var expected=tile.fuel.Concat(tile.input.Take(physical).Where(s=>!s.IsEmpty())).Concat(tile.tools).Concat(tile.output).ToArray();Check(actual.Length==expected.Length,"native fuel/input/tools/output list count");for(int i=0;i<expected.Length;i++)Check(ReferenceEquals(actual[i],expected[i])&&actual[i].itemValue.Data==expected[i].itemValue.Data&&actual[i].itemValue.Seed==expected[i].itemValue.Seed,"exact payload reference and ordered drop once");Check(GameManager.Instance.Drops==1&&GameManager.Instance.Actor==-1&&GameManager.Instance.Container=="DroppedLootContainer"&&GameManager.Instance.SkipIfEmpty&&GameManager.Instance.DropPosition.x==1&&Math.Abs(GameManager.Instance.DropPosition.y-1.9f)<0.0001f&&GameManager.Instance.DropPosition.z==1,"native drop owner/container/position/onecall");}
static string DropSignature()=>string.Join("|",GameManager.Instance.Dropped.Select(x=>x.itemValue.type+":"+x.count+":"+x.itemValue.Data));
public static string Run(){
var native=Populate(new TileEntityWorkstation(new Chunk()),9);Drop(native);CheckOrder(native,3);Check(!GameManager.Instance.Dropped.Contains(native.input[8]),"native three omits sixth extra input - custody gap");
var candidate=Populate(new CandidateTileEntityWorkstation(new Chunk()){CurrentLayoutWitness=true},9);Drop(candidate);CheckOrder(candidate,9);Check(GameManager.Instance.Dropped.Contains(candidate.input[8]),"fixture authenticated nine includes last physical cell");
candidate.input[0]=new ItemStack(new ItemValue(0){Seed=123,Data="seeded empty"},5);candidate.input[8]=new ItemStack(new ItemValue(108){Seed=456},0);Drop(candidate);CheckOrder(candidate,9);Check(!GameManager.Instance.Dropped.Contains(candidate.input[0])&&!GameManager.Instance.Dropped.Contains(candidate.input[8])&&candidate.input[0].itemValue.Seed==123,"empty physical cells skipped without empty reset");
var unknown=Populate(new CandidateTileEntityWorkstation(new Chunk()){CurrentLayoutWitness=false},9);Drop(unknown);CheckOrder(unknown,3);Check(!GameManager.Instance.Dropped.Contains(unknown.input[8]),"unknown nine fallback three remains custody gap");
var mismatched=Populate(new CandidateTileEntityWorkstation(new Chunk()){CurrentLayoutWitness=true},9);mismatched.lastInput=Stacks(3,200);Drop(mismatched);CheckOrder(mismatched,3);Check(!GameManager.Instance.Dropped.Contains(mismatched.input[8]),"unaligned nine fallback custody gap");
var legacy=Populate(new CandidateTileEntityWorkstation(new Chunk()){CurrentLayoutWitness=false},3);Drop(legacy);CheckOrder(legacy,3);
foreach(bool proven in new[]{false,true}){var same=Populate(new CandidateTileEntityWorkstation(new Chunk()){CurrentLayoutWitness=proven},9);var original=same.input;Drop(same,new TileEntityWorkstation(new Chunk()));Check(GameManager.Instance.Drops==0&&ReferenceEquals(same.input,original)&&same.input[8].itemValue.Data=="full-metadata108","same-workstation native earlyreturn unchanged; no transfer claim");}
ItemClass.Units=new Dictionary<string,ItemClass>{{"unit_iron",new ItemClass{Id=31,Name="iron",MadeOfMaterial=new Material{ForgeCategory="iron"}}},{"unit_lead",new ItemClass{Id=32,Name="lead",MadeOfMaterial=new Material{ForgeCategory="lead"}}}};CraftingManager.Recipes=new List<Recipe>{new Recipe{itemValueType=701,ingredients=new List<ItemStack>{new ItemStack(new ItemValue(31),2)}},new Recipe{itemValueType=702,ingredients=new List<ItemStack>{new ItemStack(new ItemValue(32),2)}}};
var nativeForge=Populate(new TileEntityWorkstation(new Chunk()),5);nativeForge.materialNames=new[]{"iron","lead"};nativeForge.input[3]=new ItemStack(new ItemValue(31),5);nativeForge.input[4]=new ItemStack(new ItemValue(0){Seed=789},9);Drop(nativeForge);string expectedMaterial=DropSignature();Check(GameManager.Instance.Dropped[6].itemValue.type==701&&GameManager.Instance.Dropped[6].count==2&&GameManager.Instance.Dropped[7].itemValue.type==702&&GameManager.Instance.Dropped[7].count==2&&GameManager.Instance.Dropped[8].itemValue.type==702&&GameManager.Instance.Dropped[8].count==2,"native suffix jplus3 conversion order and maxstack split");
var forge=Populate(new CandidateTileEntityWorkstation(new Chunk()){CurrentLayoutWitness=true},5);forge.materialNames=new[]{"iron","lead"};forge.input[3]=new ItemStack(new ItemValue(31),5);forge.input[4]=new ItemStack(new ItemValue(0){Seed=789},9);Drop(forge);Check(DropSignature()==expectedMaterial&&GameManager.Instance.Drops==1&&forge.input[4].itemValue.type==32,"material path identical native three prefix/suffix normalization");
return "PASS "+n+" changed ReplacedBy whole-native-body checks; witness/drop/world/material adapters explicit, unknown nine remains custody gap";
}
}
}