using System;using System.IO;using System.Collections.Generic;using System.Linq;
public class PooledBinaryWriter:BinaryWriter {public PooledBinaryWriter(Stream s):base(s){}}public class PooledBinaryReader:BinaryReader {public PooledBinaryReader(Stream s):base(s){}}
public enum NetPackageDirection {Both,ToServer,ToClient}public abstract class NetPackage {public ClientInfo Sender;public bool AllowedBeforeAuth;protected bool ValidEntityIdForSender(int actor)=>Sender!=null&&Sender.entityId==actor;protected bool ValidUserIdForSender(PlatformUserIdentifierAbs id)=>Sender!=null&&id!=null&&Sender.PlatformId!=null&&id.canonical.SequenceEqual(Sender.PlatformId.canonical);public virtual bool ShouldProcess(World w,GameManager g)=>true;public virtual void HandleSkipped(World w,GameManager g){}public virtual NetPackageDirection PackageDirection=>NetPackageDirection.Both;public virtual void write(PooledBinaryWriter w){}public abstract void read(PooledBinaryReader r);public abstract void ProcessPackage(World w,GameManager g);}public static class NetPackageManager{public static int Freed;public static int GetPackageId(Type t)=>123;public static void FreePackage(NetPackage p){Freed++;}public static T GetPackage<T>()where T:NetPackage,new()=>new();}
public interface INetConnection{bool IsDisconnected();void GetPackages(List<NetPackage> list);}public class Peer:INetConnection{public bool Dead;public List<NetPackage> Incoming=new();public bool IsDisconnected()=>Dead;public void GetPackages(List<NetPackage> list){list.Clear();list.AddRange(Incoming);Incoming.Clear();}}
public class ClientInfo{public PlatformUserIdentifierAbs PlatformId=new PlatformUserIdentifierAbs(),CrossplatformId;public int ClientNumber,entityId;public bool loginDone=true,bAttachedToEntity=true,disconnecting;public INetConnection[] netConnection;public NetPackage Sent;public void SendPackage(NetPackage p){Sent=p;}}
public class ClientInfoCollection{public Dictionary<int,ClientInfo> Entries=new();public ClientInfo ForClientNumber(int n)=>Entries.TryGetValue(n,out var c)?c:null;}
public partial class ConnectionManager{public List<NetPackage> packagesToProcess=new();public bool IsServer;public ClientInfoCollection Clients=new();public INetConnection[] connectionToServer;public NetPackage Sent;public void SendToServer(NetPackage p,bool flush=false){Sent=p;}}
public static class SingletonMonoBehaviour<T> where T:new(){public static T Instance=new T();}public partial class GameManager{public void SetBlocksRPC(System.Collections.Generic.List<BlockChangeInfo> c,PlatformUserIdentifierAbs p=null){}public void ChangeBlocks(PlatformUserIdentifierAbs p,System.Collections.Generic.List<BlockChangeInfo> changes){foreach(var c in changes){World.block=c.blockValue;World.Density=c.density;World.Texture=c.textureFull[0];World.Tile=null;}}public bool IsEditMode()=>false;public static GameManager Instance;public World World;}
public class WorldState{public string Guid;}public class World{public TileEntityPlantGrowingRebirth Tile;public ChunkCache ChunkCache=new ChunkCache();public sbyte Density;public long Texture;public object GetTileEntity(Vector3i p)=>Tile;public sbyte GetDensity(int x,int y,int z)=>Density;public long GetTexture(int x,int y,int z)=>Texture;public BlockValue block;public BlockValue GetBlock(Vector3i p)=>block;public WorldState worldState=new();public bool Remote;public Dictionary<int,EntityPlayer> Actors=new();public EntityPlayerLocal Primary;public bool IsRemote()=>Remote;public EntityPlayer GetEntity(int id)=>Actors.TryGetValue(id,out var p)?p:null;public EntityPlayerLocal GetPrimaryPlayer()=>Primary;}
public class EntityPlayer{public Inventory inventory=new Inventory();public Hand Hand=new Hand();public void PlayOneShot(string s){}public int entityId;public World world;public bool Dead;public bool IsDead()=>Dead;}public class EntityPlayerLocal:EntityPlayer{public bool Spawned=true;public bool IsSpawned()=>Spawned;}
public class RebirthWorldCharacterRecord{public Origin Origin=new();}public class Origin{public string CreationId;}public static class RebirthWorldCharacterService{public static RebirthWorldCharacterRecord Owner;public static bool TryGet(ClientInfo c,out RebirthWorldCharacterRecord o){o=Owner;return o!=null;}}
public static class RebirthSurvivorClientState{public static string Creation;public static Action Callback;public static string GetProjectedCreationId(EntityPlayer p){var result=Creation;Callback?.Invoke();return result;}}
public static class ThreadManager{public static bool Main=true;public static bool IsMainThread()=>Main;public static void AddSingleTaskMainThread(string key,Action<object> action){action(null);}}public enum EnumGamePrefs{GameGuidClient}public static class GamePrefs{public static string World;public static string GetString(EnumGamePrefs p)=>World;} public static class Log{public static void Error(string x){}public static void Warning(string x){}}
namespace HarmonyLib{[System.AttributeUsage(System.AttributeTargets.Class)]public class HarmonyPatch:System.Attribute{public HarmonyPatch(System.Type t,string s){}public HarmonyPatch(System.Type t,string s,System.Type[] a){}}}
namespace UnityEngine{public class WaitForSeconds{public WaitForSeconds(float f){}}}
public struct Vector3i{public int x,y,z;public Vector3i(int a,int b,int c){x=a;y=b;z=c;}}
public class Shape{public bool IsOmitTerrainSnappingUp;public bool IsTerrain()=>false;}
public class Block{public bool HasTileEntity;public Shape shape=new Shape();public bool IsTerrainDecoration;public string CustomPlaceSound;}
public class BlockPlantGrowing:Block{}
public class BlockPlantGrowingRebirth:BlockPlantGrowing{public bool IsSeedStage(BlockValue b)=>true;}
public struct BlockValue{public uint rawData;public int damage;public bool ischild=>false;public int type=>(int)rawData;public Block Block=>new BlockPlantGrowingRebirth();public BlockValue(uint r,int d){rawData=r;damage=d;}}
public struct TextureFullArray{public TextureFullArray(long value){values=new[]{value};}public long[] values;public bool IsDefault=>values==null||values[0]==0;public long this[int i]=>values==null?0:values[i];}
public class TypedMetadataValue{public enum TypeTag{None,Float,Integer,String}public TypeTag tag;public object value;public TypeTag GetTypeTag()=>tag;public object GetValue()=>value;}
public class ItemValue{public struct Stat{public int type;public bool isBoosted;public short value;}public int type,Meta;public float UseTimes;public ushort Quality,Seed;public byte Flags,SelectedAmmoTypeIndex;public TextureFullArray TextureFullArray;public Stat[] Stats;public ItemValue[] modifications,cosmeticMods;public System.Collections.Generic.Dictionary<string,TypedMetadataValue> Metadata;public BlockValue ToBlockValue()=>new BlockValue((uint)type,0);}
public class ItemStack{public ItemValue itemValue;public int count;public ItemStack(ItemValue v,int n){itemValue=v;count=n;}public ItemStack Clone()=>new ItemStack(itemValue,count);}
public class Hand{public bool WaitForSecondaryRelease;}
public class Inventory{public int holdingItemIdx,SelectedSlot,SlotCount=10;public ItemInventoryData holdingItemData;public ItemStack stack;public ItemStack holdingItemStack=>stack;public ItemValue holdingItemItemValue=>stack.itemValue;public ItemStack GetItem(int i)=>stack;public void SetItem(int _idx,ItemStack _itemStack){object state;SeedNativeSetterWitnessPatch.Prefix(this,_idx,_itemStack,out state);stack=_itemStack;SeedNativeSetterWitnessPatch.Postfix(state);}}
public class ItemInventoryData{public EntityPlayer holdingEntity;public World world;public bool IsBlock=true;public ItemValue itemValue;}
public class BlockPlacement{public enum EnumPlacement{Voxel,Free}public struct Result{public EnumPlacement placement;public Vector3i blockPos;public BlockValue blockValue;}}
public partial class BlockToolSelection{}
public static class MarchingCubes{public const sbyte DensityAir=-127;}
public struct BlockValueRef{public Vector3i pos;public BlockValueRef(Vector3i p){pos=p;}public bool TryGetBlockPos(out Vector3i p){p=pos;return true;}}
public class BlockChangeInfo{public BlockChangeInfo(){}public BlockChangeInfo(BlockValueRef pos,BlockValue value,bool change,int actor){blockValueRef=pos;blockValue=value;bChangeBlockValue=change;changedByEntityId=actor;}public int changedByEntityId;public BlockValueRef blockValueRef;public BlockValue blockValue;public bool bChangeBlockValue,bChangeDamage,bChangeDensity,bForceDensity,bUpdateLight,bChangeTexture;sbyte unused;public sbyte density;public TextureFullArray textureFull;public void Read(PooledBinaryReader r){if(r.ReadByte()!=1)throw new System.IO.InvalidDataException();blockValueRef=new BlockValueRef(new Vector3i(r.ReadInt32(),r.ReadInt32(),r.ReadInt32()));changedByEntityId=r.ReadInt32();byte f=r.ReadByte();bChangeBlockValue=(f&1)!=0;bChangeDamage=(f&2)!=0;bChangeDensity=(f&4)!=0;bForceDensity=(f&8)!=0;bUpdateLight=(f&16)!=0;bChangeTexture=(f&32)!=0;if(bChangeBlockValue)blockValue=new BlockValue(r.ReadUInt32(),r.ReadUInt16());if(bChangeDensity)density=r.ReadSByte();if(bChangeTexture)textureFull=new TextureFullArray{values=new[]{r.ReadInt64()}};}}
public class PlatformUserIdentifierAbs{public byte[] canonical=new byte[]{1,0};public void ToStream(PooledBinaryWriter w)=>w.Write(canonical);}
public static class StreamUtils{public static System.IO.MemoryStream ToBlob(System.Action<PooledBinaryWriter> a){var m=new System.IO.MemoryStream();var w=new PooledBinaryWriter(m);a(w);w.Flush();return m;}public static void FromBlob(System.IO.MemoryStream m,System.Action<PooledBinaryReader> a)=>a(new PooledBinaryReader(m));}
public class NetPackageSetBlock:NetPackage{public System.Collections.Generic.List<BlockChangeInfo> blockChanges;public int localPlayerThatChanged;public PlatformUserIdentifierAbs persistentPlayerId=new PlatformUserIdentifierAbs();public override void read(PooledBinaryReader r){}public override void ProcessPackage(World w,GameManager g){}public override void write(PooledBinaryWriter w){w.Write((ushort)123);persistentPlayerId.ToStream(w);w.Write((short)blockChanges.Count);foreach(var c in blockChanges){w.Write((byte)1);w.Write(c.blockValueRef.pos.x);w.Write(c.blockValueRef.pos.y);w.Write(c.blockValueRef.pos.z);w.Write(c.changedByEntityId);byte f=(byte)((c.bChangeBlockValue?1:0)|(c.bChangeDamage?2:0)|(c.bChangeDensity?4:0)|(c.bForceDensity?8:0)|(c.bUpdateLight?16:0)|(c.bChangeTexture?32:0));w.Write(f);w.Write(c.blockValue.rawData);w.Write((ushort)c.blockValue.damage);if(c.bChangeDensity)w.Write(c.density);if(c.bChangeTexture)w.Write(c.textureFull[0]);}w.Write(localPlayerThatChanged);}}
namespace HarmonyLib{
public class CodeInstruction{public System.Reflection.Emit.OpCode opcode;public object operand;public CodeInstruction(System.Reflection.Emit.OpCode o,object p){opcode=o;operand=p;}}
public class HarmonyMethod{public HarmonyMethod(System.Reflection.MethodInfo m){}}
public class Harmony{public void Patch(System.Reflection.MethodInfo m,HarmonyMethod transpiler=null){}public void Unpatch(System.Reflection.MethodInfo m,System.Reflection.MethodInfo p){}}
public static class AccessTools{public static System.Reflection.MethodInfo Method(System.Type t,string n,System.Type[] p=null)=>p==null?t.GetMethod(n,System.Reflection.BindingFlags.Public|System.Reflection.BindingFlags.NonPublic|System.Reflection.BindingFlags.Static|System.Reflection.BindingFlags.Instance):t.GetMethod(n,p);public static T MethodDelegate<T>(System.Reflection.MethodInfo m)where T:System.Delegate=>(T)m.CreateDelegate(typeof(T));}}
public class PlayerActionsLocal{}
public static class AdvancedFarmingLocalPlantingAdmission{public class Local: System.IDisposable{public void Dispose(){}public bool Complete()=>true;}public static Local Begin(ItemInventoryData d,BlockPlacement.Result r,BlockValue b)=>null;}
public class TileEntityPlantGrowingRebirth{public ulong PlantIncarnation=5,StateRevision=1;}
public class ChunkCache{public object Chunk=new object();public object GetChunkFromWorldPos(BlockValueRef p)=>Chunk;}

