public static class Cases {
 static int n;static void A(bool ok,string name){n++;if(!ok)throw new Exception(name);}
 static CandidateAbi Make(){RebirthBackpackLibraryReservation.Block=false;RebirthStationGridIngredients.Valid=true;RebirthStationGridIngredients.Calls=0;RebirthStationGridIngredients.Callback=null;RebirthStationGridIngredients.CompareCallback=null;var c=new CandidateAbi();var w=new World();var p=new EntityPlayerLocal{world=w};w.Player=p;GameManager.Instance.World=w;c.xui.playerUI.entityPlayer=p;c.result=new Recipe();c.selected=null;c.batch=3;c.station=new XUiC_RebirthCookingStation();c.slots=Enumerable.Range(0,12).Select(i=>new XUiC_RebirthCookingSlot{ItemStack=new ItemStack{count=i==0?3:0}}).ToArray();return c;}
 static bool Pass(CandidateAbi c,bool fresh=true){Recipe r;string b;return c.TryCookingPreflight(fresh,out r,out b);}
 public static int Run(){var c=Make();A(Pass(c),"normal actual candidate");c=Make();c.slots[0].ItemStack.itemValue.Full=false;A(!Pass(c),"partial drink");c=Make();c.slots[0].ItemStack.count=2;A(!Pass(c),"short batch");c=Make();c.slots[1].ItemStack.count=3;A(!Pass(c),"duplicate type");c=Make();RebirthBackpackLibraryReservation.Block=true;A(!Pass(c),"library hold");c=Make();c.submittingCook=true;A(!Pass(c),"submitting");c=Make();c.preparingRequest=true;A(!Pass(c),"preparation pending");c=Make();c.result=null;A(!Pass(c),"no result");c=Make();c.slots[0].ItemStack.count=0;A(!Pass(c),"empty grid");c=Make();c.station.Valid=false;A(!Pass(c),"native station requirement");c=Make();c.station.IsMilling=true;A(Pass(c),"actual milling API called");A(RebirthStationGridIngredients.Calls==1,"single plan");c=Make();c.station.IsMilling=true;RebirthStationGridIngredients.Valid=false;A(!Pass(c),"failed plan");
 foreach(string mode in new[]{"metadata","count","owner","world","result","selected","batch","resultInPlace","ingredientInPlace"}){c=Make();var original=c;c.station.Callback=()=>{switch(mode){case "metadata":original.slots[0].ItemStack.itemValue.Metadata="reentry";break;case "count":original.slots[0].ItemStack.count++;break;case "owner":original.xui.playerUI.entityPlayer=new EntityPlayerLocal{world=original.xui.playerUI.entityPlayer.world};break;case "world":GameManager.Instance.World=new World();break;case "result":original.result=new Recipe();break;case "selected":original.selected=new Recipe();break;case "batch":original.batch++;break;case "resultInPlace":original.result.count++;break;case "ingredientInPlace":original.result.ingredients.Add(new ItemStack());break;}};A(!Pass(c),"native callback changed "+mode);}
 c=Make();c.station.IsMilling=true;A(Pass(c,false)&&Pass(c,false)&&RebirthStationGridIngredients.Calls==1,"same render cache one plan");c.cookingReadinessRevision++;A(Pass(c,false)&&RebirthStationGridIngredients.Calls==2,"next render fresh plan");c.slots[0].ItemStack.count=1;A(!Pass(c,true),"paid Cook bypass cached presentation");
 c=Make();A(Pass(c),"saved pre-stamp witness");var witness=c.lastBuiltCookingWitness;c.slots[0].ItemStack.itemValue.Metadata="poststamp";A(!c.CookingPreflightStillCurrent(witness),"post Stamp/Heat callback mutation before registration refuses");
 c=Make();c.station.Callback=()=>{throw new InvalidOperationException("native original exception");};try{Pass(c);throw new Exception("native fault swallowed");}catch(InvalidOperationException ex){A(ex.Message=="native original exception","native callback exception preserved");}
 c=Make();c.station.craftingQueue.Entries[0].Recipe=new Recipe();A(!Pass(c),"existing occupied queue refuses with original blocker");
 c=Make();var q=c;c.station.Callback=()=>q.station.craftingQueue.Entries[0].Recipe=new Recipe();A(!Pass(c),"native callback new queue entry refuses");
 c=Make();q=c;c.station.Callback=()=>q.station.craftingQueue=new Queue();A(!Pass(c),"native callback queue controller replaced refuses");
 c=Make();q=c;c.station.Callback=()=>q.station.craftingQueue.Entries[0]=new QueueEntry();A(!Pass(c),"native callback empty cell identity replaced refuses");
 c=Make();A(Pass(c),"original empty queue retained");var queueWitness=c.lastBuiltCookingWitness;c.station.craftingQueue.Entries[0].Recipe=new Recipe();A(!c.CookingPreflightStillCurrent(queueWitness),"afterStamp queue appears before registration refuses");
 foreach(string flag in new[]{"open","showing","generation","ui","playerui","windowgroup","preparing","submitting","library"}){c=Make();var uiCase=c;c.station.Callback=()=>{switch(flag){case "open":uiCase.open=false;break;case "showing":uiCase.windowGroup.isShowing=false;break;case "generation":uiCase.pullUiGeneration++;break;case "ui":uiCase.xui=new XUi();break;case "playerui":uiCase.xui.playerUI=new PlayerUI{entityPlayer=uiCase.xui.playerUI.entityPlayer};break;case "windowgroup":uiCase.windowGroup=new Group();break;case "preparing":uiCase.preparingRequest=true;break;case "submitting":uiCase.submittingCook=true;break;case "library":RebirthBackpackLibraryReservation.Block=true;break;}};A(!Pass(c),"original UI/flag callback "+flag);}
 c=Make();var later=c;bool changed=false;RebirthStationGridIngredients.CompareCallback=stack=>{if(!changed&&object.ReferenceEquals(stack,later.slots[11].ItemStack)){changed=true;later.slots[0].ItemStack.itemValue.Metadata="late native writer";}};A(!Pass(c),"later cell changes earlier cell caught repeated readback");
 return n;}
}