// TOOLS ONLY: supplied partitions, native image keys and observations are detached DATA, not attribution authority.
sealed class AttributionLedger {
 public sealed record Paid(string Job,string Receipt,int Quantity);
 public sealed class Slot {
  public string Image{get;}public int Count{get;}public int Ordinary{get;}public int Unresolved{get;}public bool Invalid{get;}readonly Paid[] paid;
  internal Slot(string image,int count,int ordinary,int unresolved,Paid[] p,bool invalid=false){Image=image;Count=count;Ordinary=ordinary;Unresolved=unresolved;paid=(Paid[])p.Clone();Invalid=invalid;}
  public Paid[] Partitions()=>(Paid[])paid.Clone();
 }
 // SourceDebitAccounted is ONLY detached station accounting, never recipient Applied/save proof or terminal release.
 public sealed record Original(PaidCustodyPlan Plan,string Receipt,bool SourceDebitAccounted);
 public enum ReservationDisposition{Refused,NewReservation,RetrievedOriginal}
 public enum Recovery{Refused,OriginalBefore,OriginalAfter}
 public string Identity{get;}public string World{get;}public string Station{get;}public long Revision{get;}readonly Slot[] slots;readonly Dictionary<string,Original> requests;
 AttributionLedger(string id,string world,string station,long revision,Slot[] slots,Dictionary<string,Original> requests){Identity=id;World=world;Station=station;Revision=revision;this.slots=(Slot[])slots.Clone();this.requests=new(requests,StringComparer.Ordinal);}
 static bool Id(string s)=>s!=null&&s.Length>0&&s.Length<=256&&s.Trim()==s&&!s.Any(char.IsControl);
 public Slot[] Slots()=>(Slot[])slots.Clone();public bool TryOriginal(string request,out Original original)=>requests.TryGetValue(request,out original);
 public static bool TryCreate(string id,string world,string station,long revision,Slot[] slots,out AttributionLedger ledger){ledger=null;try{if(!Id(id)||!Id(station)||!Guid.TryParseExact(world,"N",out var w)||w==Guid.Empty||w.ToString("N")!=world||revision<0||revision==long.MaxValue||slots==null||slots.Length<1||slots.Length>255)return false;int budget=8*1024*1024,partitions=0;foreach(var s in slots){if(s==null||s.Count<0||s.Count>65535||s.Ordinary<0||s.Unresolved<0||s.Invalid||s.Image==null)return false;var paid=s.Partitions();if(paid.Length>64||(partitions+=paid.Length)>256)return false;long total=(long)s.Ordinary+s.Unresolved;var keys=new HashSet<(string,string)>();foreach(var p in paid){if(p==null||!Id(p.Job)||!Id(p.Receipt)||p.Quantity<1||!keys.Add((p.Job,p.Receipt)))return false;total+=p.Quantity;}if(total!=s.Count)return false;if(s.Count==0){if(s.Image!="")return false;}else{if(s.Image.Length<1||s.Image.Length>262144||(budget-=s.Image.Length)<0)return false;var bytes=Convert.FromBase64String(s.Image);if(bytes.Length<1||bytes.Length>196608||Convert.ToBase64String(bytes)!=s.Image)return false;}}ledger=new(id,world,station,revision,slots,new());return true;}catch{return false;}}
 bool Next()=>Revision<long.MaxValue-1;
 public bool TryReserveOrRetrieve(PaidCustodyPlan plan,string receipt,out AttributionLedger next,out PaidCustodyPlan retained,out ReservationDisposition disposition){next=null;retained=null;disposition=ReservationDisposition.Refused;if(plan==null||!Id(receipt))return false;if(requests.TryGetValue(plan.Request,out var existing)){if(existing.Receipt!=receipt||!existing.Plan.Same(plan))return false;next=this;retained=existing.Plan;disposition=ReservationDisposition.RetrievedOriginal;return true;}if(!Next()||requests.Count>=64||plan.Ledger!=Identity||plan.World!=World||plan.Station!=Station||plan.Revision!=Revision||plan.Source<0||plan.Source>=slots.Length)return false;var before=plan.StationBefore();if(before.Length!=slots.Length)return false;for(int i=0;i<slots.Length;i++)if(before[i].Image!=slots[i].Image||before[i].Count!=slots[i].Count)return false;var source=slots[plan.Source];if(source.Invalid||requests.Values.Any(x=>!x.SourceDebitAccounted&&x.Plan.Source==plan.Source))return false;var part=source.Partitions().SingleOrDefault(p=>p.Job==plan.Job&&p.Receipt==receipt);if(part==null||part.Quantity!=plan.PaidBefore||part.Quantity<plan.Quantity)return false;long retainedBytes=System.Text.Encoding.UTF8.GetByteCount(plan.Serialize());foreach(var entry in requests.Values){retainedBytes+=System.Text.Encoding.UTF8.GetByteCount(entry.Plan.Serialize());if(retainedBytes>8*1024*1024)return false;}if(retainedBytes>8*1024*1024)return false;var copy=new Dictionary<string,Original>(requests,StringComparer.Ordinal);copy.Add(plan.Request,new(plan,receipt,false));next=new(Identity,World,Station,Revision+1,slots,copy);retained=plan;disposition=ReservationDisposition.NewReservation;return true;}
 public bool TryInvalidate(int source,long expectedRevision,out AttributionLedger next){next=null;if(!Next()||expectedRevision!=Revision||source<0||source>=slots.Length)return false;var old=slots[source];if(old.Invalid){next=this;return true;}var copy=(Slot[])slots.Clone();copy[source]=new(old.Image,old.Count,old.Ordinary,old.Unresolved,old.Partitions(),true);next=new(Identity,World,Station,Revision+1,copy,requests);return true;}
 public bool TryAccountSourceDebit(string request,long expectedRevision,PaidCustodyPlan.Cell[] observed,out AttributionLedger next)=>Finish(request,expectedRevision,observed,false,out next);
 bool Finish(string request,long expectedRevision,PaidCustodyPlan.Cell[] observed,bool recovering,out AttributionLedger next){next=null;if(expectedRevision!=Revision||request==null||!requests.TryGetValue(request,out var original))return false;if(original.SourceDebitAccounted){next=this;return true;}if(!Next()||observed==null||observed.Length!=slots.Length)return false;var plan=original.Plan;int source=plan.Source;if(slots[source].Invalid&&!recovering)return false;var after=plan.StationAfter()[source];for(int i=0;i<slots.Length;i++){var expected=i==source?after:new PaidCustodyPlan.Cell(slots[i].Image,slots[i].Count);if(observed[i]!=expected)return false;}var old=slots[source];var parts=old.Partitions();int index=Array.FindIndex(parts,p=>p.Job==plan.Job&&p.Receipt==original.Receipt);if(index<0||parts[index].Quantity<plan.Quantity||old.Image!=plan.StationBefore()[source].Image||old.Count!=plan.StationBefore()[source].Count)return false;parts[index]=parts[index] with{Quantity=parts[index].Quantity-plan.Quantity};parts=parts.Where(p=>p.Quantity>0).ToArray();var copy=(Slot[])slots.Clone();copy[source]=new(after.Image,after.Count,old.Ordinary,old.Unresolved,parts);var rq=new Dictionary<string,Original>(requests,StringComparer.Ordinal);rq[request]=original with{SourceDebitAccounted=true};next=new(Identity,World,Station,Revision+1,copy,rq);return true;}
 public Recovery TryRecoverOriginal(string request,long expectedRevision,PaidCustodyPlan.Cell[] observed,out AttributionLedger next){next=null;if(request==null||expectedRevision!=Revision||!requests.TryGetValue(request,out var original)||original.SourceDebitAccounted||!Next()||observed==null||observed.Length!=slots.Length)return Recovery.Refused;int source=original.Plan.Source;if(!slots[source].Invalid)return Recovery.Refused;for(int i=0;i<slots.Length;i++)if(i!=source&&observed[i]!=new PaidCustodyPlan.Cell(slots[i].Image,slots[i].Count))return Recovery.Refused;if(observed[source]==original.Plan.StationBefore()[source]){var old=slots[source];var copy=(Slot[])slots.Clone();copy[source]=new(old.Image,old.Count,old.Ordinary,old.Unresolved,old.Partitions());next=new(Identity,World,Station,Revision+1,copy,requests);return Recovery.OriginalBefore;}return Finish(request,expectedRevision,observed,true,out next)?Recovery.OriginalAfter:Recovery.Refused;}
}


