using System.Globalization;using System.Text;
using System.Xml;
using System.Xml.Linq;
using G=RebirthGearInventoryPlan;
// TOOLS ONLY detached schema prototype. Supplied ledger identities are data, never authenticated attribution.
sealed class PaidCustodyPlan {
 public sealed record Cell(string Image,int Count);
 public string Station {get;} public string Request {get;} public string Job {get;} public string World {get;} public string Recipient {get;} public string Creation {get;} public string Ledger {get;}public long Revision {get;}public int Source {get;} public int PaidBefore {get;}public int Quantity {get;}public int Owned {get;}public int Maximum {get;}
 readonly Cell[] sb,sa,bb,ba,tb,ta;
 PaidCustodyPlan(string request,string station,string job,string world,string recipient,string creation,string ledger,long revision,int source,int paid,int qty,int owned,int max,Cell[] sb,Cell[] sa,Cell[] bb,Cell[] ba,Cell[] tb,Cell[] ta){Request=request;Station=station;Job=job;World=world;Recipient=recipient;Creation=creation;Ledger=ledger;Revision=revision;Source=source;PaidBefore=paid;Quantity=qty;Owned=owned;Maximum=max;this.sb=sb;this.sa=sa;this.bb=bb;this.ba=ba;this.tb=tb;this.ta=ta;}
 public Cell[] StationBefore()=>(Cell[])sb.Clone(); public Cell[] StationAfter()=>(Cell[])sa.Clone(); public Cell[] BagAfter()=>(Cell[])ba.Clone();
 static bool Id(string s)=>s!=null&&s.Length>0&&s.Length<=256&&s.Trim()==s&&!s.Any(char.IsControl);
 static bool Cells(Cell[] a,int min,int max,ref int budget){if(a==null||a.Length<min||a.Length>max)return false;foreach(var c in a){if(c==null||c.Count<0||c.Count>65535||c.Image==null)return false;if(c.Count==0){if(c.Image.Length!=0)return false;continue;}if(c.Image.Length<1||c.Image.Length>262144||c.Image.Length>budget)return false;var bytes=Convert.FromBase64String(c.Image);if(bytes.Length==0||bytes.Length>196608||Convert.ToBase64String(bytes)!=c.Image)return false;budget-=c.Image.Length;}return true;}
 static G.Stack[] Enc(Cell[] a)=>a.Select(c=>new G.Stack{Count=c.Count,ItemData=c.Image}).ToArray();
 public static bool TryCreate(string request,string station,string job,string world,string recipient,string creation,string ledger,long revision,int source,int paid,int qty,int owned,int max,Cell[] sb,Cell[] sa,Cell[] bb,Cell[] ba,Cell[] tb,Cell[] ta,out PaidCustodyPlan plan){plan=null;try{if(!Guid.TryParseExact(request,"N",out var r)||r==Guid.Empty||r.ToString("N")!=request||!Guid.TryParseExact(world,"N",out var w)||w==Guid.Empty||w.ToString("N")!=world||!Id(station)||!Id(job)||!Id(recipient)||!Id(creation)||!Id(ledger)||revision<0||revision==long.MaxValue||qty<1||qty>65535||paid<qty||max<1||max>65535)return false;int budget=8*1024*1024;if(!Cells(sb,1,255,ref budget)||!Cells(sa,1,255,ref budget)||!Cells(bb,52,169,ref budget)||!Cells(ba,52,169,ref budget)||!Cells(tb,4,20,ref budget)||!Cells(ta,4,20,ref budget)||sb.Length!=sa.Length||bb.Length!=ba.Length||tb.Length!=ta.Length||source<0||source>=sb.Length||owned<4||owned>18||owned>tb.Length||paid>sb[source].Count)return false;
 if(!RebirthGearEncodedSnapshot.TryCopy(Enc(bb),Enc(tb),owned,out _,out _)||!RebirthGearEncodedSnapshot.TryCopy(Enc(ba),Enc(ta),owned,out _,out _))return false;
 var key=sb[source].Image;for(int i=0;i<sb.Length;i++){var expected=i==source?new Cell(sb[i].Count==qty?"":key,sb[i].Count-qty):sb[i];if(sa[i]!=expected)return false;}
 long added=0;for(int group=0;group<2;group++){var before=group==0?bb:tb;var after=group==0?ba:ta;for(int i=0;i<before.Length;i++){var b=before[i];var a=after[i];if(a==b)continue;if(group==1&&i>=owned)return false;if(a.Image!=key||a.Count<=b.Count||a.Count>max||b.Count>0&&b.Image!=key)return false;added+=(long)a.Count-b.Count;}}if(added!=qty)return false;
 var totals=new Dictionary<string,long>(StringComparer.Ordinal);foreach(var pair in new[]{(sb,1),(bb,1),(tb,1),(sa,-1),(ba,-1),(ta,-1)})foreach(var c in pair.Item1)if(c.Count>0)totals[c.Image]=totals.GetValueOrDefault(c.Image)+(long)pair.Item2*c.Count;if(totals.Values.Any(x=>x!=0))return false;
 var candidate=new PaidCustodyPlan(request,station,job,world,recipient,creation,ledger,revision,source,paid,qty,owned,max,(Cell[])sb.Clone(),(Cell[])sa.Clone(),(Cell[])bb.Clone(),(Cell[])ba.Clone(),(Cell[])tb.Clone(),(Cell[])ta.Clone());if(Encoding.UTF8.GetByteCount(candidate.Serialize())>8*1024*1024)return false;plan=candidate;return true;}catch{return false;}}
 public XElement Write(){XElement Grid(string name,Cell[] a)=>new(name,a.Select(c=>new XElement("cell",new XAttribute("count",c.Count),new XAttribute("image",c.Image))));return new XElement("paidCustodyPlan",new XAttribute("schema",1),new XAttribute("request",Request),new XAttribute("station",Station),new XAttribute("job",Job),new XAttribute("world",World),new XAttribute("recipient",Recipient),new XAttribute("creation",Creation),new XAttribute("ledger",Ledger),new XAttribute("revision",Revision),new XAttribute("source",Source),new XAttribute("paid",PaidBefore),new XAttribute("quantity",Quantity),new XAttribute("owned",Owned),new XAttribute("maximum",Maximum),Grid("stationBefore",sb),Grid("stationAfter",sa),Grid("bagBefore",bb),Grid("bagAfter",ba),Grid("beltBefore",tb),Grid("beltAfter",ta));}
 public string Serialize()=>Write().ToString(SaveOptions.DisableFormatting);
 public bool Same(PaidCustodyPlan other)=>other!=null&&XNode.DeepEquals(Write(),other.Write());
  static long ReadLong(string value){if(value==null||value.Length<1||value.Length>19||value.Any(c=>c<'0'||c>'9')||!long.TryParse(value,NumberStyles.None,CultureInfo.InvariantCulture,out var number)||number.ToString(CultureInfo.InvariantCulture)!=value)throw new FormatException("Noncanonical decimal");return number;}
 static int ReadInt(string value){long number=ReadLong(value);if(number>int.MaxValue)throw new FormatException("Integer overflow");return (int)number;}
 // Complete streaming pass before XElement allocation. Declaration optional; all other extra content refused.
 static bool Preflight(string raw){if(raw==null||raw.Length>8*1024*1024||Encoding.UTF8.GetByteCount(raw)>8*1024*1024)return false;using var r=XmlReader.Create(new StringReader(raw),new XmlReaderSettings{DtdProcessing=DtdProcessing.Prohibit,XmlResolver=null,MaxCharactersInDocument=8*1024*1024,IgnoreWhitespace=true});int nodes=0,roots=0;bool declaration=false;while(r.Read()){if(++nodes>2048||r.Depth>2)return false;switch(r.NodeType){case XmlNodeType.Element:if(r.Depth==0&&++roots>1)return false;break;case XmlNodeType.EndElement:break;case XmlNodeType.XmlDeclaration:if(declaration||roots!=0)return false;declaration=true;break;default:return false;}}return roots==1;}
 public static bool TryRead(string raw,out PaidCustodyPlan plan){plan=null;try{if(!Preflight(raw))return false;using var reader=XmlReader.Create(new StringReader(raw),new XmlReaderSettings{DtdProcessing=DtdProcessing.Prohibit,XmlResolver=null,MaxCharactersInDocument=8*1024*1024,IgnoreWhitespace=true});var root=XElement.Load(reader);if(root.Name!="paidCustodyPlan"||root.DescendantsAndSelf().Any(x=>x.Name.Namespace!=XNamespace.None)||root.DescendantNodes().Any(n=>n is not XElement)||root.Attributes().Any(a=>a.Name.Namespace!=XNamespace.None))return false;var names=new[]{"schema","request","station","job","world","recipient","creation","ledger","revision","source","paid","quantity","owned","maximum"};if(root.Attributes().Count()!=names.Length||root.Attributes().Any(a=>!names.Contains(a.Name.LocalName))||(string)root.Attribute("schema")!="1")return false;var grids=new[]{"stationBefore","stationAfter","bagBefore","bagAfter","beltBefore","beltAfter"};if(root.Elements().Count()!=6||!root.Elements().Select(x=>x.Name.LocalName).SequenceEqual(grids))return false;var values=new List<Cell[]>();foreach(var grid in root.Elements()){if(grid.HasAttributes||grid.Elements().Count()>255)return false;var cells=new List<Cell>();foreach(var c in grid.Elements()){if(c.Name!="cell"||c.HasElements||c.Nodes().Any()||c.Attributes().Count()!=2||c.Attributes().Any(a=>a.Name!="count"&&a.Name!="image"))return false;cells.Add(new((string)c.Attribute("image"),ReadInt((string)c.Attribute("count"))));}values.Add(cells.ToArray());}string A(string n)=>(string)root.Attribute(n);return TryCreate(A("request"),A("station"),A("job"),A("world"),A("recipient"),A("creation"),A("ledger"),ReadLong(A("revision")),ReadInt(A("source")),ReadInt(A("paid")),ReadInt(A("quantity")),ReadInt(A("owned")),ReadInt(A("maximum")),values[0],values[1],values[2],values[3],values[4],values[5],out plan);}catch{return false;}}
}





