import {readFile,readdir,writeFile} from 'node:fs/promises';import {join} from 'node:path';
async function files(root){let output=[];for(const e of await readdir(root,{withFileTypes:true})){const p=join(root,e.name);if(e.isDirectory())output.push(...await files(p));else if(p.endsWith('.cs'))output.push(p);}return output;}
const xml=await readFile('Config/_Survivor/theory_insights.xml','utf8');
const attrs=x=>Object.fromEntries([...x.matchAll(/([a-z_]+)="([^"]*)"/g)].map(m=>[m[1],m[2]]));
const definitions=[...xml.matchAll(/<insight\s+([^>]+?)\s*\/?\s*>/g)].map(m=>attrs(m[1]));
const calls=[],oneTimeCalls=[],prefixUses=[];
for(const path of await files('Scripts')){const text=await readFile(path,'utf8');for(const m of text.matchAll(/TryAwardInsight\s*\(\s*[^,]+,\s*"([^"]+)"/g))calls.push({id:m[1],path:path.replaceAll('\\','/'),line:text.slice(0,m.index).split('\n').length});for(const m of text.matchAll(/TryAwardOneTimeTheory\s*\(/g))oneTimeCalls.push({path:path.replaceAll('\\','/'),line:text.slice(0,m.index).split('\n').length});if(text.includes('InsightMarkerPrefix')||text.includes('theory.insight.'))prefixUses.push(path.replaceAll('\\','/'));}
const ids=new Set(calls.map(c=>c.id)),subjects=new Set(definitions.filter(d=>ids.has(d.id)).map(d=>d.skill_id));
const report={scope:'Static actual-source finite Insight earnability audit. Connected callers are not live execution proof. Literature, solo reflection and specialist Theory routes do not imply finite Insight marker completion.',configured:definitions.length,subjects:new Set(definitions.map(d=>d.skill_id)).size,knownProducerIds:ids.size,knownProducerSubjects:subjects.size,unconnectedDefinitions:definitions.filter(d=>!ids.has(d.id)),callSites:calls,oneTimeTheoryDeclarationAndCalls:oneTimeCalls,insightMarkerPrefixUses:prefixUses,dynamicAudit:{oneTimeTheoryMutationCaller:'TryAwardInsight only; other occurrence is declaration',triggerFamily:'Loaded as catalog metadata/default source description; no family dispatcher found',catalogQueries:'GetInsightsForSkill/GetEarnedInsights are read-only; no award route',otherTheoryRoutes:'Literature/solo/specialist/peer learning modify Theory through their own study outcomes and do not write finite Insight markers'}};
if(report.configured!==144||report.subjects!==48||report.knownProducerIds!==5||calls.length!==7)throw Error('Actual current inventory changed: '+JSON.stringify({configured:report.configured,subjects:report.subjects,ids:report.knownProducerIds,calls:calls.length}));
await writeFile('_Documentation/TheorySoloParallel/INSIGHT_EARNABILITY_AUDIT_20261006.json',JSON.stringify(report,null,2)+'\n');
console.log(`Finite Insight source audit: ${report.configured}/${report.subjects} configured; ${report.knownProducerIds} IDs/${report.knownProducerSubjects} subjects with known callers; ${report.unconnectedDefinitions.length} unconnected definitions; ${48-report.knownProducerSubjects} subjects without known finite producer.`);