using System;using UnityEngine;
class Rule{public string Family;}class EntityClass{public bool bIsEnemyEntity=true;}class ItemValue{public bool Empty;public bool IsEmpty()=>Empty;}class DamageSource{public ItemValue AttackingItem=new ItemValue();public object BuffClass;public int Actor=7;public int getEntityId()=>Actor;}struct DamageResponse{public DamageSource Source;public bool Fatal;}
static class RebirthComplexSkillSystemService{public static bool Device;public static bool IsRemoteOwnedDeviceSource(World w,DamageSource s)=>Device;}static class RebirthProgressionRuntimeConfig{public static string ClassifyCombat(ItemValue i)=>"skill.clubs";}
class Check{static int n;static World w;static EntityPlayer p;static EntityAlive target;static DamageSource source;static void Assert(bool b,string msg){if(!b)throw new Exception(msg);n++;}
static void Setup(){Time.realtimeSinceStartup=0;w=new World();p=new EntityPlayerLocal{entityId=7,world=w};target=new EntityAlive{entityId=8,world=w};w.Player=p;w.Enemy=target;GameManager.Instance.World=w;SingletonMonoBehaviour<ConnectionManager>.Instance=new ConnectionManager();RebirthWorldCharacterRepository.Record=new RebirthWorldCharacterRecord();RebirthWorldCharacterRepository.Fail=null;RebirthWorldCharacterRepository.ThrowAfter=false;RebirthWorldCharacterRepository.Saved=null;RebirthComplexSkillSystemService.Device=false;source=new DamageSource();}
static RebirthTheorySoloState Solo=>RebirthWorldCharacterRepository.Record.Progression.SoloTheory;
static RebirthTheorySoloCombatService.Witness Capture()=>RebirthTheorySoloCombatService.Before(target,source);
static void Kill(RebirthTheorySoloCombatService.Witness witness,bool ran=true){target.Health=0;var response=new DamageResponse{Source=source,Fatal=true};var commit=RebirthTheorySoloCombatService.BeforeKill(target,response);target.Dead=true;target.bDead=true;target.entityThatKilledMe=p;RebirthTheorySoloCombatService.AfterKill(commit,true);RebirthTheorySoloCombatService.After(witness,target,response,ran);}
static void Main(){Setup();var original=Capture();Assert(original!=null&&Solo==null,"capture is not evidence");Kill(original);Assert(Solo.Evidence==1&&Solo.CombatOriginal.Issued==1&&Solo.CombatOriginal.Pending.Count==0,"original server death acknowledged and retired");Kill(original);Assert(Solo.Evidence==1,"original witness cannot replay");Assert(Capture()==null,"dead target cannot recapture");
Setup();original=Capture();Kill(original,false);Assert(Solo==null,"suppressed original refuses");
Setup();original=Capture();RebirthTheorySoloCombatService.After(original,target,new DamageResponse{Source=source,Fatal=true},true);Assert(Solo==null,"fatal response alone refuses");
Setup();original=Capture();source=new DamageSource();Kill(original);Assert(Solo==null,"foreign damage source refuses");
Setup();original=Capture();source.AttackingItem=new ItemValue();Kill(original);Assert(Solo==null,"replaced original item refuses");
Setup();original=Capture();w.worldState=new object();Kill(original);Assert(Solo==null,"replaced original world refuses");
Setup();original=Capture();RebirthWorldCharacterRepository.Record.Origin.CreationId="changed";Kill(original);Assert(Solo==null,"changed original creation refuses");
Setup();original=Capture();w.Enemy=new EntityAlive{entityId=8,world=w};Kill(original);Assert(Solo==null,"reused target ID refuses");
Setup();source.BuffClass=new object();Assert(Capture()==null,"buff kill not direct weapon outcome");source.BuffClass=null;RebirthComplexSkillSystemService.Device=true;Assert(Capture()==null,"unqualified device authority refuses");
Setup();original=Capture();var nested=Capture();Kill(nested);Kill(original);Assert(Solo.Evidence==1,"nested native death witnesses acknowledge only once");
Setup();original=Capture();RebirthTheorySoloCombatService.Unknown(original,new Exception());Kill(original);Assert(Solo==null,"exception refuses uncertain native result");
Setup();original=Capture();RebirthWorldCharacterRepository.Fail="solo-theory-combat-original-evidence";Kill(original);Assert(Solo.Evidence==1&&Solo.CombatOriginal.Pending.Count==1,"uncertain evidence save retains exact original");RebirthWorldCharacterRepository.Fail=null;Time.realtimeSinceStartup=10;ModEvents.Tick();Assert(Solo.Evidence==1&&Solo.CombatOriginal.Pending.Count==0,"retry once original evidence");
Setup();original=Capture();RebirthWorldCharacterRepository.Fail="solo-theory-combat-original-retired";Kill(original);Assert(Solo.Evidence==1&&Solo.CombatOriginal.Pending.Count==0,"retirement uncertain phase retains original without replay");RebirthWorldCharacterRepository.Fail=null;Time.realtimeSinceStartup=20;ModEvents.Tick();Assert(RebirthWorldCharacterRepository.HasSavedSoloCombatOriginal(RebirthSkillAwardService.Owner,Solo)&&Solo.Evidence==1,"retirement exact finalfile retry");
Setup();original=Capture();RebirthWorldCharacterRepository.Fail="solo-theory-combat-original-evidence";Kill(original);var old=Solo;Setup();RebirthWorldCharacterRepository.Record.Progression.SoloTheory=new RebirthTheorySoloState{CreationId="creation",Evidence=old.Evidence,CombatOriginal=old.CombatOriginal.Clone()};original=Capture();Kill(original);Assert(Solo.Evidence==2&&Solo.CombatOriginal.Pending.Count==0&&Solo.CombatOriginal.Issued==2,"saved predecessor generation retires without granting again");
Setup();var full=new RebirthTheorySoloState{CreationId="creation",Evidence=128,CombatOriginal=new RebirthTheorySoloCombatLedger()};for(int i=0;i<128;i++){var a=full.CombatOriginal.Reserve(Guid.NewGuid().ToString("N"),Guid.NewGuid().ToString("N"),"creation","skill.clubs","weapon_continuous",7,8,300,50);full.CombatOriginal.MarkEvidence(a.Ordinal,a.Id,out _);}RebirthWorldCharacterRepository.Record.Progression.SoloTheory=full;original=Capture();Kill(original);Assert(Solo.Evidence==129&&Solo.CombatOriginal.Issued==129&&Solo.CombatOriginal.Pending.Count==0,"saturated saved acknowledged journal retired before reserve");
Setup();full=new RebirthTheorySoloState{CreationId="creation",Evidence=128,CombatOriginal=new RebirthTheorySoloCombatLedger()};for(int i=0;i<128;i++){var a=full.CombatOriginal.Reserve(Guid.NewGuid().ToString("N"),Guid.NewGuid().ToString("N"),"creation","skill.clubs","weapon_continuous",7,8,300,50);full.CombatOriginal.MarkEvidence(a.Ordinal,a.Id,out _);}RebirthWorldCharacterRepository.Record.Progression.SoloTheory=full;RebirthWorldCharacterRepository.Fail="solo-theory-combat-original-predecessors";original=Capture();Kill(original);Assert(Solo.Evidence==128&&Solo.CombatOriginal.Issued==128&&Solo.CombatOriginal.Pending.Count==128,"unproved predecessor snapshot cannot retire or reserve");RebirthWorldCharacterRepository.Fail=null;Time.realtimeSinceStartup=100;ModEvents.Tick();Assert(Solo.Evidence==129&&Solo.CombatOriginal.Issued==129,"retained original native death resumes after saved predecessor proof");
Setup();full=new RebirthTheorySoloState{CreationId="creation",Evidence=128,CombatOriginal=new RebirthTheorySoloCombatLedger()};for(int i=0;i<128;i++){var a=full.CombatOriginal.Reserve(Guid.NewGuid().ToString("N"),Guid.NewGuid().ToString("N"),"creation","skill.clubs","weapon_continuous",7,8,300,50);full.CombatOriginal.MarkEvidence(a.Ordinal,a.Id,out _);}RebirthWorldCharacterRepository.Record.Progression.SoloTheory=full;RebirthWorldCharacterRepository.Fail="solo-theory-combat-original-predecessors-retired";original=Capture();Kill(original);Assert(Solo.Evidence==128&&Solo.CombatOriginal.Issued==128&&Solo.CombatOriginal.Pending.Count==0,"unknown predecessor retirement holds native original before reserve");target=new EntityAlive{world=w,entityId=9};w.Enemy=target;source=new DamageSource();var second=Capture();Kill(second);Assert(Solo.CombatOriginal.Issued==128&&Solo.Evidence==128,"other native death cannot bypass predecessor retirement hold");RebirthWorldCharacterRepository.Fail=null;Time.realtimeSinceStartup=200;ModEvents.Tick();Assert(Solo.CombatOriginal.Issued==130&&Solo.Evidence==130&&Solo.CombatOriginal.Pending.Count==0,"both exact originals resume once after known retirement");
Setup();original=Capture();target.Health=0;target.Dead=true;target.entityThatKilledMe=p;RebirthTheorySoloCombatService.After(original,target,new DamageResponse{Source=source,Fatal=true},true);Assert(Solo==null,"outer fatal postimage without original Kill commit refused");
Setup();original=Capture();target.Health=0;var foreign=new DamageSource();var wrongCommit=RebirthTheorySoloCombatService.BeforeKill(target,new DamageResponse{Source=foreign,Fatal=true});target.Dead=true;target.bDead=true;target.entityThatKilledMe=p;RebirthTheorySoloCombatService.AfterKill(wrongCommit,true);RebirthTheorySoloCombatService.After(original,target,new DamageResponse{Source=source,Fatal=true},true);Assert(Solo==null,"nested foreign native death cannot credit outer attack");
Setup();original=Capture();target.Health=0;var suppressed=RebirthTheorySoloCombatService.BeforeKill(target,new DamageResponse{Source=source,Fatal=true});target.Dead=true;target.bDead=true;target.entityThatKilledMe=p;RebirthTheorySoloCombatService.AfterKill(suppressed,false);RebirthTheorySoloCombatService.After(original,target,new DamageResponse{Source=source,Fatal=true},true);Assert(Solo==null,"suppressed native Kill refuses");
Setup();original=Capture();target.Health=0;var falseDead=RebirthTheorySoloCombatService.BeforeKill(target,new DamageResponse{Source=source,Fatal=true});target.RecordedFatal=true;target.entityThatKilledMe=p;RebirthTheorySoloCombatService.AfterKill(falseDead,true);RebirthTheorySoloCombatService.After(original,target,new DamageResponse{Source=source,Fatal=true},true);Assert(target.IsDead()&&!target.bDead&&Solo==null,"suppressed SetDead with recorded Fatal cannot prove native death");
Setup();original=Capture();target.Health=0;target.RecordedFatal=true;var flagged=RebirthTheorySoloCombatService.BeforeKill(target,new DamageResponse{Source=source,Fatal=true});Assert(flagged!=null,"original Kill exclusion uses actual bDead separately from RecordedFatal");target.bDead=true;target.entityThatKilledMe=p;RebirthTheorySoloCombatService.AfterKill(flagged,true);RebirthTheorySoloCombatService.After(original,target,new DamageResponse{Source=source,Fatal=true},true);Assert(Solo.Evidence==1,"actual native SetDead flag plus original Kill proves death");
Console.WriteLine(n+" PASS whole original server combat service (native/file adapters)");}}
