using System;using System.Reflection;
namespace HarmonyLib{}
class EntityAlive{public int Health=100;public bool IsDead()=>false;public void Kill(DamageResponse r){}public void ProcessDamageResponse(DamageResponse r){}}
class DamageSource{}struct DamageResponse{}class NetPackageDamageEntity{public void ProcessPackage(World w,GameManager g){}}class World{}class GameManager{}
static class Fault{public static bool Before,After,Unknown;public static void Hit(bool fail){if(fail)throw new InvalidOperationException("observer-only fault");}}
static class RebirthTheorySoloCombatService{public class Witness{}public class KillCommit{}public static Witness Before(EntityAlive e,DamageSource s){Fault.Hit(Fault.Before);return new Witness();}public static void After(Witness w,EntityAlive e,DamageResponse r,bool ran){Fault.Hit(Fault.After);}public static void Unknown(Witness w,Exception ex){Fault.Hit(Fault.Unknown);}public static KillCommit BeforeKill(EntityAlive e,DamageResponse r){Fault.Hit(Fault.Before);return new KillCommit();}public static void AfterKill(KillCommit c,bool ran){Fault.Hit(Fault.After);}public static void UnknownKill(KillCommit c,Exception ex){Fault.Hit(Fault.Unknown);}}
static class RebirthTheorySoloPeerCombatService{public class Scope{}public class Core{}public static Scope BeforePackage(NetPackageDamageEntity p,World w,GameManager g){Fault.Hit(Fault.Before);return new Scope();}public static Core BeforeCore(EntityAlive e,DamageResponse r){Fault.Hit(Fault.Before);return new Core();}public static void AfterCore(Core c,bool ran){Fault.Hit(Fault.After);}public static void AfterPackage(Scope s,bool ran){Fault.Hit(Fault.After);}public static void UnknownCore(Core c,Exception ex){Fault.Hit(Fault.Unknown);}public static void UnknownPackage(Scope s,Exception ex){Fault.Hit(Fault.Unknown);}}
static class RebirthStealthTrainingService{public static bool IsPreHitStealthQualified(EntityAlive e,DamageSource s)=>false;}static class RebirthStatisticsService{public static int Calls;public static void RecordDamage(EntityAlive e,DamageResponse r,DamageSource s,int strength,float actual,float extra){Calls++;}}static class RebirthSkillEventRouter{public static int Calls;public static void OnCombatDamageCompleted(EntityAlive e,DamageResponse r,float actual,bool stealth,int health){Calls++;}}
class Check{static int n,originals;static MethodInfo Method(Type t,string name)=>t.GetMethod(name,BindingFlags.NonPublic|BindingFlags.Static);static void Assert(bool b,string s){if(!b)throw new Exception(s);n++;}
static void Test(Type hook,int kind){for(int mode=0;mode<4;mode++){Fault.Before=mode==1;Fault.After=mode==2;Fault.Unknown=mode>=2;var e=new EntityAlive();object[] prefix=kind==0?new object[]{new NetPackageDamageEntity(),new World(),new GameManager(),null}:kind==3?new object[]{e,new DamageSource(),10,null}:new object[]{e,new DamageResponse(),null};Method(hook,"Prefix").Invoke(null,prefix);originals++;var state=prefix[prefix.Length-1];object[] post=kind==3?new object[]{e,new DamageResponse(),state,true}:new object[]{state,true};Method(hook,"Postfix").Invoke(null,post);var native=mode==3?new ApplicationException("original-native-exception"):null;var returned=Method(hook,"Finalizer").Invoke(null,new object[]{native,state});Assert(ReferenceEquals(returned,native),"exact native exception preserved");}Assert(originals>0,"observer faults cannot prevent original execution");}
static void Main(){Test(typeof(RebirthTheorySoloPeerCombatPacketPatch),0);Test(typeof(RebirthTheorySoloPeerCombatCorePatch),1);Test(typeof(RebirthTheorySoloCombatKillPatch),2);Test(typeof(RebirthSurvivorCombatSkillPatch),3);Assert(originals==16,"all native original continuations reached");Assert(RebirthStatisticsService.Calls==4&&RebirthSkillEventRouter.Calls==4,"existing statistics and practice unaffected by observer faults");Console.WriteLine(n+" PASS extracted actual combat hook observer-fault boundaries");}}
