using System;using System.Collections.Generic;using System.Xml.Linq;using UnityEngine;
namespace UnityEngine{public struct Vector3{public float x,y,z;public float sqrMagnitude=>x*x+y*y+z*z;public static Vector3 operator-(Vector3 a,Vector3 b)=>new Vector3{x=a.x-b.x,y=a.y-b.y,z=a.z-b.z};}public static class Time{public static float realtimeSinceStartup;}public static class Mathf{public static float Max(float a,float b)=>Math.Max(a,b);public static float Min(float a,float b)=>Math.Min(a,b);}}
struct Vector3i{public int x,y,z;public Vector3i(int a,int b,int c){x=a;y=b;z=c;}public Vector3 ToVector3()=>new Vector3{x=x,y=y,z=z};}
struct BlockValue{public uint rawData;public int damage;public int rotation{get=>0;set{}}public int meta{get=>0;set{}}public bool isair=>rawData==0;}
class TEFeatureAbs{public object Parent=new object();public bool IsSharedLock(ushort c)=>false;public Vector3i ToWorldPos()=>new Vector3i();}class TEFeatureLockPickable:TEFeatureAbs{public BlockValue lockpickDowngradeBlock=new BlockValue{rawData=2};}
class EntityPlayer{public World world;public int entityId=7;public Vector3 position;public bool Dead;public bool IsDead()=>Dead;}class EntityPlayerLocal:EntityPlayer{}
class World{public object worldState=new object(),Tile;public EntityPlayer Player;public BlockValue Block=new BlockValue{rawData=1};public bool Remote;public bool IsRemote()=>Remote;public object GetTileEntity(Vector3i p)=>Tile;public BlockValue GetBlock(Vector3i p)=>Block;public EntityPlayer GetEntity(int id)=>id==Player.entityId?Player:null;public EntityPlayer GetPrimaryPlayer()=>Player;}
class GameManager{public static GameManager Instance=new GameManager();public World World;}
class PlatformUserIdentifierAbs{}class InternalIdentifier{public string CombinedString="owner";}class ClientInfo{public int entityId=7;public bool disconnecting,loginDone=true,bAttachedToEntity=true;public InternalIdentifier InternalId=new InternalIdentifier();}
class Clients{public ClientInfo Peer;public ClientInfo ForEntityId(int id)=>Peer;}class ConnectionManager{public bool IsServer=true;public Clients Clients=new Clients();}class SingletonMonoBehaviour<T>{public static T Instance;}
class LockManager{public static LockManager Instance=new LockManager();public Guard singleLocks=new Guard();public struct LockEntry{public object Target;public ushort Channel;public LockEntry(object t,ushort c){Target=t;Channel=c;}}}class Guard{public object Target;public int Owner=7;public bool TryGetByValue(LockManager.LockEntry e,out int id){id=Owner;return ReferenceEquals(Target,e.Target)&&e.Channel==3;}}
class TimerEventData{public object Data;public float Completion;}class XUiC_Timer{public TimerEventData eventData;}
class BlockReference{public Vector3i Position;public bool TryGetBlockPos(out Vector3i p){p=Position;return true;}}class BlockChangeInfo{public bool bChangeBlockValue=true;public BlockValue blockValue=new BlockValue{rawData=2};public BlockReference blockValueRef=new BlockReference();}
class NetPackageSetBlock{public ClientInfo Sender;public int localPlayerThatChanged=7;public PlatformUserIdentifierAbs persistentPlayerId=new PlatformUserIdentifierAbs();public List<BlockChangeInfo> blockChanges=new List<BlockChangeInfo>{new BlockChangeInfo()};public bool Auth=true;public bool ValidEntityIdForSender(int id)=>Auth;public bool ValidUserIdForSender(PlatformUserIdentifierAbs id)=>Auth;}
static class ThreadManager{public static bool IsMainThread()=>true;}static class RebirthSurvivorMode{public static bool IsEnabledForCurrentWorld()=>true;}
class RebirthStablePlayerIdentity{public string StorageKey="key",CanonicalId="owner";}class Origin{public string CreationId="creation";}class Condition{public float ActivePlaySeconds=100;}class RebirthWorldProgressionState{public RebirthTheorySoloState SoloTheory;}class RebirthWorldCharacterRecord{public Origin Origin=new Origin();public Condition Condition=new Condition();public RebirthWorldProgressionState Progression=new RebirthWorldProgressionState();public void Touch(string s){}}
class RebirthTheorySoloState{public string CreationId;public RebirthTheorySoloLockpickLedger LockpickOriginal;public int Evidence;public static bool Text(string s,int n)=>!string.IsNullOrEmpty(s)&&s.Length<=n;public void RecordAcknowledged(string s,string f,string id,float d,float a){Evidence++;}public XElement Write()=>new XElement("solo",new XAttribute("creation",CreationId),new XAttribute("evidence",Evidence),LockpickOriginal?.Write(CreationId));}
static class RebirthTheorySoloRegistry{public static bool TryLockpickDifficulty(float s,out float d){d=50;return s>0&&!float.IsNaN(s);}}
static class RebirthSkillKnowledgeService{public static readonly object SyncRoot=new object();}
static class RebirthSkillAwardService{public static RebirthStablePlayerIdentity Owner=new RebirthStablePlayerIdentity();public static bool TryGetEligible(EntityPlayer p,out RebirthStablePlayerIdentity o,out RebirthWorldCharacterRecord r){o=Owner;r=RebirthWorldCharacterRepository.Record;return p==GameManager.Instance.World.Player;}public static void QueueOwnerPublication(EntityPlayer p){}}
static class RebirthWorldCharacterRepository{public static bool IsServerAuthority=true;public static RebirthWorldCharacterRecord Record;public static XElement Saved;public static string Fail;public static bool ThrowAfter;public static bool IsCurrentCachedRecord(RebirthWorldCharacterRecord r)=>ReferenceEquals(r,Record);public static bool SaveIfDirty(RebirthStablePlayerIdentity o,string reason){if(Fail==reason)return false;Saved=Record.Progression.SoloTheory.Write();if(ThrowAfter&&reason=="solo-theory-lockpick-original-completed")throw new Exception("save return unknown");return true;}public static bool HasSavedSoloLockpickOriginal(RebirthStablePlayerIdentity o,RebirthTheorySoloState s)=>XNode.DeepEquals(Saved,s.Write());}
static class ModEvents{public struct SGameUpdateData{}public delegate void Handler(ref SGameUpdateData d);public static class GameUpdate{public static Handler Callback;public static void RegisterHandler(Handler h){Callback=h;}}public static void Tick(){var d=new SGameUpdateData();GameUpdate.Callback?.Invoke(ref d);}}
class Check{static int n;static World w;static TEFeatureLockPickable f;static EntityPlayer p;static void Assert(bool b,string s){if(!b)throw new Exception(s);n++;}
static void Setup(bool remote=false){Time.realtimeSinceStartup=0;w=new World();p=remote?new EntityPlayer():new EntityPlayerLocal();p.world=w;w.Player=p;f=new TEFeatureLockPickable();w.Tile=f.Parent;GameManager.Instance.World=w;SingletonMonoBehaviour<ConnectionManager>.Instance=new ConnectionManager();if(remote)SingletonMonoBehaviour<ConnectionManager>.Instance.Clients.Peer=new ClientInfo();LockManager.Instance.singleLocks.Target=f;RebirthWorldCharacterRepository.Record=new RebirthWorldCharacterRecord();RebirthWorldCharacterRepository.Saved=null;RebirthWorldCharacterRepository.Fail=null;RebirthWorldCharacterRepository.ThrowAfter=false;RebirthTheorySoloLockpickService.Grant(f,p,3,15,15,15);Time.realtimeSinceStartup=15;}
static RebirthTheorySoloState Solo=>RebirthWorldCharacterRepository.Record.Progression.SoloTheory;
static TimerEventData Timer(){var t=new TimerEventData{Data=p,Completion=1};var setup=RebirthTheorySoloLockpickService.BeforeShowUi(f,true);RebirthTheorySoloLockpickService.CaptureTimer(new XUiC_Timer{eventData=t},t,15,true);RebirthTheorySoloLockpickService.AfterShowUi(setup,true);return t;}
static void Apply(RebirthTheorySoloLockpickService.Transition t,object source,bool native=true){var rows=source is NetPackageSetBlock pkg?pkg.blockChanges:new List<BlockChangeInfo>{new BlockChangeInfo()};var user=source is NetPackageSetBlock pk?pk.persistentPlayerId:null;var c=RebirthTheorySoloLockpickService.BeforeCommit(GameManager.Instance,user,rows);Assert(c==t,"nested original capture");w.Block=new BlockValue{rawData=2};RebirthTheorySoloLockpickService.AfterCommit(c,native);RebirthTheorySoloLockpickService.After(t,source,true);}
static void Main(){Setup();Assert(Solo.Evidence==0&&Solo.LockpickOriginal.Active!=null,"grant is no work");var timer=Timer();var t=RebirthTheorySoloLockpickService.BeforeLocal(f,timer);Assert(t!=null,"canonical completed timer");RebirthTheorySoloLockpickService.Release(f,7,3,true);Apply(t,timer);Assert(Solo.Evidence==1&&Solo.LockpickOriginal.Active==null,"host original completed once");RebirthTheorySoloLockpickService.After(t,timer,true);Assert(Solo.Evidence==1,"same callback replay");
Setup();timer=new TimerEventData{Data=p,Completion=1};Assert(RebirthTheorySoloLockpickService.BeforeLocal(f,timer)==null,"invented timer refused");timer=Timer();timer.Completion=.5f;Assert(RebirthTheorySoloLockpickService.BeforeLocal(f,timer)==null,"unfinished timer refused");timer.Completion=1;Time.realtimeSinceStartup=1;Assert(RebirthTheorySoloLockpickService.BeforeLocal(f,timer)==null,"early timer refused");
Setup(true);var pkg=new NetPackageSetBlock{Sender=SingletonMonoBehaviour<ConnectionManager>.Instance.Clients.Peer};Assert(RebirthTheorySoloLockpickService.BeforeRemote(pkg,w,GameManager.Instance)==null,"release required");RebirthTheorySoloLockpickService.Release(f,7,3,true);pkg.Sender=new ClientInfo();Assert(RebirthTheorySoloLockpickService.BeforeRemote(pkg,w,GameManager.Instance)==null,"foreign sender refused");pkg.Sender=SingletonMonoBehaviour<ConnectionManager>.Instance.Clients.Peer;pkg.Auth=false;Assert(RebirthTheorySoloLockpickService.BeforeRemote(pkg,w,GameManager.Instance)==null,"native authentication required");pkg.Auth=true;t=RebirthTheorySoloLockpickService.BeforeRemote(pkg,w,GameManager.Instance);Assert(t!=null,"remote original transition");Assert(RebirthTheorySoloLockpickService.BeforeCommit(GameManager.Instance,pkg.persistentPlayerId,new List<BlockChangeInfo>(pkg.blockChanges))==null,"foreign list clone refused");Apply(t,pkg);Assert(Solo.Evidence==1,"remote original work");
Setup();timer=Timer();t=RebirthTheorySoloLockpickService.BeforeLocal(f,timer);RebirthTheorySoloLockpickService.Release(f,7,3,true);w.Block=new BlockValue{rawData=2};RebirthTheorySoloLockpickService.After(t,timer,true);Assert(Solo.Evidence==0,"postimage alone refused");
Setup();timer=Timer();t=RebirthTheorySoloLockpickService.BeforeLocal(f,timer);RebirthTheorySoloLockpickService.Release(f,7,3,true);Apply(t,timer,false);Assert(Solo.Evidence==0,"suppressed native commit refused");
Setup();timer=Timer();t=RebirthTheorySoloLockpickService.BeforeLocal(f,timer);RebirthTheorySoloLockpickService.Release(f,7,3,true);var rows=new List<BlockChangeInfo>{new BlockChangeInfo()};var commit=RebirthTheorySoloLockpickService.BeforeCommit(GameManager.Instance,null,rows);RebirthTheorySoloLockpickService.AfterCommit(commit,true);w.Block=new BlockValue{rawData=2};RebirthTheorySoloLockpickService.After(t,timer,true);Assert(Solo.Evidence==0,"queued later postimage refused");
Setup();timer=Timer();t=RebirthTheorySoloLockpickService.BeforeLocal(f,timer);RebirthTheorySoloLockpickService.Unknown(t,new Exception());RebirthTheorySoloLockpickService.Release(f,7,3,true);Assert(RebirthTheorySoloLockpickService.BeforeLocal(f,timer)==null&&Solo.Evidence==0,"native exception holds original");
Setup();timer=Timer();t=RebirthTheorySoloLockpickService.BeforeLocal(f,timer);RebirthTheorySoloLockpickService.Release(f,7,3,true);RebirthWorldCharacterRepository.Fail="solo-theory-lockpick-original-completed";Apply(t,timer);Assert(Solo.Evidence==1&&Solo.LockpickOriginal.Active.EvidenceAttempted,"unknown save retains attempt");RebirthWorldCharacterRepository.Fail=null;Time.realtimeSinceStartup=50;ModEvents.Tick();Assert(Solo.Evidence==1&&Solo.LockpickOriginal.Active==null,"save retry once");
Setup();timer=Timer();w.worldState=new object();Assert(RebirthTheorySoloLockpickService.BeforeLocal(f,timer)==null,"replaced native world lease");Setup(true);pkg=new NetPackageSetBlock{Sender=SingletonMonoBehaviour<ConnectionManager>.Instance.Clients.Peer};RebirthTheorySoloLockpickService.Release(f,7,3,true);SingletonMonoBehaviour<ConnectionManager>.Instance.Clients.Peer=new ClientInfo();Assert(RebirthTheorySoloLockpickService.BeforeRemote(pkg,w,GameManager.Instance)==null,"reconnected peer cannot reuse lease");
Setup();timer=Timer();RebirthWorldCharacterRepository.Record.Origin.CreationId="replacement";Assert(RebirthTheorySoloLockpickService.BeforeLocal(f,timer)==null,"replaced character creation refused");
Setup();timer=Timer();w.Block=new BlockValue{rawData=1,damage=1};Assert(RebirthTheorySoloLockpickService.BeforeLocal(f,timer)==null,"changed original damage refused");
Setup();timer=Timer();t=RebirthTheorySoloLockpickService.BeforeLocal(f,timer);RebirthTheorySoloLockpickService.Release(f,7,3,true);RebirthWorldCharacterRepository.Fail="solo-theory-lockpick-original-retired";Apply(t,timer);Assert(Solo.Evidence==1&&Solo.LockpickOriginal.Active==null,"uncertain retirement keeps evidence once");w.Block=new BlockValue{rawData=1};RebirthTheorySoloLockpickService.Grant(f,p,3,15,15,15);Assert(Solo.LockpickOriginal.Issued==1,"uncertain retirement blocks fresh grant");RebirthWorldCharacterRepository.Fail=null;Time.realtimeSinceStartup=60;ModEvents.Tick();RebirthTheorySoloLockpickService.After(t,timer,true);Assert(Solo.Evidence==1,"uncertain retirement cannot replay reward");Assert(RebirthWorldCharacterRepository.HasSavedSoloLockpickOriginal(RebirthSkillAwardService.Owner,Solo),"retirement retry saves exact final state");RebirthTheorySoloLockpickService.Grant(f,p,3,15,15,15);Assert(Solo.LockpickOriginal.Issued==2&&Solo.Evidence==1,"saved retirement permits next original grant");
Setup();timer=Timer();RebirthWorldCharacterRepository.Saved=null;RebirthWorldCharacterRepository.Fail="solo-theory-lockpick-original-prepare";Assert(RebirthTheorySoloLockpickService.BeforeLocal(f,timer)==null,"unproved original final file refused");
Setup();timer=Timer();t=RebirthTheorySoloLockpickService.BeforeLocal(f,timer);RebirthTheorySoloLockpickService.Release(f,7,3,true);RebirthWorldCharacterRepository.ThrowAfter=true;Apply(t,timer);Assert(Solo.Evidence==1&&Solo.LockpickOriginal.Active.EvidenceAttempted,"throw after file write retains original outcome");RebirthWorldCharacterRepository.ThrowAfter=false;Time.realtimeSinceStartup=100;ModEvents.Tick();Assert(Solo.Evidence==1&&Solo.LockpickOriginal.Active==null,"exact saved unknown outcome reconciles once");
Console.WriteLine(n+" PASS whole original native Lockpick service (native/file adapters)");}}
