using System;using System.Linq;using System.Collections.Generic;using UnityEngine;
namespace HarmonyLib{public class HarmonyPatch:Attribute{public HarmonyPatch(Type t,string n){}public HarmonyPatch(Type t,string n,Type[] a){}}}
class Rule{public string Family;}class EntityClass{public bool bIsEnemyEntity=true;}class Inventory{public ItemValue holdingItemItemValue;}
class TypedMetadataValue{public string Value;public override bool Equals(object other)=>other is TypedMetadataValue t&&t.Value==Value;public override int GetHashCode()=>Value?.GetHashCode()??0;}class Stat{}
class ItemValue{public int type=1,Meta;public float UseTimes;public ushort Seed=10,Quality=2;public byte SelectedAmmoTypeIndex;public bool Activated;public Stat[] Stats;public Dictionary<string,TypedMetadataValue> Metadata;public ItemValue[] modifications,cosmeticMods;public bool IsEmpty()=>type==0;public ItemValue Clone(){var c=(ItemValue)MemberwiseClone();c.Metadata=Metadata==null?null:Metadata.ToDictionary(p=>p.Key,p=>new TypedMetadataValue{Value=p.Value.Value});c.modifications=modifications?.Select(i=>i?.Clone()).ToArray();c.cosmeticMods=cosmeticMods?.Select(i=>i?.Clone()).ToArray();return c;}
// NATIVE_IDENTITY
}
class DamageSource{public ItemValue AttackingItem;public object BuffClass;public int Actor=7;public int getEntityId()=>Actor;}struct DamageResponse{public DamageSource Source;public bool Fatal;}
class NetPackageDamageEntity{public ClientInfo Sender;public int entityId=8,attackerEntityId=7;public ushort strength=100;public uint flags=16;public ItemValue attackingItem;public bool Auth=true;public bool ValidEntityIdForSender(int id)=>Auth&&id==Sender?.entityId;public void ProcessPackage(World w,GameManager g){}}
static class RebirthComplexSkillSystemService{public static bool IsRemoteOwnedDeviceSource(World w,DamageSource s)=>false;}static class RebirthProgressionRuntimeConfig{public static string ClassifyCombat(ItemValue i)=>"skill.clubs";}
class Check{static int n;static World w;static EntityPlayer p;static EntityAlive target;static NetPackageDamageEntity pkg;static void Assert(bool b,string m){if(!b)throw new Exception(m);n++;}
static void Setup(){Time.realtimeSinceStartup=0;w=new World();p=new EntityPlayer{entityId=7,world=w};p.inventory.holdingItemItemValue=new ItemValue();target=new EntityAlive{entityId=8,world=w};w.Player=p;w.Enemy=target;GameManager.Instance.World=w;SingletonMonoBehaviour<ConnectionManager>.Instance=new ConnectionManager();var peer=new ClientInfo();SingletonMonoBehaviour<ConnectionManager>.Instance.Clients.Peer=peer;RebirthWorldCharacterRepository.Record=new RebirthWorldCharacterRecord();RebirthWorldCharacterRepository.Fail=null;RebirthWorldCharacterRepository.ThrowAfter=false;RebirthWorldCharacterRepository.Saved=null;pkg=new NetPackageDamageEntity{Sender=peer,attackingItem=p.inventory.holdingItemItemValue.Clone()};}
static RebirthTheorySoloState Solo=>RebirthWorldCharacterRepository.Record.Progression.SoloTheory;
static RebirthTheorySoloPeerCombatService.Scope Begin()=>RebirthTheorySoloPeerCombatService.BeforePackage(pkg,w,GameManager.Instance);
static RebirthTheorySoloPeerCombatService.Core Core(bool fatal=true){var response=new DamageResponse{Source=new DamageSource{AttackingItem=pkg.attackingItem},Fatal=fatal};return RebirthTheorySoloPeerCombatService.BeforeCore(target,response);}
static void NativeKill(RebirthTheorySoloPeerCombatService.Core c,bool ran=true){target.Health=0;var commit=RebirthTheorySoloCombatService.BeforeKill(target,c.Response);target.Dead=true;target.bDead=true;target.entityThatKilledMe=p;RebirthTheorySoloCombatService.AfterKill(commit,ran);RebirthTheorySoloPeerCombatService.AfterCore(c,true);}
static void Main(){Setup();var scope=Begin();Assert(scope!=null,"authenticated original peer packet");var core=Core();Assert(core!=null,"exact nested original core");NativeKill(core);Assert(Solo==null,"core commit waits original package completion");RebirthTheorySoloPeerCombatService.AfterPackage(scope,true);Assert(Solo.Evidence==1&&Solo.CombatOriginal.Pending.Count==0,"native peer death acknowledged once");RebirthTheorySoloPeerCombatService.AfterPackage(scope,true);Assert(Solo.Evidence==1,"package replay refused");
Setup();pkg.Sender=new ClientInfo();Assert(Begin()==null,"foreign canonical sender refused");Setup();pkg.Auth=false;Assert(Begin()==null,"independent native sender auth required");Setup();pkg.attackerEntityId=9;Assert(Begin()==null,"foreign attacker refused");Setup();pkg.attackingItem.Seed=11;Assert(Begin()==null,"same type different native identity refused");Setup();p.inventory.holdingItemItemValue.Metadata=new Dictionary<string,TypedMetadataValue>{{"provenance",new TypedMetadataValue{Value="original"}}};pkg.attackingItem.Metadata=new Dictionary<string,TypedMetadataValue>{{"provenance",new TypedMetadataValue{Value="forged"}}};Assert(Begin()==null,"native metadata identity preserved");Setup();p.inventory.holdingItemItemValue.modifications=new[]{new ItemValue{Seed=20}};pkg.attackingItem.modifications=new[]{new ItemValue{Seed=21}};Assert(Begin()==null,"native modifications identity preserved");Setup();pkg.attackingItem.UseTimes=50;pkg.attackingItem.Meta=7;scope=Begin();Assert(scope!=null,"native identity excludes expected wear and ammo meta");RebirthTheorySoloPeerCombatService.AfterPackage(scope,false);
Setup();scope=Begin();core=Core();target.Health=0;target.Dead=true;target.entityThatKilledMe=p;RebirthTheorySoloPeerCombatService.AfterCore(core,true);RebirthTheorySoloPeerCombatService.AfterPackage(scope,true);Assert(Solo==null,"fatal packet and health postimage without Kill commit refused");
Setup();scope=Begin();core=Core();NativeKill(core,false);RebirthTheorySoloPeerCombatService.AfterPackage(scope,true);Assert(Solo==null,"suppressed Kill refuses packet credit");
Setup();scope=Begin();core=Core();NativeKill(core);RebirthTheorySoloPeerCombatService.AfterPackage(scope,false);Assert(Solo==null,"suppressed native package refuses committed core attribution");
Setup();scope=Begin();core=Core();NativeKill(core);RebirthTheorySoloPeerCombatService.UnknownPackage(scope,new Exception());Assert(Solo==null,"original packet exception refuses unknown completion");
Setup();scope=Begin();p.inventory.holdingItemItemValue=new ItemValue{Seed=30};Assert(Core()==null,"switched original held weapon refused");RebirthTheorySoloPeerCombatService.AfterPackage(scope,true);
Setup();scope=Begin();var r=new DamageResponse{Source=new DamageSource{AttackingItem=pkg.attackingItem.Clone()},Fatal=true};Assert(RebirthTheorySoloPeerCombatService.BeforeCore(target,r)==null,"foreign synthesized source item reference refused");RebirthTheorySoloPeerCombatService.AfterPackage(scope,true);
Setup();scope=Begin();w.worldState=new object();Assert(Core()==null,"replaced original world refused");RebirthTheorySoloPeerCombatService.AfterPackage(scope,true);
Setup();scope=Begin();RebirthWorldCharacterRepository.Record.Origin.CreationId="changed";Assert(Core()==null,"replaced character creation refused");RebirthTheorySoloPeerCombatService.AfterPackage(scope,true);
Setup();scope=Begin();SingletonMonoBehaviour<ConnectionManager>.Instance.Clients.Peer=new ClientInfo();Assert(Core()==null,"reconnected canonical peer cannot reuse original packet");RebirthTheorySoloPeerCombatService.AfterPackage(scope,true);
Setup();scope=Begin();core=Core();NativeKill(core);RebirthWorldCharacterRepository.Fail="solo-theory-combat-original-evidence";RebirthTheorySoloPeerCombatService.AfterPackage(scope,true);Assert(Solo.Evidence==1&&Solo.CombatOriginal.Pending.Count==1,"peer unknown save retains actual original");RebirthWorldCharacterRepository.Fail=null;Time.realtimeSinceStartup=200;ModEvents.Tick();Assert(Solo.Evidence==1&&Solo.CombatOriginal.Pending.Count==0,"peer save retry once");
Setup();pkg.flags=0;scope=Begin();core=Core(false);NativeKill(core);RebirthTheorySoloPeerCombatService.AfterPackage(scope,true);Assert(Solo.Evidence==1,"actual native Kill authority independent of client Fatal flag");
Setup();scope=Begin();core=Core();target.Health=0;var noSetDead=RebirthTheorySoloCombatService.BeforeKill(target,core.Response);target.RecordedFatal=true;target.entityThatKilledMe=p;RebirthTheorySoloCombatService.AfterKill(noSetDead,true);RebirthTheorySoloPeerCombatService.AfterCore(core,true);RebirthTheorySoloPeerCombatService.AfterPackage(scope,true);Assert(Solo==null&&target.IsDead()&&!target.bDead,"peer recorded Fatal without native SetDead cannot grant");
Console.WriteLine(n+" PASS whole peer packet/core/Kill services + extracted native item identity");}}
