using System;using System.Collections.Generic;
class EntityPlayer{}
class ItemClass{public string GetItemName()=>"material";}
class ItemValue{public int type=1;public bool HasQuality;public ItemClass ItemClass=new ItemClass();public ItemValue Clone()=>(ItemValue)MemberwiseClone();}
class ItemStack{public ItemValue itemValue;public int count;public ItemStack(ItemValue v,int c){itemValue=v;count=c;}}
class TagGroup{public class Global{}}
struct FastTags<T>{public bool Ignore;public bool Test_AnySet(FastTags<T> x)=>Ignore;public static FastTags<T> Parse(string x)=>new FastTags<T>();}
class Recipe{public string craftingArea="";public List<ItemStack> ingredients=new List<ItemStack>();public bool UseIngredientModifier=true;public int itemValueType=2,count=1,craftingToolType=3,craftingTier;public float craftExpGain=4,craftingTime=10;public FastTags<TagGroup.Global> tags;public void AddIngredients(List<ItemStack> x)=>ingredients.AddRange(x);}
enum PassiveEffects{CraftingIngredientCount,CraftingOutputCount,CraftingTime}
class EffectManager{public static float Ingredient=2.9f,Output=3,Seconds=9;public static float GetValue(PassiveEffects p,object a,float b,EntityPlayer e,Recipe r,FastTags<TagGroup.Global> t,bool calcEquipment=true,bool calcHoldingItem=true,bool calcProgression=true,bool calcBuffs=true,bool calcChallenges=true,int tier=0)=>p==PassiveEffects.CraftingIngredientCount?Ingredient:p==PassiveEffects.CraftingOutputCount?Output:Seconds;}
class XUiM_Recipes{public static float Input=.8f,CraftingInputModifier=1,CraftingOutputModifier=2,CraftingTimeModifier=.5f;public static FastTags<TagGroup.Global> SandboxIgnoreTag;public static float GetCraftingInputModifier(Recipe r)=>Input;}
class RebirthTheorySoloNativePaymentPlan{public static int LastDemand,LastBatches;public static bool Allowed=true;public static bool TryCreate(IList<ItemStack>d,int n,IList<ItemStack>b,IList<ItemStack>t,out RebirthTheorySoloNativePaymentPlan p){LastDemand=d[0].count;LastBatches=n;p=new RebirthTheorySoloNativePaymentPlan();return Allowed;}public List<ItemStack> PaidSnapshot()=>new List<ItemStack>{new ItemStack(new ItemValue{HasQuality=true},17)};}
class RebirthServiceCraftSkillService{public static string ClassifyRecipe(Recipe r)=>"skill.tailoring";}
class RebirthCraftTrainingRules{public struct Model{public bool Valid;public float Raw,Difficulty;}public static Recipe Seen;public static float Raw=1;public static Model BuildModel(EntityPlayer p,Recipe r,string s){Seen=r;return new Model{Valid=true,Raw=Raw,Difficulty=42};}}
class Test{static int count;static void Check(bool x){if(!x)throw new Exception("projection "+count);count++;}static void Main(){var p=new EntityPlayer();var r=new Recipe();r.ingredients.Add(new ItemStack(new ItemValue(),4));Recipe q;RebirthTheorySoloNativePaymentPlan pay;RebirthCraftTrainingRules.Model m;Func<bool> create=()=>RebirthTheorySoloNativeRecipeProjection.TryCreate(p,r,2,3,new List<ItemStack>(),new List<ItemStack>(),out q,out pay,out m);Check(create());Check(RebirthTheorySoloNativePaymentPlan.LastDemand==1&&RebirthTheorySoloNativePaymentPlan.LastBatches==3);Check(RebirthCraftTrainingRules.Seen.count==6&&RebirthCraftTrainingRules.Seen.craftingTime==4.5f);Check(RebirthCraftTrainingRules.Seen.ingredients[0].count==1&&r.ingredients[0].count==4);r.ingredients[0].itemValue.HasQuality=true;Check(create()&&RebirthCraftTrainingRules.Seen.ingredients[0].count==17);r.tags=new FastTags<TagGroup.Global>{Ignore=true};Check(create()&&RebirthCraftTrainingRules.Seen.count==3);EffectManager.Ingredient=0;Check(create()&&RebirthTheorySoloNativePaymentPlan.LastDemand==1);r.ingredients[0].itemValue.HasQuality=false;Check(!create());EffectManager.Ingredient=2.9f;XUiM_Recipes.Input=0;Check(!create());XUiM_Recipes.Input=.8f;EffectManager.Seconds=float.NaN;Check(!create());EffectManager.Seconds=9;RebirthTheorySoloNativePaymentPlan.Allowed=false;Check(!create());RebirthTheorySoloNativePaymentPlan.Allowed=true;r.craftingArea="forge";Check(!create());r.craftingArea="";r.UseIngredientModifier=false;Check(create()&&RebirthTheorySoloNativePaymentPlan.LastDemand==4);RebirthCraftTrainingRules.Raw=0;Check(!create());RebirthCraftTrainingRules.Raw=float.NaN;Check(!create());Console.WriteLine(count+" PASS actual native recipe projection (effect/payment doubles; payment separately native-debit qualified)");}}