using System;using System.Collections.Generic;using System.Linq;using System.Xml.Linq;
namespace UnityEngine{public struct Vector3{public float x;public float sqrMagnitude=>x*x;public static Vector3 operator -(Vector3 a,Vector3 b)=>new Vector3{x=a.x-b.x};}public static class Time{public static float realtimeSinceStartup;}}
public class World{public EntityPlayer Player;public bool Remote;public bool IsRemote()=>Remote;public object GetEntity(int id)=>Player?.entityId==id?Player:null;public EntityPlayer GetPrimaryPlayer()=>Player;}
public class EntityPlayer{public int entityId;public World world;public bool Dead;public bool IsDead()=>Dead;public UnityEngine.Vector3 position;public Stats Stats=new Stats();}
public class Stats{public Health Health=new Health();}public class Health{public float Value=100;}
public class GameManager{public static GameManager Instance=new GameManager();public World World;public bool Paused;public bool IsPaused()=>Paused;}
public static class ModEvents{public struct SGameUpdateData{}public delegate void Handler(ref SGameUpdateData d);public class Event{public Handler Tick;public void RegisterHandler(Handler h){Tick+=h;}}public static Event GameUpdate=new Event();}
public class RebirthStablePlayerIdentity{public string StorageKey="owner";public static bool TryResolveServerEntity(EntityPlayer p,out RebirthStablePlayerIdentity identity){identity=RebirthSkillAwardService.Identity;return p!=null;}}
public class Origin{public string CreationId=Guid.NewGuid().ToString("N");}public class Condition{public double ActivePlaySeconds;}
public class Theory{public float Value;}
public class RebirthTeachingHistoryRuntimeState{public string Key,StudentStorageKey,SkillId;public int CompletionCount;public long LastCompletedUtcTicks;}
public class RebirthWorldProgressionState{public RebirthTheorySoloState SoloTheory;public RebirthTheoryStudyOutcome PendingTheoryStudy;public Dictionary<string,Theory> SkillKnowledge=new Dictionary<string,Theory>();public Dictionary<string,RebirthTeachingHistoryRuntimeState> TeachingHistory=new Dictionary<string,RebirthTeachingHistoryRuntimeState>();public HashSet<string> SkillAwardReceipts=new HashSet<string>();}
public class RebirthWorldCharacterRecord{public Origin Origin=new Origin();public Condition Condition=new Condition();public RebirthWorldProgressionState Progression=new RebirthWorldProgressionState();public void Touch(string s){}}
public static class RebirthSkillKnowledgeService{public static object SyncRoot=new object();}
public static class RebirthSkillAwardService{public static RebirthWorldCharacterRecord Record;public static RebirthStablePlayerIdentity Identity=new RebirthStablePlayerIdentity();public static bool TryGetEligible(EntityPlayer p,out RebirthStablePlayerIdentity i,out RebirthWorldCharacterRecord r){i=Identity;r=Record;return p!=null&&!p.world.IsRemote()&&r!=null;}public static void QueueOwnerPublication(EntityPlayer p){}}
public static class RebirthLiteratureStudySessionService{public static bool Active;public static bool TryGetUiState(EntityPlayer p,out string id,out float progress,out float seconds,out bool slow){id="book";progress=seconds=0;slow=false;return Active;}}
public static class RebirthAudiobookListeningSessionService{public static bool Active;public static bool TryGetUiState(EntityPlayer p,out string id,out string source,out float progress,out float seconds){id=source="audio";progress=seconds=0;return Active;}}
public static class RebirthTheorySpecialistLessonService{public static bool Active;public static bool IsActive(EntityPlayer p)=>Active;}
public static class RebirthBackpackLibraryReservation{public static bool Blocked;public static bool BlocksResourceUse(EntityPlayer p)=>Blocked;}
public static class RebirthSurvivorRequestScope{public static bool TryNormalize(string s,out string n){n=s;return Guid.TryParseExact(s,"N",out var g)&&g!=Guid.Empty;}}
public static class RebirthTheoryStudyPersistence{public static bool MatchesOwner(RebirthTheoryStudyOutcome o,string c)=>o==null||o.CreationId==c;}
public static class RebirthSurvivorUiText{public static string L(string k,string f)=>f;}
public static class Localization{public static string Get(string k)=>k=="xuiRebirthStudyProgress"?"{0} {1}/{2}":"{0} +{1}";}
public static class RebirthTeachingService{public static void NotifyStudy(EntityPlayer p,bool ok,string s){}public static string FriendlySkill(string s)=>s;}
public static class RebirthTeachingOutcomeStore{public static void PruneAwardReceipts(HashSet<string> r,string preserve){}}
public static class RebirthWorldCharacterRepository{
 public static bool IsServerAuthority=true,Clean;public static int Saves,FailAt,FailCancelWitnessAt;public static bool Witness=true;public static RebirthTheorySoloState SavedSolo;public static RebirthTheoryStudyOutcome SavedOutcome;public static HashSet<string> SavedReceipts;public static float SavedTheory;
 public static bool TryGetCurrentCached(RebirthStablePlayerIdentity i,out RebirthWorldCharacterRecord r){r=RebirthSkillAwardService.Record;return r!=null;}
 public static bool IsCurrentCachedRecord(RebirthWorldCharacterRecord r)=>ReferenceEquals(r,RebirthSkillAwardService.Record);
 public static bool SaveIfDirty(RebirthStablePlayerIdentity i,string reason){if(++Saves==FailAt||Clean)return false;var p=RebirthSkillAwardService.Record.Progression;SavedSolo=p.SoloTheory?.Clone();SavedOutcome=p.PendingTheoryStudy?.Clone();SavedReceipts=new HashSet<string>(p.SkillAwardReceipts);SavedTheory=p.SkillKnowledge["skill.cooking"].Value;return true;}
 public static bool HasSavedSoloCancellationHold(RebirthStablePlayerIdentity i,RebirthTheorySoloState expected)=>Witness&&SavedOutcome==null&&SavedSolo?.Session==null&&SavedSolo.CancelPendingId==expected.CancelPendingId&&XNode.DeepEquals(RebirthTheorySoloPersistence.Write(SavedSolo),RebirthTheorySoloPersistence.Write(expected));
 public static bool HasSavedSoloCancellation(RebirthStablePlayerIdentity i,string c,string id)=>Witness&&Saves!=FailCancelWitnessAt&&SavedOutcome==null&&SavedSolo?.CreationId==c&&SavedSolo.LastCancelledId==id&&SavedSolo.Session==null&&string.IsNullOrEmpty(SavedSolo.CancelPendingId);
 public static bool HasSavedSoloSession(RebirthStablePlayerIdentity i,RebirthTheorySoloState s)=>Witness&&XNode.DeepEquals(RebirthTheorySoloPersistence.Write(SavedSolo),RebirthTheorySoloPersistence.Write(s));
 public static bool HasSavedTheoryStudy(RebirthStablePlayerIdentity i,RebirthTheoryStudyOutcome o,bool applied,bool settled=false)=>Witness&&(settled?SavedOutcome==null:SavedOutcome?.Id==o.Id)&&RebirthTheorySoloService.ValidateOutcome(SavedSolo,o,applied,settled)&&(!applied||SavedReceipts.Contains(o.Receipt)&&SavedTheory>=o.Target);
}
class Check{static int assertions,id;static void A(bool b,string why){if(!b)throw new Exception(why);assertions++;}
 static EntityPlayer Setup(){var w=new World();var p=new EntityPlayer{entityId=++id,world=w};w.Player=p;GameManager.Instance.World=w;GameManager.Instance.Paused=false;var r=new RebirthWorldCharacterRecord();r.Condition.ActivePlaySeconds=200;r.Progression.SkillKnowledge["skill.cooking"]=new Theory();r.Progression.SoloTheory=new RebirthTheorySoloState{CreationId=r.Origin.CreationId};for(int j=0;j<3;j++)r.Progression.SoloTheory.RecordAcknowledged("skill.cooking","recipe_process","native:"+j,50,100+j*20);RebirthSkillAwardService.Record=r;RebirthTheorySpecialistLessonService.Active=false;RebirthLiteratureStudySessionService.Active=false;RebirthAudiobookListeningSessionService.Active=false;RebirthWorldCharacterRepository.Clean=false;RebirthWorldCharacterRepository.Saves=0;RebirthWorldCharacterRepository.FailAt=0;RebirthWorldCharacterRepository.FailCancelWitnessAt=0;RebirthWorldCharacterRepository.Witness=true;RebirthBackpackLibraryReservation.Blocked=false;return p;}
 static void Tick(float dt,int n=1){for(int j=0;j<n;j++){UnityEngine.Time.realtimeSinceStartup+=dt;var d=new ModEvents.SGameUpdateData();ModEvents.GameUpdate.Tick(ref d);}}
 static bool NativeReadingGuard(EntityPlayer player,out string message){message="";// ACTUAL_READING_GUARD
 return true;}
 static bool NativeAudioGuard(EntityPlayer player,out string message){message="";// ACTUAL_AUDIO_GUARD
 return true;}
 static bool NativeSpecialistGuard(EntityPlayer student,out string reason){reason="";// ACTUAL_SPECIALIST_GUARD
 return true;}
 static void Main(string[] args){var xml=XDocument.Load(args[0]);RebirthTheorySoloRegistry.Load(args[0],xml.Root.Element("subjects").Elements().Select(x=>(string)x.Attribute("skill_id")));RebirthTheorySoloService.Install();var p=Setup();A(RebirthTheorySoloService.TryBegin(p,"skill.cooking",out _),"begin");Tick(.5f,120);var state=RebirthSkillAwardService.Record.Progression;A(state.SkillKnowledge["skill.cooking"].Value==.5f&&state.SoloTheory.Session==null&&state.SoloTheory.Evidence.Count==0,"once settled");Tick(.5f,120);A(state.SkillKnowledge["skill.cooking"].Value==.5f,"no replay");A(!RebirthTheorySoloService.TryBegin(p,"skill.cooking",out _),"no reused evidence");
 p=Setup();RebirthWorldCharacterRepository.Witness=false;A(!RebirthTheorySoloService.TryBegin(p,"skill.cooking",out _),"failed reservation witness");Tick(.5f,120);A(RebirthSkillAwardService.Record.Progression.SoloTheory.Session.Elapsed==0,"no unwitnessed time");
 p=Setup();A(RebirthTheorySoloService.TryBegin(p,"skill.cooking",out _),"pause begin");GameManager.Instance.Paused=true;Tick(.5f,10);A(RebirthSkillAwardService.Record.Progression.SoloTheory.Session.Elapsed==0,"pause gap");GameManager.Instance.Paused=false;Tick(2);A(RebirthSkillAwardService.Record.Progression.SoloTheory.Session.Elapsed==0,"stall gap");p.position=new UnityEngine.Vector3{x=1};Tick(.5f);var original=RebirthSkillAwardService.Record.Progression.SoloTheory.Session.Id;A(RebirthTheorySoloService.TryBegin(p,"skill.cooking",out _),"resume");A(original==RebirthSkillAwardService.Record.Progression.SoloTheory.Session.Id,"same reservation identity");
 p=Setup();A(RebirthTheorySoloService.TryBegin(p,"skill.cooking",out _),"fault begin");RebirthWorldCharacterRepository.FailAt=4;Tick(.5f,120);state=RebirthSkillAwardService.Record.Progression;A(state.PendingTheoryStudy!=null&&state.SoloTheory.Session.Consumed&&state.SkillKnowledge["skill.cooking"].Value==.5f,"terminal failure retains consumed intent");RebirthWorldCharacterRepository.FailAt=0;Tick(.5f);A(state.PendingTheoryStudy==null&&state.SoloTheory.Session==null&&state.SkillKnowledge["skill.cooking"].Value==.5f,"terminal retry exactly once");
 p=Setup();A(RebirthTheorySoloService.TryBegin(p,"skill.cooking",out _),"relevance begin");Tick(.5f,20);state=RebirthSkillAwardService.Record.Progression;state.SkillKnowledge["skill.cooking"].Value=90;Tick(.5f,120);A(state.SkillKnowledge["skill.cooking"].Value==90&&state.PendingTheoryStudy==null,"actual evidence becomes trivial after Theory changes");A(!RebirthTheorySoloService.TryBegin(p,"skill.cooking",out _),"trivial reservation cannot resume");
 p=Setup();A(RebirthTheorySoloService.TryBegin(p,"skill.cooking",out _),"forged outcome begin");state=RebirthSkillAwardService.Record.Progression;var session=state.SoloTheory.Session;session.Elapsed=session.Duration;RebirthTheoryStudyOutcome.TryCreate(Guid.ParseExact(session.Id,"N"),RebirthSkillAwardService.Record.Origin.CreationId,"skill.cooking","solo","reflection",0,3,1,DateTime.UtcNow.Ticks,session.Duration,out var forged);A(!RebirthTheorySoloService.ValidateOutcome(state.SoloTheory,forged,false,false),"authored gain enforced");session.Ordinals.RemoveAt(0);RebirthTheoryStudyOutcome.TryCreate(Guid.ParseExact(session.Id,"N"),RebirthSkillAwardService.Record.Origin.CreationId,"skill.cooking","solo","reflection",0,.5f,1,DateTime.UtcNow.Ticks,session.Duration,out forged);A(!RebirthTheorySoloService.ValidateOutcome(state.SoloTheory,forged,false,false),"minimum evidence enforced");
 p=Setup();A(RebirthTheorySoloService.TryBegin(p,"skill.cooking",out _),"clean begin");p.position=new UnityEngine.Vector3{x=1};Tick(.5f);var reserved=RebirthSkillAwardService.Record.Progression.SoloTheory.Session.Id;RebirthWorldCharacterRepository.Clean=true;A(RebirthTheorySoloService.TryBegin(p,"skill.cooking",out _),"exact clean snapshot resume");A(reserved==RebirthSkillAwardService.Record.Progression.SoloTheory.Session.Id,"clean resume identity");RebirthWorldCharacterRepository.Clean=false;
 p=Setup();RebirthLiteratureStudySessionService.Active=true;A(!RebirthTheorySoloService.TryBegin(p,"skill.cooking",out _),"reading excludes solo");A(RebirthWorldCharacterRepository.Saves==0,"reading guard before reserve/save");RebirthLiteratureStudySessionService.Active=false;RebirthAudiobookListeningSessionService.Active=true;A(!RebirthTheorySoloService.TryBegin(p,"skill.cooking",out _),"audio excludes solo");RebirthAudiobookListeningSessionService.Active=false;RebirthTheorySpecialistLessonService.Active=true;A(!RebirthTheorySoloService.TryBegin(p,"skill.cooking",out _),"specialist excludes solo");RebirthTheorySpecialistLessonService.Active=false;A(RebirthTheorySoloService.TryBegin(p,"skill.cooking",out _),"guarded begin");var originalSession=RebirthSkillAwardService.Record.Progression.SoloTheory.Session.Id;RebirthTheorySoloService.PauseForOtherStudy(p);A(!RebirthTheorySoloService.IsRunning(p),"other study pauses solo timing");A(RebirthSkillAwardService.Record.Progression.SoloTheory.Session.Id==originalSession&&RebirthSkillAwardService.Record.Progression.SoloTheory.Evidence.Count==3,"other study preserves reservation evidence");A(RebirthTheorySoloService.TryBegin(p,"skill.cooking",out _),"resume after other study");RebirthLiteratureStudySessionService.Active=true;Tick(.5f);A(!RebirthTheorySoloService.IsRunning(p)&&RebirthSkillAwardService.Record.Progression.SoloTheory.Session.Id==originalSession,"defensive active study pause");RebirthLiteratureStudySessionService.Active=false;
 p=Setup();A(RebirthTheorySoloService.TryBegin(p,"skill.cooking",out _),"cancel begin");state=RebirthSkillAwardService.Record.Progression;var cancelId=state.SoloTheory.Session.Id;A(!RebirthTheorySoloService.TryCancel(p,"skill.cooking",Guid.NewGuid().ToString("N"),out _),"foreign session cancel refused");A(RebirthTheorySoloService.TryCancel(p,"skill.cooking",cancelId,out _),"saved cancel");A(state.SoloTheory.Session==null&&state.SoloTheory.Evidence.Count==3&&state.SkillKnowledge["skill.cooking"].Value==0,"cancel no gain/no evidence consumption");A(RebirthWorldCharacterRepository.SavedSolo.LastCancelledId==cancelId,"terminal original cancel identity");
 p=Setup();A(RebirthTheorySoloService.TryBegin(p,"skill.cooking",out _),"uncertain cancel begin");state=RebirthSkillAwardService.Record.Progression;cancelId=state.SoloTheory.Session.Id;RebirthWorldCharacterRepository.FailAt=3;A(!RebirthTheorySoloService.TryCancel(p,"skill.cooking",cancelId,out _),"terminal cancel write fault");A(state.SoloTheory.Session==null&&state.SoloTheory.CancelPendingId==cancelId&&state.SoloTheory.Evidence.Count==3,"terminal uncertainty retains cancellation hold");A(!RebirthTheorySoloService.TryBegin(p,"skill.cooking",out _),"no resume during cancellation uncertainty");Tick(.5f,120);A(state.SkillKnowledge["skill.cooking"].Value==0,"held cancellation cannot gain");RebirthWorldCharacterRepository.FailAt=0;A(RebirthTheorySoloService.TryCancel(p,"skill.cooking",cancelId,out _),"same cancellation retry");A(state.SoloTheory.CancelPendingId==null&&state.SoloTheory.Evidence.Count==3,"retry terminal preserves evidence");
 p=Setup();A(RebirthTheorySoloService.TryBegin(p,"skill.cooking",out _),"uncertain witness cancel begin");state=RebirthSkillAwardService.Record.Progression;cancelId=state.SoloTheory.Session.Id;RebirthWorldCharacterRepository.FailCancelWitnessAt=3;A(!RebirthTheorySoloService.TryCancel(p,"skill.cooking",cancelId,out _),"terminal write succeeded but read witness failed");A(RebirthWorldCharacterRepository.SavedSolo.LastCancelledId==cancelId&&RebirthWorldCharacterRepository.SavedSolo.Session==null,"final file may already cancel");A(state.SoloTheory.CancelPendingId==cancelId&&!RebirthTheorySoloService.TryBegin(p,"skill.cooking",out _),"uncertain successful save cannot resume");RebirthTheoryStudyOutcome.TryCreate(Guid.ParseExact(cancelId,"N"),RebirthSkillAwardService.Record.Origin.CreationId,"skill.cooking","solo","reflection",0,.5f,1,DateTime.UtcNow.Ticks,60,out var cancelledOutcome);A(!RebirthTheorySoloService.ValidateOutcome(RebirthWorldCharacterRepository.SavedSolo,cancelledOutcome,false,false),"saved terminal refuses stale completion");var holdNode=new XElement("progression",RebirthTheorySoloPersistence.Write(state.SoloTheory));A(RebirthTheorySoloPersistence.TryRead(holdNode,out var held,out _)&&held.CancelPendingId==cancelId&&held.Session==null,"cancellation hold survives save/load");RebirthWorldCharacterRepository.FailCancelWitnessAt=0;A(RebirthTheorySoloService.TryCancel(p,"skill.cooking",cancelId,out _),"uncertain witness retries same terminal cancellation");
 p=Setup();A(RebirthTheorySoloService.TryBegin(p,"skill.cooking",out _),"reverse guard begin");state=RebirthSkillAwardService.Record.Progression;var reverseId=state.SoloTheory.Session.Id;A(!NativeSpecialistGuard(p,out _),"actual specialist guard refuses active solo");A(NativeReadingGuard(p,out _)&&!RebirthTheorySoloService.IsRunning(p)&&state.SoloTheory.Session.Id==reverseId,"actual reading switch pauses original solo");A(RebirthTheorySoloService.TryBegin(p,"skill.cooking",out _),"reverse guard resume");A(NativeAudioGuard(p,out _)&&!RebirthTheorySoloService.IsRunning(p)&&state.SoloTheory.Session.Id==reverseId,"actual audio switch pauses original solo");RebirthTheorySpecialistLessonService.Active=true;A(!NativeReadingGuard(p,out _),"actual reading guard refuses active specialist");A(!NativeAudioGuard(p,out _),"actual audio guard refuses active specialist");RebirthTheorySpecialistLessonService.Active=false;RebirthLiteratureStudySessionService.Active=true;A(!NativeSpecialistGuard(p,out _),"actual specialist guard refuses active reading");RebirthLiteratureStudySessionService.Active=false;RebirthAudiobookListeningSessionService.Active=true;A(!NativeSpecialistGuard(p,out _),"actual specialist guard refuses active audio");RebirthAudiobookListeningSessionService.Active=false;
 Console.WriteLine(assertions+" PASS service/settlement");}}
