using System;using System.IO;using System.Linq;using System.Reflection;using System.Xml.Linq;
namespace UnityEngine.Scripting{public sealed class PreserveAttribute:Attribute{}}
public enum NetPackageDirection{ToServer,ToClient}
public class PooledBinaryReader:BinaryReader{public PooledBinaryReader(Stream s):base(s){}}
public class PooledBinaryWriter:BinaryWriter{public PooledBinaryWriter(Stream s):base(s){}}
public class NetPackage{public object Sender=new object();public bool SenderValid=true;public virtual NetPackageDirection PackageDirection=>NetPackageDirection.ToClient;public virtual void read(PooledBinaryReader r){}public virtual void write(PooledBinaryWriter w){}public virtual void ProcessPackage(World w,GameManager g){}public bool ValidEntityIdForSender(int id)=>SenderValid;}
public class EntityPlayerLocal:EntityPlayer{}
public class FakeConnection{public bool Disconnected;public bool IsDisconnected()=>Disconnected;}
public class ConnectionManager{public FakeConnection[] connectionToServer=new[]{new FakeConnection()};public bool IsServer;public object Sent;public void SendPackage(object p,int _attachedToEntityId){Sent=p;}public void SendToServer(object p){Sent=p;}}
public static class SingletonMonoBehaviour<T> where T:new(){public static T Instance=new T();}
public static class NetPackageManager{public static T GetPackage<T>()where T:new()=>new T();public static int GetPackageId(Type t)=>1;}
public static class RebirthSurvivorMode{public static bool IsEnabledForCurrentWorld()=>true;}
public static class RebirthSurvivorClientState{public static string GetProjectedCreationId(EntityPlayer p)=>RebirthSkillAwardService.Record.Origin.CreationId;}
public static class RebirthSurvivorNetworkCodec{public static string ReadString(BinaryReader b,int max){var s=b.ReadString();if(s.Length>max)throw new InvalidDataException();return s;}public static void WriteString(BinaryWriter b,string s,int max)=>b.Write(s??"");public static int EstimateString(string s,int max)=>(s??"").Length+2;}
class StatusCheck{
 static int count;static void A(bool x,string why){if(!x)throw new Exception(why);count++;}
 static void Main(string[] args){var xml=XDocument.Load(args[0]);RebirthTheorySoloRegistry.Load(args[0],xml.Root.Element("subjects").Elements().Select(x=>(string)x.Attribute("skill_id")));var world=new World();var player=new EntityPlayerLocal{world=world,entityId=100};world.Player=player;GameManager.Instance.World=world;var record=new RebirthWorldCharacterRecord();RebirthSkillAwardService.Record=record;record.Progression.SkillKnowledge["skill.cooking"]=new Theory();record.Progression.SoloTheory=new RebirthTheorySoloState{CreationId=record.Origin.CreationId};for(int j=0;j<3;j++)record.Progression.SoloTheory.RecordAcknowledged("skill.cooking","recipe_process","native"+j,50,100+j*20);
 var id=Guid.NewGuid();A(RebirthTheorySoloStatusServer.TryBuild(player,record.Origin.CreationId,"skill.cooking",id,out var status),"cached status");A(status.Mode==RebirthTheorySoloStatusMode.Ready&&status.Count==3,"actual available evidence");A(RebirthWorldCharacterRepository.Saves==0,"status no saves");A(!RebirthTheorySoloStatusServer.TryBuild(player,Guid.NewGuid().ToString("N"),"skill.cooking",id,out _),"foreign creation");var stranger=new EntityPlayerLocal{world=world,entityId=100};A(!RebirthTheorySoloStatusServer.TryBuild(stranger,record.Origin.CreationId,"skill.cooking",id,out _),"original entity guard");
 object sender=new object();A(RebirthTheorySoloStatusServer.Allow(world,sender),"first request");A(!RebirthTheorySoloStatusServer.Allow(world,sender),"server throttle");UnityEngine.Time.realtimeSinceStartup+=1;A(RebirthTheorySoloStatusServer.Allow(world,sender),"bounded refresh");
 world.Remote=true;SingletonMonoBehaviour<ConnectionManager>.Instance.IsServer=false;RebirthTheorySoloStatusClient.View(player,"skill.cooking");var request=(Guid)typeof(RebirthTheorySoloStatusClient).GetField("request",BindingFlags.NonPublic|BindingFlags.Static).GetValue(null);status.Request=request;RebirthTheorySoloStatusClient.Receive(world,status);A(RebirthTheorySoloStatusClient.View(player,"skill.cooking").Contains("Ready"),"scoped response accepted");var foreign=new RebirthTheorySoloStatus{Player=status.Player,Creation=Guid.NewGuid().ToString("N"),Subject=status.Subject,Request=request,Mode=RebirthTheorySoloStatusMode.Maximum,Count=3,Required=3,Duration=60};RebirthTheorySoloStatusClient.Receive(world,foreign);A(RebirthTheorySoloStatusClient.View(player,"skill.cooking").Contains("Ready"),"foreign response refused");
 status.Elapsed=float.NaN;A(!status.Valid(),"finite payload");status.Elapsed=0;status.Count=17;A(!status.Valid(),"count bound");status.Count=3;status.Duration=3601;A(!status.Valid(),"duration bound");status.Duration=60;
  var packet=NetPackageManager.GetPackage<NetPackageRebirthTheorySoloStatusResponse>().Setup(status);var buffer=new MemoryStream();packet.write(new PooledBinaryWriter(buffer));buffer.Position=0;var decoded=new NetPackageRebirthTheorySoloStatusResponse();decoded.read(new PooledBinaryReader(buffer));var image=(RebirthTheorySoloStatus)typeof(NetPackageRebirthTheorySoloStatusResponse).GetField("value",BindingFlags.NonPublic|BindingFlags.Instance).GetValue(decoded);A(image.Valid()&&image.Request==request&&image.Subject==status.Subject,"actual payload round trip");
 status.Request=Guid.NewGuid();RebirthTheorySoloStatusClient.Receive(world,status);status.Request=request;A(RebirthTheorySoloStatusClient.View(player,"skill.cooking").Contains("Ready"),"stale request refused");
 SingletonMonoBehaviour<ConnectionManager>.Instance.connectionToServer[0]=new FakeConnection();RebirthTheorySoloStatusClient.Receive(world,status);A(RebirthTheorySoloStatusClient.View(player,"skill.cooking").Contains("Checking"),"new native connection cannot inherit response");
RebirthTheorySoloStatusClient.Close();RebirthTheorySoloStatusClient.Receive(world,status);A(RebirthTheorySoloStatusClient.View(player,"skill.cooking").Contains("Checking"),"closed old request refused");Console.WriteLine(count+" PASS status");}}
