using System;using System.IO;using System.Linq;using System.Xml.Linq;
class World{public bool Remote;public EntityPlayer Player;public bool IsRemote()=>Remote;public object GetEntity(int id)=>Player;}
class EntityPlayer{public int entityId=1;public World world;public bool Dead;public bool IsDead()=>Dead;}
class GameManager{public static GameManager Instance=new GameManager();public World World;}
class RebirthStablePlayerIdentity{public string StorageKey="teacher";}
class Origin{public string CreationId=new string('a',32);}
class Condition{public double ActivePlaySeconds=100;}
class RebirthWorldProgressionState{public RebirthTheorySoloState SoloTheory;}
class RebirthWorldCharacterRecord{public Origin Origin=new Origin();public Condition Condition=new Condition();public RebirthWorldProgressionState Progression=new RebirthWorldProgressionState();public bool Dirty;public void Touch(string s){Dirty=true;}}
static class RebirthWorldCharacterRepository{public static bool IsServerAuthority=true,Current=true,Throw,SaveKnown=true;public static RebirthTheorySoloState Saved;public static bool IsCurrentCachedRecord(RebirthWorldCharacterRecord r)=>Current&&ReferenceEquals(r,RebirthSkillAwardService.Record);public static bool SaveIfDirty(RebirthStablePlayerIdentity i,string s){if(Throw)throw new IOException();if(SaveKnown){Saved=RebirthSkillAwardService.Record.Progression.SoloTheory.Clone();RebirthSkillAwardService.Record.Dirty=false;}return SaveKnown;}public static bool HasSavedSoloTeachingOriginal(RebirthStablePlayerIdentity i,RebirthTheorySoloState s)=>Saved!=null&&Saved.TeachingOriginal.IsAcknowledged(RebirthTeachingOutcomeStore.Outcome.OriginalOrdinal)&&Saved.Evidence.Count==s.Evidence.Count;}
static class RebirthSkillAwardService{public static RebirthWorldCharacterRecord Record;public static bool Eligible=true;public static bool TryGetEligible(EntityPlayer p,out RebirthStablePlayerIdentity i,out RebirthWorldCharacterRecord r){i=new RebirthStablePlayerIdentity();r=Record;return Eligible;}}
static class RebirthSkillKnowledgeService{public static readonly object SyncRoot=new object();}
static class RebirthSurvivorIds{public const string SkillTeaching="skill.teaching";}
public class RebirthTheorySoloOriginalTaskLedger{public RebirthTheorySoloOriginalTaskLedger Clone()=>new RebirthTheorySoloOriginalTaskLedger();}
class Rule{public string Family="social_transfer";public double EventSpacing=10;}
static class RebirthTheorySoloRegistry{public static bool TryGet(string s,out Rule r){r=new Rule();return s=="skill.teaching";}}
class RebirthTeachingDurableOutcome{public long OriginalOrdinal=1;public bool StudentApplied=true,InstructorApplied=true,SoloEvidenceApplied;public string OutcomeId="original",InstructorStorageKey="teacher",InstructorCreationId=new string('a',32);public float StudentKnowledgeTarget=42;}
static class RebirthTeachingOutcomeStore{public static RebirthTeachingDurableOutcome Outcome=new RebirthTeachingDurableOutcome();public static bool Available=true,Ack=true;public static bool TryGetOriginal(RebirthTeachingDurableOutcome o,out RebirthTeachingDurableOutcome original){original=Outcome;return Available&&ReferenceEquals(o,Outcome);}public static long[] PendingOriginalOrdinals(string owner,string creation)=>new[]{Outcome.OriginalOrdinal};public static bool AcknowledgeSolo(string id)=>Ack;}
class Test{static int count;static void Check(bool x,string why){if(!x)throw new Exception(count+" "+why);count++;}static void Main(){var p=new EntityPlayer();var w=new World{Player=p};p.world=w;GameManager.Instance.World=w;var r=new RebirthWorldCharacterRecord();RebirthSkillAwardService.Record=r;var i=new RebirthStablePlayerIdentity();var o=RebirthTeachingOutcomeStore.Outcome;RebirthTeachingOutcomeStore.Available=false;Check(!RebirthTheorySoloTeachingCompletion.TryApply(o,p,i,r)&&r.Progression.SoloTheory==null,"unproved original cannot touch");RebirthTeachingOutcomeStore.Available=true;o.StudentApplied=false;Check(!RebirthTheorySoloTeachingCompletion.TryApply(o,p,i,r)&&r.Progression.SoloTheory==null,"admission before actual student stage cannot touch");o.StudentApplied=true;w.Remote=true;Check(!RebirthTheorySoloTeachingCompletion.TryApply(o,p,i,r)&&r.Progression.SoloTheory==null,"remote rejected");w.Remote=false;RebirthWorldCharacterRepository.SaveKnown=false;Check(!RebirthTheorySoloTeachingCompletion.TryApply(o,p,i,r)&&r.Progression.SoloTheory.Evidence.Count==1,"unknown save retains exact evidence attempt");Check(!RebirthTheorySoloTeachingCompletion.TryApply(o,p,i,r)&&r.Progression.SoloTheory.Evidence.Count==1,"unknown retry no duplicate");RebirthWorldCharacterRepository.Throw=true;Check(!RebirthTheorySoloTeachingCompletion.TryApply(o,p,i,r)&&r.Progression.SoloTheory.Evidence.Count==1,"throw retains original attempt");RebirthWorldCharacterRepository.Throw=false;RebirthWorldCharacterRepository.SaveKnown=true;RebirthTeachingOutcomeStore.Ack=false;Check(!RebirthTheorySoloTeachingCompletion.TryApply(o,p,i,r)&&RebirthWorldCharacterRepository.Saved.Evidence.Count==1,"journal ack hold after saved character");RebirthTeachingOutcomeStore.Ack=true;Check(RebirthTheorySoloTeachingCompletion.TryApply(o,p,i,r)&&o.SoloEvidenceApplied&&r.Progression.SoloTheory.Evidence.Count==1,"exact retry completes once");Check(r.Progression.SoloTheory.Evidence[0].Difficulty==42&&r.Progression.SoloTheory.Evidence[0].Family=="social_transfer","saved continuous student target relevance");r.Progression.SoloTheory=RebirthWorldCharacterRepository.Saved.Clone();Check(RebirthTheorySoloTeachingCompletion.TryApply(o,p,i,r)&&r.Progression.SoloTheory.Evidence.Count==1,"reload original retirement no duplicate");r.Progression.SoloTheory.Evidence.Clear();Check(RebirthTheorySoloTeachingCompletion.TryApply(o,p,i,r)&&r.Progression.SoloTheory.Evidence.Count==0,"retired outcome cannot refill pruned evidence");RebirthWorldCharacterRepository.Current=false;Check(!RebirthTheorySoloTeachingCompletion.TryApply(o,p,i,r),"stale record refuses");RebirthWorldCharacterRepository.Current=true;var replaced=new World{Player=p};GameManager.Instance.World=replaced;Check(!RebirthTheorySoloTeachingCompletion.TryApply(o,p,i,r),"replaced native world refuses");Console.WriteLine(count+" PASS actual durable Teaching Solo completion producer");}}