using System;using System.Collections.Generic;using System.IO;using System.Linq;using System.Xml.Linq;
class World{public Dictionary<int,EntityPlayer> Players=new Dictionary<int,EntityPlayer>();public bool IsRemote()=>false;public object GetEntity(int n)=>Players.TryGetValue(n,out var p)?p:null;}
class EntityPlayer{public int entityId;public World world;public bool IsDead()=>false;}
class GameManager{public static GameManager Instance=new GameManager();public World World;}
class RebirthStablePlayerIdentity{public string StorageKey;public RebirthWorldCharacterRecord Record;}
class RebirthWorldCharacterRecord{public OriginState Origin=new OriginState();public ConditionState Condition=new ConditionState();public bool IsComplete=true,Dirty;public ProgressionState Progression=new ProgressionState();public RebirthTheorySoloState Saved;public void Touch(string s){Dirty=true;}}
class OriginState{public string CreationId;}
class ConditionState{public double ActivePlaySeconds=100;}
class Study{public string Receipt;}
class ProgressionState{public RebirthTheorySoloState SoloTheory;public Study PendingTheoryStudy;public HashSet<string> SkillAwardReceipts=new HashSet<string>();public Dictionary<string,RebirthSkillKnowledgeRuntimeState> SkillKnowledge=new Dictionary<string,RebirthSkillKnowledgeRuntimeState>();public Dictionary<string,RebirthTeachingLessonRuntimeState> TeachingLessons=new Dictionary<string,RebirthTeachingLessonRuntimeState>();public Dictionary<string,RebirthTeachingHistoryRuntimeState> TeachingHistory=new Dictionary<string,RebirthTeachingHistoryRuntimeState>();}
class RebirthSkillKnowledgeRuntimeState{public float Value;}
class RebirthTeachingLessonRuntimeState{public string SkillId,InstructorStorageKey,OutcomeId;public float RemainingActiveSeconds,GainMultiplier;}
class RebirthTeachingHistoryRuntimeState{public string Key,StudentStorageKey,SkillId;public long LastCompletedUtcTicks;public int CompletionCount;}
public class RebirthTheorySoloOriginalTaskLedger{public RebirthTheorySoloOriginalTaskLedger Clone()=>new RebirthTheorySoloOriginalTaskLedger();}
class Rule{public string Family="social_transfer";public double EventSpacing=10;}
static class RebirthTheorySoloRegistry{public static bool TryGet(string s,out Rule r){r=new Rule();return s=="skill.teaching";}}
static class RebirthWorldCharacterRepository{public static bool IsServerAuthority=true,FailSolo;public static bool IsCurrentCachedRecord(RebirthWorldCharacterRecord r)=>r!=null;public static bool SaveIfDirty(RebirthStablePlayerIdentity i,string why){if(why=="solo-theory-original-teaching"&&FailSolo)return false;i.Record.Dirty=false;if(i.Record.Progression.SoloTheory!=null)i.Record.Saved=i.Record.Progression.SoloTheory.Clone();return true;}public static bool HasSavedSoloTeachingOriginal(RebirthStablePlayerIdentity i,RebirthTheorySoloState s)=>i.Record.Saved!=null&&XNode.DeepEquals(i.Record.Saved.TeachingOriginal.Write(),s.TeachingOriginal.Write())&&i.Record.Saved.Evidence.Count==s.Evidence.Count;}
static class RebirthSkillAwardService{public static Dictionary<int,RebirthStablePlayerIdentity> Owners=new Dictionary<int,RebirthStablePlayerIdentity>();public static int Awards;public static bool TryGetEligible(EntityPlayer p,out RebirthStablePlayerIdentity i,out RebirthWorldCharacterRecord r){bool found=Owners.TryGetValue(p.entityId,out i);r=i?.Record;return found;}public static bool TryAwardMigratedTrainingEvidence(EntityPlayer p,RebirthSkillTrainingEvidence e,out RebirthSkillTrainingComputation c,out float s,out float a){Awards++;c=null;s=a=0;Owners[p.entityId].Record.Progression.SkillAwardReceipts.Add(e.DurableReceiptId);return true;}}
class RebirthSkillTrainingEvidence{public string SkillId,SourceKey,DurableReceiptId,ReferenceDescription;public bool AuthoritativeSuccess;public RebirthSkillTrainingEvidenceMode Mode;public float CreditedWork,DiscreteRawAward;}
class RebirthSkillTrainingComputation{}
enum RebirthSkillTrainingEvidenceMode{DiscreteAward}
static class RebirthSkillKnowledgeService{public static readonly object SyncRoot=new object();}
static class RebirthSurvivorIds{public const string SkillTeaching="skill.teaching";}
static class RebirthTheoryProgressionService{public static bool TryAwardInsight(EntityPlayer p,string id,string source,out float f,out bool old){f=0;old=false;return true;}}
static class Time{public static float realtimeSinceStartup=1;}
static class Localization{public static string Get(string s)=>s;}
static class GameIO{public static string Directory;public static string GetSaveGameDir()=>Directory;}
static class Log{public static void Warning(string x){}}
static class RebirthAtomicXmlFile{public static int Fault;public static bool TryWrite(string path,XDocument doc,out string error){error="fault";Directory.CreateDirectory(Path.GetDirectoryName(path));if(Fault==1)return false;doc.Save(path);return Fault!=2;}public static bool TryLoadFinalThenBackup(string path,out XDocument doc,out bool backup,out string error){doc=null;backup=false;error="";try{doc=XDocument.Load(path);return true;}catch{return false;}}}
// SCOPE
class Check{
 static readonly object Gate=new object();static readonly HashSet<int> LessonPlayers=new HashSet<int>(),DirtyLessonPlayers=new HashSet<int>();static readonly Dictionary<int,float> NextLessonRevisionPublish=new Dictionary<int,float>();static void PublishSavedOutcome(EntityPlayer p,string reason){}static void AddBoundedReceipt(HashSet<string> r,string receipt,string protectedReceipt=null){r.Add(receipt);}static void PruneHistory(ProgressionState p){}
 // SOURCE
 static int count;static void Assert(bool x,string why){if(!x)throw new Exception(count+" "+why);count++;}
 static void Main(string[] args){GameIO.Directory=args[0];var w=new World();GameManager.Instance.World=w;var teacher=new EntityPlayer{entityId=1,world=w};var student=new EntityPlayer{entityId=2,world=w};w.Players[1]=teacher;w.Players[2]=student;var ir=new RebirthWorldCharacterRecord();var sr=new RebirthWorldCharacterRecord();ir.Origin.CreationId=new string('a',32);sr.Origin.CreationId=new string('b',32);sr.Progression.SkillKnowledge["skill.cooking"]=new RebirthSkillKnowledgeRuntimeState();var ii=new RebirthStablePlayerIdentity{StorageKey="teacher",Record=ir};var si=new RebirthStablePlayerIdentity{StorageKey="student",Record=sr};RebirthSkillAwardService.Owners[1]=ii;RebirthSkillAwardService.Owners[2]=si;var o=new RebirthTeachingDurableOutcome{OutcomeId="original",InstructorStorageKey=ii.StorageKey,StudentStorageKey=si.StorageKey,InstructorCreationId=ir.Origin.CreationId,StudentCreationId=sr.Origin.CreationId,SkillId="skill.cooking",HistoryKey="history",HistoryTargetCount=1,CompletedUtcTicks=1,StudentKnowledgeTarget=42,TeacherAward=.4f};string error;
 Assert(RebirthTeachingOutcomeStore.TryReserveOriginal(o,0,out error),"reserve original");Assert(ir.Progression.SoloTheory==null,"admission no evidence");RebirthWorldCharacterRepository.FailSolo=true;Assert(!TryApplyDurableOutcome(o,teacher,student,ii,ir,si,sr),"Solo unknown save holds after actual participant stages");Assert(o.StudentApplied&&o.InstructorApplied&&!o.SoloEvidenceApplied&&!o.RewardApplied,"ordered stages");Assert(sr.Progression.SkillKnowledge["skill.cooking"].Value==42&&ir.Progression.TeachingHistory["history"].CompletionCount==1,"actual participant transfer/history");Assert(ir.Progression.SoloTheory.Evidence.Count==1&&RebirthSkillAwardService.Awards==0,"prepared Solo evidence not reward completion");Assert(!TryApplyDurableOutcome(o,teacher,student,ii,ir,si,sr)&&ir.Progression.SoloTheory.Evidence.Count==1,"same retry no duplicate");RebirthWorldCharacterRepository.FailSolo=false;Assert(TryApplyDurableOutcome(o,teacher,student,ii,ir,si,sr),"exact original continuation");Assert(o.SoloEvidenceApplied&&o.RewardApplied&&ir.Saved.Evidence.Count==1&&RebirthSkillAwardService.Awards==1,"saved Solo then original reward");Assert(RebirthTeachingOutcomeStore.Snapshot().Length==0,"all four retire original");Assert(!TryApplyDurableOutcome(o,teacher,student,ii,ir,si,sr)&&RebirthSkillAwardService.Awards==1,"retired callback rejected before mutation");var legacy=new RebirthTeachingDurableOutcome{OutcomeId="legacy",InstructorStorageKey=ii.StorageKey,StudentStorageKey=si.StorageKey,InstructorCreationId=ir.Origin.CreationId,StudentCreationId=sr.Origin.CreationId,SkillId="skill.cooking",HistoryKey="legacy",HistoryTargetCount=1,CompletedUtcTicks=2,StudentKnowledgeTarget=43,TeacherAward=.4f};Assert(RebirthTeachingOutcomeStore.TryReserve(legacy,out error)&&TryApplyDurableOutcome(legacy,teacher,student,ii,ir,si,sr)&&ir.Saved.Evidence.Count==1,"legacy stages preserve behavior without retroactive Solo");Console.WriteLine(count+" PASS actual Teaching orchestration + original journal + Solo evidence producer");}
}