using System;using System.Collections.Generic;using System.Linq;using UnityEngine;
namespace UnityEngine {public struct Vector3 {public float x,y,z;public Vector3(float a,float b,float c){x=a;y=b;z=c;}public static Vector3 up=>new Vector3(0,1,0);public static Vector3 operator+(Vector3 a,Vector3 b)=>new Vector3(a.x+b.x,a.y+b.y,a.z+b.z);}public class GameObject{}public class Transform{public GameObject gameObject=new GameObject();}public static class Object{public static int Destroyed;public static void Destroy(GameObject o){Destroyed++;}}}
public class ItemValue{public string Data;}
public class ItemStack{public ItemValue itemValue;public int count;public bool IsEmpty()=>count==0;}
public class Grid{public ItemStack[] items;}public class Bag{public Grid ItemGrid;}
public struct Vector3i{public int x,y,z;}public class Entity{public bool addedToChunk;public Vector3i chunkPosAddedEntityTo;public int entityId;public Bag bag;public Transform RootTransform=new Transform();}
public class EntityItem:Entity{public ItemStack itemStack;}
public class EntityRebirthGearRecoveryItem:EntityItem{public RebirthGearRecoveryIdentity RecoveryIdentity;}
public class EntityRebirthGearRecoveryBackpack:Entity{public RebirthGearRecoveryIdentity RecoveryIdentity;}
public class EntityPlayer:Entity{public World world;public Vector3 GetPosition()=>new Vector3(1,45,3);}
public class ClientInfo{}
public class World{public ChunkCluster ChunkCache=new ChunkCluster();public bool Remote;public int Spawns;public Action<Entity> OnSpawn;public Dictionary<int,Entity> Entities=new Dictionary<int,Entity>();public bool IsRemote()=>Remote;public Entity GetEntity(int id)=>Entities.TryGetValue(id,out var e)?e:null;public ulong GetWorldTime()=>123;public void SpawnEntityInWorld(Entity e){Spawns++;Entities.Add(e.entityId,e);OnSpawn?.Invoke(e);}}
public class GameManager{public static GameManager Instance;public World World;}
public class ConnectionManager{public bool IsServer=true;}
public static class SingletonMonoBehaviour<T>{public static T Instance;}
public static class ThreadManager{public static bool Main=true;public static bool IsMainThread()=>Main;}
public class EntityClass{public static int FromString(string name)=>name=="rebirthGearRecoveryBackpackV1"?43:42;public Type classname;public static bool Registered=true;public static EntityClass GetEntityClass(int id)=>Registered?new EntityClass{classname=id==42?typeof(EntityRebirthGearRecoveryItem):typeof(EntityRebirthGearRecoveryBackpack)}:null;}
public class EntityCreationData{public int Id;public bool Backpack;public ItemStack[] Items;public RebirthGearRecoveryIdentity Marker;}
public static class EntityFactory{public static int nextEntityID,Creates;public static Action<Entity> OnCreate;public static bool Throw;public static Entity CreateEntity(EntityCreationData d){Creates++;if(Throw)throw new Exception("factory");Entity e;if(d.Backpack)e=new EntityRebirthGearRecoveryBackpack{RecoveryIdentity=d.Marker,bag=new Bag{ItemGrid=new Grid{items=d.Items}}};else e=new EntityRebirthGearRecoveryItem{RecoveryIdentity=d.Marker,itemStack=d.Items[0]};e.entityId=d.Id;OnCreate?.Invoke(e);return e;}}
public class Support{public RebirthGearTransferState PendingGearTransfer;public RebirthGearTransferPhase GearTransferPhase=RebirthGearTransferPhase.GearCommitted;}
public class Record{public string StablePlayerKey="owner";public Support Support=new Support();}
public class Identity{public string StorageKey="owner";}
public static class RebirthWorldCharacterService{public static Record Record;public static Identity Identity=new Identity();public static void MarkDirty(Record r,string reason){}public static bool TryGetIdentity(EntityPlayer p,out Identity identity){identity=Identity;return identity!=null;}}
public static class RebirthRemoteGearInventorySource{public static bool Authorized=true;public static bool TryResolve(EntityPlayer p,ClientInfo s,string c,out Record r){r=RebirthWorldCharacterService.Record;return Authorized&&r!=null&&RebirthSurvivorRequestScope.Matches(c,r.Support.PendingGearTransfer.CreationId);}}
public static class RebirthWorldCharacterRepository{public static bool Saved=true;public static int Writes;public static void SaveIfDirty(Identity i,string reason){Writes++;}public static bool IsCurrentCachedRecord(Record r)=>ReferenceEquals(r,RebirthWorldCharacterService.Record);public static bool HasSavedGearTransfer(Identity i,RebirthGearTransferState p,RebirthGearTransferPhase phase)=>Saved&&ReferenceEquals(p,RebirthWorldCharacterService.Record.Support.PendingGearTransfer);}
public static class RebirthGearTransferSavedWitness{public static bool Matches(Support s,string c,RebirthGearTransferState p,RebirthGearTransferPhase phase)=>s.GearTransferPhase==phase&&ReferenceEquals(p,s.PendingGearTransfer)&&RebirthSurvivorRequestScope.Matches(c,p.CreationId);}
public static class RebirthRemoteGearAppliedConfirmation{public static bool Save=true;public static Action OnSave;public static bool TryRecordRecoveryAttempt(EntityPlayer p,ClientInfo s,string c,string tx,RebirthGearRecoveryAttempt a,out RebirthGearTransferState checkpoint){checkpoint=null;var record=RebirthWorldCharacterService.Record;if(!Save||!record.Support.PendingGearTransfer.TryAppendRecoveryAttempt(a,out var next))return false;record.Support.PendingGearTransfer=next;checkpoint=next;OnSave?.Invoke();return true;}}
public static class RebirthNativeItemCodec{public static string Encode(ItemValue value)=>value.Data;}
public static class RebirthGearRecoveryCreationData{public static bool Build=true;public static bool TryBuild(RebirthGearTransferState state,Guid pub,string key,int owner,int classId,out EntityCreationData data){data=null;if(!Build)return false;state.TryGetPlan(out var plan);state.TryGetRecoveryManifest(out var manifest);state.TryGetRecoveryAttempt(pub,out var attempt);var publication=manifest.ToXml().Elements().Single(e=>(string)e.Attribute("id")==pub.ToString("N"));var indices=publication.Elements().Select(e=>int.Parse((string)e.Attribute("index"))).ToArray();RebirthGearRecoveryIdentity.TryCreate(key,state.CreationId,Guid.Parse(state.TransactionId),pub,indices[0],out var marker);data=new EntityCreationData{Id=attempt.EntityId,Backpack=classId==43,Marker=marker,Items=indices.Select(i=>new ItemStack{count=plan.Recovery[i].Item.Count,itemValue=new ItemValue{Data=plan.Recovery[i].Item.ItemData}}).ToArray()};return true;}}
public class Chunk{public long Key;public bool IsLocked,InProgressSaving,NeedsDecoration,InProgressDecorating,NeedsLightCalculation,InProgressLighting;}
public class ChunkCluster{public bool Available=true;public Chunk Loaded=new Chunk();public int LastX,LastZ;public object ChunkProvider=new ChunkProviderGenerateWorld();public Chunk GetChunkSync(int x,int z){LastX=x;LastZ=z;return Available?Loaded:null;}}
public class ChunkProviderGenerateWorld{public RegionFileManager m_RegionFileManager=new RegionFileManager();}
public class RegionFileAccessSectorBased{}
public class RegionFileManager{public int Snapshots;public bool FlagSet,Throw;public Action OnSnapshot;public object regionFileAccess=new RegionFileAccessSectorBased();public string saveDirectory=System.IO.Path.GetTempPath();public void SaveChunkSnapshot(Chunk chunk,bool unchanged){Snapshots++;FlagSet=chunk.InProgressSaving&&unchanged;OnSnapshot?.Invoke();if(Throw)throw new Exception("uncertain snapshot queue");}}
public static class RebirthRecoveryRegionCapture{public static bool Capture=true;public static Action OnCapture;public static int RX,RZ,LX,LZ,Captures;public static bool TryCapture(string dir,int rx,int rz,int lx,int lz,Func<bool> current,out byte[] frame){frame=null;Captures++;RX=rx;RZ=rz;LX=lx;LZ=lz;if(!Capture||!current())return false;OnCapture?.Invoke();if(!current())return false;frame=new byte[]{1};return true;}}
public static class RebirthRecoveryChunkPayload{public static bool Decode=true;public static bool TryDecodeNative(byte[] frame,out uint version,out byte[] payload){version=46;payload=new byte[]{1};return Decode;}}
public static class RebirthRecoveryNativeChunkEvidence{public static bool Match=true;public static int LastY;public static Action OnMatch;public static bool TryMatch(byte[] payload,uint version,int x,int y,int z,RebirthGearTransferState state,Guid pub,string key,int pack,int item,Func<bool> current,out int end){end=0;LastY=y;if(!Match||!current())return false;OnMatch?.Invoke();if(!current())return false;end=1;return true;}}
class Program{
 static int checks;static EntityPlayer player;static ClientInfo sender=new ClientInfo();static RebirthGearTransferState original;static Guid publication;static bool backpack;static World world;
 static void Check(bool value,string label){if(!value)throw new Exception(label);checks++;}
 static void Reset(bool pack=false){backpack=pack;world=new World();player=new EntityPlayer{entityId=7,world=world};world.Entities[7]=player;GameManager.Instance=new GameManager{World=world};SingletonMonoBehaviour<ConnectionManager>.Instance=new ConnectionManager();ThreadManager.Main=true;EntityClass.Registered=true;EntityFactory.nextEntityID=501;EntityFactory.Creates=0;EntityFactory.Throw=false;EntityFactory.OnCreate=null;UnityEngine.Object.Destroyed=0;RebirthWorldCharacterService.Record=new Record();RebirthWorldCharacterService.Identity=new Identity();RebirthRemoteGearInventorySource.Authorized=true;RebirthWorldCharacterRepository.Saved=true;RebirthRemoteGearAppliedConfirmation.Save=true;RebirthRemoteGearAppliedConfirmation.OnSave=null;RebirthGearRecoveryCreationData.Build=true;
 var plan=new RebirthGearInventoryPlan{BagSlotsBefore=pack?65:52,BagSlotsAfter=52,BeltSlotsBefore=pack?4:5,BeltSlotsAfter=4,GearAfter=new RebirthGearInventoryPlan.Stack{ItemData="Ag==",Count=1}};plan.Changes.Add(new RebirthGearInventoryPlan.Change{IsBag=true,Index=0,Before=new RebirthGearInventoryPlan.Stack{ItemData="Ag==",Count=1}});var stack=new RebirthGearInventoryPlan.Stack{ItemData="AQ==",Count=2};plan.Changes.Add(new RebirthGearInventoryPlan.Change{IsBag=pack,Index=pack?52:4,Before=stack});plan.Recovery.Add(new RebirthGearInventoryPlan.RecoveryEntry{Origin=pack?RebirthGearInventoryPlan.RecoveryOrigin.Backpack:RebirthGearInventoryPlan.RecoveryOrigin.Belt,SourceIndex=pack?52:4,Item=stack});if(!RebirthGearTransferState.TryCreate(Guid.NewGuid().ToString("N"),Guid.NewGuid().ToString("N"),pack?"backpack":"belt",2,plan,out original))throw new Exception("setup");original.TryGetRecoveryManifest(out var manifest);publication=Guid.Parse((string)manifest.ToXml().Elements().Single().Attribute("id"));RebirthWorldCharacterService.Record.Support.PendingGearTransfer=original;}
 static bool Publish()=>RebirthGearRecoveryPublication.TryPublishFirst(player,sender,original.CreationId,original.TransactionId,publication,backpack?43:42);
 static bool Attempted()=>RebirthWorldCharacterService.Record.Support.PendingGearTransfer.TryGetRecoveryAttempt(publication,out _);
 static void Main(){
 Reset();EntityClass.Registered=false;Check(!Publish()&&!Attempted()&&EntityFactory.Creates==0&&EntityFactory.nextEntityID==501,"unregistered class refuses before reservation/save");
 Reset();RebirthWorldCharacterRepository.Saved=false;Check(!Publish()&&!Attempted()&&EntityFactory.Creates==0,"unsaved original refuses");
 Reset();EntityFactory.OnCreate=e=>Check(Attempted(),"save precedes native factory");Check(Publish()&&world.Spawns==1&&Attempted(),"valid item first publication");Check(!Publish()&&world.Spawns==1&&EntityFactory.Creates==1,"retry refuses second factory/spawn");
 Reset(true);Check(Publish()&&world.Spawns==1&&Attempted(),"valid grouped backpack publication");
 Reset();RebirthRemoteGearAppliedConfirmation.Save=false;Check(!Publish()&&!Attempted()&&EntityFactory.Creates==0,"failed checkpoint prevents factory");
 Reset();EntityFactory.Throw=true;Check(!Publish()&&Attempted()&&world.Spawns==0,"factory exception retains attempt");Check(!Publish()&&EntityFactory.Creates==1,"factory failure retry cannot respawn");
 Reset();EntityFactory.OnCreate=e=>((EntityRebirthGearRecoveryItem)e).RecoveryIdentity=null;Check(!Publish()&&Attempted()&&world.Spawns==0&&UnityEngine.Object.Destroyed==1,"missing marker destroys unspawned result");
 Reset();EntityFactory.OnCreate=e=>((EntityItem)e).itemStack.count--;Check(!Publish()&&world.Spawns==0&&UnityEngine.Object.Destroyed==1&&Attempted(),"wrong restored count refuses spawn");
 Reset();EntityFactory.OnCreate=e=>((EntityItem)e).itemStack.itemValue.Data="Aw==";Check(!Publish()&&world.Spawns==0&&UnityEngine.Object.Destroyed==1,"wrong restored metadata refuses spawn");
 Reset();RebirthRemoteGearAppliedConfirmation.OnSave=()=>GameManager.Instance=new GameManager{World=new World()};Check(!Publish()&&Attempted()&&EntityFactory.Creates==0,"world replacement after save prevents factory");
 Reset();EntityFactory.OnCreate=e=>SingletonMonoBehaviour<ConnectionManager>.Instance=new ConnectionManager();Check(!Publish()&&world.Spawns==0&&UnityEngine.Object.Destroyed==1&&Attempted(),"session replacement during factory refuses spawn");
 Reset();world.OnSpawn=e=>throw new Exception("after spawn");Check(!Publish()&&Attempted()&&world.Spawns==1&&world.GetEntity(501)!=null&&UnityEngine.Object.Destroyed==0,"uncertain spawned effect retained without destruction");Check(!Publish()&&world.Spawns==1,"uncertain spawn retry does not duplicate");
 Reset();world.Entities[501]=new Entity();Check(!Publish()&&!Attempted()&&EntityFactory.Creates==0,"reserved entity collision refuses");
 Reset();RebirthRemoteGearAppliedConfirmation.OnSave=()=>player.entityId=8;Check(!Publish()&&Attempted()&&EntityFactory.Creates==0,"owner entity ID change after save refuses");
 Reset();ThreadManager.Main=false;Check(!Publish()&&!Attempted(),"worker thread refuses");
 Reset();EntityFactory.OnCreate=e=>{var item=(EntityRebirthGearRecoveryItem)e;var marker=item.RecoveryIdentity;RebirthGearRecoveryIdentity.TryCreate(marker.OwnerKey,marker.CreationId,marker.TransactionId,marker.PublicationId,188,out var wrong);item.RecoveryIdentity=wrong;};Check(!Publish()&&Attempted()&&world.Spawns==0&&UnityEngine.Object.Destroyed==1,"wrong original recovery entry marker refuses");
 Reset(true);EntityFactory.OnCreate=e=>{var grid=e.bag.ItemGrid;grid.items=grid.items.Concat(new[]{new ItemStack{count=1,itemValue=new ItemValue{Data="Aw=="}}}).ToArray();};Check(!Publish()&&world.Spawns==0&&UnityEngine.Object.Destroyed==1,"unplanned backpack tail item refuses");
 Reset();EntityFactory.OnCreate=e=>RebirthRemoteGearInventorySource.Authorized=false;Check(!Publish()&&Attempted()&&world.Spawns==0&&UnityEngine.Object.Destroyed==1,"lost sender authorization during factory refuses");
 Reset();Check(Publish(),"disk observer fixture saved attempt setup");int factoryBeforeObserve=EntityFactory.Creates,spawnsBeforeObserve=world.Spawns;
 Func<bool> observe=()=>RebirthRecoveryWorldDiskEvidence.TryObserve(player,sender,original.CreationId,original.TransactionId,publication,-33,0,-1,43,42);
 Check(observe()&&RebirthRecoveryRegionCapture.RX==-2&&RebirthRecoveryRegionCapture.RZ==-1&&RebirthRecoveryRegionCapture.LX==31&&RebirthRecoveryRegionCapture.LZ==31&&EntityFactory.Creates==factoryBeforeObserve&&world.Spawns==spawnsBeforeObserve,"authenticated disk orchestration maps negative chunks without native effects");
 RebirthWorldCharacterRepository.Saved=false;Check(!observe(),"unsaved pending refuses disk observation");RebirthWorldCharacterRepository.Saved=true;
 RebirthRecoveryRegionCapture.OnCapture=()=>((ChunkProviderGenerateWorld)world.ChunkCache.ChunkProvider).m_RegionFileManager.saveDirectory=System.IO.Path.Combine(System.IO.Path.GetTempPath(),"changed");Check(!observe(),"region directory change during capture refuses");RebirthRecoveryRegionCapture.OnCapture=null;
 RebirthRecoveryChunkPayload.Decode=false;Check(!observe(),"failed chunk decode refuses observation");RebirthRecoveryChunkPayload.Decode=true;
 RebirthRecoveryNativeChunkEvidence.OnMatch=()=>RebirthRemoteGearInventorySource.Authorized=false;Check(!observe(),"authentication lost during matching refuses");RebirthRecoveryNativeChunkEvidence.OnMatch=null;RebirthRemoteGearInventorySource.Authorized=true;
 RebirthRecoveryNativeChunkEvidence.OnMatch=()=>GameManager.Instance=new GameManager{World=world};Check(!observe(),"game manager changed during matching refuses");RebirthRecoveryNativeChunkEvidence.OnMatch=null;
 ThreadManager.Main=false;Check(!observe(),"worker thread cannot observe live world save context");ThreadManager.Main=true;
 Reset();Check(Publish(),"receipt fixture original attempted publication setup");int writesBeforeReceipt=RebirthWorldCharacterRepository.Writes;
 RebirthRecoveryNativeChunkEvidence.Match=false;Check(!RebirthRecoveryWorldDiskEvidence.TryRecordReceipt(player,sender,original.CreationId,original.TransactionId,publication,-33,0,-1,43,42)&&RebirthWorldCharacterRepository.Writes==writesBeforeReceipt,"unverified disk publication cannot write receipt");RebirthRecoveryNativeChunkEvidence.Match=true;
 Check(RebirthRecoveryWorldDiskEvidence.TryRecordReceipt(player,sender,original.CreationId,original.TransactionId,publication,-33,0,-1,43,42)&&RebirthWorldCharacterService.Record.Support.PendingGearTransfer.HasRecoveryPublicationReceipt(publication)&&world.Spawns==1,"verified disk publication writes receipt without another spawn");
 Check(!RebirthRecoveryWorldDiskEvidence.TryRecordReceipt(player,sender,original.CreationId,original.TransactionId,publication,-33,0,-1,43,42)&&RebirthWorldCharacterRepository.Writes==writesBeforeReceipt+1,"duplicate disk receipt cannot write again");
 Reset();RebirthGearRecoveryEntityCapture.IsInstalled=false;Check(!RebirthGearRecoveryDispatcher.TryAdvance(player,sender,original.CreationId,original.TransactionId)&&!Attempted(),"dispatcher refuses missing capture before effect");RebirthGearRecoveryEntityCapture.IsInstalled=true;
 Check(RebirthGearRecoveryDispatcher.TryAdvance(player,sender,original.CreationId,original.TransactionId)&&world.Spawns==1,"dispatcher publishes original unattempted identity once");
 RebirthRecoveryNativeChunkEvidence.Match=false;Check(!RebirthGearRecoveryDispatcher.TryAdvance(player,sender,original.CreationId,original.TransactionId)&&world.Spawns==1,"dispatcher uncertain attempt never respawns");RebirthRecoveryNativeChunkEvidence.Match=true;
 Check(RebirthGearRecoveryDispatcher.TryAdvance(player,sender,original.CreationId,original.TransactionId)&&world.Spawns==1&&RebirthWorldCharacterService.Record.Support.PendingGearTransfer.HasAllRecoveryPublicationReceipts,"dispatcher attempted publication becomes saved receipt without spawn");
 Check(RebirthGearRecoveryDispatcher.TryAdvance(player,sender,original.CreationId,original.TransactionId)&&world.Spawns==1,"fully receipted dispatcher performs no spawn");
 Reset();Check(Publish(),"relocation saved original attempt setup");var relocated=world.GetEntity(501);relocated.addedToChunk=true;relocated.chunkPosAddedEntityTo=new Vector3i{x=-33,y=12,z=-1};
 Check(RebirthGearRecoveryDispatcher.TryAdvance(player,sender,original.CreationId,original.TransactionId)&&RebirthRecoveryRegionCapture.RX==-2&&RebirthRecoveryRegionCapture.LX==31&&RebirthRecoveryNativeChunkEvidence.LastY==0&&world.Spawns==1,"exact marked entity relocation selects current chunk without respawn");
 Reset();Check(Publish(),"foreign relocation original attempt setup");var foreign=(EntityRebirthGearRecoveryItem)world.GetEntity(501);foreign.addedToChunk=true;foreign.chunkPosAddedEntityTo=new Vector3i{x=-33,z=-1};foreign.RecoveryIdentity=null;
 Check(RebirthGearRecoveryDispatcher.TryAdvance(player,sender,original.CreationId,original.TransactionId)&&RebirthRecoveryRegionCapture.RX==0&&RebirthRecoveryRegionCapture.LX==0,"unmarked entity cannot redirect saved evidence lookup");
 Reset();Check(Publish(),"snapshot request original saved attempt setup");var snapshotEntity=world.GetEntity(501);snapshotEntity.addedToChunk=true;snapshotEntity.chunkPosAddedEntityTo=new Vector3i{x=-33,y=12,z=-1};var snapshotRegions=((ChunkProviderGenerateWorld)world.ChunkCache.ChunkProvider).m_RegionFileManager;
 Func<bool> queue=()=>RebirthGearRecoverySnapshotRequest.TryQueueOriginal(player,sender,original.CreationId,original.TransactionId,publication);
 Check(queue()&&snapshotRegions.Snapshots==1&&snapshotRegions.FlagSet&&!world.ChunkCache.Loaded.InProgressSaving&&world.ChunkCache.LastX==-33&&world.ChunkCache.LastZ==-1&&!RebirthWorldCharacterService.Record.Support.PendingGearTransfer.HasRecoveryPublicationReceipt(publication),"targeted original loaded chunk queued under native saving flag without receipt");
 Check(!queue()&&snapshotRegions.Snapshots==1,"same chunk request throttled no repeated snapshot");
 Reset();Check(Publish(),"snapshot missingchunk setup");snapshotEntity=world.GetEntity(501);snapshotEntity.addedToChunk=true;world.ChunkCache.Available=false;Check(!queue(),"snapshot request cannot load missing chunk");
 Reset();Check(Publish(),"snapshot wrong payload setup");snapshotEntity=world.GetEntity(501);snapshotEntity.addedToChunk=true;((EntityItem)snapshotEntity).itemStack.count--;snapshotRegions=((ChunkProviderGenerateWorld)world.ChunkCache.ChunkProvider).m_RegionFileManager;Check(!queue()&&snapshotRegions.Snapshots==0,"changed recovery payload cannot schedule original snapshot");
 foreach(int blocked in new[]{0,1,2,3,4,5}){Reset();Check(Publish(),"snapshot readiness setup "+blocked);snapshotEntity=world.GetEntity(501);snapshotEntity.addedToChunk=true;var chunk=world.ChunkCache.Loaded;chunk.IsLocked=blocked==0;chunk.InProgressSaving=blocked==1;chunk.NeedsDecoration=blocked==2;chunk.InProgressDecorating=blocked==3;chunk.NeedsLightCalculation=blocked==4;chunk.InProgressLighting=blocked==5;snapshotRegions=((ChunkProviderGenerateWorld)world.ChunkCache.ChunkProvider).m_RegionFileManager;Check(!queue()&&snapshotRegions.Snapshots==0&&chunk.InProgressSaving==(blocked==1),"native chunk readiness refuses without changing busy flag "+blocked);}
 Reset();Check(Publish(),"snapshot uncertainqueue setup");snapshotEntity=world.GetEntity(501);snapshotEntity.addedToChunk=true;snapshotRegions=((ChunkProviderGenerateWorld)world.ChunkCache.ChunkProvider).m_RegionFileManager;snapshotRegions.Throw=true;Check(!queue()&&snapshotRegions.Snapshots==1&&!world.ChunkCache.Loaded.InProgressSaving&&Attempted(),"uncertain snapshot resets own saving flag and retains original attempt");Check(!queue()&&snapshotRegions.Snapshots==1,"uncertain queue throttled without duplicate effect");
 Reset();Check(Publish(),"snapshot replacedmanager setup");snapshotEntity=world.GetEntity(501);snapshotEntity.addedToChunk=true;snapshotRegions=((ChunkProviderGenerateWorld)world.ChunkCache.ChunkProvider).m_RegionFileManager;snapshotRegions.OnSnapshot=()=>SingletonMonoBehaviour<ConnectionManager>.Instance=new ConnectionManager();Check(!queue()&&snapshotRegions.Snapshots==1&&!world.ChunkCache.Loaded.InProgressSaving&&!RebirthWorldCharacterService.Record.Support.PendingGearTransfer.HasRecoveryPublicationReceipt(publication),"manager replacement afterqueue is no receipt");
 Reset();Check(Publish(),"snapshot missing saved proof setup");snapshotEntity=world.GetEntity(501);snapshotEntity.addedToChunk=true;RebirthWorldCharacterRepository.Saved=false;snapshotRegions=((ChunkProviderGenerateWorld)world.ChunkCache.ChunkProvider).m_RegionFileManager;Check(!queue()&&snapshotRegions.Snapshots==0,"unsaved original attempt cannot queue chunk");
 Reset();Check(Publish(),"snapshot missing region path setup");snapshotEntity=world.GetEntity(501);snapshotEntity.addedToChunk=true;snapshotRegions=((ChunkProviderGenerateWorld)world.ChunkCache.ChunkProvider).m_RegionFileManager;snapshotRegions.saveDirectory=null;Check(!queue()&&snapshotRegions.Snapshots==0,"missing original region path cannot silently queue");
 Console.WriteLine("PASS "+checks+" whole actual first-publication service checks. Actual plan/state/manifest/attempt/identity; native factory/world/save/authentication/creation-data, disk capture/matching and journal adapter are doubles. No game execution.");
 }
}public static class RebirthGearTransferJournal{public static bool RecordRecoveryPublicationReceipt(Support state,string tx,string creation,Guid pub,Func<bool> save){var old=state.PendingGearTransfer;if(!old.TryAppendRecoveryPublicationReceipt(pub,out var next))return false;state.PendingGearTransfer=next;if(save())return true;state.PendingGearTransfer=old;return false;}}public static class RebirthGearRecoveryEntityCapture{public static bool IsInstalled=true;}