using System;using System.Globalization;using System.Linq;using System.Xml.Linq;using UnityEngine;
internal sealed class RebirthNpcNativeRigidbodyState
{
 private readonly XElement image;private RebirthNpcNativeRigidbodyState(XElement n){image=new XElement(n);}internal XElement Write()=>new XElement(image);
 internal static bool TryRead(XElement n,out RebirthNpcNativeRigidbodyState state){state=null;string[] numbers={"mass","drag","angularDrag","vx","vy","vz","ax","ay","az"};if(n==null||n.Name!="rigidDynamics"||n.Attributes().Count()!=15||n.HasElements||n.Nodes().Any(x=>!(x is XText t&&string.IsNullOrWhiteSpace(t.Value)))||n.Attributes().Any(a=>a.IsNamespaceDeclaration||a.Name.NamespaceName.Length!=0)||(string)n.Attribute("version")!="1"||(string)n.Attribute("required")!="1"||((string)n.Attribute("gravity")!="0"&&(string)n.Attribute("gravity")!="1"))return false;foreach(var key in numbers)if(!float.TryParse((string)n.Attribute(key),NumberStyles.Float,CultureInfo.InvariantCulture,out var v)||float.IsNaN(v)||float.IsInfinity(v)||v.ToString("R",CultureInfo.InvariantCulture)!=(string)n.Attribute(key))return false;if(N(n,"mass")<=0||N(n,"drag")<0||N(n,"angularDrag")<0)return false;if(!I(n,"constraints",out var constraints)||(constraints&~126)!=0||!I(n,"interpolation",out var interpolation)||interpolation<0||interpolation>2||!I(n,"collision",out var collision)||collision<0||collision>3)return false;state=new RebirthNpcNativeRigidbodyState(n);return true;}
 internal static bool TryCapture(Rigidbody body,out RebirthNpcNativeRigidbodyState state){state=null;try{if(body==null||!Enum.IsDefined(typeof(RigidbodyInterpolation),body.interpolation)||!Enum.IsDefined(typeof(CollisionDetectionMode),body.collisionDetectionMode))return false;var n=new XElement("rigidDynamics",A("version",1),A("required",1),A("mass",body.mass),A("drag",body.drag),A("angularDrag",body.angularDrag),A("gravity",body.useGravity?1:0),A("constraints",(int)body.constraints),A("interpolation",(int)body.interpolation),A("collision",(int)body.collisionDetectionMode));V(n,body.velocity,"v");V(n,body.angularVelocity,"a");return TryRead(n,out state);}catch(Exception){return false;}}
 internal bool Apply(Rigidbody body,bool release){try{body.mass=N(image,"mass");body.drag=N(image,"drag");body.angularDrag=N(image,"angularDrag");body.useGravity=(string)image.Attribute("gravity")=="1";body.constraints=(RigidbodyConstraints)Int("constraints");body.interpolation=(RigidbodyInterpolation)Int("interpolation");if(release){body.collisionDetectionMode=(CollisionDetectionMode)Int("collision");if(body.isKinematic){if(!Same(Vector("v"),Vector3.zero)||!Same(Vector("a"),Vector3.zero))return false;}else{body.velocity=Vector("v");body.angularVelocity=Vector("a");}}return Matches(body,release,release);}catch(Exception){return false;}}
 internal bool Matches(Rigidbody body,bool collision,bool motion){try{return body!=null&&body.mass==N(image,"mass")&&body.drag==N(image,"drag")&&body.angularDrag==N(image,"angularDrag")&&body.useGravity==((string)image.Attribute("gravity")=="1")&&(int)body.constraints==Int("constraints")&&(int)body.interpolation==Int("interpolation")&&(!collision||(int)body.collisionDetectionMode==Int("collision"))&&(!motion||Same(body.velocity,Vector("v"))&&Same(body.angularVelocity,Vector("a")));}catch(Exception){return false;}}
 internal bool CompatibleWithKinematic(bool value)=>!value||Same(Vector("v"),Vector3.zero)&&Same(Vector("a"),Vector3.zero);
 private static bool Same(Vector3 a,Vector3 b)=>a.x==b.x&&a.y==b.y&&a.z==b.z;
 private Vector3 Vector(string prefix)=>new Vector3(N(image,prefix+"x"),N(image,prefix+"y"),N(image,prefix+"z"));private int Int(string key)=>int.Parse((string)image.Attribute(key),CultureInfo.InvariantCulture);
 private static float N(XElement n,string key)=>float.Parse((string)n.Attribute(key),CultureInfo.InvariantCulture);private static bool I(XElement n,string key,out int v)=>int.TryParse((string)n.Attribute(key),NumberStyles.None,CultureInfo.InvariantCulture,out v)&&v.ToString(CultureInfo.InvariantCulture)==(string)n.Attribute(key);
 private static XAttribute A(string key,object v)=>new XAttribute(key,v is float f?f.ToString("R",CultureInfo.InvariantCulture):Convert.ToString(v,CultureInfo.InvariantCulture));private static void V(XElement n,Vector3 v,string p){n.Add(A(p+"x",v.x),A(p+"y",v.y),A(p+"z",v.z));}
}
