using System;using System.IO;using System.Linq;
public class PlayerUI{public Xui xui=new();}public class Xui{public bool IsUsingItemActionEntryUse;public Drag DragAndDropWindow=new();}public class Drag{public CursorStack CurrentStack=new();}public class CursorStack{public bool IsEmpty()=>!Cold.Cursor;}
public static class RebirthBackpackLibraryReservation{public static bool IsHeld(EntityPlayerLocal p)=>Cold.Library;}
public static class RemoteResourceClientTransactionCoordinator{public static bool HasPendingInventoryOperation(EntityPlayerLocal p)=>Cold.Pending;}
public static class RebirthToolbeltCapacity{public static int GetOwnedSlotCount(EntityPlayerLocal p,int len)=>4;}
public static class RebirthGearPreparationOfferBinding{public static bool MatchesBound(RebirthGearPreparationIntent i,RebirthGearInventorySnapshot s,RebirthGearTransferState t,Guid w)=>false;}
public static class RebirthGearPreparationRecoveryBinding{public static bool TryRecoverOriginal(RebirthGearPreparationIntent i,RebirthGearTransferState t,RebirthGearInventorySnapshot s,Guid w,int owned,float r,out object v){v=null;return false;}}
public class PlayerDataFile{public MemoryStream buffData;public RebirthGearInventoryPlan.Stack[] Bag,Belt;}
public static class RebirthGearNativePlayerFile{public static PlayerDataFile File;public static Action ReadAction;public static bool TryRead(RebirthStablePlayerIdentity owner,out PlayerDataFile f){f=File;ReadAction?.Invoke();return f!=null;}}
public static class RebirthPlayerDataInventory{public static object ReadSlots(PlayerDataFile f,bool bag)=>bag?f.Bag:f.Belt;}
public static class EntityBuffs{public const int Version=2;}public class BuffValue{public void Read(PooledBinaryReader r,int version)=>throw new Exception("nonzero buffs not qualified");}
public class PooledBinaryReader:BinaryReader{public PooledBinaryReader():base(new MemoryStream()){}public void SetBaseStream(Stream s){BaseStream.Position=0;data=new BinaryReader(s);}BinaryReader data;public override byte ReadByte()=>data.ReadByte();public override ushort ReadUInt16()=>data.ReadUInt16();public override string ReadString()=>data.ReadString();public override float ReadSingle()=>data.ReadSingle();}
public static class MemoryPools{public static ReaderPool poolBinaryReader=new();}public class ReaderPool{public PooledBinaryReader AllocSync(bool b)=>new();}
static class Cold{public static bool Action,Cursor,Library,Pending;}
class Program{
static int n;static void C(bool v,string s){if(!v)throw new Exception(s);n++;}
static void Main(){foreach(var creation in new[]{Guid.NewGuid().ToString("N"),"legacy-"+new string('a',64)}){
var w=Guid.NewGuid();var image=new RebirthGearInventorySnapshot{Bag=Enumerable.Range(0,52).Select(_=>new RebirthGearInventoryPlan.Stack()).ToArray(),Belt=Enumerable.Range(0,4).Select(_=>new RebirthGearInventoryPlan.Stack()).ToArray(),OwnedBeltSlots=4};
image.Bag[7]=new(){ItemData="AQIDBA==",Count=3};image.Belt[2]=new(){ItemData="BQYH",Count=2};RebirthGearPreparationIntent.TryCreateUnequip(creation,Guid.NewGuid(),3,"backpack",image,out var intent);RebirthGearPreparationMarker.TryEncode(w,4,intent,out var marker);string receipt="rbGear_"+intent.TransactionId.ToString("N");EntityPlayerLocal p=null;Peer peer=null;
void Reset(float phase=-1,string projection=null){RebirthGearOwnerReservation.ResetSession();Cold.Action=Cold.Cursor=Cold.Library=Cold.Pending=false;D.Main=D.Mode=D.Owner=D.Capture=true;D.CreationHold=false;D.Canonical="owner";D.WorldGuid=w.ToString("N");D.Creation=projection;peer=new();var world=new World{worldState=new(){Guid=D.WorldGuid}};p=new(){world=world};world.Player=world.Entity=p;p.bag.ItemGrid.items=image.Bag;p.inventory.ItemGrid.items=image.Belt;p.Buffs.CVars[marker]=1;p.Buffs.CVars[receipt]=phase;GameManager.Instance=new(){World=world};SingletonMonoBehaviour<ConnectionManager>.Instance=new(){connectionToServer=new[]{peer}};SetFile(marker,phase);RebirthGearNativePlayerFile.ReadAction=null;}
void SetFile(string key,float phase,bool duplicate=false){var ms=new MemoryStream();using(var bw=new BinaryWriter(ms,System.Text.Encoding.UTF8,true)){bw.Write((byte)2);bw.Write((ushort)0);bw.Write((ushort)(duplicate?3:2));bw.Write(key);bw.Write(1f);if(duplicate){bw.Write(key);bw.Write(1f);}bw.Write(receipt);bw.Write(phase);}RebirthGearNativePlayerFile.File=new(){buffData=ms,Bag=image.Bag,Belt=image.Belt};}
Reset();C(RebirthGearOwnerReservation.TryRestoreOriginalBeforeProjection(p,peer)&&RebirthGearOwnerReservation.IsHeld(p),"actual rejected cold preprojection restore");
Reset(-1,creation);C(RebirthGearOwnerReservation.TryRestoreOriginal(p,peer)&&RebirthGearOwnerReservation.MatchesUnpreparedIntent(p,peer,intent),"actual rejected projected restore");
Reset(-1,Guid.NewGuid().ToString("N"));C(!RebirthGearOwnerReservation.TryRestoreOriginalBeforeProjection(p,peer)&&!RebirthGearOwnerReservation.IsHeld(p),"cold foreign projection refuse");
foreach(var fault in new[]{"action","cursor","library","pending","dead","world","owner","case","foreign","duplicate","fileimage","session"}){
Reset();switch(fault){case "action":Cold.Action=true;break;case "cursor":Cold.Cursor=true;break;case "library":Cold.Library=true;break;case "pending":Cold.Pending=true;break;case "dead":p.Dead=true;break;case "world":D.WorldGuid=Guid.NewGuid().ToString();break;case "owner":D.Canonical="foreign";break;case "case":SetFile(marker.ToUpperInvariant(),-1);break;case "foreign":SetFile("_rbgearintent_foreign",-1);break;case "duplicate":SetFile(marker,-1,true);break;case "fileimage":RebirthGearNativePlayerFile.File.Bag=new RebirthGearInventoryPlan.Stack[52];break;case "session":peer.Dead=true;break;}C(!RebirthGearOwnerReservation.TryRestoreOriginalBeforeProjection(p,peer)&&!RebirthGearOwnerReservation.IsHeld(p),"cold refuses "+fault);}
Reset();RebirthGearNativePlayerFile.ReadAction=()=>{GameManager.Instance.World=new();};C(!RebirthGearOwnerReservation.TryRestoreOriginalBeforeProjection(p,peer),"cold world swap during read refuses");
Reset();RebirthGearNativePlayerFile.ReadAction=()=>{SingletonMonoBehaviour<ConnectionManager>.Instance.connectionToServer=new[]{new Peer()};};C(!RebirthGearOwnerReservation.TryRestoreOriginalBeforeProjection(p,peer),"cold peer swap during read refuses");foreach(var phase in new[]{1f,2f}){Reset(phase);bool result=RebirthGearOwnerReservation.TryRestoreOriginalBeforeProjection(p,peer);Console.WriteLine("OBSERVATION cold phase "+phase+" restore="+result+" nooffer="+RebirthGearOwnerReservation.IsHeld(p));}
}Console.WriteLine("COLD PASS "+n+" whole actual reservation/original witness/marker+receipt parsers; native file/UI/physical source synthetic");}}
