import {readFile,writeFile,mkdtemp,unlink,rmdir} from 'node:fs/promises';import {execFile} from 'node:child_process';import {promisify} from 'node:util';import {tmpdir} from 'node:os';import {join,resolve,dirname} from 'node:path';import {fileURLToPath} from 'node:url';
const run=promisify(execFile),here=dirname(fileURLToPath(import.meta.url)),root=resolve(here,'../..'),source=await readFile(join(root,'Scripts/Crafting/Cooking/XUiC_RebirthCookingWorkspace.cs'),'utf8');
function block(source,signature){const a=source.indexOf(signature);if(a<0)throw new Error(signature);let i=source.indexOf('{',a)+1,depth=1;for(;depth&&i<source.length;i++){if(source[i]==='{')depth++;if(source[i]==='}')depth--;}return source.slice(a,i);}
function statement(needle){const lines=source.split(/\r?\n/).filter(l=>l.includes(needle));if(lines.length!==1)throw new Error('statement count '+needle+' '+lines.length);return lines[0].trim();}
const inventory=JSON.parse(await readFile(join(root,'_Documentation/RecipeDescriptionsParallel/COOKING_REMAINING_KEYS_20261006.json'),'utf8'));if(inventory.length!==42)throw new Error('inventory coverage drift');
const rows=(await readFile(join(root,'Config/Localization.csv'),'utf8')).split(/\r?\n/);const extra=['xuiRebirthCookingMissingToolFormat','xuiRebirthStationReadyToProcess','xuiRebirthMillingNoFuel','xuiRebirthMillingIngredientGuide','xuiRebirthStationUnfamiliarRecipe','xuiRebirthStationNoRecipe','xuiRebirthStationProcessingArea','xuiRebirthStationProcess','xuiRebirthStationProcessStatus'];
const templates=[...inventory.map(e=>e.key),...extra].map(key=>{const matches=rows.filter(l=>l.startsWith(key+','));if(matches.length!==1)throw new Error('CSV key count '+key);let value=matches[0].slice(key.length+1);if(value.startsWith('"')&&value.endsWith('"'))value=value.slice(1,-1).replace(/""/g,'"');if(!value.trim())throw new Error('empty key '+key);value=value.replace(/\\n/g,'\n');if(value.includes('\\\n'))throw new Error('stray slash '+key);const expected=inventory.find(e=>e.key===key);if(expected&&value!==expected.english.replace(/\\\\n/g,'\\n').replace(/\\n/g,'\n'))throw new Error('CSV English differs from reviewed inventory '+key);return 'Localization.Values['+JSON.stringify(key)+']='+JSON.stringify(value)+';';}).join('\n');
for(const row of inventory)if(!source.includes('"'+row.key+'"'))throw new Error('unconnected key '+row.key);
const literalAssignments=[...source.matchAll(/status\s*=\s*"([^"\r\n]+)"/g)];if(literalAssignments.length)throw new Error('unlocalized status literal '+literalAssignments[0][1]);
const snippets={OUTCOME:statement('Text("outcomeStatus",')+'\n'+statement('Text("outcomeHint",')+'\n'+statement('Text("ingredientGuide",'),TOOLTIP:statement('string tip=value==null?')+'\nif(swaps!=null)\n'+statement('tip+=string.Format'),STATS:statement('if(hasFood)stats=')+'\n'+statement('if(hasMood)stats+=')+'\n'+statement('stats+=string.Format(RebirthSurvivorUiText.L("xuiRebirthCookingOutputTimeStats"'),COMFORT:statement('Text("actualComfort",!hasMood?'),CHOICE:statement('Caption("choice"+i,'),NAMES:statement('Text("resultName",')+'\n'+statement('Text("outcomeName",'),TITLES:statement('Text("stationQueueTitle",')+'\n'+statement('Caption("cook", milling')+'\n'+statement('Text("outcomeStatusTitle",')};
let fixture=await readFile(join(here,'CookingPresentationFixture.cs'),'utf8');for(const [k,v]of Object.entries(snippets))fixture=fixture.replace('// '+k,v);fixture=fixture.replace('// UI_L',block(await readFile(join(root,'Scripts/Survivor/UI/RebirthSurvivorUiText.cs'),'utf8'),'public static string L(')).replace('// TEMPLATES',templates);
const temp=await mkdtemp(join(tmpdir(),'rebirth-cooking-presentation-'));try{const cs=join(temp,'check.cs'),exe=join(temp,'check.exe');await writeFile(cs,fixture);await run('C:/Program Files/dotnet/dotnet.exe',['C:/Program Files/dotnet/sdk/9.0.301/Roslyn/bincore/csc.dll','/nologo','/target:exe','/out:'+exe,...['mscorlib','System','System.Core'].map(x=>'/r:C:/Windows/Microsoft.NET/Framework64/v4.0.30319/'+x+'.dll'),cs],{windowsHide:true,timeout:10000});console.log((await run(exe,[],{windowsHide:true,timeout:10000})).stdout.trim());}finally{for(const n of ['check.cs','check.exe'])await unlink(join(temp,n)).catch(e=>{if(e.code!=='ENOENT')throw e;});await rmdir(temp);}