import {readFile,writeFile,mkdtemp,unlink,rmdir} from 'node:fs/promises';import {execFile} from 'node:child_process';import {promisify} from 'node:util';import {tmpdir} from 'node:os';import {join,resolve,dirname} from 'node:path';import {fileURLToPath} from 'node:url';
const run=promisify(execFile),here=dirname(fileURLToPath(import.meta.url)),root=resolve(here,'../..');
function block(source,signature){const a=source.indexOf(signature);if(a<0)throw new Error(signature);let i=source.indexOf('{',a)+1,depth=1;for(;depth&&i<source.length;i++){if(source[i]==='{')depth++;if(source[i]==='}')depth--;}if(depth)throw new Error('unclosed '+signature);return source.slice(a,i);}
const outcome=await readFile(join(root,'Scripts/Crafting/UI/PersonalCrafting/RebirthCraftingOutcomeViewModel.cs'),'utf8'),cooking=await readFile(join(root,'Scripts/Crafting/Cooking/XUiC_RebirthCookingWorkspace.cs'),'utf8'),catalogue=await readFile(join(root,'Scripts/Crafting/Cooking/RebirthCookingCatalogue.cs'),'utf8'),ui=await readFile(join(root,'Scripts/Survivor/UI/RebirthSurvivorUiText.cs'),'utf8');
const keys=['xuiRebirthCraftSkillGainTitle','xuiRebirthCraftNoSkill','xuiRebirthCraftPracticeExplanation','xuiRebirthCraftQualityExplanation','xuiRebirthCraftQualityLearningExplanation','xuiRebirthCookingBookLabel','xuiRebirthCookingMagazineLabel','xuiRebirthCookingNoReference','xuiRebirthCookingBookPracticeBonus','xuiRebirthCookingBookBenefit','xuiRebirthCookingMagazineBenefit','xuiRebirthCookingActiveBenefits','xuiRebirthCookingConfirmingPreparation','xuiRebirthCookingPreparationProgress','xuiRebirthCookingPreparationActive','xuiRebirthCookingPreparationOptional','xuiRebirthCookingPrepareAgain','xuiRebirthCookingPrepare','xuiRebirthCookingFinishPreparation','xuiRebirthCookingTechniqueTime','xuiRebirthCookingTechniqueHerb','xuiRebirthCookingTechniqueComfort','xuiRebirthCookingTechniqueNone'];
const lines=(await readFile(join(root,'Config/Localization.csv'),'utf8')).split(/\r?\n/),templates=keys.map(key=>{const matches=lines.filter(s=>s.startsWith(key+','));if(matches.length!==1)throw new Error('key count '+key);let value=matches[0].slice(key.length+1);if(value.startsWith('"')&&value.endsWith('"'))value=value.slice(1,-1).replace(/""/g,'"');if(!value.trim())throw new Error('empty '+key);return 'Localization.Values['+JSON.stringify(key)+']='+JSON.stringify(value)+';';}).join('\n');
function statement(needle){const line=cooking.split(/\r?\n/).find(l=>l.includes(needle));if(!line)throw new Error(needle);return line.trim();}
const benefit=catalogue.split(/\r?\n/).find(l=>l.includes('public static string Benefit(')).trim();
const reference=block(cooking,'string ReferenceText(').replace('string ReferenceText(','public static string ReferenceText(');
const benefitStatements=statement('string benefits=')+'\n'+statement('if(Ready!=null)benefits=')+'\n'+statement('Text("referenceBenefits",benefits)');
let fixture=(await readFile(join(here,'OutcomeTextFixture.cs'),'utf8')).replace('// VIEW_MODEL',block(outcome,'public sealed class RebirthCraftingOutcomeViewModel')).replace('// UI_L',block(ui,'public static string L(')).replace('// TECHNIQUE',benefit).replace('// REFERENCE',reference).replace('// PREPARATION',statement('Text("prepStatus",')+'\n'+statement('Caption("prepare",remaining>0?')).replace('// BENEFIT_LINES',benefitStatements).replace('// GAIN_METHOD',block(outcome,'public static string GainText(')).replace('// TEMPLATES',templates);
const temp=await mkdtemp(join(tmpdir(),'rebirth-outcome-text-'));try{const cs=join(temp,'check.cs'),exe=join(temp,'check.exe');await writeFile(cs,fixture);await run('C:/Program Files/dotnet/dotnet.exe',['C:/Program Files/dotnet/sdk/9.0.301/Roslyn/bincore/csc.dll','/nologo','/target:exe','/out:'+exe,...['mscorlib','System','System.Core'].map(x=>'/r:C:/Windows/Microsoft.NET/Framework64/v4.0.30319/'+x+'.dll'),cs],{windowsHide:true,timeout:10000});console.log((await run(exe,[],{windowsHide:true,timeout:10000})).stdout.trim());}finally{for(const n of ['check.cs','check.exe'])await unlink(join(temp,n)).catch(e=>{if(e.code!=='ENOENT')throw e;});await rmdir(temp);}