using System;
using System.Collections;
using System.IO;
using System.Linq;
using System.Xml.Linq;
// Native scope adapters only are doubles; all domain/codec/store/filesystem code is production.
class World { public WorldState worldState=new WorldState(); public bool IsRemote()=>false; }
class WorldState { public string Guid=System.Guid.NewGuid().ToString("N").ToUpperInvariant(); }
class GameManager { public static GameManager Instance; public World World; }
class ConnectionManager { public bool IsServer=true; }
class SingletonMonoBehaviour<T> { public static T Instance; }
class ThreadManager { public static bool IsMainThread()=>true; }
class GameIO { public static string Path; public static string GetSaveGameDir()=>Path; }
class NativeIterator:IEnumerator{public Action Effects;public int Advances;public object Current=>null;public bool MoveNext(){Advances++;if(Advances==1){Effects?.Invoke();return true;}return false;}public void Reset(){throw new NotSupportedException();}}
static class Program
{
 static int count;static void Check(bool ok,string name){if(!ok)throw new Exception(name);count++;}
 static void Invalid(Action action,string name){bool rejected=false;try{action();}catch(ArgumentException){rejected=true;}catch(FormatException){rejected=true;}Check(rejected,name);}
 static string H(char c)=>new string(c,64);
 static RebirthPoiResetPlan Plan(Guid tx)=>new RebirthPoiResetPlan(tx,RebirthPoiResetCaller.Quest,H('f'),new[]{9L},new[]{7},new int[0],new[]{new RebirthPoiAuthoredResetExpectation(RebirthPoiAuthoredResetKind.Sleeper,0,H('a'),7,true),new RebirthPoiAuthoredResetExpectation(RebirthPoiAuthoredResetKind.Sleeper,1,H('b'),null,true),new RebirthPoiAuthoredResetExpectation(RebirthPoiAuthoredResetKind.Trigger,0,H('c'),null,false)});
 static RebirthPoiAuthoredRuntimeBinding[] Runtime()=>new[]{new RebirthPoiAuthoredRuntimeBinding("1:0",H('a'),7,Guid.NewGuid()),new RebirthPoiAuthoredRuntimeBinding("1:1",H('b'),21,Guid.NewGuid()),new RebirthPoiAuthoredRuntimeBinding("2:0",H('c'),31,Guid.NewGuid())};
 static void Main(){
 var tx=Guid.NewGuid();var plan=Plan(tx);Check(plan.IsAuthored&&RebirthPoiResetPlan.Write(plan).Attribute("version").Value=="2","explicit authored plan schema");Check(plan.Volumes.Single()==7&&plan.Authored[1].OriginalNativeId==null,"native ID and unresolved authored index stay distinct");Check(RebirthPoiResetPlan.Read(RebirthPoiResetPlan.Write(plan)).Canonical==plan.Canonical,"authored roundtrip");
 var legacy=new RebirthPoiResetPlan(Guid.NewGuid(),RebirthPoiResetCaller.NaturalRespawn,H('d'),new long[0],new[]{7123},new int[0]);Check(!legacy.IsAuthored&&RebirthPoiResetPlan.Write(legacy).Attribute("version").Value=="1"&&RebirthPoiResetPlan.Read(RebirthPoiResetPlan.Write(legacy)).Volumes.Single()==7123,"legacy exact high native ID remains v1");
 var empty=new RebirthPoiResetPlan(Guid.NewGuid(),RebirthPoiResetCaller.Event,H('e'),new[]{12L},Array.Empty<int>(),Array.Empty<int>(),Array.Empty<RebirthPoiAuthoredResetExpectation>(),true);
 Check(empty.IsAuthored&&empty.Authored.Count==0&&RebirthPoiResetPlan.Write(empty).Attribute("version").Value=="3","empty authored target has explicit v3 custody");
 Check(RebirthPoiResetPlan.Read(RebirthPoiResetPlan.Write(empty)).Canonical==empty.Canonical,"empty authored plan roundtrip preserves explicit intent");
 Check(new RebirthPoiAuthoredResetBindings(empty,Array.Empty<RebirthPoiAuthoredRuntimeBinding>(),0).Bindings.Count==0,"empty authored completion uses empty exact binding set");
 Invalid(()=>new RebirthPoiResetPlan(Guid.NewGuid(),RebirthPoiResetCaller.Event,H('e'),Array.Empty<long>(),Array.Empty<int>(),Array.Empty<int>(),Array.Empty<RebirthPoiAuthoredResetExpectation>(),true),"empty target still requires actual chunk effects");
 Invalid(()=>new RebirthPoiResetPlan(Guid.NewGuid(),RebirthPoiResetCaller.Event,H('e'),new[]{12L},new[]{7},Array.Empty<int>(),Array.Empty<RebirthPoiAuthoredResetExpectation>(),true),"empty authored target cannot import unexplained runtime ID");
 var wrongEmpty=RebirthPoiResetPlan.Write(plan);wrongEmpty.SetAttributeValue("version",3);Invalid(()=>RebirthPoiResetPlan.Read(wrongEmpty),"v3 cannot erase nonempty authored expectations");
 var downgradedEmpty=RebirthPoiResetPlan.Write(empty);downgradedEmpty.SetAttributeValue("version",1);Invalid(()=>RebirthPoiResetPlan.Read(downgradedEmpty),"empty authored target cannot silently downgrade to legacy");
 var runtime=Runtime();var binding=new RebirthPoiAuthoredResetBindings(plan,runtime,0);Check(binding.Bindings.Count==3,"complete actual native binding token");Check(RebirthPoiAuthoredResetBindings.Read(binding.Write(),plan,0).Canonical==binding.Canonical,"runtime binding roundtrip exact original plan and epoch");
 Invalid(()=>new RebirthPoiAuthoredResetBindings(plan,runtime.Take(2),0),"missing authored room cannot complete");Invalid(()=>new RebirthPoiAuthoredResetBindings(plan,runtime.Concat(new[]{runtime[0]}),0),"duplicate runtime key refused");
 Invalid(()=>new RebirthPoiAuthoredResetBindings(plan,new[]{new RebirthPoiAuthoredRuntimeBinding("1:0",H('a'),8,Guid.NewGuid()),runtime[1],runtime[2]},0),"changed original exact native ID refused");
 Invalid(()=>new RebirthPoiAuthoredResetBindings(plan,new[]{runtime[0],new RebirthPoiAuthoredRuntimeBinding("1:1",H('b'),7,Guid.NewGuid()),runtime[2]},0),"runtime sleeper alias refused");
 Invalid(()=>new RebirthPoiAuthoredResetBindings(plan,new[]{runtime[0],new RebirthPoiAuthoredRuntimeBinding("1:1",H('b'),21,runtime[0].Receipt),runtime[2]},0),"receipt alias refused");
 Invalid(()=>new RebirthPoiAuthoredResetBindings(plan,new[]{runtime[0],new RebirthPoiAuthoredRuntimeBinding("1:1",H('c'),21,Guid.NewGuid()),runtime[2]},0),"foreign descriptor refused");
 Invalid(()=>new RebirthPoiResetPlan(tx,RebirthPoiResetCaller.Quest,H('f'),new[]{9L},new[]{7},new int[0],new[]{plan.Authored[0],plan.Authored[0]}),"duplicate authored expectation refused");
 var malformed=RebirthPoiResetPlan.Write(plan);malformed.SetAttributeValue("version",1);Invalid(()=>RebirthPoiResetPlan.Read(malformed),"v1 cannot silently reinterpret authored slots");
 Guid generation=Guid.NewGuid();var actor=new RebirthPoiActorObservation(Guid.NewGuid(),100,"zombieArlene",1);var room=new RebirthPoiVolumeObservation(7,H('a'),new[]{actor});var original=new RebirthPoiPartialObservation(generation,0,1,new[]{room});
 Check(original.RollOverVerifiedReset(plan)==null,"authored missing bindings withheld");Check(original.RollOverVerifiedReset(plan,binding)==null,"living old actor omitted outcome withheld");
 var survived=new RebirthPoiResetActorOutcome(actor.Token,actor.EntityId,0,generation,H('a'),actor.CausalDigest,RebirthPoiPriorActorDisposition.Survived,Guid.NewGuid());binding=new RebirthPoiAuthoredResetBindings(plan,runtime,0,new[]{survived});var rolled=original.RollOverVerifiedReset(plan,binding);Check(rolled!=null&&rolled.Volumes.Count==2&&rolled.Volumes[21].Actors.Count==0,"newly registered combat room included");var inherited=rolled.Volumes[7].Actors[actor.Token];Check(!inherited.Dead&&inherited.EntityId==100&&inherited.Inheritance.OriginEpoch==0&&inherited.Inheritance.OriginGeneration==generation&&inherited.Inheritance.ResetTransaction==tx,"survivor retained with exact saved origin");
 Check(rolled.Canonical==original.RollOverVerifiedReset(plan,binding).Canonical,"same original outcomes deterministic retry");Check(RebirthPoiPartialObservation.Read(RebirthPoiPartialObservation.Write(rolled)).Canonical==rolled.Canonical,"inheritance payload roundtrip");
 var badOutcome=new RebirthPoiResetActorOutcome(actor.Token,101,0,generation,H('a'),actor.CausalDigest,RebirthPoiPriorActorDisposition.Survived,Guid.NewGuid());Check(original.RollOverVerifiedReset(plan,new RebirthPoiAuthoredResetBindings(plan,runtime,0,new[]{badOutcome}))==null,"different original actor refused");
 var removed=new RebirthPoiResetActorOutcome(actor.Token,100,0,generation,H('a'),actor.CausalDigest,RebirthPoiPriorActorDisposition.NativeRemoved,Guid.NewGuid());Check(original.RollOverVerifiedReset(plan,new RebirthPoiAuthoredResetBindings(plan,runtime,0,new[]{removed})).Volumes[7].Actors.Count==0,"explicit native removal assertion resolves old participant");
 var unresolved=new RebirthPoiResetActorOutcome(actor.Token,100,0,generation,H('a'),actor.CausalDigest,RebirthPoiPriorActorDisposition.RetainedUnresolved,Guid.NewGuid());var unknownBinding=new RebirthPoiAuthoredResetBindings(plan,runtime,0,new[]{unresolved});var unknownRolled=original.RollOverVerifiedReset(plan,unknownBinding);var unknownActor=unknownRolled.Volumes[7].Actors[actor.Token];Check(!unknownActor.Dead&&unknownActor.Inheritance.Unresolved&&unknownActor.Inheritance.OriginGeneration==generation,"unresolved unloaded obligation inherited without asserting present native survival");Check(RebirthPoiPartialObservation.Read(RebirthPoiPartialObservation.Write(unknownRolled)).Canonical==unknownRolled.Canonical,"unresolved inheritance survives strict partial serialization");var legacyInheritance=new RebirthPoiActorInheritance(0,generation,tx,Guid.NewGuid());Check(!RebirthPoiActorInheritance.Read(legacyInheritance.Write()).Unresolved,"legacy v4 inheritance without unresolved attribute remains readable");var malformedInheritance=unknownActor.Inheritance.Write();malformedInheritance.SetAttributeValue("unresolved","maybe");Invalid(()=>RebirthPoiActorInheritance.Read(malformedInheritance),"malformed unresolved boolean refused");var forgotten=new RebirthPoiActorObservation(unknownActor.Token,unknownActor.EntityId,unknownActor.ClassName,unknownActor.SpawnPoint);Check(!forgotten.IsCausalSuccessorOf(unknownActor),"native lookup absence cannot drop inherited unresolved origin");
 var root=Path.Combine(Path.GetTempPath(),"purge-authored-"+Guid.NewGuid().ToString("N"));Directory.CreateDirectory(root);var scope=new object();bool current=true,armed=false;var world=Guid.NewGuid();var native=new RebirthPoiWorldBinding(scope,world.ToString("N").ToUpperInvariant(),root,()=>current);RebirthPoiWorldStore store;Check(RebirthPoiWorldStore.TryOpen(native,out store,stage=>{if(armed&&stage=="afterManifestCandidateWritten")throw new IOException("fixture");})==RebirthPoiStoreResult.Published,"durable original world open");var poi=new RebirthPoiIdentity("house",1,2,3,0,10,10,10,"forest");Check(store.TryDiscover(store.Published,poi)==RebirthPoiStoreResult.Published,"durable discover");Check(store.TryObservePartial(store.Published,poi,0,original)==RebirthPoiStoreResult.Published,"original actor enrolled");Check(store.TryBeginReset(store.Published,poi,0,tx,plan)==RebirthPoiStoreResult.Published,"original authored intent durable");
 Check(store.TryFinishReset(store.Published,poi,0,tx,RebirthPoiResetDisposition.Completed,rolled)==RebirthPoiStoreResult.Conflict,"terminal cannot omit original bindings");
 armed=true;var predecessor=store.Published;Check(store.TryFinishReset(predecessor,poi,0,tx,RebirthPoiResetDisposition.Completed,rolled,binding)==RebirthPoiStoreResult.Uncertain&&store.HasPending&&ReferenceEquals(store.Published,predecessor),"terminal uncertain preserves original pending epoch");string candidate=File.ReadAllText(Path.Combine(native.Directory,"world.xml.candidate"));armed=false;Check(store.TryRetryPending()==RebirthPoiStoreResult.Published,"same original candidate terminal retry");store.Published.TryGet(poi,out var saved);Check(saved.Epoch==1&&saved.LastAuthoredReset.Canonical==binding.Canonical&&saved.Observations.Canonical==rolled.Canonical,"final original file witness retains binding and survivor");Check(store.TryFinishReset(store.Published,poi,0,tx,RebirthPoiResetDisposition.Completed,rolled,binding)==RebirthPoiStoreResult.Duplicate,"exact terminal retry idempotent");
 var alteredPlan=new RebirthPoiResetPlan(tx,RebirthPoiResetCaller.Quest,H('e'),new[]{9L},new[]{7},new int[0],plan.Authored);var alteredBinding=new RebirthPoiAuthoredResetBindings(alteredPlan,runtime,0,new[]{survived});Check(store.TryFinishReset(store.Published,poi,0,tx,RebirthPoiResetDisposition.Completed,rolled,alteredBinding)==RebirthPoiStoreResult.Conflict,"terminal retry rejects altered original plan");
 Check(RebirthPoiWorldStore.TryOpen(native,out var cold)==RebirthPoiStoreResult.Published&&cold.Published.TryGet(poi,out saved)&&saved.LastAuthoredReset.Canonical==binding.Canonical&&saved.Observations.Volumes[7].Actors[actor.Token].Inheritance.OriginGeneration==generation,"cold exact files retain original inherited origin");
 var clear=new RebirthPoiClearEvidence(Guid.NewGuid(),2,2,2,0,0,false,50);Check(cold.TryClear(cold.Published,poi,1,clear)==RebirthPoiStoreResult.Conflict,"inherited live participant blocks arbitrary clear assertion");
 var unknownScope=new object();var unknownNative=new RebirthPoiWorldBinding(unknownScope,Guid.NewGuid().ToString("N").ToUpperInvariant(),Path.Combine(root,"unresolved"),()=>true);Check(RebirthPoiWorldStore.TryOpen(unknownNative,out var unknownStore)==RebirthPoiStoreResult.Published,"unresolved original durable world opens");Check(unknownStore.TryDiscover(unknownStore.Published,poi)==RebirthPoiStoreResult.Published&&unknownStore.TryObservePartial(unknownStore.Published,poi,0,original)==RebirthPoiStoreResult.Published,"unresolved source obligation published before reset");Check(unknownStore.TryBeginReset(unknownStore.Published,poi,0,tx,plan)==RebirthPoiStoreResult.Published,"unresolved actor does not require fictional present-life admission");Check(unknownStore.TryFinishReset(unknownStore.Published,poi,0,tx,RebirthPoiResetDisposition.Completed,unknownRolled,unknownBinding)==RebirthPoiStoreResult.Published,"completed reset durably retains unloaded unresolved blocker");Check(RebirthPoiWorldStore.TryOpen(unknownNative,out var unknownCold)==RebirthPoiStoreResult.Published&&unknownCold.Published.TryGet(poi,out var unknownSaved)&&unknownSaved.Observations.Volumes[7].Actors[actor.Token].Inheritance.Unresolved&&unknownSaved.LastAuthoredReset.PriorActors[actor.Token].Disposition==RebirthPoiPriorActorDisposition.RetainedUnresolved,"exact original files retain unresolved disposition across reload");Check(unknownCold.TryClear(unknownCold.Published,poi,1,clear)==RebirthPoiStoreResult.Conflict,"unresolved inherited obligation blocks arbitrary clear proof after reload");Check(unknownCold.TryFinishReset(unknownCold.Published,poi,0,tx,RebirthPoiResetDisposition.Completed,unknownRolled,unknownBinding)==RebirthPoiStoreResult.Duplicate,"unresolved terminal retains exact idempotent receipt");
 var restored=inherited.RestoreVerifiedNativeParticipant(120,Guid.NewGuid());Check(restored.Inheritance.Canonical==inherited.Inheritance.Canonical&&restored.IsCausalSuccessorOf(inherited),"native restoration retains inherited origin");
 var dead=new RebirthPoiActorObservation(inherited.Token,inherited.EntityId,inherited.ClassName,inherited.SpawnPoint,Guid.NewGuid(),60,inherited.Restorations,inherited.Checkpoint,inherited.Inheritance);var terminal=new RebirthPoiPartialObservation(rolled.Generation,1,rolled.Revision+1,new[]{new RebirthPoiVolumeObservation(7,H('a'),new[]{dead},tx),rolled.Volumes[21]});Check(cold.TryObservePartial(cold.Published,poi,1,terminal)==RebirthPoiStoreResult.Published,"positive inherited death successor");Check(cold.TryClear(cold.Published,poi,1,clear)==RebirthPoiStoreResult.Published,"clear permitted after inherited actor terminal proof");cold.Published.TryGet(poi,out saved);Check(saved.LastAuthoredReset.Canonical==binding.Canonical,"binding receipt survives reclear");
 var cancel=Guid.NewGuid();Check(cold.TryBeginReset(cold.Published,poi,1,cancel)==RebirthPoiStoreResult.Published&&cold.TryFinishReset(cold.Published,poi,1,cancel,RebirthPoiResetDisposition.NoMutation)==RebirthPoiStoreResult.Published,"later original no-mutation operation");cold.Published.TryGet(poi,out saved);Check(saved.LastAuthoredReset.Canonical==binding.Canonical,"no mutation retains prior actual generation receipt");
 var xml=RebirthPoiClearanceCodec.Write(cold.Published.Shards.Values.Single());var doc=XDocument.Parse(xml);doc.Root.Element("poi").Element("authoredReset").Element("bindings").Add(new XElement("unknown"));Check(!RebirthPoiClearanceCodec.TryRead(doc.ToString(),world,scope,out _),"strict unknown binding child refused"); var ownedPoi=new RebirthPoiIdentity("owned",5,2,3,0,10,10,10,"forest");Check(cold.TryDiscover(cold.Published,ownedPoi)==RebirthPoiStoreResult.Published&&cold.TryObservePartial(cold.Published,ownedPoi,0,original)==RebirthPoiStoreResult.Published,"original caller actor predecessor");double time=0;var iterator=new NativeIterator();var protocol=new RebirthPoiResetCallerProtocol(cold,cold.Published,ownedPoi,plan,iterator,()=>time);
 iterator.Effects=()=>{protocol.ChunkCopied(scope,tx,9,true);protocol.ChunkRegenerated(scope,tx,9,true);foreach(var item in runtime)protocol.AuthoredEffectReset(scope,tx,item);protocol.PriorActorOutcomeVerified(scope,tx,survived);protocol.TriggersRefreshed(scope,tx,plan.Manifest);};Check(protocol.MoveNext()&&iterator.Advances==1,"native iterator advanced once only after original v2 intent");Check(!protocol.MoveNext()&&protocol.State==RebirthPoiResetProtocolState.Completed,"complete owned authored effects and survivor terminalize");cold.Published.TryGet(ownedPoi,out var ownedRecord);Check(ownedRecord.LastAuthoredReset.Canonical==binding.Canonical&&ownedRecord.Observations.Volumes[7].Actors[actor.Token].Inheritance.OriginEpoch==0,"actual original caller persists identical bindings and survivor");
 var secondPlan=Plan(Guid.NewGuid());var oldInherited=ownedRecord.Observations.Volumes[7].Actors[actor.Token];var twiceSurvived=new RebirthPoiResetActorOutcome(actor.Token,100,1,tx,H('a'),oldInherited.CausalDigest,RebirthPoiPriorActorDisposition.Survived,Guid.NewGuid());var secondBindings=new RebirthPoiAuthoredResetBindings(secondPlan,Runtime(),1,new[]{twiceSurvived});var twice=ownedRecord.Observations.RollOverVerifiedReset(secondPlan,secondBindings);Check(twice!=null&&twice.Volumes[7].Actors[actor.Token].Inheritance.OriginEpoch==0&&twice.Volumes[7].Actors[actor.Token].Inheritance.OriginGeneration==generation&&twice.Volumes[7].Actors[actor.Token].Inheritance.ResetTransaction==secondPlan.Transaction,"repeated inherited resets preserve original saved stamp origin");
 var missingPoi=new RebirthPoiIdentity("missing",6,2,3,0,10,10,10,"forest");cold.TryDiscover(cold.Published,missingPoi);cold.TryObservePartial(cold.Published,missingPoi,0,original);var missingNative=new NativeIterator();var missing=new RebirthPoiResetCallerProtocol(cold,cold.Published,missingPoi,Plan(Guid.NewGuid()),missingNative,()=>time);missingNative.Effects=()=>{};missing.MoveNext();missing.MoveNext();Check(missing.State==RebirthPoiResetProtocolState.Unknown&&missingNative.Advances==2,"ended native iterator cannot substitute authored and survivor witnesses");
 current=false;Check(cold.TryClear(cold.Published,poi,1,clear)==RebirthPoiStoreResult.StaleScope,"late original scope refused");
 Console.WriteLine("PASS "+count+" actual production authored generation/store assertions; native scope/effect producer assertions are doubles; no native mutation hook/game claim");
 }
}