using System;using System.IO;
class Program{
 static int checks;static void Check(bool ok,string label){if(!ok)throw new Exception(label);checks++;}
 static void Main(){byte[] frame={116,116,99,0,38,0,0,0,1,2,3};
 Check(RebirthRecoveryChunkPayload.TryDecode(frame,s=>s,out var version,out var payload)&&version==38&&payload.Length==3&&payload[2]==3,"exact detached header/payload");
 Check(!RebirthRecoveryChunkPayload.TryDecode(new byte[8],s=>s,out _,out _),"truncated frame refuses");var bad=(byte[])frame.Clone();bad[0]=0;Check(!RebirthRecoveryChunkPayload.TryDecode(bad,s=>s,out _,out _),"wrong magic refuses");bad=(byte[])frame.Clone();bad[4]=0;Check(!RebirthRecoveryChunkPayload.TryDecode(bad,s=>s,out _,out _),"zero version refuses");
 Check(!RebirthRecoveryChunkPayload.TryDecode(frame,s=>throw new IOException(),out var failedVersion,out var failedPayload)&&failedVersion==0&&failedPayload==null,"inflate error leaves no evidence");
 Check(!RebirthRecoveryChunkPayload.TryDecode(frame,s=>new MemoryStream(),out _,out _),"empty expansion refuses");
 Check(!RebirthRecoveryChunkPayload.TryDecode(frame,s=>new Endless(),out _,out _),"expanded bound refuses");
 Check(frame[8]==1&&payload[0]==1,"input preserved"); using(var nativeFrame=new MemoryStream()){
 nativeFrame.Write(new byte[]{116,116,99,0,38,0,0,0});
 var original=new byte[20000];for(int i=0;i<original.Length;i++)original[i]=(byte)(i%251);
 using(var compressor=new Noemax.GZip.DeflateOutputStream(nativeFrame,3,leaveOpen:true)){compressor.Write(original,0,original.Length);compressor.Restart();}
 var encoded=nativeFrame.ToArray();Check(RebirthRecoveryChunkPayload.TryDecodeNative(encoded,out var nativeVersion,out var nativePayload)&&nativeVersion==38&&System.Linq.Enumerable.SequenceEqual(original,nativePayload),"actual installed compression roundtrip");
 Check(!RebirthRecoveryChunkPayload.TryDecodeNative(new byte[]{116,116,99,0,38,0,0,0,255,255,255},out _,out _),"native malformed inflate refuses");
 }
 foreach(int regionVersion in new[]{0,1}){var data=new byte[16384];data[0]=55;data[1]=114;data[2]=103;data[3]=(byte)regionVersion;int entry=regionVersion==0?4:4096;data[entry]=3;data[entry+3]=1;int start=12288+(regionVersion==0?4:0);data[start]=(byte)frame.Length;Array.Copy(frame,0,data,start+(regionVersion==0?5:16),frame.Length);using(var region=new MemoryStream(data,false)){Check(RebirthRecoverySectorFrame.TryRead(region,0,0,out var captured)&&System.Linq.Enumerable.SequenceEqual(captured,frame),"native sector framing version "+regionVersion);Check(!RebirthRecoverySectorFrame.TryRead(region,1,0,out _),"absent sector refuses");}}
 var legacy=new byte[12301];legacy[0]=55;legacy[1]=114;legacy[2]=103;legacy[4]=2;legacy[7]=1;legacy[8196]=(byte)frame.Length;Array.Copy(frame,0,legacy,8201,frame.Length);
 using(var region=new MemoryStream(legacy,false)){Check(RebirthRecoverySectorFrame.TryRead(region,0,0,out var captured)&&System.Linq.Enumerable.SequenceEqual(captured,frame),"legacy sector two remains readable");}
 legacy[4]=1;using(var region=new MemoryStream(legacy,false)){Check(!RebirthRecoverySectorFrame.TryRead(region,0,0,out _),"legacy header overlap refuses");}
 legacy[4]=2;legacy[8196]=255;legacy[8197]=255;legacy[8198]=255;legacy[8199]=127;using(var region=new MemoryStream(legacy,false)){Check(!RebirthRecoverySectorFrame.TryRead(region,0,0,out _),"oversized sector payload refuses");}
 legacy[8196]=(byte)frame.Length;legacy[8197]=legacy[8198]=legacy[8199]=0;
 string temporary=Path.Combine(Path.GetTempPath(),"RebirthRegionCapture_"+Guid.NewGuid().ToString("N"));Directory.CreateDirectory(temporary);string file=Path.Combine(temporary,"r.0.0.7rg");try{
 Check(!RebirthRecoveryRegionCapture.TryCapture(temporary,0,0,0,0,()=>true,out _)&&!File.Exists(file),"missing region never created");File.WriteAllBytes(file,legacy);
 Check(RebirthRecoveryRegionCapture.TryCapture(temporary,0,0,0,0,()=>true,out var disk)&&System.Linq.Enumerable.SequenceEqual(disk,frame),"actual read-only file capture");
 Check(!RebirthRecoveryRegionCapture.TryCapture(temporary,0,0,0,0,()=>false,out _),"foreign context refuses capture");int calls=0;Check(!RebirthRecoveryRegionCapture.TryCapture(temporary,0,0,0,0,()=>++calls<3,out _),"context changed during capture refuses");
 using(var writer=new FileStream(file,FileMode.Open,FileAccess.ReadWrite,FileShare.ReadWrite)){Check(!RebirthRecoveryRegionCapture.TryCapture(temporary,0,0,0,0,()=>true,out _),"active write handle refuses capture");}
 Check(System.Linq.Enumerable.SequenceEqual(File.ReadAllBytes(file),legacy),"capture preserves file bytes");
 }finally{File.Delete(file);Directory.Delete(temporary);}
 using(var prefix=new MemoryStream())using(var writer=new BinaryWriter(prefix)){writer.Write(4);writer.Write(0);writer.Write(-7);writer.Write(0L);writer.Write(new byte[64]);Action<int> channel=bytes=>{for(int i=0;i<64;i++){writer.Write((byte)1);writer.Write(new byte[bytes]);}};channel(1);writer.Write(new byte[512+32+1794]);writer.Write((ushort)0);writer.Write(new byte[768]);channel(1);channel(1);channel(2);channel(6);channel(2);writer.Write(false);writer.Write(0);var bytes=prefix.ToArray();Check(RebirthRecoveryEntitySection.TryLocate(bytes,46,out int sx,out _,out int sz,out int count,out int offset)&&sx==4&&sz==-7&&count==0&&offset==bytes.Length,"actual native prefix structure reaches entity section");Check(!RebirthRecoveryEntitySection.TryLocate(bytes,47,out _,out _,out _,out _,out _),"unknown chunk version refuses");Array.Resize(ref bytes,bytes.Length-1);Check(!RebirthRecoveryEntitySection.TryLocate(bytes,46,out _,out _,out _,out _,out _),"truncated prefix refuses");}
 using(var entityBytes=new MemoryStream())using(var writer=new BinaryWriter(entityBytes)){writer.Write((byte)38);writer.Write(123456789);writer.Write(501);writer.Write(1800f);for(int i=0;i<6;i++)writer.Write((float)i);writer.Write(false);writer.Write(4);writer.Write(0L);writer.Write(false);writer.Write((short)0);writer.Write(true);writer.Write(70000);writer.Write(new byte[70000]);writer.Write(new byte[15]);writer.Write((ushort)5);writer.Write(new byte[]{1,3,5,7,9});writer.Write(false);writer.Write(0f);writer.Write(new byte[24]);var bytes=entityBytes.ToArray();Check(RebirthRecoveryEntityRecord.TryRead(bytes,0,123456789,out var entityRecord)&&entityRecord.EntityId==501&&entityRecord.BagLength==70000&&entityRecord.MetadataLength==5&&entityRecord.EndOffset==bytes.Length,"bounded complete custom v38 record framing");Check(!RebirthRecoveryEntityRecord.TryRead(bytes,0,42,out _),"foreign entity class refuses");var truncated=System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Take(bytes,bytes.Length-1));Check(!RebirthRecoveryEntityRecord.TryRead(truncated,0,123456789,out _),"truncated custom entity record refuses");bytes[0]=39;Check(!RebirthRecoveryEntityRecord.TryRead(bytes,0,123456789,out _),"unknown entity record version refuses");}
 Console.WriteLine("PASS "+checks+" actual bounded frame decoder checks; includes installed Noemax compression, synthetic temp-region file I/O, no game save I/O");}
 class Endless:Stream{public override bool CanRead=>true;public override bool CanSeek=>false;public override bool CanWrite=>false;public override long Length=>throw new NotSupportedException();public override long Position{get=>0;set=>throw new NotSupportedException();}public override int Read(byte[] b,int o,int c){Array.Clear(b,o,c);return c;}public override void Flush(){}public override long Seek(long o,SeekOrigin s)=>throw new NotSupportedException();public override void SetLength(long l)=>throw new NotSupportedException();public override void Write(byte[] b,int o,int c)=>throw new NotSupportedException();}
}