using System;
using System.Collections.Generic;
using System.Text;
using System.Threading;

#nullable disable

public enum RebirthNpcRequirementStatus : byte { IMPLEMENTED=0, PARTIAL=1, NOT_IMPLEMENTED=2 }

public sealed class RebirthNpcRequirementDefinition
{
    public readonly string Id, Domain, Name, PackageId, Documentation, Evidence, PersistenceObligation, NetworkingObligation, UiAdminObligation, CompletionPredicate, Assessment;
    public readonly RebirthNpcRequirementStatus Status;
    public RebirthNpcRequirementDefinition(string id,string domain,string name,string packageId,RebirthNpcRequirementStatus status,string documentation,string evidence,string persistence,string networking,string uiAdmin,string predicate,string assessment)
    { Id=id; Domain=domain; Name=name; PackageId=packageId; Status=status; Documentation=documentation; Evidence=evidence; PersistenceObligation=persistence; NetworkingObligation=networking; UiAdminObligation=uiAdmin; CompletionPredicate=predicate; Assessment=assessment; }
}

public sealed class RebirthNpcConformanceGateResult
{
    public string Gate; public bool Passed; public string Detail;
}

public sealed class RebirthNpcConformanceReport
{
    public string PackageId; public bool Passed; public int RequirementCount; public RebirthNpcConformanceGateResult[] Gates;
    public string ToReport() { StringBuilder b=new StringBuilder("[REBIRTH NPC Conformance] package=").Append(PackageId).Append(" result=").Append(Passed?"PASS":"FAIL").Append(" requirements=").Append(RequirementCount); for(int i=0;i<Gates.Length;i++) b.Append('\n').Append(Gates[i].Gate).Append('=').Append(Gates[i].Passed?"PASS":"FAIL").Append(" (").Append(Gates[i].Detail).Append(')'); return b.ToString(); }
}

public static class RebirthNpcRequirementCatalogue
{
    private static readonly RebirthNpcRequirementDefinition[] Definitions = new RebirthNpcRequirementDefinition[]
    {
            new RebirthNpcRequirementDefinition("NPC-REQ-001", "Foundation", "Minimal NPC inheritance hierarchy", "BASELINE-VERIFIED", RebirthNpcRequirementStatus.IMPLEMENTED, "Architecture §§6.1–6.7", "RebirthNpcFoundation.cs: EntityRebirthNPC, EntityRebirthHumanoidNPC, survivor, bandit, special humanoid, dog and panther classes", "NOT_REQUIRED", "NOT_REQUIRED", "NOT_REQUIRED", "Concrete behavior + registration + caller + all applicable persistence/network/UI obligations + failure/replay handling + traceability must pass", "All architecture-defined entity categories have concrete classes."),
            new RebirthNpcRequirementDefinition("NPC-REQ-002", "Foundation", "Composition and capability model", "BASELINE-VERIFIED", RebirthNpcRequirementStatus.IMPLEMENTED, "Architecture §§7–8", "RebirthNpcFoundation.cs; RebirthNpcAuthoringValidation.cs", "NOT_REQUIRED", "NOT_REQUIRED", "NOT_REQUIRED", "Concrete behavior + registration + caller + all applicable persistence/network/UI obligations + failure/replay handling + traceability must pass", "Typed capabilities and profile validation exist and are consumed by higher-level services."),
            new RebirthNpcRequirementDefinition("NPC-REQ-003", "Foundation", "Typed profile loading and production profile catalogue", "ACIP-08", RebirthNpcRequirementStatus.IMPLEMENTED, "Architecture §8; Roadmap §4.1", "Scripts/Rebirth/NPC/WorldIntegration/RebirthNpcWorldIntegration.cs: RebirthNpcProductionProfileCatalogue, Validate, six production profiles; Scripts/Rebirth/NPC/Foundation/RebirthNpcLifecycle.cs: registration", "NOT_REQUIRED", "NOT_REQUIRED", "NOT_REQUIRED", "Concrete behavior + registration + caller + all applicable persistence/network/UI obligations + failure/replay handling + traceability must pass", "Production catalogue covers survivor, bandit, special humanoid, dog and panther with spawn groups, capabilities, models and validation."),
            new RebirthNpcRequirementDefinition("NPC-REQ-004", "Foundation", "Selectable humanoid model pipelines", "BASELINE-VERIFIED", RebirthNpcRequirementStatus.IMPLEMENTED, "Model Pipeline Engineering Design", "RebirthHumanNpcModelPipeline.cs; EModelRebirthSdcsNpc.cs; AvatarSdcsNpcController.cs", "NOT_REQUIRED", "NOT_REQUIRED", "NOT_REQUIRED", "Concrete behavior + registration + caller + all applicable persistence/network/UI obligations + failure/replay handling + traceability must pass", "Pipeline selection, model integration, semantic appearance and controller support exist."),
            new RebirthNpcRequirementDefinition("NPC-REQ-005", "Foundation", "Bootstrap and service registration", "BASELINE-VERIFIED", RebirthNpcRequirementStatus.IMPLEMENTED, "Roadmap R2-B; WP22", "RebirthNpcLifecycle.cs; RebirthNpcLifecycleQualification.cs", "NOT_REQUIRED", "NOT_REQUIRED", "NOT_REQUIRED", "Concrete behavior + registration + caller + all applicable persistence/network/UI obligations + failure/replay handling + traceability must pass", "Idempotent bootstrap, package/service registration and lifecycle observations exist."),
            new RebirthNpcRequirementDefinition("NPC-REQ-006", "Foundation", "World lifecycle reset and repeated-world isolation", "BASELINE-VERIFIED", RebirthNpcRequirementStatus.IMPLEMENTED, "Roadmap R2-B; WP22", "RebirthNpcLifecycle.cs; RebirthNpcLifecycleQualification.cs", "NOT_REQUIRED", "NOT_REQUIRED", "NOT_REQUIRED", "Concrete behavior + registration + caller + all applicable persistence/network/UI obligations + failure/replay handling + traceability must pass", "World-scoped services are reset and lifecycle counters are separated appropriately."),
            new RebirthNpcRequirementDefinition("NPC-REQ-007", "Foundation", "Runtime registry and stable-id/entity-id mapping", "BASELINE-VERIFIED", RebirthNpcRequirementStatus.IMPLEMENTED, "Architecture §§9–10", "RebirthNpcFoundation.cs: RebirthNpcRuntimeRegistry", "NOT_REQUIRED", "NOT_REQUIRED", "NOT_REQUIRED", "Concrete behavior + registration + caller + all applicable persistence/network/UI obligations + failure/replay handling + traceability must pass", "Bidirectional runtime mapping, activation/deactivation and duplicate detection exist."),
            new RebirthNpcRequirementDefinition("NPC-REQ-008", "Foundation", "Consolidated runtime state", "BASELINE-VERIFIED", RebirthNpcRequirementStatus.IMPLEMENTED, "Architecture §10", "RebirthNpcFoundation.cs: RebirthNpcRuntimeState", "NOT_REQUIRED", "NOT_REQUIRED", "NOT_REQUIRED", "Concrete behavior + registration + caller + all applicable persistence/network/UI obligations + failure/replay handling + traceability must pass", "Presence, ownership, order, travel, profile and revision state are consolidated."),
            new RebirthNpcRequirementDefinition("NPC-REQ-009", "Identity & Persistence", "128-bit stable NPC identity", "BASELINE-VERIFIED", RebirthNpcRequirementStatus.IMPLEMENTED, "Architecture §9.1; Phase 22", "RebirthNpcStableId; RebirthNpcStableIdentityStore.cs", "REQUIRED", "NOT_REQUIRED", "NOT_REQUIRED", "Concrete behavior + registration + caller + all applicable persistence/network/UI obligations + failure/replay handling + traceability must pass", "Durable identity is independent of transient entity IDs."),
            new RebirthNpcRequirementDefinition("NPC-REQ-010", "Identity & Persistence", "Stable identity conflict resolution and administration", "BASELINE-VERIFIED", RebirthNpcRequirementStatus.IMPLEMENTED, "Phases 22–25", "RebirthNpcStableIdentityStore.cs; RebirthNpcIdentityAuditLedger.cs; ConsoleCmdRebirthNpcIdentityAdmin.cs", "REQUIRED", "NOT_REQUIRED", "REQUIRED", "Concrete behavior + registration + caller + all applicable persistence/network/UI obligations + failure/replay handling + traceability must pass", "Persistent mapping, fail-closed conflicts, resolve/forget commands and audit records exist."),
            new RebirthNpcRequirementDefinition("NPC-REQ-011", "Identity & Persistence", "Atomic persistence, checksum, backup and recovery", "BASELINE-VERIFIED", RebirthNpcRequirementStatus.IMPLEMENTED, "Architecture §§18,40; Phases 26–28; WP19", "RebirthNpcPersistenceFile.cs; RebirthNpcPersistenceCoordinator.cs; RebirthNpcAdministrationSupport.cs", "REQUIRED", "NOT_REQUIRED", "NOT_REQUIRED", "Concrete behavior + registration + caller + all applicable persistence/network/UI obligations + failure/replay handling + traceability must pass", "Atomic primary/backup handling, validation, quarantine and recovery exist."),
            new RebirthNpcRequirementDefinition("NPC-REQ-012", "Identity & Persistence", "Schema versioning and fail-closed migration", "BASELINE-VERIFIED", RebirthNpcRequirementStatus.IMPLEMENTED, "Architecture §§40.12–40.13", "RebirthNpcPersistenceSchema.cs; domain persistence readers", "REQUIRED", "NOT_REQUIRED", "NOT_REQUIRED", "Concrete behavior + registration + caller + all applicable persistence/network/UI obligations + failure/replay handling + traceability must pass", "Version checks, telemetry and invalid-data rejection exist."),
            new RebirthNpcRequirementDefinition("NPC-REQ-013", "Identity & Persistence", "Execution/activity persistence", "BASELINE-VERIFIED", RebirthNpcRequirementStatus.IMPLEMENTED, "Phase 21", "RebirthNpcExecutionPersistence.cs; RebirthNpcWorkCheckpointPersistence.cs; RebirthNpcWorkOutcomePersistence.cs", "REQUIRED", "NOT_REQUIRED", "NOT_REQUIRED", "Concrete behavior + registration + caller + all applicable persistence/network/UI obligations + failure/replay handling + traceability must pass", "Leases, checkpoints and outcomes are durable."),
            new RebirthNpcRequirementDefinition("NPC-REQ-014", "Identity & Persistence", "Inventory and equipment persistence", "BASELINE-VERIFIED", RebirthNpcRequirementStatus.IMPLEMENTED, "Phases 29–31; Milestones 1–2", "RebirthNpcInventoryPersistence.cs; RebirthNpcEquipmentPersistence.cs", "REQUIRED", "NOT_REQUIRED", "REQUIRED", "Concrete behavior + registration + caller + all applicable persistence/network/UI obligations + failure/replay handling + traceability must pass", "Inventory and semantic equipment have dedicated stores."),
            new RebirthNpcRequirementDefinition("NPC-REQ-015", "Identity & Persistence", "Social and faction persistence", "BASELINE-VERIFIED", RebirthNpcRequirementStatus.IMPLEMENTED, "Social Closure", "RebirthNpcSocialPersistence.cs; RebirthNpcPersistenceCoordinator.cs", "REQUIRED", "NOT_REQUIRED", "NOT_REQUIRED", "Concrete behavior + registration + caller + all applicable persistence/network/UI obligations + failure/replay handling + traceability must pass", "Relationships, memories, replay IDs and faction standings are saved/restored."),
            new RebirthNpcRequirementDefinition("NPC-REQ-016", "Identity & Persistence", "Combat/injury persistence", "BASELINE-VERIFIED", RebirthNpcRequirementStatus.IMPLEMENTED, "WP16", "RebirthNpcCombatPersistence.cs", "REQUIRED", "NOT_REQUIRED", "NOT_REQUIRED", "Concrete behavior + registration + caller + all applicable persistence/network/UI obligations + failure/replay handling + traceability must pass", "Combat life state, injuries and tactical orders are persisted."),
            new RebirthNpcRequirementDefinition("NPC-REQ-017", "Identity & Persistence", "Settlement simulation persistence", "BASELINE-VERIFIED", RebirthNpcRequirementStatus.IMPLEMENTED, "Settlement simulation", "RebirthNpcSettlementPersistence.cs", "REQUIRED", "NOT_REQUIRED", "NOT_REQUIRED", "Concrete behavior + registration + caller + all applicable persistence/network/UI obligations + failure/replay handling + traceability must pass", "Needs, profession labels, work orders, resources and reservations are durable."),
            new RebirthNpcRequirementDefinition("NPC-REQ-018", "Identity & Persistence", "Exact monolithic RebirthNpcPersistentRecord schema", "ACIP-11", RebirthNpcRequirementStatus.IMPLEMENTED, "Architecture §40.5", "Scripts/Rebirth/NPC/Persistence/RebirthNpcAggregatePersistence.cs; Scripts/Rebirth/NPC/Persistence/RebirthNpcPersistenceCoordinator.cs; Scripts/Rebirth/NPC/Foundation/RebirthNpcLifecycle.cs", "REQUIRED", "NOT_REQUIRED", "NOT_REQUIRED", "Concrete behavior + registration + caller + all applicable persistence/network/UI obligations + failure/replay handling + traceability must pass", "Architecture §40.5 is implemented as the canonical NPC-level aggregate envelope over versioned domain stores with revision/checksum consistency validation."),
            new RebirthNpcRequirementDefinition("NPC-REQ-019", "Ownership & Commands", "Ownership states and party/shared access", "BASELINE-VERIFIED", RebirthNpcRequirementStatus.IMPLEMENTED, "Architecture §11", "RebirthNpcFoundation.cs; RebirthNpcInteractionPresentationService.cs; RebirthNpcCommandSystem.cs", "NOT_REQUIRED", "NOT_REQUIRED", "NOT_REQUIRED", "Concrete behavior + registration + caller + all applicable persistence/network/UI obligations + failure/replay handling + traceability must pass", "Ownership and party-aware permission projection exist."),
            new RebirthNpcRequirementDefinition("NPC-REQ-020", "Ownership & Commands", "Hire and dismiss", "BASELINE-VERIFIED", RebirthNpcRequirementStatus.IMPLEMENTED, "Architecture §12; Major Update 18", "RebirthNpcHireService; RebirthNpcInteractionMutationHandlers.cs", "NOT_REQUIRED", "NOT_REQUIRED", "NOT_REQUIRED", "Concrete behavior + registration + caller + all applicable persistence/network/UI obligations + failure/replay handling + traceability must pass", "Authoritative hire/dismiss mutations with session and revision checks exist."),
            new RebirthNpcRequirementDefinition("NPC-REQ-021", "Ownership & Commands", "Mercenary contracts, wages and expiry", "ACIP-07", RebirthNpcRequirementStatus.IMPLEMENTED, "Architecture §12.3", "RebirthNpcLifecycleGameplayService.StartContract/Tick/ExpireContract; economy and ownership adapters", "NOT_REQUIRED", "NOT_REQUIRED", "NOT_REQUIRED", "Concrete behavior + registration + caller + all applicable persistence/network/UI obligations + failure/replay handling + traceability must pass", "Generic hiring exists, but the documented mercenary contract economy is absent."),
            new RebirthNpcRequirementDefinition("NPC-REQ-022", "Ownership & Commands", "Order state model", "BASELINE-VERIFIED", RebirthNpcRequirementStatus.IMPLEMENTED, "Architecture §13", "RebirthNpcFoundation.cs; RebirthNpcCommandSystem.cs", "NOT_REQUIRED", "NOT_REQUIRED", "NOT_REQUIRED", "Concrete behavior + registration + caller + all applicable persistence/network/UI obligations + failure/replay handling + traceability must pass", "Follow, stay, guard, patrol, work, mission and travel orders are represented."),
            new RebirthNpcRequirementDefinition("NPC-REQ-023", "Ownership & Commands", "Replay-safe command gateway, arbitration and retry", "BASELINE-VERIFIED", RebirthNpcRequirementStatus.IMPLEMENTED, "Phases 6–9", "RebirthNpcCommandSystem.cs", "NOT_REQUIRED", "NOT_REQUIRED", "REQUIRED", "Concrete behavior + registration + caller + all applicable persistence/network/UI obligations + failure/replay handling + traceability must pass", "Command IDs, revisions, priorities, replay journals, arbitration and retry exist."),
            new RebirthNpcRequirementDefinition("NPC-REQ-024", "Ownership & Commands", "Command networking request/ack", "BASELINE-VERIFIED", RebirthNpcRequirementStatus.IMPLEMENTED, "Phase 7", "NetPackageRebirthNpcCommand.cs", "NOT_REQUIRED", "REQUIRED", "REQUIRED", "Concrete behavior + registration + caller + all applicable persistence/network/UI obligations + failure/replay handling + traceability must pass", "Server-routed request/ack and response correlation exist."),
            new RebirthNpcRequirementDefinition("NPC-REQ-025", "Ownership & Commands", "Execution leases and heartbeat recovery", "BASELINE-VERIFIED", RebirthNpcRequirementStatus.IMPLEMENTED, "Phases 10–12", "RebirthNpcExecutionLease.cs; RebirthNpcActivityRuntime.cs", "NOT_REQUIRED", "NOT_REQUIRED", "NOT_REQUIRED", "Concrete behavior + registration + caller + all applicable persistence/network/UI obligations + failure/replay handling + traceability must pass", "Lease ownership, heartbeat, timeout and recovery exist."),
            new RebirthNpcRequirementDefinition("NPC-REQ-026", "Ownership & Commands", "Owner recall/teleport/distance recovery", "ACIP-07", RebirthNpcRequirementStatus.IMPLEMENTED, "Architecture §14", "RebirthNpcLifecycleGameplayService.RequestRecall; safe placement and world adapters", "NOT_REQUIRED", "NOT_REQUIRED", "NOT_REQUIRED", "Concrete behavior + registration + caller + all applicable persistence/network/UI obligations + failure/replay handling + traceability must pass", "Follow and stuck recovery exist, but no complete shared recall/teleport controller with all placement policies was found."),
            new RebirthNpcRequirementDefinition("NPC-REQ-027", "Ownership & Commands", "Vehicle attachment and travel restoration", "ACIP-07", RebirthNpcRequirementStatus.IMPLEMENTED, "Architecture §15", "RebirthNpcLifecycleGameplayService.BeginVehicleTravel/EndVehicleTravel; persisted seat and prior order", "REQUIRED", "NOT_REQUIRED", "NOT_REQUIRED", "Concrete behavior + registration + caller + all applicable persistence/network/UI obligations + failure/replay handling + traceability must pass", "Travel activity exists, but seat attachment, seat selection, dismount restoration and vehicle-specific policy are absent."),
            new RebirthNpcRequirementDefinition("NPC-REQ-028", "Ownership & Commands", "Mission temporary absence", "ACIP-07", RebirthNpcRequirementStatus.IMPLEMENTED, "Architecture §16", "RebirthNpcLifecycleGameplayService.StartMission/ResolveMission; deterministic elapsed-time executor", "NOT_REQUIRED", "NOT_REQUIRED", "NOT_REQUIRED", "Concrete behavior + registration + caller + all applicable persistence/network/UI obligations + failure/replay handling + traceability must pass", "Mission lifecycle exists through an executor interface, but no full mission catalogue, off-world simulation or reward execution set was found."),
            new RebirthNpcRequirementDefinition("NPC-REQ-029", "AI & Navigation", "Decision engine and interrupts", "BASELINE-VERIFIED", RebirthNpcRequirementStatus.IMPLEMENTED, "Architecture §21", "RebirthNpcDecisionEngine.cs", "NOT_REQUIRED", "NOT_REQUIRED", "NOT_REQUIRED", "Concrete behavior + registration + caller + all applicable persistence/network/UI obligations + failure/replay handling + traceability must pass", "Goal-provider arbitration, task lifecycle and interrupt severity exist."),
            new RebirthNpcRequirementDefinition("NPC-REQ-030", "AI & Navigation", "Controller dispatch", "BASELINE-VERIFIED", RebirthNpcRequirementStatus.IMPLEMENTED, "Phase 13", "RebirthNpcControllerDispatch.cs", "NOT_REQUIRED", "NOT_REQUIRED", "NOT_REQUIRED", "Concrete behavior + registration + caller + all applicable persistence/network/UI obligations + failure/replay handling + traceability must pass", "Controller registration and activity dispatch are integrated."),
            new RebirthNpcRequirementDefinition("NPC-REQ-031", "AI & Navigation", "Follow controller", "BASELINE-VERIFIED", RebirthNpcRequirementStatus.IMPLEMENTED, "Phase 15", "RebirthNpcFollowController.cs", "NOT_REQUIRED", "NOT_REQUIRED", "NOT_REQUIRED", "Concrete behavior + registration + caller + all applicable persistence/network/UI obligations + failure/replay handling + traceability must pass", "Follow target resolution and movement dispatch exist."),
            new RebirthNpcRequirementDefinition("NPC-REQ-032", "AI & Navigation", "Stay and guard stationary controllers", "BASELINE-VERIFIED", RebirthNpcRequirementStatus.IMPLEMENTED, "Phase 14", "RebirthNpcStationaryControllers.cs", "NOT_REQUIRED", "NOT_REQUIRED", "NOT_REQUIRED", "Concrete behavior + registration + caller + all applicable persistence/network/UI obligations + failure/replay handling + traceability must pass", "Stay/guard sessions and outcomes exist."),
            new RebirthNpcRequirementDefinition("NPC-REQ-033", "AI & Navigation", "Patrol controller", "BASELINE-VERIFIED", RebirthNpcRequirementStatus.IMPLEMENTED, "Phase 17", "RebirthNpcPatrolController.cs", "NOT_REQUIRED", "NOT_REQUIRED", "NOT_REQUIRED", "Concrete behavior + registration + caller + all applicable persistence/network/UI obligations + failure/replay handling + traceability must pass", "Waypoint progression and looping exist."),
            new RebirthNpcRequirementDefinition("NPC-REQ-034", "AI & Navigation", "Travel controller", "BASELINE-VERIFIED", RebirthNpcRequirementStatus.IMPLEMENTED, "Phase 19", "RebirthNpcTravelController.cs", "NOT_REQUIRED", "NOT_REQUIRED", "NOT_REQUIRED", "Concrete behavior + registration + caller + all applicable persistence/network/UI obligations + failure/replay handling + traceability must pass", "Travel activity dispatches through the movement adapter."),
            new RebirthNpcRequirementDefinition("NPC-REQ-035", "AI & Navigation", "Native navigation and stuck recovery", "BASELINE-VERIFIED", RebirthNpcRequirementStatus.IMPLEMENTED, "Architecture §22; Major Update 26", "RebirthNpcNavigationRuntime.cs; RebirthNpcFollowController.cs", "NOT_REQUIRED", "NOT_REQUIRED", "NOT_REQUIRED", "Concrete behavior + registration + caller + all applicable persistence/network/UI obligations + failure/replay handling + traceability must pass", "Native navigator integration, path budgets and recovery stages exist."),
            new RebirthNpcRequirementDefinition("NPC-REQ-036", "AI & Navigation", "Targeting service and owner-protection priority", "ACIP-06", RebirthNpcRequirementStatus.IMPLEMENTED, "Architecture §20", "No concrete RebirthNpcTargetingService or equivalent target scoring pipeline found", "NOT_REQUIRED", "NOT_REQUIRED", "REQUIRED", "Concrete behavior + registration + caller + all applicable persistence/network/UI obligations + failure/replay handling + traceability must pass", "Damage observation is not target acquisition. Candidate scoring and owner-threat priority are absent."),
            new RebirthNpcRequirementDefinition("NPC-REQ-037", "AI & Navigation", "Category-specific survivor/bandit/dog/panther combat AI", "ACIP-06", RebirthNpcRequirementStatus.IMPLEMENTED, "Architecture §§21.4–21.7", "Entity subclasses exist; no dedicated category-specific combat goal/task implementations found", "NOT_REQUIRED", "NOT_REQUIRED", "NOT_REQUIRED", "Concrete behavior + registration + caller + all applicable persistence/network/UI obligations + failure/replay handling + traceability must pass", "The documented combat behaviour differences are absent."),
            new RebirthNpcRequirementDefinition("NPC-REQ-038", "AI & Navigation", "Friendly-fire and projectile passthrough policy", "ACIP-06", RebirthNpcRequirementStatus.IMPLEMENTED, "Architecture §20.5", "No NPC-framework policy service/patches found", "NOT_REQUIRED", "NOT_REQUIRED", "NOT_REQUIRED", "Concrete behavior + registration + caller + all applicable persistence/network/UI obligations + failure/replay handling + traceability must pass", "The documented policy has no concrete implementation."),
            new RebirthNpcRequirementDefinition("NPC-REQ-039", "AI & Navigation", "Combat injury, incapacitation, rescue and death finalization", "BASELINE-VERIFIED", RebirthNpcRequirementStatus.IMPLEMENTED, "WP16", "RebirthNpcCombatEmergencySystem.cs; RebirthNpcCombatPersistence.cs", "NOT_REQUIRED", "NOT_REQUIRED", "NOT_REQUIRED", "Concrete behavior + registration + caller + all applicable persistence/network/UI obligations + failure/replay handling + traceability must pass", "Injury, life-state transitions, rescue and tactical orders exist."),
            new RebirthNpcRequirementDefinition("NPC-REQ-040", "AI & Navigation", "Respawn controller and category-specific respawn policy", "ACIP-07", RebirthNpcRequirementStatus.IMPLEMENTED, "Architecture §17", "RebirthNpcLifecycleGameplayService.ScheduleRespawn/TryRespawn; category placement and duplicate guard", "NOT_REQUIRED", "NOT_REQUIRED", "NOT_REQUIRED", "Concrete behavior + registration + caller + all applicable persistence/network/UI obligations + failure/replay handling + traceability must pass", "Bed/owner/settlement placement and reconstruction workflow are absent."),
            new RebirthNpcRequirementDefinition("NPC-REQ-041", "Networking", "Package registration and protocol versioning", "BASELINE-VERIFIED", RebirthNpcRequirementStatus.IMPLEMENTED, "Architecture §§19,41", "RebirthNpcNetworkProtocol.cs; RebirthNpcLifecycle.cs", "NOT_REQUIRED", "NOT_REQUIRED", "REQUIRED", "Concrete behavior + registration + caller + all applicable persistence/network/UI obligations + failure/replay handling + traceability must pass", "Command, runtime, appearance, semantic equipment, interaction and baseline packages are registered."),
            new RebirthNpcRequirementDefinition("NPC-REQ-042", "Networking", "Runtime-state replication", "BASELINE-VERIFIED", RebirthNpcRequirementStatus.IMPLEMENTED, "Architecture §41.4.4", "NetPackageRebirthNpcRuntimeState.cs", "NOT_REQUIRED", "REQUIRED", "NOT_REQUIRED", "Concrete behavior + registration + caller + all applicable persistence/network/UI obligations + failure/replay handling + traceability must pass", "Authoritative runtime snapshots and client application exist."),
            new RebirthNpcRequirementDefinition("NPC-REQ-043", "Networking", "Appearance and semantic equipment replication", "BASELINE-VERIFIED", RebirthNpcRequirementStatus.IMPLEMENTED, "Major Update 25", "NetPackageRebirthNpcAppearanceEquipment.cs; NetPackageRebirthNpcSemanticEquipment.cs", "NOT_REQUIRED", "REQUIRED", "REQUIRED", "Concrete behavior + registration + caller + all applicable persistence/network/UI obligations + failure/replay handling + traceability must pass", "Appearance/equipment baseline replication exists."),
            new RebirthNpcRequirementDefinition("NPC-REQ-044", "Networking", "Interaction request/response networking", "BASELINE-VERIFIED", RebirthNpcRequirementStatus.IMPLEMENTED, "Major Update 31", "NetPackageRebirthNpcInteraction.cs; network client used by XUi", "NOT_REQUIRED", "REQUIRED", "REQUIRED", "Concrete behavior + registration + caller + all applicable persistence/network/UI obligations + failure/replay handling + traceability must pass", "UI mutations route to the server and refresh projections."),
            new RebirthNpcRequirementDefinition("NPC-REQ-045", "Networking", "Late join/reconnect baseline completion", "BASELINE-VERIFIED", RebirthNpcRequirementStatus.IMPLEMENTED, "Major Update 25", "RebirthNpcNetworkBaselineService", "NOT_REQUIRED", "REQUIRED", "NOT_REQUIRED", "Concrete behavior + registration + caller + all applicable persistence/network/UI obligations + failure/replay handling + traceability must pass", "Baseline synchronization and completion signalling exist."),
            new RebirthNpcRequirementDefinition("NPC-REQ-046", "Networking", "Interest management and bandwidth policy", "ACIP-10", RebirthNpcRequirementStatus.IMPLEMENTED, "Architecture §§41.8–41.10", "Scripts/Rebirth/NPC/Replication/RebirthNpcReplicationPerformanceIntegration.cs; Scripts/Rebirth/NPC/Progression/RebirthNpcProgressionReplication.cs; Scripts/Rebirth/NPC/Social/RebirthNpcSocialService.cs; Scripts/Rebirth/NPC/Foundation/RebirthNpcLifecycle.cs; Scripts/Rebirth/NPC/Administration/RebirthNpcAdministrationSupport.cs", "NOT_REQUIRED", "NOT_REQUIRED", "NOT_REQUIRED", "Concrete behavior + registration + caller + all applicable persistence/network/UI obligations + failure/replay handling + traceability must pass", "Ownership, interaction, visibility, distance and activity determine documented tiers with per-domain frequency and byte budgets, out-of-interest suppression and baseline recovery."),
            new RebirthNpcRequirementDefinition("NPC-REQ-047", "Networking", "Client prediction/interpolation", "ACIP-10", RebirthNpcRequirementStatus.IMPLEMENTED, "Architecture §41.11", "Scripts/Rebirth/NPC/Replication/RebirthNpcReplicationPerformanceIntegration.cs; Scripts/Rebirth/NPC/Progression/RebirthNpcProgressionReplication.cs; Scripts/Rebirth/NPC/Social/RebirthNpcSocialService.cs; Scripts/Rebirth/NPC/Foundation/RebirthNpcLifecycle.cs; Scripts/Rebirth/NPC/Administration/RebirthNpcAdministrationSupport.cs", "NOT_REQUIRED", "NOT_REQUIRED", "NOT_REQUIRED", "Concrete behavior + registration + caller + all applicable persistence/network/UI obligations + failure/replay handling + traceability must pass", "Client visual tracks provide revision-gated interpolation and bounded 250 ms prediction; predicted values cannot mutate authoritative state and corrections are counted."),
            new RebirthNpcRequirementDefinition("NPC-REQ-048", "Networking", "Security validation and anti-replay", "BASELINE-VERIFIED", RebirthNpcRequirementStatus.IMPLEMENTED, "Architecture §§19.5,41.15", "Command system; interaction sessions; network packages", "NOT_REQUIRED", "NOT_REQUIRED", "NOT_REQUIRED", "Concrete behavior + registration + caller + all applicable persistence/network/UI obligations + failure/replay handling + traceability must pass", "Server ownership, session, revision, replay ID and permission checks exist."),
            new RebirthNpcRequirementDefinition("NPC-REQ-049", "Inventory & Equipment", "Authoritative inventory transactions", "BASELINE-VERIFIED", RebirthNpcRequirementStatus.IMPLEMENTED, "Phases 29–31", "RebirthNpcInventoryTransactions.cs; RebirthNpcInventoryAuthority.cs", "NOT_REQUIRED", "NOT_REQUIRED", "NOT_REQUIRED", "Concrete behavior + registration + caller + all applicable persistence/network/UI obligations + failure/replay handling + traceability must pass", "Reservations, revisions, debit/credit and replay protection exist."),
            new RebirthNpcRequirementDefinition("NPC-REQ-050", "Inventory & Equipment", "External endpoints and compensated transfer", "BASELINE-VERIFIED", RebirthNpcRequirementStatus.IMPLEMENTED, "Major Updates 5–6,10", "RebirthNpcExternalInventoryGateway.cs; logistics/physical adapters", "NOT_REQUIRED", "NOT_REQUIRED", "NOT_REQUIRED", "Concrete behavior + registration + caller + all applicable persistence/network/UI obligations + failure/replay handling + traceability must pass", "Endpoint reservations, transfer coordination and compensation exist."),
            new RebirthNpcRequirementDefinition("NPC-REQ-051", "Inventory & Equipment", "Inventory disposition on dismissal/death", "BASELINE-VERIFIED", RebirthNpcRequirementStatus.IMPLEMENTED, "Inventory architecture", "RebirthNpcInventoryDisposition.cs", "NOT_REQUIRED", "NOT_REQUIRED", "NOT_REQUIRED", "Concrete behavior + registration + caller + all applicable persistence/network/UI obligations + failure/replay handling + traceability must pass", "Reason-based disposition policy exists."),
            new RebirthNpcRequirementDefinition("NPC-REQ-052", "Inventory & Equipment", "Item integrity diagnostics", "BASELINE-VERIFIED", RebirthNpcRequirementStatus.IMPLEMENTED, "Inventory validation", "RebirthNpcItemIntegrityService.cs", "NOT_REQUIRED", "NOT_REQUIRED", "NOT_REQUIRED", "Concrete behavior + registration + caller + all applicable persistence/network/UI obligations + failure/replay handling + traceability must pass", "Integrity snapshot/accounting exists."),
            new RebirthNpcRequirementDefinition("NPC-REQ-053", "Inventory & Equipment", "Semantic equipment state", "BASELINE-VERIFIED", RebirthNpcRequirementStatus.IMPLEMENTED, "Milestone 2", "RebirthNpcEquipmentService.cs", "NOT_REQUIRED", "NOT_REQUIRED", "REQUIRED", "Concrete behavior + registration + caller + all applicable persistence/network/UI obligations + failure/replay handling + traceability must pass", "Validated slots, revisions and replay journal exist."),
            new RebirthNpcRequirementDefinition("NPC-REQ-054", "Inventory & Equipment", "Native ItemValue/equipment bridge", "BASELINE-VERIFIED", RebirthNpcRequirementStatus.IMPLEMENTED, "Milestone 2; Major Update 27", "RebirthNpcNativeEquipmentBridge.cs", "NOT_REQUIRED", "NOT_REQUIRED", "REQUIRED", "Concrete behavior + registration + caller + all applicable persistence/network/UI obligations + failure/replay handling + traceability must pass", "Semantic equipment projects into native inventory/equipment."),
            new RebirthNpcRequirementDefinition("NPC-REQ-055", "Inventory & Equipment", "Weapon use, ammo, accuracy and reload mechanics", "ACIP-02", RebirthNpcRequirementStatus.IMPLEMENTED, "Architecture §24", "AvatarSdcsNpcController.cs; native equipment bridge", "NOT_REQUIRED", "NOT_REQUIRED", "REQUIRED", "Concrete behavior + registration + caller + all applicable persistence/network/UI obligations + failure/replay handling + traceability must pass", "Animation/equipment hooks exist, but no full authoritative weapon-use subsystem was found."),
            new RebirthNpcRequirementDefinition("NPC-REQ-056", "Inventory & Equipment", "Quick Stack and remote-resource integration", "ACIP-09", RebirthNpcRequirementStatus.PARTIAL, "Architecture §23.5", "External inventory endpoint abstractions", "NOT_REQUIRED", "NOT_REQUIRED", "REQUIRED", "Concrete behavior + registration + caller + all applicable persistence/network/UI obligations + failure/replay handling + traceability must pass", "Resource integration exists, but no explicit NPC Quick Stack command/UI integration was found."),
            new RebirthNpcRequirementDefinition("NPC-REQ-057", "Work", "Work assignment and capability evaluation", "BASELINE-VERIFIED", RebirthNpcRequirementStatus.IMPLEMENTED, "Architecture §25", "RebirthNpcWorkDomain.cs; RebirthNpcWorkAssignmentService.cs", "NOT_REQUIRED", "NOT_REQUIRED", "NOT_REQUIRED", "Concrete behavior + registration + caller + all applicable persistence/network/UI obligations + failure/replay handling + traceability must pass", "Typed work definitions, assignments and capability checks exist."),
            new RebirthNpcRequirementDefinition("NPC-REQ-058", "Work", "Reservations and coordinator", "BASELINE-VERIFIED", RebirthNpcRequirementStatus.IMPLEMENTED, "Major Update 3", "RebirthNpcWorkReservationsAndCoordinator.cs", "NOT_REQUIRED", "NOT_REQUIRED", "NOT_REQUIRED", "Concrete behavior + registration + caller + all applicable persistence/network/UI obligations + failure/replay handling + traceability must pass", "Target reservation, expiry and executor coordination exist."),
            new RebirthNpcRequirementDefinition("NPC-REQ-059", "Work", "Outcomes, checkpoints and progression event publishing", "BASELINE-VERIFIED", RebirthNpcRequirementStatus.IMPLEMENTED, "Roadmap §4.12", "RebirthNpcWorkOutcomesAndEvents.cs; checkpoint/outcome persistence", "REQUIRED", "NOT_REQUIRED", "NOT_REQUIRED", "Concrete behavior + registration + caller + all applicable persistence/network/UI obligations + failure/replay handling + traceability must pass", "Durable outcomes/checkpoints and bounded event publication exist."),
            new RebirthNpcRequirementDefinition("NPC-REQ-060", "Work", "Advanced Farming harvest", "BASELINE-VERIFIED", RebirthNpcRequirementStatus.IMPLEMENTED, "Major Update 7", "RebirthNpcAdvancedFarmingWorkAdapter.cs", "NOT_REQUIRED", "NOT_REQUIRED", "NOT_REQUIRED", "Concrete behavior + registration + caller + all applicable persistence/network/UI obligations + failure/replay handling + traceability must pass", "Harvest validation/execution adapter exists."),
            new RebirthNpcRequirementDefinition("NPC-REQ-061", "Work", "Planting and watering", "BASELINE-VERIFIED", RebirthNpcRequirementStatus.IMPLEMENTED, "Major Update 8", "RebirthNpcAdvancedFarmingPlantingWateringAdapter.cs", "NOT_REQUIRED", "NOT_REQUIRED", "NOT_REQUIRED", "Concrete behavior + registration + caller + all applicable persistence/network/UI obligations + failure/replay handling + traceability must pass", "Planting/watering validation and resource handling exist."),
            new RebirthNpcRequirementDefinition("NPC-REQ-062", "Work", "Farming packages and multi-target orchestration", "BASELINE-VERIFIED", RebirthNpcRequirementStatus.IMPLEMENTED, "Major Update 9", "RebirthNpcFarmingWorkPackageService.cs", "NOT_REQUIRED", "NOT_REQUIRED", "NOT_REQUIRED", "Concrete behavior + registration + caller + all applicable persistence/network/UI obligations + failure/replay handling + traceability must pass", "Bounded target sequences and partial execution exist."),
            new RebirthNpcRequirementDefinition("NPC-REQ-063", "Work", "Settlement logistics and hauling", "BASELINE-VERIFIED", RebirthNpcRequirementStatus.IMPLEMENTED, "Major Updates 5,6,10", "RebirthNpcSettlementLogisticsPackageService.cs; RebirthNpcHaulingWorkExecutor.cs", "NOT_REQUIRED", "NOT_REQUIRED", "NOT_REQUIRED", "Concrete behavior + registration + caller + all applicable persistence/network/UI obligations + failure/replay handling + traceability must pass", "Mixed endpoint routing, partial hauling and compensation exist."),
            new RebirthNpcRequirementDefinition("NPC-REQ-064", "Work", "Workstation crafting and queue orchestration", "BASELINE-VERIFIED", RebirthNpcRequirementStatus.IMPLEMENTED, "Major Update 11", "RebirthNpcWorkstationExecutionService.cs", "NOT_REQUIRED", "NOT_REQUIRED", "NOT_REQUIRED", "Concrete behavior + registration + caller + all applicable persistence/network/UI obligations + failure/replay handling + traceability must pass", "Recipe resolution, native queue construction and input/fuel handling exist."),
            new RebirthNpcRequirementDefinition("NPC-REQ-065", "Work", "Construction, repair, upgrade and placement", "BASELINE-VERIFIED", RebirthNpcRequirementStatus.IMPLEMENTED, "Major Update 12", "RebirthNpcConstructionWorkPackageService.cs", "NOT_REQUIRED", "NOT_REQUIRED", "NOT_REQUIRED", "Concrete behavior + registration + caller + all applicable persistence/network/UI obligations + failure/replay handling + traceability must pass", "Packages, material reservations and mutation boundaries exist."),
            new RebirthNpcRequirementDefinition("NPC-REQ-066", "Work", "Mining/resource extraction", "BASELINE-VERIFIED", RebirthNpcRequirementStatus.IMPLEMENTED, "Major Update 13", "RebirthNpcMiningWorkPackageService.cs", "NOT_REQUIRED", "NOT_REQUIRED", "NOT_REQUIRED", "Concrete behavior + registration + caller + all applicable persistence/network/UI obligations + failure/replay handling + traceability must pass", "Mining package and adapter contracts exist."),
            new RebirthNpcRequirementDefinition("NPC-REQ-067", "Work", "Scavenging/container extraction", "BASELINE-VERIFIED", RebirthNpcRequirementStatus.IMPLEMENTED, "Major Update 14", "RebirthNpcScavengingWorkPackageService.cs", "NOT_REQUIRED", "NOT_REQUIRED", "NOT_REQUIRED", "Concrete behavior + registration + caller + all applicable persistence/network/UI obligations + failure/replay handling + traceability must pass", "Transfer plans, reservations and compensation exist."),
            new RebirthNpcRequirementDefinition("NPC-REQ-068", "Work", "Guard-post duty", "BASELINE-VERIFIED", RebirthNpcRequirementStatus.IMPLEMENTED, "Major Update 15", "RebirthNpcGuardDutyWorkPackageService.cs", "REQUIRED", "NOT_REQUIRED", "NOT_REQUIRED", "Concrete behavior + registration + caller + all applicable persistence/network/UI obligations + failure/replay handling + traceability must pass", "Guard duty package and restoration exist."),
            new RebirthNpcRequirementDefinition("NPC-REQ-069", "Work", "Medical treatment duty", "BASELINE-VERIFIED", RebirthNpcRequirementStatus.IMPLEMENTED, "Major Update 16", "RebirthNpcMedicalTreatmentWorkPackageService.cs", "NOT_REQUIRED", "NOT_REQUIRED", "NOT_REQUIRED", "Concrete behavior + registration + caller + all applicable persistence/network/UI obligations + failure/replay handling + traceability must pass", "Treatment package, supply handling and target flow exist."),
            new RebirthNpcRequirementDefinition("NPC-REQ-070", "Work", "Offline work simulation and production economy", "ACIP-09", RebirthNpcRequirementStatus.PARTIAL, "Roadmap §4.24", "RebirthNpcSettlementSimulation.cs; RebirthNpcSettlementOperations.cs", "NOT_REQUIRED", "NOT_REQUIRED", "NOT_REQUIRED", "Concrete behavior + registration + caller + all applicable persistence/network/UI obligations + failure/replay handling + traceability must pass", "A simulation exists, but complete elapsed-time offline production chains and balancing are not implemented."),
            new RebirthNpcRequirementDefinition("NPC-REQ-071", "Interaction & Social", "Contextual interaction projection", "BASELINE-VERIFIED", RebirthNpcRequirementStatus.IMPLEMENTED, "Major Update 17", "RebirthNpcInteractionPresentationService.cs; RebirthNpcInteractionXUi.cs", "NOT_REQUIRED", "NOT_REQUIRED", "REQUIRED", "Concrete behavior + registration + caller + all applicable persistence/network/UI obligations + failure/replay handling + traceability must pass", "Stable menu entries and XUi opening exist."),
            new RebirthNpcRequirementDefinition("NPC-REQ-072", "Interaction & Social", "Authoritative mutation handlers", "BASELINE-VERIFIED", RebirthNpcRequirementStatus.IMPLEMENTED, "Major Update 18", "RebirthNpcInteractionMutationHandlers.cs; router", "NOT_REQUIRED", "NOT_REQUIRED", "REQUIRED", "Concrete behavior + registration + caller + all applicable persistence/network/UI obligations + failure/replay handling + traceability must pass", "Hire/dismiss/order/work/dialogue/trade mutations use permission/revision checks."),
            new RebirthNpcRequirementDefinition("NPC-REQ-073", "Interaction & Social", "Direct entity activation binding", "BASELINE-VERIFIED", RebirthNpcRequirementStatus.IMPLEMENTED, "Qualification Closure", "RebirthNpcDirectActivationBinding", "NOT_REQUIRED", "NOT_REQUIRED", "NOT_REQUIRED", "Concrete behavior + registration + caller + all applicable persistence/network/UI obligations + failure/replay handling + traceability must pass", "Harmony-based activation opens the interaction surface."),
            new RebirthNpcRequirementDefinition("NPC-REQ-074", "Interaction & Social", "Dialogue profiles, topics and bounded conversations", "BASELINE-VERIFIED", RebirthNpcRequirementStatus.IMPLEMENTED, "Major Update 20", "RebirthNpcDialogueService.cs", "NOT_REQUIRED", "NOT_REQUIRED", "REQUIRED", "Concrete behavior + registration + caller + all applicable persistence/network/UI obligations + failure/replay handling + traceability must pass", "Profile topics, permission filtering, turns, expiry and deterministic events exist."),
            new RebirthNpcRequirementDefinition("NPC-REQ-075", "Interaction & Social", "Dynamic dialogue-topic XUi", "BASELINE-VERIFIED", RebirthNpcRequirementStatus.IMPLEMENTED, "Major Update 31", "RebirthNpcTradeDialogueXUi.cs", "NOT_REQUIRED", "NOT_REQUIRED", "REQUIRED", "Concrete behavior + registration + caller + all applicable persistence/network/UI obligations + failure/replay handling + traceability must pass", "Server-projected topics populate bounded dynamic controls."),
            new RebirthNpcRequirementDefinition("NPC-REQ-076", "Interaction & Social", "Trade offers, quotes and compensated transactions", "BASELINE-VERIFIED", RebirthNpcRequirementStatus.IMPLEMENTED, "Major Update 19", "RebirthNpcTradeService.cs; trade XUi; player endpoint", "NOT_REQUIRED", "NOT_REQUIRED", "REQUIRED", "Concrete behavior + registration + caller + all applicable persistence/network/UI obligations + failure/replay handling + traceability must pass", "Offer registry, quote expiry/revision and compensated inventory/currency mutation exist."),
            new RebirthNpcRequirementDefinition("NPC-REQ-077", "Interaction & Social", "Production trade/economy content", "ACIP-09", RebirthNpcRequirementStatus.PARTIAL, "Roadmap §4.21", "Trade offer registry exists", "NOT_REQUIRED", "NOT_REQUIRED", "REQUIRED", "Concrete behavior + registration + caller + all applicable persistence/network/UI obligations + failure/replay handling + traceability must pass", "No comprehensive balanced offer catalogue or trader differentiation was found."),
            new RebirthNpcRequirementDefinition("NPC-REQ-078", "Interaction & Social", "Social memories and relationships", "BASELINE-VERIFIED", RebirthNpcRequirementStatus.IMPLEMENTED, "Social architecture", "RebirthNpcSocialService.cs; social persistence", "NOT_REQUIRED", "NOT_REQUIRED", "NOT_REQUIRED", "Concrete behavior + registration + caller + all applicable persistence/network/UI obligations + failure/replay handling + traceability must pass", "Bounded memories, relationship dimensions and replay IDs exist."),
            new RebirthNpcRequirementDefinition("NPC-REQ-079", "Interaction & Social", "Faction standing projection", "BASELINE-VERIFIED", RebirthNpcRequirementStatus.IMPLEMENTED, "Architecture §20.4", "RebirthNpcSocialGameplayIntegration.cs; social persistence", "REQUIRED", "NOT_REQUIRED", "NOT_REQUIRED", "Concrete behavior + registration + caller + all applicable persistence/network/UI obligations + failure/replay handling + traceability must pass", "Faction standing mutation and persistence exist."),
            new RebirthNpcRequirementDefinition("NPC-REQ-080", "Interaction & Social", "Gameplay social event producers", "ACIP-09", RebirthNpcRequirementStatus.PARTIAL, "Social Event Source Integration", "RebirthNpcSocialGameplayEventProducers.cs", "NOT_REQUIRED", "NOT_REQUIRED", "NOT_REQUIRED", "Concrete behavior + registration + caller + all applicable persistence/network/UI obligations + failure/replay handling + traceability must pass", "Combat/damage and explicit producer APIs exist, but all documented sources are not wired."),
            new RebirthNpcRequirementDefinition("NPC-REQ-081", "Interaction & Social", "Names and identity presentation", "ACIP-08", RebirthNpcRequirementStatus.IMPLEMENTED, "Architecture §27.1", "Scripts/Rebirth/NPC/WorldIntegration/RebirthNpcWorldIntegration.cs: GenerateName, GetDisplayName, persisted RebirthNpcWorldIdentityRecord; Scripts/Rebirth/NPC/Administration/RebirthNpcAdministrationSupport.cs: worldintegration", "NOT_REQUIRED", "NOT_REQUIRED", "REQUIRED", "Concrete behavior + registration + caller + all applicable persistence/network/UI obligations + failure/replay handling + traceability must pass", "Deterministic localized identity keys and durable display names are assigned from stable identity and exposed to presentation/admin projections."),
            new RebirthNpcRequirementDefinition("NPC-REQ-082", "Interaction & Social", "Nav/compass markers", "ACIP-08", RebirthNpcRequirementStatus.IMPLEMENTED, "Architecture §27.2", "Scripts/Rebirth/NPC/WorldIntegration/RebirthNpcWorldIntegration.cs: UpdateMarker, RemoveMarker, RemoveMarkersForNpc, owner/party authorization; Scripts/Rebirth/NPC/Foundation/RebirthNpcLifecycle.cs: registration", "NOT_REQUIRED", "NOT_REQUIRED", "REQUIRED", "Concrete behavior + registration + caller + all applicable persistence/network/UI obligations + failure/replay handling + traceability must pass", "Compass/map markers are authorized by ownership or party membership and removed on unload, invalid presence or terminal lifecycle."),
            new RebirthNpcRequirementDefinition("NPC-REQ-083", "Interaction & Social", "Animation and sound integration", "ACIP-08", RebirthNpcRequirementStatus.IMPLEMENTED, "Architecture §27.3", "Scripts/Rebirth/NPC/WorldIntegration/RebirthNpcWorldIntegration.cs: PublishPresentation, activity/sound mappings; Scripts/Rebirth/NPC/Activity/RebirthNpcActivityRuntime.cs: OnActivityTransition caller; Scripts/Rebirth/NPC/Combat/RebirthNpcTargetingAndCombatAi.cs: OnCombatTransition caller", "NOT_REQUIRED", "NOT_REQUIRED", "NOT_REQUIRED", "Concrete behavior + registration + caller + all applicable persistence/network/UI obligations + failure/replay handling + traceability must pass", "Category/profile animation and sound mappings are invoked from real activity and combat transitions."),
            new RebirthNpcRequirementDefinition("NPC-REQ-084", "World Integration", "Spawn composition category integration", "ACIP-08", RebirthNpcRequirementStatus.PARTIAL, "Architecture §28", "Scripts/Rebirth/NPC/WorldIntegration/RebirthNpcWorldIntegration.cs: TryComposeSpawn, production spawn groups and native Spawn adapter; Scripts/Rebirth/NPC/Foundation/RebirthNpcLifecycle.cs: initialization", "NOT_REQUIRED", "NOT_REQUIRED", "NOT_REQUIRED", "Concrete behavior + registration + caller + all applicable persistence/network/UI obligations + failure/replay handling + traceability must pass", "Profiles and spawn-service scaffolding exist. Native spawn adapter, encounter callers/groups and durable replay/save reconciliation remain missing; native qualification is not performed."),
            new RebirthNpcRequirementDefinition("NPC-REQ-085", "World Integration", "Ambient-to-persistent handoff", "ACIP-08", RebirthNpcRequirementStatus.IMPLEMENTED, "Architecture §28.3", "Scripts/Rebirth/NPC/WorldIntegration/RebirthNpcWorldIntegration.cs: TryPromoteAmbient, exactly-once ByAmbient map, stable-ID registration, atomic RebirthNpcWorldIntegration.xml persistence", "REQUIRED", "NOT_REQUIRED", "NOT_REQUIRED", "Concrete behavior + registration + caller + all applicable persistence/network/UI obligations + failure/replay handling + traceability must pass", "Eligible ambient NPCs are promoted once to durable stable identity with duplicate prevention and persistent registration."),
            new RebirthNpcRequirementDefinition("NPC-REQ-086", "World Integration", "Entity warming integration", "ACIP-08", RebirthNpcRequirementStatus.IMPLEMENTED, "Architecture §28.4", "Scripts/Rebirth/NPC/WorldIntegration/RebirthNpcWorldIntegration.cs: OnWarmActivated, OnWarmDeactivated, stable-ID duplicate guard; Scripts/Rebirth/NPC/Foundation/RebirthNpcLifecycle.cs: registration/reset; Scripts/Rebirth/NPC/Administration/RebirthNpcAdministrationSupport.cs: diagnostics", "NOT_REQUIRED", "NOT_REQUIRED", "REQUIRED", "Concrete behavior + registration + caller + all applicable persistence/network/UI obligations + failure/replay handling + traceability must pass", "Entity warming rebinds persistent actors without duplicate stable IDs, unloads without terminal deletion, and exposes lifecycle diagnostics."),
            new RebirthNpcRequirementDefinition("NPC-REQ-087", "Settlement", "Needs model", "BASELINE-VERIFIED", RebirthNpcRequirementStatus.IMPLEMENTED, "Settlement architecture", "RebirthNpcSettlementSimulation.cs", "NOT_REQUIRED", "NOT_REQUIRED", "NOT_REQUIRED", "Concrete behavior + registration + caller + all applicable persistence/network/UI obligations + failure/replay handling + traceability must pass", "Hunger, thirst, fatigue, warmth, safety, morale, social and medical needs exist."),
            new RebirthNpcRequirementDefinition("NPC-REQ-088", "Settlement", "Profession assignment labels and skill dictionary", "BASELINE-VERIFIED", RebirthNpcRequirementStatus.IMPLEMENTED, "Settlement architecture", "RebirthNpcProfessionRecord", "NOT_REQUIRED", "NOT_REQUIRED", "NOT_REQUIRED", "Concrete behavior + registration + caller + all applicable persistence/network/UI obligations + failure/replay handling + traceability must pass", "Settlement work matching can use profession ID and skill values."),
            new RebirthNpcRequirementDefinition("NPC-REQ-089", "Settlement", "Complete NPC progression/profession system", "ACIP-01", RebirthNpcRequirementStatus.IMPLEMENTED, "NPC Progression Specification", "Scripts/Rebirth/NPC/Progression/RebirthNpcProgressionDomain.cs; Scripts/Rebirth/NPC/Progression/RebirthNpcProgressionService.cs; Scripts/Rebirth/NPC/Progression/RebirthNpcProgressionPersistence.cs; Scripts/Rebirth/NPC/Work/RebirthNpcWorkOutcomesAndEvents.cs", "REQUIRED", "NOT_REQUIRED", "REQUIRED", "Concrete behavior + registration + caller + all applicable persistence/network/UI obligations + failure/replay handling + traceability must pass", "The authoritative generic progression/profession foundation, durable records, work-event caller and persistence are concrete; specialized profession adapters remain independently tracked by NPC-REQ-113..120."),
            new RebirthNpcRequirementDefinition("NPC-REQ-090", "Performance", "Spatial indexing", "BASELINE-VERIFIED", RebirthNpcRequirementStatus.IMPLEMENTED, "WP18", "RebirthNpcSpatialIndex", "NOT_REQUIRED", "NOT_REQUIRED", "NOT_REQUIRED", "Concrete behavior + registration + caller + all applicable persistence/network/UI obligations + failure/replay handling + traceability must pass", "Grid update/removal/radius query exists."),
            new RebirthNpcRequirementDefinition("NPC-REQ-091", "Performance", "Bounded caches and retention", "BASELINE-VERIFIED", RebirthNpcRequirementStatus.IMPLEMENTED, "WP18", "RebirthNpcBoundedCache; RebirthNpcRetentionCoordinator", "NOT_REQUIRED", "NOT_REQUIRED", "NOT_REQUIRED", "Concrete behavior + registration + caller + all applicable persistence/network/UI obligations + failure/replay handling + traceability must pass", "Capacity, expiry, eviction and cleanup are explicit."),
            new RebirthNpcRequirementDefinition("NPC-REQ-092", "Performance", "Path budgets", "BASELINE-VERIFIED", RebirthNpcRequirementStatus.IMPLEMENTED, "WP18", "RebirthNpcPathBudgetCoordinator", "NOT_REQUIRED", "NOT_REQUIRED", "NOT_REQUIRED", "Concrete behavior + registration + caller + all applicable persistence/network/UI obligations + failure/replay handling + traceability must pass", "Critical/interactive/background budgets exist."),
            new RebirthNpcRequirementDefinition("NPC-REQ-093", "Performance", "Network batching integration", "ACIP-10", RebirthNpcRequirementStatus.IMPLEMENTED, "WP18", "Scripts/Rebirth/NPC/Replication/RebirthNpcReplicationPerformanceIntegration.cs; Scripts/Rebirth/NPC/Progression/RebirthNpcProgressionReplication.cs; Scripts/Rebirth/NPC/Social/RebirthNpcSocialService.cs; Scripts/Rebirth/NPC/Foundation/RebirthNpcLifecycle.cs; Scripts/Rebirth/NPC/Administration/RebirthNpcAdministrationSupport.cs", "NOT_REQUIRED", "REQUIRED", "NOT_REQUIRED", "Concrete behavior + registration + caller + all applicable persistence/network/UI obligations + failure/replay handling + traceability must pass", "Production progression delta replication enters the interest/budget policy and RebirthNpcNetworkBatcher; low-frequency exemptions must be explicit."),
            new RebirthNpcRequirementDefinition("NPC-REQ-094", "Performance", "Serialization buffer pooling", "BASELINE-VERIFIED", RebirthNpcRequirementStatus.IMPLEMENTED, "WP18", "RebirthNpcSerializationBufferPool", "NOT_REQUIRED", "NOT_REQUIRED", "NOT_REQUIRED", "Concrete behavior + registration + caller + all applicable persistence/network/UI obligations + failure/replay handling + traceability must pass", "Power-of-two reuse and bounded retention exist."),
            new RebirthNpcRequirementDefinition("NPC-REQ-095", "Performance", "Relationship batching integration", "ACIP-10", RebirthNpcRequirementStatus.IMPLEMENTED, "WP18", "Scripts/Rebirth/NPC/Replication/RebirthNpcReplicationPerformanceIntegration.cs; Scripts/Rebirth/NPC/Progression/RebirthNpcProgressionReplication.cs; Scripts/Rebirth/NPC/Social/RebirthNpcSocialService.cs; Scripts/Rebirth/NPC/Foundation/RebirthNpcLifecycle.cs; Scripts/Rebirth/NPC/Administration/RebirthNpcAdministrationSupport.cs", "NOT_REQUIRED", "NOT_REQUIRED", "NOT_REQUIRED", "Concrete behavior + registration + caller + all applicable persistence/network/UI obligations + failure/replay handling + traceability must pass", "Committed social mutations enter RebirthNpcRelationshipBatcher with per-source monotonic sequence, replay suppression, ordered drain and deferral counters."),
            new RebirthNpcRequirementDefinition("NPC-REQ-096", "Performance", "Synthetic scale benchmark", "BASELINE-VERIFIED", RebirthNpcRequirementStatus.IMPLEMENTED, "WP18", "RebirthNpcScaleBenchmarkService", "NOT_REQUIRED", "NOT_REQUIRED", "NOT_REQUIRED", "Concrete behavior + registration + caller + all applicable persistence/network/UI obligations + failure/replay handling + traceability must pass", "Synthetic spatial/serialization/batch measurements exist."),
            new RebirthNpcRequirementDefinition("NPC-REQ-097", "Administration", "Administration report and inspection", "BASELINE-VERIFIED", RebirthNpcRequirementStatus.IMPLEMENTED, "WP19", "RebirthNpcAdministrationSupport.cs", "NOT_REQUIRED", "NOT_REQUIRED", "REQUIRED", "Concrete behavior + registration + caller + all applicable persistence/network/UI obligations + failure/replay handling + traceability must pass", "Status, NPC inspection, queues, validation, export, recovery and audit exist."),
            new RebirthNpcRequirementDefinition("NPC-REQ-098", "Administration", "Support export and backup recovery", "BASELINE-VERIFIED", RebirthNpcRequirementStatus.IMPLEMENTED, "WP19", "RebirthNpcAdministrationSupport.cs", "REQUIRED", "NOT_REQUIRED", "NOT_REQUIRED", "Concrete behavior + registration + caller + all applicable persistence/network/UI obligations + failure/replay handling + traceability must pass", "Allow-listed export and quarantined backup restoration exist."),
            new RebirthNpcRequirementDefinition("NPC-REQ-099", "Compatibility", "b259 API/build qualification", "BASELINE-VERIFIED", RebirthNpcRequirementStatus.IMPLEMENTED, "Corrected WP21", "RebirthNpcBuildQualification.cs; WP21 script", "NOT_REQUIRED", "NOT_REQUIRED", "REQUIRED", "Concrete behavior + registration + caller + all applicable persistence/network/UI obligations + failure/replay handling + traceability must pass", "Exact Assembly-CSharp MVID and consumed contracts are checked."),
            new RebirthNpcRequirementDefinition("NPC-REQ-100", "Compatibility", "Base-game adapter registry", "BASELINE-VERIFIED", RebirthNpcRequirementStatus.IMPLEMENTED, "WP17", "RebirthNpcBaseGameAdapters.cs", "NOT_REQUIRED", "NOT_REQUIRED", "NOT_REQUIRED", "Concrete behavior + registration + caller + all applicable persistence/network/UI obligations + failure/replay handling + traceability must pass", "Capability descriptors and lookup exist."),
            new RebirthNpcRequirementDefinition("NPC-REQ-101", "Compatibility", "Supported 2.6 migration", "ACIP-11", RebirthNpcRequirementStatus.IMPLEMENTED, "Architecture §18.5; WP17", "Scripts/Rebirth/NPC/Compatibility/RebirthNpcLegacyMigration.cs; Scripts/Rebirth/NPC/Persistence/RebirthNpcAggregatePersistence.cs; BuildScripts/NPC/Fixtures/ACIP-11/legacy26_supported.xml; BuildScripts/NPC/Invoke-RebirthNpcAcip11Qualification.py", "REQUIRED", "NOT_REQUIRED", "NOT_REQUIRED", "Concrete behavior + registration + caller + all applicable persistence/network/UI obligations + failure/replay handling + traceability must pass", "Supported 2.6 fields are governed by explicit map/discard/fail rules with deterministic IDs, idempotence, audit, rollback and quarantine."),
            new RebirthNpcRequirementDefinition("NPC-REQ-102", "Compatibility", "Third-party capability interfaces", "BASELINE-VERIFIED", RebirthNpcRequirementStatus.IMPLEMENTED, "WP17", "RebirthNpcThirdPartyCapabilities.cs", "NOT_REQUIRED", "NOT_REQUIRED", "NOT_REQUIRED", "Concrete behavior + registration + caller + all applicable persistence/network/UI obligations + failure/replay handling + traceability must pass", "Versioned registration and duplicate/server-safety checks exist."),
            new RebirthNpcRequirementDefinition("NPC-REQ-103", "Validation", "Release-candidate gate/evidence model", "BASELINE-VERIFIED", RebirthNpcRequirementStatus.IMPLEMENTED, "WP20", "RebirthNpcReleaseCandidateValidation.cs", "NOT_REQUIRED", "NOT_REQUIRED", "NOT_REQUIRED", "Concrete behavior + registration + caller + all applicable persistence/network/UI obligations + failure/replay handling + traceability must pass", "Static and runtime-evidence gates are represented."),
            new RebirthNpcRequirementDefinition("NPC-REQ-104", "Validation", "Production qualification checks", "BASELINE-VERIFIED", RebirthNpcRequirementStatus.IMPLEMENTED, "Qualification closure", "RebirthNpcProductionQualification.cs", "NOT_REQUIRED", "NOT_REQUIRED", "NOT_REQUIRED", "Concrete behavior + registration + caller + all applicable persistence/network/UI obligations + failure/replay handling + traceability must pass", "Cross-service static checks cover major integrations."),
            new RebirthNpcRequirementDefinition("NPC-REQ-105", "Validation", "Automated feature-level conformance test suite", "ACIP-00", RebirthNpcRequirementStatus.IMPLEMENTED, "Architecture acceptance criteria", "Scripts/Rebirth/NPC/Conformance/RebirthNpcConformanceControlPlane.cs; BuildScripts/NPC/Invoke-RebirthNpcConformanceAudit.py; BuildScripts/NPC/Invoke-RebirthNpcCompletionGate.py; RebirthNpcLifecycle.RegisterServicesNoLock; ConsoleCmdRebirthNpc.Execute(conformance)", "NOT_REQUIRED", "NOT_REQUIRED", "REQUIRED", "Concrete behavior + registration + caller + all applicable persistence/network/UI obligations + failure/replay handling + traceability must pass", "No unit-test suite automatically proves every documentation requirement."),
            new RebirthNpcRequirementDefinition("NPC-REQ-106", "NPC Progression", "Generic progression definitions and records", "ACIP-01", RebirthNpcRequirementStatus.IMPLEMENTED, "Progression §§4.1–4.10", "Scripts/Rebirth/NPC/Progression/RebirthNpcProgressionDomain.cs; Scripts/Rebirth/NPC/Progression/RebirthNpcProgressionService.cs; RebirthNpcLifecycle.RegisterServicesNoLock", "REQUIRED", "NOT_REQUIRED", "REQUIRED", "Concrete behavior + registration + caller + all applicable persistence/network/UI obligations + failure/replay handling + traceability must pass", "Concrete definition, record, entry, request/result, query and authoritative service types are registered and callable."),
            new RebirthNpcRequirementDefinition("NPC-REQ-107", "NPC Progression", "XP validation, deduplication and anti-exploit pipeline", "ACIP-01", RebirthNpcRequirementStatus.IMPLEMENTED, "Progression §5", "Scripts/Rebirth/NPC/Progression/RebirthNpcProgressionService.cs; Scripts/Rebirth/NPC/Work/RebirthNpcWorkOutcomesAndEvents.cs; Scripts/Rebirth/NPC/Progression/RebirthNpcProgressionQualification.cs", "REQUIRED", "NOT_REQUIRED", "REQUIRED", "Concrete behavior + registration + caller + all applicable persistence/network/UI obligations + failure/replay handling + traceability must pass", "Server authority, source validation, award bounds, replay IDs, duplicate suppression and explicit rejection codes are implemented; work outcomes reach a registered sink."),
            new RebirthNpcRequirementDefinition("NPC-REQ-108", "NPC Progression", "Quadratic level mathematics and multi-level awards", "ACIP-01", RebirthNpcRequirementStatus.IMPLEMENTED, "Progression §6", "Scripts/Rebirth/NPC/Progression/RebirthNpcProgressionDomain.cs; Scripts/Rebirth/NPC/Progression/RebirthNpcProgressionService.cs; Scripts/Rebirth/NPC/Progression/RebirthNpcProgressionPersistence.cs; Scripts/Rebirth/NPC/Progression/RebirthNpcProgressionQualification.cs", "REQUIRED", "NOT_REQUIRED", "REQUIRED", "Concrete behavior + registration + caller + all applicable persistence/network/UI obligations + failure/replay handling + traceability must pass", "Integer quadratic thresholds A=125/B=375, bounded binary-search level resolution, checked/clamped awards, multi-level results, versioned persistence and restoration are implemented."),
            new RebirthNpcRequirementDefinition("NPC-REQ-109", "NPC Progression", "Constitution and health scaling", "ACIP-02", RebirthNpcRequirementStatus.IMPLEMENTED, "Progression §7.2", "No corresponding concrete progression service/domain found under Scripts/Rebirth/NPC.", "NOT_REQUIRED", "NOT_REQUIRED", "NOT_REQUIRED", "Concrete behavior + registration + caller + all applicable persistence/network/UI obligations + failure/replay handling + traceability must pass", "The generic work progression-event bus and settlement skill dictionary are integration seams only; no sink implements these mechanics."),
            new RebirthNpcRequirementDefinition("NPC-REQ-110", "NPC Progression", "Strength and melee/physical scaling", "ACIP-02", RebirthNpcRequirementStatus.IMPLEMENTED, "Progression §7.3", "No corresponding concrete progression service/domain found under Scripts/Rebirth/NPC.", "NOT_REQUIRED", "NOT_REQUIRED", "NOT_REQUIRED", "Concrete behavior + registration + caller + all applicable persistence/network/UI obligations + failure/replay handling + traceability must pass", "The generic work progression-event bus and settlement skill dictionary are integration seams only; no sink implements these mechanics."),
            new RebirthNpcRequirementDefinition("NPC-REQ-111", "NPC Progression", "Dexterity movement/responsiveness/dodge scaling", "ACIP-02", RebirthNpcRequirementStatus.IMPLEMENTED, "Progression §7.4", "No corresponding concrete progression service/domain found under Scripts/Rebirth/NPC.", "NOT_REQUIRED", "NOT_REQUIRED", "NOT_REQUIRED", "Concrete behavior + registration + caller + all applicable persistence/network/UI obligations + failure/replay handling + traceability must pass", "The generic work progression-event bus and settlement skill dictionary are integration seams only; no sink implements these mechanics."),
            new RebirthNpcRequirementDefinition("NPC-REQ-112", "NPC Progression", "Weapon specialty XP, damage, accuracy and reload scaling", "ACIP-02", RebirthNpcRequirementStatus.IMPLEMENTED, "Progression §8", "No corresponding concrete progression service/domain found under Scripts/Rebirth/NPC.", "NOT_REQUIRED", "NOT_REQUIRED", "NOT_REQUIRED", "Concrete behavior + registration + caller + all applicable persistence/network/UI obligations + failure/replay handling + traceability must pass", "The generic work progression-event bus and settlement skill dictionary are integration seams only; no sink implements these mechanics."),
            new RebirthNpcRequirementDefinition("NPC-REQ-113", "NPC Progression", "Farming profession progression", "ACIP-03", RebirthNpcRequirementStatus.IMPLEMENTED, "Progression §§10.8,11", "Scripts/Rebirth/NPC/Progression/RebirthNpcProfessionProgression.cs; Scripts/Rebirth/NPC/Simulation/RebirthNpcSettlementSimulation.cs; Scripts/Rebirth/NPC/Progression/RebirthNpcProgressionAcip03Qualification.cs", "NOT_REQUIRED", "NOT_REQUIRED", "NOT_REQUIRED", "Concrete behavior + registration + caller + all applicable persistence/network/UI obligations + failure/replay handling + traceability must pass", "ACIP-03 authoritative profession outcome publisher, progression adapter, runtime consumers, settlement caller and qualification evidence."),
            new RebirthNpcRequirementDefinition("NPC-REQ-114", "NPC Progression", "Looting profession progression", "ACIP-03", RebirthNpcRequirementStatus.IMPLEMENTED, "Progression §§10.9,12", "Scripts/Rebirth/NPC/Progression/RebirthNpcProfessionProgression.cs; Scripts/Rebirth/NPC/Simulation/RebirthNpcSettlementSimulation.cs; Scripts/Rebirth/NPC/Progression/RebirthNpcProgressionAcip03Qualification.cs", "NOT_REQUIRED", "NOT_REQUIRED", "NOT_REQUIRED", "Concrete behavior + registration + caller + all applicable persistence/network/UI obligations + failure/replay handling + traceability must pass", "ACIP-03 authoritative profession outcome publisher, progression adapter, runtime consumers, settlement caller and qualification evidence."),
            new RebirthNpcRequirementDefinition("NPC-REQ-115", "NPC Progression", "Gathering profession progression", "ACIP-03", RebirthNpcRequirementStatus.IMPLEMENTED, "Progression §§10.10,13", "Scripts/Rebirth/NPC/Progression/RebirthNpcProfessionProgression.cs; Scripts/Rebirth/NPC/Simulation/RebirthNpcSettlementSimulation.cs; Scripts/Rebirth/NPC/Progression/RebirthNpcProgressionAcip03Qualification.cs", "NOT_REQUIRED", "NOT_REQUIRED", "NOT_REQUIRED", "Concrete behavior + registration + caller + all applicable persistence/network/UI obligations + failure/replay handling + traceability must pass", "ACIP-03 authoritative profession outcome publisher, progression adapter, runtime consumers, settlement caller and qualification evidence."),
            new RebirthNpcRequirementDefinition("NPC-REQ-116", "NPC Progression", "Mining profession progression", "ACIP-03", RebirthNpcRequirementStatus.IMPLEMENTED, "Progression §§10.11,14", "Scripts/Rebirth/NPC/Progression/RebirthNpcProfessionProgression.cs; Scripts/Rebirth/NPC/Simulation/RebirthNpcSettlementSimulation.cs; Scripts/Rebirth/NPC/Progression/RebirthNpcProgressionAcip03Qualification.cs", "NOT_REQUIRED", "NOT_REQUIRED", "NOT_REQUIRED", "Concrete behavior + registration + caller + all applicable persistence/network/UI obligations + failure/replay handling + traceability must pass", "ACIP-03 authoritative profession outcome publisher, progression adapter, runtime consumers, settlement caller and qualification evidence."),
            new RebirthNpcRequirementDefinition("NPC-REQ-117", "NPC Progression", "Salvaging profession progression", "ACIP-03", RebirthNpcRequirementStatus.IMPLEMENTED, "Progression §§10.12,15", "Scripts/Rebirth/NPC/Progression/RebirthNpcProfessionProgression.cs; Scripts/Rebirth/NPC/Simulation/RebirthNpcSettlementSimulation.cs; Scripts/Rebirth/NPC/Progression/RebirthNpcProgressionAcip03Qualification.cs", "NOT_REQUIRED", "NOT_REQUIRED", "NOT_REQUIRED", "Concrete behavior + registration + caller + all applicable persistence/network/UI obligations + failure/replay handling + traceability must pass", "ACIP-03 authoritative profession outcome publisher, progression adapter, runtime consumers, settlement caller and qualification evidence."),
            new RebirthNpcRequirementDefinition("NPC-REQ-118", "NPC Progression", "Cooking profession progression", "ACIP-03", RebirthNpcRequirementStatus.IMPLEMENTED, "Progression §§10.13,16", "Scripts/Rebirth/NPC/Progression/RebirthNpcProfessionProgression.cs; Scripts/Rebirth/NPC/Simulation/RebirthNpcSettlementSimulation.cs; Scripts/Rebirth/NPC/Progression/RebirthNpcProgressionAcip03Qualification.cs", "NOT_REQUIRED", "NOT_REQUIRED", "NOT_REQUIRED", "Concrete behavior + registration + caller + all applicable persistence/network/UI obligations + failure/replay handling + traceability must pass", "ACIP-03 authoritative profession outcome publisher, progression adapter, runtime consumers, settlement caller and qualification evidence."),
            new RebirthNpcRequirementDefinition("NPC-REQ-119", "NPC Progression", "Base Repairs profession progression", "ACIP-03", RebirthNpcRequirementStatus.IMPLEMENTED, "Progression §§10.14,17", "Scripts/Rebirth/NPC/Progression/RebirthNpcProfessionProgression.cs; Scripts/Rebirth/NPC/Simulation/RebirthNpcSettlementSimulation.cs; Scripts/Rebirth/NPC/Progression/RebirthNpcProgressionAcip03Qualification.cs", "NOT_REQUIRED", "NOT_REQUIRED", "NOT_REQUIRED", "Concrete behavior + registration + caller + all applicable persistence/network/UI obligations + failure/replay handling + traceability must pass", "ACIP-03 authoritative profession outcome publisher, progression adapter, runtime consumers, settlement caller and qualification evidence."),
            new RebirthNpcRequirementDefinition("NPC-REQ-120", "NPC Progression", "Medicine profession progression", "ACIP-03", RebirthNpcRequirementStatus.IMPLEMENTED, "Progression §§10.15,18", "Scripts/Rebirth/NPC/Progression/RebirthNpcProfessionProgression.cs; Scripts/Rebirth/NPC/Simulation/RebirthNpcSettlementSimulation.cs; Scripts/Rebirth/NPC/Progression/RebirthNpcProgressionAcip03Qualification.cs", "NOT_REQUIRED", "NOT_REQUIRED", "NOT_REQUIRED", "Concrete behavior + registration + caller + all applicable persistence/network/UI obligations + failure/replay handling + traceability must pass", "ACIP-03 authoritative profession outcome publisher, progression adapter, runtime consumers, settlement caller and qualification evidence."),
            new RebirthNpcRequirementDefinition("NPC-REQ-121", "NPC Progression", "Certification evaluation and dependency graph", "ACIP-04", RebirthNpcRequirementStatus.IMPLEMENTED, "Progression §§11.1,28,44–45", "Scripts/Rebirth/NPC/Progression/RebirthNpcAdvancedProgression.cs; Scripts/Rebirth/NPC/Progression/RebirthNpcAdvancedProgressionQualification.cs; Scripts/Rebirth/NPC/Progression/RebirthNpcProfessionProgression.cs; Scripts/Rebirth/NPC/Foundation/RebirthNpcLifecycle.cs; Scripts/Rebirth/NPC/Persistence/RebirthNpcPersistenceCoordinator.cs; Scripts/Rebirth/NPC/Administration/RebirthNpcAdministrationSupport.cs; _Documentation/NPC Framework/ACIP-04 - Certifications Mentorship and Specialization/ACIP-04_IMPLEMENTATION_AND_ACCEPTANCE.md", "REQUIRED", "NOT_REQUIRED", "REQUIRED", "Concrete behavior + registration + caller + all applicable persistence/network/UI obligations + failure/replay handling + traceability must pass", "Concrete ACIP-04 implementation with persistence, lifecycle, administration, failure/replay handling and direct profession consumers."),
            new RebirthNpcRequirementDefinition("NPC-REQ-122", "NPC Progression", "Mentorship runtime model", "ACIP-04", RebirthNpcRequirementStatus.IMPLEMENTED, "Progression §§11.2,46", "Scripts/Rebirth/NPC/Progression/RebirthNpcAdvancedProgression.cs; Scripts/Rebirth/NPC/Progression/RebirthNpcAdvancedProgressionQualification.cs; Scripts/Rebirth/NPC/Progression/RebirthNpcProfessionProgression.cs; Scripts/Rebirth/NPC/Foundation/RebirthNpcLifecycle.cs; Scripts/Rebirth/NPC/Persistence/RebirthNpcPersistenceCoordinator.cs; Scripts/Rebirth/NPC/Administration/RebirthNpcAdministrationSupport.cs; _Documentation/NPC Framework/ACIP-04 - Certifications Mentorship and Specialization/ACIP-04_IMPLEMENTATION_AND_ACCEPTANCE.md", "REQUIRED", "NOT_REQUIRED", "REQUIRED", "Concrete behavior + registration + caller + all applicable persistence/network/UI obligations + failure/replay handling + traceability must pass", "Concrete ACIP-04 implementation with persistence, lifecycle, administration, failure/replay handling and direct profession consumers."),
            new RebirthNpcRequirementDefinition("NPC-REQ-123", "NPC Progression", "Specialization resolution", "ACIP-04", RebirthNpcRequirementStatus.IMPLEMENTED, "Progression §§20,29", "Scripts/Rebirth/NPC/Progression/RebirthNpcAdvancedProgression.cs; Scripts/Rebirth/NPC/Progression/RebirthNpcAdvancedProgressionQualification.cs; Scripts/Rebirth/NPC/Progression/RebirthNpcProfessionProgression.cs; Scripts/Rebirth/NPC/Foundation/RebirthNpcLifecycle.cs; Scripts/Rebirth/NPC/Persistence/RebirthNpcPersistenceCoordinator.cs; Scripts/Rebirth/NPC/Administration/RebirthNpcAdministrationSupport.cs; _Documentation/NPC Framework/ACIP-04 - Certifications Mentorship and Specialization/ACIP-04_IMPLEMENTATION_AND_ACCEPTANCE.md", "REQUIRED", "NOT_REQUIRED", "REQUIRED", "Concrete behavior + registration + caller + all applicable persistence/network/UI obligations + failure/replay handling + traceability must pass", "Concrete ACIP-04 implementation with persistence, lifecycle, administration, failure/replay handling and direct profession consumers."),
            new RebirthNpcRequirementDefinition("NPC-REQ-124", "NPC Progression", "Modifier evaluation and AI integration", "ACIP-02", RebirthNpcRequirementStatus.IMPLEMENTED, "Progression §§35,47", "No corresponding concrete progression service/domain found under Scripts/Rebirth/NPC.", "NOT_REQUIRED", "NOT_REQUIRED", "NOT_REQUIRED", "Concrete behavior + registration + caller + all applicable persistence/network/UI obligations + failure/replay handling + traceability must pass", "The generic work progression-event bus and settlement skill dictionary are integration seams only; no sink implements these mechanics."),
            new RebirthNpcRequirementDefinition("NPC-REQ-125", "NPC Progression", "Progression replication and binary serialization", "ACIP-05", RebirthNpcRequirementStatus.IMPLEMENTED, "Progression §§30–31,49", "Scripts/Rebirth/NPC/Progression/RebirthNpcProgressionReplication.cs; Scripts/Rebirth/NPC/Foundation/RebirthNpcLifecycle.cs; BuildScripts/NPC/Invoke-RebirthNpcAcip05Qualification.py", "NOT_REQUIRED", "REQUIRED", "NOT_REQUIRED", "Concrete behavior + registration + caller + all applicable persistence/network/UI obligations + failure/replay handling + traceability must pass", "The generic work progression-event bus and settlement skill dictionary are integration seams only; no sink implements these mechanics."),
            new RebirthNpcRequirementDefinition("NPC-REQ-126", "NPC Progression", "Progression UI and player-facing observability", "ACIP-05", RebirthNpcRequirementStatus.IMPLEMENTED, "Progression §§8.15,12.4,48", "Scripts/Rebirth/NPC/Progression/RebirthNpcProgressionXUi.cs; Config/XUi_InGame/xui.xml; Config/XUi_InGame/windows.xml; BuildScripts/NPC/Invoke-RebirthNpcAcip05Qualification.py", "NOT_REQUIRED", "NOT_REQUIRED", "REQUIRED", "Concrete behavior + registration + caller + all applicable persistence/network/UI obligations + failure/replay handling + traceability must pass", "The generic work progression-event bus and settlement skill dictionary are integration seams only; no sink implements these mechanics."),
            new RebirthNpcRequirementDefinition("NPC-REQ-127", "NPC Progression", "Progression diagnostics, telemetry and administration", "ACIP-05", RebirthNpcRequirementStatus.IMPLEMENTED, "Progression §§12,27,41–42,51–52", "Scripts/Rebirth/NPC/Progression/RebirthNpcProgressionAdministration.cs; Scripts/Rebirth/NPC/Progression/RebirthNpcProgressionReplication.cs; Scripts/Rebirth/NPC/Administration/RebirthNpcAdministrationSupport.cs; BuildScripts/NPC/Invoke-RebirthNpcAcip05Qualification.py", "NOT_REQUIRED", "NOT_REQUIRED", "REQUIRED", "Concrete behavior + registration + caller + all applicable persistence/network/UI obligations + failure/replay handling + traceability must pass", "The generic work progression-event bus and settlement skill dictionary are integration seams only; no sink implements these mechanics.")
    };
    public static RebirthNpcRequirementDefinition[] GetAll() { return (RebirthNpcRequirementDefinition[])Definitions.Clone(); }
    public static RebirthNpcRequirementDefinition[] GetByPackage(string packageId) { List<RebirthNpcRequirementDefinition> result=new List<RebirthNpcRequirementDefinition>(); for(int i=0;i<Definitions.Length;i++) if(string.Equals(Definitions[i].PackageId,packageId,StringComparison.OrdinalIgnoreCase)) result.Add(Definitions[i]); return result.ToArray(); }
    public static RebirthNpcRequirementDefinition Find(string id) { for(int i=0;i<Definitions.Length;i++) if(string.Equals(Definitions[i].Id,id,StringComparison.OrdinalIgnoreCase)) return Definitions[i]; return null; }
    public static int Count { get { return Definitions.Length; } }
}

public static class RebirthNpcConformanceControlPlane
{
    private static long runs,passes,failures;
    public static RebirthNpcConformanceReport Run(string packageId)
    {
        Interlocked.Increment(ref runs);
        string id=string.IsNullOrEmpty(packageId)?"ACIP-00":packageId.Trim().ToUpperInvariant();
        RebirthNpcRequirementDefinition[] assigned=RebirthNpcRequirementCatalogue.GetByPackage(id);
        List<RebirthNpcConformanceGateResult> gates=new List<RebirthNpcConformanceGateResult>();
        Add(gates,"catalogueCount",RebirthNpcRequirementCatalogue.Count==127,"count="+RebirthNpcRequirementCatalogue.Count+" expected=127");
        Add(gates,"stableIds",ValidateStableIds(),"unique immutable NPC-REQ-### IDs");
        Add(gates,"packageAssignment",assigned.Length>0,"assigned="+assigned.Length);
        Add(gates,"completionPredicates",AllPredicatesPresent(assigned),"all assigned rows have explicit predicates");
        Add(gates,"traceabilityEvidence",AllEvidencePresent(assigned),"all assigned rows have source/caller evidence");
        RebirthNpcLifecycleSnapshot life=RebirthNpcLifecycle.GetSnapshot();
        Add(gates,"runtimeRegistration",Contains(life.RegisteredServices,typeof(RebirthNpcConformanceControlPlane).FullName),"lifecycle service registration");
        Add(gates,"callerRegistration",Contains(life.RegisteredServices,typeof(RebirthNpcRequirementCatalogue).FullName),"catalogue registered and callable through rbnpc conformance");
        Add(gates,"placeholderRejection",NoPlaceholderOnlyPass(assigned),"partial/missing rows cannot pass");
        bool pass=true; for(int i=0;i<gates.Count;i++) if(!gates[i].Passed){pass=false;break;}
        if(pass) Interlocked.Increment(ref passes); else Interlocked.Increment(ref failures);
        return new RebirthNpcConformanceReport { PackageId=id, Passed=pass, RequirementCount=assigned.Length, Gates=gates.ToArray() };
    }
    public static string GetReport(string packageId) { return Run(packageId).ToReport()+"\n"+GetCounters(); }
    public static string GetCounters() { return "runs="+Interlocked.Read(ref runs)+" passes="+Interlocked.Read(ref passes)+" failures="+Interlocked.Read(ref failures); }
    private static void Add(List<RebirthNpcConformanceGateResult> list,string gate,bool pass,string detail){list.Add(new RebirthNpcConformanceGateResult{Gate=gate,Passed=pass,Detail=detail});}
    private static bool ValidateStableIds(){HashSet<string> ids=new HashSet<string>(StringComparer.Ordinal);RebirthNpcRequirementDefinition[] all=RebirthNpcRequirementCatalogue.GetAll();for(int i=0;i<all.Length;i++){if(!ids.Add(all[i].Id)||all[i].Id!="NPC-REQ-"+(i+1).ToString("000"))return false;}return true;}
    private static bool AllPredicatesPresent(RebirthNpcRequirementDefinition[] values){for(int i=0;i<values.Length;i++)if(string.IsNullOrWhiteSpace(values[i].CompletionPredicate))return false;return true;}
    private static bool AllEvidencePresent(RebirthNpcRequirementDefinition[] values){for(int i=0;i<values.Length;i++)if(string.IsNullOrWhiteSpace(values[i].Evidence))return false;return true;}
    private static bool NoPlaceholderOnlyPass(RebirthNpcRequirementDefinition[] values){for(int i=0;i<values.Length;i++)if(values[i].Status!=RebirthNpcRequirementStatus.IMPLEMENTED)return false;return true;}
    private static bool Contains(string[] values,string expected){if(values==null)return false;for(int i=0;i<values.Length;i++)if(string.Equals(values[i],expected,StringComparison.Ordinal))return true;return false;}
}
