#!/usr/bin/env python3
from pathlib import Path
import sys,re,csv,xml.etree.ElementTree as ET
root=Path(sys.argv[1] if len(sys.argv)>1 else '.').resolve(); passed=failed=0

def ck(name,cond):
 global passed,failed
 if cond: passed+=1; print('PASS',name)
 else: failed+=1; print('FAIL',name)
def txt(rel): return (root/rel).read_text(encoding='utf-8',errors='replace')
def balanced(rel):
 s=txt(rel); return s.count('{')==s.count('}') and s.count('(')==s.count(')') and s.count('[')==s.count(']')

prog=ET.parse(root/'Config/_Survivor/progression.xml').getroot(); skills={x.get('id'):x for x in prog.find('skills')}; know={x.get('id'):x for x in prog.find('knowledge')}
bg=ET.parse(root/'Config/_Survivor/backgrounds.xml').getroot(); bartender=bg.find("./background[@id='background.bartender']")
cap=ET.parse(root/'Config/_Survivor/capabilities.xml').getroot(); craft=ET.parse(root/'Config/_Survivor/crafting_progression.xml').getroot(); rk=ET.parse(root/'Config/_Survivor/recipe_knowledge.xml').getroot()
bon=ET.parse(root/'Config/_Survivor/background_bonuses.xml').getroot(); mix=bon.find("./bonus[@id='background_bonus.master_mixologist']")
svc=txt('Scripts/Survivor/Backgrounds/RebirthDrinkPreparationSignatureService.cs'); net=txt('Scripts/Survivor/Backgrounds/RebirthDrinkPreparationSignatureNetPackages.cs')
met=txt('Scripts/Metabolism/RebirthMetabolismService.cs'); models=txt('Scripts/Metabolism/RebirthMetabolismModels.cs'); repo=txt('Scripts/Metabolism/RebirthMetabolismStateRepository.cs')
buffs=txt('Config/_Metabolism/buffs.xml'); craftsvc=txt('Scripts/Survivor/Progression/RebirthServiceCraftSkillService.cs'); inst=txt('Scripts/Survivor/Progression/RebirthSurvivorProgressionInstaller.cs'); dbg=txt('Scripts/Survivor/Debug/ConsoleCmdRebirthSurvivor.cs')

# Skill/data/UI
s=skills.get('skill.drink_preparation'); ck('Drink Preparation skill exists',s is not None); ck('Drink Preparation signed runtime bounds',s is not None and s.get('min')=='-50' and s.get('max')=='100'); ck('Drink Preparation completed-craft LBD source',s is not None and 'completed applicable prepared-drink recipes' in (s.get('lbd_source') or ''))
loc=txt('Config/Localization.csv'); ck('Drink Preparation localized','xuiRebirthSkillDrinkPreparation,Drink Preparation' in loc and 'xuiRebirthSkillSourceDrinkPreparation,' in loc); ck('Drink Preparation icon exists',(root/'UIAtlases/RebirthSurvivorIcons/rb_skill_drink_preparation.png').is_file())
ck('beverage Knowledge points to Drink Preparation',know['recipebook.cooking.beverages'].get('associated_skills')=='skill.drink_preparation'); ck('basics Knowledge relates Cooking and Drink Preparation','skill.drink_preparation' in know['recipebook.cooking.basics'].get('associated_skills','') and 'skill.cooking' in know['recipebook.cooking.basics'].get('associated_skills',''))
# Bartender preserved budget (40 positive starting skill, 55 skill-knowledge)
starts={x.get('id'):float(x.get('value')) for x in bartender.find('starting_skills')}; sk={x.get('id'):float(x.get('value')) for x in bartender.find('starting_skill_knowledge')}
ck('Bartender primary Drink Preparation bias',starts.get('skill.drink_preparation')==25 and starts.get('skill.bartering')==15 and 'skill.cooking' not in starts); ck('Bartender weaknesses unchanged',starts.get('skill.construction')==-10 and starts.get('skill.medicine')==-5); ck('Bartender positive starting-skill budget preserved',sum(v for v in starts.values() if v>0)==40); ck('Bartender knowledge bias includes Drink Preparation',sk.get('skill.drink_preparation')==30 and sk.get('skill.bartering')==20 and sk.get('skill.cooking')==5); ck('Bartender skill-knowledge positive budget preserved',sum(v for v in sk.values() if v>0)==55); ck('Bartender starts beverage Knowledge',bartender.find("./starting_knowledge/knowledge[@id='recipebook.cooking.beverages']") is not None)
# Recipe authority
capdr=[x for x in cap.findall('capability') if (x.get('target_id') or '').lower().startswith('drink')]; ck('12 gated drink capabilities audited',len(capdr)==12); ck('all gated drink capabilities use Drink Preparation',all(x.find("./requires_all/skill[@id='skill.drink_preparation']") is not None for x in capdr)); ck('no gated drink capability still Cooking',all(x.find("./requires_all/skill[@id='skill.cooking']") is None for x in capdr));
craftdr=[x for x in craft.findall('./recipes/recipe') if (x.get('id') or '').lower().startswith('drink') and x.get('policy')=='gated']; ck('12 gated drink progression rows',len(craftdr)==12); ck('all gated drink progression rows primary Drink Preparation',all(x.get('primary_skill')=='skill.drink_preparation' for x in craftdr)); boiled=craft.find("./recipes/recipe[@id='drinkJarBoiledWater']"); ck('boiled water remains universal',boiled is not None and boiled.get('policy')=='universal'); rkdr=[x for x in rk.findall('recipe') if (x.get('name') or '').lower().startswith('drink')]; ck('drink recipe Knowledge categorized Drink Preparation',all(x.get('category')=='drink_preparation' for x in rkdr))
ck('service craft SkillIds includes Drink Preparation','"skill.drink_preparation"' in craftsvc.split('private static readonly string[] SkillIds',1)[1].split(';',1)[0]); ck('compat drink heuristic maps to Drink Preparation','Contains(outputName,"drink")' in craftsvc and 'return "skill.drink_preparation"' in craftsvc)
# Bonus tuning and profiles
mt=mix.find("./tuning[@key='special_effect_duration_multiplier']") if mix is not None else None; ck('Master Mixologist locked 2x',mt is not None and mt.get('value')=='2' and mt.get('locked')=='true'); ck('Chunk K service installed','RebirthDrinkPreparationSignatureService.Install(HarmonyInstance)' in inst); ck('four nonduplicated migrated profiles',svc.count('new RebirthPreparedDrinkProfile(')==4); ck('Beer 60 to 360 profile','"drinkJarBeer"' in svc and '60f,360f' in svc); ck('Red Tea 300 to 600 profile','"drinkJarRedTea"' in svc and '300f,600f' in svc); ck('Goldenrod 300 to 600 profile','"drinkJarGoldenRodTea"' in svc and '300f,600f' in svc); ck('Yucca 300 to 600 profile','"drinkJarYuccaJuice"' in svc and '300f,600f' in svc); ck('skill duration interpolation uses 0..100','Mathf.Lerp(profile.SkillZeroDurationSeconds,profile.SkillHundredDurationSeconds,skill/100f)' in svc); ck('Bartender multiplies final duration','if(bartender)duration*=' in svc and 'special_effect_duration_multiplier' in svc)
# Provenance / handoff / multiplayer
ck('prepared drink provenance kind', 'PreparedDrinkKind="prepared_drink"' in svc); ck('provenance stores creator','CreatorStableId=author.StablePlayerId' in svc); ck('provenance stores author background','BackgroundId=author.BackgroundId' in svc); ck('provenance stores Bartender bonus only when owned','BonusId=bartender?MasterMixologistBonusId:string.Empty' in svc); ck('provenance stores Drink Preparation skill/value','SkillId=SkillId,SkillValue=skill' in svc); ck('provenance stores absolute final duration','Workmanship=Mathf.Clamp(duration' in svc); ck('duration reader consumes item provenance','RebirthItemProvenanceAdapter.TryRead(item,out p)' in svc and 'p.Workmanship' in svc); ck('stack compatibility remains shared provenance authority','RebirthItemProvenanceAdapter.Stamp(item' in svc and 'RebirthProvenanceItemStackPatch' in txt('Scripts/Survivor/Provenance/RebirthItemProvenanceAdapter.cs')); ck('metabolism drinks remain single-stack',txt('Config/_Metabolism/items.xml').count("property[@name='Stacknumber']/@value\">1</set>")>=12)
ck('client request ToServer','NetPackageRebirthPreparedDrinkCraftRequest' in net and 'NetPackageDirection.ToServer' in net); ck('server request sender-bound','ValidEntityIdForSender(playerId)' in net); ck('server revalidates recipe output','recipe.itemValueType!=itemType' in svc); ck('server revalidates Drink Preparation classifier','ClassifyRecipe(recipe),SkillId' in svc); ck('pending requests expire','PendingSeconds=120.0' in svc and 'CreatedUtc<cutoff' in svc); ck('server correction ToClient','NetPackageRebirthPreparedDrinkCraftCorrection' in net and 'NetPackageDirection.ToClient' in net); ck('correction routes exact item seed and quality','v.Seed!=corrected.Seed||v.Quality!=corrected.Quality' in svc)
# Digestion onset and save continuity
ck('ingestion stores prepared drink duration','PreparedDrinkSpecialEffectDurationSeconds' in models); ck('ingestion stores activation latch','PreparedDrinkSpecialEffectActivated' in models); ck('fluid consumption snapshots item duration','GetPreparedSpecialEffectDurationSeconds(stack.itemValue)' in met); ck('duration persisted','preparedDrinkEffectSeconds' in repo); ck('activation latch persisted','preparedDrinkEffectActivated' in repo); ck('legacy saves default no prepared drink duration','AF(x, "preparedDrinkEffectSeconds", 0f)' in repo); ck('special effect begins inside intestinal absorption',met.find('TryActivateSpecialEffect(player, entry.SourceItemName')>met.find('ProcessIntestinalFluidAbsorption')); ck('activation requires actual absorbed volume','if (absorbed > 0.001f && !entry.PreparedDrinkSpecialEffectActivated' in met); ck('activation one-shot latch','!entry.PreparedDrinkSpecialEffectActivated' in met and 'entry.PreparedDrinkSpecialEffectActivated = true' in met); ck('no special activation at drink button path','TryActivateSpecialEffect' not in met[met.find('public static RebirthConsumeResult ConsumeAt'):met.find('private static RebirthConsumeResult Fail') if 'private static RebirthConsumeResult Fail' in met else met.find('ProcessIntestinalFluidAbsorption')]); ck('native/current preserved effects remain','FirePreservedUseEffects(player, stack.itemValue, true)' in met); ck('Heavy Drinker/Caffeine support remains separate','RebirthTraitSupportService.TryApplyFromItem(player, def.ItemName, "trait-support-metabolism-drink")' in met); ck('migrated duration has no Iron Gut dependency','iron_gut' not in svc.lower() and 'slowmetabolism' not in svc.lower().replace('old slow metabolism','')); ck('consumer background not consulted at activation','HasBonus(consumer' not in svc and 'TryActivateSpecialEffect(EntityPlayer consumer' in svc)
# Buff identity values
ck('Beer physical resistance +15','buffRebirthPreparedBeerPainResistance' in buffs and 'PhysicalDamageResist" operation="base_add" value="15"' in buffs); ck('Red Tea mobility restored','buffRebirthPreparedRedTeaMobility' in buffs and 'CarryCapacity" operation="base_add" value="15"' in buffs and buffs.count('operation="perc_add" value="0.5"')>=2); ck('Goldenrod mining identity restored','buffRebirthPreparedGoldenrodMining' in buffs and 'tags="stone"' in buffs and 'tags="metal"' in buffs and 'tags="miningTool"' in buffs); ck('Yucca field-work identity restored without duplicate cooling','buffRebirthPreparedYuccaWork' in buffs and 'tags="earth,wood"' in buffs and 'HyperthermalResist' not in buffs[buffs.find('buffRebirthPreparedYuccaWork'):]); ck('Coffee duplicate buff not added','buffRebirthPreparedCoffee' not in buffs and '"drinkJarCoffee",new RebirthPreparedDrinkProfile' not in svc)
# Debug/Base isolation
ck('Chunk K debug command','chunkkbonus' in dbg and 'ExecuteChunkKBonus' in dbg); ck('Chunk K vectors exposed','RebirthDrinkPreparationSignatureService.RunVectors()' in dbg); ck('service Rebirth-only gates',svc.count('RebirthSurvivorMode.IsEnabledForCurrentWorld()')>=4); ck('activation server-only','consumer.world.IsRemote()' in svc); ck('PC013 compatibility allows later normal Skills',"45+ skills (later approved normal Skills allowed)" in txt('BuildScripts/Progression/validate_advanced_disciplines_pc013.py'))
# Documentation/migration evidence
audit=txt('_Documentation/ProjectChanges/REBIRTH_3_0_BACKGROUND_SIGNATURE_BONUSES_PC024_CHUNK_K_SOURCE_AUDIT_20260902.md')
matrix=txt('_Documentation/ProjectChanges/REBIRTH_3_0_BACKGROUND_SIGNATURE_BONUSES_PC024_CHUNK_K_DRINK_MIGRATION_MATRIX_20260902.csv')
pc=txt('_Documentation/ProjectChanges/REBIRTH_3_0_PROJECT_CHANGE_BACKGROUND_SIGNATURE_BONUSES_PC024_CHUNK_K_DRINK_PREPARATION_BARTENDER_20260902.md')
ck('source audit names all five legacy custom families',all(x in audit for x in ['FuriousRamsayStaminaBoostCoffee','FuriousRamsayPainResistanceBoostBeer','FuriousRamsayMobilityBoostRedTea','FuriousRamsayBlockDamageBoostGoldenRodTea','FuriousRamsayEarthDamageBoostYuccaJuice']))
ck('migration matrix covers complete current drink roster',matrix.count('\n"drink')>=14)
ck('migration matrix records Coffee dedup','"drinkJarCoffee"' in matrix and 'DO_NOT_DUPLICATE' in matrix)
ck('migration matrix records Yucca partial dedup','"drinkJarYuccaJuice"' in matrix and 'PORT_PARTIAL_DEDUP' in matrix)
ck('project change documents schema 8 to 9','schema 8 → 9' in pc)
ck('project change records runtime acceptance pending','compile/live acceptance pending' in pc)

# Localization duplication
rows=list(csv.reader((root/'Config/Localization.csv').open(encoding='utf-8-sig'))); keys=[r[0].strip() for r in rows[1:] if r and r[0].strip()]; ck('localization duplicate keys zero',len(keys)==len(set(keys)))
# XML / delimiter
xmls=list(root.rglob('*.xml')); bad=[]
for p in xmls:
 try: ET.parse(p)
 except Exception as e: bad.append(str(p.relative_to(root)))
ck('all project XML parses',not bad)
for rel in ['Scripts/Survivor/Backgrounds/RebirthDrinkPreparationSignatureService.cs','Scripts/Survivor/Backgrounds/RebirthDrinkPreparationSignatureNetPackages.cs','Scripts/Metabolism/RebirthMetabolismModels.cs','Scripts/Metabolism/RebirthMetabolismStateRepository.cs','Scripts/Metabolism/RebirthMetabolismService.cs','Scripts/Survivor/Progression/RebirthServiceCraftSkillService.cs','Scripts/Survivor/Progression/RebirthSurvivorProgressionInstaller.cs','Scripts/Survivor/Debug/ConsoleCmdRebirthSurvivor.cs']:
 ck('delimiter '+Path(rel).name,balanced(rel))
print(f'PC024_STATIC_CHECKS={passed+failed} PASSED={passed} FAILED={failed} XML={len(xmls)}')
sys.exit(1 if failed else 0)
