using System;using System.Collections.Generic;using System.Linq;
class Block{public const int ItemsStartHere=1000;}
class ItemClass{public const int ItemsStartHere=1000;public int MaxCount=100;public static ItemClass GetForId(int id)=>new ItemClass();}
class ItemValue{public int type,TextureFullArray;public bool IsShapeHelperBlock;public Dictionary<string,object> Metadata=new Dictionary<string,object>();public ItemValue(int id){type=id;}public ItemValue Clone(){var v=new ItemValue(type){TextureFullArray=TextureFullArray,IsShapeHelperBlock=IsShapeHelperBlock};foreach(var p in Metadata)v.Metadata.Add(p.Key,p.Value);return v;}}
partial class ItemStack{public ItemValue itemValue;public int count;public ItemStack(ItemValue item,int n){itemValue=item;count=n;}public ItemStack Clone()=>new ItemStack(itemValue.Clone(),count);public void Set(ItemValue item,int n){itemValue=item;count=n;}public bool CanStackPartly(ref int n)=>false;}
class CraftCompleteData{public ItemStack CraftedItemStack;}
static class RebirthStationCompletionReceipt{public const string Prefix="receipt.";public class Identity{public int Count;}public static bool TryReadIdentity(CraftCompleteData receipt,out Identity id){id=new Identity{Count=receipt.CraftedItemStack.count};return true;}}
static class RebirthStationGridIngredients{public static bool IsSameStackSnapshot(ItemStack a,ItemStack b)=>a!=null&&b!=null&&a.count==b.count&&a.itemValue.type==b.itemValue.type&&a.itemValue.Metadata.Count==b.itemValue.Metadata.Count&&a.itemValue.Metadata.All(p=>b.itemValue.Metadata.TryGetValue(p.Key,out var v)&&Equals(p.Value,v));}
class Program{
 static void Main(){int checks=0;Action<bool,string>check=(ok,name)=>{if(!ok)throw new Exception(name);checks++;};var output=new ItemValue(1001);var existing=new ItemValue(1001);existing.Metadata["authoredVariant"]="original";var cells=new[]{new ItemStack(existing,2),new ItemStack(new ItemValue(0),0)};var before=cells.Select(s=>s.Clone()).ToArray();var input=new ItemStack(output,1);check(ItemStack.AddToItemStackArray(cells,input,-1)==0&&cells[0].count==3&&cells[0].itemValue.Metadata.ContainsKey("authoredVariant")&&cells[1].count==0,"actual native greedy same-type merge retains different metadata despite free slot");check(!RebirthStationOutputDelta.Matches(before,cells,new CraftCompleteData{CraftedItemStack=new ItemStack(output.Clone(),1)}),"actual post-effect delta refuses already mutated legal native merge");cells=new[]{new ItemStack(new ItemValue(1002),0)};before=cells.Select(s=>s.Clone()).ToArray();check(ItemStack.AddToItemStackArray(cells,new ItemStack(output,1),-1)==0&&cells[0].itemValue.type==1001,"actual native IsEmpty accepts retained zero-count nonempty payload");check(!RebirthStationOutputDelta.Matches(before,cells,new CraftCompleteData{CraftedItemStack=new ItemStack(output.Clone(),1)}),"actual output delta refuses native zero-count replacement after effect");cells=new[]{new ItemStack(new ItemValue(1002),100)};before=cells.Select(s=>s.Clone()).ToArray();check(ItemStack.AddToItemStackArray(cells,new ItemStack(output,1),-1)==-1&&RebirthStationGridIngredients.IsSameStackSnapshot(cells[0],before[0]),"actual full output insertion no effect");Console.WriteLine(checks+" PASS installed extracted stack methods + actual OutputDelta; metadata equality/receipt adapters explicit doubles");}
}
